<div id="<?= /* @escapeNotVerified */ $block->getUniqueId() ?>"
     class="dashboard-form"
     data-mage-init='{
         "itemTable":{
             "addBlockData":{
                 "widgetId": "<?= /* @escapeNotVerified */ $block->getUniqueId() ?>"
             }
         }
     }'
>
    <?php if (!$block->getIsTitleHidden()): ?>
        <h3 class="dashboard-form__title">
            <?= /* @escapeNotVerified */ __('Order by SKU') ?>
        </h3>
    <?php endif ?>

    <div class="dashboard-form__divider">
        <form class="form form-addbysku"
              action="<?= /* @escapeNotVerified */ $block->getFormAction() ?>"
              method="post"
              data-mage-init='{"validation":{}}'
              <?= $block->getIsMultipart() ? 'enctype="multipart/form-data"' : '' ?>
        >
            <div data-container="items"></div>

            <div class="action dashboard__item">
                <div class="action__handler">
                    <button type="button"
                            title="<?= /* @escapeNotVerified */ __('Add Row') ?>"
                            class="button action__button"
                            data-role="add"
                    >
                        <?= /* @escapeNotVerified */ __('Add Row') ?>
                    </button>
                </div>
            </div>

            <?php if ($block->getChildHtml()): ?>
                <?= $block->getChildHtml(); ?>
            <?php endif; ?>

            <div class="action">
                <div class="action__handler">
                    <button type="submit"
                            title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>"
                            class="button action__button"
                    >
                        <?= /* @escapeNotVerified */ __('Add to Cart') ?>
                    </button>
                </div>
            </div>

            <?php if ($block->getLink()): ?>
                <?= /* @escapeNotVerified */ $block->getLink(); ?>
            <?php endif; ?>
        </form>

        <script data-template="add-block" type="text/x-magento-template">
            <div class="fields additional deletableItem dashboard__item"
                 data-mage-init='{"deletableItem":{}}'
            >
                <div class="input dashboard-form__divider sku required">
                    <label for="id-items<%- data.widgetId %><%- data.rowIndex %>sku"
                           class="label"
                    >
                        <?= /* @escapeNotVerified */ __('SKU') ?>
                    </label>

                    <input type="text"
                           class="input__field"
                           name="items[<%- data.rowIndex %>][sku]"
                           placeholder="SKU"
                           id="id-items<%- data.widgetId %><%- data.rowIndex %>sku"
                           data-id="<%- data.widgetId %><%- data.rowIndex %>sku"
                           data-sku="true"
                           aria-required="true"
                           data-validate='{
                               "required-if-all-sku-empty-and-file-not-loaded": {
                                   specifiedId: "#customer_sku_csv",
                                   dataSku: "data-sku"
                               }
                           }'
                    />
                </div>

                <div class="input dashboard-form__divider qty required">
                    <label for="id-items<%- data.widgetId %><%- data.rowIndex %>qty"
                           class="label"
                    >
                        <?= /* @escapeNotVerified */ __('Qty') ?>
                    </label>

                    <input type="number"
                           class="input__field"
                           name="items[<%- data.rowIndex %>][qty]"
                           id="id-items<%- data.widgetId %><%- data.rowIndex %>qty"
                           maxlength="13"
                           placeholder="QTY"
                           aria-required="true"
                           data-validate='{
                               "required-number-if-specified": "[data-id=<%- data.widgetId %><%- data.rowIndex %>sku]",
                               "validate-number": true,
                               "validate-greater-than-zero": true,
                               "validate-number-range": "0.0001-99999999.9999"
                           }'
                    />
                </div>

                <% if (data.rowIndex > 0) { %>
                    <div class="action">
                        <div class="action__handler">
                            <button type="button" class="button action__button remove"
                                    title="<?= /* @escapeNotVerified */ __('Remove Row') ?>"
                                    data-role="delete"
                            >
                                <?= /* @escapeNotVerified */ __('Remove Row') ?>
                            </button>
                        </div>
                    </div>
                <% } %>
            </div>
        </script>
    </div>
</div>
