<?php /** @var \Snowdog\Menu\Block\NodeType\Category $block */ ?>
<?php
    $nodeId = $block->getId();
    $class = $block->getMenuClass();
    $categoryUrl = $block->getCategoryUrl($nodeId);
    $categoryUrl = $categoryUrl ?: '#';
    $dataAttribute = '';
    $isContent = $block->getIsParent();

    $classLink = $block->getIsRoot() ? $class . '__label link--invert' : $class . '__label';
    $title = $block->getTitle();

    if ($nodeId && $isContent) {
        $dataAttribute = ' aria-controls="dropdown-' . $nodeId . '"';
    }

    if ($block->isCurrentCategory($nodeId)) {
        $classLink .= ' current';
    }
?>
<a href="<?= $categoryUrl ?>"
   class="<?= $classLink ?>"<?= $dataAttribute ?>
>
    <?= $title ?>
    <?php if ($block->getIsParent()): ?>
       <?php if ($block->getLevel() == 0): ?>
            <svg title="view more" class="icon <?= $class ?>__icon">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
            </svg>
        <?php else: ?>
            <svg title="view more" class="icon <?= $class ?>__icon <?= $class ?>__icon--inner">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
            </svg>
        <?php endif ?>
    <?php endif ?>
</a>
