<?php /** @var \Snowdog\Menu\Block\NodeType\Category $block */ ?>
<?php
    $nodeId = $block->getId();
    $class = $block->getMenuClass();
    $categoryUrl = $block->getCategoryUrl($nodeId);
    $categoryUrl = $categoryUrl ?: '#';
    $dataAttribute = '';
    $isContent = $block->getIsParent();

    $classLink = $block->getIsRoot() ? $class . '__label link--invert' : $class . '__label';
    $title = $block->getTitle();

    if ($nodeId && $isContent) {
        $dataAttribute = ' aria-controls="dropdown-' . $nodeId . '"';
    }

    if ($block->isCurrentCategory($nodeId)) {
        $classLink .= ' current';
    }
?>
<a
    href="<?= $categoryUrl ?>"
    class="<?= $classLink ?>"
    <?= $dataAttribute ?>
    <?php if ($isContent): ?>
        role="button"
        aria-expanded="false"
    <?php endif; ?>
>
    <?= $title ?>
    <?php if ($isContent): ?>
        <svg
            class="
                icon
                <?= $class ?>__icon
                <?= ($block->getLevel() > 0) ? $class . '__icon--inner' : '' ?>
            "
            role="presentation"
            focusable="false"
        >
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-down')) ?>"></use>
        </svg>
    <?php endif ?>
</a>
