<?php /** @var \Snowdog\Menu\Block\NodeType\CmsPage $block */ ?>
<?php
    $nodeId = $block->getId();
    $class = $block->getMenuClass();
    $pageUrl = $block->getPageUrl($nodeId);
    $pageUrl = $pageUrl ?: '#';
    $dataAttribute = '';
    $isContent = $block->getIsParent();

    $classLink = $block->getIsRoot() ? $class . '__label link--invert' : $class . '__inner-label';
    $title = $block->getTitle();

    if ($nodeId && $isContent) {
        $dataAttribute = ' aria-controls="dropdown-' . $nodeId . '"';
    }

    if ($block->isCurrentPage($nodeId)) {
        $classLink .= ' current';
    }

?>
<a
    href="<?= $pageUrl ?>"
    class="<?= $classLink ?>"
    <?= $dataAttribute ?>
>
    <?= $title ?>
    <?php if ($block->getIsParent()): ?>
        <svg
            class="
                icon
                <?= $class ?>__icon
                <?= ($block->getLevel() > 0) ? $class . '__icon--inner' : '' ?>
            "
            role="presentation"
            focusable="false"
        >
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-down')) ?>"></use>
        </svg>
    <?php endif ?>
</a>
