<?php /** @var \Snowdog\Menu\Block\NodeType\CmsPage $block */ ?>
<?php
    $nodeId = $block->getId();
    $class = $block->getMenuClass();
    $pageUrl = $block->getPageUrl($nodeId);
    $pageUrl = $pageUrl ?: '#';
    $dataAttribute = '';
    $isContent = $block->getIsParent();
    $isViewAllLink = $block->getIsViewAllLink();

    if ($isViewAllLink) {
        $title = __('View All');
        $classLink = $class . '__label link--invert';
    } else {
        $classLink = $block->getIsRoot() ? $class . '__label link--invert' : $class . '__label';
        $title = $block->getTitle();

        if ($nodeId && $isContent) {
            $dataAttribute = ' aria-controls="dropdown-' . $nodeId . '"';
        }

        if ($block->isCurrentPage($nodeId)) {
            $classLink .= ' current';
        }
    }
?>
<a
    href="<?= $block->escapeUrl($pageUrl) ?>"
    class="<?= $block->escapeHtmlAttr($classLink) ?>"
    <?= /* @noEscape */ $dataAttribute ?>
    <?php if ($isContent && !$isViewAllLink): ?>
        role="button"
        aria-expanded="false"
    <?php endif; ?>
>
    <?= $block->escapeHtml($title) ?>
    <?php if ($isContent && !$isViewAllLink): ?>
        <svg
            class="
                icon
                <?= $block->escapeHtmlAttr($class) ?>__icon
                <?= ($block->getLevel() > 0) ? $block->escapeHtmlAttr($class) . '__icon--inner' : '' ?>
            "
            role="presentation"
            focusable="false"
        >
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-down')) ?>"></use>
        </svg>
    <?php endif ?>
</a>
