<?php /** @var \Snowdog\Menu\Block\NodeType\CustomUrl $block */ ?>
<?php
    $attributes = [];
    $class = $block->getMenuClass();
    $classLink = $block->getIsRoot() ? $class . '__label link--invert' : $class . '__inner-label';
    $title = $block->getTitle();
    $isContent = $block->getIsParent();

    if ($block->getId() && $isContent) {
        $attributes[] = 'aria-controls="dropdown-' . $block->getId() . '"';
    }

    $attributes[] = 'class="' . $classLink . '"';

    if ($block->getTarget()) {
        $attributes[] = 'target="__blank" rel="noopener"';
    }
?>
<a
    href="<?= $block->getContent() ?>"
    <?= implode(' ', $attributes) ?>
>
    <?= $title ?>
    <?php if ($block->getIsParent()): ?>
        <svg
            class="
                icon
                <?= $class ?>__icon
                <?= ($block->getLevel() > 0) ? $class . '__icon--inner' : '' ?>
            "
            role="presentation"
            focusable="false"
        >
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-down')) ?>"></use>
        </svg>
    <?php endif ?>
</a>
