<?php
/**
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 */

?>
<?php if ($block->getCurrencyCount() > 1) : ?>
    <?php $currencies = $block->getCurrencies(); ?>
    <?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div 
        class="
            dropdown-list
            dropdown-list--detailed-content
            footer__dropdown-switcher
        "
        data-mage-init='{ "dropdownList": {} }'
        id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>"
    >
        <div 
            class="
                actions 
                dropdown 
                options 
                switcher-options
            "
        >
            <ul class="dropdown-list__list">
                <li
                    class="
                        dropdown-list__item
                        dropdown-list__item--collapse
                    "
                >
                    <button
                        class="dropdown-list__label"
                        aria-expanded="false"
                        aria-controls="dropdown-currency-content"
                    >
                        <?= $block->escapeHtml($currentCurrencyCode) ?> - <?= $currencies[$currentCurrencyCode] ?
                            $block->escapeHtml($currencies[$currentCurrencyCode]) : ''
                        ?>
                        <svg
                            class="
                                icon 
                                dropdown-list__icon
                            "
                            aria-hidden="true"
                            role="img"
                        >
                            <title><?= __('Arrow Down'); ?></title>
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-down')) ?>"></use>
                        </svg>
                    </button>

                    <div
                        id="dropdown-currency-content"
                        class="dropdown-list__content"
                        aria-hidden="true"
                    >
                        <ul class="list">
                            <?php foreach ($currencies as $_code => $_name) : ?>
                                <?php if ($_code != $currentCurrencyCode) : ?>
                                    <li 
                                        class="
                                            list__item
                                            currency-<?= $block->escapeHtmlAttr($_code) ?> 
                                            switcher-option
                                        "
                                    >
                                        <a 
                                            href="#" 
                                            data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'
                                            title="<?= $block->escapeHtmlAttr($_code) ?> - <?= $block->escapeHtmlAttr($_name) ?>"
                                            class="link"
                                        >
                                            <?= $block->escapeHtml($_code) ?> - <?= $block->escapeHtml($_name) ?>
                                        </a>
                                    </li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
<?php endif; ?>
