<?php
/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="block dropdown-container dropdown-container--open-wide"
     data-mage-init='{"dropdownContainer": {}}'
>
    <h2 class="dropdown-container__label heading heading--fourth-level" >
        <?php /* @escapeNotVerified */ echo __('My Account'); ?>
        <svg class="dropdown-container__icon"
             title="account navigation toggle"
        >
               <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#arrow-down'); ?>"></use>
        </svg>
    </h2>
    <nav class="account-nav dropdown-container__content" aria-label="account navigation">
        <ul class="nav items account-nav__list">
            <?php echo $block->getChildHtml();?>
        </ul>
    </nav>
</div>
