<div class="dashboard-nav" data-mage-init='{ "dashboardNav": {} }'>
    <div class="dashboard-nav__mobile">
        <?= /* @escapeNotVerified */ __('Account Dashboard'); ?>
    </div>

    <div class="dashboard-nav__content">
        <h3 class="dashboard-nav__title">
            <?= /* @escapeNotVerified */ __('My Account'); ?>
        </h3>

        <?= /* @escapeNotVerified */ $block->getChildHtml(); ?>
    </div>
</div>
