<?php
/** @var \Magento\Msrp\Block\Popup $block */
?>
<?php if ($block->isEnabled()) : ?>
    <script data-role="msrp-popup-template" type="text/x-magento-template">
    <div id="map-popup-click-for-price" class="map-popup display-none">
        <div class="popup-header">
            <strong class="title" id="map-popup-heading-price"></strong>
        </div>
        <div class="popup-content">
            <div class="map-info-price" id="map-popup-content">
                <div class="price-box">
                    <div class="map-msrp" id="map-popup-msrp-box">
                        <span class="label"><?= $block->escapeHtml(__('Price')) ?></span>
                        <span class="old-price map-old-price price__value price__value--old" id="map-popup-msrp">
                            <span class="price"></span>
                        </span>
                    </div>
                    <div class="map-price" id="map-popup-price-box">
                        <span class="label"><?= $block->escapeHtml(__('Actual Price')) ?></span>
                        <span id="map-popup-price" class="actual-price price__value"></span>
                    </div>
                </div>
            </div>
            <div class="map-text" id="map-popup-text">
                <?= /* @noEscape */ $block->getExplanationMessage() ?>
            </div>
            <form action="" method="POST" class="map-form-addtocart">
                <input type="hidden" name="product" class="product_id" value="" />
                <button type="button"
                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                        class="button action tocart primary">
                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                </button>
                <div class="additional-addtocart-box">
                    <?= $block->getChildHtml() ?>
                </div>
            </form>
        </div>
    </div>
    </script>
    <script data-role="msrp-info-template" type="text/x-magento-template">
    <div id="map-popup-what-this" class="map-popup display-none">
        <div class="popup-header">
            <strong class="title" id="map-popup-heading-what-this"></strong>
        </div>
        <div class="popup-content">
            <div class="map-help-text" id="map-popup-text-what-this">
                <?= /* @noEscape */ $block->getExplanationMessageWhatsThis() ?>
            </div>
        </div>
    </div>
    </script>
<?php endif; ?>
