<?php
/** @var \Magento\Msrp\Block\Popup $block */
?>
<?php if ($block->isEnabled()) : ?>
    <script data-role="msrp-popup-template" type="text/x-magento-template">
        <div
            id="map-popup-click-for-price"
            class="map-popup display-none"
        >
            <div class="modal__content">
                <div class="modal__top">
                    <div class="popup-header">
                        <strong
                            class="title"
                            id="map-popup-heading-price"
                        ></strong>
                    </div>
                    <h3
                        class="
                            modal__heading
                            heading
                            heading--third-level
                        "
                        id="myTitle"
                    >
                        <?= $block->escapeHtml(__('Product Price')) ?>
                    </h3>
                </div>

                <div class="modal__middle">
                    <div class="popup-content">
                        <div
                            class="map-info-price margin-bottom-m"
                            id="map-popup-content"
                        >
                            <div class="price-box">
                                <div
                                    class="map-msrp margin-bottom-xs"
                                    id="map-popup-msrp-box"
                                >
                                    <span class="label">
                                        <?= $block->escapeHtml(__('Price:')) ?>
                                    </span>
                                    <span
                                        class="
                                            old-price
                                            map-old-price
                                            price__value
                                            price__value--old
                                        "
                                        id="map-popup-msrp"
                                    >
                                        <span class="price"></span>
                                    </span>
                                </div>
                                <div
                                    class="map-price"
                                    id="map-popup-price-box"
                                >
                                    <span class="label">
                                        <?= $block->escapeHtml(__('Actual Price:')) ?>
                                    </span>
                                    <span
                                        id="map-popup-price"
                                        class="actual-price price__value"
                                    ></span>
                                </div>
                            </div>
                        </div>
                        <p
                            class="map-text margin-0"
                            id="map-popup-text"
                        >
                            <?= /* @noEscape */ $block->getExplanationMessage() ?>
                        </p>
                    </div>
                </div>

                <div class="modal__bottom msrp__modal-bottom">
                    <button
                        type="button"
                        title="<?= $block->escapeHtmlAttr(__('Cancel')) ?>"
                        class="
                            button
                            button--secondary
                            msrp__cancel-button
                        "
                    >
                        <?= $block->escapeHtml(__('Cancel')) ?>
                    </button>
                    <form
                        action=""
                        method="POST"
                        class="map-form-addtocart"
                    >
                        <input
                            type="hidden"
                            name="product"
                            class="product_id"
                            value=""
                        />
                        <button
                            type="button"
                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                            class="
                                button
                                action
                                tocart
                                primary
                                msrp__tocart-button
                                margin-left-m
                            "
                        >
                            <?= $block->escapeHtml(__('Add to Cart')) ?>
                        </button>
                    </form>
                    <?php if (!empty($block->getChildHtml())): ?>
                        <div class="additional-addtocart-box msrp__additional-addtocart-box">
                            <?= $block->getChildHtml() ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </script>
    <script data-role="msrp-info-template" type="text/x-magento-template">
        <div
            id="map-popup-what-this"
            class="map-popup display-none"
        >
            <div class="popup-header">
                <strong
                    class="title"
                    id="map-popup-heading-what-this"
                ></strong>
            </div>
            <div class="popup-content">
                <div
                    class="map-help-text"
                    id="map-popup-text-what-this"
                >
                    <?= /* @noEscape */ $block->getExplanationMessageWhatsThis() ?>
                </div>
            </div>
        </div>
    </script>
<?php endif; ?>
