<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>

<div class="bundle-option">
    <h4
        class="
            bundle-option__title
            <?= ($_option->getRequired()) ? 'bundle-option__title--required': '' ?>
        "
    >
        <?= $block->escapeHtml($_option->getTitle()) ?>
    </h4>
    <?php if ($block->showSingle()): ?>
        <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
        <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
        <input
            type="hidden"
            class="bundle option"
            name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
            value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"
        >
    <?php else: ?>
        <?php foreach($_selections as $_selection): ?>
            <div class="checkbox">
                <input
                    class="checkbox__field bundle option"
                    id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $_selection->getSelectionId() ?>"
                    type="checkbox"
                    <?php if ($_option->getRequired()): ?> 
                        <?= 
                            'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' .
                            $block->escapeHtmlAttr($_option->getId()) . ']&quot;]:checked\'}"' 
                        ?>
                    <?php endif; ?>
                    name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()); ?>][<?= $block->escapeHtmlAttr($_selection->getId()) ?>]"
                    data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>][<?= $block->escapeHtmlAttr($_selection->getId()) ?>]"
                    <?= ($block->isSelected($_selection)) ? ' checked="checked"' : ''; ?>
                    <?= (!$_selection->isSaleable()) ? ' disabled="disabled"' : ''; ?>
                    value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                >
                <svg class="checkbox__icon" title="Checked">
                    <title><?= __('Checked') ?></title>
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                </svg>
                <label
                    class="checkbox__label"
                    for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $_selection->getSelectionId() ?>"
                >
                    <?= $block->getSelectionQtyTitlePrice($_selection) ?>
                    <br/>
                    <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                </label>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
