<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<?php $inputClass = 'checkbox__field bundle option bundle-option-' . $escaper->escapeHtmlAttr($_option->getId()) ?>
<?php $inputId = 'bundle-option-' . $escaper->escapeHtmlAttr($_option->getId()) ?>
<?php $inputName = 'bundle_option[' . $escaper->escapeHtmlAttr($_option->getId()) . ']' ?>
<?php $dataValidation = 'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' .
    $escaper->escapeHtmlAttr($_option->getId()) . ']&quot;]:checked\'}"' ?>
<div class="bundle-option">
    <h4
        class="
            bundle-option__title
            <?= ($_option->getRequired()) ? 'bundle-option__title--required': '' ?>
        "
    >
        <?= $escaper->escapeHtml($_option->getTitle()) ?>
    </h4>
    <?php if ($block->showSingle()): ?>
        <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
        <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
        <input
            type="hidden"
            class="bundle option"
            name="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
            value="<?= $escaper->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"
        >
    <?php else: ?>
        <?php foreach($_selections as $_selection): ?>
            <?php $sectionId = $_selection->getSelectionId() ?>
            <div class="checkbox">
                <input
                    class="checkbox__field bundle option"
                    id="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>-<?= $_selection->getSelectionId() ?>"
                    type="checkbox"
                    <?php if ($_option->getRequired()): ?>
                        <?=
                            'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' .
                            $escaper->escapeHtmlAttr($_option->getId()) . ']&quot;]:checked\'}"'
                        ?>
                    <?php endif; ?>
                    name="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()); ?>][<?= $escaper->escapeHtmlAttr($_selection->getId()) ?>]"
                    data-selector="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>][<?= $escaper->escapeHtmlAttr($_selection->getId()) ?>]"
                    <?= ($block->isSelected($_selection)) ? ' checked="checked"' : ''; ?>
                    <?= (!$_selection->isSaleable()) ? ' disabled="disabled"' : ''; ?>
                    value="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                >

                <input
                    class="<?=/* @noEscape */ $inputClass ?> change-container-classname"
                    id="<?=/* @noEscape */ $inputId . '-' . $escaper->escapeHtmlAttr($sectionId)?>"
                    type="checkbox"
                   <?php if ($_option->getRequired()): ?>
                        <?= /* @noEscape */ $dataValidation ?>
                   <?php endif;?>
                   name="<?=/* @noEscape */ $inputName .'['. $escaper->escapeHtmlAttr($sectionId)?>]"
                   data-selector="<?= /* @noEscape */ $inputName.'['.$escaper->escapeHtmlAttr($sectionId)?>]"
                    <?php if ($block->isSelected($selection)): ?>
                        <?= 'checked="checked"' ?>
                    <?php endif; ?>
                    <?php if (!$selection->isSaleable()): ?>
                        <?= 'disabled="disabled"' ?>
                    <?php endif; ?>
                    value="<?= $escaper->escapeHtmlAttr($sectionId) ?>"
                    data-errors-message-box="#validation-message-box"
                />

                <svg class="checkbox__icon" title="Checked">
                    <title><?= $escaper->escapeHtml(__('Checked')) ?></title>
                    <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                </svg>
                <label
                    class="checkbox__label"
                    for="<?= /* @noEscape */ $inputId . '-' . $escaper->escapeHtmlAttr($sectionId) ?>"
                >
                    <?= $block->getSelectionQtyTitlePrice($_selection) ?>
                    <br/>
                    <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                </label>
            </div>
        <?php endforeach; ?>
        <div id="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>-container"></div>
        <div id="validation-message-box"></div>
    <?php endif; ?>
</div>
