<?php
/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Multi */
$_option = $block->getOption();
$_optionId = $_option->getId();
$_selections = $_option->getSelections();
?>

<div class="bundle-option">
    <h4
        class="
            bundle-option__title
            <?= ($_option->getRequired()) ? 'bundle-option__title--required': '' ?>
        "
    >
        <?= $block->escapeHtml($_option->getTitle()) ?>
    </h4>
    <?php if ($block->showSingle()): ?>
        <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
        <input
            type="hidden"
            name="bundle_option[<?= $block->escapeHtmlAttr($_optionId) ?>]"
            value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"
            value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"
            class="
                bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>
                bundle
                option
            "
        />
    <?php else: ?>
        <div class="select select--multi">
            <select
                multiple="multiple"
                id="bundle-option-<?= $block->escapeHtmlAttr($_optionId) ?>"
                name="bundle_option[<?= $block->escapeHtmlAttr($_optionId) ?>][]"
                data-selector="bundle_option[<?= $block->escapeHtmlAttr($_optionId) ?>][]"
                class="
                    bundle-option-<?= $block->escapeHtmlAttr($_optionId) ?>
                    select__field
                    padding-0
                    bundle
                    option
                "
                aria-label="<?= $block->escapeHtmlAttr($_option->getTitle()) ?>"
                <?php if ($_option->getRequired()): ?>
                    data-validate="{'required':'true'}" ?>
                <?php endif ?>
            >
                <?php if (!$_option->getRequired()): ?>
                    <option
                        class="padding-hz-m"
                        value=""
                    >
                        <?= $block->escapeHtml(__('None')) ?>
                    </option>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <option
                        title="<?= $block->escapeHtmlAttr($_selection->getName()) ?>"
                        value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                        class="padding-hz-m"
                        <?php if ($block->isSelected($_selection)): ?>
                            selected="selected"
                        <?php endif; ?>
                        <?php if (!$_selection->isSaleable()): ?>
                            disabled="disabled"
                        <?php endif; ?>
                    >
                        <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    <?php endif; ?>
</div>
