<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Multi */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>

<div class="bundle-option">
    <h4
        class="
            bundle-option__title
            <?= ($_option->getRequired()) ? 'bundle-option__title--required': '' ?>
        "
    >
        <?= $block->escapeHtml($_option->getTitle()) ?>
    </h4>
    <?php if ($block->showSingle()): ?>
        <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
        <input
            type="hidden"
            name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()); ?>]"
            value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()); ?>"
        >
    <?php else: ?>
        <select
            multiple="multiple"
            size="5"
            id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()); ?>"
            name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()); ?>][]"
            data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()); ?>][]"
            class="bundle option"
            <?= ($_option->getRequired()) ? 'data-validate={required:true}' : ''; ?>
        >
            <?php if(!$_option->getRequired()): ?>
                <option value="">
                    <?= $block->escapeHtml(__('None')) ?>
                </option>
            <?php endif; ?>
            <?php foreach ($_selections as $_selection): ?>
                <option
                    value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                    <?= ($block->isSelected($_selection)) ? ' selected="selected"' : '' ?>
                    <?= (!$_selection->isSaleable()) ? ' disabled="disabled"' : '' ?>
                >
                    <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selection, false) ?>
                </option>
            <?php endforeach; ?>
        </select>
    <?php endif; ?>
</div>
