<?php
/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select */
$_option                           = $block->getOption();
$_optionId                         = $_option->getId();
$_optionTitle                      = $_option->getTitle();
$_selections                       = $_option->getSelections();
$_default                          = $_option->getDefaultSelection();
list($_defaultQty, $_canChangeQty) = $block->getDefaultValues();
?>

<div class="bundle-option">
    <label
        class="
            bundle-option__title
            <?= ($_option->getRequired()) ? 'bundle-option__title--required': '' ?>
        "
        for="bundle-option-<?= $block->escapeHtmlAttr($_optionId) ?>"
    >
        <?= $block->escapeHtml($_optionTitle) ?>
    </label>
    <?php if ($block->showSingle()): ?>
        <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
        <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
        <input
            id="bundle-option-<?= $block->escapeHtmlAttr($_optionId) ?>"
            type="hidden"
            class="
                bundle-option-<?= $block->escapeHtmlAttr($_optionId) ?>
                bundle
                option
            "
            name="bundle_option[<?= $block->escapeHtmlAttr($_optionId) ?>]"
            value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"
        >
    <?php else: ?>
        <div
            class="
                select
                select--native
                bundle-option__select
            "
        >
            <select
                id="bundle-option-<?= $block->escapeHtmlAttr($_optionId) ?>"
                name="bundle_option[<?= $block->escapeHtmlAttr($_optionId) ?>]"
                data-selector="bundle_option[<?= $block->escapeHtmlAttr($_optionId) ?>]"
                class="
                    bundle-option-<?= $block->escapeHtmlAttr($_optionId) ?>
                    select__field
                    bundle
                    option
                "
                <?php if ($_option->getRequired()): ?>
                    data-validate="{'required': 'true'}"
                    required
                <?php endif ?>
                data-mage-init='{"select": {}}'
            >
                 <option value="">
                     <?= $block->escapeHtml(__('Choose a selection...')) ?>
                </option>
                <?php foreach ($_selections as $_selection): ?>
                    <option
                        title="<?= $block->escapeHtmlAttr($_selection->getName()) ?>"
                        value="<?= $_selection->getSelectionId() ?>"
                        <?php if ($block->isSelected($_selection)): ?>
                            selected="selected"
                        <?php endif ?>
                        <?php if (!$_selection->isSaleable()): ?>
                            disabled="disabled"
                        <?php endif ?>
                    >
                        <?= $block->getSelectionTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    <?php endif; ?>

    <div class="input bundle-option__qty">
        <label
            class="label margin-right-s"
            for="bundle-option-<?= $block->escapeHtmlAttr($_optionId) ?>-qty-input"
        >
            <?= __('Qty') ?>:
        </label>
        <input
            <?php if (!$_canChangeQty): ?>
                disabled="disabled"
            <?php endif ?>
            id="bundle-option-<?= $block->escapeHtmlAttr($_optionId) ?>-qty-input"
            class="input__field bundle-option__qty-input qty"
            type="number"
            name="bundle_option_qty[<?= $block->escapeHtmlAttr($_optionId) ?>]"
            data-selector="bundle_option_qty[<?= $block->escapeHtmlAttr($_optionId) ?>]"
            value="<?= $block->escapeHtmlAttr($_defaultQty) ?>"
            min="0"
        >
    </div>
</div>
