<?php /** @var $block \Magento\Invitation\Block\Form */?>
<?= /* @escapeNotVerified */ $block->getChildHtml('form_before') ?>

<?php $maxPerSend = $block->getMaxInvitationsPerSend(); ?>

<?php if ($maxPerSend): ?>
    <form id="invitationForm"
          action=""
          method="post"
          class="form"
          data-mage-init='{
            "rowBuilder":{
                "rowTemplate":"#add-email-friends-tmpl",
                "rowContainer":"#invitations-options",
                "rowParentElem":"<div></div>",
                "remEventSelector":"button",
                "btnRemoveSelector":".action__button.remove",
                "maxRows":"<?= /* @escapeNotVerified */ $block->getMaxInvitationsPerSend(); ?>",
                "maxRowsMsg":"#max-emails-message",
                "addRowBtn":"#add-email-button",
                "additionalRowClass":"additional"
            },
            "validation":{}
          }'
          data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>"
    >

        <input name="form_key" type="hidden" value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getFormKeyValue()) ?>" />

        <h3 class="dashboard-form__title">
            <?= /* @escapeNotVerified */ __('Invite your friends by entering their email addresses'); ?>
        </h3>

        <div id="invitations-options"></div>

        <?php if ($block->isInvitationMessageAllowed()): ?>
            <div id="max-emails-message" style="display: none;" class="message notice limit" role="alert">
                <?= /* @escapeNotVerified */ __('Maximum %1 email addresses allowed.', $block->getMaxInvitationsPerSend()) ?>
            </div>
        <?php endif; ?>

        <div class="action dashboard-form__divider">
            <div class="action__handler">
                <?php if (1 < $block->getMaxInvitationsPerSend()): ?>
                    <button type="button" id="add-email-button" class="button action__button add">
                        <?= /* @escapeNotVerified */ __('Add') ?>
                    </button>
                <?php endif; ?>
            </div>
        </div>

        <?php if ($block->isInvitationMessageAllowed()): ?>
            <div class="input dashboard-form__divider text">
                <label for="message" class="label">
                    <?= /* @escapeNotVerified */ __('Message'); ?>
                </label>

                <textarea name="message"
                          id="message"
                          title="<?= /* @escapeNotVerified */ __('Message') ?>"
                          placeholder="<?= /* @escapeNotVerified */ __('Message') ?>"
                          class="input__field input__field--textarea"
                          rows="5"
                          cols="5"
                ></textarea>
            </div>
        <?php endif;?>

        <div class="action">
            <?php
                $getCustomerInvitationUrl = $this->helper('Magento\Invitation\Helper\Data')
                                                 ->getCustomerInvitationUrl();
            ?>

            <div class="action__handler">
                <button class="button action__button" type="submit">
                    <?= /* @escapeNotVerified */ __('Send Invitations') ?>
                </button>
            </div>

            <div class="action__handler">
                <a href="<?= /* @escapeNotVerified */ $getCustomerInvitationUrl ?>"
                   class="link action__link back"
                >
                   <?php  /* @escapeNotVerified */ echo __('Back to Invitations') ?>
                </a>
            </div>
        </div>
    </form>

    <script id="add-email-friends-tmpl" type="text/x-magento-template">
        <div class="input dashboard-form__divider required">
            <label for="email_<%- data._index_ %>" class="label">
                <?= /* @escapeNotVerified */ __('Email') ?>
            </label>

            <input name="email[<%- data._index_ %>]"
                   id="email_<%- data._index_ %>"
                   title="<?= /* @escapeNotVerified */ __('Email') ?>"
                   value=""
                   class="input__field "
                   type="email"
                   data-validate="{required:true, 'validate-email':true}"
                   placeholder="<?= /* @escapeNotVerified */ __('Enter Email') ?>"
            />
        </div>

        <div class="action">
            <div class="action__handler">
                <button type="button"
                        id="btn-remove<%- data._index_ %>"
                        class="button action__button remove"
                        title="<?= /* @escapeNotVerified */ $block->escapeJsQuote(__('Remove')) ?>"
                >
                    <?= /* @escapeNotVerified */ $block->escapeJsQuote(__('Remove')) ?>
                </button>
            </div>
        </div>
    </script>
<?php else:?>
    <div class="message info empty">
        <?= /* @escapeNotVerified */ __('You cannot send more invitations'); ?>
    </div>

    <?php
        $getCustomerInvitationUrl = $this->helper('Magento\Invitation\Helper\Data')
                                         ->getCustomerInvitationUrl();
    ?>

    <div class="action">
        <div class="action__handler">
            <a href="<?= /* @escapeNotVerified */ $getCustomerInvitationUrl ?>"
               class="link action__link"
            >
                <?php  /* @escapeNotVerified */ echo __('Back to Invitations') ?>
            </a>
        </div>
    </div>
<?php endif; ?>
