<?php /** @var $block \Magento\Invitation\Block\Form */?>
<?php echo $block->getChildHtml('form_before')?>

<?php $maxPerSend = $block->getMaxInvitationsPerSend(); ?>

<?php if ($maxPerSend): ?>
    <form id="invitationForm"
          action="" 
          method="post" 
          class="form" 
          data-mage-init='
            {
                "rowBuilder":{
                    "rowTemplate":"#add-email-friends-tmpl",
                    "rowContainer":"#invitations-options",
                    "rowParentElem":"<div></div>",
                    "remEventSelector":"button",
                    "btnRemoveSelector":".action__button.remove",
                    "maxRows":"<?php /* @escapeNotVerified */ echo $block->getMaxInvitationsPerSend(); ?>",
                    "maxRowsMsg":"#max-emails-message",
                    "addRowBtn":"#add-email-button",
                    "additionalRowClass":"additional"
                },
                "validation":{}
            }
          '
          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
>

        <input name="form_key" type="hidden" value="<?php echo $block->escapeHtml($block->getFormKeyValue()) ?>" />

            <h5 class="heading heading--fifth-level dashboard-form__title">
                <?php /* @escapeNotVerified */ echo __('Invite your friends by entering their email addresses'); ?>
            </h5>

            <div id="invitations-options"></div>

            <?php if ($block->isInvitationMessageAllowed()): ?>
                <div id="max-emails-message" style="display: none;" class="message notice limit" role="alert">
                    <?php /* @escapeNotVerified */ echo __('Maximum %1 email addresses allowed.', $block->getMaxInvitationsPerSend()) ?>
                </div>
            <?php endif; ?>
            
            <div class="action dashboard-form__divider">
                <div class="action__handler">
                    <?php if (1 < $block->getMaxInvitationsPerSend()): ?>
                        <button type="button" id="add-email-button" class="button action__button add">
                            <?php /* @escapeNotVerified */ echo __('Add') ?>
                        </button>
                    <?php endif; ?>
                </div>
            </div>

            <?php if ($block->isInvitationMessageAllowed()): ?>
                <div class="input dashboard-form__divider text">
                    <label for="message" class="label">
                        <?php /* @escapeNotVerified */ echo __('Message');?>
                    </label>

                    <textarea name="message" 
                              id="message" 
                              title="<?php /* @escapeNotVerified */ echo __('Message') ?>" 
                              placeholder="<?php /* @escapeNotVerified */ echo __('Message') ?>" 
                              class="input__field input__field--textarea" 
                              rows="5" 
                              cols="5"
                    ></textarea>
                </div>
            <?php endif;?>

        <div class="action">
            <div class="action__handler">
                <button class="button action__button" type="submit">
                    <?php /* @escapeNotVerified */ echo __('Send Invitations') ?>
                </button>
            </div>

            <div class="action__handler">
                <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Invitation\Helper\Data')->getCustomerInvitationUrl() ?>" 
                   class="link action__link back">
                   <?php  /* @escapeNotVerified */ echo __('Back to Invitations') ?>
                </a>
            </div>
        </div>
    </form>

    <script id="add-email-friends-tmpl" type="text/x-magento-template">
        <div class="input dashboard-form__divider required">
            <label for="email_<%- data._index_ %>" class="label">
                <?php /* @escapeNotVerified */ echo __('Email') ?>
            </label>
                
            <input name="email[<%- data._index_ %>]" 
                   id="email_<%- data._index_ %>"
                   title="<?php /* @escapeNotVerified */ echo __('Email') ?>" 
                   value="" 
                   class="input__field " 
                   type="email"
                   data-validate="{required:true, 'validate-email':true}"
                   placeholder="<?php /* @escapeNotVerified */ echo __('Enter Email') ?>"
            />
        </div>

        <div class="action">
            <div class="action__handler">
                <button type="button" 
                        id="btn-remove<%- data._index_ %>" 
                        class="button action__button remove"
                        title="<?php /* @escapeNotVerified */ echo $block->escapeJsQuote(__('Remove')) ?>"
                >
                    <?php /* @escapeNotVerified */ echo $block->escapeJsQuote(__('Remove')) ?>
                </button>
            </div>
        </div>
    </script>
<?php else:?>
    <div class="message info empty">
        <?php /* @escapeNotVerified */ echo __('You cannot send more invitations'); ?>
    </div>

    <div class="action">
        <div class="action__handler">
            <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Invitation\Helper\Data')->getCustomerInvitationUrl() ?>" 
               class="link action__link"
            >
                <?php  /* @escapeNotVerified */ echo __('Back to Invitations') ?>
            </a>
        </div>
    </div>
<?php endif; ?>
