<?php
/**
 * @see \Magento\Invitation\Block\Customer\ListCustomer
 */
?>
<div class="dashboard-table dashboard__item">
    <?= $block->getChildHtml('list_before')?>

    <div class="dashboard-table__header">
        <h3 class="dashboard-table__title">
            <?= __('My Invitations'); ?>
        </h3>
    </div>

    <?php if (count($block->getInvitationCollection())): ?>
        <div class="dashboard-table__content">
            <table
                class="table dashboard-table__table"
                id="invitations-list-table"
            >
                <thead>
                    <tr>
                        <th scope="col" class="col email">
                            <?= __('Email'); ?>
                        </th>

                        <th scope="col" class="col status">
                            <?= __('Status'); ?>
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($block->getInvitationCollection() as $invitation): ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Email')); ?>"
                                class="col email"
                            >
                                <?= $block->escapeHtml($invitation->getEmail()); ?>
                            </td>

                            <td data-th="<?= $block->escapeHtml(__('Status')); ?>"
                                class="col status"
                            >
                                <?= /* @escapeNotVerified */
                                    $this->helper('Magento\Invitation\Helper\Data')
                                         ->getInvitationStatusText($invitation);
                                ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else: ?>
        <div class="message info empty">
            <?= __('There are no sent invitations.'); ?>
        </div>
    <?php endif; ?>

    <div class="action">
        <?php
            $getCustomerInvitaionUrl = $this->helper('Magento\Invitation\Helper\Data')
                                            ->getCustomerInvitationFormUrl();
        ?>

        <div class="action__handler">
            <a href="<?= $getCustomerInvitaionUrl ?>"
               class="link action__link"
            >
                <?= __('Send Invitations') ?>
            </a>
        </div>

        <div class="action__handler">
            <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
               class="link action__link"
            >
                <?= __('Back') ?>
            </a>
        </div>
    </div>
</div>
