<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php if ($block->getMenu()): ?>
    <?php $menuClass = $block->getMenu()->getCssClass() ?>

    <nav
        id="mega-menu"
        class="<?= $block->escapeHtmlAttr($menuClass) ?>"
        data-action="navigation"
        aria-label="<?= $block->escapeHtmlAttr(__('Store navigation')) ?>"
        data-mage-init='{ "megaMenu": { } }'
    >
        <ul class="<?= $block->escapeHtmlAttr($menuClass) ?>__list container">
            <?php foreach ($block->getNodes() as $idx => $node): ?>
                <?php
                    $childrenLevel = $node->getLevel() + 1;
                    $children = $this->getNodes($childrenLevel, $node);
                    $node->setIsParent((bool) $children);
                    $node->setIterationNo($idx + 1);
                    $parentClass = $children ? ' ' . $menuClass . '__item--parent' : '';
                    $additionalClasses = $node->getClasses() ? ' ' . $node->getClasses() : '';
                    $itemClasses = $parentClass . $additionalClasses;
                ?>
                <li class="<?= $block->escapeHtmlAttr($menuClass) ?>__item<?= $block->escapeHtmlAttr($itemClasses) ?> nav-<?= $block->escapeHtmlAttr($idx) + 1 ?>">
                    <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                    <?= /* @noEscape */ $block->renderSubmenu($children, $node, $childrenLevel) ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <div class="<?= $block->escapeHtmlAttr($menuClass) ?>__mobile-bg"></div>
    </nav>
<?php endif; ?>
