<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php if ($block->getMenu()): ?>
    <?php $menuClass = $block->getMenu()->getCssClass() ?>

    <nav
        id="mega-menu"
        class="<?= $escaper->escapeHtmlAttr($menuClass) ?>"
        data-action="navigation"
        data-mage-init='{ "megaMenu": { } }'
    >
        <ul class="<?= $escaper->escapeHtmlAttr($menuClass) ?>__list container">
            <?php foreach ($block->getNodes() as $idx => $node): ?>
                <?php
                    $childrenLevel = $node->getLevel() + 1;
                    $children = $this->getNodes($childrenLevel, $node);
                    $node->setIsParent((bool) $children);
                    $node->setIterationNo($idx + 1);
                    $parentClass = $children ? ' ' . $menuClass . '__item--parent' : '';
                    $additionalClasses = $node->getClasses() ? ' ' . $node->getClasses() : '';
                    $itemClasses = $parentClass . $additionalClasses;
                ?>
                <li
                    class="
                        <?= $escaper->escapeHtmlAttr($menuClass) ?>__item
                        <?= $escaper->escapeHtmlAttr($itemClasses) ?>
                        nav-<?= (int) ($idx + 1) ?>
                    "
                >
                    <?= $block->renderMenuNode($node) ?>
                    <?= $block->renderSubmenu($children, $node, $childrenLevel) ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <div class="<?= $escaper->escapeHtmlAttr($menuClass) ?>__mobile-bg"></div>
    </nav>
<?php endif; ?>
