<?php
/**
 * Wrapper for product sections to include title
 *
 * @var \Magento\Framework\View\Element\Template $block
 */
$childHtml = $block->getChildHtml();
?>
<?php if (trim($childHtml) !== "") : ?>
    <div class="product-full-width-section container">
        <h2 class="product-section-title">
            <?= $block->escapeHtml($block->getTitle()); ?>
        </h2>
        <?= $block->getChildHtml(); ?>
    </div>
<?php endif; ?>
