<?php
/**
 * Wrapper for product sections to include title
 *
 * @var \Magento\Framework\View\Element\Template $block
 */
$childHtml = $block->getChildHtml();
$tabId = $block->getId();
?>

<?php if (trim($childHtml) !== "") : ?>
    <button
        id="tab-title-<?= $tabId; ?>"
        class="
            tab__title
            <?= ($tabId == 1) ? 'tab__title--active' : ''; ?>
        "
        data-tab="tab-<?= $tabId; ?>"
        aria-controls="tab-<?= $tabId; ?>"
        data-testid="product-tab__title"
        aria-selected="<?= ($tabId == 1) ? 'true' : 'false'; ?>"
        aria-expanded="<?= ($tabId == 1) ? 'true' : 'false'; ?>"
        role="tab"
    >
        <?= $block->escapeHtml($block->getTitle()); ?>

        <svg
            class="icon tab__icon"
            role="presentation"
            focusable="false"
        >
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#angle-down')); ?>"></use>
        </svg>
    </button>

    <div
        id="tab-<?= $tabId; ?>"
        class="
            tab__content
            <?= ($tabId == 1) ? 'tab__content--active' : ''; ?>
        "
        data-content="tab-<?= $tabId; ?>"
        aria-labelledby="tab-title-<?= $tabId; ?>"
        aria-hidden="<?= ($tabId == 1) ? 'false' : 'true'; ?>"
        role="tabpanel"
    >
        <?= $block->getChildHtml(); ?>
    </div>
<?php endif; ?>
