<?php
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
// phpcs:disable Magento2.PHP.ShortEchoSyntax.ShortEchoTag

/** @var $block \Magento\Ui\Block\Wrapper */

//TODO: recently viewed list required - now grid template is used
?>
<section
    class="
        recently-viewed
        recently-viewed--grid
    "
>
    <div class="recently-viewed__block">
        <div
            class="
                recently-viewed__heading
                section__heading
            "
        >
            <h2
                class="
                    recently-viewed__title
                    heading--first-level
                    margin-0
                "
            >
                <?= $block->escapeHtml(__('Recently Viewed')) ?>
            </h2>
        </div>

        <?php
        //slider config
        $sliderIsAjax           = true;
        $sliderArrows           = true;
        $sliderClass            = 'slider--products slider--nested';
        $sliderInfinite         = 'no';
        $sliderSlidesToShow     = '2';
        $sliderSlidesToScroll   = '1';
        $sliderResponsiveConfig = '[
            {
                "breakpoint": 767,
                "settings": {
                    "slidesToShow": 3,
                    "slidesToScroll": 1,
                    "dots": false
                }
            },
            {
                "breakpoint": 1023,
                "settings": {
                    "slidesToShow": 4,
                    "slidesToScroll": 1,
                    "dots": false
                }
            }
        ]';
        ?>
        <?php
        $sliderBlockBefore = $this->getLayout()
            ->createBlock("Magento\Framework\View\Element\Template")
            ->setTemplate("Magento_Theme::html/slider.phtml");

        $sliderBlockBefore->setData([
            'is_ajax'           => $sliderIsAjax,
            'arrows'            => $sliderArrows,
            'slides_element'    => '.admin__data-grid-outer-wrap',
            'slider_html'       => 'before-slides',
            'slider_class'      => $sliderClass,
            'infinite'          => $sliderInfinite,
            'slides_to_show'    => $sliderSlidesToShow,
            'slides_to_scroll'  => $sliderSlidesToScroll,
            'responsive_config' => $sliderResponsiveConfig
        ]);
        ?>
        <?= $sliderBlockBefore->toHtml(); ?>

        <?= /* @noEscape */ $block->renderApp([
            'widget_columns' => [
                'displayMode' => 'grid',
                'displayAs' => 'slider',
                'itemWrapperClasses' => 'slider__item',
                'itemClasses' => 'product-grid-item product-grid-item--slider-item'
            ],
            'image' => [
                'imageCode' => 'recently_viewed_products_grid_content_widget'
            ]
        ]) ?>

        <?php $sliderBlockAfter = $this->getLayout()
            ->createBlock("Magento\Framework\View\Element\Template")
            ->setTemplate("Magento_Theme::html/slider.phtml"),
            $sliderBlockAfter->setData([
                'slider_html'   => 'after-slides'
            ])
        ?>
        <?=  /* @noEscape */ $sliderBlockAfter->toHtml(); ?>
    </div>
</section>
