<?php
// phpcs:disable Magento2.PHP.ShortEchoSyntax.ShortEchoTag

/** @var $block \Magento\Ui\Block\Wrapper */
?>
<div
    class="
        recently-viewed
        recently-viewed--sidebar
    "
>
    <div class="sidebar-block">
        <div class="sidebar-block__heading">
            <h2 class="sidebar-block__title">
                <?= $block->escapeHtml(__('Recently Viewed')) ?>
            </h2>
        </div>

        <div
            class="loader loader--visible"
            aria-live="polite"
            aria-label="<?= $block->escapeHtmlAttr(__('Do not refresh the page')) ?>"
        >
            <div class="loader__icon"></div>
        </div>

        <?= /* @noEscape */ $block->renderApp([
            'listing' => [
                'displayMode' => 'grid',
            ],
            'widget_columns' => [
                'itemWrapperClasses' => '',
                'itemClasses' => 'product-grid-item'
            ],
            'image' => [
                'imageCode' => 'recently_viewed_products_images_names_widget'
            ]
        ]) ?>
    </div>
</div>
