<?php /** @var $block Magento\Framework\View\Element\Template */ ?>
<form
    class="
        dashboard-form
        form
        form-add-team
    "
    method="post"
    id="add-team-form"
    action="<?= $block->escapeUrl($block->getUrl('*/team/manage')) ?>"
    data-mage-init='{"validation":{}}'
>
    <input
        type="hidden"
        name="target_id"
    />
    <input
        type="hidden"
        name="team_id"
    />
    <fieldset class="fieldset info">
        <legend
            class="
                fieldset__legend
                fieldset__legend--hidden
            "
        >
            <?= $block->escapeHtml(__('User\'s Team information')) ?>
        </legend>
        <div class="input team-title required">
            <label
                class="label"
                for="team-title"
            >
                <?= $block->escapeHtml(__('Team Title')) ?>
            </label>
            <input
                type="text"
                name="name"
                id="team-title"
                value=""
                title="<?= $block->escapeHtmlAttr(__('Team Title')) ?>"
                class="input__field"
                data-validate="{required:true}"
            />
        </div>
        <div class="input description">
            <label
                class="label"
                for="description"
            >
                <?= $block->escapeHtml(__('Description')) ?>
            </label>
            <textarea
                name="description"
                id="description"
                rows="4"
                title="<?= $block->escapeHtmlAttr(__('Description')) ?>"
                class="
                    input__field
                    input__field--textarea
                "
            ></textarea>
        </div>
    </fieldset>
</form>
