<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block Magento\Framework\View\Element\Template */ ?>
<form class="form form-add-team" method="post" id="add-team-form"
      action="<?= $block->escapeUrl($block->getUrl('*/team/manage')) ?>"
      data-mage-init='{"validation":{}}'>
    <input type="hidden" name="target_id" />
    <input type="hidden" name="team_id" />
    <fieldset class="fieldset info">
        <div class="field team-title required">
            <label class="label" for="team-title">
                <span><?= $block->escapeHtml(__('Team Title')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="name" id="team-title" value=""
                       title="<?= $block->escapeHtmlAttr(__('Team Title')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field description">
            <label class="label" for="description">
                <span><?= $block->escapeHtml(__('Description')) ?></span>
            </label>
            <div class="control">
                <textarea name="description" id="description" rows="4"
                          title="<?= $block->escapeHtmlAttr(__('Description')) ?>" class="textarea"></textarea>
            </div>
        </div>
    </fieldset>
</form>
