<?php
$_href = $block->getHref();
?>

<a 
    class="header-button"
    data-testid="customer-account-link" 
    aria-label="<?= $escaper->escapeHtmlAttr(__('Customer Account')) ?>"
    <?= $block->getLinkAttributes() ?>
>
    <svg class="icon header-button__icon">
        <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#account')) ?>"></use>
    </svg>
    <span class="header-button__text">
        <?= $escaper->escapeHtml(__('Account')) ?>
    </span>
</a>
