<?php
$_href = $block->getHref();
?>

<a class="header-button"
   aria-label="<?= /* @escapeNotVerified */ __('Customer Account') ?>"
   <?= /* @escapeNotVerified */ $block->getLinkAttributes() ?>
>
    <svg class="icon header-button__icon">
        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#account') ?>"></use>
    </svg>
    <span class="header-button__text">
        <?= /* @escapeNotVerified */ __('Account') ?>
    </span>
</a>
