<?php
$_href = $block->getHref();
?>

<a 
    class="header-button"
    data-testid="customer-account-link" 
    aria-label="<?= __('Customer Account') ?>"
    <?= $block->getLinkAttributes() ?>
>
    <svg class="icon header-button__icon">
        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#account') ?>"></use>
    </svg>
    <span class="header-button__text">
        <?= __('Account') ?>
    </span>
</a>
