<a
    class="
        header-button
        button
        button--icon
        button--icon-light
    "
    href="<?= $block->escapeUrl($block->getUrl('checkout/cart')); ?>"
    aria-label="<?= $block->escapeHtmlAttr(__('Shopping cart')) ?>"
>
    <svg
        class="icon header-button__icon"
        role="presentation"
        focusable="false"
    >
        <title><?= $block->escapeHtml(__('Shopping cart')) ?></title>
        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#shopping-cart')); ?>"></use>
    </svg>
</a>
