<a
    class="header-button"
    data-testid="contact-header-link"
    href="#"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Store phone number')) ?>"
>
    <svg
        class="icon header-button__icon"
        role="presentation"
        focusable="false"
    >
        <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#phone')) ?>"></use>
    </svg>
    <span class="header-button__text">
        <?= $escaper->escapeHtml(__('Contact')) ?>
    </span>
</a>
