<a 
    class="header-button"
    data-testid="contact-header-link"
    href="#"
    aria-label="<?= $block->escapeHtmlAttr(__('Store phone number')) ?>"
>
    <svg class="icon header-button__icon">
        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#phone')) ?>"></use>
    </svg>
    <span class="header-button__text">
        <?= $block->escapeHtml(__('Contact')) ?>
    </span>
</a>
