<?php
/* @var \Magento\Wishlist\Block\Link $block */
?>
<a
    class="
        header-button
        button
        button--icon
        button--icon-light
        button--icon-fill
    "
    data-testid="wishlist-link"
    aria-labelledby="wishlist-header-link-title"
    data-bind="scope: 'wishlist'"
    <?= /* @noEscape */ $block->getLinkAttributes() ?>
>
    <span
        class="visually-hidden"
        id="wishlist-header-link-title"
        data-bind="i18n: $t('Wishlist, %1').replace('%1', wishlist().counter || '0 items')"
    ></span>
    <svg
        class="icon header-button__icon"
        role="presentation"
        focusable="false"
    >
        <title><?= $block->escapeHtml(__('Heart')) ?></title>
        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#heart')); ?>"></use>
    </svg>
    <!-- ko if: wishlist().counter -->
        <span
            class="
                header-button__counter
                header-button__counter--hidden
            "
            data-bind="
                css: {
                    'header-button__counter--hidden': null
                }
            "
        >
            <span class="header-button__counter-dot"></span>
        </span>
    <!-- /ko -->
</a>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>
