<?php
/* @var \Magento\Wishlist\Block\Link $block */
?>

<a
    class="header-button header-button--reset-margin"
    data-testid="wishlist-link"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Wishlist')) ?>"
    data-bind="scope: 'wishlist'"
    <?= $block->getLinkAttributes() ?>
>
    <svg
        class="icon header-button__icon"
        role="presentation"
        focusable="false"
    >
        <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#heart')); ?>"></use>
    </svg>
    <span class="header-button__text">
        <?= $escaper->escapeHtml(__('Wishlist')) ?>
    </span>
    <!-- ko if: wishlist().counter -->
        <span
            class="header-button__counter header-button__counter--hidden"
            data-bind="css: {'header-button__counter--hidden': null}"
        >
            <span class="header-button__counter-dot"></span>
        </span>
    <!-- /ko -->
</a>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>
