<?php
/** @var $block \Snowdog\SolrNavigation\Block\Product\Toolbar */
?>

<?php if ($block->getResponse()->getItemsFound()): ?>
    <div class="toolbar">
        <?php include($block->getTemplateFile('Snowdog_SolrNavigation::product/list/toolbar/sorter.phtml')); ?>
        <?php include($block->getTemplateFile('Snowdog_SolrNavigation::product/list/toolbar/limiter.phtml')); ?>
    </div>
<?php endif ?>
