<?php
/**
 * @var \Magento\CompanyPayment\Block\Company\Profile\PaymentMethod $block
 * @codingStandardsIgnoreFile
 */
?>

<div class="block block-company-profile-payment-methods dashboard-items">
    <h3 class="dashboard-items__title">
        <?= $block->escapeHtml(__('Payment Information')) ?>
    </h3>
    <div class="block-content">
        <?php if ($block->hasPaymentMethods()): ?>
            <div class="company-profile-payment-methods">
                <h4 class="payment-methods-label">
                    <?= $block->escapeHtml(__('Available Payment Methods')) ?>
                </h4>
                <ul class="payment-methods-list">
                    <?php foreach ($block->getPaymentMethods() as $paymentMethod): ?>
                        <li>
                            <?= $block->escapeHtml($paymentMethod) ?>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        <?php else: ?>
            <div class="message message-notice notice">
                <div data-ui-id="messages-message-notice">
                    <?= $block->escapeHtml(__('This company has no payment methods. Please contact store administrator.')) ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
