<?php
/**
 * @var \Magento\CompanyPayment\Block\Company\Profile\PaymentMethod $block
 */
?>

<div class="dashboard-items">
    <h2
        class="
            dashboard-items__title
            margin-bottom-sm
        "
    >
        <?= $block->escapeHtml(__('Payment Information')) ?>
    </h2>
    <div class="row">
        <div
            class="
                dashboard-items__item
                col-sm-6
            "
        >
            <?php
            if ($block->hasPaymentMethods()): ?>
                <div class="company-profile-payment-methods">
                    <h3
                        id="payment-methods-label"
                        class="
                            payment-methods-label
                            dashboard-items__subtitle
                            margin-bottom-l
                        "
                    >
                        <?= $block->escapeHtml(__('Available Payment Methods')) ?>
                    </h3>
                    <ul
                        class="
                            payment-methods-list
                            list
                            list--native
                        "
                        aria-labelledby="payment-methods-label"
                    >
                    <?php foreach ($block->getPaymentMethods() as $paymentMethod): ?>
                        <li class="list__item">
                            <?= $block->escapeHtml($paymentMethod) ?>
                        </li>
                    <?php endforeach; ?>
                    </ul>
                </div>
            <?php else: ?>
                <div class="message message-notice notice">
                    <div data-ui-id="messages-message-notice">
                    <?= $block->escapeHtml(__('This company has no payment methods. Please contact store administrator.')) ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
