<?php if (count($block->getItems()) > 0) : ?>
    <form
        action="<?= $block->escapeUrl($block->getActionUpdateUrl()) ?>"
        method="post"
        id="gift-registry-items-form"
        class="form giftregistry items"
        data-mage-init='{"validation":{}}'
    >
        <fieldset class="fieldset">
            <legend class="fieldset__legend fieldset__legend--hidden">
                <?= $block->escapeHtml(__('Gift Registry')) ?>
            </legend>
            <?= $block->getBlockHtml('formkey') ?>
            <div class="table-wrapper giftregistry">
                <table
                    id="shopping-cart-table"
                    class="
                        data
                        table
                        table-giftregistry-items
                    "
                >
                    <caption class="table__caption">
                        <?= $block->escapeHtml(__('Gift Registry')) ?>
                    </caption>
                    <thead>
                        <tr>
                            <th
                                scope="col"
                                class="col product"
                            >
                                <?= $block->escapeHtml(__('Product')) ?>
                            </th>
                            <th
                                scope="col"
                                class="col note"
                            >
                                <?= $block->escapeHtml(__('Note')) ?>
                            </th>
                            <th
                                scope="col"
                                class="col date"
                            >
                                <?= $block->escapeHtml(__('Added On')) ?>
                            </th>
                            <th
                                scope="col"
                                class="col qty"
                            >
                                <?= $block->escapeHtml(__('Qty')) ?>
                            </th>
                            <th
                                scope="col"
                                class="col fulfilled"
                            >
                                <?= $block->escapeHtml(__('Qty Fulfilled')) ?>
                            </th>
                            <th
                                scope="col"
                                class="col actions"
                            >
                                <?= $block->escapeHtml(__('Delete')) ?>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($block->getItems() as $_item) : ?>
                            <?= $block->getItemHtml($_item) ?>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
            <div class="actions-group">
                <div class="actions-group__handler">
                    <button
                        type="submit"
                        class="
                            action
                            primary
                            update
                            button
                            actions-group__button
                        "
                    >
                        <?= $block->escapeHtml(__('Update Gift Registry')) ?>
                    </button>
                </div>
                <div class="actions-group__handler">
                    <a
                        href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
                        class="
                            action
                            back
                            link
                            actions-group__link
                        "
                    >
                        <?= $block->escapeHtml(__('Back')) ?>
                    </a>
                </div>
            </div>
        </fieldset>
    </form>
<?php else : ?>
    <div class="message">
        <?= $block->escapeHtml(__('This gift registry has no items.')) ?>
    </div>
    <div class="actions-group">
        <div class="actions-group__handler">
            <a
                href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
                class="
                    action
                    back
                    link
                    actions-group__link
                "
            >
                <?= $block->escapeHtml(__('Back')) ?>
            </a>
        </div>
    </div>
<?php endif ?>
