<?php $entityCollection = $block->getEntityCollection(); ?>

<?php if ($entityCollection && count($entityCollection)): ?>
    <div class="dashboard-table ">
        <div class="dashboard-table__header">
            <h3 class="dashboard-table__title">
                <?=  __('Gift Registry'); ?>
            </h3>
        </div>

        <div class="dashboard-table__content">
            <table id="giftregistry-table" class="table dashboard-table__table">
                <thead>
                    <tr>
                        <th scope="col" class="col event">
                            <?=  __('Event'); ?>
                        </th>

                        <th scope="col" class="col create">
                            <?=  __('Created On'); ?>
                        </th>

                        <th scope="col" class="col info">
                            <?=  __('Message'); ?>
                        </th>

                        <th scope="col" class="col actions">
                            &nbsp;
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($entityCollection as $item): ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Event')); ?>"
                                class="col event"
                                title="<?= $block->getEscapedTitle($item) ?>"
                            >
                                <?= $block->truncateString($block->getEscapedTitle($item), 70)?>
                            </td>

                            <td data-th="<?= $block->escapeHtml(__('Created On')); ?>"
                                class="col create"
                            >
                                <?= $block->getFormattedDate($item) ?>
                            </td>

                            <td data-th="<?= $block->escapeHtml(__('Message')); ?>"
                                class="col info"
                            >
                                <?= $block->getEscapedMessage($item) ?>
                            </td>

                            <td data-th="<?= $block->escapeHtml(__('Action')); ?>"
                                class="col actions"
                            >
                                <a href="<?= $block->getItemsUrl($item) ?>"
                                   class="action manage"
                                   title="<?=  __('Manage Items') ?>"
                                >
                                    <?=  __('Manage Items') ?>
                                </a>

                                <a href="<?= $block->getShareUrl($item) ?>"
                                   class="action share"
                                   title="<?=  __('Share') ?>"
                                >
                                    <?=  __('Share') ?>
                                </a>

                                <a href="<?= $block->getEditUrl($item) ?>"
                                   class="action edit"
                                   title="<?=  __('Edit') ?>"
                                >
                                    <?=  __('Edit') ?>
                                </a>

                                <a href="#"
                                   data-post='<?= $block->getDeleteParams($item) ?>'
                                   class="action delete"
                                   title="<?=  __('Delete') ?>"
                                   data-role="remove-gift-registry"
                                >
                                    <?=  __('Delete') ?>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <?php if ($block->getChildHtml('pager')): ?>
        <?= $block->getChildHtml('pager'); ?>
    <?php endif;?>

<?php else:?>
    <div class="message info empty">
        <?=  __('You haven\'t created a gift registry yet.'); ?>
    </div>
<?php endif;?>

<div class="action">
    <div class="action__handler">
        <?php if ($block->canAddNewEntity()):?>
            <a href="<?= $block->escapeUrl($block->getAddUrl()) ?>"
               class="link action__link primary add"
            >
                <?=  __('Add New') ?>
            </a>
        <?php endif;?>
    </div>

    <div class="action__handler">
        <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
           class="link action__link back"
        >
            <?=  __('Back') ?>
        </a>
    </div>
</div>

<script>
    require([
        'mage/dataPost',
        'Magento_Ui/js/modal/confirm',
        'prototype'
    ], function(dataPost, confirm){
//<![CDATA[
        $$("[data-role='remove-gift-registry']").each(function(item){
            Event.observe(item, "click", function (event) {
                var params = JSON.parse(jQuery(event.currentTarget).attr('data-post'));

                event.stopPropagation();
                confirm({
                    content: '<?=  __('Are you sure you want to delete this gift registry?') ?>',
                    actions: {
                        confirm: function () {
                            dataPost().postData(params);
                        }
                    }
                });
            });
        });
//]]>
    });
</script>

