<?php
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php $entityCollection = $block->getEntityCollection(); ?>

<?php if ($entityCollection && count($entityCollection)): ?>
    <div class="dashboard-table margin-bottom-xs">
        <div class="table-wrapper giftregistry">
            <table
                id="giftregistry-table"
                class="
                    table
                    giftregistry__table
                    margin-0
                "
                tabindex="0"
                role="table"
            >
                <caption class="table__caption">
                    <?= $block->escapeHtml(__('Gift Registry')) ?>
                </caption>
                <thead>
                    <tr role="row">
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Event')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Created On')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Message')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        ></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($entityCollection as $item) :?>
                        <tr role="row">
                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Event:')) ?>"
                                role="gridcell"
                            >
                                <?= /* @noEscape */ $block->truncateString($block->getEscapedTitle($item), 70) ?>
                            </td>
                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Created On:')) ?>"
                                role="gridcell"
                            >
                                <?= $block->escapeHtml($block->getFormattedDate($item)) ?>
                            </td>
                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Message:')) ?>"
                                role="gridcell"
                            >
                                <?= /* @noEscape */ $block->getEscapedMessage($item) ?>
                            </td>
                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Action:')) ?>"
                                role="gridcell"
                            >
                                <a
                                    href="<?= $block->escapeUrl($block->getItemsUrl($item)) ?>"
                                    class="
                                        link
                                        dashboard-table__link
                                        padding-right-xs
                                    "
                                    title="<?= $block->escapeHtmlAttr(__('Manage Items')) ?>"
                                >
                                    <?= $block->escapeHtml(__('Manage Items')) ?>
                                </a>
                                <a
                                    href="<?= $block->escapeUrl($block->getShareUrl($item)) ?>"
                                    class="
                                        link
                                        dashboard-table__link
                                        padding-right-xs
                                    "
                                    title="<?= $block->escapeHtmlAttr(__('Share')) ?>"
                                >
                                    <?= $block->escapeHtml(__('Share')) ?>
                                </a>
                                <a
                                    href="<?= $block->escapeUrl($block->getEditUrl($item)) ?>"
                                    class="
                                        link
                                        dashboard-table__link
                                        padding-right-xs
                                    "
                                    title="<?= $block->escapeHtmlAttr(__('Edit')) ?>"
                                >
                                    <?= $block->escapeHtml(__('Edit')) ?>
                                </a>
                                <a
                                    href="#"
                                    data-post='<?= /* @noEscape */ $block->getDeleteParams($item) ?>'
                                    class="
                                        link
                                        dashboard-table__link
                                        padding-right-xs
                                    "
                                    title="<?= $block->escapeHtmlAttr(__('Delete')) ?>"
                                    data-role="remove-gift-registry"
                                >
                                    <?= $block->escapeHtml(__('Delete')) ?>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if ($block->getChildHtml('pager')) :?>
        <div
            class="
                toolbar
                giftregistry-toolbar
                bottom
            "
        >
            <?= $block->getChildHtml('pager') ?>
        </div>
    <?php endif;?>
<?php else :?>
    <div class="message">
        <?= $block->escapeHtml(__('You haven\'t created a gift registry yet.')) ?>
    </div>
<?php endif;?>

<div class="actions-group">
    <div class="actions-group__handler">
        <?php if ($block->canAddNewEntity()) :?>
            <a
                href="<?= $block->escapeUrl($block->getAddUrl()) ?>"
                class="
                    link--button
                    button
                    actions-group__button
                "
                title="<?= $block->escapeHtmlAttr(__('Add New')) ?>"
            >
                <?= $block->escapeHtml(__('Add New')) ?>
            </a>
        <?php endif;?>
    </div>
    <div class="actions-group__handler">
        <a
            href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
            class="
                link
                actions-group__link
            "
            title="<?= $block->escapeHtmlAttr(__('Back to My Account')) ?>"
        >
            <?= $block->escapeHtml(__('Back')) ?>
        </a>
    </div>
</div>
<?php
$confirmationMessage = $block->escapeJs(__('Are you sure you want to delete this gift registry?'));
?>
<?php $scriptString = <<<script
    require([
        'mage/dataPost',
        'Magento_Ui/js/modal/confirm',
        'prototype'
    ], function(dataPost, confirm){
//<![CDATA[
        $$("[data-role='remove-gift-registry']").each(function(item){
            Event.observe(item, "click", function (event) {
                var params = JSON.parse(jQuery(event.currentTarget).attr('data-post'));

                event.stopPropagation();
                confirm({
                    content: '{$confirmationMessage}',
                    actions: {
                        confirm: function () {
                            dataPost().postData(params);
                        }
                    }
                });
            });
        });
//]]>
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
