<?php $entityCollection = $block->getEntityCollection(); ?>

<?php if ($entityCollection && count($entityCollection)):?>
    <div class="dashboard-table ">
        <div class="dashboard-table__header">
            <h5 class="heading heading--fifth-level dashboard-table__title">
                <?php /* @escapeNotVerified */ echo __('Gift Registry'); ?>
            </h5>
        </div>

        <div class="dashboard-table__content">
            <table id="giftregistry-table" class="table">
                <thead>
                    <tr>
                        <th scope="col" class="col event">
                            <?php /* @escapeNotVerified */ echo __('Event'); ?>
                        </th>

                        <th scope="col" class="col create">
                            <?php /* @escapeNotVerified */ echo __('Created On'); ?>
                        </th>

                        <th scope="col" class="col info">
                            <?php /* @escapeNotVerified */ echo __('Message'); ?>
                        </th>

                        <th scope="col" class="col actions">
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($entityCollection as $item): ?>
                        <tr>
                            <td data-th="<?php echo $block->escapeHtml(__('Event')); ?>" 
                                class="col event" 
                                title="<?php /* @escapeNotVerified */ echo $block->getEscapedTitle($item)?>"
                            >
                                <?php /* @escapeNotVerified */ echo $block->truncateString($block->getEscapedTitle($item), 70)?>
                            </td>

                            <td data-th="<?php echo $block->escapeHtml(__('Created On')); ?>" 
                                class="col create"
                            >
                                <?php /* @escapeNotVerified */ echo $block->getFormattedDate($item) ?>
                            </td>

                            <td data-th="<?php echo $block->escapeHtml(__('Message')); ?>" 
                                class="col info"
                            >
                                <?php /* @escapeNotVerified */ echo $block->getEscapedMessage($item)?>
                            </td>

                            <td data-th="<?php echo $block->escapeHtml(__('Action')); ?>" class="col actions">
                                <a href="<?php /* @escapeNotVerified */ echo $block->getItemsUrl($item)?>" 
                                   class="action manage" 
                                   title="<?php /* @escapeNotVerified */ echo __('Manage Items') ?>"
                                >
                                    <?php /* @escapeNotVerified */ echo __('Manage Items') ?>
                                </a>

                                <a href="<?php /* @escapeNotVerified */ echo $block->getShareUrl($item)?>" 
                                   class="action share" 
                                   title="<?php /* @escapeNotVerified */ echo __('Share') ?>"
                                >
                                    <?php /* @escapeNotVerified */ echo __('Share') ?>
                                </a>

                                <a href="<?php /* @escapeNotVerified */ echo $block->getEditUrl($item)?>" 
                                   class="action edit" 
                                   title="<?php /* @escapeNotVerified */ echo __('Edit') ?>"
                                >
                                    <?php /* @escapeNotVerified */ echo __('Edit') ?>
                                </a>

                                <a href="#"
                                   data-post='<?php /* @escapeNotVerified */ echo $block->getDeleteParams($item)?>'
                                   class="action delete"
                                   title="<?php /* @escapeNotVerified */ echo __('Delete') ?>"
                                   data-role="remove-gift-registry"
                                >
                                    <?php /* @escapeNotVerified */ echo __('Delete') ?>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <?php if ($block->getChildHtml('pager')): ?>
        <?php echo $block->getChildHtml('pager'); ?>
    <?php endif;?>

<?php else:?>
    <div class="message info empty">
        <?php /* @escapeNotVerified */ echo __('You haven\'t created a gift registry yet.'); ?>
    </div>
<?php endif;?>

<div class="action">
    <div class="action__handler">
        <?php if ($block->canAddNewEntity()):?>
            <a href="<?php echo $block->escapeUrl($block->getAddUrl()) ?>" class="link action__link primary add">
                <?php /* @escapeNotVerified */ echo __('Add New') ?>
            </a>
        <?php endif;?>
    </div>

    <div class="action__handler">
        <a href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>" class="link action__link back">
            <?php /* @escapeNotVerified */ echo __('Back') ?>
        </a>
    </div>
</div>

<script>
    require([
        'mage/dataPost',
        'Magento_Ui/js/modal/confirm',
        'prototype'
    ], function(dataPost, confirm){
//<![CDATA[
        $$("[data-role='remove-gift-registry']").each(function(item){
            Event.observe(item, "click", function (event) {
                var params = JSON.parse(jQuery(event.currentTarget).attr('data-post'));

                event.stopPropagation();
                confirm({
                    content: '<?php /* @escapeNotVerified */ echo __('Are you sure you want to delete this gift registry?') ?>',
                    actions: {
                        confirm: function () {
                            dataPost().postData(params);
                        }
                    }
                });
            });
        });
//]]>
    });
</script>

