<script id="add-recipient-tmpl" type="text/x-magento-template">
    <div class="input required">
        <label for="recipients-name<%- data._index_ %>" class="label">
            <?= $block->escapeHtml(__('First Name')) ?>
        </label>

        <input name="recipients[<%- data._index_ %>][name]"
               type="text"
               title="<?= $block->escapeHtmlAttr(__('Name'))?>"
               class="input__field"
               id="recipients-name<%- data._index_ %>"
               data-validate="{required:true}"
        />
    </div>
    <div class="input required dashboard-form__divider">
        <label for="recipients-email<%- data._index_ %>" class="label">
            <?= $block->escapeHtml(__('Email')) ?>
        </label>

        <input name="recipients[<%- data._index_ %>][email]"
               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
               id="recipients-email<%- data._index_ %>"
               type="email"
               class="input__field"
               data-validate="{required:true, 'validate-email':true}"
        />
    </div>

    <div class="action dashboard-form__divider">
        <div class="action__handler">
            <button type="button" class="button action__button remove" id="btn-remove<%- data._index_ %>">
                <?= $block->escapeHtml(__('Remove')) ?>
            </button>
        </div>
    </div>
</script>

<div class="dashboard-form">

    <h3 class="dashboard-form__title">
        <?= $block->getFormHeader() ?>
    </h3>

    <form action="<?= $block->getSendUrl() ?>"
          method="post"
          id="giftregistry-sharing-form"
          class="form form-giftregistry-share validation"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
    >
            <?= $block->getBlockHtml('formkey') ?>
            <div class="information">
                <h4 class="information__title">
                    <?= $block->escapeHtml(__('Sender')) ?>
                </h4>
            </div>

            <div class="input name required">
                <?php
                    if ($block->getFormData('sender_name')) {
                        $getSenderNameValue = $block->getFormData('sender_name');
                    }
                    else {
                        $getSenderNameValue = $block->getCustomerName();
                    }
                ?>

                <label for="sender_name" class="label">
                    <?= $block->escapeHtml(__('Name')) ?>
                </label>

                <input name="sender_name"
                       value="<?= $block->escapeHtmlAttr($getSenderNameValue) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                       id="sender_name"
                       type="text"
                       class="input__field"
                       data-validate="{required:true}"
                />
            </div>

            <div class="input required dashboard-form__divider">
                <label for="sender_message" class="label">
                    <?= $block->escapeHtml(__('Message')) ?>
                </label>

                <textarea name="sender_message"
                          class="input__field input__field--textarea"
                          id="sender_message"
                          cols="3"
                          rows="3"
                          data-validate="{required:true}"
                ><?= $block->getFormData('sender_message'); ?></textarea>
            </div>

            <div class="information">
                <h4 class="information__title">
                    <?= $block->escapeHtml(__('Invitee')) ?>
                </h4>
            </div>

            <div id="recipients-options"></div>

            <?php if ($block->getRecipientsLimit()): ?>
                <div id="max-recipient-message" style="display: none" class="message notice limit">
                    <?= $block->escapeHtml(__('Maximum %1 email addresses.', $block->getRecipientsLimit())) ?>
                </div>
            <?php endif; ?>

            <div class="action dashboard-form__divider">
                <div class="action__handler">
                    <?php if ($block->getRecipientsLimit()): ?>
                        <button type="button" id="add-recipient-button" class="button action__button add">
                            <?= $block->escapeHtml(__('Add Invitee')) ?>
                        </button>
                    <?php endif; ?>
                </div>
            </div>

        <div class="action">
            <div class="action__handler">
                <button type="submit" class="button action__button primary share">
                    <?= $block->escapeHtml(__('Share Gift Registry')) ?>
                </button>
            </div>

            <div class="action__handler">
                <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
                   class="link action__link back"
                >
                    <?= $block->escapeHtml(__('Back')) ?>
                </a>
            </div>
        </div>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "#giftregistry-sharing-form": {
            "rowBuilder": {
                "rowTemplate": "#add-recipient-tmpl",
                "rowContainer": "#recipients-options",
                "maxRows": "<?= $block->escapeHtmlAttr($block->getRecipientsLimit()) ?>",
                "maxRowsMsg": "#max-recipient-message",
                "addRowBtn": "#add-recipient-button",
                "rowParentElem": "<div></div>",
                "remEventSelector": "button",
                "btnRemoveSelector": ".action__button.remove",
                "additionalRowClass": "additional",
                "formDataPost": {
                        <?php if (is_array($block->getFormData('recipients'))): ?>
                            "formData": <?= $block->escapeHtmlAttr(json_encode($block->getFormData('recipients'))); ?>,
                        <?php endif; ?>
                    "templateFields": ["recipients-name", "recipients-email"]
                }
            },
            "validation": {}
        }
    }
</script>
