<script id="add-recipient-tmpl" type="text/x-magento-template">
    <div class="input required">
        <label for="recipients-name<%- data._index_ %>" class="label">
            <?php /* @escapeNotVerified */ echo __('First Name') ?>
        </label>

        <input name="recipients[<%- data._index_ %>][name]" 
               type="text" 
               title="<?php /* @escapeNotVerified */ echo __('Name')?>" 
               class="input__field" 
               id="recipients-name<%- data._index_ %>" 
               data-validate="{required:true}"
        />
    </div>
    <div class="input required dashboard-form__divider">
        <label for="recipients-email<%- data._index_ %>" class="label">
            <?php /* @escapeNotVerified */ echo __('Email') ?>
        </label>

        <input name="recipients[<%- data._index_ %>][email]" 
               title="<?php /* @escapeNotVerified */ echo __('Email') ?>" 
               id="recipients-email<%- data._index_ %>" 
               type="email" 
               class="input__field" 
               data-validate="{required:true, 'validate-email':true}"
        />
    </div>

    <div class="action dashboard-form__divider">
        <div class="action__handler">
            <button type="button" class="button action__button remove" id="btn-remove<%- data._index_ %>">
                <?php /* @escapeNotVerified */ echo __('Remove') ?>
            </button>
        </div>
    </div>
</script>

<div class="dashboard-form">

    <h5 class="heading heading--fifth-level dashboard-form__title">
        <?php /* @escapeNotVerified */ echo $block->getFormHeader() ?>
    </h5>

    <form action="<?php /* @escapeNotVerified */ echo $block->getSendUrl() ?>" 
          method="post" 
          id="giftregistry-sharing-form" 
          class="form form-giftregistry-share validation" 
          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
    >
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="information">
                <h6 class="heading heading--sixth-level information__title">
                    <?php /* @escapeNotVerified */ echo __('Sender') ?>
                </h6>
            </div>

            <div class="input name required">
                <label for="sender_name" class="label">
                    <?php /* @escapeNotVerified */ echo __('Name') ?>
                </label>
                
                <input name="sender_name" 
                       value="<?php if ($block->getFormData('sender_name')): ?><?php /* @escapeNotVerified */ echo $block->getFormData('sender_name') ?><?php else:?><?php /* @escapeNotVerified */ echo $block->getCustomerName() ?><?php endif;?>" 
                       title="<?php /* @escapeNotVerified */ echo __('Name') ?>" 
                       id="sender_name" 
                       type="text" 
                       class="input__field" 
                       data-validate="{required:true}"
                />
            </div>

            <div class="input required dashboard-form__divider">
                <label for="sender_message" class="label">
                    <?php /* @escapeNotVerified */ echo __('Message') ?>
                </label>

                <textarea name="sender_message" 
                          class="input__field input__field--textarea" 
                          id="sender_message" 
                          cols="3" 
                          rows="3" 
                          data-validate="{required:true}"
                ><?php /* @escapeNotVerified */ echo $block->getFormData('sender_message'); ?></textarea>
            </div>

            <div class="information">
                <h6 class="heading heading--sixth-level information__title">
                    <?php /* @escapeNotVerified */ echo __('Invitee') ?>
                </h6>
            </div>
            
            <div id="recipients-options"></div>

            <?php if ($block->getRecipientsLimit()): ?>
                <div id="max-recipient-message" style="display: none" class="message notice limit">
                    <?php /* @escapeNotVerified */ echo __('Maximum %1 email addresses.', $block->getRecipientsLimit()) ?>
                </div>
            <?php endif; ?>

            <div class="action dashboard-form__divider">
                <div class="action__handler">
                    <?php if ($block->getRecipientsLimit()): ?>
                        <button type="button" id="add-recipient-button" class="button action__button add">
                            <?php /* @escapeNotVerified */ echo __('Add Invitee') ?>
                        </button>
                    <?php endif; ?>
                </div>
            </div>

        <div class="action">
            <div class="action__handler">
                <button type="submit" class="button action__button primary share">
                    <?php /* @escapeNotVerified */ echo __('Share Gift Registry') ?>
                </button>
            </div>

            <div class="action__handler">
                <a href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>" class="link action__link back">
                    <?php /* @escapeNotVerified */ echo __('Back') ?>
                </a>
            </div>
        </div>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "#giftregistry-sharing-form": {
            "rowBuilder": {
                "rowTemplate": "#add-recipient-tmpl",
                "rowContainer": "#recipients-options",
                "maxRows": "<?php /* @escapeNotVerified */ echo $block->getRecipientsLimit() ?>",
                "maxRowsMsg": "#max-recipient-message",
                "addRowBtn": "#add-recipient-button",
                "rowParentElem": "<div></div>",
                "remEventSelector": "button",
                "btnRemoveSelector": ".action__button.remove",
                "additionalRowClass": "additional",
                "formDataPost": {
                        <?php if (is_array($block->getFormData('recipients'))): ?>
                            "formData": <?php /* @escapeNotVerified */ echo json_encode($block->getFormData('recipients')); ?>,
                        <?php endif; ?>
                    "templateFields": ["recipients-name", "recipients-email"]
                }
            },
            "validation": {}
        }
    }
</script>
