<?php
// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>

<?php if ($block->isWishListAllowed()) : ?>
    <button
        class="product-view__action product-view__action--button product-view__action--wishlist"
        data-post='<?= $block->getWishlistParams() ?>'
        data-action="add-to-wishlist"
        data-testid="add-to-wishlist-button"
    >   
        <svg class="icon">
            <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#heart'); ?>"></use>
        </svg>
    </button>
<?php endif; ?>



<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= $block->getWishlistOptionsJson() ?>
        }
    }
</script>
