<?php
// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
$hasText = $block->getHasText();
$buttonText = $block->getText();
$additionalClass = $block->getAdditionalClass();
$productId = $block->getProduct()->getId();
?>

<?php if ($block->isWishListAllowed()) : ?>
    <button
        class="
            button
            button--icon
            <?= $block->escapeHtmlAttr($additionalClass) ?>
        "
        type="button"
        data-testid="add-to-wishlist-button"
        aria-label="<?= $block->escapeHtmlAttr(__('Add product to wishlist')) ?>"
        data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
        data-action="add-to-wishlist"
        data-mage-init='{
            "wishlistItem": {
                "productId": "<?= $productId ?>",
                "class": "button--icon-filled",
                "addToParams": <?= $block->getAddToWishlistParams($block->getProduct()) ?>
            }
        }'
    >
        <svg
            class="icon button__icon"
            role="presentation"
            focusable="false"
        >
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#heart')); ?>"></use>
        </svg>
        <?php if($hasText): ?>
            <span class="button__text">
                <?= $block->escapeHtml($buttonText) ?>
            </span>
        <?php endif; ?>
    </button>
<?php endif; ?>



<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= $block->getWishlistOptionsJson() ?>
        }
    }
</script>
