<?php
/**
 * @var SelectContact $block
 */

use MageMe\WebForms\Block\Form\Element\Field\Type\SelectContact;

$validationRules = $block->getValidationRules();
$validationDescriptions = $block->getValidationDescriptions();
?>

<select id='<?= $block->getFieldId() ?>'
        name='<?= $block->getFieldName() ?>'
        class='<?= $block->getFieldClass() ?>'
        style='<?= $block->getFieldStyle() ?>'
        <?php if ($validationRules) { ?>
            data-validate="{<?= implode(", ", $validationRules); ?>}"
        <?php } ?>
        <?php foreach ($validationDescriptions as $key => $data) {
            echo $key . '=' . '"' . htmlspecialchars((string)$data) . '"';
        }
        ?>
        <?php if ($block->getIsLabelHidden()) { ?>aria-label="<?= $block->getFieldLabel() ?>"
        <?php } else { ?> aria-labelledby="label_<?= $block->getFieldId() ?>" <?php } ?>
        <?php if ($block->getIsRequired()) { ?>aria-required="true"<?php } ?>
        <?php if ($block->getAutocomplete()) { ?>autocomplete="<?= $block->getAutocomplete() ?>" <?php } ?>
        <?= htmlspecialchars((string)$block->getCustomAttributes()) ?>
>
    <?php
    foreach ($block->getFieldOptions() as $i => $option) {
        $checked = false;
        if ($option["checked"]) {
            $checked = 'selected';
        }
        if (isset($option["value"])) {
            $contact = $block->getContactArray($option["value"]);
            $value = $option["value"];
            if ($option['null']) {
                $value = '';
            }
            if (!empty($option['optgroup']) && !empty($option['label'])) {
                ?>
                <optgroup label="<?= $block->applyTranslation($option['label']); ?>">
                <?php
            } elseif (!empty($option['optgroup_close'])) {
                ?>
                </optgroup>
                <?php
            } else {
                if ($contact) {
                    ?>
                    <option value="<?= $contact["email"] ? $i : $value; ?>" <?= $checked ?>><?= $block->applyTranslation($contact['name']); ?></option>
                    <?php
                }
            }
        }
    }
    ?>
</select>
