<?php
/**
 * Template for filter items block
 *
 * @var $block \Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer
 */
?>
<?php
$datascope = $block->escapeHtmlAttr($this->getFilter()->getRequestVar()) . 'Filter';
?>
<?php if (!empty($filterItems)): ?>
    <div data-bind="scope: '<?= $datascope; ?>'">
        <!-- ko template: getTemplate() --> <!-- /ko -->
    </div>

    <script type="text/x-magento-init">
        {
            "*" : {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "<?= $datascope; ?>": <?= /* @escapeNotVerified */ $this->getJsLayout(); ?>
                    }
                }
            }
        }
    </script>
<?php endif; ?>
