<?php
/**
 * Template for filter items block
 *
 * @var $block \Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer
 */

?>
<button
    class="
        button
        button--icon
        modal-trigger
        filters__trigger
    "
    type="button"
    aria-label="<?= $block->escapeHtmlAttr(__('Open categories filter')) ?>"
    data-modal-trigger="filters-category"
    aria-expanded="false"
    data-mage-init='{ "modal": {
        "mqOpen": "(min-width: 1024px)"
    } }'
>
    <span class="button__text ">
        <?= $block->escapeHtml(__('Category')) ?>
    </span>

    <svg
        class="icon"
        role="presentation"
        focusable="false"
    >
        <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#angle-right')); ?>"></use>
    </svg>
</button>

<div
    class="
        modal
        modal--tertiary
        filters__modal
    "
    role="dialog"
    aria-hidden="true"
    id="filters-category"
    data-modal="filters-category"
    aria-labelledby="filters-categories-title"
>
    <div
        role="document"
        class="
            modal__container
            filters__container
        "
        tabindex="0"
    >
        <div
            class="
                modal__content
                filters__content
            "
        >
            <div
                class="
                    modal__top
                    filters__content-top
                "
            >
                <h2
                    class="
                        modal__heading
                        filters__heading
                    "
                    id="filters-categories-title"
                >
                    <?= $block->escapeHtml(__('Category')) ?>
                </h2>
            </div>

            <div
                class="
                    modal__middle
                    filters__content-middle
                "
            >
                <div
                    class="
                        filter
                        filter--category
                    "
                >
                    <ul class="list categories-list">
                        <?php foreach ($filterItems as $filterItem): ?>
                            <li
                                class="
                                    list__item
                                    categories-list__item
                                "
                            >
                                <?php if ($filterItem->getCount() > 0): ?>
                                    <a
                                        href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                                        class="
                                            link
                                            categories-list__link
                                        "
                                    >

                                        <?= $block->escapeHtml($filterItem->getLabel()) ?>
                                    </a>
                                <?php endif; ?>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>
        </div>

        <button
            class="
                button
                button--icon
                button--rotate-icon
                filters__close-button
                modal__close-button
            "
            type="button"
            aria-label="<?= $block->escapeHtmlAttr(__('Close filters modal')) ?>"
        >
            <svg
                class="
                    icon
                    button__icon
                    modal__close-button-icon
                "
                role="presentation"
                focusable="false"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#close')); ?>"></use>
            </svg>
        </button>
    </div>
</div>
