<?php
/**
 * Template for filter items block
 *
 * @var $block \Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\Slider
 */
?>
<?php
$currencyHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');

$filter = $block->getFilter();
$filterCode = $filter->getRequestVar();
$filterName = $filter->getName();
$filterConfig = json_decode($block->getJsonConfig(), true);

$filterMinValue = $filterConfig['minValue'];
$filterMaxValue = $filterConfig['maxValue'];
$filterMinValueNumber = number_format($filterMinValue, 2);
$filterMaxValueNumber = number_format($filterMaxValue, 2);
$filterCurrentValueFrom = $filterConfig['currentValue']['from'];
$filterCurrentValueTo = $filterConfig['currentValue']['to'];
$filterUrl = $filterConfig['urlTemplate'];
$filterSymbolPattern = $filterConfig['fieldFormat']['pattern'];
$filterSymbol = str_replace('%s', '', $filterSymbolPattern);
?>
<?php if (!($filterMinValueNumber === $filterMaxValueNumber)): ?>
<li
    class="
        dropdown-list__item
        dropdown-list__item--collapse
        filter
        filter--range
    "
>
    <div
        class="
            dropdown-list__label-wrapper
            filter__label-wrapper
        "
    >
        <button
            type="button"
            class="dropdown-list__label"
            aria-controls="<?= $block->escapeHtmlAttr($filterCode); ?>Filter"
            aria-expanded="true"
        >
            <h3 class="filter__heading">
                <?= $block->escapeHtml($filterName); ?>
            </h3>

            <svg
                class="
                    icon
                    dropdown-list__icon
                "
                role="presentation"
                focusable="false"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#angle-down')); ?>"></use>
            </svg>
        </button>
    </div>

    <div
        id="<?= $block->escapeHtmlAttr($filterCode); ?>Filter"
        class="
            dropdown-list__content
            filter__content
        "
        aria-hidden="false"
    >
        <div
            class="more-info"
            data-mage-init='{
                "moreInfo": {
                    "path": "/rest/V1/snowproductattributedescription/description/:attributeCode",
                    "variable": ":attributeCode",
                    "data": "<?= $block->escapeHtmlAttr($filterCode) ?>"
                }
            }'
            aria-hidden="true"
        >
            <button
                class="
                    button
                    button--icon
                    button--fluid
                    more-info__trigger
                "
                type="button"
                aria-expanded="false"
            >
                <span class="button__text">
                    <?= $block->escapeHtml(__('More information')) ?>
                </span>
                <svg
                    class="
                        icon
                        button__icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#info')); ?>"></use>
                </svg>
            </button>

            <div
                class="more-info__content-wrapper"
                aria-hidden="true"
            >
                <div class="more-info__content">
                    <h3 class="more-info__heading">
                        <?= $block->escapeHtml($filterName) ?>
                    </h3>

                    <div class="more-info__data"></div>

                    <button
                        class="
                            button
                            button--icon
                            button--rotate-icon
                            more-info__close
                        "
                        type="button"
                        aria-label="<?= $block->escapeHtmlAttr(__('Close more information')) ?>"
                    >
                        <svg
                            class="icon"
                            role="presentation"
                            focusable="false"
                        >
                            <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#close')); ?>"></use>
                        </svg>
                    </button>
                </div>
            </div>
        </div>

        <div
            class="range-filter filter__range"
            data-mage-init='{ "range": {
                "sliderLabel": "<?= $filterName ?>"
            } }'
        >
            <div
                class="range-filter__slider"
                data-min="<?= $block->escapeHtmlAttr($filterMinValue) ?>"
                data-max="<?= $block->escapeHtmlAttr($filterMaxValue) ?>"
            >
            </div>
            <div class="range-filter__inputs-wrapper ">
                <div
                    class="
                        input
                        range-filter__input
                        range-filter__input--lower
                    "
                >
                    <label
                        class="
                            label
                            range-filter__label
                        "
                        for="<?= $block->escapeHtmlAttr($filterCode) ?>-lower"
                    >
                        <?= $block->escapeHtml(__('Minimum value')) ?>
                    </label>
                    <input
                        class="
                            input__field
                            range-filter__field
                            range-filter__field--lower
                        "
                        id="<?= $block->escapeHtmlAttr($filterCode) ?>-lower"
                        name="range-filter-min"
                        type="number"
                        value="<?= $block->escapeHtmlAttr($filterCurrentValueFrom) ?>"
                        placeholder="<?= $block->escapeHtmlAttr($filterCurrentValueFrom) ?>"
                    >
                </div>
                <span class="range-filter__suffix">
                    <?= $block->escapeHtml($filterSymbol) ?>
                </span>
                <span class="range-filter__dash">-</span>
                <div
                    class="
                        input
                        range-filter__input
                        range-filter__input--upper
                    "
                >
                    <label
                        class="
                            label
                            range-filter__label
                        "
                        for="<?= $block->escapeHtmlAttr($filterCode) ?>-upper"
                    >
                        <?= $block->escapeHtml(__('Maximum value')) ?>
                    </label>
                    <input
                        class="
                            input__field
                            range-filter__field
                            range-filter__field--upper
                        "
                        id="<?= $block->escapeHtmlAttr($filterCode) ?>-upper"
                        name="range-filter-max"
                        type="number"
                        value="<?= $block->escapeHtmlAttr($filterCurrentValueTo) ?>"
                        placeholder="<?= $block->escapeHtmlAttr($filterCurrentValueTo) ?>"
                    >
                </div>
                <span class="range-filter__suffix">
                    <?= $block->escapeHtml($filterSymbol) ?>
                </span>
            </div>
        </div>
        <button
            class="
                button
                range-filter__button
                button--fluid
                margin-vc-sm
            "
            type="button"
            id="<?= $block->escapeHtmlAttr($filterCode) ?>-filter"
            data-filter-url="<?= $block->escapeUrl($filterUrl) ?>"
            href="<?= $block->escapeUrl($filterUrl) ?>"
            data-min="<?= $block->escapeHtmlAttr($filterMinValueNumber) ?>"
            data-max="<?= $block->escapeHtmlAttr($filterMaxValueNumber) ?>"
            data-attribute="<?= $block->escapeHtmlAttr($filterCode) ?>"
            data-mage-init='{ "priceRange": { } }'
        >
            <?= $block->escapeHtml(__('Apply')) ?>
        </button>
    </div>
</li>
<?php endif ?>
