<section class="home__wrapper grid">
    <section class="grid__column grid__column--1-2 home__vertical-grid home__column-left">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-banner-middle-left-top')->toHtml(); ?>
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-banner-middle-left-bottom')->toHtml(); ?>
    </section>
    <section class="grid__column grid__column--1-2 home__column-right">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-banner-middle-right')->toHtml(); ?>
    </section>
</section>
