<section class="home__wrapper grid">
    <div class="grid__column grid__column--1-3 home__third-banner">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-banner-bottom')->toHtml(); ?>
    </div>
    <div class="grid__column grid__column--1-3 home__third-banner">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-banner-bottom')->toHtml(); ?>
    </div>
    <div class="grid__column grid__column--1-3 home__third-banner">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-banner-bottom')->toHtml(); ?>
    </div>
</section>
