<?php /** @var $block \Magento\Company\Block\Company\Management\Info */ ?>
<?php if (!$block->hasCustomerCompany()): ?>
    <div class="message info empty">
        <span><?= $block->escapeHtml(__('You don\'t have a company account yet.')) ?></span>
    </div>
    <?php if ($block->isAllowedRegister()): ?>
        <div class="actions-group margin-top-sm">
            <div class="actions-group__handler">
                <a
                    href="<?= $block->escapeUrl($block->getCreateCompanyAccountUrl()) ?>"
                    class="
                        action
                        create
                        primary
                        button
                        actions-group__button
                    "
                >
                    <?= $block->escapeHtml(__('Create a Company Account')) ?>
                </a>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
