<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>

<div class="container">
    <form class="search"
          id="search_mini_form"
          action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>"
          method="get"
    >
        <div class="search__wrapper">
            <div class="input search__input">
                <label class="input__label"
                       for="search"
                >
                    <?= __('Search'); ?>
                </label>
                <input id="search"
                       data-mage-init='{"quickSearch":{
                            "formSelector":"#search_mini_form",
                            "url":"<?= /* @escapeNotVerified */ $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                            "destinationSelector":"#search_autocomplete"}
                       }'
                       type="text"
                       name="<?= /* @escapeNotVerified */ $helper->getQueryParamName(); ?>"
                       value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText(); ?>"
                       placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...'); ?>"
                       class="input__field"
                       maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength(); ?>"
                       role="combobox"
                       aria-haspopup="false"
                       aria-autocomplete="both"
                       autocomplete="off"
                />
            </div>
            <button type="submit"
                    title="<?= $block->escapeHtml(__('Search')); ?>"
                    class="button search__button"
            >
                <?= /* @escapeNotVerified */ __('Search'); ?>
            </button>
        </div>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <?php echo $block->getChildHtml() ?>
    </form>
</div>
