<div class="file-upload skus">
    <label class="file-upload__label" for="customer_sku_csv">
        <?= /* @escapeNotVerified */ __('File extensions allowed: .csv'); ?>
    </label>

    <div class="file-upload__handler" 
         data-mage-init='{
             "fieldsetControls": {}, 
             "fileChooser": {
                 "fileNameSelector": "[name=<?= /* @escapeNotVerified */ \Magento\AdvancedCheckout\Model\Import::FIELD_NAME_SOURCE_FILE ?>]",
                 "fileNameIndicatorSelector": "[name=<?= /* @escapeNotVerified */ \Magento\AdvancedCheckout\Helper\Data::REQUEST_PARAMETER_SKU_FILE_IMPORTED_FLAG ?>]"
             }
         }'
    >
        <input id="customer_sku_csv" 
               type="file" 
               data-reset="true"
               class="file-upload__field"
               data-mage-init='{"fileUpload": {}}'
               name="<?= /* @escapeNotVerified */ \Magento\AdvancedCheckout\Model\Import::FIELD_NAME_SOURCE_FILE ?>"
        />

        <button type="button"
                class="button file-upload__button reset"
                data-mage-init='{"fieldsetResetControl":{}}'
        >
            <?= /* @escapeNotVerified */ __('Reset')?>
        </button>

        <input type="hidden" 
               value="0" 
               data-reset="true"
               name="<?= /* @escapeNotVerified */ \Magento\AdvancedCheckout\Helper\Data::REQUEST_PARAMETER_SKU_FILE_IMPORTED_FLAG ?>" 
        />

        <span class="file-upload__name">
            <?= /* @escapeNotVerified */ __('File not choosen'); ?>
        </span>
    </div>

    <div class="information">
        <p class="information__text">
            <?= /* @escapeNotVerified */ __('Your csv file must include "sku" and "qty" columns.'); ?>
        </p>
    </div>
</div>
