<?php
    use Magento\AdvancedCheckout\Model\Import as ImportModel;
    use Magento\AdvancedCheckout\Helper\Data as DataHelper;
?>
<div class="file-upload skus">
    <label class="file-upload__label" for="customer_sku_csv">
        <?= __('File extensions allowed: .csv'); ?>
    </label>

    <div class="file-upload__handler"
         data-mage-init='{
             "fieldsetControls": {},
             "fileChooser": {
                 "fileNameSelector": "[name=<?= ImportModel::FIELD_NAME_SOURCE_FILE ?>]",
                 "fileNameIndicatorSelector": "[name=<?= DataHelper::REQUEST_PARAMETER_SKU_FILE_IMPORTED_FLAG ?>]"
             }
         }'
    >
        <input id="customer_sku_csv"
               type="file"
               data-reset="true"
               class="file-upload__field"
               data-mage-init='{"fileUpload": {}}'
               name="<?= ImportModel::FIELD_NAME_SOURCE_FILE ?>"
        />

        <button type="button"
                class="button file-upload__button reset"
                data-mage-init='{"fieldsetResetControl":{}}'
        >
            <?= __('Reset')?>
        </button>

        <input type="hidden"
               value="0"
               data-reset="true"
               name="<?= DataHelper::REQUEST_PARAMETER_SKU_FILE_IMPORTED_FLAG ?>"
        />

        <span class="file-upload__name">
            <?= __('File not choosen'); ?>
        </span>
    </div>

    <div class="information">
        <p class="information__text">
            <?= __('Your csv file must include "sku" and "qty" columns.'); ?>
        </p>
    </div>
</div>
