<?php
// @codingStandardsIgnoreFile
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<?php if ($block->isHomePage()):?>
    <div class="logo">
<?php else: ?>
    <a class="logo"
       href="<?php echo $block->getUrl(''); ?>"
       title="<?php /* @escapeNotVerified */ echo $storeName ?>"
    >
<?php endif ?>
        <img src="<?= $block->getViewFileUrl('images/logo.svg'); ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             class="logo__image"
        />
<?php if ($block->isHomePage()):?>
</div>
<?php else:?>
    </a>
<?php endif?>
