<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <a 
        class="button button--icon cart-list-item__actions-item"
        href="<?= $escaper->escapeUrl($block->getConfigureUrl()); ?>"
        title="<?= $escaper->escapeHtmlAttr(__('Edit item parameters')); ?>"
        data-testid="cart-edit-item-link"
    >
        <svg class="button__icon">
            <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#edit')); ?>"></use>
        </svg>
   </a>
<?php endif ?>
