<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <a
        class="
            button
            button--icon
            button--icon-light
            cart-list-item__action
        "
        href="<?= $block->getConfigureUrl(); ?>"
        title="<?= $block->escapeHtml(__('Edit item parameters')); ?>"
        data-testid="cart-edit-item-link"
    >
        <svg class="icon button__icon cart-list-item__action-icon">
            <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#edit'); ?>"></use>
        </svg>
   </a>
<?php endif ?>
