<button
    type="button"
    title="<?= $escaper->escapeHtmlAttr(__('Remove item')); ?>"
    class="button button--icon cart-list-item__actions-item"
    data-post='<?= /* @noEscape */ $block->getDeletePostJson(); ?>'
    data-testid="cart-delete-item"
>
    <svg
        class="button__icon"
        role="presentation"
        focusable="false"
    >
        <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#remove')); ?>"></use>
    </svg>
</button>
