<button
    type="button"
    title="<?= $block->escapeHtmlAttr(__('Remove item')) ?>"
    class="
        button
        button--icon
        button--icon-light
        cart-list-item__action
    "
    data-post='<?= $block->getDeletePostJson() ?>'
>
    <svg
        class="
            icon
            button__icon
            cart-list-item__action-icon
        "
        role="presentation"
        focusable="false"
    >
        <title><?= __('Remove product') ?></title>
        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#remove')) ?>"></use>
    </svg>
</button>
