<button
    type="button"
    title="<?= $block->escapeHtmlAttr(__('Remove item')) ?>"
    class="
        button
        button--icon
        cart-list-item__action
    "
    data-post='<?= /* @noEscape */ $block->getDeletePostJson() ?>'
>
    <svg
        class="
            icon
            button__icon
            cart-list-item__action-icon
        "
        role="presentation"
        focusable="false"
    >
        <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#remove')) ?>"></use>
    </svg>
</button>
