<?php
/**
 * @var \Magento\Framework\View\Element\AbstractBlock $block
 */

// We should use strlen function because coupon code could be "0", converted to bool will lead to false
$hasCouponCode = (bool) strlen($block->getCouponCode());
?>
<div
    class="block discount"
    id="block-discount"
    data-mage-init='{
        "collapsible":{
            "active": <?= $hasCouponCode ? 'true' : 'false' ?>,
            "openedState": "active",
            "saveState": false
        }
    }'
>
    <div data-role="title" class="discount__title">
        <span 
            class="discount__title-text"
            data-testid="apply-discount-title"  
        >
            <?= $block->escapeHtml(__('Apply Discount Code')) ?>
        </span>
        <svg class="icon discount__title-icon">
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#arrow-down')) ?>"></use>
        </svg>
    </div>
    <div
        class="content discount__content"
        data-role="content"
        aria-labelledby="block-discount-heading"
    >
        <form
            id="discount-coupon-form"
            class="form"
            action="<?= $block->escapeUrl($block->getUrl('checkout/cart/couponPost')) ?>"
            method="post"
            data-mage-init='{
                "discountCode":{
                    "couponCodeSelector": "#coupon_code",
                    "removeCouponSelector": "#remove-coupon",
                    "applyButton": "button.action.apply",
                    "cancelButton": "button.action.cancel"
                }
            }'
        >
            <div
                class="
                    fieldset
                    form__content
                    coupon
                    discount__controls
                    <?php $block->escapeHtmlAttr($hasCouponCode) ? 'applied' : '' ?>
                "
            >
                <input type="hidden" name="remove" id="remove-coupon" value="0">
                <div class="input discount__input">
                    <label for="coupon_code" class="label label--hidden">
                        <?= $block->escapeHtml(__('Enter discount code')); ?>
                    </label>
                    <input
                        type="text"
                        class="input-text input__field discount__field"
                        id="coupon_code"
                        name="coupon_code"
                        value="<?= $block->escapeHtml($block->getCouponCode()); ?>"
                        placeholder="<?= $block->escapeHtmlAttr(__('Enter discount code')) ?>"
                    >
                </div>
                <?php if (!$hasCouponCode) :?>
                    <button
                        class="action apply button button--apply discount__button"
                        type="button"
                        value="<?= $block->escapeHtmlAttr(__('Apply Discount')) ?>"
                        data-testid="apply-discount-button"
                    >
                        <?= $block->escapeHtml(__('Apply Discount')); ?>
                    </button>
                <?php else: ?>
                    <button
                        type="button"
                        class="button action cancel button--cancel discount__button"
                        value="<?= $block->escapeHtmlAttr(__('Cancel Coupon')) ?>"
                    >
                        <?= $block->escapeHtml(__('Cancel Coupon')) ?>
                    </button>
                <?php endif; ?>
            </div>
            <?php if (!$hasCouponCode) : ?>
                <?= /* @noEscape */ $block->getChildHtml('captcha') ?>
            <?php endif; ?>
        </form>
    </div>
</div>
