<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>
<?php $mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form
    action="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
    method="post"
    id="form-validate"
    data-mage-init='{
        "Magento_Checkout/js/action/update-shopping-cart": {
            "validationURL" : "<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
            "updateCartActionContainer": "#update_cart_action_container"
        }
    }'
    class="form form-cart cart__products-list"
>
    <?= $block->getBlockHtml('formkey') ?>
    <div
        id="shopping-cart-table"
        data-mage-init='{
            "shoppingCart":{
                "emptyCartButton": "cart-actions__clear",
                "updateCartActionContainer": "#update_cart_action_container"
            }
        }'
    >
        <?php foreach ($block->getItems() as $_item): ?>
            <?= $block->getItemHtml($_item); ?>
        <?php endforeach ?>
        <div class="cart-actions">
            <?php if ($block->getContinueShoppingUrl()): ?>
                <a
                    class="
                        button
                        button--secondary
                        button--link
                        cart-actions__button
                        cart-actions__button--continue
                    "
                    href="<?= $escaper->escapeUrl($block->getContinueShoppingUrl()) ?>"
                    title="<?= $escaper->escapeHtmlAttr(__('Continue Shopping')) ?>"
                    data-testid="continue-shopping-link"
                >
                    <?= $escaper->escapeHtml(__('Continue Shopping')) ?>
                </a>
            <?php endif; ?>
            <?php if ($block->getViewModel()->isClearShoppingCartEnabled()): ?>
                <button
                    type="button"
                    name="update_cart_action"
                    data-cart-empty=""
                    value="empty_cart"
                    title="<?= $escaper->escapeHtmlAttr(__('Clear Shopping Cart')) ?>"
                    class="
                        button
                        button--secondary
                        cart-actions__button
                        cart-actions__clear
                    "
                    id="empty_cart_button"
                >
                    <?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?>
                </button>
            <?php endif ?>

            <button
                type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $escaper->escapeHtmlAttr(__('Update Shopping Cart')) ?>"
                class="button button--secondary cart-actions__button"
                data-testid="update-cart-button"
            >
                <?= $escaper->escapeHtml(__('Update Shopping Cart')) ?>
            </button>
            <input
                type="hidden"
                value=""
                id="update_cart_action_container"
                data-cart-item-update=""
            >
        </div>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions'); ?>
<?= $block->getChildHtml('shopping.cart.table.after'); ?>
