<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>
<?php if (!$block->hasError()): ?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
    <?php foreach ($methods as $method): ?>
        <?php if ($methodHtml = $block->getMethodHtml($method)): ?>
            <div class="cart-summary__item">
                <?= $methodHtml; ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
