<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>
<?php if (!$block->hasError()): ?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>

    <?php foreach ($methods as $method): ?>
        <?php if ($methodHtml = $block->getMethodHtml($method)): ?>
            <?= $block->escapeHtml($methodHtml) ?>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
