<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>
<?php if (!$block->hasError()): ?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
    <?php foreach ($methods as $method): ?>
        <?php $methodHtml = $block->getMethodHtml($method); ?>
        <?php if (trim($methodHtml) !== '') :?>
            <div class="cart-summary__item">
                <?= /* @noEscape */ $methodHtml; ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
