<?php /** @var $block \Magento\Checkout\Block\Cart\Shipping */ ?>

<div
    id="block-shipping"
    class="
        shipping
        shipping-estimation
        cart-summary__item
    "
    data-mage-init='{
        "collapsible":{
            "openedState": "active",
            "saveState": true
        }
    }'
>
    <div
        data-role="title"
        class="shipping-estimation__title"
        data-testid="shippin-estimation-title"
    >
        <span class="shipping-estimation__title-text">
            <?= $block->getQuote()->isVirtual()
                ? $escaper->escapeHtml(__('Estimate Tax'))
                : $escaper->escapeHtml(__('Estimate Shipping and Tax'));
            ?>
        </span>
        <svg class="shipping-estimation__title-icon">
            <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#arrow-down')); ?>"></use>
        </svg>
    </div>
    <div
        id="block-summary"
        data-bind="scope:'block-summary'"
        class="content shipping-estimation__content"
        data-role="content"
    >
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#block-summary": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout(); ?>
                }
            }
        </script>

        <?php
        $serializedCheckoutConfig = /* @noEscape */ $block->getSerializedCheckoutConfig();
        $scriptString = <<<script
            window.checkoutConfig = {$serializedCheckoutConfig};
            window.customerData = window.checkoutConfig.customerData;
            window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
            require([
                'mage/url',
                'Magento_Ui/js/block-loader'
            ], function(url, blockLoader) {
                blockLoader(
                    "{$escaper->escapeJs($escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')))}"
                );
                return url.setBaseUrl('{$escaper->escapeJs($escaper->escapeUrl($block->getBaseUrl()))}');
            })
        script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    </div>
</div>
