<?php
/**
 * Shopping cart totals template
 * @var $block \Magento\Checkout\Block\Cart\Totals
 */
?>
<div id="cart-totals"
     class="cart-summary__item cart-totals"
     data-bind="scope:'block-totals'"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#cart-totals": {
                "Magento_Ui/js/core/app": <?= $block->getJsLayout(); ?>
            }
        }
    </script>
</div>
