<?php
/** @var \Magento\Catalog\Pricing\Render\ConfiguredPriceBox $block */
$schema = ($block->getZone() == 'item_view');
$idSuffix = $block->getIdSuffix() ?: '';
?>
<?php if ($block->hasSpecialPrice()) : ?>
    <div class="price-as-configured">
        <span class="price__value price__value--special">
            <?= /* @noEscape */ $block->renderAmount(
                $block->getConfiguredPrice()->getAmount(),
                [
                    'display_label'     => $block->escapeHtml(__('Special Price')),
                    'price_id'          => $block->escapeHtml($block->getPriceId('product-price-' . $idSuffix)),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema,
                ]
            ); ?>
        </span>
        <span class="price__value price__value--old">
            <?= /* @noEscape */ $block->renderAmount(
                $block->getConfiguredRegularPrice()->getAmount(),
                [
                    'display_label'     => $block->escapeHtml(__('Regular Price')),
                    'price_id'          => $block->escapeHtml($block->getPriceId('old-price-' . $idSuffix)),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true,
                ]
            ); ?>
        </span>
    </div>
<?php else : ?>
    <?php
    $priceLabel = ($block->getPriceLabel() !== null)
        ? $block->getPriceLabel()
        : '';
    ?>
    <div class="price-as-configured">
        <span class="price__value">
            <?= /* @noEscape */ $block->renderAmount(
                $block->getConfiguredPrice()->getAmount(),
                [
                    'display_label'     => $block->escapeHtml($priceLabel),
                    'price_id'          => $block->escapeHtml($block->getPriceId('product-price-' . $idSuffix)),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema,
                ]
            ); ?>
        </span>
    </div>
<?php endif; ?>
