<?php
/** @var $block Magento\RequisitionList\Block\Requisition\View\Details */
?>
<a
    class="
        button
        button--link
        action
        export
        padding-0
        margin-right-xs
    "
    href="<?= $block->escapeUrl($block->getViewModel()->getExportUrl()) ?>"
    data-mobile-label="<?= $block->escapeHtmlAttr(__('Export')) ?>"
>
    <?= $block->escapeHtml(__('Export')) ?>
</a>
