<?php if ($crumbs && is_array($crumbs)): ?>
    <div class="breadcrumbs container">
        <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
            <?php if ($crumbInfo['link']): ?>
                <span class="breadcrumbs__item">
                    <a
                        href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>"
                        class="breadcrumbs__link link--invert"
                        title="<?= $block->escapeHtml($crumbInfo['title']) ?>"
                    >
                        <?= $block->escapeHtml($crumbInfo['label']) ?>
                    </a>
                </span>
            <?php else: ?>
                <span class="breadcrumbs__item">
                    <?= $block->escapeHtml($crumbInfo['label']) ?>
                </span>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
