<?php
// @codingStandardsIgnoreFile
/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<?php switch ($block->getShowPart()):
    case 'welcome': ?>
        <li class="links-list__item" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span class="links-list__msg-label"
                  data-bind="text: new String('<?php echo $block->escapeHtml(__('Welcome, %1!', '%1'));?>').replace('%1', customer().firstname)"
            ></span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span class="links-list__msg-label"
                  data-bind="html:'<?=$block->escapeHtml($welcomeMessage) ?>'"
            ></span>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php break; ?>

    <?php case 'other': ?>
        <?php echo $block->getChildHtml(); ?>
    <?php break; ?>

<?php endswitch; ?>
