<?php
$modalId = $block->getPopupId();
$cmsBlockId = $block->getCmsBlockId();
?>
<?php if ($modalId && $cmsBlockId): ?>
    <div
        role="dialog"
        aria-hidden="true"
        id="<?= $block->escapeHtmlAttr($modalId); ?>"
        data-modal="<?= $block->escapeHtmlAttr($modalId); ?>"
        class="modal"
    >
        <div
            class="modal__container"
            role="document"
            tabindex="0"
        >
            <div class="modal__content">
                <?= $block
                        ->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId($cmsBlockId)
                        ->toHtml();
                ?>
            </div>
            <button
                class="
                    button
                    button--icon
                    button--rotate-icon
                    modal__close-button
                "
                type="button"
                aria-label="<?= $block->escapeHtmlAttr(__('Close modal')) ?>"
            >
                <svg
                    class="
                        icon
                        button__icon
                        modal__close-button-icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#close')); ?>"></use>
                </svg>
            </button>
        </div>
    </div>
<?php endif ?>
