<?php
    $img480 = $block->getImg480();
    $img768 = $block->getImg768();
    $img960 = $block->getImg960();
    $img1024 = $block->getImg1024();
    $img1328 = $block->getImg1328();

    $img480x2 = $block->getImg4802x();
    $img768x2 = $block->getImg7682x();
    $img960x2 = $block->getImg9602x();
    $img1024x2 = $block->getImg10242x();
    $img1328x2 = $block->getImg13282x();

    $imgDefault = $block->getImgDefault() ? $block->getImgDefault() : $img480;

    $imgFull = $block->getImgFull() ? $block->getImgFull() : $imgDefault;
    $imgFullx2 = $block->getImgFull2x() ? $block->getImgFull2x() : false;

    $pictureClass = $block->getPictureClass();
    $imgClass = $block->getImgClass();
    $pictureAlt = $block->getPictureAlt();
    $pictureFullUrl = $block->getPictureFullUrl();
    $mediaUrl = $this->helper('Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl();

    if ($pictureFullUrl) {
        $mediaUrl = false;
    }

    $aspectRatioWidth = $block->getImgRatioWidth();
    $aspectRatioHeight = $block->getImgRatioHeight();

    $pictureAspectRatio = true;

    if ($aspectRatioHeight && $aspectRatioWidth) {
        $pictureAspectRatio = ($aspectRatioHeight / $aspectRatioWidth) * 100;
    }

    if ($aspectRatioHeight && $aspectRatioWidth) {
        $pictureClass .= ' ratio-container';
        $imgClass .= ' ratio-image';
    }
?>
<?php if ($pictureClass): ?>
    <picture
        class="
            image 
            <?= $block->escapeHtmlAttr($pictureClass) ?>
        "
        <?php if($aspectRatioHeight && $aspectRatioWidth): ?>
            style="padding-bottom: <?= $block->escapeHtmlAttr($pictureAspectRatio) . '%'; ?>"
        <?php endif; ?>
    >
        <?php if ($img480): ?>
            <source
                data-srcset="
                    <?= $block->escapeUrl($mediaUrl . $img480) ?>
                    <?php if ($img480x2): ?>
                        <?= ' 1x, ' . $block->escapeUrl($mediaUrl . $img480x2) . ' 2x' ?>
                    <?php endif; ?>
                "
                media="(max-width: 479px)"
            />
        <?php endif ?>
        <?php if ($img768): ?>
            <source
                data-srcset="
                    <?= $block->escapeUrl($mediaUrl . $img768) ?>
                    <?php if ($img768x2): ?>
                        <?= ' 1x, ' . $block->escapeUrl($mediaUrl . $img768x2) . ' 2x' ?>
                    <?php endif; ?>
                "
                media="(max-width: 767px)"
            />
        <?php endif ?>
        <?php if ($img960): ?>
            <source
                data-srcset="
                    <?= $block->escapeUrl($mediaUrl . $img960) ?>
                    <?php if ($img960x2): ?>
                        <?= ' 1x, ' . $block->escapeUrl($mediaUrl . $img960x2) . ' 2x' ?>
                    <?php endif; ?>
                "
                media="(max-width: 959px)"
            />
        <?php endif ?>
        <?php if ($img1024): ?>
            <source
                data-srcset="
                    <?= $block->escapeUrl($mediaUrl . $img1024) ?>
                    <?php if ($img1024x2): ?>
                        <?= ' 1x, ' . $block->escapeUrl($mediaUrl . $img1024x2) . ' 2x' ?>
                    <?php endif; ?>
                "
                media="(max-width: 1023px)"
            />
        <?php endif ?>
        <?php if ($img1328): ?>
            <source
                data-srcset="
                    <?= $block->escapeUrl($mediaUrl . $img1328) ?>
                    <?php if ($img1328x2): ?>
                        <?= ' 1x, ' . $block->escapeUrl($mediaUrl . $img1328x2) . ' 2x' ?>
                    <?php endif; ?>
                "
                media="(max-width: 1327px)"
            />
        <?php endif ?>
        <?php if ($imgFull): ?>
            <source
                data-srcset="
                    <?= $block->escapeUrl($mediaUrl . $imgFull) ?>
                    <?php if ($imgFullx2): ?>
                        <?= ' 1x, ' . $block->escapeUrl($mediaUrl . $imgFullx2) . ' 2x' ?>
                    <?php endif; ?>
                "
                media=""
            />
        <?php endif ?>
        <img
            class="
                lazyload 
                <?= $block->escapeHtmlAttr($imgClass) ?>
            "
            data-src="<?= $block->escapeUrl($mediaUrl . $imgDefault) ?>"
            alt="<?= $block->escapeHtmlAttr($pictureAlt) ?>"
            src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAABCAQAAABN/Pf1AAAAC0lEQVR42mNkwAIAACoAAgu1Hc4AAAAASUVORK5CYII="
        />
    </picture>
<?php endif ?>
