<?php
$anchor = $block->getLinkAnchor();
$label = $block->getLinkText();
$cssClass = $block->hasCssClass() ? $block->getCssClass() : '';
?>
<?php if (is_array($anchor) && is_array($label)): ?>
    <ul class="list">
        <?php foreach ($anchor as $key => $value): ?>
            <li class="list__item <?= $key ?>">
                <a
                    href="<?= $block->escapeHtmlAttr($value) ?>"
                    class="skip-nav <?= $block->escapeHtmlAttr($cssClass) ?>"
                    data-mage-init='{"skipNav": {} }'
                >
                    <?= $label[$key]; ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
<?php else: ?>
    <a
        href="<?= $block->escapeHtmlAttr($anchor) ?>"
        class="skip-nav <?= $block->escapeHtmlAttr($cssClass) ?>"
        data-mage-init='{"skipNav": {} }'
    >
        <?= $label; ?>
    </a>
<?php endif; ?>
