<?php
/**
 * use before-slides as slider_html to get html before slides
 * use after-slides as slider_html to get html after slides
 */
?>

<?php
//slider basis
$sliderHtml = $block->getSliderHtml();
$sliderClass = $block->getSliderClass();
$wrapperClass = $block->getWrapperClass();

//slider config
$sliderMobileFirst = $block->getMobileFirst();
$sliderInfinite = $block->getInfinite();
$sliderCenterMode = $block->getCenterMode();
$sliderDots = $block->getDots();
$sliderArrows = $block->getArrows();
$sliderAutoplay = $block->getAutoplay();
$sliderAutoplaySpeed = $block->getAutoplaySpeed();
$sliderPauseOnFocus = $block->getPauseOnFocus();
$sliderPauseOnHover = $block->getPauseOnHover();
$sliderSlidesToShow = $block->getSlidesToShow();
$sliderSlidesToScroll = $block->getSlidesToScroll();
$sliderResponsiveConfig = $block->getResponsiveConfig();

//slider defaults
$sliderMobileFirst = ($sliderMobileFirst === 'no') ? 'false' : 'true';
$sliderInfinite = ($sliderInfinite === 'no') ? 'false' : 'true';
$sliderCenterMode = ($sliderCenterMode === 'yes') ? 'true' : 'false';
$sliderDots = ($sliderDots === 'no') ? 'false' : 'true';
$sliderArrows = ($sliderArrows === 'no') ? 'false' : 'true';
$sliderAutoplay = ($sliderAutoplay === 'yes') ? 'true' : 'false';
$sliderAutoplaySpeed = $sliderAutoplaySpeed ? $block->escapeHtmlAttr($sliderAutoplaySpeed) : '3000';
$sliderPauseOnFocus = ($sliderPauseOnFocus === 'no') ? 'false' : 'true';
$sliderPauseOnHover = ($sliderPauseOnHover === 'no') ? 'false' : 'true';
$sliderSlidesToShow = $sliderSlidesToShow ? $block->escapeHtmlAttr($sliderSlidesToShow) : '1';
$sliderSlidesToScroll = $sliderSlidesToScroll ? $block->escapeHtmlAttr($sliderSlidesToScroll) : '1';
$sliderResponsiveConfig = $sliderResponsiveConfig ? $block->escapeHtmlAttr($sliderResponsiveConfig) : 'false';
$sliderSwipeToSlide = ($sliderPauseOnHover === 'no') ? 'false' : 'true';

//slider data
$sliderDisplayTitle = $block->getDisplayTitle();
$sliderTitle = $block->getSliderTitle();
$sliderTitleClass = $block->getTitleClass();
$sliderContentBefore = $block->getContentBefore();
$sliderContentAfter = $block->getContentAfter();
?>
<?php if ($sliderHtml == 'before-slides'): ?>
    <?php if ($wrapperClass): ?>
        <div class="<?= $block->escapeHtmlAttr($wrapperClass) ?>">
    <?php endif; ?>

    <div
        class="
            slider
            slider--loading
            <?= $block->escapeHtmlAttr($sliderClass) ?>
        "
        data-mage-init='{
            "slider": {
                "mobileFirst"        : <?= $sliderMobileFirst ?>,
                "infinite"           : <?= $sliderInfinite ?>,
                "centerMode"         : <?= $sliderCenterMode ?>,
                "dots"               : <?= $sliderDots ?>,
                "arrows"             : <?= $sliderArrows ?>,
                "autoplay"           : <?= $sliderAutoplay ?>,
                "autoplaySpeed"      : <?= $sliderAutoplaySpeed ?>,
                "pauseOnFocus"       : <?= $sliderPauseOnFocus ?>,
                "pauseOnHover"       : <?= $sliderPauseOnHover ?>,
                "slidesToShow"       : <?= $sliderSlidesToShow ?>,
                "slidesToScroll"     : <?= $sliderSlidesToScroll ?>,
                "responsiveConfig"   : <?= $sliderResponsiveConfig ?>,
                "swipeToSlide"       : <?= $sliderSwipeToSlide ?>,
                "dotsClass"          : "slider__dots",
                "loadingClass"       : "slider--loading",
                "loaderVisibleClass" : "loader--visible",
                "elementLoader"      : ".loader",
                "elementSlides"      : ".slider__slides",
                "elementNavPrev"     : ".slider__prev",
                "elementNavNext"     : ".slider__next"
            }
        }'
    >
        <div
            data-role="loader"
            class="loader loader--visible"
            aria-live="polite"
            aria-label="<?= $block->escapeHtmlAttr(__('Do not refresh the page')); ?>"
        >
            <div class="loader__icon"></div>
        </div>

        <?php if ($sliderDisplayTitle): ?>
            <div class="slider__heading">
                <span class="<?= $block->escapeHtmlAttr($sliderTitleClass) ?>">
                    <?= $sliderTitle ?>
                </span>
            </div>
        <?php endif ?>

        <?php if ($sliderContentBefore): ?>
            <div class="slider__before">
                <?= $sliderContentBefore ?>
            </div>
        <?php endif ?>

        <div class="slider__handler">
            <div class="slider__container">
                <div class="slider__slides">

<?php endif; //before-slides end ?>
<?php if ($sliderHtml == 'after-slides'): ?>

                </div>
            </div>

            <?php if ($sliderArrows === 'true'): ?>
                <div class="slider__navigation">
                    <div class="slider__arrows">
                        <button
                            class="
                                button
                                button--icon
                                button--icon-border
                                slider__nav-button
                                slider__prev
                            "
                            type="button"
                            aria-label="<?= $block->escapeHtmlAttr(__('Go to previous slide')) ?>"
                        >
                            <svg
                                class="
                                    icon
                                    button__icon
                                    slider__nav-icon
                                "
                                role="img"
                            >
                                <title><?= __('Arrow left') ?></title>
                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#arrow-left')); ?>"></use>
                            </svg>
                        </button>
                        <button
                            class="
                                button
                                button--icon
                                button--icon-border
                                slider__nav-button
                                slider__next
                            "
                            type="button"
                            aria-label="<?= $block->escapeHtmlAttr(__('Go to next slide')) ?>"
                        >
                            <svg
                                class="
                                    icon
                                    button__icon
                                    slider__nav-icon
                                "
                                role="img"
                            >
                                <title><?= __('Arrow right') ?></title>
                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#arrow-right')); ?>"></use>
                            </svg>
                        </button>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <?php if ($sliderContentAfter): ?>
            <div class="slider__after">
                <?= $sliderContentAfter ?>
            </div>
        <?php endif ?>
    </div>

    <?php if ($wrapperClass): ?>
        </div>
    <?php endif; ?>
<?php endif; //after-slides end ?>
