<ul class="list list--horizontal">
    <li class="list__item">
        <a class="button button--link button--icon"
           title="<?php /* @escapeNotVerified */echo __('Facebook') ?>"
           href="#"
        >
            <svg class="button__icon">
                <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#facebook'); ?>"></use>
            </svg>
        </a>
    </li>
    <li class="list__item">
        <a class="button button--link button--icon"
           title="<?php /* @escapeNotVerified */echo __('Twitter') ?>"
           href="#"
        >
            <svg class="button__icon">
                <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#twitter'); ?>"></use>
            </svg>
        </a>
    </li>
    <li class="list__item">
        <a class="button button--link button--icon"
           title="<?php /* @escapeNotVerified */echo __('Linkedin') ?>"
           href="#"
        >
            <svg class="button__icon">
                <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#linkedin'); ?>"></use>
            </svg>
        </a>
    </li>
    <li class="list__item">
        <a class="button button--link button--icon"
           title="<?php /* @escapeNotVerified */echo __('Google+') ?>"
           href="#"
        >
            <svg class="button__icon">
                <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#google-plus'); ?>"></use>
            </svg>
        </a>
    </li>
</ul>
