<ul class="social-list">
    <li class="social-list__item">
        <a class="button button--icon"
           title="<?php /* @escapeNotVerified */echo __('Facebook') ?>"
           href="#"
        >
            <span class="social-list__icon">
                <svg class="button__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#facebook'); ?>"></use>
                </svg>
            </span>
        </a>
    </li>
    <li class="social-list__item">
        <a class="button button--icon"
           title="<?php /* @escapeNotVerified */echo __('Twitter') ?>"
           href="#"
        >
            <span class="social-list__icon">
                <svg class="button__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#twitter'); ?>"></use>
                </svg>
            </span>
        </a>
    </li>
    <li class="social-list__item">
        <a class="button button--icon"
           title="<?php /* @escapeNotVerified */echo __('Linkedin') ?>"
           href="#"
        >
            <span class="social-list__icon">
                <svg class="button__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#linkedin'); ?>"></use>
                </svg>
            </span>
        </a>
    </li>
    <li class="social-list__item">
        <a class="button button--icon"
           title="<?php /* @escapeNotVerified */echo __('Google+') ?>"
           href="#"
        >
            <span class="social-list__icon">
                <svg class="button__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#google-plus'); ?>"></use>
                </svg>
            </span>
        </a>
    </li>
</ul>
