<?php
    $svgIcon = $block->getIcon();
    $svgIconClass = $block->getIconClass();
    $svgIconTitle = $block->getIconTitle();
?>
<?php if ($svgIcon): ?>
    <svg
        class="
            icon
            <?= $block->escapeHtmlAttr($svgIconClass) ?>
        "
        role="img"
    >
        <?php if ($svgIconTitle): ?>
            <title><?= $block->escapeHtml($svgIconTitle) ?></title>
        <?php endif ?>
        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl("images/icons-sprite.svg#" . $svgIcon)) ?>"></use>
    </svg>
<?php endif ?>
