<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
?>

<?php if (!empty($block->getPageHeading())): ?>
    <div class="title-wrapper row row--no-margins between-xs <?= $escaper->escapeHtmlAttr($block->getCssClass()) ?>">
        <h1
            class="heading heading--page"
            <?php if ($block->getId()) : ?>
                id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>"
            <?php endif; ?>
            <?= $escaper->escapeHtmlAttr($block->getAddBaseAttributeAria() ? 'aria-labelledby="' . $block->getAddBaseAttributeAria() . '"' : ''); ?>
        >
            <span
                class="base"
                data-ui-id="page-title-wrapper"
                <?= /* @noEscape */ $block->getAddBaseAttribute() ?>
            >
                 <?= $escaper->escapeHtml($block->getPageHeading()); ?>
            </span>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif ?>
