<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
?>

<?php if (!empty($block->getPageHeading())): ?>
    <div class="title-wrapper row row--no-margins between-xs <?= $block->getCssClass() ?>">
        <h1
            class="heading heading--page"
            <?= $block->getId() ? 'id="' . $block->getId() . '"' : ''; ?>
            <?= $block->getAddBaseAttributeAria() ? 'aria-labelledby="' . $block->getAddBaseAttributeAria() . '"' : ''; ?>
        >
            <span
                class="base"
                data-ui-id="page-title-wrapper"
                <?= $block->getAddBaseAttribute() ?>
            >
                 <?= $block->escapeHtml($block->getPageHeading()); ?>
            </span>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif ?>
