<?php
/**
 * Multishipping checkout billing information
 *
 * @var $block \Magento\Multishipping\Block\Checkout\Billing
 * @var $escaper \Magento\Framework\Escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php $checkoutConfig = /* @noEscape */ $block->getCheckoutData()->getSerializedCheckoutConfigs();
$scriptString = <<<script
    window.checkoutConfig = {$checkoutConfig};
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData = window.checkoutConfig.customerData;
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<div
    id="checkout"
    data-bind="scope:'checkoutMessages'"
>
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "checkoutMessages": {
                            "component": "Magento_Ui/js/view/messages",
                            "displayArea": "messages"
                        }
                    }
                }
            }
        }
    </script>
</div>
<form
    action="<?= $escaper->escapeUrl($block->getPostActionUrl()); ?>"
    method="post"
    id="multishipping-billing-form"
    class="form multicheckout billing"
>
    <div class="block-billing margin-bottom-m">
        <div class="dashboard-items">
            <div class="row dashboard-items__content">
                <div class="col-sm-6 dashboard-items__item">
                    <h3 class="heading dashboard-items__subtitle">
                        <?= $escaper->escapeHtml(__('Billing Address')); ?>
                    </h3>
                    <div class="margin-bottom-m">
                        <address>
                            <?= /* @noEscape */ $block->getCheckoutData()->getAddressHtml($block->getAddress()); ?>
                        </address>
                    </div>
                    <div class="actions-group margin-bottom-xl">
                        <div class="actions-group__handler">
                            <a
                                href="<?= $escaper->escapeUrl($block->getSelectAddressUrl()); ?>"
                                class="
                                    link
                                    actions-group__link
                                "
                            >
                                <?= $escaper->escapeHtml(__('Change')); ?>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 dashboard-items__item">
                    <h3 class="heading dashboard-items__subtitle">
                        <?= $escaper->escapeHtml(__('Payment Method')); ?>
                    </h3>
                    <div class="margin-bottom-m">
                        <fieldset class="fieldset">
                            <legend class="fieldset__legend fieldset__legend--hidden">
                                <?= $escaper->escapeHtml(__('Payment Method')); ?>
                            </legend>
                            <div class="box-content">
                                <?= $block->getChildHtml('payment_methods_before') ?>
                                <?php /* Payment methods forms list */ ?>
                                <dl
                                    class="checkout-payment-method"
                                    id="payment-methods"
                                >
                                    <?php
                                    $methods = $block->getMethods();
                                    $methodsCount = count($methods);
                                    $methodsForms = $block->hasFormTemplates() ? $block->getFormTemplates() : [];

                                    foreach ($methods as $_method):
                                        $code = $_method->getCode();
                                        $checked = $block->getSelectedMethodCode() === $code;

                                        if (isset($methodsForms[$code])) {
                                            $block->setMethodFormTemplate($code, $methodsForms[$code]);
                                        }
                                    ?>
                                        <div data-bind="scope: 'payment_method_<?= $escaper->escapeHtml($code); ?>'">
                                            <dt class="item-title radio__handler">
                                                <?php if ($methodsCount > 1): ?>
                                                    <input
                                                        type="radio"
                                                        id="p_method_<?= $escaper->escapeHtmlAttr($code); ?>"
                                                        value="<?= $escaper->escapeHtmlAttr($code); ?>"
                                                        name="payment[method]"
                                                        title="<?= $escaper->escapeHtmlAttr($_method->getTitle()) ?>"
                                                        data-bind="
                                                            value: getCode(),
                                                            checked: isChecked,
                                                            click: selectPaymentMethod,
                                                            visible: isRadioButtonVisible()
                                                        "
                                                        aria-labelledby="payment-info-label"
                                                        <?php if ($checked): ?>
                                                            checked="checked"
                                                        <?php endif; ?>
                                                        class="radio__field"
                                                    />
                                                <?php else: ?>
                                                    <input
                                                        type="radio"
                                                        id="p_method_<?= $escaper->escapeHtml($code); ?>"
                                                        value="<?= $escaper->escapeHtmlAttr($code); ?>"
                                                        name="payment[method]"
                                                        data-bind="
                                                            value: getCode(),
                                                            afterRender: selectPaymentMethod
                                                        "
                                                        aria-labelledby="payment-info-label"
                                                        checked="checked"
                                                        class="
                                                            radio__field
                                                            solo
                                                            method
                                                        "
                                                    />
                                                <?php endif; ?>
                                                <label
                                                    for="p_method_<?= $escaper->escapeHtml($code); ?>"
                                                    class="radio__label"
                                                >
                                                    <?= $escaper->escapeHtml($_method->getTitle()) ?>
                                                </label>
                                            </dt>
                                            <?php if ($html = $block->getChildHtml('payment.method.' . $code)): ?>
                                                <dd class="item-content <?= $checked ? '' : 'no-display'; ?>">
                                                    <?= /* @noEscape */ $html; ?>
                                                </dd>
                                            <?php endif; ?>
                                        </div>
                                    <?php endforeach; ?>
                                </dl>
                                <?= $block->getChildHtml('payment_methods_after') ?>
                                <?= $block->getChildHtml('checkout_billing_items') ?>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="actions-group">
        <div
            class="actions-group__handler"
            id="parent-payment-continue"
        >
            <button
                id="payment-continue"
                type="button"
                class="
                    button
                    actions-group__button
                    action
                    primary
                    continue
                "
            >
                <?= $escaper->escapeHtml(__('Go to Review Your Order')); ?>
            </button>
        </div>
        <div class="actions-group__handler">
            <a
                href="<?= $escaper->escapeUrl($block->getBackUrl()); ?>"
                class="
                    link
                    actions-group__link
                    action
                    back
                "
            >
                <?= $escaper->escapeHtml(__('Back to Shipping Information')); ?>
            </a>
        </div>
    </div>
</form>
<?php $quoteBaseGrandTotal = (float)$block->getQuoteBaseGrandTotal();
$scriptString = <<<script
    require(['jquery', 'mage/mage'], function(jQuery) {
        var addtocartForm = jQuery('#multishipping-billing-form');

        addtocartForm.mage('payment', {
            checkoutPrice: {$quoteBaseGrandTotal}
        });

        addtocartForm.mage('validation', {
            errorPlacement: function(error, element) {
                if (element.attr('data-validate') && element.attr('data-validate').indexOf('validate-cc-ukss') >= 0) {
                    element.parents('form').find('[data-validation-msg="validate-cc-ukss"]').html(error);
                } else {
                    element.after(error);
                }
            }
        });
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<?php $scriptString = <<<script
    //<![CDATA[
    require(
        [
            'Magento_Checkout/js/model/quote',
            'jquery',
            'domReady!'
        ], function(quote, $) {
            quote.billingAddress({
script;
$scriptString .= "city: '" . $escaper->escapeJs($block->getAddress()->getCity()) . "'," . PHP_EOL;
$scriptString .= "company: '" . $escaper->escapeJs($block->getAddress()->getCompany()) . "'," . PHP_EOL;
$scriptString .= "countryId: '" . $escaper->escapeJs($block->getAddress()->getCountryId()) . "'," . PHP_EOL;
$scriptString .= "customerAddressId: '" . $escaper->escapeJs($block->getAddress()->getCustomerAddressId()) . "'," . PHP_EOL;
$scriptString .= "customerId: '" . $escaper->escapeJs($block->getAddress()->getCustomerId()) . "'," . PHP_EOL;
$scriptString .= "fax: '" . $escaper->escapeJs($block->getAddress()->getFax()) . "'," . PHP_EOL;
$scriptString .= "firstname: '" . $escaper->escapeJs($block->getAddress()->getFirstname()) . "'," . PHP_EOL;
$scriptString .= "lastname: '" . $escaper->escapeJs($block->getAddress()->getLastname()) . "'," . PHP_EOL;
$scriptString .= "postcode: '" . $escaper->escapeJs($block->getAddress()->getPostcode()) . "'," . PHP_EOL;
$scriptString .= "regionId: '" . $escaper->escapeJs($block->getAddress()->getRegionId()) . "'," . PHP_EOL;
$scriptString .= "regionCode: '" . $escaper->escapeJs($block->getAddress()->getRegionCode()) . "'," . PHP_EOL;
$scriptString .= "region: '" . $escaper->escapeJs($block->getAddress()->getRegion()) . "'," . PHP_EOL;
$scriptString .= "street: " . /* @noEscape */ json_encode($block->getAddress()->getStreet()) . "," . PHP_EOL;
$scriptString .= "telephone: '" . $escaper->escapeJs($block->getAddress()->getTelephone()) . "'" . PHP_EOL;
$scriptString .= <<<script
            });
        });
    //]]>
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
