<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>

<?php if (count($block->getItems())): ?>
    <div class="grid grid--align-start">
        <?php foreach ($block->getItems() as $item): ?>
            <div class="wishlist__item grid__column grid__column--1-3">
                <div
                    data-row="product-item"
                    class="catalog-grid-item"
                    id="item_<?= $item->getId(); ?>"
                >
                    <?php foreach ($columns as $column): ?>
                        <?php
                            $column->setItem($item);
                            echo $column->toHtml($item);
                        ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="message info empty">
        <?= /* @escapeNotVerified */ __('This Wish List has no Items'); ?>
    </div>
<?php endif; ?>

<?php foreach ($columns as $column): ?>
    <?= /* @escapeNotVerified */ $column->getAdditionalHtml(); ?>
<?php endforeach; ?>
