<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>

<?php if (count($block->getItems())): ?>
    <div
        class="
            products-grid
            wishlist
            row
            wishlist__grid
        "
    >
        <?php foreach ($block->getItems() as $item): ?>
            <div
                id="item_<?= $block->escapeHtmlAttr($item->getId()) ?>"
                class="
                    col-xs-6
                    col-md-4
                    wishlist__item
                "
                data-row="product-item"
            >
                <?php foreach ($columns as $column): ?>
                    <?php $column->setItem($item); ?>
                    <?= $column->toHtml($item); ?>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="message">
        <?= __('This Wish List has no Items'); ?>
    </div>
<?php endif; ?>

<?php foreach ($columns as $column): ?>
    <?= $column->getAdditionalHtml(); ?>
<?php endforeach; ?>
