<?php $_item = $block->getItem(); ?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="name" data-th="<?= $escaper->escapeHtmlAttr(__('Product Name')); ?>">
        <strong>
            <?= $escaper->escapeHtml($_item->getName()) ?>
        </strong>

        <?php if ($_options = $block->getItemOptions()): ?>
            <ul class="list">
                <?php foreach ($_options as $_option) : ?>
                    <li class="list__item">
                        <?php // TODO: review if we want to introduce tooltip wrapper like in original file ?>
                        <?= $escaper->escapeHtml($_option['label']) . ': ' ?>

                        <?php if (!$block->getPrintStatus()): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <strong>
                                        <?= $escaper->escapeHtml($_formatedOptionValue['full_view']) ?>
                                    </strong>
                                <?php else: ?>
                                    <strong>
                                        <?= $escaper->escapeHtml($_formatedOptionValue['value'], ['a', 'img']) ?>
                                    </strong>
                                <?php endif; ?>
                        <?php else: ?>
                            <strong>
                                <?=
                                    $escaper->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))
                                ?>
                            </strong>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>

        <?php if ($addtInfoBlock) :?>
            <?= $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>

        <?= $escaper->escapeHtml($_item->getDescription()) ?>
    </td>

    <td class="sku" data-th="<?= $escaper->escapeHtmlAttr(__('SKU')); ?>">
        <?= /* @noEscape */ $block->prepareSku($block->getSku()) ?>
    </td>

    <td class="price" data-th="<?= $escaper->escapeHtmlAttr(__('Price')); ?>">
        <?= /* @noEscape */ $block->getItemPriceHtml(); ?>
    </td>

    <td class="qty" data-th="<?= $escaper->escapeHtmlAttr(__('Qty')); ?>">
        <ul class="list items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <li class="list__item">
                    <span class="title">
                        <?= $escaper->escapeHtml(__('Ordered')); ?>
                    </span>

                    <span class="content">
                        <?= (float) $block->getItem()->getQtyOrdered() ?>
                    </span>
                </li>
            <?php endif; ?>

            <?php if ($block->getItem()->getQtyShipped() > 0): ?>
                <li class="list__item">
                    <span class="title">
                        <?= $escaper->escapeHtml(__('Shipped')); ?>
                    </span>

                    <span class="content">
                        <?= (float) $block->getItem()->getQtyShipped() ?>
                    </span>
                </li>
            <?php endif; ?>

            <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
                <li class="list__item">
                    <span class="title">
                        <?= $escaper->escapeHtml(__('Canceled')); ?>
                    </span>

                    <span class="content">
                        <?= (float) $block->getItem()->getQtyCanceled() ?>
                    </span>
                </li>
            <?php endif; ?>

            <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
                <li class="list__item">
                    <span class="title">
                        <?= $escaper->escapeHtml(__('Refunded')); ?>
                    </span>

                    <span class="content">
                        <?= (float) $block->getItem()->getQtyRefunded() ?>
                    </span>
                </li>
            <?php endif; ?>
        </ul>
    </td>

    <td class="col subtotal" data-th="<?= $escaper->escapeHtmlAttr(__('Subtotal')); ?>">
        <?= /* @noEscape */ $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
