<?php $_item = $block->getItem(); ?>

<tr id="order-item-row-<?= $_item->getId() ?>">
    <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
        <?= $block->escapeHtml($_item->getName()) ?>

        <?php if ($_options = $block->getItemOptions()): ?>
            <ul class="list">
                <?php foreach ($_options as $_option) : ?>
                    <li>
                        <?= $block->escapeHtml($_option['label']) ?>

                        <?php if (!$block->getPrintStatus()): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>

                            <?= $_formatedOptionValue['value'] ?>:&nbsp;

                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <strong>
                                    <?= $block->escapeHtml($_option['label']) ?>:&nbsp;
                                    <?= $_formatedOptionValue['full_view'] ?>
                                </strong>
                            <?php endif; ?>
                        <?php else: ?>
                            <strong>
                                <?= nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                            </strong>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>

        <?php if ($addtInfoBlock) : ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>

        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>

    <td data-th="<?= $block->escapeHtmlAttr(__('SKU')) ?>">
        <?= $block->prepareSku($block->getSku()) ?>
    </td>

    <td data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>

    <td data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
        <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
            <?= __('Ordered') ?>:&nbsp;<?= $block->getItem()->getQtyOrdered()*1 ?>
        <?php endif; ?>

        <?php if ($block->getItem()->getQtyShipped() > 0): ?>
            <?= __('Shipped') ?>:&nbsp;<?= $block->getItem()->getQtyShipped()*1 ?>
        <?php endif; ?>

        <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
            <?= __('Canceled') ?>:&nbsp;<?= $block->getItem()->getQtyCanceled()*1 ?>
        <?php endif; ?>

        <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
            <?= __('Refunded') ?>:&nbsp;<?= $block->getItem()->getQtyRefunded()*1 ?>
        <?php endif; ?>
    </td>

    <td data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?= $block->escapeHtml(__('Subtotal')) ?>:&nbsp;<?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
