<?php
    $addressHelper = $this->helper(Magento\Customer\Helper\Address::class);
?>

<form
    class="row form-address-edit form"
    action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
    method="post"
    id="form-validate"
    enctype="multipart/form-data"
    data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
>
    <div class="col-sm-6 dashboard-form">
        <h3 class="dashboard-form__title">
            <?= $block->escapeHtml(__('Contact Information')) ?>
        </h3>

        <div class="dashboard-form__divider">
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>"/>
            <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>"/>

            <?= $block->getNameBlockHtml() ?>

            <div class="input">
                <?php
                    $getCompanyValidationClass = $addressHelper->getAttributeValidationClass('company');
                ?>

                <label class="label" for="company">
                    <?= $block->escapeHtml(__('Company')) ?>
                </label>

                <input
                    type="text"
                    name="company"
                    id="company"
                    title="<?= $block->escapeHtmlAttr(__('Company')) ?>"
                    value="<?= $block->escapeHtmlAttr($block->getAddress()->getCompany()) ?>"
                    class="input__field <?= $block->escapeHtmlAttr($getCompanyValidationClass) ?>"
                >
            </div>

            <div class="input required">
                <?php
                    $getTelephoneValidationClass = $addressHelper->getAttributeValidationClass('telephone');
                ?>

                <label class="label" for="telephone">
                    <?= $block->escapeHtml(__('Phone Number')) ?>
                </label>

                <input
                    type="text"
                    name="telephone"
                    value="<?= $block->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>"
                    title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                    class="input__field <?= $block->escapeHtmlAttr($getTelephoneValidationClass) ?>"
                    id="telephone"
                >
            </div>

            <div class="input">
                <?php
                    $getFaxValidationClass = $addressHelper->getAttributeValidationClass('fax');
                ?>

                <label class="label" for="fax">
                    <?= $block->escapeHtml(__('Fax')) ?>
                </label>

                <input
                    type="text"
                    name="fax"
                    id="fax"
                    title="<?= $block->escapeHtmlAttr(__('Fax')) ?>"
                    value="<?= $block->escapeHtmlAttr($block->getAddress()->getFax()) ?>"
                    class="input__field <?= $block->escapeHtmlAttr($getFaxValidationClass) ?>"
                >
            </div>
        </div>
    </div>

    <div class="col-sm-6 dashboard-form">
        <h3 class="dashboard-form__title">
            <?= $block->escapeHtml(__('Address')) ?>
        </h3>

        <div class="dashboard-form__divider">
            <?php
                $_streetValidationClass = $addressHelper->getAttributeValidationClass('street');
            ?>

            <div class="input required">
                <label for="street_1" class="label">
                    <?= $block->escapeHtml(__('Street Address')) ?>
                </label>

                <input
                    type="text"
                    name="street[]"
                    value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                    title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                    id="street_1"
                    class="input__field <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"
                >
            </div>

            <?php
                $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass));
                $getStreetLines         = $addressHelper->getStreetLines();
            ?>

            <?php for ($_i = 2, $_n = $getStreetLines; $_i <= $_n; $_i++): ?>
                <div class="input">
                    <label class="label" for="street_<?= $_i ?>">
                        <?= $block->escapeHtml(__('Street Address %1', $_i)) ?>
                    </label>

                    <input
                        type="text"
                        name="street[]"
                        value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i)) ?>"
                        title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>"
                        id="street_<?= $_i ?>"
                        class="input__field <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"
                    >
                </div>
            <?php endfor; ?>

            <?php if ($addressHelper->isVatAttributeVisible()): ?>
                <div class="input">
                    <?php
                        $getVatValidationClass = $addressHelper->getAttributeValidationClass('vat_id');
                    ?>

                    <label class="label" for="vat_id">
                        <?= $block->escapeHtml(__('VAT Number')) ?>
                    </label>

                    <input
                        type="text"
                        name="vat_id"
                        value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                        title="<?= $block->escapeHtmlAttr(__('VAT Number')) ?>"
                        class="input__field <?= $block->escapeHtmlAttr($getVatValidationClass) ?>"
                        id="vat_id"
                    >
                </div>
            <?php endif; ?>

            <div class="input required">
                <?php
                    $getCityValidationClass = $addressHelper->getAttributeValidationClass('city');
                ?>

                <label class="label" for="city">
                    <?= $block->escapeHtml(__('City')) ?>
                </label>

                <input
                    type="text"
                    name="city"
                    value="<?= $block->escapeHtml($block->getAddress()->getCity()) ?>"
                    title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                    class="input__field <?= $block->escapeHtmlAttr($getCityValidationClass) ?>"
                    id="city"
                >
            </div>

            <div class="input required">
                <?php
                    $getRegionValidationClass = $addressHelper->getAttributeValidationClass('region');
                ?>

                <label class="label" for="region_id">
                    <?= $block->escapeHtml(__('State/Province')) ?>
                </label>

                <select
                    id="region_id"
                    name="region_id"
                    title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                    class="select__field select__field--native validate-select"
                    style="display: none;"
                >
                    <option value="" disabled>
                        <?= $block->escapeHtml(__('Please select a region, state or province.')) ?>
                    </option>
                </select>

                <input
                    type="text"
                    id="region"
                    name="region"
                    value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                    title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                    class="input__field <?= $block->escapeHtmlAttr($getRegionValidationClass) ?>"
                >
            </div>

            <div class="input required">
                <?php
                    $getPostcodeValidationClass = $addressHelper->getAttributeValidationClass('postcode');
                ?>

                <label class="label" for="zip">
                    <?= __('Zip/Postal Code') ?>
                </label>

                <input
                    type="text"
                    name="postcode"
                    value="<?= $block->escapeHtml($block->getAddress()->getPostcode()) ?>"
                    title="<?= __('Zip/Postal Code') ?>"
                    id="zip"
                    class="
                        input__field
                        validate-zip-international
                        <?= $getPostcodeValidationClass ?>
                    "
                >
            </div>

            <div class="input required">
                <label class="label" for="country">
                    <?= $block->escapeHtml(__('Country')) ?>
                </label>

                <?php $countryList = $block->getCountryCollection()->toOptionArray() ?>

                <select
                    name="country_id"
                    id="country"
                    class="select__field select__field--native required-entry"
                    title="Country"
                    data-validate="{'validate-select': true}"
                    aria-required="true"
                >
                    <option value="" disabled>
                        <?= $block->escapeHtml(__('Please select a country.')) ?>
                    </option>

                    <?php for ($i = 1, $n = count($countryList); $i < $n; $i++): ?>
                        <option
                            value="<?= $countryList[$i]['value'] ?>"
                            <?php if ($block->getCountryId() === $countryList[$i]['value']) echo 'selected' ?>
                        >
                            <?= $countryList[$i]['label']; ?>
                        </option>
                    <?php endfor ?>
                </select>
            </div>

            <?php if ($block->isDefaultBilling()): ?>
                <div class="message info">
                    <?= $block->escapeHtml(__("It's a default billing address.")) ?>
                </div>
            <?php elseif ($block->canSetAsDefaultBilling()): ?>
                <div class="checkbox dashboard-form__divider">
                    <input
                        type="checkbox"
                        id="primary_billing"
                        name="default_billing"
                        value="1"
                        class="checkbox__field"
                    >

                    <svg class="checkbox__icon">
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
                    </svg>

                    <label class="checkbox__label" for="primary_billing">
                        <?= $block->escapeHtml(__('Use as my default billing address')) ?>
                    </label>
                </div>
            <?php else: ?>
                <input type="hidden" name="default_billing" value="1">
            <?php endif ?>

            <?php if ($block->isDefaultShipping()): ?>
                <div class="message info">
                    <?= $block->escapeHtml(__("It's a default shipping address.")) ?>
                </div>
            <?php elseif ($block->canSetAsDefaultShipping()): ?>
                <div class="checkbox dashboard-form__divider">
                    <input
                        type="checkbox"
                        id="primary_shipping"
                        name="default_shipping"
                        value="1"
                        class="checkbox__field"
                    >

                    <svg class="checkbox__icon">
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked')) ?>"></use>
                    </svg>

                    <label class="checkbox__label" for="primary_shipping">
                        <?= $block->escapeHtml(__('Use as my default shipping address')) ?>
                    </label>
                </div>
            <?php else: ?>
                <input type="hidden" name="default_shipping" value="1">
            <?php endif ?>
        </div>
    </div>

    <div class="col-xs-12 action">
        <div class="action__handler">
            <button
                type="submit"
                class="button action__button"
                data-action="save-address"
                title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>"
            >
                <?= $block->escapeHtml(__('Save Address')) ?>
            </button>
        </div>

        <div class="action__handler">
            <a
                class="link action__link"
                href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
            >
                <?= $block->escapeHtml(__('Go back')) ?>
            </a>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @escapeNotVerified */($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?= $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
