<?php

/**
 * @see \Blackbird\ContentManager\Block\View
 */
?>
<?php
/*
 *
 *
 * AVAILABLE METHODS
 *
 * Get all raw values as an array
 * $content->getData();
 *
 * Get a specific value by his field identifier
 * $content->getData('field_identifier');
 * $content->getFieldIdentifier();
 * $content->getAttributeText('field_identifier');
 *
 * Get content type model
 * $content->getContentType();
 *
 * Get image URL for an image field type.
 * $content->getImage($attributeName, $width, $height, $keepRatio, $cropped = false);
 *
 * Get file absolute URL, for a file field typ
 * $content->getFile($field_identifier);
 *
 * Get content url
 * $content->getLinkUrl();
 *
 * Render a field in HTML
 * $content->render($element, $params);
 *
 * See the complete documentation and more examples at:
 * http://www.advancedcontentmanager.com/documentation/
 *
 */
?>
<?php
/** @var \Blackbird\ContentManager\Model\Content $content */
$content = $block->getContent();
$ctPrefix = 'cb_article_';
$ctPicPrefix = 'cb_pic_';
$date = new DateTime($content->getData($ctPrefix . 'date'));
$dateFormatted = $date->format('F j\,\ Y');
$title = $content->getData($ctPrefix . 'title');

$imageAttributes = [
    $ctPicPrefix . 'alt',
    $ctPicPrefix . 'default',
    $ctPicPrefix . 'max_480',
    $ctPicPrefix . 'max_480_2x',
    $ctPicPrefix . 'max_768',
    $ctPicPrefix . 'max_768_2x',
    $ctPicPrefix . 'max_1024',
    $ctPicPrefix . 'max_1024_2x',
    $ctPicPrefix . 'max_1328',
    $ctPicPrefix . 'max_1328_2x',
    $ctPicPrefix . 'full',
    $ctPicPrefix . 'full_2x'
];

$imageId = (int) explode(',', $content->getData($ctPrefix . 'image'))[0];
$imagesContent = $content->getContentCollection($ctPrefix . 'image', $imageAttributes);
$imageDefault = '';
$imageAlt = '';
$image = null;

$images = $imagesContent->getItems();

if (!empty($images[$imageId])) {
    $image = $images[$imageId];
}

if (!empty($image)) {
    $imageDefault = $block->escapeUrl($image->getFile($ctPicPrefix . 'default'));

    $image480 = $block->escapeUrl($image->getFile($ctPicPrefix . 'max_480'));
    $image4802x = $block->escapeUrl($image->getFile($ctPicPrefix . 'max_480_2x'));

    $image768 = $block->escapeUrl($image->getFile($ctPicPrefix . 'max_768'));
    $image7682x = $block->escapeUrl($image->getFile($ctPicPrefix . 'max_768_2x'));

    $image1024 = $block->escapeUrl($image->getFile($ctPicPrefix . 'max_1024'));
    $image10242x = $block->escapeUrl($image->getFile($ctPicPrefix . 'max_1024_2x'));

    $image1328 = $block->escapeUrl($image->getFile($ctPicPrefix . 'max_1328'));
    $image13282x = $block->escapeUrl($image->getFile($ctPicPrefix . 'max_1328_2x'));

    $imageFull = $block->escapeUrl($image->getFile($ctPicPrefix . 'full'));
    $imageFull2x = $block->escapeUrl($image->getFile($ctPicPrefix . 'full_2x'));

    $imageAlt = $image->getData($ctPicPrefix . 'alt');

    $block->getChildBlock('colibri-article-image')->setData([
        'picture_class' => 'article__image',
        'picture_full_url' => true,
        'img_default' => $imageDefault,
        'img_480' => $image480,
        'img_768' => $image768,
        'img_1024' => $image1024,
        'img_1328' => $image1328,
        'img_full' => $imageFull,
        'img_4802x' => $image4802x,
        'img_7682x' => $image7682x,
        'img_10242x' => $image10242x,
        'img_13282x' => $image13282x,
        'img_full_2x' => $imageFull2x,
        'picture_alt' => $imageAlt
    ]);
}

$categories = explode(',', $content->getData($ctPrefix . 'category'));

$filtersBlock = $block->getChildBlock('blog-filter');
$filters = $filtersBlock->getFilters();

$recentArticlesBlock = $block->getChildBlock('recent-articles');
$recentArticles = $recentArticlesBlock->getCollection();

$entityId = $content->getData('entity_id');
?>

<div class="blog-post row">
    <article
        class="
            article-item
            article-item--single
            col-md-8
            col-lg-9
        "
    >
        <header class="article-item__header">
            <h1 class="article-item__title">
                <?= $title ?>
            </h1>
            <span class="article-item__sub-title heading--font-secondary">
                <?= $dateFormatted ?>
            </span>
        </header>
        <section class="article-item__container">
            <div class="article-item__media">
                <div class="banner article-item__banner">
                    <?= $block->getChildHtml('colibri-article-image', false); ?>
                </div>
            </div>
            <div class="article-item__body">
                <div class="article-item__content">
                    <?= $content->render($ctPrefix . 'text'); ?>
                </div>
                <?php if (count(array_filter($categories))) : ?>
                    <footer class="article-item__footer">
                        <ul
                            class="
                                list
                                list--horizontal
                                article-item__links-list
                            "
                        >
                            <li class="list__item">
                                <strong>
                                    <?= __('Posted in:') ?>
                                </strong>
                            </li>
                            <?php foreach ($filters as $filter) : ?>
                                <?php foreach ($filter->getAllOptions() as $option) : ?>
                                    <?php if (in_array($option['value'], $categories)) : ?>
                                        <li class="list__item">
                                            <a
                                                class="link"
                                                href="<?= $block->escapeUrl('/blog?' . $filter->getIdentifier() . '=' . $option['value']) ?>"
                                                title="<?= $block->escapeHtmlAttr($option['label']) ?>"
                                            >
                                                <?= $option['label'] ?>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </ul>
                    </footer>
                <?php endif; ?>
            </div>
        </section>
    </article>

    <nav
        class="
            blog__nav
            col-md-4
            col-lg-3
        "
    >
        <div class="blog__recommended">
            <h3 class="blog__nav-heading heading--font-secondary">
                <?= __('Recent Posts') ?>
            </h3>

            <ul class="list blog__nav-list">
                <?php foreach ($recentArticles as $article) : ?>
                    <?php if ($entityId !== $article->getData('entity_id')) : ?>
                        <?php
                            $link = $block->escapeUrl($article->getLinkUrl());
                            $title = $article->getData($ctPrefix . 'title');
                        ?>
                        <li class="list__item">
                            <a
                                href="<?= $link ?>"
                                class="link"
                            >
                                <?= $title ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php if (!empty($filters)) : ?>
            <div class="blog__categories">
                <h3 class="blog__nav-heading heading--font-secondary">
                    <?= __('Categories') ?>
                </h3>
                <ul class="list blog__nav-list">
                    <?php foreach ($filters as $filter) : ?>
                        <?php foreach ($filter->getAllOptions() as $option) : ?>
                            <li class="list__item">
                                <a
                                    href="<?= $block->escapeUrl($filtersBlock->getFilterUrl($filter->getIdentifier(), $option['value'])) ?>"
                                    class="link"
                                >
                                    <?= $option['label'] ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    </nav>
</div>
