<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php $menuClass = $block->getMenuCssClass() ?>

<button class="side-menu-trigger" type="button">
    <svg class="side-menu-trigger__icon">
        <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#mobile-menu'); ?>"></use>
    </svg>
</button>

<nav class="<?= $menuClass ?>">
    <ul class="<?= $menuClass ?>__list list list--divided"
        data-mage-init='{ "sideMenuTrigger": {} }'
    >
        <?php foreach ($block->getNodes() as $node): ?>
            <?php
                $childrenLevel = $node->getLevel() + 1;
                $children = $this->getNodes($childrenLevel, $node);
                $node->setIsParent((bool) $children);
                $parentClass = $children ? ' ' . $menuClass . '__item--parent' : '';
                $additionalClasses = $node->getClasses() ? ' ' . $node->getClasses() : '';
                $itemClasses = $parentClass . $additionalClasses;
            ?>
            <li class="<?= $menuClass ?>__item<?= $itemClasses ?> list__item">
                <?php echo $block->renderMenuNode($node) ?>
                <?php echo $block->renderSubmenu($children, $node, $childrenLevel) ?>
            </li>
        <?php endforeach; ?>
    </ul>
</nav>
