<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php if ($block->getMenu()): ?>
    <?php
        $menuClass = $block->getMenu()->getCssClass();
        $parentNode = $block->getParentNode();
        $level = $block->getLevel();

        $wrapperAttributes = [
            'class' => [
                $menuClass . '__content',
            ],
            'id' => 'dropdown-' . $parentNode->getNodeId()
        ];
    ?>
    <div <?= $block->buildAttrFromArray($wrapperAttributes) ?>>
        <ul class="list footer__links-list">
            <?php foreach ($block->getSubmenuNodes() as $node): ?>
                <?php
                    $childrenLevel = $node->getLevel() + 1;
                    $children = $this->getNodes($childrenLevel, $node);
                    $node->setIsParent((bool) $children);

                    $nodeAttributes = [
                        'class' => [
                            'list__item'
                        ]
                    ];

                    if ($node->getClasses()) {
                        $nodeAttributes['class'][] = $node->getClasses();
                    }
                ?>
                <li <?= $block->buildAttrFromArray($nodeAttributes) ?>>
                    <?= $block->renderMenuNode($node) ?>
                    <?= $block->renderSubmenu($children, $node, $childrenLevel) ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
