<?php if ($block->getQuote()->hasVirtualItems()) : ?>
<div 
    class="
        dashboard-items 
        dashboard-table 
        margin-bottom-m
    "
>
    <div class="dashboard-table__header">
        <h2 class="dashboard-table__title">
            <?= $block->escapeHtml(__('Other items in your order')) ?>
        </h2>
        <a 
            href="<?= $block->escapeUrl($block->getVirtualProductEditUrl()) ?>"
            class="link dashboard-table__link"
            title="<?= $block->escapeHtmlAttr(__('Edit Items')) ?>"
        >
            <?= $block->escapeHtml(__('Edit Items')) ?>
        </a>
    </div>
    <div class="dashboard-table__content">
        <p>
            <?= $block->escapeHtml(__('Shipping is not applicable.')) ?>
        </p>
        <table 
            class="
                items
                data
                table
            " 
            id="unavailable-shipping-table"
            role="table"
        >
            <caption class="table__caption">
                <?= $block->escapeHtml(__('Other items in your order')) ?>
            </caption>
            <thead>
                <tr role="row">
                    <th 
                        class="
                            col
                            item
                        " 
                        scope="col"
                        role="columnheader"
                    >
                        <?= $block->escapeHtml(__('Product Name')) ?>
                    </th>
                    <th 
                        class="
                            col
                            qty
                        "
                        scope="col"
                        role="columnheader"
                    >
                        <?= $block->escapeHtml(__('Qty')) ?>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getVirtualQuoteItems() as $_item) : ?>
                    <tr role="row">
                        <td 
                            class="
                                col
                                item
                            " 
                            data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>"
                            role="gridcell"
                        >
                            <?= $block->getItemHtml($_item) ?>
                        </td>
                        <td 
                            class="
                                col
                                qty
                            "
                            data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>" 
                            role="gridcell"
                        >
                            <?= $block->escapeHtml($_item->getQty()) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php endif; ?>
