<?php
/** @var \Magento\Customer\Block\Widget\Company $block */
?>
<div
    class="
        input
        company
        <?= $block->isRequired() ? 'required' : '' ?>
    "
>
    <label
        for="company"
        class="label"
    >
            <?= $block->escapeHtml(__('Company')) ?>
    </label>
    <?php
    $_validationClass = $block->escapeHtmlAttr(
        $this->helper(\Magento\Customer\Helper\Address::class)
                ->getAttributeValidationClass('company')
    );
    ?>
    <input
        type="text"
        name="company"
        id="company"
        value="<?= $block->escapeHtmlAttr($block->getCompany()) ?>"
        title="<?= $block->escapeHtmlAttr(__('Company')) ?>"
        class="input__field <?= $_validationClass ?: '' ?>"
        <?= $block->isRequired() ? ' data-validate="{required:true}" required' : '' ?>
    />
</div>
