<?php
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Customer\Block\Widget\Dob $block */

/*
USAGE:
<?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
   ->setDate($block->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
   ->setDate($block->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css. Alternatively we could calculate widths
automatically using block input parameters.
*/

$translatedCalendarConfigJson = $block->getTranslatedCalendarConfigJson();
$fieldCssClass = 'input input--inline date input-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?= /* @noEscape */ $fieldCssClass; ?>">
    <label class="input__label" for="<?= /* @noEscape */ $block->getHtmlId()?>">
        <?= $escaper->escapeHtml($block->getStoreLabel('dob')) ?>
    </label>
    <?= $block->getFieldHtml(); ?>
    <?php if ($_message = $block->getAdditionalDescription()) : ?>
        <div class="input__note">
            <?= $escaper->escapeHtml($_message); ?>
        </div>
    <?php endif; ?>
</div>

<script type="text/x-magento-init">
    {
       "*": {
           "Magento_Customer/js/validation": {}
       }
    }
</script>

<?php $scriptString = <<<code
require([
    'jquery',
    'jquery-ui-modules/datepicker'
], function($) {
    //<![CDATA[
        $.extend(true, $, {
            calendarConfig: {$translatedCalendarConfigJson}
        });
    //]]>
});
code;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
