<div class="input<?php if ($block->isRequired()) echo ' required' ?>">
    <label class="input__label"
           for="<?= /* @escapeNotVerified */ $block->getFieldId('gender')?>"
    >
        <?= /* @escapeNotVerified */ __('Gender') ?>
    </label>
    <?php $is_required = $block->isRequired(); ?>
        <select id="<?= /* @escapeNotVerified */ $block->getFieldId('gender')?>"
                name="<?= /* @escapeNotVerified */ $block->getFieldName('gender')?>"
                title="<?= /* @escapeNotVerified */ __('Gender') ?>"
                class="select <?= ($is_required) ? ' validate-select': ''?>"
                data-mage-init='{"select": {}}'
                <?= ($is_required) ? 'data-validate="{required:true}"' : '' ?>
            <?= /* @escapeNotVerified */ $block->getFieldParams() ?>
        >
            <?php $options = $block->getGenderOptions(); ?>
            <?php $value = $block->getGender();?>
            <?php foreach ($options as $option):?>
                <option value="<?= /* @escapeNotVerified */ $option->getValue() ?>"
                    <?php if ($option->getValue() == $value) echo ' selected="selected"' ?>
                >
                    <?php /* @escapeNotVerified */ echo __($option->getLabel()) ?>
                </option>
            <?php endforeach;?>
        </select>
</div>
