<div class="input <?= $block->isRequired() ?'required' : '' ?>">
    <label
        class="input__label"
        for="<?= $block->escapeHtmlAttr($block->getFieldId('gender')) ?>"
    >
        <?= $block->escapeHtml($block->getStoreLabel('gender')) ?>
    </label>
    <?php $is_required = $block->isRequired(); ?>
        <select
            id="<?= $block->getFieldId('gender') ?>"
            name="<?= $block->getFieldName('gender') ?>"
            title="<?= $block->escapeHtml($block->getStoreLabel('gender')) ?>"
            class="select <?= ($is_required) ? ' validate-select': ''?>"
            data-mage-init='{"select": {}}'
            <?= $is_required ? 'data-validate="{required:true}"' : '' ?>
            <?= $block->getFieldParams() ?>
        >
            <?php $options = $block->getGenderOptions(); ?>
            <?php $value = $block->getGender(); ?>
            <?php foreach ($options as $option): ?>
                <option
                    value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"
                    <?= $option->getValue() == $value ? 'selected="selected"' : '' ?>
                >
                    <?= $block->escapeHtml(__($option->getLabel())) ?>
                </option>
            <?php endforeach;?>
        </select>
</div>
