<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="form__field taxvat<?php if ($block->isRequired()) echo ' required'; ?>">
    <label class="input__label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId('taxvat')?>">
        <?php /* @escapeNotVerified */ echo __('Tax/VAT number') ?>
    </label>
    <input type="text"
           id="<?php /* @escapeNotVerified */ echo $block->getFieldId('taxvat')?>"
           name="<?php /* @escapeNotVerified */ echo $block->getFieldName('taxvat')?>"
           value="<?php echo $block->escapeHtml($block->getTaxvat()) ?>"
           title="<?php /* @escapeNotVerified */ echo __('Tax/VAT number') ?>"
           class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('taxvat') ?>"
           <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->isRequired()) echo ' data-validate="{required:true}"' ?>
    >
    </div>
</div>
