<div class="input<?= ($block->isRequired()) ? ' required' : '' ?>">
    <label
        class="input__label"
        for="<?= $block->escapeHtmlAttr($block->getFieldId('taxvat')) ?>"
    >
           <?= $block->escapeHtml($block->getStoreLabel('taxvat')) ?>
    </label>
    <input
        type="text"
        id="<?= $block->escapeHtmlAttr($block->getFieldId('taxvat')) ?>"
        name="<?= $block->escapeHtmlAttr($block->getFieldName('taxvat')) ?>"
        value="<?= $block->escapeHtmlAttr($block->getTaxvat()) ?>"
        title="<?= $block->escapeHtmlAttr($block->getStoreLabel('taxvat')) ?>"
        class="
            input__field
            <?= $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('taxvat') ?>
        "
        <?= $block->getFieldParams() ?>
        <?= ($block->isRequired()) ? ' data-validate="{required:true}"' : '' ?>
    >
</div>
