<?php
/** @var \Magento\Customer\Block\Widget\Telephone $block */
?>

<div
    class="
        input
        telephone
        <?= $block->isRequired() ? 'required' : '' ?>"
    >
    <label
        for="telephone"
        class="label"
    >
        <?= $block->escapeHtml(__('Phone Number')) ?>
    </label>
    <input
        type="tel"
        name="telephone"
        id="telephone"
        value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
        title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
        class="
            input__field
            <?= $block->escapeHtmlAttr(
                $block->getAttributeValidationClass('telephone')
            ) ?>
        "
        <?= $block->isRequired() ? ' data-validate="{required:true}" required' : '' ?>
    />
</div>
