<?php
/** @var \Magento\Customer\Block\Widget\Telephone $block */
?>

<div
    class="
        input
        telephone
        <?= $block->isRequired() ? 'required' : '' ?>"
    >
    <label
        for="telephone"
        class="label"
    >
        <?= $escaper->escapeHtml(__('Phone Number')) ?>
    </label>
    <input
        type="tel"
        name="telephone"
        id="telephone"
        value="<?= $escaper->escapeHtmlAttr($block->getTelephone()) ?>"
        title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
        class="
            input__field
            <?= $escaper->escapeHtmlAttr(
                $block->getAttributeValidationClass('telephone')
            ) ?>
        "
    />
</div>
