<?php
/**
 * Order by SKU widget template
 *
 * @var $block \Magento\QuickOrder\Block\Sku
 */
?>
<div
    id="<?= $block->escapeHtmlAttr($block->getUniqueId()) ?>"
    class="
        widget
        block
        block-addbysku
    "
    data-role="block-addbysku"
    data-mage-init='{
        "quickOrderItemTable":{
            "addBlockData":{"widgetId":"<?= $block->escapeHtmlAttr($block->getUniqueId()) ?>"},
            "addEvent":"addNewRow",
            "addSelector":"[data-role=new-block]"
        }
    }'
>
    <div
        data-role="show-errors"
        class="wrap-sum-errors"
        data-mage-init='{
            "countingErrors":{
                "wrapError":"[data-role=block-addbysku]",
                "nameErrorBlock":"[data-role=error-message]"
            }
        }'
     ></div>
    <?php if (!$block->getIsTitleHidden()) : ?>
        <div class="block-title">
            <strong role="heading" aria-level="2">
                <?= $block->escapeHtml(__('Order by SKU')) ?>
            </strong>
        </div>
    <?php endif ?>
    <div class="block-content row">
        <div class="col-xs-12 col-lg-6">
            <form
                class="form form-addbysku"
                action="<?= $block->escapeUrl($block->getUrl('quickorder/sku/uploadfile')) ?>"
                method="post"
                data-role="send-sku"
                data-mage-init='{"validation":{}, "quickOrderAddToCart":{}}'
                <?php if ($block->getIsMultipart()) : ?>
                    enctype="multipart/form-data"
                <?php endif; ?>
            >
                <div class="box box-items">
                    <fieldset
                        class="fieldset"
                        data-container="items"
                    ></fieldset>
                </div>
                <?php if ($block->getChildHtml()) : ?>
                    <div class="box box-upload">
                        <fieldset class="fieldset">
                            <?= $block->getChildHtml() ?>
                        </fieldset>
                    </div>
                <?php endif; ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button
                            type="submit"
                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                            class="
                                button
                                button--add-to
                                quickorder__button
                                action
                                tocart
                                primary
                            "
                            data-action="submit-sku"
                            disabled
                        >
                            <?= $block->escapeHtml(__('Add to Cart')) ?>
                        </button>
                    </div>
                </div>
                <?php if ($block->getLink()) : ?>
                    <?= /* @noEscape */ $block->getLink() ?>
                <?php endif; ?>
            </form>
        </div>
        <script data-template="add-block" type="text/x-magento-template">
            <div
                class="
                    fields
                    additional
                    deletable-item
                    quickorder__item
                    margin-top-s
                "
                data-role="new-block"
                data-mage-init='{
                    "deletableItem":{},
                    "productSkuItem":{
                        "rowIndex": "<%- data.rowIndex %>",
                        "tableWigetSelector":"[data-role=block-addbysku]",
                        "urlSku":"<?= $block->escapeUrl($block->getUrl('quickorder/ajax/search')) ?>"
                    }
                }'
            >
                <div
                    class="
                        input
                        sku
                        required
                        ui-front
                        quickorder__input
                    "
                >
                    <label class="label">
                        <?= $block->escapeHtml(__('Enter SKU or Product Name')) ?>
                    </label>
                    <input
                        type="text"
                        name="items[<%- data.rowIndex %>][sku]"
                        id="id-items<%- data.widgetId %><%- data.rowIndex %>sku"
                        class="input__field"
                        data-id="<%- data.widgetId %><%- data.rowIndex %>sku"
                        data-sku="true"
                        aria-required="true"
                        data-mage-init='{
                            "Magento_QuickOrder/js/sku/autocomplete": {
                                "sourceUrl": "<?= $block->escapeUrl($block->getUrl('quickorder/ajax_product/suggest')) ?>"
                            }
                        }'
                        data-validate='{
                            "required-if-all-sku-empty-and-file-not-loaded": {
                                specifiedId: "#customer_sku_csv",
                                dataSku: "data-sku"
                            }
                        }'
                        data-role="product-sku"
                    />
                    <div
                        class="product-block"
                        data-role="product-block"
                    ></div>
                </div>
                <div
                    class="
                        input
                        qty
                        required
                        quickorder__input
                        quickorder__input--qty
                    "
                >
                    <label class="label">
                        <?= $block->escapeHtml(__('Qty')) ?>
                    </label>
                    <input
                        type="number"
                        name="items[<%- data.rowIndex %>][qty]"
                        id="id-items<%- data.widgetId %><%- data.rowIndex %>qty"
                        class="input__field"
                        class="qty"
                        maxlength="13"
                        aria-required="true"
                        data-validate='{
                            "required-number-if-specified": "[data-id=<%- data.widgetId %><%- data.rowIndex %>sku]",
                            "validate-number": true,
                            "validate-greater-than-zero": true,
                            "validate-number-range": "0.0001-99999999.9999"
                        }'
                        data-role="product-qty"
                    />
                </div>
                <div class="margin-bottom-m">
                    <button
                        type="button"
                        title="<?= __('Remove Item'); ?>"
                        class="
                            button
                            button--icon
                            action
                            quickorder__button
                            remove
                        "
                        data-role="delete"
                    >
                        <svg
                            class="
                                icon
                                button__icon
                            "
                            role="presentation"
                            focusable="false"
                        >
                            <title><?= __('Remove'); ?></title>
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#remove')) ?>"></use>
                        </svg>
                    </button>
                </div>
            </div>
        </script>
    </div>
</div>
