<?php
/** @var \Snowdog\SolrNavigation\Block\Product\Toolbar $block */
?>
<div class="toolbar__limiter">
    <div class="select toolbar__limiter-wrapper">
        <label class="label toolbar__limiter-label" for="limiter">
            <?= __('Show') ?>
        </label>
        <select
            id="limiter"
            class="select__field select__field--native toolbar__limiter-select"
            name="limiter"
            onchange="document.location.href=this.value"
            data-mage-init='{ "select": { "type": "number" } }'
        >
            <?php foreach ($block->getAvailableLimit() as $_limit): ?>
                <option
                    value="<?= $block->getLimitUrl($_limit) ?>"
                    <?= ($block->isLimitCurrent($_limit)) ? 'selected="selected"' : '' ?>
                >
                    <?= $block->getLimitLabel($_limit) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
