
<div data-bind="scope: 'lastOrderedItems'">
    <div
        class="sidebar-block sidebar-block--hidden"
        data-bind="css: {'sidebar-block--hidden': !lastOrderedItems().items || lastOrderedItems().items.length === 0}"
    >
        <p class="sidebar-block__heading">
            <span class="sidebar-block__title">
                <?= /* @escapeNotVerified */ __('Recently Ordered') ?>
            </span>
        </p>

        <form
            id="reorder-validate-detail"
            method="post"
            action="<?= /* @escapeNotVerified */ $block->getFormActionUrl() ?>"
        >
            <ol
                id="cart-sidebar-reorder"
                class="list sidebar-block__list"
                data-bind="foreach: lastOrderedItems().items"
            >
                <li>
                    <div class="sidebar-block__item">
                        <a
                            data-bind="attr: {href: url}, text: name"
                            class="link sidebar-block__link"
                        ></a>
                    </div>
                    <div
                        class="checkbox sidebar-block__checkbox"
                        data-bind="css: {'no-display': !is_saleable}"
                    >
                        <input
                            type="checkbox"
                            name="order_items[]"
                            data-bind="attr: {id: 'reorder-item-' + id, value: id}"
                            title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>"
                            class="checkbox__field"
                            data-validate='{"validate-one-checkbox-required-by-name": true}'
                        />
                        <svg class="checkbox__icon">
                            <use xlink:href="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
                        </svg>
                        <label
                            class="checkbox__label"
                            data-bind="attr: {'for': 'reorder-item-' + id}"
                        >
                            <?= /* @escapeNotVerified */ __('Add to Cart') ?>
                        </label>
                    </div>
                </li>
            </ol>

            <div id="cart-sidebar-reorder-advice-container"></div>

            <div>
                <button
                    type="submit"
                    class="button sidebar-block__action"
                >
                    <?= /* @escapeNotVerified */ __('Add to Cart') ?>
                </button>

                <a
                    class="button button--link sidebar-block__action"
                    href="<?= /* @escapeNotVerified */ $block->getUrl('customer/account') ?>"
                >
                    <?= /* @escapeNotVerified */ __('View All'); ?>
                </a>
            </div>
        </form>

        <script>
            require(["jquery", "mage/mage"], function(jQuery){
                jQuery('#reorder-validate-detail').mage('validation', {
                    errorPlacement: function(error, element) {
                        error.appendTo('#cart-sidebar-reorder-advice-container');
                    }
                });
            });
        </script>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "lastOrderedItems": {
                    "component": "Magento_Sales/js/view/last-ordered-items"
                }
            }
        }
    }
}
</script>
