<?php
/**
 * Last ordered items sidebar
 *
 * @var $block \Magento\Sales\Block\Reorder\Sidebar
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div data-bind="scope: 'lastOrderedItems'">
    <div
        class="sidebar-block sidebar-block--hidden"
        data-bind="css: {'sidebar-block--hidden': !lastOrderedItems().items || lastOrderedItems().items.length === 0}"
    >
        <div class="sidebar-block__heading">
            <h2 class="heading--first-level sidebar-block__title">
                <?= $escaper->escapeUrl(__('Recently Ordered')) ?>
            </h2>
        </div>
        <div class="divider sidebar-block__divider"></div>
        <form
            id="reorder-validate-detail"
            method="post"
            action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
        >
            <ol
                id="cart-sidebar-reorder"
                class="list sidebar-block__list"
                data-bind="foreach: lastOrderedItems().items"
            >
                <li>
                    <div class="sidebar-block__item">
                        <a
                            data-bind="attr: {href: url}, text: name"
                            class="link sidebar-block__link"
                        ></a>
                    </div>
                    <div
                        class="checkbox sidebar-block__checkbox"
                        data-bind="css: {'no-display': !is_saleable}"
                    >
                        <input
                            type="checkbox"
                            name="order_items[]"
                            data-bind="
                                attr: {
                                    id: 'reorder-item-' + id,
                                    value: id,
                                    title: is_saleable ? '<?= $escaper->escapeHtml(__('Add to Cart')) ?>' : '<?= $escaper->escapeHtml(__('Product is not salable.')) ?>'
                                },
                                disable: !is_saleable
                            "
                            class="checkbox__field"
                            data-validate='{"validate-one-checkbox-required-by-name": true}'
                        />
                        <svg class="checkbox__icon">
                            <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked')); ?>"></use>
                        </svg>
                        <label
                            class="checkbox__label"
                            data-bind="attr: {'for': 'reorder-item-' + id}"
                        >
                            <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                        </label>
                    </div>
                </li>
            </ol>

            <div id="cart-sidebar-reorder-advice-container"></div>

            <div>
                <button
                    type="submit"
                    class="button sidebar-block__action"
                >
                    <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                </button>

                <a
                    class="button button--link sidebar-block__action"
                    href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>"
                >
                    <?= $escaper->escapeHtml(__('View All')); ?>
                </a>
            </div>
        </form>

        <?php $scriptString = <<<script
            require(["jquery", "mage/mage"], function(jQuery){
                jQuery('#reorder-validate-detail').mage('validation', {
                    errorPlacement: function(error, element) {
                        error.appendTo('#cart-sidebar-reorder-advice-container');
                    }
                });
            });
        script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "lastOrderedItems": {
                    "component": "Magento_Sales/js/view/last-ordered-items"
                }
            }
        }
    }
}
</script>
