<?php
/** @var \Amasty\GiftCard\Pricing\Render\FinalPriceBox $block */
$productId = $block->getSaleableItem()->getId();
?>

<?php if ($block->getCanShowPrice() !== false && !$block->isProductForm()): ?>
    <div class="price">
        <div class="price-box price__value">
            <?php if (!$block->isSinglePrice()): ?>
                <span class="price-label price__text">
                    <?= $escaper->escapeHtml(__('From')); ?>
                </span>
            <?php endif; ?>
            <span id="product-price-<?= $escaper->escapeHtmlAttr($productId . $block->getIdSuffix()); ?>">
                <?= $escaper->escapeHtml($block->convertAndFormatCurrency($block->getMinPrice(), false)); ?>
            </span>
        </div>
    </div>
<?php endif; ?>

<?php if ($block->isProductForm()): ?>
    <?php
    $currency = $block->getCurrencyShortName();
    $product = $block->getSaleableItem();
    ?>
    <div
        class="amgiftcard-price-container"
        data-bind="scope: 'price'"
    >
        <div
            class="
                amgiftcard-price-multiple
                price
                opacity-0
            "
            data-bind="
                visible: $data.showCustomPrice,
                css: {
                    'opacity-0': !$data.isLoaded()
                }
            "
        >
            <div class="price-from">
                <div
                    class="
                        price-container
                        price-final_price
                        price__value
                        price__value--between
                    "
                >
                    <span class="price-label price__text">
                        <?= $escaper->escapeHtml(__('From')) ?>
                    </span>
                    <span
                        data-price-amount="<?= $block->convertCurrency($block->getMinPrice()) ?>"
                        data-price-type="minPrice"
                        class="price-wrapper"
                    >
                        <span class="price__value">
                            <?= $escaper->escapeHtml($block->convertAndFormatCurrency($block->getMinPrice(), false)) ?>
                        </span>
                    </span>
                </div>
            </div>
            <div class="price-to">
                <span
                    class="
                        price-container
                        price-final_price
                        tax
                        weee
                        price__value
                        price__value--between
                    "
                >
                    <span class="price-label price__text">
                        <?= $escaper->escapeHtml(__('To')) ?>
                    </span>
                    <span
                        data-price-amount="<?= $block->convertCurrency($block->getMaxPrice()) ?>"
                        data-price-type="maxPrice"
                        class="price-wrapper"
                    >
                        <span class="price__value">
                            <?= $escaper->escapeHtml($block->convertAndFormatCurrency($block->getMaxPrice(), false)) ?>
                        </span>
                    </span>
                </span>
            </div>
        </div>
        <span
            class="
                price-final_price
                price
                display-none
            "
            data-bind="
                visible: !$data.showCustomPrice(),
                css: {
                    'display-none': !$data.isLoaded()
                }
            "
        >
            <span
                class="price-wrapper price__value"
                data-price-amount="
                    <?= $block->isSinglePrice()
                        ? $escaper->escapeHtmlAttr($block->convertCurrency($block->getFinalPrice($product)))
                        : '0';
                    ?>
                "
                data-price-type="finalPrice"
                id="product-price-<?= $escaper->escapeHtmlAttr($productId . $block->getIdSuffix()) ?>"
            >
                <?= $escaper->escapeHtml($block->convertAndFormatCurrency($block->getMinPrice(), false)) ?>
            </span>
        </span>
    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "price": {
                        "component": "Amasty_GiftCard/js/price",
                        "template": "Amasty_GiftCard/price",
                        "prices": <?= /** @noEscape */ $block->getPredefinedAmounts() ?>,
                        "currencyCode": "<?= $escaper->escapeHtmlAttr($block->getCurrencyCode()) ?>",
                        "feeType": "<?= $escaper->escapeHtmlAttr($product->getAmGiftcardFeeType()) ?>",
                        "feeValue": "<?= $escaper->escapeHtmlAttr($product->getAmGiftcardFeeValue()) ?>",
                        "feeStatus": "<?= $escaper->escapeHtmlAttr($product->getAmGiftcardFeeEnable()) ?>",
                        "feeValueConverted": "<?= $escaper->escapeHtmlAttr($this->convertCurrency($product->getAmGiftcardFeeValue())) ?>",
                        "productId": "<?= $escaper->escapeHtmlAttr($product->getId()); ?>",
                        "customMinAmountCurrency": "<?= /** @noEscape */ $block->convertAndFormatCurrency($block->getOpenAmountMin(), false) ?>",
                        "customMaxAmountCurrency": "<?= /** @noEscape */ $block->convertAndFormatCurrency($block->getOpenAmountMax(), false) ?>",
                        "customMinAmount": "<?= $escaper->escapeHtmlAttr($this->convertCurrency($block->getOpenAmountMin())) ?>",
                        "customMaxAmount": "<?= $escaper->escapeHtmlAttr($this->convertCurrency($block->getOpenAmountMax())) ?>",
                        "isOpenAmount": "<?= $escaper->escapeHtmlAttr($block->isOpenAmount()) ?>",
                        "isSinglePrice": "<?= $escaper->escapeHtmlAttr($block->isSinglePrice()) ?>"
                    }
                }
            }
        }
    }
    </script>
<?php endif; ?>
