<?php
/** @var $block \Amasty\GiftCard\Pricing\Render\FinalPriceBox */
/** @var $viewModel \Amasty\GiftCard\ViewModel\Price\Component\Price */
$viewModel = $block->getViewModel();
$productId = $viewModel->getSaleableItem()->getId();
?>

<?php if ($block->getCanShowPrice() !== false && !$block->isProductForm()): ?>
    <div class="price-box">
        <?php if (!$viewModel->isSinglePrice()): ?>
            <span class="price-label price__text">
                <?= $escaper->escapeHtml(__('From')) ?>
            </span>
        <?php endif; ?>
        <span
            class="price__value"
            id="product-price-<?= $escaper->escapeHtmlAttr($productId . $block->getIdSuffix()) ?>"
        >
            <?= $escaper->escapeHtml($viewModel->convertAndFormatCurrency($viewModel->getMinPrice(), false)) ?>
        </span>
    </div>
<?php endif; ?>

<?php if ($block->isProductForm()): ?>
    <?php
    $currency = $block->getCurrencyShortName();
    $product = $viewModel->getSaleableItem();
    ?>
    <div
        class="amgiftcard-price-container"
        data-amcard-js="price-container"
        data-bind="scope: 'price_<?= $escaper->escapeHtmlAttr($productId) ?>'"
    >
        <div
            class="
                amgiftcard-price-multiple
                price
                opacity-0
            "
            data-bind="
                visible: $data.showCustomPrice,
                css: {
                    'opacity-0': $data.isLoaded() === false
                }
            "
        >
            <div class="price-from">
                <div
                    class="
                        price-container
                        price-final_price
                        price__value
                        price__value--between
                    "
                >
                    <span class="price-label price__text">
                        <?= $escaper->escapeHtml(__('From')) ?>
                    </span>
                    <span
                        data-price-amount="<?=  /* @noEscape */ $viewModel->convertCurrency($block->getMinPrice()) ?>"
                        data-price-type="minPrice"
                        class="price-wrapper"
                    >
                        <span class="price__value">
                            <?= $escaper->escapeHtml(/* @noEscape */ $viewModel->convertAndFormatCurrency(/* @noEscape */ $viewModel->getMinPrice(), false)) ?>
                        </span>
                    </span>
                </div>
            </div>
            <div class="price-to">
                <span
                    class="
                        price-container
                        price-final_price
                        tax
                        weee
                        price__value
                        price__value--between
                    "
                >
                    <span class="price-label price__text">
                        <?= $escaper->escapeHtml(__('To')) ?>
                    </span>
                    <span
                        data-price-amount="<?= /* @noEscape */ $viewModel->convertCurrency($block->getMaxPrice()) ?>"
                        data-price-type="maxPrice"
                        class="price-wrapper"
                    >
                        <span class="price__value">
                            <?= $escaper->escapeHtml(/* @noEscape */ $viewModel->convertAndFormatCurrency(/* @noEscape */ $viewModel->getMaxPrice(), false)) ?>
                        </span>
                    </span>
                </span>
            </div>
        </div>
        <span
            class="
                price-final_price
                price
                display-none
            "
            data-bind="
                visible: !$data.showCustomPrice(),
                css: {
                    'display-none': !$data.isLoaded()
                }
            "
        >
            <span
                class="price-wrapper price__value"
                data-price-amount="
                    <?= $viewModel->isSinglePrice()
                        ? $escaper->escapeHtmlAttr(/* @noEscape */ $viewModel->convertCurrency(/* @noEscape */ $viewModel->getFinalPrice($product)))
                        : '0';
                    ?>
                "
                data-price-type="finalPrice"
                id="product-price-<?= $escaper->escapeHtmlAttr($productId . $block->getIdSuffix()) ?>"
            >
                <?= $escaper->escapeHtml(/* @noEscape */ $viewModel->convertAndFormatCurrency(/* @noEscape */ $viewModel->getMinPrice(), false)) ?>
            </span>
        </span>
    </div>

    <?= $block->getPriceComponentHtml() ?>
<?php endif; ?>
