<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>

<?php if ($_product->isSaleable()): ?>
    <button
        type="submit"
        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
        class="
            button
            product-view__update-cart
        "
        id="product-updatecart-button"
    >
        <span>
            <?= $block->escapeHtml($buttonTitle) ?>
        </span>
    </button>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
