<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>

<?php if ($_product->isSaleable()): ?>
    <div class="product-view__update-cart">
        <button
            type="submit"
            title="<?= $buttonTitle ?>"
            class="button product-view__update-cart-btn action tocart"
            id="product-updatecart-button"
        >
            <span>
                <?= $buttonTitle ?>
            </span>
        </button>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
