<?php $url = $block->getReviewsUrl() . '#reviews'; ?>
<?php $urlForm = $block->getReviewsUrl() . '#review-form'; ?>

<?php if ($block->getReviewsCount()): ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <?php if ($rating):?>
        <div
            class="rating__star"
            aria-label="<?= __('Average rating') . ': ' . $rating . '%'; ?>"
            title="<?= __('Average rating') . ': ' . $rating . '%'; ?>"
            style="width:<?= $rating ?>%"
        >
            <span class="rating__indicator"></span>
        </div>
    <?php endif; ?>
<?php elseif ($block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary short empty">
        <a class="action add" href="<?=  $urlForm ?>">
            <?=  __('Be the first to review this product') ?>
        </a>
    </div>
<?php endif; ?>
