<?php
/** @var \Magento\Review\Block\Product\ReviewRenderer $block */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';

?>
<?php if ($block->isReviewEnabled() && $block->getReviewsCount()) : ?>
    <?php
        $reviewsCount = $block->getReviewsCount();
        $rating = $block->getRatingSummary();
    ?>
    <div class="review review--summary">
        <?php if ($rating): ?>
            <div class="review__summary-handle">
                <div
                    class="rating rating--secondary"
                    aria-label="<?= $block->escapeHtmlAttr(__('Average rating') . ': ' . $rating . '%'); ?>"
                    title="<?= $block->escapeHtmlAttr(__('Average rating') . ': ' . $rating . '%'); ?>"
                    tabindex="0"
                >
                    <div
                        class="rating__star"
                        role="presentation"
                        style="width:<?=  $rating; ?>%"
                    >
                        <span class="rating__indicator"></span>
                    </div>
                </div>

                <a
                    href="<?= $url ?>"
                    class="review__amount"
                    title="<?= $block->escapeHtmlAttr($reviewsCount . __(' reviews')); ?>"
                    data-mage-init='{ "goToReview": { "reviewId": "reviews" } }'
                    aria-label="<?= $block->escapeHtmlAttr(__('See ') . $reviewsCount . __(' reviews')); ?>"
                >
                    <?= $reviewsCount . $block->escapeHtml(__(' Reviews')); ?>
                </a>
                <a
                    href="<?= $block->escapeHtmlAttr($urlForm) ?>"
                    title="<?= $block->escapeHtmlAttr(__('Add Your Review')) ?>"
                    class="review__summary-add"
                    data-mage-init='{ "goToReview": { "reviewId": "review-form" } }'
                >
                    <?=  $block->escapeHtml(__('Add Your Review')) ?>
                </a>
            </div>
        <?php endif; ?>
    </div>
<?php elseif ($block->getDisplayIfEmpty()): ?>
    <div class="review review--summary empty">
        <a
            href="<?=  $urlForm; ?>"
            title="<?=  $block->escapeHtmlAttr(__('Be the first to review this product')) ?>"
            data-mage-init='{ "goToReview": { "reviewId": "review-form" } }'
        >
            <?=  $block->escapeHtml(__('Be the first to review this product')) ?>
        </a>
    </div>
<?php endif; ?>
