<?php
/** @var \Magento\Wishlist\Block\Customer\Sharing $block */
?>
<form
    class="dashboard-form form"
    action="<?= $block->escapeUrl($block->getSendUrl()) ?>"
    id="form-validate"
    method="post"
    data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>"
    data-mage-init='{"validation": {}}'
>
    <?= /* @escapeNotVerified */ $block->getBlockHtml('formkey') ?>
    <h3 class="dashboard-form__title">
        <?= /* @escapeNotVerified */ __('Sharing Information') ?>
    </h3>
    <div class="dashboard-form__divider">
        <div class="input">
            <label class="label" for="email_address">
                <?= /* @escapeNotVerified */ __('Email addresses, separated by commas') ?>
            </label>
            <textarea
                class="input__field input__field--textarea"
                name="emails"
                cols="60"
                rows="5"
                id="email_address"
                data-validate="{required: true, 'validate-emails': true}"
            >
                <?= /* @escapeNotVerified */ $block->getEnteredData('emails') ?>
            </textarea>
        </div>
        <div class="input">
            <label class="label" for="message">
                <?= /* @escapeNotVerified */ __('Message') ?>
            </label>
            <textarea
                class="input__field input__field--textarea"
                id="message"
                name="message"
                cols="60"
                rows="5"
            >
                <?= /* @escapeNotVerified */ $block->getEnteredData('message') ?>
            </textarea>
        </div>
        <?php if ($this->helper('Magento\Wishlist\Helper\Rss')->isRssAllow()): ?>
            <div class="checkbox">
                <input
                    type="checkbox"
                    name="rss_url"
                    id="rss_url"
                    value="1"
                    title="<?= /* @escapeNotVerified */ __('Check here to link an RSS feed to your Wish List.') ?>"
                    class="checkbox__field"
                >
                <svg class="checkbox__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
                </svg>
                <label class="checkbox__label" for="rss_url">
                    <?= /* @escapeNotVerified */ __('Check here to link an RSS feed to your Wish List.') ?>
                </label>
            </div>
        <?php endif; ?>
    </div>
    <div class="action">
        <div class="action__handler">
            <button
                type="submit"
                title="<?= /* @escapeNotVerified */ __('Share Wish List') ?>"
                class="button action__button"
            >
                <?= /* @escapeNotVerified */ __('Share Wish List') ?>
            </button>
        </div>
        <div class="action__handler">
            <a
                class="action__link"
                href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
            >
                <?= /* @escapeNotVerified */ __('Back') ?>
            </a>
        </div>
    </div>
</form>
