<?php
/** @var \Magento\Wishlist\Block\Customer\Sharing $block */
?>
<form
    action="<?= $block->escapeUrl($block->getSendUrl()) ?>"
    id="form-validate"
    class="dashboard-form"
    method="post"
    data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
    data-mage-init='{"validation": {}}'
>
    <?= $block->getBlockHtml('formkey') ?>
    <h3 class="dashboard-form__title">
        <?= $block->escapeHtml(__('Sharing Information')); ?>
    </h3>
    <fieldset class="fieldset">
        <legend class="fieldset__legend fieldset__legend--hidden">
            <?= $block->escapeHtml(__('Sharing Information')); ?>
        </legend>
        <div class="input">
            <label
                for="email_address"
                class="
                    label
                    input__label
                "
            >
                <?= $block->escapeHtml(__('Email addresses, separated by commas')); ?>
            </label>
            <textarea
                class="
                    input__field
                    input__field--textarea
                "
                name="emails"
                cols="60"
                rows="5"
                id="email_address"
                data-validate="{required: true, 'validate-emails': true}"
            ><?= $block->escapeHtml($block->getEnteredData('emails')); ?></textarea>
        </div>
        <div class="input">
            <label
                for="message"
                class="
                    label
                    input__label
                "
            >
                <?= $block->escapeHtml(__('Message')); ?>
            </label>
            <textarea
                class="
                    input__field
                    input__field--textarea
                "
                id="message"
                name="message"
                cols="60"
                rows="5"
            ><?= $block->escapeHtml($block->getEnteredData('message')); ?></textarea>
        </div>
        <?php if ($this->helper('Magento\Wishlist\Helper\Rss')->isRssAllow()): ?>
            <div class="checkbox padding-bottom-m">
                <input
                    type="checkbox"
                    name="rss_url"
                    id="rss_url"
                    value="1"
                    title="<?= $block->escapeHtmlAttr(__('Check here to link an RSS feed to your Wish List.')) ?>"
                    class="checkbox__field"
                >
                <svg
                    class="
                        checkbox__icon
                        checkbox__icon--checked
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                </svg>
                <svg
                    class="
                        checkbox__icon
                        checkbox__icon--unchecked
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
                </svg>
                <label
                    class="checkbox__label"
                    for="rss_url"
                >
                    <?= $block->escapeHtml(__('Check here to link an RSS feed to your Wish List.')) ?>
                </label>
            </div>
        <?php endif; ?>
    </fieldset>
    <div class="actions-group">
        <div class="actions-group__handler">
            <button
                type="submit"
                title="<?= $block->escapeHtmlAttr(__('Share Wish List')) ?>"
                class="
                    button
                    actions-group__button
                "
            >
                <?= $block->escapeHtml(__('Share Wish List')); ?>
            </button>
        </div>
        <div class="actions-group__handler">
            <a
                class="actions-group__link"
                href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
            >
                <?= $block->escapeHtml(__('Back')); ?>
            </a>
        </div>
    </div>
</form>
