<?php
/** @var \Magento\Wishlist\Block\Customer\Sidebar $block */
$wishlstViewModel = $block->getData('wishlistDataViewModel');
?>
<?php if ($wishlstViewModel->isAllow()): ?>
    <div data-bind="scope: 'wishlist'">
        <div
            class="sidebar-block"
            data-bind="css: { 'sidebar-block--loaded': !wishlist().counter }"
        >
            <div class="sidebar-block__heading">
                <h2 class="heading--first-level sidebar-block__title">
                    <?= $escaper->escapeHtml($block->getTitle()); ?>
                </h2>
                <!-- ko if: wishlist().counter -->
                <span
                    data-bind="text: wishlist().counter"
                    class="sidebar-block__counter"
                ></span>
                <!-- /ko -->
            </div>

            <div
                class="loader loader--visible"
                data-bind="css: { 'loader--visible': null }"
            >
                <div class="loader__circle"></div>
            </div>

            <!-- ko if: wishlist().counter -->
                <div
                    class="
                        divider
                        sidebar-block__divider
                        sidebar-block__hidden
                    "
                    data-bind="css: { 'sidebar-block__hidden': null }"
                ></div>

                <ol
                    class="
                        list
                        sidebar-block__list
                        sidebar-block__list--hidden
                    "
                    id="wishlist-sidebar"
                    data-bind="
                        foreach: wishlist().items,
                        css: {'sidebar-block__list--hidden': null}
                    "
                >
                    <li class="sidebar-block__wishlist-item">
                        <div
                            class="
                                sidebar-block__item
                                sidebar-block__item--wishlist
                            "
                        >
                            <div class="sidebar-block__product-image">
                                <a data-bind="attr: { href: product_url, title: product_name }">
                                    <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
                                </a>
                            </div>

                            <div class="sidebar-block__product-info">
                                <a
                                    data-bind="attr: { href: product_url }"
                                    class="link sidebar-block__link"
                                >
                                    <span data-bind="text: product_name"></span>
                                </a>
                                <div data-bind="html: product_price"></div>
                            </div>
                        </div>
                        <div>
                            <!-- ko if: product_is_saleable_and_visible -->
                                <button
                                    type="button"
                                    class="
                                        button
                                        button--secondary
                                        sidebar-block__action
                                    "
                                    title="<?= $escaper->escapeHtmlAttr(__('Add product to cart')) ?>"
                                    data-bind="attr: {'data-post': add_to_cart_params}"
                                    data-testid="add-to-cart-wishlist"
                                >
                                    <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                </button>
                            <!-- /ko -->

                            <button
                                type="button"
                                class="
                                    button
                                    button--link
                                    button--secondary
                                    sidebar-block__action
                                "
                                title="<?= $escaper->escapeHtmlAttr(__('Remove product from wish list')) ?>"
                                data-bind="attr: {'data-post': delete_item_params}"
                            >
                                <?= $escaper->escapeHtml(__('Remove')) ?>
                            </button>
                        </div>
                    </li>
                </ol>

                <a
                    class="
                        button
                        button--link
                        sidebar-block__hidden
                    "
                    href="<?= $escaper->escapeUrl($wishlstViewModel->getListUrl()) ?>"
                    title="<?= $escaper->escapeHtmlAttr(__('Go to Wish List')) ?>"
                    data-bind="css: { 'sidebar-block__hidden': null }"
                    data-testid="go-to-wishlist-link"
                >
                    <?= $escaper->escapeHtml(__('Go to Wish List')) ?>
                </a>
            <!-- /ko -->

            <div
                class="sidebar-block__hidden"
                data-bind="css: {'sidebar-block__hidden': null}"
            >
                <!-- ko ifnot: wishlist().counter -->
                    <div class="message empty sidebar-block__message">
                        <?= $escaper->escapeHtml(__('You have no items in your wish list.')) ?>
                    </div>
                <!-- /ko -->
            </div>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "wishlist": {
                            "component": "Magento_Wishlist/js/view/wishlist"
                        }
                    }
                }
            }
        }
    </script>
<?php endif ?>
