<?php
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
?>
<?php if ($wishlistHelper->isAllow()) : ?>
    <div class="sidebar-block" data-bind="scope: 'wishlist'">
        <p class="sidebar-block__heading">
            <span class="sidebar-block__title">
                <?= /* @escapeNotVerified */ $block->getTitle(); ?>
            </span>
            <!-- ko if: wishlist().counter -->
            <span
                data-bind="text: wishlist().counter"
                class="sidebar-block__counter"
            ></span>
            <!-- /ko -->
        </p>

        <!-- ko if: wishlist().counter -->
            <ol
                class="list sidebar-block__list sidebar-block__list--hidden"
                id="wishlist-sidebar"
                data-bind="
                    foreach: wishlist().items,
                    css: {'sidebar-block__list--hidden': null}
                "
            >
                <li class="sidebar-block__wishlist-item">
                    <div class="sidebar-block__item sidebar-block__item--wishlist">
                        <div class="sidebar-block__product-image">
                            <a data-bind="attr: { href: product_url, title: product_name }">
                                <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
                            </a>
                        </div>

                        <div class="sidebar-block__product-info">
                            <a
                                data-bind="attr: { href: product_url }"
                                class="link sidebar-block__link"
                            >
                                <span data-bind="text: product_name"></span>
                            </a>
                            <div data-bind="html: product_price"></div>
                        </div>
                    </div>
                    <div>
                        <!-- ko if: product_is_saleable_and_visible -->
                            <button
                                type="button"
                                class="button button--secondary sidebar-block__action"
                                title="<?= /* @escapeNotVerified */ __('Add product to cart') ?>"
                                data-bind="attr: {'data-post': add_to_cart_params}"
                            >
                                <?= /* @escapeNotVerified */ __('Add to Cart') ?>
                            </button>
                        <!-- /ko -->

                        <button
                            type="button"
                            class="button button--link button--secondary sidebar-block__action"
                            title="<?= /* @escapeNotVerified */ __('Remove product from wish list') ?>"
                            data-bind="attr: {'data-post': delete_item_params}"
                        >
                            <?= /* @escapeNotVerified */ __('Remove') ?>
                        </button>
                    </div>
                </li>
            </ol>

            <a
                class="button button--link"
                href="<?= /* @escapeNotVerified */ $wishlistHelper->getListUrl() ?>"
                title="<?= /* @escapeNotVerified */ __('Go to Wish List') ?>"
            >
                <?= /* @escapeNotVerified */ __('Go to Wish List') ?>
            </a>
        <!-- /ko -->

        <div
            class="sidebar-block__hidden"
            data-bind="css: {'sidebar-block__hidden': null}"
        >
            <!-- ko ifnot: wishlist().counter -->
                <div class="message empty">
                    <?= /* @escapeNotVerified */ __('You have no items in your wish list.') ?>
                </div>
            <!-- /ko -->
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "wishlist": {
                            "component": "Magento_Wishlist/js/view/wishlist"
                        }
                    }
                }
            }
        }
    </script>
<?php endif ?>
