<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist $block */
?>
<?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()): ?>
    <?= $block->getChildHtml('wishlist_item_pager'); ?>
    <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    <form
        class="form-wishlist-items"
        id="wishlist-view-form"
        data-mage-init='{
            "wishlist":{
                "addToCartUrl":<?= $block->getItemAddToCartParams("%item%") ?>,
                "addAllToCartUrl":<?= $block->getAddAllToCartParams() ?>,
                "commentString":""
            },
            "validation": {}
        }'
        action="<?= $block->escapeUrl($block->getUrl('wishlist/index/update', ['wishlist_id' => $block->getWishlistInstance()->getId()])) ?>"
        method="post"
    >
        <?= $block->getChildHtml('top') ?>
        <?php if ($block->hasWishlistItems()): ?>
            <?= $block->getBlockHtml('formkey') ?>
            <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
            <?= $block->getChildHtml('items') ?>
        <?php else: ?>
            <div class="message">
                <?= __('You have no items in your wish list.') ?>
            </div>
        <?php endif ?>
        <?= $block->getChildHtml('bottom') ?>
        <div class="actions-group wishlist__actions">
            <div class="actions-group__handler">
                <?= $block->getChildHtml('control_buttons') ?>
            </div>
            <div class="actions-group__handler">
                <a
                    href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
                    class="link actions-group__link"
                >
                    <?= __('Back') ?>
                </a>
            </div>
        </div>
    </form>
    <script id="form-tmpl" type="text/x-magento-template">
      <form id="wishlist-hidden-form" method="post" action="<%- data.url %>" class="no-display">
          <% if (data.qty) { %>
          <input name="qty" value="<%- data.qty %>">
          <% } %>

          <% if (data.item) { %>
          <input name="item" value="<%- data.item %>">
          <% } %>

          <% if (data.entity) { %>
          <input name="entity" value="<%- data.entity %>">
          <% } %>
      </form>
    </script>
<?php endif ?>
