<?php
/** @var $block \Magento\RequisitionList\Block\Requisition\View\Details */
?>
<div
    class="
        dashboard-actions-toolbar__item
        block block-requisition-list
        link-button
    "
    data-bind="scope: 'move_items_to_requisition'"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "move_items_massaction": {
                        "component": "Magento_RequisitionList/js/requisition/items/grid/massaction",
                        "selectProvider": "requisition.item.grid.selection.provider",
                        "action": "<?= $block->escapeUrl($block->getUrl('requisition_list/item/move')) ?>"
                    },
                    "move_items_to_requisition": {
                        "component": "Magento_RequisitionList/js/requisition/action/items/massaction",
                        "editModuleName": "move_items_to_requisition.edit",
                        "gridMassactionName": "move_items_massaction",
                        "currentListId": "<?= (int) $block->getRequest()->getParam('requisition_id') ?>",
                        "title": "<?= $block->escapeJs(__('Move Selected')) ?>",
                        "mobileLabel": "<?= $block->escapeJs(__('Move')) ?>"
                    },
                    "move_items_to_requisition.edit": {
                        "component": "Magento_RequisitionList/js/requisition/list/edit",
                        "modal": "add_to_requisition_popup",
                        "saveUrl": "<?= $block->escapeUrl($block->getUrl('rest/V1/requisition_lists')) ?>"
                    }
                }
            }
        }
    }
</script>

