<?php
/** @var $block \Magento\RequisitionList\Block\Requisition\View\Details */
/** @var $escaper \Magento\Framework\Escaper */
?>
<!-- ko scope: 'remove_items_massaction' -->
<button
    type="button"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Remove Selected')) ?>"
    data-mobile-label="<?= $escaper->escapeHtmlAttr(__('Remove')) ?>"
    class="
        dashboard-actions-toolbar__item
        button
        button--secondary
        action
        remove-selected
    "
    data-bind="click: applyAction.bind($data, {
        requisition_id: '<?= (int) $block->getRequest()->getParam('requisition_id') ?>'
    })"
>
    <?= $escaper->escapeHtml(__('Remove Selected')) ?>
</button>
<!-- /ko -->
<?php $content = __('Are you sure you would like to remove selected items from the requisition list?'); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "remove_items_massaction": {
                        "component": "Magento_RequisitionList/js/requisition/items/grid/massaction",
                        "selectProvider": "requisition.item.grid.selection.provider",
                        "hasConfirm": true,
                        "confirmConfig": {
                            "content": "<?= $escaper->escapeJs($content) ?>",
                            "modalClass": "requisition-popup modal-slide",
                            "confirmLabel": "<?= $escaper->escapeJs(__('Delete')) ?>"
                        },
                        "action": "<?= $escaper->escapeUrl($block->getUrl('requisition_list/item/delete')) ?>"
                    }
                }
            }
        }
    }
</script>
