<?php
// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info'); ?>

<?php if ($_orders && count($_orders)): ?>
    <div class="dashboard-table">
        <div class="dashboard-table__header">
            <h3 class="dashboard-table__title">
                <?= $block->escapeHtml(__('My Orders')) ?>
            </h3>
        </div>

        <div class="dashboard-table__content">
            <table class="table dashboard-table__table" id="my-orders-table">
                <thead>
                    <tr>
                        <th scope="col" class="id">
                            <?= $block->escapeHtml(__('Order #')) ?>
                        </th>

                        <th scope="col" class="date">
                            <?= $block->escapeHtml(__('Date')) ?>
                        </th>

                        <?= $block->getChildHtml('extra.column.header'); ?>

                        <th scope="col" class="shipping">
                            <?= $block->escapeHtml(__('Ship To')) ?>
                        </th>

                        <th scope="col" class="total">
                            <?= $block->escapeHtml(__('Order Total')) ?>
                        </th>

                        <th scope="col" class="status">
                            <?= $block->escapeHtml(__('Status')) ?>
                        </th>

                        <th scope="col" class="actions">
                            &nbsp;
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($_orders as $_order): ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="id">
                                <?= $_order->getRealOrderId() ?>
                            </td>

                            <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="date">
                                <?= $block->formatDate($_order->getCreatedAt()) ?>
                            </td>

                            <?php $extra = $block->getChildBlock('extra.container'); ?>
                            <?php if ($extra): ?>
                                <?php $extra->setOrder($_order); ?>
                                <?php echo $extra->getChildHtml() ?>
                            <?php endif; ?>

                            <td data-th="<?= $block->escapeHtmlAttr(__('Ship To')) ?>" class="shipping">
                                <?= $_order->getShippingAddress()
                                        ? $block->escapeHtml($_order->getShippingAddress()->getName())
                                        : '&nbsp;'
                                ?>
                            </td>

                            <td data-th="<?= $block->escapeHtmlAttr(__('Order Total')) ?>" class="total">
                                <?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?>
                            </td>

                            <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="status">
                                <?= /* @noEscape */ $_order->getStatusLabel() ?>
                            </td>

                            <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="actions">
                                <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="link dashboard-table__link">
                                    <?= $block->escapeHtml(__('View Order')) ?>
                                </a>

                                <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                     |
                                    <a href="#"
                                       data-post='<?= /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order)); ?>'
                                       class="link"
                                    >
                                        <?= $block->escapeHtml(__('Reorder')) ?>
                                    </a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <?php if ($block->getPagerHtml()): ?>
        <?= $block->getPagerHtml(); ?>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty">
        <?= $block->escapeHtml(__('You have placed no orders.')); ?>
    </div>
<?php endif; ?>
