<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info'); ?>

<?php if ($_orders && count($_orders)): ?>
    <div class="dashboard-table">
        <div class="dashboard-table__header">
            <h2 class="heading dashboard-table__title">
                <?= $block->escapeHtml(__('Recent orders')) ?>
            </h2>
        </div>

        <div class="dashboard-table__content">
            <table
                class="table margin-0"
                tabindex="0"
                role="table"
            >
                <caption class="table__caption">
                    <?= $block->escapeHtml(__('Recent orders')) ?>
                </caption>
                <thead>
                    <tr role="row">
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Order #')) ?>
                        </th>

                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Date')) ?>
                        </th>

                        <?= $block->getChildHtml('extra.column.header'); ?>

                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Order Total')) ?>
                        </th>

                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Status')) ?>
                        </th>

                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <span class="table__visually-hidden">
                                <?= $block->escapeHtml(__('Action')) ?>
                            </span>
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($_orders as $_order): ?>
                        <tr class="row">
                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>"
                                role="gridcell"
                            >
                                <?= $block->escapeHtml($_order->getRealOrderId()) ?>
                            </td>

                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>"
                                role="gridcell"
                            >
                                <?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?>
                            </td>

                            <?php $extra = $block->getChildBlock('extra.container'); ?>

                            <?php if ($extra): ?>
                                <?php $extra->setOrder($_order); ?>
                                <?= $extra->getChildHtml() ?>
                            <?php endif; ?>

                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Order Total')) ?>"
                                role="gridcell"
                            >
                                <?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?>
                            </td>

                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>"
                                role="gridcell"
                            >
                                <?= $block->escapeHtml($_order->getStatusLabel()) ?>
                            </td>

                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>"
                                role="gridcell"
                            >
                                <a
                                    href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>"
                                    class="link dashboard-table__link"
                                >
                                    <?= $block->escapeHtml(__('View Order')) ?>
                                </a>

                                <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())): ?>
                                     |
                                    <a
                                        href="#"
                                        data-post='<?= /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order)) ?>'
                                        class="
                                            action
                                            reorder
                                            link
                                            dashboard-table__link
                                        "
                                    >
                                        <?= $block->escapeHtml(__('Reorder')) ?>
                                    </a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <?php if ($block->getPagerHtml()): ?>
        <?= $block->getPagerHtml(); ?>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty">
        <?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?>
    </div>
<?php endif; ?>
