<?php $_order = $block->getOrder() ?>

<div class="block block-order-details-view">
    <h3 class="dashboard__title">
        <?= $block->escapeHtml(__('Order Information')) ?>
    </h3>

    <div class="row">
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="col-sm-3 information">
                <h4 class="information__title">
                    <?= $block->escapeHtml(__('Shipping Address')) ?>
                </h4>

                <p class="information__text">
                    <address>
                        <?= $block->escapeHtml($block->getFormattedAddress($_order->getShippingAddress())); ?>
                    </address>
                </p>
            </div>

            <div class="col-sm-3 information">
                <h4 class="information__title">
                    <?= $block->escapeHtml(__('Shipping Method')) ?>
                </h4>

                <p class="information__text">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml(__('No shipping information available')); ?>
                    <?php endif; ?>
                </p>
            </div>
        <?php endif; ?>

        <div class="col-sm-3 information">
            <h4 class="information__title">
                <?= $block->escapeHtml(__('Billing Address')) ?>
            </h4>

            <p class="information__text">
                <address>
                    <?= /* @noEscape */ $block->getFormattedAddress($_order->getBillingAddress()); ?>
                </address>
            </p>
        </div>

        <div class="col-sm-3 information">
            <h4 class="information__title">
                <?= $block->escapeHtml(__('Payment Method')) ?>
            </h4>

            <p class="information__text">
                <?= /* @noEscape */ $block->getPaymentInfoHtml() ?>
            </p>
        </div>
    </div>
</div>
