<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <h2 class="heading heading--fifth-level dashboard__title">
        <?php /* @escapeNotVerified */ echo __('Order Information') ?>
    </h2>

    <div class="grid">
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="information grid__column grid__column--1-4">
                <h5 class="heading heading--fifth-level information__title">
                    <?php /* @escapeNotVerified */ echo __('Shipping Address') ?>
                </h5>

                <p class="information__text">
                    <address>
                        <?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getShippingAddress()); ?>
                    </address>
                </p>
            </div>

            <div class="information grid__column grid__column--1-4">
                <h5 class="heading heading--fifth-level information__title">
                    <?php /* @escapeNotVerified */ echo __('Shipping Method') ?>
                </h5>

                <p class="information__text">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?php echo $block->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else: ?>
                        <?php /* @escapeNotVerified */ echo __('No shipping information available'); ?>
                    <?php endif; ?>
                </p>
            </div>
        <?php endif; ?>

        <div class="information grid__column grid__column--1-4">
            <h5 class="heading heading--fifth-level information__title">
                <span><?php /* @escapeNotVerified */ echo __('Billing Address') ?></span>
            </h5>

            <p class="information__text">
                <address>
                    <?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getBillingAddress()); ?>
                </address>
            </p>
        </div>

        <div class="information grid__column grid__column--1-4">
            <h5 class="heading heading--fifth-level information__title">
                <span><?php /* @escapeNotVerified */ echo __('Payment Method') ?></span>
            </h5>

            <p class="information__text">
                <?php echo $block->getPaymentInfoHtml() ?>
            </p>
        </div>
    </div>
</div>
