<?php $_order = $block->getOrder() ?>

<div class="block block-order-details-view">
    <h3 class="dashboard__title">
        <?= /* @escapeNotVerified */ __('Order Information') ?>
    </h3>

    <div class="grid">
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="information grid__column grid__column--1-4">
                <h4 class="information__title">
                    <?= /* @escapeNotVerified */ __('Shipping Address') ?>
                </h4>

                <p class="information__text">
                    <address>
                        <?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getShippingAddress()); ?>
                    </address>
                </p>
            </div>

            <div class="information grid__column grid__column--1-4">
                <h4 class="information__title">
                    <?= /* @escapeNotVerified */ __('Shipping Method') ?>
                </h4>

                <p class="information__text">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?= /* @escapeNotVerified */ $block->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else: ?>
                        <?= /* @escapeNotVerified */ __('No shipping information available'); ?>
                    <?php endif; ?>
                </p>
            </div>
        <?php endif; ?>

        <div class="information grid__column grid__column--1-4">
            <h4 class="information__title">
                <?= /* @escapeNotVerified */ __('Billing Address') ?>
            </h4>

            <p class="information__text">
                <address>
                    <?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getBillingAddress()); ?>
                </address>
            </p>
        </div>

        <div class="information grid__column grid__column--1-4">
            <h4 class="information__title">
                <?= /* @escapeNotVerified */ __('Payment Method') ?>
            </h4>

            <p class="information__text">
                <?= /* @escapeNotVerified */ $block->getPaymentInfoHtml() ?>
            </p>
        </div>
    </div>
</div>
