<?php
    $messageHelper = $this->helper('Magento\GiftMessage\Helper\Message');
?>

<div class="dashboard-table dashboard-table--tab">
    <div class="dashboard-table__header">
        <h3 class="dashboard-table__title">
            <?= __('Items Ordered') ?>
        </h3>
    </div>

    <div class="dashboard-table__content">
        <table
            class="table dashboard-table__table"
            id="my-orders-table"
            summary="<?= __('Items Ordered') ?>"
        >
            <thead>
                <?php if ($block->isPagerDisplayed()): ?>
                    <tr>
                        <td colspan="5"
                            data-block="order-items-pager-top"
                            class="order-pager-wrapper order-pager-wrapper-top"
                        >
                            <?= $block->getPagerHtml() ?>
                        </td>
                    </tr>
                <?php endif; ?>

                <tr>
                    <th class="name">
                        <?= __('Product Name') ?>
                    </th>

                    <th class="sku">
                        <?= __('SKU') ?>
                    </th>

                    <th class="price">
                        <?= __('Price') ?>
                    </th>

                    <th class="qty">
                        <?= __('Qty') ?>
                    </th>

                    <th class="subtotal">
                        <?= __('Subtotal') ?>
                    </th>
                </tr>
            </thead>

            <?php $items = $block->getItems(); ?>
            <?php $giftMessage = ''; ?>

            <?php foreach ($items as $item): ?>
                <?php if ($item->getParentItem()) continue; ?>

                <tbody>
                    <?= $block->getItemHtml($item) ?>

                    <?php
                        $isMessageAllowed = $messageHelper->isMessagesAllowed('order_item', $item);
                    ?>

                    <?php if ($isMessageAllowed && $item->getGiftMessageId()): ?>
                        <?php
                            $giftMessage = $messageHelper->getGiftMessageForEntity($item);
                        ?>
                        <tr>
                            <td class="col options" colspan="5">
                                <a href="#"
                                   id="order-item-gift-message-link-<?= $item->getId() ?>"
                                   class="action show"
                                   aria-controls="order-item-gift-message-<?= $item->getId() ?>"
                                   data-item-id="<?= $item->getId() ?>"
                                >
                                   <?= __('Gift Message') ?>
                                </a>

                                <?php
                                    $giftMessage       = $messageHelper->getGiftMessageForEntity($item);
                                    $escapeGiftMessage = $messageHelper->getEscapedGiftMessage($item);
                                ?>

                                <div class="order-gift-message"
                                     id="order-item-gift-message-<?= $item->getId() ?>"
                                     role="region"
                                     aria-expanded="false"
                                     tabindex="-1"
                                >
                                    <a href="#"
                                       title="<?= __('Close') ?>"
                                       aria-controls="order-item-gift-message-<?= $item->getId() ?>"
                                       data-item-id="<?= $item->getId() ?>"
                                       class="link">
                                        <?= __('Close') ?>
                                    </a>

                                    <dl class="item-options">
                                        <dt class="item-sender">
                                            <strong class="label">
                                                <?= __('From') ?>
                                            </strong>

                                            <?= $block->escapeHtml($giftMessage->getSender()) ?>
                                        </dt>

                                        <dt class="item-recipient">
                                            <strong class="label">
                                                <?= __('To') ?>
                                            </strong>

                                            <?= $block->escapeHtml($giftMessage->getRecipient()) ?>
                                        </dt>

                                        <dd class="item-message">
                                            <?= $escapeGiftMessage ?>
                                        </dd>
                                    </dl>
                                </div>
                            </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            <?php endforeach; ?>

            <tfoot>
                <?php if ($block->isPagerDisplayed()): ?>
                    <tr>
                        <td colspan="5"
                            data-block="order-items-pager-bottom"
                            class="order-pager-wrapper order-pager-wrapper-bottom"
                        >
                            <?= $block->getPagerHtml(); ?>
                        </td>
                    </tr>
                <?php endif; ?>

                <?= $block->getChildHtml('order_totals') ?>
            </tfoot>
        </table>
    </div>
</div>

<?php if ($giftMessage): ?>
<script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>
