<?php
// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Recent */
?>
<div class="dashboard-table">
<?php $_orders = $block->getOrders(); ?>
    <div class="dashboard-table__header">
        <h3 class="dashboard-table__title">
            <?= $block->escapeHtml(__('Recent Orders')) ?>
        </h3>

        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <a class="link dashboard-table__link"
               href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>"
            >
                <?= $block->escapeHtml(__('View All')) ?>
            </a>
        <?php endif; ?>
    </div>

    <div class="dashboard-table__content">
        <?= $block->getChildHtml() ?>
        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <table class="table dashboard-table__table" id="my-orders-table">
                <thead>
                    <tr>
                        <th scope="col" class="col id">
                            <?= $block->escapeHtml(__('Order #')) ?>
                        </th>

                        <th scope="col" class="col date">
                            <?= $block->escapeHtml(__('Date')) ?>
                        </th>

                        <th scope="col" class="col shipping">
                            <?= $block->escapeHtml(__('Ship To')) ?>
                        </th>

                        <th scope="col" class="col total">
                            <?= $block->escapeHtml(__('Order Total')) ?>
                        </th>

                        <th scope="col" class="col status">
                            <?= $block->escapeHtml(__('Status')) ?>
                        </th>

                        <th scope="col" class="col actions">
                            <?= $block->escapeHtml(__('Action')) ?>
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($_orders as $_order): ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="col id">
                                <?= $block->escapeHtml($_order->getRealOrderId()) ?>
                            </td>

                            <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="col date">
                                <?= $block->escapeHtml($block->formatDate($_order->getCreatedAt())) ?>
                            </td>

                            <td data-th="<?= $block->escapeHtmlAttr(__('Ship To')) ?>" class="col shipping">
                                <?= $_order->getShippingAddress()
                                        ? $block->escapeHtml($_order->getShippingAddress()->getName())
                                        : '&nbsp;'
                                ?>
                            </td>

                            <td data-th="<?= $block->escapeHtmlAttr(__('Order Total')) ?>" class="col total">
                                <?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?>
                            </td>

                            <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="col status">
                                <?= $block->escapeHtml($_order->getStatusLabel()) ?>
                            </td>

                            <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                                <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="link dashboard-table__link">
                                    <?= $block->escapeHtml(__('View Order')) ?>
                                </a>

                                <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())): ?>
                                    |
                                    <a href="#"
                                       data-post='<?= /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order)); ?>'
                                       class="link order"
                                    >
                                        <?= $block->escapeHtml(__('Reorder')) ?>
                                    </a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <div class="message info empty">
                <?= $block->escapeHtml(__('You have placed no orders.')); ?>
            </div>
        <?php endif; ?>
    </div>
</div>
