
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else: ?>
        <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
            <td <?= $block->escapeHtmlAttr($block->getLabelProperties()) ?> colspan="4">
                <?php if ($_total->getStrong()):?>
                    <?= $block->escapeHtml($_total->getLabel()) ?>
                <?php else:?>
                    <?= $block->escapeHtml($_total->getLabel()) ?>
                <?php endif?>
            </th>

            <td <?= $block->escapeHtmlAttr($block->getValueProperties()) ?>>
                <?php if ($_total->getStrong()):?>
                    <?= $block->escapeHtml($block->formatValue($_total)) ?>
                <?php else:?>
                    <?= $block->escapeHtml($block->formatValue($_total)) ?>
                <?php endif?>
            </td>
        </tr>
    <?php endif; ?>
<?php endforeach; ?>
