<?php
/**
 * Send to friend form
 */
/** @var \Magento\SendFriend\Block\Send $block */
?>
<script id="add-recipient-tmpl" type="text/x-magento-template">
    <div class="fieldset email-to-friend__inner-fieldset">
        <div class="input required">
            <label
                for="recipients-name<%- data._index_ %>"
                class="input__label"
            >
                <?= $block->escapeHtml(__('Name')) ?>
            </label>
            <input
                name="recipients[name][<%- data._index_ %>]"
                type="text"
                title="<?= $block->escapeJs(__('Name')) ?>"
                class="input__field"
                id="recipients-name<%- data._index_ %>"
                data-validate="{required:true}"
            />
        </div>

        <div class="input required">
            <label
                for="recipients-email<%- data._index_ %>"
                class="input__label">
                    <?= $block->escapeHtml(__('Email')) ?>
            </label>
            <input
                name="recipients[email][<%- data._index_ %>]"
                title="<?= $block->escapeJs(__('Email')) ?>"
                id="recipients-email<%- data._index_ %>"
                type="email"
                class="input__field"
                data-mage-init='{"mage/trim-input":{}}'
                data-validate="{required:true, 'validate-email':true}"
            />
        </div>
        <div class="actions-group">
            <div class="actions-group__handler">
                <button
                    type="button"
                    id="btn-remove<%- data._index_ %>"
                    class="
                        button
                        button--secondary
                        actions-group__button
                        email-to-friend__remove
                        action
                        remove
                    "
                    title="<?= $block->escapeJs(__('Remove Recipent')) ?>"
                >
                    <?= $block->escapeHtml(__('Remove')) ?>
                </button>
            </div>
        </div>
    </div>
</script>

<div class="row email-to-friend">
    <div class="col-xs-12">
        <form
            action="<?= $block->escapeUrl($block->getSendUrl()) ?>"
            method="post"
            id="product-sendtofriend-form"
            data-mage-init='{
                "rowBuilder":{
                    "rowTemplate":"#add-recipient-tmpl",
                    "rowContainer":"#recipients-options",
                    "rowParentElem":"<div></div>",
                    "remEventSelector":"button",
                    "btnRemoveSelector":".action.remove",
                    "maxRows":"<?= (int) $block->getMaxRecipients() ?>",
                    "maxRowsMsg":"#max-recipient-message",
                    "addRowBtn":"#add-recipient-button",
                    "additionalRowClass":"additional"},
                "validation":{}
            }'
            data-hasRequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
        >
            <fieldset
                class="fieldset email-to-friend__fieldset"
                id="sender_options"
            >
                <?= $block->getBlockHtml('formkey') ?>
                <legend
                    class="
                        fieldset__legend
                        email-to-friend__legend
                        text-center
                    "
                >
                    <?= $block->escapeHtml(__('Sender')) ?>
                </legend>
                <div class="input required">
                    <label
                        for="sender-name"
                        class="input__label"
                    >
                        <?= $block->escapeHtml(__('Name')) ?>
                    </label>
                    <input
                        name="sender[name]"
                        value="<?= $block->escapeHtmlAttr($block->getUserName()) ?>"
                        title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                        id="sender-name"
                        type="text"
                        class="input__field"
                        data-validate="{required:true}"
                    />
                </div>

                <div class="input required">
                    <label
                        for="sender-email"
                        class="input__label"
                    >
                        <?= $block->escapeHtml(__('Email')) ?>
                    </label>
                    <input
                        name="sender[email]"
                        value="<?= $block->escapeHtmlAttr($block->getEmail()) ?>"
                        title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                        id="sender-email"
                        type="email"
                        class="input__field"
                        data-mage-init='{"mage/trim-input":{}}'
                        data-validate="{required:true, 'validate-email':true}"
                    />
                </div>

                <div class="input required">
                    <label
                        for="sender-message"
                        class="input__label"
                    >
                        <?= $block->escapeHtml(__('Message')) ?>
                    </label>
                    <textarea
                        name="sender[message]"
                        class="input__field input__field--textarea"
                        id="sender-message"
                        cols="3"
                        rows="3"
                        data-validate="{required:true}"
                    ><?= $block->escapeHtml($block->getMessage()) ?></textarea>
                </div>
            </fieldset>

            <fieldset class="fieldset email-to-friend__fieldset">
                <?= $block->getBlockHtml('formkey') ?>
                <legend
                    class="
                        fieldset__legend
                        email-to-friend__legend
                        text-center
                    "
                >
                    <?= $block->escapeHtml(__('Invitee')) ?>
                </legend>
                <div id="recipients-options"></div>
                <?php if ($block->getMaxRecipients()): ?>
                    <div
                        id="max-recipient-message"
                        style="display: none;"
                        class="message notice limit"
                        role="alert"
                    >
                        <span>
                            <?= $block->escapeHtml(__('Maximum %1 email addresses allowed.', $block->getMaxRecipients())) ?>
                        </span>
                    </div>
                <?php endif; ?>
                <div class="actions-group">
                    <div class="actions-group__handler">
                        <?php if (1 < $block->getMaxRecipients()): ?>
                            <button
                                type="button"
                                id="add-recipient-button"
                                class="
                                    button
                                    button--secondary
                                    actions-group__button
                                "
                            >
                                <?= $block->escapeHtml(__('Add Invitee')) ?>
                            </button>
                        <?php endif; ?>
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
            </fieldset>
            <?= $block->getChildHtml('captcha'); ?>
            <div class="actions-group">
                <div class="actions-group__handler">
                    <button
                        type="submit"
                        class="button actions-group__button"
                        <?php if (!$block->canSend()): ?>
                            disabled="disabled"
                        <?php endif ?>
                    >
                        <?= $block->escapeHtml(__('Send Email')) ?>
                    </button>
                </div>
                <div class="actions-group__handler">
                    <a
                        class="link actions-group__link"
                        href="#"
                        role="back"
                    >
                        <?= $block->escapeHtml(__('Back')) ?>
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>


<script type="text/x-magento-init">
    {
        "a[role='back']": {
            "Magento_SendFriend/js/back-event": {}
        }
    }
</script>
