<?php
/**
 * Send to friend form
 */
/** @var \Magento\SendFriend\Block\Send $block */
?>
<script id="add-recipient-tmpl" type="text/x-magento-template">
    <fieldset class="fieldset email-to-friend__inner-fieldset">
        <div class="input required">
            <label
                for="recipients-name<%- data._index_ %>"
                class="input__label"
            >
                <?= $escaper->escapeHtml(__('Name')) ?>
            </label>
            <input
                name="recipients[name][<%- data._index_ %>]"
                type="text"
                title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                class="input__field"
                id="recipients-name<%- data._index_ %>"
                data-validate="{ required: true }"
                data-mage-init='{"mage/trim-input":{}}'
            />
        </div>

        <div class="input required">
            <label
                for="recipients-email<%- data._index_ %>"
                class="input__label"
            >
                <?= $escaper->escapeHtml(__('Email')) ?>
            </label>
            <input
                name="recipients[email][<%- data._index_ %>]"
                title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                id="recipients-email<%- data._index_ %>"
                type="email"
                class="input__field"
                data-validate="{ required: true, 'validate-email': true }"
                data-mage-init='{"mage/trim-input":{}}'
            />
        </div>
        <button
            type="button"
            id="btn-remove<%- data._index_ %>"
            class="button button--secondary remove email-to-friend__remove"
            title="<?= $escaper->escapeHtmlAttr(__('Remove Recipent')) ?>"
        >
            <?= $escaper->escapeHtml(__('Remove')) ?>
        </button>
    </fieldset>
</script>

<form
    action="<?= $escaper->escapeUrl($block->getSendUrl()) ?>"
    method="post"
    id="product-sendtofriend-form"
    data-mage-init='{
        "rowBuilder": {
            "rowTemplate":"#add-recipient-tmpl",
            "rowContainer":"#recipients-options",
            "rowParentElem":"<div></div>",
            "remEventSelector":"button",
            "btnRemoveSelector":".button.remove",
            "maxRows":"<?= /* @noEscape */ (int)$block->getMaxRecipients() ?>",
            "maxRowsMsg":"#max-recipient-message",
            "addRowBtn":"#add-recipient-button",
            "additionalRowClass":"additional"
        },
        "validation": { }
    }'
    class="email-to-friend"
    data-hasRequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
>
    <fieldset
        class="fieldset email-to-friend__sender-wrapper"
        id="sender_options"
    >
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="heading heading--second-level">
            <?= $escaper->escapeHtml(__('Sender')) ?>
        </legend>
        <div class="input required">
            <label for="sender-name" class="label">
                <?= $escaper->escapeHtml(__('Name')) ?>
            </label>
            <input
                name="sender[name]"
                value="<?= $escaper->escapeHtmlAttr($block->getUserName()) ?>"
                title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                id="sender-name"
                type="text"
                class="input__field"
                data-validate="{ required: true }"
            />
        </div>
        <div class="input required">
            <label for="sender-email" class="label">
                <?= $escaper->escapeHtml(__('Email')) ?>
            </label>
            <input
                name="sender[email]"
                value="<?= $escaper->escapeHtmlAttr($block->getEmail()) ?>"
                title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                id="sender-email"
                type="text"
                class="input__field"
                data-validate="{ required: true, 'validate-email': true }"
            />
        </div>
        <div class="input required">
            <label for="sender-message" class="label">
                <?= $escaper->escapeHtml(__('Message')) ?>
            </label>
            <textarea
                name="sender[message]"
                class="input__field input__field--textarea"
                id="sender-message"
                cols="3"
                data-validate="{ required: true}"
            ><?= $escaper->escapeHtml($block->getMessage()) ?></textarea>
        </div>
    </fieldset>

    <fieldset class="fieldset email-to-friend__fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="heading heading--second-level">
            <?= $escaper->escapeHtml(__('Invitee')) ?>
        </legend>
        <div class="email-to-friend__options" id="recipients-options"></div>
        <?php if ($block->getMaxRecipients()): ?>
            <div
                id="max-recipient-message"
                style="display: none"
                class="message notice limit"
                role="alert"
            >
                <?= $escaper->escapeHtml(__('Maximum %1 email addresses allowed.', $block->getMaxRecipients())) ?>
            </div>
        <?php endif ?>
        <?php if (1 < $block->getMaxRecipients()): ?>
            <button
                type="button"
                id="add-recipient-button"
                class="button button--secondary add"
            >
                <?= $escaper->escapeHtml(__('Add Invitee')) ?>
            </button>
        <?php endif ?>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <?= $block->getChildHtml('captcha'); ?>
    <button
        type="submit"
        class="button email-to-friend__submit"
        <?= !$block->canSend() ? 'disabled' : '' ?>
    >
        <?= $escaper->escapeHtml(__('Send Email')) ?>
    </button>
    <span class="link email-to-friend__back" role="back">
        <?= $escaper->escapeHtml(__('Back')) ?>
    </span>
</form>

<script type="text/x-magento-init">
    {
        "span[role='back']": {
            "Magento_SendFriend/js/back-event": { }
        }
    }
</script>
