<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php $menuClass = $block->getMenu()->getCssClass() ?>

<nav class="<?= $menuClass ?>">
    <ul class="<?= $menuClass ?>__list"
        data-mage-init='{ "sideMenuTrigger": {} }'
    >
        <?php foreach ($block->getNodes() as $node): ?>
            <?php
                $childrenLevel = $node->getLevel() + 1;
                $children = $this->getNodes($childrenLevel, $node);
                $node->setIsParent((bool) $children);
                $parentClass = $children ? ' ' . $menuClass . '__item--parent' : '';
                $additionalClasses = $node->getClasses() ? ' ' . $node->getClasses() : '';
                $itemClasses = $parentClass . $additionalClasses;
            ?>
            <li class="<?= $menuClass ?>__item<?= $itemClasses ?>">
                <?php echo $block->renderMenuNode($node) ?>
                <?php echo $block->renderSubmenu($children, $node, $childrenLevel) ?>
            </li>
        <?php endforeach ?>
    </ul>
</nav>
