<?php if ($block->getWishlistHelper()->isAllow()): ?>
    <button
        class="button button--icon"
        type="submit"
        title="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Add to Wish List')) ?>"
        aria-label="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Add to Wish List')) ?>"
        data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($block->getProduct()) ?>'
        data-action="add-to-wishlist"
        role="button"
    >
        <svg class="button__icon">
            <use xlink:href="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/icons-sprite.svg#heart') ?>"></use>
        </svg>
    </button>
<?php endif; ?>
