<?php
// @codingStandardsIgnoreFile
/** @var $block Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist */
?>
<?php if ($block->getWishlistHelper()->isAllow()): ?>
    <button class="action towishlist button button--icon"
            title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
            aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
            data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($block->getProduct()); ?>'
            data-action="add-to-wishlist"
            role="button"
    >
        <svg title="icon wishlist" class="button__icon">
            <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#wishlist'); ?>"></use>
        </svg>
    </button>
<?php endif; ?>
