<?php
// @codingStandardsIgnoreFile
/** @var $block Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist */
?>
<?php if ($block->getWishlistHelper()->isAllow()): ?>
    <button
        class="
            button
            button--icon
            catalog-list-item__actions-secondary-button
        "
        type="submit"
        title="<?= __('Add to wishlist') ?>"
        aria-label="<?= __('Add to wishlist') ?>"
        data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($block->getProduct()); ?>'
        data-action="add-to-wishlist"
        role="button"
    >
        <svg class="button__icon catalog-list-item__actions-secondary-button-icon">
            <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#heart') ?>"></use>
        </svg>
    </button>
<?php endif; ?>
