<?php
/** @var \Snowdog\SolrNavigation\Block\Navigation\Categories $block */
$subCategories = $block->getSubCategories(2)
?>
<?php if (!empty($subCategories)): ?>
    <li
        class="
            dropdown-list__item
            dropdown-list__item--collapse
            filter
        "
    >
        <div
            class="dropdown-list__label filter__label"
            aria-controls="checkbox"
        >
            <?= __('Category') ?>
            <svg class="icon dropdown-list__icon">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
            </svg>
        </div>
        <div
            id="checkbox"
            class="dropdown-list__content filter__content"
            data-content="checkbox"
            aria-hidden="true"
        >
            <ul class="list filters__category-list">
                <?php foreach ($subCategories as $id => $subCategory): ?>
                    <li class="list__item">
                        <a
                            class="filters__link"
                            href="<?= $block->getCategoryUrl($id) ?>"
                            title="<?= $subCategory['name'] ?>"
                        >
                            <?= $subCategory['name'] ?>
                        </a>
                        <?php if ($subCategory['child']): ?>
                            <ul class="list list--nested">
                                <?php foreach ($subCategory['child'] as $id => $item): ?>
                                    <a
                                        class="filters__link"
                                        href="<?= $block->getCategoryUrl($id) ?>"
                                        title="<?= $item['name'] ?>"
                                    >
                                        <?= $item['name'] ?>
                                    </a>
                                    <?php if ($item['child']): ?>
                                        <ul class="list list--nested">
                                            <?php foreach ($item['child'] as $id => $item): ?>
                                                <a
                                                    class="filters__link"
                                                    href="<?= $block->getCategoryUrl($id) ?>"
                                                    title="<?= $item['name'] ?>"
                                                >
                                                    <?= $item['name'] ?>
                                                </a>
                                            <?php endforeach ?>
                                        </ul>
                                    <?php endif ?>
                                <?php endforeach ?>
                            </ul>
                        <?php endif ?>
                    </li>
                <?php endforeach ?>
            </ul>
            <div class="filter__divider"></div>
        </div>
    </li>
<?php endif ?>
