<?php
/** @var \Snowdog\SolrNavigation\Block\Navigation\Categories $block */
$subCategories = $block->getSubCategories(2)
?>
<?php if (!empty($subCategories)): ?>
    <li
        class="
            dropdown-list__item
            dropdown-list__item--collapse
            filter
        "
    >
        <button
            type="button"
            class="dropdown-list__label filter__label"
            aria-controls="filter-categories"
            aria-expanded="false"
        >
            <h3 class="filter__label-title">
                <?= __('Category') ?>
            </h3>
            <svg class="icon dropdown-list__icon" role="presentation">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
            </svg>
        </button>
        <div
            id="filter-categories"
            class="dropdown-list__content filter__content"
            aria-hidden="true"
        >
            <ul class="list filter__category-list">
                <?php foreach ($subCategories as $id => $subCategory): ?>
                    <li class="list__item filter__category-item">
                        <a
                            class="link filter__category-link"
                            href="<?= $block->getCategoryUrl($id) ?>"
                            title="<?= $subCategory['name'] ?>"
                        >
                            <?= $subCategory['name'] ?>
                        </a>
                        <?php if ($subCategory['child']): ?>
                            <ul class="list filter__category-list--nested">
                                <?php foreach ($subCategory['child'] as $id => $item): ?>
                                    <li class="filter__category-item">
                                        <a
                                            class="link filter__category-link"
                                            href="<?= $block->getCategoryUrl($id) ?>"
                                            title="<?= $item['name'] ?>"
                                        >
                                            <?= $item['name'] ?>
                                        </a>
                                        <?php if ($item['child']): ?>
                                            <ul class="list filter__category-list--nested-second-level">
                                                <?php foreach ($item['child'] as $id => $item): ?>
                                                    <li class="filter__category-item">
                                                        <a
                                                            class="link filter__category-link"
                                                            href="<?= $block->getCategoryUrl($id) ?>"
                                                            title="<?= $item['name'] ?>"
                                                        >
                                                            <?= $item['name'] ?>
                                                        </a>
                                                    </li>
                                                <?php endforeach ?>
                                            </ul>
                                        <?php endif ?>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        <?php endif ?>
                    </li>
                <?php endforeach ?>
            </ul>
            <div class="filter__divider"></div>
        </div>
    </li>
<?php endif ?>
