<?php
/** @var \Snowdog\SolrNavigation\Block\Navigation\ListItem $block */
?>
<li
    class="
        dropdown-list__item
        dropdown-list__item--collapse
        filter
    "
>
    <button
        type="button"
        class="dropdown-list__label filter__label"
        aria-controls="filter-checkbox"
        aria-expanded="false"
    >
        <h3 class="filter__label-title">
            <?= $block->escapeHtml($block->getAttributeLabel()) ?>
        </h3>
        <svg class="icon dropdown-list__icon" role="presentation">
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-down')) ?>"></use>
        </svg>
    </button>
    <div
        id="filter-checkbox"
        class="dropdown-list__content filter__content"
        aria-hidden="true"
    >
        <ul class="list">
            <?php foreach ($block->getItems() as $_item): ?>
                <?php
                $navigationUrl = $block->getNavigationUrl(
                    $block->getAttributeCode(),
                    $_item['value_id']
                );
                ?>
                <li>
                    <a
                        href="<?= $block->escapeUrl($navigationUrl) ?>"
                        class="
                            checkbox
                            checkbox--link
                            <?= $block->isActive($_item['value_id']) ? 'checkbox--link-checked' : '' ?>
                        "
                        title="<?= $_item['label'] ?>"
                    >
                        <svg class="checkbox__icon" role="presentation">
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                        </svg>
                        <span class="checkbox__label">
                            <?= $block->escapeHtml($_item['label']) ?>
                        </span>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
        <div class="filter__divider"></div>
    </div>
</li>
