<?php
/** @var \Snowdog\SolrNavigation\Block\Navigation\ListItem $block */
?>

<li
    class="
        dropdown-list__item
        dropdown-list__item--collapse
        filter
    "
>
    <?php if (strtolower($block->getAttributeLabel()) == 'color') : ?>
        <button
            type="button"
            class="dropdown-list__label filter__label"
            aria-controls="filter-color"
            aria-expanded="false"
        >
            <h3 class="filter__label-title">
                <?= $block->getAttributeLabel() ?>
            </h3>
            <svg class="icon dropdown-list__icon" role="presentation">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
            </svg>
        </button>
        <div
            id="filter-color"
            class="dropdown-list__content filter__content"
            aria-hidden="true"
        >
            <ul class="list filter__list">
                <?php foreach ($block->getItems() as $_item): ?>
                    <li class="filter__color-item">
                        <a
                            href="<?= $block->getNavigationUrl($block->getAttributeCode(), $_item['value_id']) ?>"
                            class="
                                filter__color-option
                                <?= $block->isActive($_item['value_id']) ? 'filter__color-option--active' : '' ?>
                            "
                            title="<?= $_item['label'] ?>"
                        >
                            <div
                                class="filter__color-sample"
                                style="background: <?= $_item['swatch_value'] ?>"
                            ></div>
                            <span class="filter__color-label">
                                <?= $_item['label'] ?>
                            </span>
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
            <div class="filter__divider"></div>
        </div>
    <?php else : ?>
        <button
            type="button"
            class="dropdown-list__label filter__label"
            aria-controls="filter-swatch"
            aria-expanded="false"
        >
            <h3 class="filter__label-title">
                <?= $block->getAttributeLabel() ?>
            </h3>
            <svg class="icon dropdown-list__icon" role="presentation">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
            </svg>
        </button>
        <div
            id="filter-swatch"
            class="dropdown-list__content filter__content"
            aria-hidden="true"
        >
            <ul class="list filter__list">
                <?php foreach ($block->getItems() as $_item): ?>
                    <li class="filter__swatch-item">
                        <a
                            href="<?= $block->getNavigationUrl($block->getAttributeCode(), $_item['value_id']) ?>"
                            class="
                                filter__swatch-option
                                <?= $block->isActive($_item['value_id']) ? 'filter__swatch-option--active' : '' ?>
                            "
                            title="<?= $_item['label'] ?>"
                        >
                            <?= $_item['label'] ?>
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
            <div class="filter__divider"></div>
        </div>
    <?php endif; ?>
</li>
