<?php
/**
 * Temlate for \Magento\Customer\Block\Address\Book block
 * @var $block \Magento\Customer\Block\Address\Book
 */
?>
<div class="dashboard-items">
    <h3 class="dashboard-items__title">
        <?= $block->escapeHtml(__('Default Addresses')) ?>
    </h3>

    <div class="row dashboard-items__content">
        <?php if ($_pAddsses = $block->getDefaultBilling()): ?>
            <div class="col-sm-6 dashboard-items__item">
                <h4>
                    <?= $block->escapeHtml(__('Default Billing Address')) ?>
                </h4>

                <div class="dashboard-items__address">
                    <address>
                        <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                    </address>
                </div>

                <div class="action">
                    <div class="action__handler">
                        <a class="link action__link"
                           href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>"
                        >
                            <?= $block->escapeHtml(__('Change Billing Address')) ?>
                        </a>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <div class="col-sm-6 dashboard-items__item">
                <h4>
                    <?= $block->escapeHtml(__('Default Billing Address')) ?>
                </h4>

                <div class="dashboard-items__address">
                    <p>
                        <?= $block->escapeHtml(__('You have no default billing address in your address book.')) ?>
                    </p>
                </div>
            </div>
        <?php endif ?>

        <?php if ($_pAddsses = $block->getDefaultShipping()): ?>
            <div class="col-sm-6 dashboard-items__item">
                <h4>
                    <?= $block->escapeHtml(__('Default Shipping Address')) ?>
                </h4>

                <div class="dashboard-items__address">
                    <address>
                        <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                    </address>
                </div>

                <div class="action">
                    <div class="action__handler">
                        <a class="link action__link"
                           href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>"
                        >
                            <?= $block->escapeHtml(__('Change Shipping Address')) ?>
                        </a>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <div class="col-sm-6 dashboard-items__item">
                <h4>
                    <?= $block->escapeHtml(__('Default Shipping Address')) ?>
                </h4>

                <div class="dashboard-items__address">
                    <p>
                        <?= $block->escapeHtml(__('You have no default shipping address in your address book.')) ?>
                    </p>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
