<?php
    $addressHelper = $this->helper('Magento\Customer\Helper\Address');
?>

<form class="form-address-edit form"
      action="<?= /* @escapeNotVerified */ $block->getSaveUrl() ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>"
>
    <div class="dashboard-form">
        <h3 class="dashboard-form__title">
            <?= /* @escapeNotVerified */ __('Contact Information') ?>
        </h3>

        <div class="dashboard-form__divider">
            <?= /* @escapeNotVerified */ $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="success_url" value="<?= /* @escapeNotVerified */ $block->getSuccessUrl() ?>">
            <input type="hidden" name="error_url" value="<?= /* @escapeNotVerified */ $block->getErrorUrl() ?>">

            <?= /* @escapeNotVerified */ $block->getNameBlockHtml() ?>

            <div class="input dashboard__input">
                <?php
                    $getCompanyValidationClass = $addressHelper->getAttributeValidationClass('company');
                ?>

                <label class="label" for="company">
                    <?= /* @escapeNotVerified */ __('Company') ?>
                </label>

                <input type="text"
                       name="company"
                       id="company"
                       title="<?= /* @escapeNotVerified */ __('Company') ?>"
                       value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getAddress()->getCompany()) ?>"
                       class="input__field <?= /* @escapeNotVerified */ $getCompanyValidationClass ?>"
                />
            </div>

            <div class="input dashboard__input required">
                <?php
                    $getTelephoneValidationClass = $addressHelper->getAttributeValidationClass('telephone');
                ?>

                <label class="label" for="telephone">
                    <?= /* @escapeNotVerified */ __('Phone Number') ?>
                </label>

                <input type="text"
                       name="telephone"
                       value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getAddress()->getTelephone()) ?>"
                       title="<?= /* @escapeNotVerified */ __('Phone Number') ?>"
                       class="input__field <?= /* @escapeNotVerified */ $getTelephoneValidationClass ?>"
                       id="telephone"
                />
            </div>

            <div class="input dashboard__input">
                <?php
                    $getFaxValidationClass = $addressHelper->getAttributeValidationClass('fax');
                ?>

                <label class="label" for="fax">
                    <?= /* @escapeNotVerified */ __('Fax') ?>
                </label>

                <input type="text"
                       name="fax"
                       id="fax"
                       title="<?= /* @escapeNotVerified */ __('Fax') ?>"
                       value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getAddress()->getFax()) ?>"
                       class="input__field <?= /* @escapeNotVerified */ $getFaxValidationClass ?>"
                />
            </div>
        </div>
    </div>

    <div class="dashboard-form" data-mage-init='{"countryList": {}}'>
        <h3 class="dashboard-form__title">
            <?= /* @escapeNotVerified */ __('Address') ?>
        </h3>

        <div class="dashboard-form__divider">
            <?php
                $_streetValidationClass = $addressHelper->getAttributeValidationClass('street');
            ?>

            <div class="input dashboard__input required">
                <label for="street_1" class="label">
                    <?= /* @escapeNotVerified */ __('Street Address') ?>
                </label>

                <input type="text"
                       name="street[]"
                       value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getStreetLine(1)) ?>"
                       title="<?= /* @escapeNotVerified */ __('Street Address') ?>"
                       id="street_1"
                       class="input__field <?= /* @escapeNotVerified */ $_streetValidationClass ?>"
                />
            </div>

            <?php
                $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass));
                $getStreenLines         = $addressHelper->getStreetLines();
            ?>

            <?php for ($_i = 1, $_n = $getStreenLines; $_i < $_n; $_i++): ?>
                <div class="input dashboard__input">
                    <label class="label" for="street_<?= /* @escapeNotVerified */ $_i+1 ?>">
                        <?= /* @escapeNotVerified */ __('Street Address %1', $_i+1) ?>
                    </label>

                    <input type="text"
                           name="street[]"
                           value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getStreetLine($_i+1)) ?>"
                           title="<?= /* @escapeNotVerified */ __('Street Address %1', $_i+1) ?>"
                           id="street_<?= /* @escapeNotVerified */ $_i+1 ?>"
                           class="input__field <?= /* @escapeNotVerified */ $_streetValidationClass ?>"
                    />
                </div>
            <?php endfor; ?>

            <?php if ($addressHelper->isVatAttributeVisible()) : ?>
                <div class="input dashboard__input">
                    <?php
                        $getVatValidationClass = $addressHelper->getAttributeValidationClass('vat_id');
                    ?>

                    <label class="label" for="vat_id">
                        <?= /* @escapeNotVerified */ __('VAT Number') ?>
                    </label>

                    <input type="text"
                           name="vat_id"
                           value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getAddress()->getVatId()) ?>"
                           title="<?= /* @escapeNotVerified */ __('VAT Number') ?>"
                           class="input__field <?= /* @escapeNotVerified */ $getVatValidationClass ?>"
                           id="vat_id"
                    />
                </div>
            <?php endif; ?>

            <div class="input dashboard__input required">
                <?php
                    $getCityValidationClass = $addressHelper->getAttributeValidationClass('city');
                ?>

                <label class="label" for="city">
                    <?= /* @escapeNotVerified */ __('City') ?>
                </label>

                <input type="text"
                       name="city"
                       value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getAddress()->getCity()) ?>"
                       title="<?= /* @escapeNotVerified */ __('City') ?>"
                       class="input__field <?= /* @escapeNotVerified */ $getCityValidationClass ?>"
                       id="city"
                />
            </div>

            <div class="select dashboard__address dashboard-form__select">
                <?php
                    $isFieldDisabled          = (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';
                    $getRegionValidationClass = $addressHelper->getAttributeValidationClass('region');
                ?>

                <label class="label" for="region_id">
                    <?= /* @escapeNotVerified */ __('State/Province') ?>
                </label>

                <select id="region_id"
                        name="region_id"
                        title="<?= /* @escapeNotVerified */ __('State/Province') ?>"
                        class="select__field select__field--native validate-select"
                        data-mage-init='{"select": {}}'
                        <?= /* @escapeNotVerified */ $isFieldDisabled ?>
                >
                    <option value="" disabled>
                        <?= /* @escapeNotVerified */ __('Please select a region, state or province.') ?>
                    </option>
                </select>

                <input type="text"
                       id="region"
                       name="region"
                       value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getRegion()) ?>"
                       title="<?= /* @escapeNotVerified */ __('State/Province') ?>"
                       class="input__field <?= /* @escapeNotVerified */ $getRegionValidationClass ?>"
                       <?= /* @escapeNotVerified */ $isFieldDisabled ?>
                />
            </div>

            <div class="input dashboard__input required">
                <?php
                    $getPostcodeValidationClass = $addressHelper->getAttributeValidationClass('postcode');
                ?>

                <label class="label" for="zip">
                    <?= /* @escapeNotVerified */ __('Zip/Postal Code') ?>
                </label>

                <input type="text"
                       name="postcode"
                       value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getAddress()->getPostcode()) ?>"
                       title="<?= /* @escapeNotVerified */ __('Zip/Postal Code') ?>"
                       id="zip"
                       class="
                            input__field
                            validate-zip-international
                            <?= /* @escapeNotVerified */ $getPostcodeValidationClass ?>
                       "
                />
            </div>

            <div class="select dashboard__address dashboard-form__select">
                <label class="label" for="country">
                    <?= /* @escapeNotVerified */ __('Country') ?>
                </label>

                <?php $countryList = $block->getCountryCollection()->toOptionArray() ?>

                <select name="country_id"
                        id="country"
                        class="select__field select__field--native required-entry"
                        title="Country"
                        data-validate="{'validate-select':true}"
                        data-mage-init='{"select": {}}'
                        aria-required="true"
                >
                    <option value="" disabled>
                        <?= /* @escapeNotVerified */ __('Please select a country.') ?>
                    </option>

                    <?php for ($i = 1, $n = count($countryList); $i < $n; $i++): ?>
                        <?php if ($block->getCountryId() === $countryList[$i]['value']): ?>
                            <option value="<?= /* @escapeNotVerified */ $countryList[$i]['value'] ?>" selected>
                                <?= $countryList[$i]['label']; ?>
                            </option>
                        <?php else: ?>
                            <option value="<?= /* @escapeNotVerified */ $countryList[$i]['value'] ?>">
                                <?= $countryList[$i]['label']; ?>
                            </option>
                        <?php endif ?>
                    <?php endfor ?>
                </select>
            </div>

            <?php if ($block->isDefaultBilling()): ?>
                <div class="message info">
                    <?= /* @escapeNotVerified */ __("It's a default billing address.") ?>
                </div>
            <?php elseif ($block->canSetAsDefaultBilling()): ?>
                <div class="checkbox dashboard-form__divider">
                    <input type="checkbox"
                           id="primary_billing"
                           name="default_billing"
                           value="1"
                           class="checkbox__field"
                    />

                    <svg class="checkbox__icon">
                        <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
                    </svg>

                    <label class="checkbox__label" for="primary_billing">
                        <?= /* @escapeNotVerified */ __('Use as my default billing address') ?>
                    </label>
                </div>
            <?php else: ?>
                <input type="hidden" name="default_billing" value="1" />
            <?php endif; ?>

            <?php if ($block->isDefaultShipping()): ?>
                <div class="message info">
                    <?= /* @escapeNotVerified */ __("It's a default shipping address.") ?>
                </div>
            <?php elseif ($block->canSetAsDefaultShipping()): ?>
                <div class="checkbox dashboard-form__divider">
                    <input type="checkbox"
                           id="primary_shipping"
                           name="default_shipping"
                           value="1"
                           class="checkbox__field"
                    />

                    <svg class="checkbox__icon">
                        <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
                    </svg>

                    <label class="checkbox__label" for="primary_shipping">
                        <?= /* @escapeNotVerified */ __('Use as my default shipping address') ?>
                    </label>
                </div>
            <?php else: ?>
                <input type="hidden" name="default_shipping" value="1"/>
            <?php endif; ?>
        </div>
    </div>

    <div class="action">
        <div class="action__handler">
            <button type="submit"
                    class="button action__button"
                    data-action="save-address"
                    title="<?= /* @escapeNotVerified */ __('Save Address') ?>"
            >
                <?= /* @escapeNotVerified */ __('Save Address') ?>
            </button>
        </div>

        <div class="action__handler">
            <a class="link action__link"
               href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getBackUrl()) ?>"
            >
                <?= /* @escapeNotVerified */ __('Go back') ?>
            </a>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @escapeNotVerified */($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @escapeNotVerified */ $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?= /* @escapeNotVerified */ $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @escapeNotVerified */ $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
