<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
?>
<div class="users-account">
    <h2>
        <?php /* @escapeNotVerified */ echo __('Address Book') ?>
    </h2>
    <form class="form-address-edit"
          action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>"
          method="post"
          id="form-validate"
          enctype="multipart/form-data"
          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
          aria-label="edit or add address"
    >
        <fieldset class="fieldset users-account__fieldset"
                  aria-labelledby="address-book-contact"
        >
            <h3 class="heading heading--fifth-level"
                id="address-book-contact"
            >
                <?php /* @escapeNotVerified */ echo __('Contact Information') ?>
            </h3>
            <?php echo $block->getBlockHtml('formkey')?>
            <input type="hidden"
                   name="success_url"
                   value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>"
            />
            <input type="hidden"
                   name="error_url"
                   value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>"
            />
            <?php echo $block->getNameBlockHtml() ?>
            <div class="form__field input company">
                <label class="input__label" for="company">
                    <?php /* @escapeNotVerified */ echo __('Company') ?>
                </label>
                <input type="text"
                       name="company"
                       id="company"
                       title="<?php /* @escapeNotVerified */ echo __('Company') ?>"
                       value="<?php echo $block->escapeHtml($block->getAddress()->getCompany()) ?>"
                       class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>"
                />
            </div>
            <div class="form__field input telephone required">
                <label class="input__label" for="telephone">
                    <?php /* @escapeNotVerified */ echo __('Phone Number') ?>
                </label>
                <input type="text"
                       name="telephone"
                       value="<?php echo $block->escapeHtml($block->getAddress()->getTelephone()) ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>"
                       class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>"
                       id="telephone"
                />
            </div>
            <div class="form__field input fax">
                <label class="input__label" for="fax">
                    <?php /* @escapeNotVerified */ echo __('Fax') ?>
                </label>
                <input type="text"
                       name="fax"
                       id="fax"
                       title="<?php /* @escapeNotVerified */ echo __('Fax') ?>"
                       value="<?php echo $block->escapeHtml($block->getAddress()->getFax()) ?>"
                       class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('fax') ?>"
                />
            </div>
        </fieldset>
        <fieldset class="fieldset" aria-labelledby="address-book-address">
            <h3 class="heading heading--fifth-level"
                id="address-book-address"
            >
                <?php /* @escapeNotVerified */ echo __('Address Information') ?>
            </h3>
            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
            <div class="form__field input street required">
                <label for="street_1" class="input__label">
                    <?php /* @escapeNotVerified */ echo __('Street Address') ?>
                </label>
                <input type="text"
                       name="street[]"
                       value="<?php echo $block->escapeHtml($block->getStreetLine(1)) ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>"
                       id="street_1"
                       class="input__field <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>"
                />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="form__field input additional">
                            <label class="input__label"
                                   for="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>"
                            >
                                <?php /* @escapeNotVerified */ echo __('Street Address %1', $_i+1) ?>
                            </label>
                            <input type="text"
                                   name="street[]"
                                   value="<?php echo $block->escapeHtml($block->getStreetLine($_i+1)) ?>"
                                   title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i+1) ?>"
                                   id="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>"
                                   class="input__field <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>"
                             />
                        </div>
                    <?php endfor; ?>
                </div>
            </div>

            <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
                <div class="form__field input taxvat">
                    <label class="input__label" for="vat_id">
                        <?php /* @escapeNotVerified */ echo __('VAT Number') ?>
                    </label>
                    <input type="text"
                           name="vat_id"
                           value="<?php echo $block->escapeHtml($block->getAddress()->getVatId()) ?>"
                           title="<?php /* @escapeNotVerified */ echo __('VAT Number') ?>"
                           class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>"
                           id="vat_id"
                     />
                </div>
            <?php endif; ?>
            <div class="form__field input city required">
                <label class="input__label" for="city">
                    <?php /* @escapeNotVerified */ echo __('City') ?>
                </label>
                <input type="text"
                       name="city"
                       value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>"
                       title="<?php /* @escapeNotVerified */ echo __('City') ?>"
                       class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city"
                />
            </div>
            <div class="form__field input region required">
                <label class="input__label" for="region_id">
                    <?php /* @escapeNotVerified */ echo __('State/Province') ?>
                </label>
                <select id="region_id"
                        name="region_id"
                        title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>"
                        class="validate-select select"
                        <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>
                >
                    <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                </select>
                <input type="text"
                       id="region"
                       name="region"
                       value="<?php echo $block->escapeHtml($block->getRegion()) ?>"
                       title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>"
                       class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"
                       <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>
                 />
            </div>
            <div class="form__field input zip required">
                <label class="input__label" for="zip">
                    <?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>
                </label>
                <input type="text"
                       name="postcode"
                       value="<?php echo $block->escapeHtml($block->getAddress()->getPostcode()) ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip"
                       class="input__field validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>"
                />
            </div>
            <div class="form__field country required">
                <label class="input__label" for="country">
                    <?php /* @escapeNotVerified */ echo __('Country') ?>
                </label>
                <?php echo $block->getCountryHtmlSelect() ?>
            </div>

            <?php if ($block->isDefaultBilling()): ?>
                <div class="message info">
                    <?php /* @escapeNotVerified */ echo __("It's a default billing address.") ?>
                </div>
            <?php elseif ($block->canSetAsDefaultBilling()): ?>
                <div class="form__field checkbox choice set billing">
                    <input type="checkbox"
                           id="primary_billing"
                           name="default_billing"
                           value="1"
                           class="checkbox checkbox__field"
                    />
                    <svg class="checkbox__icon">
                        <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
                    </svg>
                    <label class="checkbox__label" for="primary_billing">
                        <?php /* @escapeNotVerified */ echo __('Use as my default billing address') ?>
                    </label>
                </div>
            <?php else: ?>
                <input type="hidden" name="default_billing" value="1" />
            <?php endif; ?>

            <?php if ($block->isDefaultShipping()): ?>
                <div class="message info">
                    <?php /* @escapeNotVerified */ echo __("It's a default shipping address.") ?>
                </div>
            <?php elseif ($block->canSetAsDefaultShipping()): ?>
                <div class="field checkbox choice set shipping">
                    <input type="checkbox"
                           id="primary_shipping"
                           name="default_shipping"
                           value="1"
                           class="checkbox checkbox__field"
                    />
                    <svg class="checkbox__icon">
                        <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
                    </svg>
                    <label class="checkbox__label" for="primary_shipping">
                        <?php /* @escapeNotVerified */ echo __('Use as my default shipping address') ?>
                    </label>
                </div>
            <?php else: ?>
                <input type="hidden" name="default_shipping" value="1">
            <?php endif; ?>
        </fieldset>
        <div class="users-account__actions actions-toolbar">
            <a class="action back users-account__button"
               href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"
            >
                <?php /* @escapeNotVerified */ echo __('Go back') ?>
            </a>
            <button type="submit"
                    class="action save primary users-account__button-primary"
                    data-action="save-address"
                    title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>"
            >
                <?php /* @escapeNotVerified */ echo __('Save Address') ?>
            </button>

        </div>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
