<?php
/** @var \Magento\Customer\Block\Address\Edit $block */
/** @var \Magento\Customer\ViewModel\Address $viewModel */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$viewModel = $block->getViewModel();
?>
<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<?php $_country_id = $block->getAttributeData()->getFrontendLabel('country_id'); ?>
<?php $_street = $block->getAttributeData()->getFrontendLabel('street'); ?>
<?php $_city = $block->getAttributeData()->getFrontendLabel('city'); ?>
<?php $_region = $block->getAttributeData()->getFrontendLabel('region'); ?>
<?php $_selectRegion = 'Please select a region, state or province.'; ?>
<?php $_displayAll = $block->getConfig('general/region/display_all'); ?>

<?php $_vatidValidationClass = $viewModel->addressGetAttributeValidationClass('vat_id'); ?>
<?php $_cityValidationClass = $viewModel->addressGetAttributeValidationClass('city'); ?>
<?php $_postcodeValidationClass_value = $viewModel->addressGetAttributeValidationClass('postcode'); ?>
<?php $_postcodeValidationClass = $_postcodeValidationClass_value; ?>
<?php $_streetValidationClass = $viewModel->addressGetAttributeValidationClass('street'); ?>
<?php $_streetValidationClassNotRequired = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
<?php $_regionValidationClass = $viewModel->addressGetAttributeValidationClass('region'); ?>
<form
    class="
        row
        form-address-edit
        form
    "
    action="<?= $escaper->escapeUrl($block->getSaveUrl()) ?>"
    method="post"
    id="form-validate"
    enctype="multipart/form-data"
    data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
>
    <div class="col-sm-6 dashboard-form">
        <h3 class="dashboard-form__title">
            <?= $escaper->escapeHtml(__('Contact Information')) ?>
        </h3>

        <div class="dashboard-form__divider">
            <?= $block->getBlockHtml('formkey') ?>
            <input
                type="hidden"
                name="success_url"
                value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>"
            />
            <input
                type="hidden"
                name="error_url"
                value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>"
            />

            <?= $block->getNameBlockHtml() ?>

            <?php if ($_company->isEnabled()): ?>
                <?= $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
            <?php endif ?>

            <?php if ($_telephone->isEnabled()): ?>
                <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
            <?php endif ?>

            <?php if ($_fax->isEnabled()): ?>
                <?= $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
            <?php endif ?>
        </div>
    </div>

    <div class="col-sm-6 dashboard-form">
        <h3 class="dashboard-form__title">
            <?= $escaper->escapeHtml(__('Address')) ?>
        </h3>

        <div class="dashboard-form__divider">
            <div class="input street required">
                <label
                    for="street_1"
                    class="label"
                >
                    <?= /* @noEscape */ $_street ?>
                </label>
                <input
                    type="text"
                    name="street[]"
                    value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                    title="<?= /* @noEscape */ $_street ?>"
                    id="street_1"
                    class="
                        input__field
                        <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>
                    "
                />
            </div>

            <?php for ($_i = 1, $_n = $viewModel->addressGetStreetLines(); $_i < $_n; $_i++): ?>
                <div class="input">
                    <label
                        class="label"
                        for="street_<?= /* @noEscape */ $_i + 1 ?>"
                    >
                        <?= $escaper->escapeHtml(__('Street Address: Line %1', $_i + 1)) ?>
                    </label>
                    <input
                        type="text"
                        name="street[]"
                        value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                        id="street_<?= /* @noEscape */ $_i + 1 ?>"
                        class="
                            input__field
                            <?= $escaper->escapeHtmlAttr($_streetValidationClassNotRequired) ?>
                        "
                    />
                </div>
            <?php endfor; ?>

            <?php if ($viewModel->addressIsVatAttributeVisible()): ?>
                <div class="input taxvat">
                    <label
                        class="label"
                        for="vat_id"
                    >
                        <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>
                    </label>
                    <div class="control">
                        <input
                            type="text"
                            name="vat_id"
                            value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                            title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                            class="
                                input__field
                                <?= $escaper->escapeHtmlAttr($_vatidValidationClass) ?>
                            "
                            id="vat_id"
                        />
                    </div>
                </div>
            <?php endif; ?>

            <div
                class="
                    input
                    city
                    required
                "
            >
                <label
                    class="label"
                    for="city"
                >
                    <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>
                </label>
                <div class="control">
                    <input
                        type="text"
                        name="city"
                        value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                        class="
                            input__field
                            <?= $escaper->escapeHtmlAttr($_cityValidationClass) ?>
                        "
                        id="city"
                    />
                </div>
            </div>

            <div
                class="
                    select
                    dashboard__address
                    dashboard-form__select
                    region
                    required
                "
            >
                <label
                    class="label"
                    for="region_id"
                >
                    <?= /* @noEscape */ $_region ?>
                </label>
                <div class="control">
                    <select
                        id="region_id"
                        name="region_id"
                        title="<?= /* @noEscape */ $_region ?>"
                        class="
                            validate-select
                            region_id
                            select__field
                            select__field--native
                        "
                        <?= /* @noEscape */ !$_displayAll ? 'disabled="disabled"' : '' ?>
                    >
                        <option value="">
                            <?= $escaper->escapeHtml(__($_selectRegion)) ?>
                        </option>
                    </select>
                    <input
                        type="text"
                        id="region"
                        name="region"
                        value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"
                        title="<?= /* @noEscape */ $_region ?>"
                        class="
                            input__field
                            validate-not-number-first
                            <?= $escaper->escapeHtmlAttr($_regionValidationClass) ?>
                        "
                        <?= !$_displayAll ? ' disabled="disabled"' : '' ?>
                    />
                </div>
            </div>

            <div
                class="
                    input
                    zip
                    required
                "
            >
                <label
                    class="label"
                    for="zip"
                >
                    <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>
                </label>
                <input
                    type="text"
                    name="postcode"
                    value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                    title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                    id="zip"
                    class="
                        input__field
                        validate-zip-international
                        <?= $escaper->escapeHtmlAttr($_postcodeValidationClass) ?>
                    "
                />
                <div
                    role="alert"
                    class="message warning"
                    style="display:none"
                >
                    <span></span>
                </div>
            </div>

            <div
                class="
                    input
                    dashboard__address
                    dashboard-form__select
                    country
                    required
                "
            >
                <label
                    class="label"
                    for="country"
                >
                    <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?>
                </label>
                <div class="select">
                    <?php $countryList = $block->getCountryCollection()->toOptionArray() ?>
                    <select
                        name="country_id"
                        id="country"
                        class="
                            select__field
                            select__field--native
                            required-entry
                        "
                        title="Country"
                        data-validate="{'validate-select': true}"
                        aria-required="true"
                    >
                        <option
                            value=""
                            disabled
                        >
                            <?= $escaper->escapeHtml(__('Please select a country.')) ?>
                        </option>

                        <?php for ($i = 0, $n = count($countryList); $i < $n; $i++): ?>
                            <option
                                value="<?= $escaper->escapeHtmlAttr($countryList[$i]['value']) ?>"
                                <?php if ($block->getCountryId() === $countryList[$i]['value']) echo 'selected' ?>
                            >
                                <?= $escaper->escapeHtml($countryList[$i]['label']) ?>
                            </option>
                        <?php endfor ?>
                    </select>
                </div>
            </div>

            <?php if ($block->isDefaultBilling()): ?>
                <div class="message info">
                    <?= $escaper->escapeHtml(__("It's a default billing address.")) ?>
                </div>
            <?php elseif ($block->canSetAsDefaultBilling()): ?>
                <div class="checkbox dashboard-form__divider">
                    <input
                        type="checkbox"
                        id="primary_billing"
                        name="default_billing"
                        value="1"
                        class="checkbox__field"
                    />

                    <svg
                        class="checkbox__icon"
                        role="presentation"
                        focusable="false"
                    >
                        <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked')); ?>"></use>
                    </svg>

                    <label class="checkbox__label" for="primary_billing">
                        <?= $escaper->escapeHtml(__('Use as my default billing address')) ?>
                    </label>
                </div>
            <?php else: ?>
                <input
                    type="hidden"
                    name="default_billing"
                    value="1"
                />
            <?php endif; ?>

            <?php if ($block->isDefaultShipping()): ?>
                <div class="message info">
                    <?= $escaper->escapeHtml(__("It's a default shipping address.")) ?>
                </div>
            <?php elseif ($block->canSetAsDefaultShipping()): ?>
                <div class="checkbox dashboard-form__divider">
                    <input
                        type="checkbox"
                        id="primary_shipping"
                        name="default_shipping"
                        value="1"
                        class="checkbox__field"
                    />

                    <svg
                        class="checkbox__icon"
                        role="presentation"
                        focusable="false"
                    >
                        <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked')); ?>"></use>
                    </svg>

                    <label class="checkbox__label" for="primary_shipping">
                        <?= $escaper->escapeHtml(__('Use as my default shipping address')) ?>
                    </label>
                </div>
            <?php else: ?>
                <input
                    type="hidden"
                    name="default_shipping"
                    value="1"
                />
            <?php endif; ?>
        </div>
    </div>

    <div class="action">
        <div class="action__handler">
            <button
                type="submit"
                class="button action__button"
                data-action="save-address"
                title="<?= $escaper->escapeHtmlAttr(__('Save Address')) ?>"
            >
                <?= $escaper->escapeHtml(__('Save Address')) ?>
            </button>
        </div>

        <div class="action__handler">
            <a
                class="link action__link"
                href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"
            >
                <?= $escaper->escapeHtml(__('Go back')) ?>
            </a>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes() ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $_displayAll ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $viewModel->dataGetRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $viewModel->dataGetCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
