<?php

/** @var \Magento\Customer\Block\Address\Grid $block */
$customerAddressView = $block->getData('customer_address');
?>

<div class="dashboard-table">
    <div class="dashboard-table__header">
        <h3 class="dashboard-table__title">
            <?= $block->escapeHtml(__('Additional Address Entries')); ?>
        </h3>
    </div>
    <?php if ($_pAddsses = $block->getAdditionalAddresses()) : ?>
        <div class="dashboard-table__content">
            <table 
                class="table dashboard-table__table" 
                id="additional-addresses-table"
            >
                <thead>
                    <tr>
                        <th scope="col" class="col firstname">
                            <?= $block->escapeHtml(__('First Name')) ?>
                        </th>
                        <th scope="col" class="col lastname">
                            <?= $block->escapeHtml(__('Last Name')) ?>
                        </th>
                        <th scope="col" class="col streetaddress">
                            <?= $block->escapeHtml(__('Street Address')) ?>
                        </th>
                        <th scope="col" class="col city">
                            <?= $block->escapeHtml(__('City')) ?>
                        </th>
                        <th scope="col" class="col country">
                            <?= $block->escapeHtml(__('Country')) ?>
                        </th>
                        <th scope="col" class="col state">
                            <?= $block->escapeHtml(__('State')) ?>
                        </th>
                        <th scope="col" class="col zip">
                            <?= $block->escapeHtml(__('Zip/Postal Code')) ?>
                        </th>
                        <th scope="col" class="col phone">
                            <?= $block->escapeHtml(__('Phone')) ?>
                        </th>
                        <th scope="col" class="col actions">
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($_pAddsses as $address) : ?>
                        <tr>
                            <td 
                                data-th="<?= $block->escapeHtmlAttr(__('First Name')) ?>" 
                                class="col firstname"
                            >
                                <?= $block->escapeHtml($address->getFirstname()) ?>
                            </td>
                            <td 
                                data-th="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" 
                                class="col lastname"
                            >
                                <?= $block->escapeHtml($address->getLastname()) ?>
                            </td>
                            <td 
                                data-th="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" 
                                class="col streetaddress"
                            >
                                <?= $block->escapeHtml($block->getStreetAddress($address)) ?>
                            </td>
                            <td 
                                data-th="<?= $block->escapeHtmlAttr(__('City')) ?>" 
                                class="col city"
                            >
                                <?= $block->escapeHtml($address->getCity()) ?>
                            </td>
                            <td 
                                data-th="<?= $block->escapeHtmlAttr(__('Country')) ?>" 
                                class="col country"
                            >
                                <?= $block->escapeHtml($block->getCountryByCode($address->getCountryId())) ?>
                            </td>
                            <td 
                                data-th="<?= $block->escapeHtmlAttr(__('State')) ?>" 
                                class="col state"
                            >
                                <?= $block->escapeHtml($address->getRegion()->getRegion()) ?>
                            </td>
                            <td 
                                data-th="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>" class="col zip"><?= $block->escapeHtml($address->getPostcode()) ?></td>
                            <td 
                                data-th="<?= $block->escapeHtmlAttr(__('Phone')) ?>" 
                                class="col phone"
                            >
                                <?= $block->escapeHtml($address->getTelephone()) ?>
                            </td>
                            <td 
                                data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" 
                                class="col actions"
                            >
                                <a 
                                    class="action edit" 
                                    href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $address->getId()])) ?>"
                                >
                                    <?= $block->escapeHtml(__('Edit')) ?>
                                </a>
                                <a 
                                    class="action delete" 
                                    href="#" 
                                    role="delete-address" 
                                    data-address="<?= $block->escapeHtmlAttr($address->getId()) ?>"
                                >
                                    <?= $block->escapeHtml(__('Delete')) ?>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php if ($block->getChildHtml('pager')) : ?>
            <?= $block->getChildHtml('pager') ?>
        <?php endif ?>
    <?php else : ?>
        <p class="message info empty">
            <?= $block->escapeHtml(__('You have no other address entries in your address book.')) ?>
        </p>
    <?php endif ?>
</>

<div class="action">
    <div class="action__handler">
        <button 
            type="button" 
            role="add-address" 
            title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>" 
            class="
                button 
                action__button 
                primary 
                add
            "
        >
            <?= $block->escapeHtml(__('Add New Address')) ?>
        </button>
    </div>
    <div class="action__handler">
        <a 
            class="link action__link action back" 
            href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>"
        >
            <?= $block->escapeHtml(__('Back')) ?>
        </a>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "td a[role='delete-address']",
                "deleteUrlPrefix": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteUrl())) ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
