<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
$fieldNameFile = \Magento\AdvancedCheckout\Model\Import::FIELD_NAME_SOURCE_FILE;
$fieldImportedFlagFile = \Magento\AdvancedCheckout\Helper\Data::REQUEST_PARAMETER_SKU_FILE_IMPORTED_FLAG;
$extErrorText = __(
    'The file could not be uploaded because it is in the wrong format. Please select a CSV file to upload.'
);
?>
<div class="field upload skus">
    <label class="label" for="customer_sku_csv">
        <span><?= $block->escapeHtml(__('Add from File')) ?></span>
    </label>
    <div class="control" data-mage-init='{"fieldsetControls": {}, "fileChooser": {
            "fileNameSelector": "[name=<?= $block->escapeHtml($fieldNameFile) ?>]",
            "fileNameIndicatorSelector": "[name=<?= $block->escapeHtml($fieldImportedFlagFile) ?>]"
            },
            "quickOrderFile":{
            "fileNameSelector": "[name=<?= $block->escapeHtml($fieldNameFile) ?>]",
            "extErrorText": "<?= $block->escapeHtml($extErrorText) ?>",
            "urlSku":"<?= $block->escapeHtml($block->getUrl('quickorder/ajax/search')) ?>"
            }}'>
        <div class="note">
            <p><?= /* @noEscape */ $block->escapeHtml(__('File must be in .csv format and include "SKU" and "QTY" columns')); ?>
               <?= /* @noEscape */ $block->getChildHtml('quick_order_download_template_link') ?></p>
        </div>
        <div class="upload-container">
            <div class="file-upload"><?= $block->escapeHtml(__('Choose File')) ?></div>
            <input id="customer_sku_csv" type="file" data-reset="true" class="action-upload"
                name="<?= $block->escapeHtml($fieldNameFile) ?>"
                >
        </div>
    </div>
</div>
