<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
$fieldNameFile = \Magento\AdvancedCheckout\Model\Import::FIELD_NAME_SOURCE_FILE;
$fieldImportedFlagFile = \Magento\AdvancedCheckout\Helper\Data::REQUEST_PARAMETER_SKU_FILE_IMPORTED_FLAG;
$extErrorText = $block->escapeHtml(__(
    'The file could not be uploaded because it is in the wrong format. Please select a CSV file to upload.'
));
?>
<li class="list__item quickorder__list-item">
    <p>
        <?= $block->escapeHtml(__('Add from File')) ?>
    </p>
    <div
        class="control"
        data-mage-init='{
            "fieldsetControls": {},
            "fileChooser": {
                "fileNameSelector": "[name=<?= $block->escapeHtmlAttr($fieldNameFile) ?>]",
                "fileNameIndicatorSelector": "[name=<?= $block->escapeHtmlAttr($fieldImportedFlagFile) ?>]"
            },
            "quickOrderFile":{
                "fileNameSelector": "[name=<?= $block->escapeHtmlAttr($fieldNameFile) ?>]",
                "extErrorText": "<?= $block->escapeHtmlAttr($extErrorText) ?>",
                "urlSku":"<?= $block->escapeUrl($block->getUrl('quickorder/ajax/search')) ?>"
            }
        }'>
        <p>
            <?= __('File must be in .csv format and include "SKU" and "QTY" columns'); ?>
            <?= $block->getChildHtml('quick_order_download_template_link') ?>
        </p>
        <div class="upload-container">
            <label for="customer_sku_csv">
                <?= $block->escapeHtml(__('Choose File')) ?>
            </label>
            <input
                id="customer_sku_csv"
                type="file"
                data-reset="true"
                accept=".csv"
                name="<?= $block->escapeHtmlAttr($fieldNameFile) ?>"
            >
        </div>
    </div>
</li>
