<div class="blank-notice">
    <a
        class="
            logo
            blank-notice__logo
        "
        href="<?= $block->getUrl(''); ?>"
        aria-label="<?= $block->escapeHtmlAttr(__('Alpaca Home page link')) ?>"
    >
        <svg
            class="logo__image"
            role="presentation"
            focusable="false"
        >
            <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#logo')); ?>"></use>
        </svg>
    </a>
    <div class="blank-notice__container">
        <?= $this->getChildHtml('cms_page_content') ?>
    </div>
</div>
