<?php
$placeholder = 'data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAABCAQAAABN/Pf1AAAAC0lEQVR42mNkwAIAACoAAgu1Hc4AAAAASUVORK5CYII=';
$logo = $block->escapeUrl($block->getViewFileUrl('images/logo/logo.svg'));
?>
<div class="blank-notice">
    <a
        class="
            logo
            blank-notice__logo
        "
        href="<?= $block->getUrl(''); ?>"
        aria-label="<?= $block->escapeHtmlAttr(__('Alpaca Home page link')) ?>"
    >
        <img
            class="logo__image"
            alt="<?= $block->escapeHtmlAttr(__('Alpaca Logo')) ?>"
            src="<?= $logo ?>"
        >
    </a>
    <div class="blank-notice__container">
        <?= $this->getChildHtml('cms_page_content') ?>
    </div>
</div>
