<div
    data-bind="scope: 'messages'"
    class="messages__wrap"
    aria-live="assertive"
    data-aos="fade-down"
    data-aos-anchor=".header"
    data-aos-anchor-placement="bottom-top"
>
    <div>
        <div
            data-bind="foreach: { data: cookieMessages, as: 'message' }, visible: isVisible()"
            class="messages"
        >
            <div data-bind="
                    attr: {
                        class:
                            'message '
                            + 'message--' + message.type
                            + ' ' + message.type,
                        'data-ui-id': 'message-' + message.type,
                    }
                "
            >
                <div data-bind="html: $parent.prepareMessageForHtml(message.text)"></div>
            </div>
        </div>
    </div>
    <div>
        <div
            data-bind="foreach: { data: messages().messages, as: 'message' }, visible: isVisible()"
            class="messages"
        >
            <div data-bind="
                    attr: {
                        class:
                            'message '
                            + 'message--' + message.type
                            + ' ' + message.type,
                        'data-ui-id': 'message-' + message.type,
                    }
                "
            >
                <div data-bind="html: $parent.prepareMessageForHtml(message.text)"></div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "messages": {
                        "component": "Magento_Theme/js/view/messages"
                    }
                }
            }
        }
    }
</script>
