<!doctype html>
<html <?= $htmlAttributes ?>>
    <head <?= $headAttributes ?>>
        <?php // TODO: Critical css ?>
        <style>
            body {
                opacity: 0;
            }
        </style>

        <link
            href="<?= /* @noEscape */ $this->getViewFileUrl('css/styles.css') ?>"
            rel="stylesheet"
            as="style"
            media="print"
            onload="this.media='all'"
        />

        <link
            rel="preload"
            href="<?= /* @noEscape */ $this->getViewFileUrl('fonts/work-sans-regular.woff2') ?>"
            as="font"
            type="font/woff2"
            crossorigin
        >

        <link
            rel="preload"
            href="<?= /* @noEscape */ $this->getViewFileUrl('fonts/work-sans-medium.woff2') ?>"
            as="font"
            type="font/woff2"
            crossorigin
        >

        <link
            rel="preload"
            href="<?= /* @noEscape */ $this->getViewFileUrl('fonts/work-sans-bold.woff2') ?>"
            as="font"
            type="font/woff2"
            crossorigin
        >

        <link
            rel="preload"
            href="<?= /* @noEscape */ $this->getViewFileUrl('fonts/playfair-display-regular.woff2') ?>"
            as="font"
            type="font/woff2"
            crossorigin
        >

        <?= /* @noEscape */ $requireJs ?>
        <?= /* @noEscape */ $headContent ?>
        <?= /* @noEscape */ $headAdditional ?>
    </head>
    <body
        data-container="body"
        data-mage-init='{
            "loaderAjax": {},
            "loader": {
                "icon": "<?= /* @noEscape */ $loaderIcon ?>"
            }
        }'
        <?= /* @noEscape */ $bodyAttributes ?>
    >
        <?= /* @noEscape */ $layoutContent ?>
    </body>
</html>
