<!doctype html>
<html <?= $htmlAttributes ?>>
    <head <?= $headAttributes ?>>
        <script
            src="<?= $this->getViewFileUrl('Magento_Theme::js/lib/core.min.js'); ?>"
            type="text/javascript"
        ></script>
        <?= $requireJs ?>
        <?= $headContent ?>
        <?= $headAdditional ?>
    </head>
    <body
        data-container="body"
        data-mage-init='{
            "loaderAjax": {},
            "loader": {
                "icon": "<?= $loaderIcon ?>"
            }
        }'
        <?= $bodyAttributes ?>
    >
        <?= $layoutContent ?>
    </body>
</html>
