<!doctype html>
<html <?= /* @noEscape */ $htmlAttributes ?>>
    <head <?= /* @noEscape */ $headAttributes ?>>
        <script
            src="<?= $this->getViewFileUrl('Magento_Theme::js/lib/core.min.js'); ?>"
            type="text/javascript"
        ></script>
        <?= /* @noEscape */ $requireJs ?>
        <?= /* @noEscape */ $headContent ?>
        <?= /* @noEscape */ $headAdditional ?>
    </head>
    <body
        data-container="body"
        data-mage-init='{
            "loaderAjax": {},
            "loader": {
                "icon": "<?= /* @noEscape */ $loaderIcon ?>"
            }
        }'
        <?= /* @noEscape */ $bodyAttributes ?>
    >
        <?= /* @noEscape */ $layoutContent ?>
    </body>
</html>
