<div class="dashboard-items">
    <div class="dashboard-table__header">
        <h3 class="dashboard-table__title">
            <?= __('Address Book') ?>
        </h3>

        <a class="link dashboard-table__link"
           href="<?= $block->getAddressBookUrl() ?>"
        >
            <?= __('Manage Addresses') ?>
        </a>
    </div>

    <div class="row dashboard-items__content">
        <div class="col-sm-6 dashboard-items__item">
            <h4>
                <?= __('Default Billing Address') ?>
            </h4>

            <div class="dashboard-items__address">
                <address>
                    <?= $block->getPrimaryBillingAddressHtml() ?>
                </address>
            </div>

            <div class="action">
                <div class="action__handler">
                    <a class="link action__link "
                       href="<?= $block->getPrimaryBillingAddressEditUrl() ?>"
                       data-ui-id="default-billing-edit-link"
                    >
                        <?= __('Edit Address') ?>
                    </a>
                </div>
            </div>
        </div>

        <div class="col-sm-6 dashboard-items__item">
            <h4>
                <?= __('Default Shipping Address') ?>
            </h4>

            <div class="dashboard-items__address">
                <address>
                    <?= $block->getPrimaryShippingAddressHtml() ?>
                </address>
            </div>

            <div class="action">
                <div class="action__handler">
                    <a class="link action__link "
                       href="<?= $block->getPrimaryShippingAddressEditUrl() ?>"
                       data-ui-id="default-shipping-edit-link"
                    >
                        <?= __('Edit Address') ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
