<div class="dashboard-items">
    <div class="dashboard-table__header">
        <h5 class="heading heading--fifth-level dashboard-table__title ">
            <?php /* @escapeNotVerified */ echo __('Address Book') ?>
        </h5>

        <a class="link dashboard-table__link" 
           href="<?php /* @escapeNotVerified */ echo $block->getAddressBookUrl() ?>"
        >
            <?php /* @escapeNotVerified */ echo __('Manage Addresses') ?>
        </a>
    </div>

    <div class="grid dashboard-items__content">
        <div class="dashboard-items__item grid__column grid__column--1-2">
            <h5 class="heading heading--sixth-level">
                <span><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></span>
            </h5>

            <div class="dashboard-items__address">
                <address>
                    <?php echo $block->getPrimaryBillingAddressHtml() ?>
                </address>
            </div>

            <div class="action">
                <div class="action__handler">
                    <a class="link action__link " 
                       href="<?php /* @escapeNotVerified */ echo $block->getPrimaryBillingAddressEditUrl() ?>" 
                       data-ui-id="default-billing-edit-link"
                    >
                        <?php /* @escapeNotVerified */ echo __('Edit Address') ?>
                    </a>
                </div>
            </div>
        </div>

        <div class="dashboard-items__item grid__column grid__column--1-2">
            <h5 class="heading heading--sixth-level">
                <span><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></span>
            </h5>

            <div class="dashboard-items__address">
                <address>
                    <?php echo $block->getPrimaryShippingAddressHtml() ?>
                </address>
            </div>

            <div class="action">
                <div class="action__handler">
                    <a class="link action__link " 
                       href="<?php /* @escapeNotVerified */ echo $block->getPrimaryShippingAddressEditUrl() ?>" 
                       data-ui-id="default-shipping-edit-link"
                    >
                        <?php /* @escapeNotVerified */ echo __('Edit Address') ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
