<div class="dashboard-items">
    <h2 class="dashboard-items__title margin-bottom-sm">
        <?= $block->escapeHtml(__('Account Information')) ?>
    </h2>

    <div class="row dashboard-items__content">
        <div class="col-sm-6 dashboard-items__item">
            <h3 class="dashboard-items__subtitle margin-bottom-l">
                <?= $block->escapeHtml(__('Contact Information')) ?>
            </h3>

            <div class="margin-bottom-l">
                <?= $block->escapeHtml($block->getName()) ?>
                <br>
                <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>
            </div>

            <div class="actions-group margin-bottom-xl">
                <div class="actions-group__handler">
                    <a
                        href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>"
                        class="
                            link
                            actions-group__link
                            dashboard__link
                            padding-0
                        "
                    >
                        <?= $block->escapeHtml(__('Edit')) ?>
                    </a>

                    <a
                        href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>"
                        class="
                            link
                            actions-group__link
                            dashboard__link
                            padding-0
                        "
                    >
                        <?= $block->escapeHtml(__('Change Password')) ?>
                    </a>
                </div>
            </div>
        </div>

        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="col-sm-6 dashboard-items__item">
                <h3 class="dashboard-items__subtitle margin-bottom-l">
                    <?= $block->escapeHtml(__('Newsletters')) ?>
                </h3>

                <div class="margin-bottom-l">
                    <?php if ($block->getIsSubscribed()): ?>
                        <?= $block->escapeHtml(__('You subscribe to "General Subscription".')) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml(__('You don\'t subscribe to our newsletter.')) ?>
                    <?php endif; ?>

                    <?php /* Extensions placeholder */ ?>
                    <?= $block->getChildHtml('customer.account.dashboard.info.extra') ?>
                </div>

                <div class="actions-group margin-bottom-xl">
                    <div class="actions-group__handler">
                        <a
                            class="link actions-group__link"
                            href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"
                        >
                           <?= $block->escapeHtml(__('Edit')) ?>
                        </a>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?= $block->getChildHtml('additional_blocks'); ?>
    </div>
</div>
