<div class="wishlist__select margin-hz-xs">
    <div class="checkbox">
        <label class="margin-0">
            <input
                type="checkbox"
                class="
                    checkbox
                    product-item-checkbox
                    checkbox__field
                "
                name="selected[<?= /* @noEscape */ $block->getItem()->getId()*1 ?>]"
                data-role="select-product"
            />
            <svg
                class="
                    checkbox__icon
                    checkbox__icon--checked
                "
                role="presentation"
                focusable="false"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
            </svg>
            <svg
                class="
                    checkbox__icon
                    checkbox__icon--unchecked
                "
                role="presentation"
                focusable="false"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
            </svg>
            <span
                class="checkbox__label"
            >
                <?= $block->escapeHtml(__('Select Product')) ?>
            </span>
        </label>
    </div>
</div>
