<?php
/** @var \Amasty\GdprCookie\Block\CookieBar $block */

$cookiePrivacyTextJson = $block->getCookiePolicyText();
$groupsJson = $block->getAllGroups();
$groups = json_decode($groupsJson, true);
$cookiePrivacyText = json_decode($cookiePrivacyTextJson, true);
?>
<?php if ($block->getNoticeType() === \Amasty\GdprCookie\Model\Config\Source\CookiePolicyBarStyle::CONFIRMATION_MODAL && $groups): ?>
    <div
        data-role="gdpr-cookie-container"
        class="amgdprcookie-modal-template"
        data-amgdpr-js="modal"
    >
        <div
            data-bind="mageInit: {
                'cookieModal': {
                    'isNotice': '<?= $block->escapeHtmlAttr($block->isNotice()) ?>',
                    'websiteInteraction': '<?= $block->escapeHtmlAttr($block->getWebsiteInteraction()) ?>',
                    'settingsLink': '<?= $block->escapeUrl($block->getSettingsLink()) ?>',
                    'firstShowProcess': '<?= $block->escapeHtmlAttr($block->isProcessFirstShow()) ?>'
                }
            }"
            role="dialog"
            aria-hidden="true"
            id="cookie-modal"
            data-modal="cookie-modal"
            class="modal"
        >
            <div class="modal__container modal__cookies-container">
                <form
                    id="amgdprcookie-form"
                    class="amgdprcookie-settings-form"
                    data-amcookie-js="form-cookie"
                    data-modal="cookie-modal"
                >
                    <button
                        class="
                            button
                            button--icon
                            button--rotate-icon
                            modal__close-button
                        "
                        type="button"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Close modal')) ?>"
                    >
                        <svg
                            class="
                                icon
                                button__icon
                                modal__close-button-icon
                            "
                            role="presentation"
                            focusable="false"
                        >
                            <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#close')); ?>"></use>
                        </svg>
                    </button>
                    <div
                        data-amcookie-js="groups"
                        class="margin-bottom-xl modal__content"
                    >
                        <?php foreach ($groups as $key => $group): ?>
                            <div class="margin-bottom-l">
                                <h2>
                                    <?= $block->escapeHtml(__($group['name'])) ?>
                                </h2>
                                <div
                                    class="
                                        field
                                        choice
                                        checkbox
                                    "
                                >
                                    <input
                                        id="<?= 'switch-box-' . $key ?>"
                                        class="checkbox__field <?= $group['isEssential'] ? 'checkbox__field--disabled' : ''; ?>"
                                        type="checkbox"
                                        data-amcookie-js="field"
                                        name="groups[]"
                                        value="<?= /** @noEscape */ (int) $group['groupId'] ?>"
                                        <?= $group['isEssential'] ? 'disabled' : ''; ?>
                                        <?= $group['checked'] ? 'checked' : ''; ?>
                                    />

                                    <svg
                                        role="presentation"
                                        focusable="false"
                                        class="
                                            checkbox__icon
                                            checkbox__icon--checked
                                        "
                                    >
                                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                                    </svg>

                                    <svg
                                        role="presentation"
                                        focusable="false"
                                        class="
                                            checkbox__icon
                                            checkbox__icon--unchecked
                                        "
                                    >
                                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
                                    </svg>

                                    <label
                                        for="<?= 'switch-box-' . $key ?>"
                                        class="
                                            label
                                            checkbox__label
                                        "
                                    >
                                        <?= $block->escapeHtml(__($group['name'] . ' Cookies')) ?>
                                    </label>
                                </div>
                                <p>
                                    <?= $block->escapeHtml($group['description']) ?>
                                </p>
                                <a
                                    href="<?= $block->escapeUrl($block->getUrl('cookie-settings')) ?>"
                                    class="link"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                <?= $block->escapeHtml(__('More information')) ?>
                                </a>
                            </div>
                        <?php endforeach; ?>
                        <p>
                            <?= /** @noEscape */ $cookiePrivacyText ?>
                        </p>
                    </div>

                    <div class="modal__bottom">
                        <div class="modal__bottom-actions">
                            <div class="modal__bottom-action">
                                <button
                                    class="button"
                                    data-amcookie-js="allow-all-cookies"
                                    type="button"
                                >
                                    <?= $block->escapeHtml(__('Allow all Cookies')); ?>
                                </button>
                            </div>
                            <div class="modal__bottom-action">
                                <button
                                    type="button"
                                    class="
                                        button
                                        button--secondary
                                    "
                                    data-amcookie-js="save-cookies"
                                >
                                    <?= $block->escapeHtml(__('Save')); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<?php elseif ($block->getNoticeType() === \Amasty\GdprCookie\Model\Config\Source\CookiePolicyBarStyle::CONFIRMATION && $cookiePrivacyText): ?>
    <div
        data-role="gdpr-cookie-container"
        class="amgdprcookie-bar-template display-none"
        data-bind="mageInit: {
            'cookieBar': {
                'isNotice': '<?= $block->escapeHtmlAttr($block->isNotice()) ?>',
                'settingsLink': '<?= $block->escapeUrl($block->getSettingsLink()) ?>',
                'websiteInteraction': '<?= $block->escapeHtmlAttr($block->getWebsiteInteraction()) ?>',
                'firstShowProcess': '<?= $block->escapeHtmlAttr($block->isProcessFirstShow()) ?>',
                'barLocation': '<?= $block->escapeHtmlAttr($block->getBarLocation()) ?>'
            }
        }"
    >
        <div
            role="alertdialog"
            tabindex="-1"
            class="
                cookie-message
                cookie-message--open
                cookie-message--actions
                amgdprcookie-bar-container
            "
            data-amcookie-js="bar"
        >
            <div
                role="document"
                class="cookie-message__container"
                tabindex="0"
            >
                <p
                    class="cookie-message__text"
                >
                    <?= /** @noEscape */ $cookiePrivacyText ?>
                </p>

                <div class="cookie-message__actions">
                    <div class="cookie-message__action">
                        <button
                            id="btn-cookie-allow"
                            class="
                                action
                                amgdprcookie-button
                                -allow
                                button
                                button--secondary
                                button--link
                                cookie-message__button
                            "
                            data-amcookie-js="allow-all-cookies"
                        >
                            <?= $block->escapeHtml(__('Allow Cookies')) ?>
                        </button>
                    </div>
                    <div class="cookie-message__action">
                        <a
                            href="<?= $block->escapeUrl($block->getSettingsLink()) ?>"
                            id="btn-cookie-disallow"
                            class="
                                action
                                amgdprcookie-button
                                -settings
                                button
                                button--secondary
                                button--link
                                cookie-message__button
                            "
                        >
                            <?= $block->escapeHtml(__('Cookies Settings')) ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .amgdprcookie-bar-template {
            z-index: 15;
            <?php if ((int) $block->getBarLocation()): ?>
                top: 0;
            <?php else: ?>
                bottom: 0;
            <?php endif; ?>
        }
    </style>
<?php endif; ?>
<?php if ($cookiePrivacyText): ?>
<style>
    .amgdprcookie-modal-template,
    .amgdprcookie-bar-container {
    <?php if ((int)$block->getBarLocation() === \Amasty\GdprCookie\Model\Config\Source\CookieBarLocation::DISPLAY_AT_FOOTER): ?>
        bottom: unset;
    <?php endif; ?>
        background-color: <?= $block->escapeHtml($block->getBackgroundBarCollor()); ?>;
    }
    .amgdprcookie-modal-template .amgdprcookie-policy,
    .amgdprcookie-bar-container .amgdprcookie-policy {
        color: <?= $block->escapeHtml($block->getTextBarCollor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-text,
    .amgdprcookie-bar-container .amgdprcookie-text {
        color: <?= $block->escapeHtml($block->getDescriptionTextBarColor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-header,
    .amgdprcookie-bar-container .amgdprcookie-header {
        color: <?= $block->escapeHtml($block->getHeaderTextBarColor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-link,
    .amgdprcookie-modal-template .amgdprcookie-policy a,
    .amgdprcookie-bar-container .amgdprcookie-policy a {
        color: <?= $block->escapeHtml($block->getLinksBarCollor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-button.-allow,
    .amgdprcookie-bar-container .amgdprcookie-button.-allow {
        background-color: <?= $block->escapeHtml($block->getButtonBarCollor()) ?>;
        border-color: <?= $block->escapeHtml($block->getButtonBarCollor()) ?>;
        color: <?= $block->escapeHtml($block->getButtonTextBarCollor()) ?>;
    }

    .amgdprcookie-bar-container .amgdprcookie-button.-settings {
        background-color: <?= $block->escapeHtml($block->getButtonSettingsColor()) ?>;
        border-color: <?= $block->escapeHtml($block->getButtonSettingsColor()) ?>;
        color: <?= $block->escapeHtml($block->getButtonSettingsTextColor()) ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-button.-save {
        background-color: <?= $block->escapeHtml($block->getButtonSaveColor()) ?>;
        border-color: <?= $block->escapeHtml($block->getButtonSaveColor()) ?>;
        color: <?= $block->escapeHtml($block->getButtonSaveTextColor()) ?>;
    }
</style>
<?php endif; ?>
