<?php
/** @var \Amasty\GdprCookie\Block\CookieBar $block */
/** @var \Amasty\GdprCookie\Block\widget\Settings $widget */

$confirmationModal = \Amasty\GdprCookie\Model\Config\Source\CookiePolicyBarStyle::CONFIRMATION_MODAL;
$confirmationPopup = \Amasty\GdprCookie\Model\Config\Source\CookiePolicyBarStyle::CONFIRMATION_POPUP;
$confirmationClassic = \Amasty\GdprCookie\Model\Config\Source\CookiePolicyBarStyle::CONFIRMATION;
$cookiePrivacyTextJson = $block->getNotificationText();
$cookiePrivacyText = json_decode($cookiePrivacyTextJson, true);
$widget = $this->getLayout()->createBlock('Amasty\GdprCookie\Block\widget\Settings');
$groupData = $widget->getGroupData()['groupData'];
?>

<!-- Don't display if in /cookie-settings -->
<?php if (!strpos($block->getRequest()->getRequestUri(), 'cookie-settings')): ?>
    <?php if ($block->getNoticeType() === $confirmationModal && $cookiePrivacyText): ?>
        <div class="modals-wrapper">
            <div
                data-role="gdpr-cookie-container"
                class="amgdprcookie-modal-template"
                data-amgdpr-js="gdpr-cookie-container"
            >
            <div class="amgdprcookie-modal-block" data-amgdpr-js="modal"></div>
                <div
                    data-bind="mageInit: {
                        'cookieModal': {
                            'isNotice': '<?= $widget->isNeedToShow() ?>'
                        }
                    }"
                    role="dialog"
                    aria-hidden="true"
                    id="cookie-modal"
                    data-modal="cookie-modal"
                    class="modal"
                >
                    <div class="modal__container modal__cookies-container">
                        <form
                            id="amgdprcookie-form"
                            class="amgdprcookie-settings-form"
                            data-amcookie-js="form-cookie"
                            data-modal="cookie-modal"
                        >
                            <button
                                class="
                                    button
                                    button--icon
                                    button--rotate-icon
                                    modal__close-button
                                "
                                type="button"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Close modal')) ?>"
                            >
                                <svg
                                    class="
                                        icon
                                        button__icon
                                        modal__close-button-icon
                                    "
                                    role="presentation"
                                    focusable="false"
                                >
                                    <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#close')); ?>"></use>
                                </svg>
                            </button>
                            <div
                                data-amcookie-js="groups"
                                class="margin-bottom-xl modal__content"
                            >
                                <?php foreach ($groupData as $key => $group): ?>
                                    <div class="margin-bottom-l">
                                        <h2>
                                            <?= $block->escapeHtml(__($group['name'])) ?>
                                        </h2>
                                        <div
                                            class="
                                                field
                                                choice
                                                checkbox
                                            "
                                        >
                                            <input
                                                id="<?= 'switch-box-' . $key ?>"
                                                class="checkbox__field <?= $group['isEssential'] ? 'checkbox__field--disabled' : ''; ?>"
                                                type="checkbox"
                                                data-amcookie-js="field"
                                                name="groups[]"
                                                value="<?= /** @noEscape */ (int) $group['groupId'] ?>"
                                                <?= $group['isEssential'] ? 'disabled' : ''; ?>
                                                <?= $group['checked'] ? 'checked' : ''; ?>
                                            />

                                            <svg
                                                role="presentation"
                                                focusable="false"
                                                class="
                                                    checkbox__icon
                                                    checkbox__icon--checked
                                                "
                                            >
                                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                                            </svg>

                                            <svg
                                                role="presentation"
                                                focusable="false"
                                                class="
                                                    checkbox__icon
                                                    checkbox__icon--unchecked
                                                "
                                            >
                                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
                                            </svg>

                                            <label
                                                for="<?= 'switch-box-' . $key ?>"
                                                class="
                                                    label
                                                    checkbox__label
                                                "
                                            >
                                                <?= $block->escapeHtml(__($group['name'] . ' Cookies')) ?>
                                            </label>
                                        </div>
                                        <p class="margin-bottom-m">
                                            <?= $block->escapeHtml($group['description']) ?>
                                        </p>
                                        <a
                                            href="<?= $block->escapeUrl($block->getUrl('cookie-settings')) ?>"
                                            class="link"
                                            target="_blank"
                                            rel="noopener noreferrer"
                                        >
                                        <?= $block->escapeHtml(__('More information')) ?>
                                        </a>
                                    </div>
                                <?php endforeach; ?>
                                <p>
                                    <?= /** @noEscape */ $cookiePrivacyText ?>
                                </p>
                            </div>

                            <div class="modal__bottom">
                                <div class="modal__bottom-actions">
                                    <div class="modal__bottom-action">
                                        <button
                                            class="button"
                                            data-amcookie-js="allow-all-cookies"
                                            type="button"
                                        >
                                            <!-- $block->getSettingsButtonName() in admin panel is Allow all Cookies - Amasty module bug -->
                                            <?php if($block->escapeHtmlAttr($block->getSettingsButtonName())): ?>
                                                <?= $block->escapeHtmlAttr($block->getSettingsButtonName()) ?>
                                            <?php else: ?>
                                                <?= $block->escapeHtml(__('Allow all Cookies')); ?>
                                            <?php endif; ?>
                                        </button>
                                    </div>
                                    <div class="modal__bottom-action">
                                        <button
                                            type="button"
                                            class="
                                                button
                                                button--secondary
                                            "
                                            data-amcookie-js="save-cookies"
                                        >
                                            <?php if($block->escapeHtmlAttr($block->getAcceptButtonName())): ?>
                                                <?= $block->escapeHtmlAttr($block->getAcceptButtonName()) ?>
                                            <?php else: ?>
                                                <?= $block->escapeHtml(__('Save')); ?>
                                            <?php endif; ?>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <?php elseif (($block->getNoticeType() === $confirmationClassic ||
        $block->getNoticeType() === $confirmationPopup) && $cookiePrivacyText): ?>
        <div
            data-role="gdpr-cookie-container"
            class="amgdprcookie-bar-template display-none"
            data-bind="mageInit: {
                'cookieBar': {
                    'isNotice': '<?= $widget->isNeedToShow() ?>',
                    'barLocation': '<?= $block->escapeHtmlAttr($block->getBarLocation()) ?>'
                }
            }"
        >
            <div
                role="alertdialog"
                tabindex="-1"
                class="
                    cookie-message
                    cookie-message--open
                    cookie-message--actions
                    amgdprcookie-bar-container
                "
                data-amcookie-js="bar"
            >
                <div
                    role="document"
                    class="cookie-message__container"
                    tabindex="0"
                >
                    <p
                        class="cookie-message__text"
                    >
                        <?= /** @noEscape */ $cookiePrivacyText ?>
                    </p>

                    <div class="cookie-message__actions">
                        <div class="cookie-message__action">
                            <button
                                id="btn-cookie-allow"
                                class="
                                    action
                                    amgdprcookie-button
                                    -allow
                                    button
                                    button--secondary
                                    button--link
                                    cookie-message__button
                                "
                                data-amcookie-js="allow-all-cookies"
                            >
                                <?php if($block->escapeHtmlAttr($block->getAcceptButtonName())): ?>
                                    <?= $block->escapeHtmlAttr($block->getAcceptButtonName()) ?>
                                <?php else: ?>
                                    <?= $block->escapeHtml(__('Allow all Cookies')); ?>
                                <?php endif; ?>
                            </button>
                        </div>
                        <div class="cookie-message__action">
                            <a
                                href="<?= $block->escapeUrl($block->getUrl('cookie-settings')) ?>"
                                id="btn-cookie-disallow"
                                class="
                                    action
                                    amgdprcookie-button
                                    -settings
                                    button
                                    button--secondary
                                    button--link
                                    cookie-message__button
                                "
                            >
                                <?= $block->escapeHtml(__('Cookies Settings')) ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <style>
            .amgdprcookie-bar-template {
                z-index: 15;
                <?php if ((int) $block->getBarLocation()): ?>
                    top: 0;
                <?php else: ?>
                    bottom: 0;
                <?php endif; ?>
            }
        </style>
    <?php endif; ?>
    <?php if ($cookiePrivacyText): ?>
        <style>
            .amgdprcookie-modal-template,
            .amgdprcookie-bar-container {
            <?php if ((int)$block->getBarLocation() === \Amasty\GdprCookie\Model\Config\Source\CookieBarLocation::DISPLAY_AT_FOOTER): ?>
                bottom: unset;
            <?php endif; ?>
                background-color: <?= $escaper->escapeHtml($block->getBackgroundColor()); ?>;
            }
            .amgdprcookie-modal-template .amgdprcookie-policy,
            .amgdprcookie-bar-container .amgdprcookie-policy {
                color: <?= $escaper->escapeHtml($block->getPolicyTextColor()); ?>;
            }

            .amgdprcookie-modal-template .amgdprcookie-text,
            .amgdprcookie-bar-container .amgdprcookie-text {
                color: <?= $escaper->escapeHtml($block->getDescriptionTextColor()); ?>;
            }

            .amgdprcookie-modal-template .amgdprcookie-header,
            .amgdprcookie-bar-container .amgdprcookie-header {
                color: <?= $escaper->escapeHtml($block->getTitleTextColor()); ?>;
            }

            .amgdprcookie-modal-template .amgdprcookie-link,
            .amgdprcookie-modal-template .amgdprcookie-policy a,
            .amgdprcookie-bar-container .amgdprcookie-policy a {
                color: <?= $escaper->escapeHtml($block->getLinksColor()); ?>;
            }

            .amgdprcookie-modal-template .amgdprcookie-button.-save,
            .amgdprcookie-bar-container .amgdprcookie-button.-allow {
                background-color: <?= $escaper->escapeHtml($block->getAcceptButtonColor()) ?>;
                border-color: <?= $escaper->escapeHtml($block->getAcceptButtonColor()) ?>;
                color: <?= $escaper->escapeHtml($block->getAcceptTextColor()) ?>;
            }

            .amgdprcookie-modal-template .amgdprcookie-button.-save:hover,
            .amgdprcookie-bar-container .amgdprcookie-button.-allow:hover {
                background-color: <?= $escaper->escapeHtml($block->getAcceptButtonColorHover()) ?>;
                border-color: <?= $escaper->escapeHtml($block->getAcceptButtonColorHover()) ?>;
                color: <?= $escaper->escapeHtml($block->getAcceptTextColorHover()) ?>;
            }

            .amgdprcookie-modal-template .amgdprcookie-button.-allow,
            .amgdprcookie-bar-container .amgdprcookie-button.-settings {
                background-color: <?= $escaper->escapeHtml($block->getSettingsButtonColor()) ?>;
                border-color: <?= $escaper->escapeHtml($block->getSettingsButtonColor()) ?>;
                color: <?= $escaper->escapeHtml($block->getSettingsTextColor()) ?>;
            }

            .amgdprcookie-modal-template .amgdprcookie-button.-allow:hover,
            .amgdprcookie-bar-container .amgdprcookie-button.-settings:hover {
                background-color: <?= $escaper->escapeHtml($block->getSettingsButtonColorHover()) ?>;
                border-color: <?= $escaper->escapeHtml($block->getSettingsButtonColorHover()) ?>;
                color: <?= $escaper->escapeHtml($block->getSettingsTextColorHover()) ?>;
            }

            .amgdprcookie-modal-template .amgdprcookie-button.-decline,
            .amgdprcookie-bar-container .amgdprcookie-button.-decline {
                background-color: <?= $escaper->escapeHtml($block->getDeclineButtonColor()) ?>;
                border-color: <?= $escaper->escapeHtml($block->getDeclineButtonColor()) ?>;
                color: <?= $escaper->escapeHtml($block->getDeclineTextColor()) ?>;
            }

            .amgdprcookie-modal-template .amgdprcookie-button.-decline:hover,
            .amgdprcookie-bar-container .amgdprcookie-button.-decline:hover {
                background-color: <?= $escaper->escapeHtml($block->getDeclineButtonColorHover()) ?>;
                border-color: <?= $escaper->escapeHtml($block->getDeclineButtonColorHover()) ?>;
                color: <?= $escaper->escapeHtml($block->getDeclineTextColorHover()) ?>;
            }
        </style>
    <?php endif; ?>
<?php endif ?>