<?php
/** @var \Amasty\GdprCookie\Block\CookieBar $block */

$cookiePrivacyText = /** @noEscape */ $block->getCookiePolicyText();
$groupsJson = $block->getAllGroups();
$groups = json_decode($groupsJson, true);
?>
<?php if ($block->getNoticeType() === \Amasty\GdprCookie\Model\Config\Source\CookiePolicyBarStyle::CONFIRMATION_MODAL && $cookiePrivacyText && $groups): ?>

    <div data-role="gdpr-cookie-container" class="amgdprcookie-modal-template" data-amgdpr-js="modal">
        <div data-bind="mageInit: {'cookieModal': {}}" role="dialog" aria-hidden="true" id="cookie-modal" data-modal="cookie-modal" class="modal " aria-labelledby="myTitle" aria-describedby="myDesc">
            <div class="modal__container">
                <form
                    id="amgdprcookie-form"
                    class="amgdprcookie-settings-form"
                    data-amcookie-js="form-cookie"
                    data-modal="cookie-modal"
                >
                    <div
                        data-amcookie-js="groups"
                        class="margin-bottom-xl modal__content"
                    >
                        <?php foreach ($groups as $key => $group): ?>
                            <div class="margin-bottom-l">
                                <h2>
                                    <?= $block->escapeHtml(__($group['name'])) ?>
                                </h2>
                                <div
                                    class="
                                        field
                                        choice
                                        checkbox
                                    "
                                >
                                    <input
                                        id="<?= 'switch-box-' . $key ?>"
                                        class="checkbox__field <?= $group['isEssential'] ? 'checkbox__field--disabled' : ''; ?>"
                                        type="checkbox"
                                        data-amcookie-js="field"
                                        name="groups[]"
                                        value="<?= /** @noEscape */ (int) $group['groupId'] ?>"
                                        <?= $group['isEssential'] ? 'disabled' : ''; ?>
                                        <?= $group['isEssential'] ? 'onclick="return false;"' : ''; ?>
                                        <?= $group['checked'] ? 'checked' : ''; ?>
                                    />

                                    <svg
                                        role="presentation"
                                        focusable="false"
                                        class="
                                            checkbox__icon
                                            checkbox__icon--checked
                                        "
                                    >
                                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                                    </svg>

                                    <svg
                                        role="presentation"
                                        focusable="false"
                                        class="
                                            checkbox__icon
                                            checkbox__icon--unchecked
                                        "
                                    >
                                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
                                    </svg>

                                    <label
                                        for="<?= 'switch-box-' . $key ?>"
                                        class="
                                            label
                                            checkbox__label
                                        "
                                    >
                                        <?= $block->escapeHtml(__($group['name'] . ' Cookies')) ?>
                                    </label>
                                </div>
                                <p>
                                    <?= $block->escapeHtml($group['description']) ?>
                                </p>
                                <a
                                    href="<?= $block->escapeUrl($block->getUrl('cookie-settings')) ?>"
                                    class="link"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                <?= $block->escapeHtml(__('More information')) ?>
                                </a>
                            </div>
                        <?php endforeach; ?>
                        <p>
                            <?= /** @noEscape */ $cookiePrivacyText ?>
                        </p>
                    </div>

                    <div class="modal__bottom">
                        <div class="modal__bottom-actions">
                            <div class="modal__bottom-action">
                                <button
                                    class="button"
                                    data-amcookie-js="settings-allow"
                                >
                                    <?= $block->escapeHtml(__('Allow all Cookies')); ?>
                                </button>
                            </div>
                            <div class="modal__bottom-action">
                                <button
                                    class="
                                        button
                                        button--secondary
                                    "
                                    data-amcookie-js="settings-save"
                                >
                                    <?= $block->escapeHtml(__('Save')); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="amgdprcookie-modal-block" data-amgdpr-js="modal"></div>
    <script type="text/x-magento-init">
        {"*": {
                "Amasty_GdprCookie/js/settings": {}
            }
        }
    </script>
    <!-- <script type="text/x-magento-init">
    {
        "[data-role=gdpr-cookie-container]": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "gdpr-cookie-modal": {
                        "component": "Amasty_GdprCookie/js/modal",
                        "isNotice": <?= $block->escapeHtmlAttr($block->isNotice()) ?>,
                        "groups": <?= /* @noEscape */ $groupsJson ?>,
                        "cookieText": <?= /** @noEscape */ $cookiePrivacyText ?>,
                       "settingsLink": "<?= $block->escapeUrl($block->getSettingsLink()) ?>",
                       "websiteInteraction": "<?= $block->escapeHtmlAttr($block->getWebsiteInteraction()) ?>",
                        "firstShowProcess": "<?= $block->escapeHtmlAttr($block->isProcessFirstShow()) ?>"
                    }
                }
            }
        }
    }
    </script> -->
<?php elseif ($block->getNoticeType() === \Amasty\GdprCookie\Model\Config\Source\CookiePolicyBarStyle::CONFIRMATION && $cookiePrivacyText): ?>
    <!-- ko scope: 'gdpr-cookie-container' -->
    <div data-role="gdpr-cookie-container" class="amgdprcookie-bar-template" data-bind="css: {'-bottom' : isScrollBottom}">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <!-- /ko -->
    <script type="text/x-magento-init">
    {
        "[data-role=gdpr-cookie-container]": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "gdpr-cookie-container": {
                        "component": "Amasty_GdprCookie/js/cookies",
                        "noticeType": <?= $block->escapeHtmlAttr($block->getNoticeType()) ?>,
                        "isNotice": <?= $block->escapeHtmlAttr($block->isNotice()) ?>,
                        "policyText": <?= /** @noEscape */ $cookiePrivacyText ?>,
                        "allowLink": "<?= $block->escapeUrl($block->getAllowLink()) ?>",
                        "settingsLink": "<?= $block->escapeUrl($block->getSettingsLink()) ?>",
                        "websiteInteraction": "<?= $block->escapeHtmlAttr($block->getWebsiteInteraction()) ?>",
                        "firstShowProcess": "<?= $block->escapeHtmlAttr($block->isProcessFirstShow()) ?>",
                        "barLocation": "<?= $block->escapeHtmlAttr($block->getBarLocation()) ?>",
                        "groups": <?= /* @noEscape */ $groups ?>
                    }
                }
            }
        }
    }
    </script>
    <style>
        .amgdprcookie-bar-template {
                z-index: 15;
            <?php if ((int)$block->getBarLocation()): ?>
                top: 0;
            <?php else: ?>
                bottom: 0;
            <?php endif; ?>
        }
    </style>
<?php endif; ?>
<?php if ($cookiePrivacyText): ?>
<style>
    .amgdprcookie-modal-template,
    .amgdprcookie-bar-container {
    <?php if ((int)$block->getBarLocation() === \Amasty\GdprCookie\Model\Config\Source\CookieBarLocation::DISPLAY_AT_FOOTER): ?>
        bottom: unset;
    <?php endif; ?>
        background-color: <?= $block->escapeHtml($block->getBackgroundBarCollor()); ?>;
    }
    .amgdprcookie-modal-template .amgdprcookie-policy,
    .amgdprcookie-bar-container .amgdprcookie-policy {
        color: <?= $block->escapeHtml($block->getTextBarCollor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-text,
    .amgdprcookie-bar-container .amgdprcookie-text {
        color: <?= $block->escapeHtml($block->getDescriptionTextBarColor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-header,
    .amgdprcookie-bar-container .amgdprcookie-header {
        color: <?= $block->escapeHtml($block->getHeaderTextBarColor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-link,
    .amgdprcookie-modal-template .amgdprcookie-policy a,
    .amgdprcookie-bar-container .amgdprcookie-policy a {
        color: <?= $block->escapeHtml($block->getLinksBarCollor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-button.-allow,
    .amgdprcookie-bar-container .amgdprcookie-button.-allow {
        background-color: <?= $block->escapeHtml($block->getButtonBarCollor()) ?>;
        border-color: <?= $block->escapeHtml($block->getButtonBarCollor()) ?>;
        color: <?= $block->escapeHtml($block->getButtonTextBarCollor()) ?>;
    }

    .amgdprcookie-bar-container .amgdprcookie-button.-settings {
        background-color: <?= $block->escapeHtml($block->getButtonSettingsColor()) ?>;
        border-color: <?= $block->escapeHtml($block->getButtonSettingsColor()) ?>;
        color: <?= $block->escapeHtml($block->getButtonSettingsTextColor()) ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-button.-save {
        background-color: <?= $block->escapeHtml($block->getButtonSaveColor()) ?>;
        border-color: <?= $block->escapeHtml($block->getButtonSaveColor()) ?>;
        color: <?= $block->escapeHtml($block->getButtonSaveTextColor()) ?>;
    }
</style>
<?php endif; ?>
