<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<select
    id="<?= $block->escapeHtmlAttr($block->getSelectRegionId()) ?>"
    name="<?= $block->escapeHtmlAttr($block->getSelectRegionName()) ?>"
    title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
    class="select__field <?= $block->escapeHtmlAttr($block->getSelectRegionClass()) ?>" <?= /* @noEscape */ $block->getSelectRegionParams() ?>
    data-mage-init='{ "select": {}}'
>
    <option value=""><?= $block->escapeHtml($block->getSelectRegionDefault()) ?></option>
</select>
