<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<input type="text"
       class="input__field <?= $block->escapeHtmlAttr($block->getInputClass()) ?> "
       name="<?= $block->escapeHtmlAttr($block->getInputName()) ?>"
       id="<?= $block->escapeHtmlAttr($block->getInputId()) ?>"
       value="<?= $block->escapeHtmlAttr($block->getInputValue()) ?>"  <?= /* @noEscape */ $block->getInputParams() ?>
/>
