<?php
/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 * @var $shippingLatencyHelper \Snowdog\ShippingLatency\Helper\Data
 */
?>
<?php
$block->setPreconfiguredValue();
$_product = $block->getProduct();
$_associatedProducts = $block->getAssociatedProducts();
$_hasAssociatedProducts = count($_associatedProducts) > 0;
$shippingLatencyHelper = $this->helper('Snowdog\ShippingLatency\Helper\Data');
?>
<table
    class="table product-view__grouped-table"
    id="super-product-table"
    tabindex="0"
    role="table"
    data-mage-init='{ "Magento_GroupedProduct/js/product-ids-resolver": {} }'
>
    <caption class="table__caption">
        <?= $block->escapeHtml(__('Grouped product items')) ?>
    </caption>
    <thead>
    <tr role="row">
        <th
            class="product-view__grouped-product-name-th"
            scope="col"
            role="columnheader"
        >
            <?= $block->escapeHtml(__('Product Name')) ?>
        </th>
        <?php if ($_product->isSaleable()) : ?>
            <th
                role="columnheader"
                scope="col"
            >
                <?= $block->escapeHtml(__('Qty')) ?>
            </th>
        <?php endif; ?>
    </tr>
    </thead>

    <?php if ($_hasAssociatedProducts) : ?>
        <tbody>
        <?php foreach ($_associatedProducts as $_item) : ?>
            <tr role="row">
                <td
                    class="product-view__grouped-product-name-cell"
                    data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>"
                    role="gridcell"
                >
                        <span class="product-view__grouped-product-name">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </span>
                    <?php if ($block->getCanShowProductPrice($_product)) : ?>
                        <?php if ($block->getCanShowProductPrice($_item)) : ?>
                            <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
                <?php if ($_product->isSaleable()) : ?>
                    <td
                        data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                        class="product-view__grouped-product-qty-td"
                        role="gridcell"
                    >
                        <?php if ($_item->isSaleable()) : ?>
                            <div class="input product-view__grouped-qty">
                                <label
                                    class="
                                        label
                                        input__label
                                        label--hidden
                                    "
                                    for="id_super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                                >
                                    <?= $block->escapeHtml(__('Qty')) ?>
                                </label>
                                <input
                                    type="number"
                                    id="id_super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                                    name="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                                    data-selector="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                                    value="<?= $block->escapeHtmlAttr($_item->getQty() * 1) ?>"
                                    title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                    class="input__field qty"
                                    data-validate="{'validate-grouped-qty':'#super-product-table'}"
                                    data-errors-message-box="#validation-message-box"
                                />
                            </div>
                        <?php else : ?>
                            <div
                                class="stock unavailable"
                                title="<?= $block->escapeHtmlAttr(__('Availability')) ?>"
                            >
                                <span>
                                    <?= $block->escapeHtml(__('Out of stock')) ?>
                                </span>
                            </div>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>
            </tr>
            <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))) : ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    <?php else: ?>
        <?php
            $shippingLatencyText = $_product->getAttributeText('shipping_latency');
            $isShownInStock = $shippingLatencyHelper->isShippingLatencyAllowed($_product);
        ?>
        <?php if ($isShownInStock || $shippingLatencyText): ?>
            <div class="shipping_latency">
                <button
                    class="
                                                button
                                                button--link
                                                modal-trigger
                                                product-view__stock
                                            "
                    type="button"
                    aria-expanded="false"
                    data-modal-trigger="shipping-latency-popup"
                    data-mage-init='{ "modal" : {} }'
                >
                    <?php if ($isShownInStock): ?>
                        <?= $block->escapeHtml(__('In stock')) ?>
                    <?php elseif ($shippingLatencyText->getText() !== 'None'): ?>
                        <?= $block->escapeHtml($shippingLatencyText); ?>
                    <?php endif; ?>
                </button>
                <div
                    id="shipping-latency-popup-<?= $_product->getId(); ?>"
                    role="dialog"
                    aria-hidden="true"
                    data-modal="shipping-latency-popup"
                    aria-labelledby="shipping-latency-title"
                    class="modal"
                >
                    <div
                        class="modal__container"
                        role="document"
                        tabindex="0"
                    >
                        <div class="modal__content">
                            <?php if ($isShownInStock): ?>
                                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('one-day-shipping')->toHtml(); ?>
                            <?php else: ?>
                                <h3 id="shipping-latency-title">
                                    <?= $block->escapeHtml($shippingLatencyText); ?>
                                </h3>
                                <?= $shippingLatencyHelper->getProductPopupHtml($_product->getData()); ?>
                            <?php endif ?>
                        </div>
                        <button
                            class="
                                                        button
                                                        button--icon
                                                        button--rotate-icon
                                                        modal__close-button
                                                    "
                            type="button"
                            aria-label="<?= $block->escapeHtmlAttr(__('Close modal')) ?>"
                        >
                            <svg
                                class="
                                                            icon
                                                            button__icon
                                                            modal__close-button-icon
                                                        "
                                role="presentation"
                                focusable="false"
                            >
                                <title><?= __('Close') ?></title>
                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#close')); ?>"></use>
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <tbody>
                <tr role="row">
                    <td
                        class="unavailable"
                        colspan="<?php if ($_product->isSaleable()) : ?>4<?php else : ?>3<?php endif; ?>"
                        role="gridcell"
                    >
                        <?= $block->escapeHtml(__('No options of this product are available.')) ?>
                    </td>
                </tr>
            </tbody>
        <?php endif; ?>
    <?php endif; ?>
</table>
<div id="validation-message-box"></div>
