<?php

/**
 * @see \Blackbird\ContentManager\Block\ContentList
 * @var \Blackbird\ContentManager\Block\ContentList $block
 */
?>

<?php
$collection = $block->getCollection();
$sliderClassName = $block->getSliderClass();
$sliderWrapperClass = $block->getWrapperClass();
$sliderTitleClassName = $block->getSliderTitleClass();

$sliderPictureBlock = $this->getLayout()
    ->createBlock("Magento\Framework\View\Element\Template")
    ->setTemplate("Magento_Theme::html/picture.phtml");
$sliderBlockBefore = $this->getLayout()
    ->createBlock("Magento\Framework\View\Element\Template")
    ->setTemplate("Magento_Theme::html/slider.phtml");
$sliderBlockAfter = $this->getLayout()
    ->createBlock("Magento\Framework\View\Element\Template")
    ->setTemplate("Magento_Theme::html/slider.phtml");

$picturePrefix = $this->getPicturePrefix();
$sliderPrefix = $this->getSliderPrefix();
$wrapperClass = $this->getWrapperClass();

// banners attrubutes to show
$sliderPrefix = $sliderPrefix ? $sliderPrefix : 'cb_slider_';
$picturePrefix = $picturePrefix ? $picturePrefix : 'cb_pic_';
$pictureData = [
    'title',
    'alt',
    'url',
    'url_target',
    'main_image',
    'order'
];
$pictureFiles = [
    'default',
    'max_480',
    'max_480_2x',
    'max_768',
    'max_768_2x',
    'max_1024',
    'max_1024_2x',
    'max_1328',
    'max_1328_2x',
    'full',
    'full_2x'
];

$bannersAttributes = '*';
$bannersArray = [];
$sliderItemClass = 'slider__item';
?>

<?php foreach ($collection as $content) : ?>
    <?php
    //slider config
    $sliderInfinite = $content->getData($sliderPrefix . 'infinite');
    $sliderCenterMode = $content->getData($sliderPrefix . 'center');
    $sliderDots = $content->getData($sliderPrefix . 'dots');
    $sliderArrows = ($content->getData($sliderPrefix . 'arrows') === 'no') ? false : true;
    $sliderAutoplay = $content->getData($sliderPrefix . 'autoplay');
    $sliderAutoplaySpeed = $content->getData($sliderPrefix . 'speed');
    $sliderPauseOnFocus = $content->getData($sliderPrefix . 'focus');
    $sliderPauseOnHover = $content->getData($sliderPrefix . 'hover');
    $sliderSlidesToShow = $content->getData($sliderPrefix . 'slidestoshow');
    $sliderSlidesToScroll = $content->getData($sliderPrefix . 'slidestoscroll');
    $sliderResponsiveConfig = $content->getData($sliderPrefix . 'responsive_cfg');

    $sliderTitle = $block->escapeHtml($content->getData($sliderPrefix . 'title'));
    $sliderDisplayTitle = $block->escapeHtml($content->getData($sliderPrefix . 'display_title'));
    $sliderDisplayTitle = ($sliderDisplayTitle === 'no') ? false : true;
    $sliderContentBefore =
        $content->getData($sliderPrefix . 'ct_before') ?
            $content->render($sliderPrefix . 'ct_before') :
            false;
    $sliderContentAfter =
        $content->getData($sliderPrefix . 'ct_after') ?
            $content->render($sliderPrefix . 'ct_after') :
            false;

    $sliderBanners = $content->getContentCollection($sliderPrefix . 'banners', $bannersAttributes);

    foreach ($sliderBanners as $index => $banner) {
        foreach ($pictureData as $pictureDataAttr) {
            $bannersArray[$index][$pictureDataAttr] = $banner->getData($picturePrefix . $pictureDataAttr);
        }

        foreach ($pictureFiles as $pictureFile) {
            $bannersArray[$index][$pictureFile] =
                $banner->getData($picturePrefix . $pictureFile) ? $banner->getFile($picturePrefix . $pictureFile) : false;
        }
    }

    // sorting banners collection by order
    usort($bannersArray, function ($a, $b) {
        return $a['order'] - $b['order'];
    });
    ?>

    <?php
    $sliderBlockBefore->setData([
        'slider_html'       => 'before-slides',
        'slider_class'      => $sliderClassName,
        'wrapper_class'     => $sliderWrapperClass,
        'display_title'     => $sliderDisplayTitle,
        'slider_title'      => $sliderTitle,
        'title_class'       => $sliderTitleClassName,
        'content_before'    => $sliderContentBefore,
        'infinite'          => $sliderInfinite,
        'center_mode'       => $sliderCenterMode,
        'dots'              => $sliderDots,
        'arrows'            => $sliderArrows,
        'autoplay'          => $sliderAutoplay,
        'autoplay_speed'    => $sliderAutoplaySpeed,
        'pause_on_focus'    => $sliderPauseOnFocus,
        'pause_on_hover'    => $sliderPauseOnHover,
        'slides_to_show'    => $sliderSlidesToShow,
        'slides_to_scroll'  => $sliderSlidesToScroll,
        'responsive_config' => $sliderResponsiveConfig
    ]);
    ?>
    <?= $sliderBlockBefore->toHtml(); ?>

    <?php if ($bannersArray): ?>
        <?php foreach ($bannersArray as $banner): ?>
            <?php
            $escapedBannerUrl = $block->escapeUrl($banner['url']);
            $bannerUrlTarget = ($banner['url_target'] == '_blank') ? '_blank' : '_self';

            $sliderPictureBlock->setData([
                'picture_class' => 'banner__image',
                'picture_full_url' => true,
                'img_default' => $banner['default'],
                'img_480' => $banner['max_480'],
                'img_768' => $banner['max_768'],
                'img_1024' => $banner['max_1024'],
                'img_1328' => $banner['max_1328'],
                'img_full' => $banner['full'],
                'img_4802x' => $banner['max_480_2x'],
                'img_7682x' => $banner['max_768_2x'],
                'img_10242x' => $banner['max_1024_2x'],
                'img_13282x' => $banner['max_1328_2x'],
                'img_full_2x' => $banner['full_2x'],
                'picture_alt' => $banner['alt']
            ]);
            ?>
            <div class="<?= $block->escapeHtmlAttr($sliderItemClass) ?>">
                <<?= $escapedBannerUrl ? 'a href="' . $escapedBannerUrl . '" target="' . $bannerUrlTarget . '"' : 'div'; ?>
                class="banner"
                >
                    <?= $sliderPictureBlock->toHtml(); ?>
                </<?= $escapedBannerUrl ? 'a' : 'div'; ?>>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php
    $sliderBlockAfter->setData([
        'slider_html'   => 'after-slides',
        'wrapper_class' => $sliderWrapperClass,
        'content_after' => $sliderContentAfter
    ]);
    ?>

    <?= $sliderBlockAfter->toHtml(); ?>
<?php endforeach; ?>
