<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Company\Block\Company\CompanyInfo
 */
?>
<fieldset class="fieldset company">
    <div class="field">
        <label class="label" for="company"><span>
            <?= $block->escapeHtml(__('Company')) ?></span>
        </label>
        <div class="control">
            <input type="text" class="input-text readonly" name="company"
                   value="<?= $block->escapeHtmlAttr($block->getCompanyName()) ?>" readonly="readonly"/>
        </div>
    </div>
</fieldset>
<fieldset class="fieldset job_title">
    <div class="field">
        <label class="label" for="job_title"><span>
            <?= $block->escapeHtml(__('Job Title')) ?></span></label>
        <div class="control">
            <input type="text" class="input-text" name="customer[extension_attributes][company_attributes][job_title]"
                   value="<?= $block->escapeHtmlAttr($block->getJobTitle()) ?>"/>
        </div>
    </div>
</fieldset>
