<?php
/**
 * @var $block \Magento\Company\Block\Company\CompanyInfo
 */
?>
<fieldset class="fieldset company">
    <div class="input">
        <label
            class="label"
            for="company"
        >
            <?= $block->escapeHtml(__('Company')) ?>
        </label>
        <input
            type="text"
            class="input__field readonly"
            name="company"
            id="company"
            value="<?= $block->escapeHtmlAttr($block->getCompanyName()) ?>"
            readonly="readonly"
        />
    </div>
    <div class="input">
        <label
            class="label"
            for="job_title"
        >
            <?= $block->escapeHtml(__('Job Title')) ?>
        </label>
        <input
            type="text"
            id="job_title"
            class="input__field"
            name="customer[extension_attributes][company_attributes][job_title]"
            value="<?= $block->escapeHtmlAttr($block->getJobTitle()) ?>"
        />
    </div>
</fieldset>
