<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) :?>
    <a
        href="<?= $block->escapeUrl($block->getPrintUrl()) ?>"
        target="_blank"
        class="
            print
            button
            button--secondary
            link--button
        "
    >
        <?= $block->escapeHtml(__('Print receipt')) ?>
    </a>
    <?= $block->getChildHtml() ?>
<?php endif;?>
