<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div
        id="checkout-loader"
        data-role="checkout-loader"
        class="loader-mask"
        data-mage-init='{"checkoutLoader": {}}'
    >
        <div
            class="loader loader--visible"
            aria-live="polite"
            aria-label="<?= $block->escapeHtml(__('Do not refresh the page')) ?>"
        >
            <div class="loader__icon"></div>
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= $block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))) ?>");
            return url.setBaseUrl('<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl())) ?>');
        })
    </script>
</div>
