<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="success-page__order-confirmation">
    <?php if ($block->getOrderId()): ?>
        <p>
            <?php if ($block->getCanViewOrder()): ?>
                <?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?>
            <?php else: ?>
                <?= $block->escapeHtml(__('Your order # is: <strong>%1</strong>.', $block->getOrderId()), ['strong']) ?>
            <?php endif;?>

            <br />

            <?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?>
        </p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <a
        class="
            button
            link--button
            success-page__button
        "
        href="<?= $block->escapeUrl($block->getContinueUrl()) ?>"
    >
        <?= $block->escapeHtml(__('Continue Shopping')) ?>
    </a>
</div>
