<div class="catalog-list">
  <div class="catalog-list__sidebar">
    <?= $this->getChildHtml('solr.filters') ?>
    <?= $this->getChildHtml('solr.navigation') ?>
  </div>
  <div class="catalog-list__products">
    <?= $this->getChildHtml('solr.toolbar') ?>
    <?= $this->getChildHtml('solr.category.products') ?>
    <?= $this->getChildHtml('solr.category.products.grid') ?>
    <?= $this->getChildHtml('solr.pager') ?>
  </div>
</div>
