<?php
/** @var \Snowdog\SolrNavigation\Block\Filters $block */
$filters = $block->getFilterBlocks();
?>
<button
    class="button button--secondary filters__skip-button"
    type="button"
    data-mage-init='{"skipFilters": {}}'
>
    <?= $block->escapeHtml(__('Skip to products')) ?>
</button>
<?php if (!empty($filters)): ?>
    <h2 class="filters__heading">
        <?= $block->escapeHtml(__('Now Shopping by')) ?>
    </h2>
    <div class="divider filters__divider"></div>
    <div class="filters__active">
        <ul class="active-filters list">
            <?php foreach ($filters as $filterBlock): ?>
                <?= /* @noEscape */ $filterBlock->toHtml() ?>
            <?php endforeach; ?>
            <a
                href="<?= $block->escapeUrl($block->getCleanUrl()) ?>"
                class="active-filters__clear-all"
                title="<?= $block->escapeHtmlAttr(__('Clear all filters')) ?>"
            >
                <?= $block->escapeHtml(__('Clear All')) ?>
            </a>
        </ul>
    </div>
<?php endif; ?>
