<?php
/** @var \Snowdog\SolrNavigation\Block\Filters $block */
$filters = $block->getFilterBlocks();
?>
<button
    class="button button button--secondary filters__skip-button"
    type="button"
    data-mage-init='{"skipFilters": {}}'
>
    <?= __('Skip to products') ?>
</button>
<?php if (!empty($filters)): ?>
    <h2 class="filters__heading">
        <?= __('Now Shopping by') ?>
    </h2>
    <div class="divider filters__divider"></div>
    <div class="filters__active">
        <ul class="active-filters list">
            <?php foreach ($filters as $filterBlock): ?>
                <?= $filterBlock->toHtml() ?>
            <?php endforeach; ?>
            <a
                href="<?= $block->getCleanUrl() ?>"
                class="active-filters__clear-all"
                title="<?= __('Clear all filters') ?>"
            >
                <?= __('Clear All') ?>
            </a>
        </ul>
    </div>
<?php endif; ?>
