<?php
/** @var \Snowdog\SolrNavigation\Block\Filters $block */
$filters = $block->getFilterBlocks();
?>

<?php if (!empty($filters)): ?>
    <h1 class="filters__heading">
        <?= /* @escapeNotVerified */ __('Now Shopping by') ?>
    </h1>
    <div class="divider filters__divider">
        <span class="divider__left"></span>
        <span class="divider__right"></span>
    </div>
    <div class="filters__active">
        <ul class="active-filters list">
            <?php foreach ($filters as $filterBlock): ?>
                <?= $filterBlock->toHtml() ?>
            <?php endforeach; ?>
            <a
                href="<?= $block->getCleanUrl() ?>"
                class="active-filters__clear-all"
                title="<?= __('Clear all filters') ?>"
            >
                <?= /* @escapeNotVerified */ __('Clear All') ?>
            </a>
        </ul>
    </div>
<?php endif; ?>
