<?php
use Snowdog\SolrNavigation\Helper\Data;
/* @var $block \Snowdog\SolrNavigation\Block\Product\ListProduct */
/** @var Data $solrDataHelper */
$solrDataHelper = $this->helper('Snowdog\SolrNavigation\Helper\Data');
?>

<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>

<?php if ($block->getMode() == 'grid') : ?>
    <?php if (count($block->getProducts()) == 0): ?>
        <div class="message info empty">
            <div>
                <?= __('We can\'t find products matching the selection.') ?>
            </div>
        </div>
    <?php else: ?>
        <ul class="catalog-grid">
            <?php foreach ($block->getProducts() as $_product): ?>
                <li
                    class="catalog-grid-item"
                    data-testid="catalog-grid-item"
                >
                    <?php if ($solrDataHelper->isProductNew($_product) === true): ?>
                        <div class="badge catalog-grid-item__badge">
                            <?= __('NEW') ?>
                        </div>
                    <?php endif ?>
                    <a
                        href="<?= $block->getProductUrl($_product) ?>"
                        class="catalog-grid-item__link"
                        title="<?= $_product['name'] ?>"
                        data-testid="catalog-grid-item__link"
                    >
                        <div class="lazyload-wrapper catalog-grid-item__image-wrapper">
                            <img
                                class="image lazyload"
                                src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                                data-src="<?= $solrDataHelper->getImageUrl($_product['small_image'], 564, 700) ?>"
                                alt="<?= $_product['image_label'] ?>"
                                data-testid="catalog-grid-item__image"
                            />
                        </div>
                    </a>
                    <section class="catalog-grid-item__details">
                        <h2
                            class="
                                catalog-grid-item__name
                                <?= !$solrDataHelper->getPrice($_product) ? 'catalog-grid-item__name--bigger' : '' ?>
                            "
                            data-testid="catalog-grid-item__name"
                        >
                            <a
                                href="<?= $block->getProductUrl($_product) ?>"
                                class="catalog-grid-item__name-link"
                                title="<?= $_product['name'] ?>"
                            >
                                <?= $_product['name'] ?>
                            </a>
                        </h2>
                        <?php if($solrDataHelper->getPrice($_product)): ?>
                            <div class="catalog-grid-item__price">
                                <div
                                    class="price"
                                    data-testid="catalog-grid-item__price"
                                >
                                    <span class="price__value">
                                        <?= $solrDataHelper->getPrice($_product) ?>
                                    </span>
                                </div>
                            </div>
                        <?php endif ?>
                        <?php
                        $reviews = $block->getProductReviewSummary($_product['entity_id']);
                        $rating = $reviews['rating_summary'];
                        ?>
                        <?php if ($rating): ?>
                            <div
                                class="rating catalog-grid-item__rating"
                                aria-label="<?= __('Average rating') ?>: <?= $rating ?>%"
                                title="<?= __('Average rating') ?>: <?= $rating ?>%"
                                tabindex="0"
                            >
                                <div
                                    class="rating__star"
                                    style="width: <?= $rating ?>%"
                                    data-testid="rating__star"
                                >
                                    <span class="rating__indicator"></span>
                                </div>
                            </div>
                        <?php endif ?>

                        <div class="catalog-grid-item__actions">
                            <form
                                class="catalog-grid-item__primary-form"
                                action="<?= $block->escapeUrl($block->getAddToUrl('cart', $_product['entity_id'], false)) ?>"
                                method="post"
                                data-mage-init='{ "solrAddToCart": {} }'
                                data-product-sku="<?= $_product['sku'] ?>"
                            >
                                <input
                                    type="hidden"
                                    name="product"
                                    value="<?= $_product['entity_id'] ?>"
                                />

                                <?= $block->getBlockHtml('formkey') ?>

                                <button
                                    class="
                                        button
                                        button--secondary
                                        catalog-grid-item__primary-action
                                        action
                                        tocart
                                    "
                                    type="submit"
                                    disabled
                                    data-testid="add-to-cart-button"
                                >
                                    <span class="catalog-grid-item__cart-text">
                                        <?= __('Add to Cart') ?>
                                    </span>
                                    <svg class="icon catalog-grid-item__cart-icon">
                                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#shopping-cart') ?>"></use>
                                    </svg>
                                </button>
                            </form>
                            <div class="catalog-grid-item__secondary-action">
                                <button
                                    class="button button--icon"
                                    type="button"
                                    aria-label="<?= __('Add to wishlist') ?>"
                                    title="<?= __('Add to wishlist') ?>"
                                    data-post='{
                                        "action": "<?= $block->escapeUrl($block->getAddToUrl('wishlist', $_product['entity_id'], false)) ?>",
                                        "data": { "product": <?= $_product['entity_id'] ?> }
                                    }'
                                    data-action="add-to-wishlist"
                                    data-testid="add-to-wishlist-button"
                                >
                                    <svg class="button__icon">
                                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#heart') ?>"></use>
                                    </svg>
                                </button>
                            </div>
                            <div class="catalog-grid-item__secondary-action">
                                <button
                                    class="button button--icon"
                                    type="button"
                                    aria-label="<?= __('Add to compare') ?>"
                                    title="<?= __('Add to compare') ?>"
                                    data-post='{
                                        "action": "<?= $block->escapeUrl($block->getAddToUrl('compare', $_product['entity_id'], false)) ?>",
                                        "data": { "product": <?= $_product['entity_id'] ?> }
                                    }'
                                    data-action="add-to-compare"
                                    data-testid="add-to-compare-button"
                                >
                                    <svg class="button__icon">
                                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#compare') ?>"></use>
                                    </svg>
                                </button>
                            </div>
                        </div>
                    </section>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endif ?>
<?php endif ?>
