<?php
use Snowdog\SolrNavigation\Helper\Data;
/* @var $block \Snowdog\SolrNavigation\Block\Product\ListProduct */
/** @var Data $solrDataHelper */
$solrDataHelper = $this->helper('Snowdog\SolrNavigation\Helper\Data');
?>

<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>

<?php if ($block->getMode() == 'list') : ?>
    <?php if (count($block->getProducts()) == 0): ?>
        <div class="message info empty">
            <?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?>
        </div>
    <?php else: ?>
        <?php foreach ($block->getProducts() as $_product): ?>
            <section class="catalog-list-item catalog-list__item">
                <a
                    href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
                    class="catalog-list-item__link"
                    title="<?= $block->escapeHtmlAttr($_product['name']) ?>"
                >
                    <div class="lazyload-wrapper catalog-list-item__image-wrapper">
                        <img
                            class="image lazyload"
                            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                            data-src="<?= $block->escapeUrl($solrDataHelper->getImageUrl($_product['small_image'], 564, 700)) ?>"
                            alt="<?= $block->escapeHtmlAttr($_product['image_label']) ?>"
                        />
                    </div>
                </a>
                <div class="catalog-list-item__main">
                    <?php if ($solrDataHelper->isProductNew($_product) === true): ?>
                        <div class="badge catalog-list-item__badge">
                            <?= $block->escapeHtml(__('NEW')) ?>
                        </div>
                    <?php endif; ?>
                    <div class="catalog-list-item__details">
                        <h2 class="catalog-list-item__name">
                            <a
                                href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
                                class="catalog-list-item__link"
                                title="<?= $block->escapeHtmlAttr($_product['name']) ?>"
                            >
                                <?= $block->escapeHtml($_product['name']) ?>
                            </a>
                        </h2>
                        <div class="catalog-list-item__reviews">
                            <?php
                            $reviews = $block->getProductReviewSummary($_product['entity_id']);
                            $rating = $reviews['rating_summary'];
                            ?>
                            <?php if ($rating): ?>
                                <div
                                    class="rating catalog-grid-item__rating"
                                    aria-label="<?= $block->escapeHtmlAttr(__('Average rating')) ?>: <?= $block->escapeHtmlAttr($rating) ?>%"
                                    title="<?= $block->escapeHtmlAttr(__('Average rating')) ?>: <?= $block->escapeHtmlAttr($rating) ?>%"
                                    tabindex="0"
                                >
                                    <div class="rating__star" style="width: <?= $rating ?>%">
                                        <span class="rating__indicator"></span>
                                    </div>
                                </div>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="catalog-list-item__price">
                        <div class="price">
                            <span class="price__value">
                                <?= $block->escapeHtml($solrDataHelper->getPrice($_product)) ?>
                            </span>
                        </div>
                    </div>
                    <div class="catalog-list-item__actions">
                        <div class="catalog-list-item__actions-primary">
                            <form
                                action="<?= $block->escapeUrl($block->getAddToUrl('cart', $_product['entity_id'], false)) ?>"
                                method="post"
                                data-mage-init='{ "solrAddToCart": {} }'
                                data-product-sku="<?= $block->escapeHtmlAttr($_product['sku']) ?>"
                            >
                                <input
                                    type="hidden"
                                    name="product"
                                    value="<?= $block->escapeHtmlAttr($_product['entity_id']) ?>"
                                />

                                <?= $block->getBlockHtml('formkey') ?>

                                <button
                                    class="
                                        button
                                        button--secondary
                                        catalog-list-item__actions-primary-button
                                        action
                                        tocart
                                    "
                                    type="submit"
                                    disabled
                                >
                                    <span>
                                        <?= $block->escapeHtml(__('Add to Cart')) ?>
                                    </span>
                                </button>
                            </form>
                        </div>
                        <div class="catalog-list-item__actions-secondary">
                            <button
                                class="button button--icon"
                                type="button"
                                aria-label="<?= $block->escapeHtmlAttr(__('Add to wishlist')) ?>"
                                data-post='{
                                    "action": "<?= $block->escapeJs($block->getAddToUrl('wishlist', $_product['entity_id'], false)) ?>",
                                    "data": { "product": <?= $block->escapeJs(['entity_id']) ?> }
                                }'
                                data-action="add-to-wishlist"
                            >
                                <svg class="button__icon">
                                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#heart')) ?>"></use>
                                </svg>
                            </button>
                            <button
                                class="button button--icon"
                                type="button"
                                aria-label="<?= $block->escapeHtmlAttr(__('Add to compare')) ?>"
                                data-post='{
                                    "action": "<?= $block->escapeJs($block->getAddToUrl('compare', $_product['entity_id'], false)) ?>",
                                    "data": { "product": <?= $block->escapeJs(['entity_id']) ?> }
                                }'
                                data-action="add-to-compare"
                            >
                                <svg class="button__icon">
                                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#compare')) ?>"></use>
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
            </section>
        <?php endforeach ?>
    <?php endif ?>
<?php endif ?>
