<?php
use Snowdog\SolrNavigation\Helper\Data;
/* @var $block \Snowdog\SolrNavigation\Block\Product\ListProduct */
/** @var Data $solrDataHelper */
$solrDataHelper = $this->helper('Snowdog\SolrNavigation\Helper\Data');
?>

<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>

<?php if ($block->getMode() == 'list') : ?>
    <?php if (count($block->getProducts()) == 0): ?>
        <div class="message info empty">
            <?= __('We can\'t find products matching the selection.') ?>
        </div>
    <?php else: ?>
        <?php foreach ($block->getProducts() as $_product): ?>
            <section class="catalog-list-item catalog-list__item">
                <a
                    href="<?= $block->getProductUrl($_product) ?>"
                    class="catalog-list-item__link"
                    title="<?= $_product['name'] ?>"
                >
                    <div class="lazyload-wrapper catalog-list-item__image-wrapper">
                        <img
                            class="image lazyload"
                            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                            data-src="<?= $solrDataHelper->getImageUrl($_product['small_image'], 564, 700) ?>"
                            alt="<?= $_product['image_label'] ?>"
                        />
                    </div>
                </a>
                <div class="catalog-list-item__main">
                    <?php if ($solrDataHelper->isProductNew($_product) === true): ?>
                        <div class="badge catalog-list-item__badge">
                            <?= __('NEW') ?>
                        </div>
                    <?php endif; ?>
                    <div class="catalog-list-item__details">
                        <h2 class="catalog-list-item__name">
                            <a
                                href="<?= $block->getProductUrl($_product) ?>"
                                class="catalog-list-item__link"
                                title="<?= $_product['name'] ?>"
                            >
                                <?= $_product['name'] ?>
                            </a>
                        </h2>
                        <div class="catalog-list-item__reviews">
                            <?php
                            $reviews = $block->getProductReviewSummary($_product['entity_id']);
                            $rating = $reviews['rating_summary'];
                            ?>
                            <?php if ($rating): ?>
                                <div
                                    class="rating catalog-grid-item__rating"
                                    aria-label="<?= __('Average rating') ?>: <?= $rating ?>%"
                                    title="<?= __('Average rating') ?>: <?= $rating ?>%"
                                    tabindex="0"
                                >
                                    <div class="rating__star" style="width: <?= $rating ?>%">
                                        <span class="rating__indicator"></span>
                                    </div>
                                </div>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="catalog-list-item__price">
                        <div class="price">
                            <span class="price__value">
                                <?= $solrDataHelper->getPrice($_product) ?>
                            </span>
                        </div>
                    </div>
                    <div class="catalog-list-item__actions">
                        <div class="catalog-list-item__actions-primary">
                            <form
                                action="<?= $block->escapeUrl($block->getAddToUrl('cart', $_product['entity_id'])) ?>"
                                method="post"
                                data-mage-init='{ "solrAddToCart": {} }'
                            >
                                <input
                                    type="hidden"
                                    name="form_key"
                                    value=""
                                >

                                <button
                                    class="
                                        button
                                        button--secondary
                                        catalog-list-item__actions-primary-button
                                    "
                                    type="submit"
                                >
                                    <span>
                                        <?= __('Add to Cart') ?>
                                    </span>
                                </button>
                            </form>
                        </div>
                        <div class="catalog-list-item__actions-secondary">
                            <form
                                action="<?= $block->escapeHtml($block->getAddToUrl('wishlist', $_product['entity_id'])) ?>"
                                method="post"
                                data-mage-init='{ "validation": {} }'
                            >
                                <button
                                    class="button button--icon"
                                    type="submit"
                                    aria-label="<?= __('Add to wishlist') ?>"
                                    title="<?= __('Add to wishlist') ?>"
                                >
                                    <svg class="button__icon">
                                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#heart') ?>"></use>
                                    </svg>
                                </button>
                            </form>
                            <form
                                action="<?= $block->escapeHtml($block->getAddToUrl('compare', $_product['entity_id'])) ?>"
                                method="post"
                                data-mage-init='{ "validation": {} }'
                            >
                                <button
                                    class="button button--icon"
                                    type="submit"
                                    aria-label="<?= __('Add to compare') ?>"
                                    title="<?= __('Add to compare') ?>"
                                >
                                    <svg class="button__icon">
                                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#compare') ?>"></use>
                                    </svg>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
        <?php endforeach ?>
    <?php endif ?>
<?php endif ?>
