<?php
//phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
//phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
<?php
/**
 * Create account form template
 */
/* @var $block \Magento\CustomAttributeManagement\Block\Form\Renderer\Text */
$elementId = /* @noEscape */ $block->getHtmlId() . '<%- data._index_ %>';
?>
<div
    id="<?= /* @noEscape */ $elementId ?>"
    class="
        input
        col-md-6
        <?= /* @noEscape */ $block->getHtmlId() ?>
        <?= /* @noEscape */ $elementId ?>
        <?php if ($block->isRequired()): ?>
            required
        <?php endif;?>
    "
>
    <label
        for="items:<?= /* @noEscape */ $block->getHtmlId() ?><%- data._index_ %>"
        class="label input__label"
    >
        <?= $block->escapeHtml($block->getLabel()) ?>
    </label>
    <input
        type="text"
        id="items:<?= /* @noEscape */ $block->getHtmlId() ?><%- data._index_ %>"
        name="items[<%- data._index_ %>][<?= $block->escapeHtmlAttr($block->getFieldName()) ?>]"
        value="<?= $block->escapeHtmlAttr($block->getEscapedValue()) ?>"
        class="
            input__field
            margin-bottom-m
            <?= $block->getHtmlClass();?>
            <?= ($block->getFieldName() == 'qty_requested') ? ' check-count' : ''?>
        "
    >
</div>
