<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
//phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
<?php
/**
 * Create account form template
 */
/* @var $block \Magento\CustomAttributeManagement\Block\Form\Renderer\Text */
$elementId = /* @noEscape */ $block->getHtmlId() . '<%- data._index_ %>';
?>
<div id="<?= /* @noEscape */ $elementId ?>" class="field <?= /* @noEscape */ $block->getHtmlId() ?>
    <?= /* @noEscape */ $elementId ?><?php if ($block->isRequired()) : ?> required<?php endif;?>">
    <label for="items:<?= /* @noEscape */ $block->getHtmlId() ?><%- data._index_ %>" class="label">
        <span><?= $block->escapeHtml($block->getLabel()) ?></span>
    </label>
    <div class="control">
        <input type="text" id="items:<?= /* @noEscape */ $block->getHtmlId() ?><%- data._index_ %>" name="items[<%- data._index_ %>][<?= $block->escapeHtmlAttr($block->getFieldName()) ?>]" value="<?= $block->escapeHtmlAttr($block->getEscapedValue()) ?>" class="input-text<?= $block->getHtmlClass();?><?= ($block->getFieldName() == 'qty_requested') ? ' check-count' : ''?>">
    </div>
</div>
