<?php
/** @var $block \Magento\Rma\Block\Order\Button */
?>
<?php if ($this->helper(Magento\Rma\Helper\Data::class)->canCreateRma($block->getOrder())): ?>
    <a
        href="<?= $block->escapeUrl($this->helper(Magento\Rma\Helper\Data::class)->getReturnCreateUrl($block->getOrder())) ?>"
        class="
            actions-group__link
            dashboard-table__link
            padding-0
        "
        aria-label="<?= $block->escapeHtmlAttr(__('Return Order')) ?>"
    >
        <?= $block->escapeHtml(__('Return')) ?>
    </a>
<?php endif;?>
