<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
/** @var $block \Magento\Rma\Block\Order\Button */
?>
<?php if ($this->helper(Magento\Rma\Helper\Data::class)->canCreateRma($block->getOrder())) : ?>
    <a href="<?= $block->escapeUrl($this->helper(Magento\Rma\Helper\Data::class)->getReturnCreateUrl($block->getOrder())) ?>" class="action return"><span><?= $block->escapeHtml(__('Return')) ?></span></a>
<?php endif;?>
