<?php /** @var \Snowdog\Menu\Block\NodeType\Category $block */ ?>
<?php
    $nodeId = $block->getId();
    $class = $block->getMenuClass();
    $categoryUrl = $block->getCategoryUrl($nodeId);
    $categoryUrl = $categoryUrl ?: '#';
    $dataAttribute = '';


    $classLink = $block->getIsRoot() ? $class . '__link' : $class . '__inner-link';
    $title = $block->getTitle();

    if ($nodeId) {
        $dataAttribute = ' data-menu="menu-' . $nodeId . '"';
    }

    if ($block->isCurrentCategory($nodeId)) {
        $classLink .= ' current';
    }
?>
<a href="<?= $categoryUrl ?>" class="<?= $classLink ?>"<?= $dataAttribute ?>>
    <?= $title ?>
</a>
