<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>

<?php if ($_product->isSaleable()): ?>
        <button
            type="submit"
            title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
            class="
                button
                product-view__add-to-cart
                button--add-to
                action
                tocart
            "
            id="product-addtocart-button"
            aria-label="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
        >
            <span class="button__text">
                <?= $block->escapeHtml($buttonTitle) ?>
            </span>
        </button>

        <?= $block->getChildHtml('', true) ?>
<?php endif; ?>

<?php if ($block->isRedirectToCartEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else: ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/js/validate-product": {}
            }
        }
    </script>
<?php endif; ?>
