<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>

<?php if ($_product->isSaleable()): ?>
        <button
            type="submit"
            title="<?= $buttonTitle ?>"
            class="
                button
                button--icon
                button--add-to-icon
                product-view__add-to-cart
                action
                tocart
            "
            id="product-addtocart-button"
            aria-label="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
        >
            <span class="button__text">
                <?= $buttonTitle ?>
            </span>
            <svg
                class="icon button__icon"
                role="presentation"
                focusable="false"
            >
                <title>Add to Cart</title>
                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#shopping-cart')); ?>"></use>
            </svg>
        </button>

        <?= $block->getChildHtml('', true) ?>
<?php endif; ?>

<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else: ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/js/validate-product": {}
            }
        }
    </script>
<?php endif; ?>
