<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>

<?php if ($_product->isSaleable()): ?>
    <div class="product-view__add-to-cart">
        <button
            type="submit"
            title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
            class="button primary tocart"
            id="product-addtocart-button"
        >
            <?= /* @escapeNotVerified */ $buttonTitle ?>
        </button>

        <?= $block->getChildHtml('', true) ?>
    </div>
<?php endif; ?>

<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/js/validate-product": {}
            }
        }
    </script>
<?php endif; ?>
