<?php
/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <table class="table table--clean" id="product-attribute-specs-table">
        <tbody>
            <?php foreach ($_additional as $_data): ?>
                <tr>
                    <th class="label" scope="row">
                        <?= $block->escapeHtml(__($_data['label'])) ?>
                    </th>

                    <td class="data" data-th="<?= $block->escapeHtml(__($_data['label'])) ?>">
                        <?= $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif;?>
