<?php
/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <table
        class="table table--scope-row"
        id="product-attribute-specs-table"
    >
        <caption class="table__caption">
            <?= $block->escapeHtml(__('Product specification details')) ?>
        </caption>
        <tbody>
            <?php foreach ($_additional as $_data): ?>
                <tr role="row">
                    <th
                        scope="row"
                        role="rowheader"
                    >
                        <?= $block->escapeHtml(__($_data['label'])) ?>
                    </th>

                    <td
                        role="gridcell"
                        data-th="<?= $block->escapeHtmlAttr(__($_data['label'])) ?>"
                    >
                        <?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif;?>
