<div class="product-view__information">
    <div class="brief-info">
        <h3 class="brief-info__heading">
            <?= $escaper->escapeHtml(__('Buy with us')) ?>
        </h3>
        <div class="brief-info__items-container">
            <div class="brief-info__item">
                <span
                    class="brief-info__icon-wrapper brief-info__icon-wrapper--delivery-truck"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Delivery truck')) ?>"
                >
                    <svg
                        class="
                            icon
                            brief-info__icon
                            brief-info__icon--delivery-truck
                        "
                        role="presentation"
                        focusable="false"
                    >
                        <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#shipping-time-truck')); ?>"></use>
                    </svg>
                </span>

                <div class="brief-info__content">
                    <h3 class="brief-info__title">
                        <?= $escaper->escapeHtml(__('Shipping in 24h')) ?>
                    </h3>
                </div>
            </div>

            <div class="brief-info__item">
                <span
                    class="brief-info__icon-wrapper"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Curved arrows')) ?>"
                >
                    <svg
                        class="
                            icon
                            brief-info__icon
                        "
                        role="presentation"
                        focusable="false"
                    >
                        <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#curved-arrows')); ?>"></use>
                    </svg>
                </span>

                <div class="brief-info__content">
                    <h3 class="brief-info__title">
                        <?= $escaper->escapeHtml(__('Free returns')) ?>
                    </h3>
                </div>
            </div>

            <div class="brief-info__item">
                <span
                    class="brief-info__icon-wrapper"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Shield')) ?>"
                >
                    <svg
                        class="
                            icon
                            brief-info__icon
                        "
                        role="presentation"
                        focusable="false"
                    >
                        <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#shield')); ?>"></use>
                    </svg>
                </span>

                <div class="brief-info__content">
                    <h3 class="brief-info__title">
                        <?= $escaper->escapeHtml(__('Secure payment')) ?>
                    </h3>
                </div>
            </div>
        </div>
    </div>
</div>
