<div class="product-view__brief">
    <div class="brief-info">
        <ul class="list brief-info__items-container">
            <li class="list__item brief-info__list-item">
                <button
                    class="brief-info__item modal-trigger"
                    type="button"
                    data-modal-trigger="popup-product-benefit-1"
                    data-mage-init='{"modal" : {}}'
                >
                    <span
                        class="
                            brief-info__icon-wrapper
                            margin-right-xs
                        "
                        aria-label="<?= $block->escapeHtmlAttr(__('Delivery'))  ?>"
                    >
                        <svg
                            class="icon brief-info__icon"
                            role="presentation"
                            focusable="false"
                        >
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#delivery')); ?>"></use>
                        </svg>
                    </span>
                    <div class="brief-info__content">
                        <h3 class="brief-info__title">
                            <?= $block->escapeHtml(__('Free Shipping')) ?>
                        </h3>
                        <p class="brief-info__subtitle">
                            <?= $block->escapeHtml(__('On Hundreds of Products')) ?>
                        </p>
                    </div>
                </button>
            </li>
            <li class="list__item brief-info__list-item">
                <button
                    class="brief-info__item modal-trigger"
                    type="button"
                    data-modal-trigger="popup-product-benefit-2"
                    data-mage-init='{"modal" : {}}'
                >
                    <span
                        class="
                            brief-info__icon-wrapper
                            margin-right-xs
                        "
                        aria-label="<?= $block->escapeHtmlAttr(__('Big Star'))  ?>"
                    >
                        <svg
                            class="icon brief-info__icon"
                            role="presentation"
                            focusable="false"
                        >
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#return')); ?>"></use>
                        </svg>
                    </span>
                    <div class="brief-info__content">
                        <span class="brief-info__title">
                            <?= $block->escapeHtml(__('Return Policy')) ?>
                        </span>
                        <p class="brief-info__subtitle">
                            <?= $block->escapeHtml(__('Lorem Ipsum is simply')) ?>
                        </p>
                    </div>
                </button>
            </li>
        </ul>
    </div>
</div>
<?= $block->getChildHtml('popup.product.benefit1'); ?>
<?= $block->getChildHtml('popup.product.benefit2'); ?>
