<picture class="image additional-content__image">
    <source
        data-srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        media="(max-width: 767px)"
        srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
    >

    <source
        data-srcset="<?= $block->getViewFileUrl('/images/product-view/banner.jpg') ?>"
        media="(min-width: 768px)"
        srcset="<?= $block->getViewFileUrl('/images/product-view/banner.jpg') ?>"
    >

    <img
        class="lazyloaded"
        src="<?= $block->getViewFileUrl('/images/product-view/banner.jpg') ?>"
        data-src="<?= $block->getViewFileUrl('/images/product-view/banner.jpg') ?>"
        alt="image alt text"
    >
</picture>

<div class="additional-content__info">
    <div class="additional-content__section">
        <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        </p>

        <p>
            It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        </p>
    </div>

    <div class="additional-content__section">
        <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
        </p>

        <p>
            It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        </p>
    </div>
</div>
