<?php
// TODO get magento version without objectManager
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productMetadata = $objectManager->get('Magento\Framework\App\ProductMetadataInterface');
?>

<div 
    class="
        product-view__buttons-wrapper
        <?= ($productMetadata->getEdition() == 'B2B') ? 'product-view__buttons-wrapper--ee' : '' ?>
    "
>
    <?= $block->getChildHtml() ?>  
</div>


