<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Snowdog\AlpacaGeneral\ViewModel\ProductMetadata $productMetadata */
$productMetadata = $block->getProductMetadata();
?>

<div
    class="
        product-view__buttons-wrapper
        <?= ($productMetadata->getEdition() == 'B2B') ? 'product-view__buttons-wrapper--ee' : '' ?>
    "
>
    <?= $block->getChildHtml() ?>
</div>


