<?php
/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>

<form
    data-product-sku="<?= $_product->getSku() ?>"
    action="<?= $block->getSubmitUrl($_product) ?>"
    method="post"
    class="product-view__form"
    id="product_addtocart_form"<?php if ($_product->getOptions()): ?>
    enctype="multipart/form-data"<?php endif; ?>
>
    <input type="hidden" name="product" value="<?= $_product->getId() ?>" />
    <input type="hidden" name="selected_configurable_option" value="" />
    <input type="hidden" name="related_product" id="related-products-field" value="" />

    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getChildHtml('form_top') ?>

    <?php if ($block->hasOptions()): ?>
        <?= $block->getChildHtml('product.column.right.options'); ?>
    <?php else: ?>
        <?= $block->getChildHtml('product.info.form.content'); ?>
    <?php endif ?>

    <?= $block->getChildHtml('product.column.right.actions') ?>
</form>

<script>
    require([
        'jquery',
        'priceBox'
    ], function($) {
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($_product->getId()) ?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?= $block->getJsonConfig() ?>});
    });
</script>
