<?php
/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');
$imageWidth = $block->getImageAttribute('product_page_image_medium', 'width');
$imageHeight = $block->getImageAttribute('product_page_image_medium', 'height');
?>

<div
    class="
        gallery-placeholder
        fotorama__wrapper
        _block-content-loading
    "
    data-gallery-role="gallery-placeholder"
    data-testid="product-gallery-placeholder"
>
    <div
        data-role="loader"
        class="
            loader
            loader--visible
            ratio-container
        "
        aria-live="polite"
        aria-label="<?= $block->escapeHtmlAttr(__('Do not refresh the page')); ?>"
        style="padding-bottom: <?= $imageHeight / $imageWidth * 100 ?>%"
    >
        <div class="loader__icon"></div>
        <img
            alt="<?= $mainImage ? $block->escapeHtmlAttr($mainImage->getData('label')) : 'placeholder'; ?>"
            class="
                gallery__placeholder-image
                lazyload
                ratio-image
            "
            data-src="<?= /* @noEscape */ $mainImageData ?>"
            src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAABCAQAAABN/Pf1AAAAC0lEQVR42mNkwAIAACoAAgu1Hc4AAAAASUVORK5CYII&#x3D;"
        />
    </div>
</div>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
