<?php
/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$imageWidth = $block->getImageAttribute('product_page_image_medium', 'width');
$imageHeight = $block->getImageAttribute('product_page_image_medium', 'height');
?>

<div
    class="gallery-placeholder _block-content-loading"
    data-gallery-role="gallery-placeholder"
    data-testid="product-gallery-placeholder"
>
    <div
        data-role="loader"
        aria-live="polite"
        aria-label="<?= $block->escapeHtmlAttr(__('Do not refresh the page')); ?>"
        class="loader loader--visible"
        style="padding-bottom: <?= $imageHeight / $imageWidth * 100 ?>%"
    >
        <div class="loader__icon"></div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
