<?php // phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis ?>
<?php
$_product = $block->getProduct();
$helper = $this->helper(Magento\Catalog\Helper\Product::class);
?>

<?php if ($block->canEmailToFriend()): ?>
    <a
        href="<?= $escaper->escapeUrl($helper->getEmailToFriendUrl($_product)) ?>"
        class="product-view__action product-view__action--a product-view__action--emailfriend"
        data-testid="product-email-friend-link"
    >
        <svg
            class="icon product-view__icon-envelope"
            role="presentation"
            focusable="false"
        >
            <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#envelope')); ?>"></use>
        </svg>
    </a>
<?php endif; ?>
