<?php // @codingStandardsIgnoreFile ?>
<?php
$_product = $block->getProduct();
$helper = $this->helper('Magento\Catalog\Helper\Product');
?>

<?php if ($block->canEmailToFriend()): ?>
    <a
        href="<?= $helper->getEmailToFriendUrl($_product) ?>"
        class="product-view__action product-view__action--a product-view__action--emailfriend"
        data-testid="product-email-friend-link"
    >
        <svg class="icon product-view__icon-envelope">
            <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#envelope'); ?>"></use>
        </svg>
    </a>
<?php endif; ?>
