<?php
$_product = $block->getProduct();
$productId = $_product->getId();
?>

<?php if ($block->shouldRenderQuantity() && $_product->isSaleable()): ?>
    <div
        class="
            product-view__qty
            qty-<?= $block->escapeHtmlAttr($productId) ?>
        "
    >
        <label class="label" for="qty">
            <?= $block->escapeHtml(__('Qty')) ?>
        </label>

        <div
            class="quantity-update"
            data-mage-init='{ "qtyUpdater": {
                "increaseText": "<?= $block->escapeHtml(__('The quantity was increased to')) ?>",
                "decreseText": "<?= $block->escapeHtml(__('The quantity was decreased to')) ?>"
            } }'
        >
            <button
                class="
                    button
                    button--icon
                    quantity-update__button
                    quantity-update__button--minus
                "
                type="button"
                aria-label="<?= $block->escapeHtmlAttr(__('Decrease the quantity')) ?>"
                data-testid="quantity-minus-button"
            >
                <svg
                    class="
                        icon
                        button__icon
                        quantity-update__icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#minus')); ?>"></use>
                </svg>
            </button>

            <input
                type="number"
                name="qty"
                id="qty"
                value="<?= $block->getProductDefaultQty() * 1 ?>"
                title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                class="quantity-update__input"
                data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
            />

            <button
                class="
                    button
                    button--icon
                    quantity-update__button
                    quantity-update__button--plus
                "
                type="button"
                aria-label="<?= $block->escapeHtmlAttr(__('Increase the quantity')) ?>"
                data-testid="quantity-plus-button"
            >
                <svg
                    class="
                        icon
                        button__icon
                        quantity-update__icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#plus')); ?>"></use>
                </svg>
            </button>
            <p
                role="alert"
                class="quantity-update__alert display-none"
            ></p>
        </div>
    </div>
<?php endif; ?>
