<?php $_product = $block->getProduct(); ?>

<?php if ($block->shouldRenderQuantity() && $_product->isSaleable()): ?>
    <div class="product-view__qty">
        <label class="label" for="qty">
            <?= __('Qty') ?>
        </label>

        <div
            class="quantity-update"
            data-mage-init='{ "qtyUpdater": {} }'
        >
            <button
                class="
                    button
                    button--icon
                    button--icon-light
                    quantity-update__button
                    quantity-update__button--minus
                "
                type="button"
                aria-label="Decrease the quantity"
                data-testid="quantity-minus-button"
            >
                <svg
                    class="
                        icon
                        button__icon
                        quantity-update__icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#minus'); ?>"></use>
                </svg>
            </button>

            <input
                type="number"
                name="qty"
                id="qty"
                value="<?= $block->getProductDefaultQty() * 1 ?>"
                title="<?= __('Qty') ?>"
                class="quantity-update__input"
                data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
            />

            <button
                class="
                    button
                    button--icon
                    button--icon-light
                    quantity-update__button
                    quantity-update__button--plus
                "
                type="button"
                aria-label="Increase the quantity"
                data-testid="quantity-plus-button"
            >
                <svg
                    class="
                        icon
                        button__icon
                        quantity-update__icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#plus'); ?>"></use>
                </svg>
            </button>
        </div>
    </div>
<?php endif; ?>
