<?php $_product = $block->getProduct(); ?>

<?php if ($block->shouldRenderQuantity() && $_product->isSaleable()): ?>
    <div class="product-view__qty">
        <label class="product-view__swatch-option-title" for="qty">
            <?= __('Qty') ?>
        </label>

        <div class="quantity-update" data-mage-init='{ "qtyUpdater": {} }'>
            <button
                class="
                    button
                    button--icon
                    quantity-update__button
                    quantity-update__button--minus
                "
                type="button"
                aria-label="quantity minus button"
                data-testid="quantity-minus-button"
            >
                <svg class="button__icon quantity-update__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#minus'); ?>"></use>
                </svg>
            </button>

            <input
                type="number"
                name="qty"
                id="qty"
                value="<?= $block->getProductDefaultQty() * 1 ?>"
                title="<?= __('Qty') ?>"
                class="quantity-update__input"
                data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
            />

            <button
                class="
                    button
                    button--icon
                    quantity-update__button
                    quantity-update__button--plus
                "
                type="button"
                aria-label="quantity plus button"
                data-testid="quantity-plus-button"
            >
                <svg class="button__icon quantity-update__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#plus'); ?>"></use>
                </svg>
            </button>
        </div>
    </div>
<?php endif; ?>
