<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php
$_product = $block->getProduct();
/** @var \Snowdog\ShippingLatency\Helper\Data $shippingLatencyHelper */
$shippingLatencyHelper = $this->helper('Snowdog\ShippingLatency\Helper\Data');
$shippingLatencyText = $_product->getAttributeText('shipping_latency');
$isShownInStock = $shippingLatencyHelper->isShippingLatencyAllowed($_product);
?>

<?php if($shippingLatencyHelper && ($isShownInStock || $shippingLatencyText)): ?>
    <button
        class="
            button
            button--link
            modal-trigger
            product-view__stock
        "
        type="button"
        aria-expanded="false"
        data-modal-trigger="shipping-latency-popup"
        data-mage-init='{ "modal" : {} }'
    >
        <?php if ($isShownInStock): ?>
            <?= $block->escapeHtml(__('In stock')) ?>
        <?php elseif ($shippingLatencyText->getText() !== 'None'): ?>
            <?= $block->escapeHtml($shippingLatencyText); ?>
        <?php else: ?>
            <?= $block->escapeHtml(__('Out of stock')) ?>
        <?php endif; ?>
    </button>
    <div
        id="shipping-latency-popup"
        role="dialog"
        aria-hidden="true"
        data-modal="shipping-latency-popup"
        aria-labelledby="shipping-latency-title"
        class="modal"
    >
        <div
            class="modal__container"
            role="document"
            tabindex="0"
        >
            <div class="modal__content">
                <?php if ($isShownInStock): ?>
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('one-day-shipping')->toHtml(); ?>
                <?php else: ?>
                    <h3 id="shipping-latency-title">
                        <?= $block->escapeHtml($shippingLatencyText); ?>
                    </h3>
                    <?= $shippingLatencyHelper->getProductPopupHtml($_product->getData()); ?>
                <?php endif ?>
            </div>
            <button
                class="
                    button
                    button--icon
                    button--rotate-icon
                    modal__close-button
                "
                type="button"
                aria-label="<?= $block->escapeHtmlAttr(__('Close modal')) ?>"
            >
                <svg
                    class="
                        icon
                        button__icon
                        modal__close-button-icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <title><?= __('Close') ?></title>
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#close')); ?>"></use>
                </svg>
            </button>
        </div>
    </div>
<?php endif; ?>
