<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper(Magento\Catalog\Helper\Output::class);
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $block->decorateArray($block->getOptions($stripSelection));
?>
<?php if ($product->isSaleable()):?>
    <?php if (count($options)): ?>
        <script type="text/x-magento-init">
            {
                "#product_addtocart_form": {
                    "priceBundle": {
                        "optionConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                        "controlContainer": ".bundle-option"
                    }
                }
            }
        </script>
        <div class="product-view__customization">
            <div class="product-view__description product-view__description-bundle">
                <span class="product-view__description-title">
                    <?= $block->escapeHtml(__('Customize %1', $helper->productAttribute($product, $product->getName(), 'name'))) ?>
                </span>
            </div>
            <?= $block->getChildHtml('product_info_bundle_options_top') ?>
            <?php foreach ($options as $option): ?>
                <?php if (!$option->getSelections()): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <?= $block->getOptionHtml($option) ?>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p>
            <?= $block->escapeHtml(__('No options of this product are available.')) ?>
        </p>
    <?php endif; ?>
<?php endif; ?>
