<?php /** @var $block \Amasty\GiftCard\Block\Product\View\Type\GiftCard */ ?>
<?php $_currencyShortName = $block->getCurrencyShortName(); ?>
<?php $_product = $block->getProduct(); ?>

<?php if ($_product->isSaleable() && $block->isConfigured($_product)): ?>
    <div
        class="fieldset"
        data-amgiftcard-js="amgiftcard-fieldset"
        data-mage-init='{ "amastyGiftCardMain": {
            "productId": "<?= $block->escapeJs($_product->getId()); ?>",
            "feeType": "<?= $block->escapeJs($_product->getAmGiftcardFeeType()); ?>",
            "feeValue": "<?= $block->escapeJs($block->getFeeAmount()); ?>"
          }
        }'
    >
        <?php if ($block->isMultiAmount() || $_product->getAmGiftcardPrices()): ?>
            <div class="field required">
                <label
                    class="label"
                    for="amgiftcard_amount"
                >
                    <?= $block->escapeHtml(__('Card Value in %1', $_currencyShortName)); ?>
                </label>
                <?php if ($block->isPredefinedAmount()): ?>
                    <div class="control">
                        <div class="select select--native">
                            <select
                                id="am_giftcard_amount"
                                name="am_giftcard_amount"
                                class="required-entry select__field"
                                data-amgiftcard-js="amgiftcard-amount"
                                data-mage-init='{"select": {}}'
                            >
                                <option value="">
                                    <?= $block->escapeHtml(__('Choose an Amount...')); ?>
                                </option>
                                <?php
                                $listAmounts = $block->getListAmounts();
                                $selectedAmount = $block->getDefaultAmount();
                                foreach ($listAmounts as $_amount): ?>
                                    <option
                                        data-value="<?= $block->escapeHtmlAttr($block->convertPrice($_amount)); ?>"
                                        value="<?= $block->escapeHtmlAttr($block->convertPrice($_amount)); ?>"
                                        data-amgiftcard-js="amgiftcard-amount-item"
                                        <?php if ($selectedAmount === $_amount): ?>
                                            selected
                                        <?php endif; ?>
                                        >
                                        <?= /* @noEscape */ $block->getFormatPrice($_amount); ?>
                                    </option>
                                <?php endforeach; ?>
                                <?php if ($_product->getAmAllowOpenAmount()): ?>
                                    <option value="custom">
                                        <?= $block->escapeHtml(__('Custom Amount')); ?>
                                    </option>
                                <?php endif; ?>
                            </select>
                        </div>

                        <?php if ($_product->getAmAllowOpenAmount()): ?>
                            <div
                                class="
                                    input
                                    <?php if ($block->isPredefinedAmount()): ?>
                                        display-none
                                    <?php endif; ?>
                                "
                                id="amgiftcard_amount_custom_block"
                                data-amgiftcard-js="amgiftcard-custom-amount-wrapper"
                            >
                                <?php $_min = $_max = 0;
                                if ($_product->getAmOpenAmountMin() || $_product->getAmOpenAmountMax()): ?>
                                    <?php $_min = $_product->getAmOpenAmountMin(); ?>
                                    <?php $_max = $_product->getAmOpenAmountMax(); ?>
                                    <input
                                        name="am_giftcard_amount_custom"
                                        class="
                                            input__field
                                            validate-number-range
                                            number-range-<?= $block->escapeHtmlAttr($block->round($block->convertPrice($_min)) . '-' . $block->round($block->convertPrice($_max))); ?>
                                            required-entry
                                            amgiftcard-min-amount
                                            amgiftcard-max-amount
                                        "
                                        value="<?= $block->escapeHtmlAttr($block->getDefaultValue('am_giftcard_amount_custom')); ?>"
                                        type="text"
                                        data-amgiftcard-js="amgiftcard-amount-custom"
                                    >
                                    <div class="margin-top-xs">
                                        <?php if ($_product->getAmOpenAmountMin()): ?>
                                            <?= $block->escapeHtml(__('Minimum: %1', $block->getFormatPrice($_min)));?>
                                        <?php endif; ?>

                                        <?php if ($_product->getAmOpenAmountMax()): ?>
                                            <?= $block->escapeHtml(__('Maximum: %1', $block->getFormatPrice($_max)));?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php if ($_product->getAmGiftcardType() == \Amasty\GiftCard\Model\GiftCard::TYPE_COMBINED): ?>
            <div class="field required">
                <label
                    for="am_giftcard_type"
                    class="label"
                >
                    <?= $block->escapeHtml(__('Choose card type')); ?>
                </label>
                <select
                    id="am_giftcard_type"
                    name="am_giftcard_type"
                    class="required-entry"
                    data-amgiftcard-js="amgiftcard-type"
                >
                    <option value="">
                        <?= $block->escapeHtml(__('-- Please Select --')); ?>
                    </option>
                    <?php foreach ($block->getListCardTypes() as $_cardType): ?>
                        <option
                            value="<?= $block->escapeHtmlAttr($_cardType['value']); ?>"
                            <?php if ($block->getDefaultValue('am_giftcard_type') == $_cardType['value']): ?>
                                selected
                            <?php endif; ?>
                        >
                            <?= $block->escapeHtml($_cardType['label']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <p class="note amgiftcard-delivery-info">
                    <?= $block->escapeHtml(__('Please be aware that printed gift card will be sent to the shipping address you specify during checkout.')); ?>
                </p>
            </div>
        <?php endif; ?>

        <?php if ($_images = $block->getImages()): ?>
            <div data-amgiftcard-js="amgiftcard-images">
                <div class="input required">
                    <label
                        for="am_giftcard_image"
                        class="label"
                    >
                        <?= $block->escapeHtml(__('Choose card Image')); ?>
                    </label>
                    <input
                        type="text"
                        name="am_giftcard_image"
                        class="amgiftcard-image-input required-entry"
                        value="<?= $block->escapeHtmlAttr($block->getDefaultValue('am_giftcard_image')); ?>"
                        data-amgiftcard-js="amgiftcard-image-input"
                    />
                </div>
                <?php foreach ($_images as $_image): ?>
                    <img
                        class="amgiftcard-image"
                        data-id="<?= $block->escapeHtmlAttr($_image->getId()) ?>"
                        src="<?= $block->escapeUrl($_image->getImageUrl()) ?>"
                        data-img-full-src="<?= $block->escapeUrl($_image->getImageUrl()); ?>"
                        data-amgiftcard-js="amgiftcard-image"
                    />
                <?php endforeach; ?>
                <?php if ($block->getAllowUsersUploadImages()): ?>
                    <div
                        class="
                            amgiftcard-image-container
                            -hidden
                            margin-top-xs
                        "
                    >
                        <div class="amgiftcard-image-wrapper">
                            <img
                                class="amgiftcard-userimage"
                                data-amgiftcard-js="amgiftcard-userimage"
                                alt="<?= $block->escapeHtmlAttr(__('Gift Card Image')) ?>"
                            />
                        </div>
                        <span
                            class="amgiftcard-close"
                            data-amgiftcard-js="amgiftcard-close"
                        ></span>
                    </div>
                    <div class="amgiftcard-browse-container margin-top-xs">
                        <div class="file-upload ">
                            <input
                                class="amgiftcard-image-input file-upload__input"
                                type="file"
                                id="amgiftcard-userimage-input"
                                name="amgiftcard-userimage-input"
                                accept=".jpg, .jpeg, .gif, .png"
                                data-amgiftcard-js="amgiftcard-userimage-input"
                            >
                            <label
                                class="file-upload__wrapper"
                                for="amgiftcard-userimage-input"
                            >
                                <span class="file-upload__label">
                                    <?= $block->escapeHtml(__('or upload your image')) ?>
                                </span>

                                <span
                                    class="button file-upload__button"
                                    role="button"
                                    tabindex="0"
                                    aria-controls="amgiftcard-userimage-input"
                                >
                                    <?= $block->escapeHtml(__('Browse')) ?>
                                </span>
                            </label>
                        </div>
                    </div>
                <p
                    class="amgiftcard-error"
                    data-amgiftcard-js="amgiftcard-userimage-error"
                ></p>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        <?php if ($block->isOptionEnable('am_giftcard_sender_name')): ?>
            <div class="input required">
                <label
                    for="am_giftcard_sender_name"
                    class="label"
                >
                    <?= $block->escapeHtml(__('Sender Name')); ?>
                </label>
                <input
                    type="text"
                    id="am_giftcard_sender_name"
                    name="am_giftcard_sender_name"
                    class="input__field required-entry"
                    value="<?= $block->escapeHtmlAttr($block->getDefaultValue('am_giftcard_sender_name')); ?>"
                />
            </div>
        <?php endif; ?>
        <?php if ($block->isOptionEnable('am_giftcard_sender_email')): ?>
            <div class="input required">
                <label
                    for="am_giftcard_sender_email"
                    class="label"
                >
                    <?= $block->escapeHtml(__('Sender Email')); ?>
                </label>
                <input
                    type="text"
                    id="am_giftcard_sender_email"
                    name="am_giftcard_sender_email"
                    class="
                        input__field
                        validate-email
                        required-entry
                    "
                    value="<?= $block->escapeHtmlAttr($block->getDefaultValue('am_giftcard_sender_email')); ?>"
                />
            </div>
        <?php endif; ?>
        <?php if ($_product->getAmGiftcardType() != \Amasty\GiftCard\Model\GiftCard::TYPE_PRINTED): ?>
            <?php if ($block->isOptionEnable('am_giftcard_recipient_name')): ?>
                <div
                    class="
                        input
                        required
                        am_giftcard_recipient_data
                    "
                    data-amgiftcard-js="amgiftcard-recipient-data"
                >
                    <label
                        for="am_giftcard_recipient_name"
                        class="label"
                    >
                        <?= $block->escapeHtml(__('Recipient Name')); ?>
                    </label>
                    <input
                        type="text"
                        id="am_giftcard_recipient_name"
                        name="am_giftcard_recipient_name"
                        class="input__field required-entry"
                        value="<?= $block->escapeHtmlAttr($block->getDefaultValue('am_giftcard_recipient_name')); ?>"
                    />
                </div>
            <?php endif; ?>
            <div
                class="
                    input
                    required
                    am_giftcard_recipient_data
                "
                data-amgiftcard-js="amgiftcard-recipient-data"
            >
                <label
                    for="am_giftcard_recipient_email"
                    class="label"
                >
                    <?= $block->escapeHtml(__('Recipient Email')); ?>
                </label>
                <input
                    type="text"
                    id="am_giftcard_recipient_email"
                    name="am_giftcard_recipient_email"
                    class="
                        input__field
                        validate-email
                        required-entry
                    "
                    value="<?= $block->escapeHtmlAttr($this->getDefaultValue('am_giftcard_recipient_email')); ?>"
                />
            </div>
        <?php endif; ?>

        <?php if ($block->isOptionEnable('am_giftcard_date_delivery')): ?>
            <div class="field required">
                <label
                    for="am_giftcard_date_delivery"
                    class="label"
                >
                    <?= $block->escapeHtml(__('Date of Certificate Delivery')); ?>
                </label>
                <input
                    name="am_giftcard_date_delivery"
                    id="am_giftcard_date_delivery"
                    value="<?= $block->escapeHtmlAttr($block->getDefaultValue('am_giftcard_date_delivery')); ?>"
                    class="
                        required-entry
                        datetime-picker
                        validate-date date
                    "
                    type="text"
                    data-amgiftcard-js="amgiftcard-delivery-date"
                >
                <p
                    class="amgiftcard-delivery-info display-none"
                    data-amgiftcard-js="amgiftcard-delivery-info"
                >
                    <?=
                        $block->escapeHtml(
                            __('Please be aware that delivery date of printed certificates may be different due to post.')
                        );
                    ?>
                </p>
            </div>
            <div class="field required">
                <label
                    for="am_giftcard_date_delivery_timezone"
                    class="label"
                >
                    <?= $block->escapeHtml(__('Select timezone')); ?>
                </label>
                <select
                    class="required-entry"
                    name="am_giftcard_date_delivery_timezone"
                    id="am_giftcard_date_delivery_timezone"
                >
                    <option value=""></option>
                    <?php foreach ($block->getListTimezones() as $_timezone): ?>
                        <option
                            value="<?= $block->escapeHtmlAttr($_timezone['value']); ?>"
                            <?php if ($block->getDefaultValue('am_giftcard_date_delivery_timezone') == $_timezone['value']): ?>
                                selected
                            <?php endif; ?>
                        >
                            <?= $block->escapeHtml($_timezone['label']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        <?php endif; ?>

        <?php if ($block->isOptionEnable(\Amasty\GiftCard\Model\Options::GIFT_MESSAGE)): ?>
            <div class="input">
                <label
                    for="am_giftcard_message"
                    class="label"
                >
                    <?= $block->escapeHtml(__('Message')); ?>
                </label>
                <textarea
                    name="am_giftcard_message"
                    id="am_giftcard_message"
                    class="input__field input__field--textarea"
                    cols="5"
                    rows="3"
                ><?= $block->escapeHtml($block->getDefaultValue('am_giftcard_message')); ?></textarea>
            </div>
        <?php endif; ?>

        <div class="amgiftcard-preview">
            <button
                title="<?= $block->escapeHtmlAttr(__('Preview Gift Card')) ?>"
                class="button button--secondary"
                data-amgiftcard-js="amgiftcard-preview"
                disabled
            >
                <?= $block->escapeHtml(__('Preview Gift Card')) ?>
            </button>
        </div>

        <script>
            require([
                'jquery',
                "mage/calendar",
                "mage/tooltip"
            ], function ($) {
                if ($('[data-amgiftcard-js="amgiftcard-delivery-date"]')) {
                    $('[data-amgiftcard-js="amgiftcard-delivery-date"]').calendar({
                        showTime: false,
                        minDate: new Date(),
                    });
                }

                $('[data-amgiftcard-js="info-tooltip"]').tooltip({
                    position: {
                        my: "left bottom",
                        at: "right top",
                        collision: "flipfit flipfit"

                    },
                    tooltipClass: "amgiftcard-tooltip",
                    content: "<?= $block->escapeHtml(__($block->getTooltipContent())); ?>"
                });
            });
        </script>
    </div>
<?php endif; ?>
