<li
    class="list__item list__item--compare"
    data-bind="scope: 'compareProducts'"
    data-role="compare-products-link"
>
    <a
        title="<?= $block->escapeHtmlAttr(__('Compare Products')) ?>"
        class="list__link compare-link"
        data-bind="attr: {'href': compareProducts().listUrl}, css: {'no-display': !compareProducts().count}"
    >
        <?= $block->escapeHtml(__('Compare Products')) ?>
        <span
            class="compare-link__qty"
            data-bind="text: compareProducts().countCaption"
        ></span>
    </a>
</li>
<script type="text/x-magento-init">
    {
        "[data-role=compare-products-link]": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout(); ?>
        }
    }
</script>
