<li class="links-list__item links-list__item--compare"
    data-bind="scope: 'compareProducts'"
    data-role="compare-products-link"
>
    <a class="links-list__link compare-link"
       title="<?php /* @escapeNotVerified */ echo __('Compare Products') ?>"
       data-bind="attr: {'href': compareProducts().listUrl}, css: {'no-display': !compareProducts().count}"
    >
        <?php /* @escapeNotVerified */ echo __('Compare Products') ?>
        <span class="compare-link__qty"
              data-bind="text: compareProducts().countCaption"
        >
        </span>
    </a>
</li>
<script type="text/x-magento-init">
    {"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>
