<?php
// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$taxDataHelper = $this->helper(Magento\Tax\Helper\Data::class);
?>
<tbody class="cart item">
    <tr role="row">
        <td
            data-th="<?= $block->escapeHtmlAttr(__('Item:')) ?>"
            role="gridcell"
        >
            <div class="row middle-sm">
                <div class="paypal-review__product-image margin-right-m">
                    <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                </div>
                <div class="paypal-review__product-details">
                    <span>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    </span>
                    <?php if ($_options = $block->getOptionList()) :?>
                        <dl class="item-options">
                            <?php foreach ($_options as $_option) :?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <dt>
                                    <?= $block->escapeHtml($_option['label']) ?>
                                </dt>
                                <dd>
                                    <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                        <?= /* @noEscape */ $_formatedOptionValue['full_view'] ?>
                                    <?php else :?>
                                        <?= /* @noEscape */ $_formatedOptionValue['value'] ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif;?>
                    <?php if ($addtInfoBlock = $block->getProductAdditionalInformationBlock()) :?>
                        <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif;?>
                </div>
            </div>
        </td>
        <td
            data-th="<?= $block->escapeHtmlAttr(__('Price:')) ?>"
            role="gridcell"
        >
            <?php if ($taxDataHelper->displayCartPriceInclTax() || $taxDataHelper->displayCartBothPrices()) :?>
                <span
                    class="price-including-tax"
                    data-label="<?= $block->escapeHtmlAttr(__('Incl. Tax')) ?>"
                >
                    <?= $block->getUnitPriceInclTaxHtml($_item) ?>
                </span>
            <?php endif; ?>
            <?php if ($taxDataHelper->displayCartPriceExclTax() || $taxDataHelper->displayCartBothPrices()) :?>
                <span
                    class="price-excluding-tax"
                    data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>"
                >
                    <?= $block->getUnitPriceExclTaxHtml($_item) ?>
                </span>
            <?php endif; ?>
        </td>
        <td
            data-th="<?= $block->escapeHtmlAttr(__('Qty:')) ?>"
            role="gridcell"
        >
            <span class="qty">
                <?= $block->escapeHtml($_item->getQty()) ?>
            </span>
        </td>
        <td
            data-th="<?= $block->escapeHtmlAttr(__('Subtotal:')) ?>"
            role="gridcell"
        >
            <?php if ($taxDataHelper->displayCartPriceInclTax() || $taxDataHelper->displayCartBothPrices()) :?>
                <span
                    class="price-including-tax"
                    data-label="<?= $block->escapeHtmlAttr(__('Incl. Tax:')) ?>"
                >
                    <?= $block->getRowTotalInclTaxHtml($_item) ?>
                </span>
            <?php endif; ?>
            <?php if ($taxDataHelper->displayCartPriceExclTax() || $taxDataHelper->displayCartBothPrices()) :?>
                <span
                    class="price-excluding-tax"
                    data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax:')) ?>"
                >
                    <?= $block->getRowTotalExclTaxHtml($_item) ?>
                </span>
            <?php endif; ?>
        </td>
    </tr>
</tbody>
