<?php
$pageTitle = $this->getChildHtml('page.main.title');
$categoryImage = $this->getChildHtml('category.image');
$categoryDescription = $this->getChildHtml('category.description');
$categoryCms = $this->getChildHtml('category.cms');
?>
<?php if ($categoryDescription): ?>
    <div
        class="
            banner
            banner--category
            catalog-list__banner
            <?php if ($categoryImage) : ?>
                banner--category-image
            <?php endif; ?>
        "
        data-mage-init='{ "bannerCollapsible": {} }'
    >
        <div class="banner__wrapper">
            <div class="banner__image-wrapper">
                <?php if ($categoryImage) : ?>
                    <?= $categoryImage ?>
                <?php endif; ?>
            </div>

            <div class="banner__heading-wrapper">
                <div class="banner__heading">
                    <?= $pageTitle ?>
                </div>
                <button
                    class="
                        button
                        button--icon
                        banner__button
                        banner__button-collapse
                    "
                    type="button"
                    aria-label="<?= $block->escapeHtmlAttr(__('check category description')) ?>"
                    aria-expanded="false"
                >
                    <span class="button__text banner__button-text">
                        <?= __('More information') ?>
                    </span>

                    <svg
                        class="icon banner__button-icon"
                        role="presentation"
                        focusable="false"
                    >
                        <title><?= __('Arrow down') ?></title>
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-down')) ?>"></use>
                    </svg>
                </button>
            </div>
        </div>

        <div
            class="banner__content--category"
            tabindex="-1"
            aria-hidden="true"
        >
            <?= $categoryDescription ?>

            <div class="banner__actions-wrapper">
                <button
                    class="
                        button
                        button--icon
                        banner__button
                        banner__button-close
                        margin-vc-xs
                    "
                    type="button"
                    aria-label="<?= $block->escapeHtmlAttr(__('hide details')) ?>"
                >
                    <span class="button__text banner__button-text">
                        <?= __('Hide details') ?>
                    </span>

                    <svg
                        class="icon banner__button-icon margin-right-m"
                        role="presentation"
                        focusable="false"
                    >
                        <title><?= __('Arrow down') ?></title>
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-up')) ?>"></use>
                    </svg>
                </button>
            </div>
        </div>
    </div>
<?php else: ?>
    <?= $pageTitle ?>
<?php endif; ?>

<?= $categoryCms ?>
