<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php $descriptionBottom = $block->getCurrentCategory()->getCategoryTextBottom(); ?>
<?php if ($descriptionBottom): ?>
    <div class="catalog-list__category-description">
        <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
            $block->getCurrentCategory(),
            $descriptionBottom,
            'category_text_bottom'
        ) ?>
    </div>
<?php endif; ?>
