<?php $_items = $block->getItems(); ?>
<?php if (count($_items)): ?>
    <div class="dashboard-table">
        <div class="dashboard-table__header">
            <h3 class="dashboard-table__title">
                <?= __('My Downloadable Products') ?>
            </h3>
        </div>

        <div class="dashboard-table__content">
            <table
                id="my-downloadable-products-table"
                class="table dashboard-table__table"
            >
                <thead>
                    <tr>
                        <th scope="col" class="id">
                            <?= __('Order #') ?>
                        </th>

                        <th scope="col" class="date">
                            <?= __('Date') ?>
                        </th>

                        <th scope="col" class="title">
                            <?= __('Title') ?>
                        </th>

                        <th scope="col" class="status">
                            <?= __('Status') ?>
                        </th>

                        <th scope="col" class="remaining">
                            <?= __('Remaining Downloads') ?>
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($_items as $_item): ?>
                        <?php
                            $getOrderId = $block->getOrderViewUrl($_item->getPurchased()->getOrderId());
                        ?>

                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="id">
                                <a href="<?= $getOrderId ?>"
                                   title="<?= $block->escapeHtml(__('View Order')) ?>"
                                >
                                    <?= $_item->getPurchased()->getOrderIncrementId() ?>
                                </a>
                            </td>

                            <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="date">
                                <?= $block->formatDate($_item->getPurchased()->getCreatedAt()) ?>
                            </td>

                            <td data-th="<?= $block->escapeHtml(__('Title')) ?>" class="title">
                                <strong class="product-name">
                                    <?= $block->escapeHtml($_item->getPurchased()->getProductName()) ?>
                                </strong>

                                <?php $linkStatus = \Magento\Downloadable\Model\Link\Purchased\Item::LINK_STATUS_AVAILABLE; ?>

                                <?php if ($_item->getStatus() == $linkStatus): ?>
                                    <?php
                                        $clickFunction = $block->getIsOpenInNewWindow() ? 'onclick="this.target=\'_blank\'"' : '';
                                    ?>

                                    <a href="<?= $block->getDownloadUrl($_item) ?>"
                                       title="<?= $block->escapeHtml(__('Start Download')) ?>"
                                       class="link download"
                                       <?= $clickFunction; ?>
                                    >
                                        <?= $block->escapeHtml($_item->getLinkTitle()) ?>
                                    </a>
                                <?php endif; ?>
                            </td>

                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="status">
                                <?= __(ucfirst($_item->getStatus())) ?>
                            </td>

                            <td data-th="<?= $block->escapeHtml(__('Remaining Downloads')) ?>"
                                class="remaining"
                            >
                                <?= $block->getRemainingDownloads($_item) ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <?php if ($block->getChildHtml('pager')): ?>
        <?= $block->getChildHtml('pager'); ?>
    <?php endif; ?>

<?php else: ?>
    <div class="message info empty">
        <?= __('You have not purchased any downloadable products yet.'); ?>
    </div>
<?php endif; ?>

<div class="action">
    <div class="action__handler">
        <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
           class="link action__link"
        >
            <?= __('Back') ?>
        </a>
    </div>
</div>
