<?php
use Magento\Downloadable\Model\Link\Purchased\Item;

/**
 * @var $block \Magento\Downloadable\Block\Customer\Products\ListProducts
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php $_items = $block->getItems(); ?>
<?php if (count($_items)): ?>
    <div class="dashboard-table">
        <div class="dashboard-table__header">
            <h2 class="heading dashboard-table__title">
                <?= $block->escapeHtml(__('Downloadable Products')) ?>
            </h2>
        </div>
        <div class="dashboard-table__content">
            <table
                class="table"
                tabindex="0"
                role="table"
            >
                <caption class="table__caption">
                    <?= $block->escapeHtml(__('Downloadable Products')) ?>
                </caption>
                <thead>
                    <tr role="row">
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Order #')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Date')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Title')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Status')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Remaining Downloads')) ?>
                        </th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($_items as $_item): ?>
                    <tr role="row">
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>"
                            role="gridcell"
                        >
                            <a
                                href="<?= $block->escapeUrl($block->getOrderViewUrl($_item->getPurchased()->getOrderId())) ?>"
                                title="<?= $block->escapeHtmlAttr(__('View Order')) ?>"
                                class="link dashboard-table__link"
                            >
                                <?= $block->escapeHtml($_item->getPurchased()->getOrderIncrementId()) ?>
                            </a>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>"
                            role="gridcell"
                        >
                            <?= /* @noEscape */ $block->formatDate($_item->getPurchased()->getCreatedAt()) ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Title')) ?>"
                            role="gridcell"
                        >
                            <strong class="product-name">
                                <?= $block->escapeHtml($_item->getPurchased()->getProductName()) ?>
                            </strong>
                            <?php if ($_item->getStatus() == Item::LINK_STATUS_AVAILABLE): ?>
                                <a
                                    href="<?= $block->escapeUrl($block->getDownloadUrl($_item)) ?>"
                                    id="download_<?= /* @noEscape */ $_item->getPurchased()->getProductId() ?>"
                                    title="<?= $block->escapeHtmlAttr(__('Start Download')) ?>"
                                    class="action download"
                                >
                                    <?= $block->escapeHtml($_item->getLinkTitle()) ?>
                                </a>

                                <?php if ($block->getIsOpenInNewWindow()): ?>
                                    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                                        'onclick',
                                        "this.target='_blank'",
                                        'a#download_' . $_item->getPurchased()->getProductId()
                                    ) ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>"
                            role="gridcell"
                        >
                            <?= $block->escapeHtml(__(ucfirst($_item->getStatus()))) ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Remaining Downloads')) ?>"
                            role="gridcell"
                        >
                            <?= $block->escapeHtml($block->getRemainingDownloads($_item)) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if ($block->getChildHtml('pager')): ?>
        <?= $block->getChildHtml('pager') ?>
    <?php endif; ?>
<?php else: ?>
    <div class="message">
        <?= $block->escapeHtml(__('You have not purchased any downloadable products yet.')) ?>
    </div>
<?php endif; ?>

<div class="actions-group margin-top-l">
    <div class="actions-group__handler">
        <a
            href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
            class="link actions-group__link"
        >
            <?= $block->escapeHtml(__('Back')) ?>
        </a>
    </div>
</div>
