<?php $_order = $block->getOrder() ?>

<div class="dashboard-table dashboard-table--tab">
    <div class="dashboard-table__header">
        <h3 class="dashboard-table__title">
            <?= $block->escapeHtml(__('Invoice #')) ?>
            <?= $_order->getIncrementId(); ?>
        </h3>

        <a href="<?= $block->escapeUrl($block->getPrintAllInvoicesUrl($_order)) ?>"
           class="link dashboard-table__link"
           target="_blank"
           rel="noopener"
        >
            <?= $block->escapeHtml(__('Print All Invoices')) ?>
        </a>
    </div>

    <?php foreach ($_order->getInvoiceCollection() as $_invoice): ?>
        <div class="dashboard-table__content">
            <table
                class="table dashboard-table__table"
                id="my-invoice-table-<?= (int) $_invoice->getId() ?>"
            >
                <thead>
                    <tr>
                        <th class="name">
                            <?= $block->escapeHtml(__('Product Name')) ?>
                        </th>

                        <th class="sku">
                            <?= $block->escapeHtml(__('SKU')) ?>
                        </th>

                        <th class="price">
                            <?= $block->escapeHtml(__('Price')) ?>
                        </th>

                        <th class="qty">
                            <?= $block->escapeHtml(__('Qty Invoiced')) ?>
                        </th>

                        <th class="subtotal">
                            <?= $block->escapeHtml(__('Subtotal')) ?>
                        </th>
                    </tr>
                </thead>

                <?php $_items = $_invoice->getAllItems(); ?>
                <?php $_count = count($_items) ?>

                <?php foreach ($_items as $_item): ?>
                    <?php if ($_item->getOrderItem()->getParentItem()): continue; endif; ?>

                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endforeach; ?>

                <tfoot>
                    <?= $block->getInvoiceTotalsHtml($_invoice) ?>
                </tfoot>
            </table>
        </div>

        <?= $block->getInvoiceCommentsHtml($_invoice) ?>
    <?php endforeach; ?>
</div>
