<?php /** @var $block \Magento\Framework\Pricing\Render\Amount */ ?>

<span
    class="price-container <?= $block->escapeHtmlAttr($block->getAdjustmentCssClasses()) ?>"
    <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>
>
    <span
        <?php if ($block->getPriceId()): ?>
            id="<?= $block->escapeHtmlAttr($block->getPriceId()) ?>"
        <?php endif;?>
        <?php if ($block->getDisplayLabel()): ?>
            data-label="<?= $block->escapeHtmlAttr($block->getDisplayLabel() . $block->getDisplayInclExclTaxes()) ?>"
            aria-label="<?= $block->escapeHtmlAttr($block->getDisplayLabel() . $block->getDisplayInclExclTaxes()) ?>"
        <?php endif; ?>
        data-price-amount="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>"
        data-price-type="<?= $block->escapeHtmlAttr($block->getPriceType()) ?>"
        class="<?= $block->escapeHtmlAttr($block->getPriceWrapperCss()) ?>"
    >
        <?= $block->escapeHtml($block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()), ['span']) ?>
    </span>
    <?php if ($block->hasAdjustmentsHtml()) :?>
        <?= $block->getAdjustmentsHtml() ?>
    <?php endif; ?>
    <?php if ($block->getSchema()): ?>
        <meta
            itemprop="price"
            content="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>"
        />
        <meta
            itemprop="priceCurrency"
            content="<?= $block->escapeHtmlAttr($block->getDisplayCurrencyCode()) ?>"
        />
    <?php endif; ?>
</span>
