<?php
// @codingStandardsIgnoreFile
/** @var $block Magento\Company\Block\Company\Management\Info */
?>
<?php if ($block->hasCustomerCompany() && $block->isUserEditAllowed()): ?>
    <div class="dashboard-items">
        <div class="grid dashboard-items__content">
            <div class="dashboard-items__item">
                <div class="action">
                    <div class="action__handler">
                        <button
                            type="button"
                            title="<?= $block->escapeHtml(__('Add New User')) ?>"
                            class="button action__button"
                            data-mage-init='{
                                "Magento_Company/js/user-edit": {
                                    "gridProvider": "company_users_listing.company_users_listing_data_source"
                                }
                            }'
                            data-mobile-label="<?= /* @noEscape */ $block->escapeHtml(__('Add New User')) ?>"
                        >
                            <?= $block->escapeHtml(__('Add New User')) ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>
