<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block Magento\Company\Block\Company\Management\Info */
?>
<?php if ($block->hasCustomerCompany() && $block->isUserEditAllowed()) : ?>
    <div class="actions">
        <button type="button"
                title="<?= $block->escapeHtml(__('Add New User')) ?>"
                class="action primary"
                data-mage-init='{"Magento_Company/js/user-edit":{"gridProvider":"company_users_listing.company_users_listing_data_source"}}'
                data-mobile-label="<?= /* @noEscape */ $block->escapeHtml(__('Add New User')) ?>">
            <span><?= $block->escapeHtml(__('Add New User')) ?></span>
        </button>
    </div>
<?php endif; ?>
