<?php /** @var \Snowdog\Menu\Block\NodeType\CmsPage $block */ ?>
<?php
    $nodeId = $block->getId();
    $class = $block->getMenuClass();
    $pageUrl = $block->getPageUrl($nodeId);
    $pageUrl = $pageUrl ?: '#';
    $dataAttribute = '';

    $classLink = $block->getIsRoot() ? $class . '__label' : 'link footer__link';
    $title = $block->getTitle();

    if ($nodeId) {
        $dataAttribute = ' aria-controls="dropdown-' . $nodeId . '"';
    }

    if ($block->isCurrentPage($nodeId)) {
        $classLink .= ' footer__link--current';
    }
?>

<?php if ($block->getIsRoot()): ?>
    <button
        type="button"
        class="<?= $block->escapeHtmlAttr($classLink) ?>"
        <?=  /* @noEscape */ $dataAttribute ?>
    >
        <?= $block->escapeHtml($title) ?>
        <svg
            class="dropdown-list__icon"
            role="presentation"
            focusable="false"
        >
            <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-down')) ?>"></use>
        </svg>
    </button>
<?php else: ?>
    <a
        href="<?= $block->escapeUrl($pageUrl) ?>"
        class="<?= $block->escapeHtmlAttr($classLink) ?>"
    >
        <?= $block->escapeHtml($title) ?>
    </a>
<?php endif; ?>
