<?php /** @var \Snowdog\Menu\Block\NodeType\CustomUrl $block */ ?>
<?php
    $attributes = [];
    $class = $block->getMenuClass();
    $classLink = $block->getIsRoot() ? $class . '__label' : 'link footer__link';
    $title = $block->getTitle();
    $content = $block->getContent();
    if ($block->getId()) {
        $attributes[] = 'aria-controls="dropdown-' . $block->getId() . '"';
    }

    $attributes[] = 'class="' . $classLink . '"';

    if ($block->getTarget()) {
        $attributes[] = 'target="__blank" rel="noopener"';
    }
?>

<?php if ($block->getIsRoot()): ?>
    <button
        type="button"
        <?= /* @noEscape */ implode(' ', $attributes) ?>
    >
        <?= $block->escapeHtml($title) ?>
        <svg
            class="dropdown-list__icon"
            role="presentation"
            focusable="false"
        >
            <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#angle-down')) ?>"></use>
        </svg>
    </button>
<?php else: ?>
    <a
        <?php if ($content): ?>
            href="<?= $block->escapeUrl($content) ?>"
        <?php endif; ?>
        class="<?= $block->escapeHtmlAttr($classLink) ?>"
    >
        <?= $block->escapeHtml($title) ?>
    </a>
<?php endif; ?>
