<div class="information">
    <h5 class="heading heading--fifth-level information__title">
        <?= /* @escapeNotVerified */ __('Balance'); ?>
    </h5>

    <p class="information__text">
        <span>
            <?= /* @escapeNotVerified */ __('Your balance is:'); ?>
        </span>
        
        <strong>
            <?= /* @escapeNotVerified */ 
                $this->helper('Magento\Framework\Pricing\Helper\Data')
                     ->currency($block->getBalance()); 
            ?>
        </strong>
    </p>
</div>
