<div class="information">
    <h5 class="heading heading--fifth-level information__title">
        <?php /* @escapeNotVerified */ echo __('Balance'); ?>
    </h5>

    <p class="information__text">
        <span>
            <?php /* @escapeNotVerified */ echo __('Your balance is:'); ?>
        </span>
        
        <strong>
            <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($block->getBalance()); ?>
        </strong>
    </p>
</div>
