<?php if ($block->canShow() && $block->getEvents() && count($block->getEvents())): ?>
<div class="dashboard-table ">
    <div class="dashboard-table__header">
        <h5 class="heading heading--fifth-level dashboard-table__title">
            <?php /* @escapeNotVerified */ echo __('Balance History'); ?>
        </h5>
    </div>

    <div class="dashboard-table__content">
        <table id="customerbalance-history" class="table dashboard-table__table">
            <thead>
                <tr>
                    <th scope="col" class="col actions">
                        <?php /* @escapeNotVerified */ echo __('Action'); ?>
                    </th>

                    <th scope="col" class="col change">
                        <?php /* @escapeNotVerified */ echo __('Balance Change'); ?>
                    </th>

                    <th scope="col" class="col balance">
                        <?php /* @escapeNotVerified */ echo __('Balance'); ?>
                    </th>

                    <th scope="col" class="col date">
                        <?php /* @escapeNotVerified */ echo __('Date'); ?>
                    </th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($block->getEvents() as $event): ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Action')); ?>" class="col actions">
                            <?php /* @escapeNotVerified */ echo $block->getActionLabel($event->getAction()); ?>
                        </td>

                        <td data-th="<?php echo $block->escapeHtml(__('Balance Change')); ?>" class="col change">
                            <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($event->getBalanceDelta()); ?>
                        </td>

                        <td data-th="<?php echo $block->escapeHtml(__('Balance')); ?>" class="col balance">
                            <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($event->getBalanceAmount()); ?>
                        </td>

                        <td data-th="<?php echo $block->escapeHtml(__('Date')); ?>" class="col date">
                            <?php /* @escapeNotVerified */ echo $block->formatDate($event->getUpdatedAt(), \IntlDateFormatter::SHORT, true); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php endif; ?>
