<?php
$blockCanShow   = $block->canShow();
$blockGetEvents = $block->getEvents();
?>

<?php if ($blockCanShow && $blockGetEvents && count($blockGetEvents)): ?>
<div class="dashboard-table ">
    <div class="dashboard-table__header">
        <h3 class="dashboard-table__title">
            <?= $escaper->escapeHtml(__('Balance History')); ?>
        </h3>
    </div>

    <div class="dashboard-table__content">
        <table
            id="customerbalance-history"
            class="table dashboard-table__table"
        >
            <thead>
                <tr>
                    <th scope="col" class="col actions">
                        <?= $escaper->escapeHtml(__('Action')); ?>
                    </th>

                    <th scope="col" class="col change">
                        <?= $escaper->escapeHtml(__('Balance Change')); ?>
                    </th>

                    <th scope="col" class="col balance">
                        <?= $escaper->escapeHtml(__('Balance')); ?>
                    </th>

                    <th scope="col" class="col date">
                        <?= $escaper->escapeHtml(__('Date')); ?>
                    </th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($block->getEvents() as $event): ?>
                    <?php
                        $getBalanceDelta  = $this->helper('Magento\Framework\Pricing\Helper\Data')
                                                 ->currency($event->getBalanceDelta());
                        $getBalanceAmount = $this->helper('Magento\Framework\Pricing\Helper\Data')
                                                 ->currency($event->getBalanceAmount());
                        $getFormDate      = $block->formatDate($event->getUpdatedAt(), \IntlDateFormatter::SHORT, true);
                    ?>

                    <tr>
                        <td data-th="<?= $escaper->escapeHtmlAttr(__('Action')); ?>" class="col actions">
                            <?= $block->getActionLabel($event->getAction()); ?>
                        </td>

                        <td data-th="<?= $escaper->escapeHtmlAttr(__('Balance Change')); ?>" class="col change">
                            <?= $getBalanceDelta ?>
                        </td>

                        <td data-th="<?= $escaper->escapeHtmlAttr(__('Balance')); ?>" class="col balance">
                            <?= $getBalanceAmount ?>
                        </td>

                        <td data-th="<?= $escaper->escapeHtmlAttr(__('Date')); ?>" class="col date">
                            <?= $getFormDate ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
