<?php /* @var $block \Amasty\GiftCard\Block\Checkout\Cart\GiftCard */ ?>
<?php if ($block->isEnableGiftFormInCart()): ?>
    <div
        class="cart-discount"
        data-mage-init='{
            "collapsible":{
                "openedState": "active",
                "saveState": false
            }
        }'
    >
        <button
            class="cart-discount__button"
            type="button"
            aria-expanded="false"
            data-role="title"
        >
            <span
                class="cart-discount__button-text"
                data-testid="apply-gift-card-title"
            >
                <?= $block->escapeHtml(__('Apply Gift Card Code')) ?>
            </span>

            <svg
                class="icon cart-discount__button-icon"
                role="presentation"
                focusable="false"
            >
                <use xlink:href="
                    <?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#angle-down')) ?>
                "></use>
            </svg>
        </button>


        <div
            class="cart-discount__content"
            data-role="content"
            aria-hidden="true"
        >
            <div
                class="margin-top-s"
                data-amgiftcard-js="amgiftcard-info">
            </div>

            <form
                id="amgiftcard-form-post"
                method="post"
                data-amgiftcard-js="amgiftcard-form-post"
            >
                <?php $getAppliedCodes = $block->getAppliedCodes(); ?>

                <?php if (count($getAppliedCodes)): ?>
                    <?php foreach ($getAppliedCodes as $code): ?>
                        <div>
                            <?= $block->escapeHtml($code->getCode()) ?>

                            <a
                                class="
                                    button
                                    button--link
                                    padding-hz-m
                                    margin-left-xs
                                "
                                href="javascript:void(0);"
                                data-href="
                                    <?= $block->escapeUrl($block->getUrl(
                                        'amgiftcard/cart/remove',
                                        ['code_id' => $code->getCodeId()]
                                    )) ?>
                                "
                                title="<?= $block->escapeHtmlAttr(__('Remove')) ?>"
                                data-amgiftcard-js="amgiftcard-remove"
                            >
                                <?= $block->escapeHtml(__('Remove')) ?>
                            </a>
                        </div>
                    <?php endforeach; ?>
                <?php endif;?>
            </form>

            <form
                id="amgiftcard-form"
                class="amgiftcard-form"
                action="<?= $block->escapeUrl($block->getUrl('amgiftcard/cart/apply')) ?>"
                method="post"
                data-amgiftcard-js="amgiftcard-form"
                data-mage-init='{
                    "discountCode":{
                        "couponCodeSelector": "#coupon_code",
                        "removeCouponSelector": "#remove-amgiftcard",
                        "applyButtonGift": "button.action.apply"
                    }
                }'
            >
                <input
                    type="hidden"
                    name="remove"
                    id="remove-amgiftcard"
                    value="0"
                />

                <div class="cart-discount__controls padding-top-s">
                    <div class="input cart-discount__content-input">
                        <?php
                            $enterGiftCardLabel = __('Enter gift card code');
                        ?>
                        <label
                            for="am_giftcard_code"
                            class="
                                label
                                label--hidden
                                input__label
                            "
                        >
                            <?= $block->escapeHtml($enterGiftCardLabel) ?>
                        </label>

                        <input
                            id="am_giftcard_code"
                            type="text"
                            name="am_giftcard_code"
                            value=""
                            class="input__field cart-discount__content-field"
                            placeholder="<?= $block->escapeHtmlAttr($enterGiftCardLabel) ?>"
                            data-validate="{required:true}"
                        >
                    </div>
                    <?php
                        $addGiftCartLabel = __('Add Gift Card');
                    ?>
                    <button
                        class="button cart-discount__content-button"
                        type="submit"
                        value="<?= $block->escapeHtmlAttr($addGiftCartLabel) ?>"
                    >
                        <?= $block->escapeHtml($addGiftCartLabel) ?>
                    </button>
                </div>
                <?php
                    $checkGiftCartLabel = __('Check Gift Card status');
                ?>
                <button
                    type="button"
                    class="button"
                    value="<?= $block->escapeHtmlAttr($checkGiftCartLabel) ?>"
                    data-amgiftcard-js="amgiftcard-check-status"
                >
                    <?= $block->escapeHtml($checkGiftCartLabel) ?>
                </button>

                <script>
                    require([
                        'jquery',
                        'Amasty_GiftCard/js/cart/main'
                    ], function ($) {
                        $('[data-amgiftcard-js="amgiftcard-check-status"]').amGiftcardCart({
                            checkCardUrl: "<?= $block->escapeUrl($block->getUrl('amgiftcard/cart/check')) ?>"
                        });
                    });
                </script>
            </form>
        </div>
    </div>
<?php endif; ?>
