<?php /* @var $block \Amasty\GiftCard\Block\Checkout\Cart\GiftCard */ ?>
<?php if ($block->isEnableGiftFormInCart()): ?>
    <div
        data-mage-init='{
            "collapsible":{
                "openedState": "active",
                "saveState": false
            }
        }'
    >
        <button
            class="cart-discount__button"
            type="button"
            aria-expanded="false"
            data-role="title"
        >
            <span
                class="cart-discount__button-text"
                data-testid="apply-discount-title"
            >
                <?= $block->escapeHtml(__('Apply Gift Card Code')) ?>
            </span>

            <svg class="icon cart-discount__button-icon" role="img">
                <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#angle-down') ?>"></use>
            </svg>
        </button>


        <div
            class="cart-discount__content"
            data-role="content"
            aria-hidden="true"
        >
            <div data-amgiftcard-js="amgiftcard-info"></div>

            <form
                id="amgiftcard-form-post"
                method="post"
                data-amgiftcard-js="amgiftcard-form-post"
            >
                <?php $getAppliedCodes = $block->getAppliedCodes(); ?>

                <?php if (count($getAppliedCodes)) : ?>
                    <?php foreach ($getAppliedCodes as $code) : ?>
                        <div>
                            <?= $code->getCode();?>

                            <a
                                class="btn-remove btn-remove-amgiftcard"
                                href="javascript:void(0);"
                                data-href="
                                    <?= $block->getUrl(
                                        'amgiftcard/cart/remove',
                                        [ 'code_id' => $code->getCodeId() ]
                                    )?>
                                "
                                title="Remove"
                                data-amgiftcard-js="amgiftcard-remove"
                            >
                                <?= $block->escapeHtml(__('Remove')); ?>
                            </a>
                        </div>
                    <?php endforeach; ?>
                <?php endif;?>
            </form>

            <form
                id="amgiftcard-form"
                class="amgiftcard-form"
                action="<?= $block->getUrl('amgiftcard/cart/apply') ?>"
                method="post"
                data-amgiftcard-js="amgiftcard-form"
                data-mage-init='{
                    "discountCode":{
                        "couponCodeSelector": "#coupon_code",
                        "removeCouponSelector": "#remove-amgiftcard",
                        "applyButtonGift": "button.action.apply"
                    }
                }'
            >
                <input type="hidden" name="remove" id="remove-amgiftcard" value="0" />

                <div class="cart-discount__controls">
                    <div class="input cart-discount__content-input">
                        <label
                            for="coupon_code"
                            class="label label--hidden input__label"
                        >
                            <?= $block->escapeHtml(__('Enter gift card code')) ?>
                        </label>

                        <input
                            id="am_giftcard_code"
                            type="text"
                            name="am_giftcard_code"
                            value=""
                            class="input__field cart-discount__content-field"
                            placeholder="<?= $block->escapeHtml(__('Enter gift card code'));?>"
                            data-validate="{required:true}"
                        >
                    </div>

                    <button
                        class="button cart-discount__content-button"
                        type="submit"
                        value="<?= $block->escapeHtml(__('Add Gift Card')) ?>"
                    >
                        <?= $block->escapeHtml(__('Add Gift Card')) ?>
                    </button>
                </div>

                <button
                    type="button"
                    class="button"
                    value="<?= $block->escapeHtml(__('Check Gift Card status')) ?>"
                    data-amgiftcard-js="amgiftcard-check-status"
                >
                    <?= $block->escapeHtml(__('Check Gift Card status')) ?>
                </button>

                <script>
                    require([
                        'jquery',
                        'Amasty_GiftCard/js/cart/main'
                    ], function ($) {
                        $('[data-amgiftcard-js="amgiftcard-check-status"]').amGiftcardCart({
                            checkCardUrl: "<?= $block->escapeUrl($block->getUrl('amgiftcard/cart/check')) ?>"
                        });
                    });
                </script>
            </form>
        </div>
    </div>
<?php endif; ?>
