<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div class="fields additional margin-top-sm">
    <div class="input sku">
        <label
            for="multiple_skus"
            class="label"
        >
            <?= $block->escapeHtml(__('Enter Multiple SKUs')) ?>
        </label>
        <textarea
            name="multiple_skus"
            data-role="multiple-skus"
            id="multiple_skus"
            data-id="multiple_skus"
            aria-required="false"
            rows="2"
            class="input__field input__field--textarea"
        ></textarea>
        <small>
            <?= $block->escapeHtml(__('Use commas or paragraph to separate SKUs.')) ?>
        </small>
    </div>
</div>
<div class="margin-bottom-m">
    <button
        type="button"
        title="<?= $block->escapeHtmlAttr(__('Add to List')) ?>"
        class="
            button
            button--secondary
            quickorder__button
            action
            move-to-single-skus
        "
        data-mage-init='{"quickOrderMultipleSkus":{
            "urlSku":"<?= /* @noEscape */ $block->getUrl('quickorder/ajax/search') ?>"
        }}'
    >
        <?= $block->escapeHtml(__('Add to List')) ?>
    </button>
</div>
