<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<li class="list__item quickorder__list-item">
    <div class="input quickorder__textarea">
        <label for="multiple_skus" class="input__label">
            <?= __('Enter Multiple SKUs') ?>
        </label>
        <textarea
            name="multiple_skus"
            data-role="multiple-skus"
            id="multiple_skus"
            data-id="multiple_skus"
            aria-required="false"
            rows="2"
            class="input__field input__field--textarea"
        ></textarea>
    </div>
    <p>
        <?= __('Use commas or paragraph to separate SKUs.') ?>
    </p>
    <button
        type="button"
        class="button button--secondary"
        data-mage-init='{
            "quickOrderMultipleSkus": {
                "urlSku":"<?= $block->getUrl('quickorder/ajax/search') ?>"
            }
        }'
    >
        <?= __('Add to List') ?>
    </button>
</li>
