<?php
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
/** @var \Magento\Bundle\Pricing\Render\FinalPriceBox $block */
/** @var \Magento\Bundle\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPrice();
$minimalPrice = $finalPriceModel->getMinimalPrice();
$maximalPrice = $finalPriceModel->getMaximalPrice();
/** ex: \Magento\Bundle\Pricing\Price\BundleRegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $regularPriceModel */
$regularPriceModel = $block->getPriceType('regular_price');
$maximalRegularPrice = $regularPriceModel->getMaximalPrice();
$minimalRegularPrice = $regularPriceModel->getMinimalPrice();
?>

<?php if ($block->getSaleableItem()->getPriceView()): ?>
    <span class="minimal-price price__value">
        <span class="price__text">
            <?= __('As low as') ?>
        </span>
        <?php if ($minimalPrice < $minimalRegularPrice): ?>
            <span class="old-price price__value price__value--old">
                <?= $block->renderAmount($minimalRegularPrice, [
                    'display_label'    => __('Minimal Regular Price'),
                    'price_id'         => $block->getPriceId('old-price-' . $idSuffix),
                    'skip_adjustments' => true
                ]); ?>
            </span>
            <span class="price__value price__value--special">
                <?= $block->renderAmount($minimalPrice, [
                    'display_label'    => __('Minimal Special Price'),
                    'price_id' => $block->getPriceId('from-')
                ]); ?>
            </span>
        <?php endif ?>
        <?= $block->renderAmount($minimalPrice, [
            'display_label'    => __('Minimal Price'),
            'price_id' => $block->getPriceId('from-')
        ]); ?>

    </span>
<?php else: ?>
    <?php if ($block->showRangePrice()): ?>
        <span class="price-from price__value price__value--between">
            <span class="price__text">
                <?= __('From') ?>
            </span>
            <?php if ($minimalPrice < $minimalRegularPrice): ?>
                <span class="old-price price__value price__value--old">
                    <?= $block->renderAmount($minimalRegularPrice, [
                        'display_label'    => __('Minimal Regular Price'),
                        'price_id'         => $block->getPriceId('old-price-' . $idSuffix),
                        'skip_adjustments' => true
                    ]); ?>
                </span>
                <span class="price__value price__value--special">
                    <?= $block->renderAmount($minimalPrice, [
                        'display_label'    => __('Minimal Special Price'),
                        'price_id'   => $block->getPriceId('from-'),
                        'price_type' => 'minPrice'
                    ]); ?>
                </span>
            <?php else: ?>
                <?= $block->renderAmount($minimalPrice, [
                    'display_label'    => __('Minimal Price'),
                    'price_id'   => $block->getPriceId('from-'),
                    'price_type' => 'minPrice'
                ]); ?>
            <?php endif ?>
        </span>
        <span class="price-to price__value price__value--between">
            <span class="price__text">
                <?= __('To') ?>
            </span>
            <?php if ($maximalPrice < $maximalRegularPrice): ?>
                <span class="old-price price__value price__value--old">
                    <?= $block->renderAmount($maximalRegularPrice, [
                        'display_label'    => __('Maximal Regular Price'),
                        'price_id'         => $block->getPriceId('old-price-' . $idSuffix),
                        'skip_adjustments' => true
                    ]); ?>
                </span>
                <span class="price__value price__value--special">
                    <?= $block->renderAmount($maximalPrice, [
                        'display_label'    => __('Maximal Special Price'),
                        'price_id'   => $block->getPriceId('to-'),
                        'price_type' => 'maxPrice'
                    ]); ?>
                </span>
            <?php else: ?>
                <?= $block->renderAmount($maximalPrice, [
                    'display_label'    => __('Maximal Price'),
                    'price_id'   => $block->getPriceId('to-'),
                    'price_type' => 'maxPrice'
                ]); ?>
            <?php endif ?>
        </span>
    <?php else: ?>
        <span class="price__value">
            <?php if ($minimalPrice < $minimalRegularPrice): ?>
                <span class="old-price price__value price__value--old">
                    <?= $block->renderAmount($minimalRegularPrice, [
                        'display_label'    => __('Minimal Regular Price'),
                        'price_id'         => $block->getPriceId('old-price-' . $idSuffix),
                        'skip_adjustments' => true
                    ]); ?>
                </span>
                <span class="price__value price__value--special">
                    <?= $block->renderAmount($minimalPrice, [
                        'display_label'    => __('Minimal Special Price'),
                        'price_id' => $block->getPriceId('product-price-')
                    ]); ?>
                </span>
            <?php else: ?>
                <?= $block->renderAmount($minimalPrice, [
                    'display_label'    => __('Minimal Price'),
                    'price_id' => $block->getPriceId('product-price-')
                ]); ?>
            <?php endif ?>

        </span>
    <?php endif ?>
<?php endif ?>
