<?php
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
/** @var \Magento\Bundle\Pricing\Render\FinalPriceBox $block */
/** @var \Magento\Bundle\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPrice();
$minimalPrice = $finalPriceModel->getMinimalPrice();
$maximalPrice = $finalPriceModel->getMaximalPrice();
/** ex: \Magento\Bundle\Pricing\Price\BundleRegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $regularPriceModel */
$regularPriceModel = $block->getPriceType('regular_price');
$maximalRegularPrice = $regularPriceModel->getMaximalPrice();
$minimalRegularPrice = $regularPriceModel->getMinimalPrice();
?>

<?php if ($block->getSaleableItem()->getPriceView()): ?>
    <span class="minimal-price price__value">
        <span class="price__text">
            <?= $block->escapeHtml(__('As low as')) ?>
        </span>
        <?php if ($minimalPrice < $minimalRegularPrice): ?>
            <span class="old-price price__value price__value--old">
                <?= /* @noEscape */ $block->renderAmount($minimalRegularPrice, [
                    'price_id'         => $block->getPriceId('old-price-' . $idSuffix),
                    'skip_adjustments' => true
                ]); ?>
            </span>
        <?php endif ?>
        <?= /* @noEscape */ $block->renderAmount($minimalPrice, [
            'price_id' => $block->getPriceId('from-')
        ]); ?>
    </span>
<?php else: ?>
    <?php if ($block->showRangePrice()): ?>
        <div class="price price--between">
            <span class="price-from">
                <span class="price__text">
                    <?= $block->escapeHtml(__('From')) ?>
                </span>
                <?php if ($minimalPrice < $minimalRegularPrice): ?>
                    <span class="old-price price__value price__value--old">
                        <?= /* @noEscape */ $block->renderAmount($minimalRegularPrice, [
                            'price_id'         => $block->getPriceId('old-price-' . $idSuffix),
                            'skip_adjustments' => true
                        ]); ?>
                    </span>
                    <span class="price__value price__value--special">
                        <?= /* @noEscape */ $block->renderAmount($minimalPrice, [
                            'price_id'   => $block->getPriceId('from-'),
                            'price_type' => 'minPrice'
                        ]); ?>
                    </span>
                <?php else: ?>
                    <span class="price__value">
                        <?= /* @noEscape */ $block->renderAmount($minimalPrice, [
                            'price_id'   => $block->getPriceId('from-'),
                            'price_type' => 'minPrice'
                        ]); ?>
                    </span>
                <?php endif ?>
            </span>
            <span class="price-to">
                <span class="price__text">
                    <?= $block->escapeHtml(__('To')) ?>
                </span>
                <?php if ($maximalPrice < $maximalRegularPrice): ?>
                    <span class="old-price price__value price__value--old">
                        <?= /* @noEscape */ $block->renderAmount($maximalRegularPrice, [
                            'price_id'         => $block->getPriceId('old-price-' . $idSuffix),
                            'skip_adjustments' => true
                        ]); ?>
                    </span>
                    <span class="price__value price__value--special">
                        <?= /* @noEscape */ $block->renderAmount($maximalPrice, [
                            'price_id'   => $block->getPriceId('to-'),
                            'price_type' => 'maxPrice'
                        ]); ?>
                    </span>
                <?php else: ?>
                    <span class="price__value">
                        <?= /* @noEscape */ $block->renderAmount($maximalPrice, [
                            'price_id'   => $block->getPriceId('to-'),
                            'price_type' => 'maxPrice'
                        ]); ?>
                    </span>
                <?php endif ?>
            </span>
        </div>
    <?php else: ?>
        <span class="price__value">
            <?php if ($minimalPrice < $minimalRegularPrice): ?>
                <span class="old-price price__value price__value--old">
                    <?= /* @noEscape */ $block->renderAmount($minimalRegularPrice, [
                        'price_id'         => $block->getPriceId('old-price-' . $idSuffix),
                        'skip_adjustments' => true
                    ]); ?>
                </span>
                <span class="price__value price__value--special">
                    <?= /* @noEscape */ $block->renderAmount($minimalPrice, [
                        'price_id' => $block->getPriceId('product-price-')
                    ]); ?>
                </span>
            <?php else: ?>
                <?= /* @noEscape */ $block->renderAmount($minimalPrice, [
                    'price_id' => $block->getPriceId('product-price-')
                ]); ?>
            <?php endif ?>

        </span>
    <?php endif ?>
<?php endif ?>
