<div class="footer__handler container">
    <button
        class="
            button
            button--icon
            footer__scroll-top
        "
        type="button"
        aria-label="<?= $block->escapeHtmlAttr(__('Scroll to top')) ?>"
        data-mage-init='{ "scrollTop": { } }'
    >
        <svg
            class="icon"
            role="presentation"
            focusable="false"
        >
            <title><?= __('Scroll to top') ?></title>
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#arrow-up')) ?>"></use>
        </svg>
    </button>

    <section class="footer__newsletter">
        <?= $this->getChildHtml('footer-newsletter') ?>
    </section>

    <div class="footer__social-handler ">
        <h3 class="footer__social-list-title">
            <?= __('Let\'s get social!') ?>
        </h3>
        <ul
            class="
                list
                list--with-icon
                list--horizontal
                footer__social-list
            "
        >
            <li class="list__item">
                <a
                    href="#"
                    class="list__icon-link"
                    aria-label="<?= $block->escapeHtmlAttr(__('Go to Our Facebook Page')) ?>"
                >
                    <svg
                        class="
                            icon
                            footer__social-icon
                        "
                        role="img"
                    >
                        <title><?= __('Facebook logo') ?></title>
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#facebook')) ?>"></use>
                    </svg>
                </a>
            </li>
            <li class="list__item">
                <a
                    href="#"
                    class="list__icon-link"
                    aria-label="<?= $block->escapeHtmlAttr(__('Check Our on Twitter')) ?>"
                >
                    <svg
                        class="
                            icon
                            footer__social-icon
                        "
                        role="img"
                    >
                        <title><?= __('Twitter logo') ?></title>
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#twitter')) ?>"></use>
                    </svg>
                </a>
            </li>
        </ul>
    </div>

    <section class="footer__links">
    <?php // $this->getChildHtml('footer-menu') TO DO MOVE TO CMS BLOCK ?>
        <div
            id="dropdown-footer"
            class="
                dropdown-list
                dropdown-list--with-breakpoint
            "
            data-mage-init='{ "dropdownList": {} }'
        >
            <ul class="dropdown-list__list">
                <li
                    class="
                        dropdown-list__item
                        dropdown-list__item--collapse
                    "
                >
                    <button
                        class="dropdown-list__label"
                        aria-controls="dropdown-customers"
                        disabled=""
                    >
                        Customers
                        <svg
                            class="
                                icon
                                dropdown-list__icon
                                dropdown-list__icon--inner
                            "
                            role="img"
                        >
                            <title>Arrow down</title>
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#angle-down')) ?>"></use>
                        </svg>
                    </button>

                    <div
                        id="dropdown-customers"
                        class="dropdown-list__content"
                        aria-hidden="false"
                    >
                        <ul
                            class="
                                list
                                list__columns
                                footer__links-list
                            "
                        >
                            <li
                                class="
                                    list__item
                                    list__column
                                    list__column--hidden
                                "
                            >
                                <a href="" class="link">
                                    Column 1
                                </a>
                                <ul class="list">
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Sign in"
                                        >
                                            Login to My Account
                                        </a>
                                    </li>
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Sign up"
                                        >
                                            Create an Account
                                        </a>
                                    </li>
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="My Orders"
                                        >
                                            My Orders
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li
                                class="
                                    list__item
                                    list__column
                                    list__column--hidden
                                "
                            >
                                <a href="" class="link">
                                    Column 2
                                </a>
                                <ul class="list">
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="My Cart"
                                        >
                                            My Cart
                                        </a>
                                    </li>
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Checkout"
                                        >
                                            Checkout
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </li>

                <li
                    class="
                        dropdown-list__item
                        dropdown-list__item--collapse
                    "
                >
                    <button
                        class="dropdown-list__label"
                        aria-controls="dropdown-information"
                        disabled=""
                    >
                        Information
                        <svg
                            class="
                                icon
                                dropdown-list__icon
                                dropdown-list__icon--inner
                            "
                            role="img"
                        >
                            <title>Arrow down</title>
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#angle-down')) ?>"></use>
                        </svg>
                    </button>

                    <div
                        id="dropdown-information"
                        class="dropdown-list__content"
                        aria-hidden="false"
                    >
                        <ul
                            class="
                                list
                                list__columns
                                footer__links-list
                            "
                        >
                            <li
                                class="
                                    list__item
                                    list__column
                                    list__column--hidden
                                "
                            >
                                <a href="" class="link">
                                    Column 1
                                </a>
                                <ul class="list">
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Hours"
                                        >
                                            Hours
                                        </a>
                                    </li>
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="About Us"
                                        >
                                            About Us
                                        </a>
                                    </li>
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Contact Us"
                                        >
                                            Contact Us
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li
                                class="
                                    list__item
                                    list__column
                                    list__column--hidden
                                "
                            >
                                <a href="" class="link">
                                    Column 2
                                </a>
                                <ul class="list">
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Job Openings"
                                        >
                                            Job Openings
                                        </a>
                                    </li>
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Returns"
                                        >
                                            Returns
                                        </a>
                                    </li>
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Shipping"
                                        >
                                            Shipping
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li
                                class="
                                    list__item
                                    list__column
                                    list__column--hidden
                                "
                            >
                                <a href="" class="link">
                                    Column 3
                                </a>
                                <ul class="list">
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Privacy Policy"
                                        >
                                            Privacy Policy
                                        </a>
                                    </li>
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Terms &amp; Conditions"
                                        >
                                            Terms &amp; Conditions
                                        </a>
                                    </li>
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Site Map"
                                        >
                                            Site Map
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li
                                class="
                                    list__item
                                    list__column
                                    list__column--hidden
                                "
                            >
                                <a href="" class="link">
                                    Column 4
                                </a>
                                <ul class="list">
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Reviews"
                                        >
                                            Reviews
                                        </a>
                                    </li>
                                    <li
                                        class="
                                            list__item
                                            list__column-item
                                        "
                                    >
                                        <a
                                            href="#"
                                            class="
                                                link
                                                footer__link
                                            "
                                            title="Email Us!"
                                        >
                                            Email Us!
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </section>
</div>

<section class="footer__bottom-bar ">
    <?php // $this->getChildHtml('social-links') TO DO MOVE TO CMS BLOCK ?>
    <div class="footer__bottom-bar-handler container">
        <small class="footer__copyright">
            Copyright © 2019 Colibri
        </small>
        <ul
            class="
                footer__payments-list
                list
                list--horizontal
            "
        >
            <li class="list__item">
                <svg
                    class="
                        icon
                        footer__payments-list-icon
                        footer__payments-list-icon--visa
                    "
                    role="img"
                >
                    <title>Visa</title>
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#visa')) ?>"></use>
                </svg>
            </li>
            <li class="list__item">
                <svg
                    class="
                        icon
                        footer__payments-list-icon
                    "
                    role="img"
                >
                    <title>Master Card</title>
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#master-card')) ?>"></use>
                </svg>
            </li>
            <li class="list__item">
                <svg class="icon footer__payments-list-icon" role="img">
                    <title>Discover</title>
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#discover')) ?>"></use>
                </svg>
            </li>
            <li class="list__item">
                <svg class="icon footer__payments-list-icon" role="img">
                    <title>American Express</title>
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#american-express')) ?>"></use>
                </svg>
            </li>
            <li class="list__item">
                <svg class="icon footer__payments-list-icon footer__payments-list-icon--paypal" role="img">
                    <title>PayPal</title>
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#paypal')) ?>"></use>
                </svg>
            </li>
        </ul>
    </div>
</section>

<?php // $this->getChildHtml('cookie-message') TO DO MOVE TO CMS BLOCK ?>
<div
    class="cookie-message"
    data-type="cookie"
    tabindex="0"
    aria-label="Cookie policy message"
    data-mage-init='{ "cookieMessage": { } }'
>

    <div class="cookie-message__container">
        <p class="cookie-message__text">
            <a href="#" class="link--invert">Example link</a> Find out more about their purpose and settings in your browser. By browsing the site you are agreeing to use cookies according to your browser settings.
        </p>

        <button
            class="
                button
                button--icon
                cookie-message__close
                button--rotate-icon
            "
            type="button"
            aria-label="Close cookie message"
        >
            <svg
                class="
                    icon
                    button__icon
                    cookie-message__close-icon
                "
                role="presentation"
                focusable="false"
            >
                <title>Close</title>
                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#close')) ?>"></use>
            </svg>
        </button>
    </div>
</div>
