<div class="footer__handler container">
    <section class="footer__newsletter">
        <?= $this->getChildHtml('footer-newsletter') ?>
    </section>
    <section class="footer__links">
        <?= $this->getChildHtml('footer-links') ?>
    </section>
</div>
<section class="footer__bottom-bar">
    <div class="footer__bottom-bar-handler container">
        <?= $this->getChildHtml('social-links') ?>
        <small class="footer__copyright">
            <?= /* @escapeNotVerified */ __('Copyright © 2017 Alpaca. All rights reserved.') ?>
        </small>
    </div>
</section>
