<!-- This should be moved to CMS Menu when customising features will be available. This file is temporary -->
<div class="
        dropdown-list
        dropdown-list@screen-m
        dropdown-list--is-open@screen-m
        dropdown-list--dark
        js-is-medium-open
     "
     data-mage-init='{ "dropdownList": {} }'
>
    <ul class="dropdown-list__list">
        <li class="
                dropdown-list__item
                dropdown-list__item--collapse
            "
        >
            <button class="dropdown-list__label"
                    type="button"
                    aria-expanded="false"
                    aria-controls="dropdown-help"
                    data-dropdown="dropdown-help"
            >
                <?= /* @escapeNotVerified */ __('Help') ?>
                <svg class="dropdown-list__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
                </svg>
            </button>
            <div id="dropdown-help" class="dropdown-list__content" data-content="dropdown-help" aria-hidden="true">
                <ul class="list footer__links-list">
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Contact') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Frequently asked questions (FAQ)') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('How to buy') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Track your package') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Guides') ?>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="
                dropdown-list__item
                dropdown-list__item--collapse
            "
        >
            <button class="dropdown-list__label"
                    type="button"
                    aria-expanded="false"
                    aria-controls="dropdown-info"
                    data-dropdown="dropdown-info"
            >
                <?= /* @escapeNotVerified */ __('Information') ?>
                <svg class="dropdown-list__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
                </svg>
            </button>
            <div id="dropdown-info"
                 class="dropdown-list__content"
                 data-content="dropdown-info"
                 aria-hidden="true"
            >
                <ul class="list footer__links-list">
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Delivery time') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Payments') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Delivery cost') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Returns and exchanges') ?>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="
                dropdown-list__item
                dropdown-list__item--collapse
            "
        >
            <button class="dropdown-list__label"
                    type="button"
                    aria-expanded="false"
                    aria-controls="dropdown-worth"
                    data-dropdown="dropdown-worth"
            >
                <?= /* @escapeNotVerified */ __('Why is worth it') ?>
                <svg class="dropdown-list__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
                </svg>
            </button>
            <div id="dropdown-worth"
                 class="dropdown-list__content"
                 data-content="dropdown-worth"
                 aria-hidden="true"
            >
                <ul class="list footer__links-list">
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('30 days for return') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Guarantee') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('454 Brands') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Discounts') ?>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="
                dropdown-list__item
                dropdown-list__item--collapse
            "
        >
            <button class="dropdown-list__label"
                    type="button"
                    aria-expanded="false"
                    aria-controls="dropdown-alpaca"
                    data-dropdown="dropdown-alpaca"
            >
                <?= /* @escapeNotVerified */ __('Alpaca.pl') ?>
                <svg class="dropdown-list__icon">
                    <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
                </svg>
            </button>
            <div id="dropdown-alpaca"
                 class="dropdown-list__content"
                 data-content="dropdown-alpaca"
                 aria-hidden="true"
            >
                <ul class="list footer__links-list">
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('About us') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Certificates and safety') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Prizes and customer feedback') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Cookie policy') ?>
                        </a>
                    </li>
                    <li class="list__item">
                        <a href="#" class="link footer__link">
                            <?= /* @escapeNotVerified */ __('Regulations') ?>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</div>
