<div class="footer__handler container row">
    <button
        class="button footer__scroll-top"
        type="button"
        aria-label="<?= __('Scroll to top') ?>"
        data-mage-init='{ "scrollTop": { } }'
    >
        <svg class="icon footer__icon" role="img">
            <title><?= __('Arrow up') ?></title>
            <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#arrow-up') ?>"></use>
        </svg>
    </button>
    <section class="footer__newsletter col-xs-12 col-lg-3">
        <?= $this->getChildHtml('footer-newsletter') ?>
    </section>
    <section class="footer__links col-xs-12 col-lg-9">
        <?= $this->getChildHtml('footer-menu') ?>
    </section>
</div>
<section class="footer__bottom-bar">
    <div class="footer__bottom-bar-handler container">
        <?= $this->getChildHtml('social-links') ?>
        <small class="footer__copyright">
            <?= __('Copyright © 2018 Alpaca. All rights reserved.') ?>
        </small>
    </div>
</section>
<div
    class="cookie-message"
    data-type="cookie"
    data-mage-init='{ "cookieMessage": { } }'
>
    <div class="cookie-message__container">
        <span class="cookie-message__text">
            <a href="#" class="cookie-message__link">Example link</a> Find out more about their purpose and settings in your browser. By browsing the site you are agreeing to use cookies according to your browser settings.
        </span>
        <button class="cookie-message__close" type="button">
            <svg class="cookie-message__close-icon">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#close') ?>"></use>
            </svg>
        </button>
    </div>
</div>
