<button
    class="
        button
        button--icon
        footer__scroll-top
    "
    type="button"
    aria-label="<?= $block->escapeHtmlAttr(__('Scroll to top')) ?>"
    data-mage-init='{ "scrollTop": {} }'
>
    <svg
        class="icon"
        role="presentation"
        focusable="false"
    >
        <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#arrow-up')) ?>"></use>
    </svg>
</button>
