<div class="footer__social-handler">
    <span class="footer__social-list-subtitle">
        <?= $escaper->escapeHtml(__('Find us on')) ?>
    </span>
    <ul class="list list--with-icon list--horizontal footer__social-list">
        <li class="list__item footer__social-list-item">
            <a
                href="#"
                class="list__icon-link"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Go to Youtube')) ?>"
            >
                <svg class="icon footer__social-icon">
                    <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#youtube')) ?>"></use>
                </svg>
            </a>
        </li>
        <li class="list__item footer__social-list-item">
            <a
                href="#"
                class="list__icon-link"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Go to Facebook')) ?>"
            >
                <svg class="icon footer__social-icon">
                    <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#facebook')) ?>"></use>
                </svg>
            </a>
        </li>
        <li class="list__item footer__social-list-item">
            <a
                href="#"
                class="list__icon-link"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Go to Instagram')) ?>"
            >
                <svg class="icon footer__social-icon">
                    <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#instagram')) ?>"></use>
                </svg>
            </a>
        </li>
        <li class="list__item footer__social-list-item">
            <a
                href="#"
                class="list__icon-link"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Go to Google Plus')) ?>"
            >
                <svg class="icon footer__social-icon">
                    <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#google-plus')) ?>"></use>
                </svg>
            </a>
        </li>
        <li class="list__item footer__social-list-item">
            <a
                href="#"
                class="list__icon-link"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Go to Twitter')) ?>"
            >
                <svg class="icon footer__social-icon">
                    <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#twitter')) ?>"></use>
                </svg>
            </a>
        </li>
    </ul>
</div>
