<div class="footer__social-handler ">
    <span class="footer__social-list-subtitle">
        <?= __('Find us on') ?>
    </span>

    <ul class="list list--with-icon list--horizontal footer__social-list">
        <li class="list__item footer__social-list-item">
            <a href="#" class="list__icon-link ">
                <svg class="list__icon footer__social-icon">
                    <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#youtube'); ?>"></use>
                </svg>
            </a>
        </li>
        <li class="list__item footer__social-list-item">
            <a href="#" class="list__icon-link ">
                <svg class="list__icon footer__social-icon">
                    <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#facebook'); ?>"></use>
                </svg>
            </a>
        </li>
        <li class="list__item footer__social-list-item">
            <a href="#" class="list__icon-link ">
                <svg class="list__icon footer__social-icon">
                    <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#instagram'); ?>"></use>
                </svg>
            </a>
        </li>
        <li class="list__item footer__social-list-item">
            <a href="#" class="list__icon-link ">
                <svg class="list__icon footer__social-icon">
                    <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#google-plus'); ?>"></use>
                </svg>
            </a>
        </li>
        <li class="list__item footer__social-list-item">
            <a href="#" class="list__icon-link ">
                <svg class="list__icon footer__social-icon">
                    <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#twitter'); ?>"></use>
                </svg>
            </a>
        </li>
    </ul>
</div>
