<?php
// @codingStandardsIgnoreFile
?>

<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div
            class="product-view__stock-status"
            title="<?= /* @escapeNotVerified */ __('Availability') ?>"
        >
            <?= /* @escapeNotVerified */ __('In stock') ?>
        </div>
    <?php else: ?>
        <div
            class="product-view__stock-status product-view__stock-status--alert"
            title="<?= /* @escapeNotVerified */ __('Availability') ?>"
        >
            <?= /* @escapeNotVerified */ __('Out of stock') ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
