<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div
            class="product-view__stock-status"
            title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>"
        >
            <?= $escaper->escapeHtml(__('In stock')) ?>
        </div>
    <?php else: ?>
        <div
            class="product-view__stock-status product-view__stock-status--alert"
            title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>"
        >
            <?= $escaper->escapeHtml(__('Out of stock')) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
