<?php

use MageMe\WebForms\Block\Widget\Button;

/** @var Button $block */
?>

<button
    class="
        button
        primary
        <?= $block->escapeHtmlAttr($this->getButtonCssClass()) ?>
    "
    data-modal-trigger="<?= $block->escapeHtmlAttr($this->getContainerId()) ?>"
    data-mage-init='{
        "modal": {
            "useAjax": true,
            "ajaxUrl": "<?= $block->escapeUrl($block->getAjaxUrl()) ?>",
            "ajaxTarget": "#target_<?= $block->escapeHtmlAttr($this->getContainerId()) ?>",
            "ajaxErrorMessage": "<?= $block->escapeHtmlAttr(__('Failed to load modal content.')) ?>"
        }
    }'
    type="button"
    title="<?= $block->escapeHtmlAttr($this->getButtonText()) ?>"
>
    <?= $block->escapeHtml(__($this->getButtonText())) ?>
</button>
<div
    role="dialog"
    aria-hidden="true"
    id="<?= $block->escapeHtmlAttr($this->getContainerId()) ?>"
    data-modal="<?= $block->escapeHtmlAttr($this->getContainerId()) ?>"
    class="
        modal
        modal--button
        <?= str_replace('"', '\"', $block->escapeHtmlAttr($this->getPopupCssClass())) ?>
    "
>
    <div
        class="modal__container webforms__modal-container"
        role="document"
        tabindex="0"
    >
        <div class="modal__content webforms__modal-content">
            <div
                id="target_<?= $block->escapeHtmlAttr($this->getContainerId()) ?>"
                class="
                    webforms-popup
                    mfp-hide
                "
            >
                <!-- webform modal content -->
            </div>
        </div>
        <button
            class="
                button
                button--icon
                button--rotate-icon
                modal__close-button
            "
            type="button"
            aria-label="<?= $block->escapeHtmlAttr(__('Close modal')) ?>"
        >
            <svg
                class="
                    icon
                    button__icon
                    modal__close-button-icon
                "
                role="presentation"
                focusable="false"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#close')); ?>"></use>
            </svg>
        </button>
    </div>
</div>
