<?php if ($block->canShowBlock()) : ?>
<?php
$filtersCollection = $block->getFilters();
$categoryFilter = 'category';
$isAnyFilterActive = false;
?>
    <div
        class="filters"
        id="layered-filter-block"
    >
        <?= $block->getChildHtml('state') ?>

        <?php foreach ($filtersCollection as $filter): ?>
            <?php
            $filterId = $block->escapeHtmlAttr(
                str_replace(
                    ' ',
                    '-',
                    mb_strtolower($filter->getName(), 'UTF-8')
                )
            );
            ?>
            <?php if ($filter->getItemsCount()): ?>
                <?php if ($filterId === $categoryFilter): ?>
                    <div class="filters__item">
                        <?= $block->getChildBlock('renderer')->render($filter); ?>
                    </div>
                <?php else: ?>
                    <?php
                    $isAnyFilterActive = true;
                    break;
                    ?>
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if ($isAnyFilterActive): ?>
            <div class="filters__item">
                <button
                    class="
                        button
                        button--icon
                        modal-trigger
                        filters__trigger
                        filters__trigger--open
                    "
                    type="button"
                    aria-label="<?= $block->escapeHtmlAttr(__('Open shopping options')) ?>"
                    data-modal-trigger="filters-options"
                    aria-expanded="false"
                    data-mage-init='{ "modal": {} }'
                >
                    <span class="button__text">
                        <?= __('Shopping Options') ?>
                    </span>
                    <svg
                        class="icon"
                        role="presentation"
                        focusable="false"
                    >
                        <title><?= __('Arrow right') ?></title>
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#angle-right')); ?>"></use>
                    </svg>
                </button>

                <div
                    class="
                        modal
                        modal--tertiary
                        filters__modal
                    "
                    role="dialog"
                    aria-hidden="true"
                    id="filters-options"
                    data-modal="filters-options"
                    aria-lebelledby="filters-option-title"
                >
                    <div
                        role="document"
                        class="
                            modal__container
                            filters__container
                        "
                        tabindex="0"
                    >
                        <div
                            class="
                                modal__content
                                filters__content
                            "
                        >
                            <div
                                class="
                                    modal__top
                                    filters__content-top
                                "
                            >
                                <h2
                                    class="
                                        modal__heading
                                        filters__heading
                                    "
                                    id="filters-option-title"
                                >
                                    <?= __('Shopping options') ?>
                                </h2>
                            </div>

                            <div
                                class="
                                    modal__middle
                                    filters__content-middle
                                "
                            >
                                <div
                                    class="
                                        dropdown-list
                                        filters__dropdown
                                    "
                                    id="filters-dropdown"
                                    data-mage-init='{ "dropdownList": {} }'
                                >
                                    <ul class="dropdown-list__list">
                                        <?php foreach ($block->getFilters() as $filter): ?>
                                            <?php
                                            $filterName = $block->escapeHtml($filter->getName());
                                            $filterId = $block->escapeHtmlAttr(
                                                str_replace(
                                                    ' ',
                                                    '-',
                                                    mb_strtolower($filterName, 'UTF-8')
                                                )
                                            );
                                            ?>
                                            <?php if ($filter->getItemsCount() && $filterId != $categoryFilter): ?>
                                                <li
                                                    class="
                                                        dropdown-list__item
                                                        dropdown-list__item--collapse
                                                        filter
                                                        filter--checkbox
                                                    "
                                                >
                                                    <div
                                                        class="
                                                            dropdown-list__label-wrapper
                                                            filter__label-wrapper
                                                        "
                                                    >
                                                        <button
                                                            type="button"
                                                            class="dropdown-list__label"
                                                            aria-controls="filter-<?= $filterId ?>"
                                                            aria-expanded="true"
                                                        >
                                                            <h3 class="filter__heading">
                                                                <?= $filterName ?>
                                                            </h3>
                                                            <svg
                                                                class="
                                                                    icon
                                                                    dropdown-list__icon
                                                                "
                                                                role="presentation"
                                                                focusable="false"
                                                            >
                                                                <title><?= __('Arrow down') ?></title>
                                                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#angle-down')); ?>"></use>
                                                            </svg>
                                                        </button>
                                                    </div>

                                                    <div
                                                        class="
                                                            dropdown-list__content
                                                            filter__content
                                                        "
                                                        id="filter-<?= $filterId ?>"
                                                        aria-hidden="false"
                                                    >
                                                        <?= $block->getChildBlock('renderer')->render($filter) ?>
                                                    </div>
                                                </li>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <button
                            class="
                                button
                                button--icon
                                button--rotate-icon
                                modal__close-button
                                filters__close-button
                            "
                            type="button"
                            aria-label="<?= $block->escapeHtmlAttr(__('Close filters modal')) ?>"
                        >
                            <svg
                                class="
                                    icon
                                    button__icon
                                    modal__close-button-icon
                                "
                                role="img"
                            >
                                <title><?= __('Close') ?></title>
                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#close')); ?>"></use>
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
