<?php
    /* @var $block \Magento\MultipleWishlist\Block\Behaviour */
?>
<script id="form-tmpl-multiple" type="text/x-magento-template">
    <form id="wishlist-hidden-form" method="post" action="<%- data.url %>" class="no-display">
        <% if (data.itemId) { %>
            <input name="item_id" value="<%- data.itemId %>">
        <% } %>
        <% if (data.wishlistId) { %>
            <input name="wishlist_id" value="<%- data.wishlistId %>">
        <% } %>
        <% if (data.qty) { %>
            <input name="qty" value="<%- data.qty %>">
        <% } %>
        <% if (data.item) { %>
            <input name="item" value="<%- data.item %>">
        <% } %>
        <% if (data.entity) { %>
            <input name="entity" value="<%- data.entity %>">
        <% } %>
        <% if (data.form_key) { %>
            <input name="form_key" value="<%- data.form_key %>">
        <% } %>
    </form>
</script>
<script id="popup-tmpl" type="text/x-magento-template">
    <div class="window wishlist overlay active"></div>
    <div id="<%- data.popupWishlistBlockId %>" class="window wishlist popup active">
        <div class="popup-actions">
            <div class="secondary">
                <button type="button"
                        title="<%- window.jQuery.mage.__('Close') %>"
                        class="action close <%- data.btnCloseClass %>"
                        data-dismiss="popup">
                    <span><%- data.translate.close %></span>
                </button>
            </div>
        </div>
        <div class="popup-header">
             <strong class="title" id="popup-title">
                 <span>
                     <% if (data.isEdit) { %>
                        <%- data.translate.editWishlist %>
                     <% } else { %>
                        <%- data.translate.createNewWishlist %>
                     <% } %>
                 </span>
             </strong>
        </div>
        <div class="popup-content" id="popup-content">
            <form id="<%- data.popupWishlistFormId %>" method="post" action="<%- data.url %>" class="form wishlist">
                <input name="form_key" type="hidden" value="<%- data.formKey %>">
                <fieldset class="fieldset">
                    <div class="field name">
                        <label for="wishlist-name" class="label">
                            <span><%- data.translate.wishListName %></span>
                        </label>
                        <div class="control">
                            <input id="wishlist-name"
                                   class="input-text"
                                   data-role="prompt-field"
                                   data-validate="{required:true}"
                                   type="text"
                                   name="name"
                                   maxlength="255"
                                   value="<%- data.name %>">
                        </div>
                    </div>
                    <div class="field choice">
                        <input id="wishlist-public"
                               type="checkbox"
                               name="visibility"<% if (data.isPublic) { %> checked=true<% } %>">
                        <label for="wishlist-public" class="label">
                            <span><%- data.translate.publicWishList %></span>
                        </label>
                    </div>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button class="action save primary" type="submit" title="<%- window.jQuery.mage.__('Save') %>">
                                <span><%- data.translate.save %></span>
                            </button>
                        </div>
                        <div class="secondary">
                            <button class="action cancel <%- data.btnCloseClass %>" type="button" title="<%- window.jQuery.mage.__('Cancel') %>">
                                <span><%- data.translate.cancel %></span>
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</script>
<script id="split-btn-tmpl" type="text/x-magento-template">
    <div
        class="
            dropdown-list
            dropdown-list--detailed-content
        "
        data-mage-init='{ "dropdownList": {} }'
    >
        <button
            type="button"
            data-post='<%- JSON.stringify(data.generalParams) %>'
            data-action="add-to-wishlist"
            class="label action split"
        >
            <%- data.buttonName %>
        </button>

        <ul class="dropdown-list__list" >
            <li class="dropdown-list__item dropdown-list__item--collapse">
                <button
                    class="action toggle change dropdown-list__label"
                    title="<%- window.jQuery.mage.__('Add to:') %>"
                    type="button"
                    aria-expanded="false"
                    aria-controls="dropdown-wishlist-content"
                >
                    <%- window.jQuery.mage.__('Add to:') %>
                    <svg
                        class="icon dropdown-list__icon"
                        aria-hidden="true"
                        role="img"
                    >
                        <title><?= __('Arrow Down'); ?></title>
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-down')) ?>"></use>
                    </svg>
                </button>
                <div
                    id="dropdown-wishlist-content"
                    class="dropdown-list__content"
                    aria-hidden="true"
                >
                    <ul class="list">
                        <% _.each(data.wishlists, function(item) { %>
                            <li class="list__item">
                                <% if (item.newClass) { %>
                                    <span role="button"
                                        tabindex="0"
                                        class="action <%- item.newClass %>"
                                        data-action-keypress="true"
                                        data-post-new-wishlist='<%- JSON.stringify(item.params) %>'
                                        data-action="add-to-wishlist"
                                        title="<%- item.name %>">
                                        <span><%- item.name %></span>
                                    </span>
                                <% } else { %>
                                    <span role="button"
                                        tabindex="0"
                                        data-action-keypress="true"
                                        data-post='<%- JSON.stringify(item.params) %>'
                                        data-action="add-to-wishlist"
                                        title="<%- item.name %>">
                                        <%- item.name %>
                                    </span>
                                <% } %>
                            </li>
                        <% }); %>
                    </ul>
                </div>
            </li>

        </ul>
    </div>
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "multipleWishlist": {
                        "component": "Magento_MultipleWishlist/js/view/multiple-wishlist",
                        "config": {
                            "multipleWishlistOptions": {
                                "createUrl": "<?= $block->escapeUrl($block->getCreateUrl()) ?>",
                                "wishlistLink": ".action.towishlist"
                            }
                        }
                    }
                }
            }
        }
    }
</script>
