<?php
/** @var VladimirPopov\WebForms\Block\Form $this */

if ($this->getRegistry()->registry('redirect_url')): ?>
    <meta
        http-equiv="refresh"
        content="0;url=<?= $this->getRegistry()->registry('redirect_url') ?>"
    >
    <script type="text/javascript">
        window.location = '<?= $this->getRegistry()->registry('redirect_url') ?>';
    </script>
<?php endif; ?>

<?php
$tmpData = $this->getSession()->getData('webform_result_tmp_' . $this->getForm()->getId());
$tmpResult = new \Magento\Framework\DataObject;
$_uid = $this->getUid();
if (!empty($tmpData['field']) && is_array($tmpData['field'])) {
    foreach ($tmpData['field'] as $field_id => $value) {
        $tmpResult->setData('field_' . $field_id, $value);
    }
}
if ($this->getForm()->getIsActive() == \VladimirPopov\WebForms\Model\Form::STATUS_DISABLED || !$this->isDirectAvailable()): ?>
    <?= $this->getNotAvailableMessage(); ?>
<?php else: ?>
    <?php if ($this->isAjax()): ?>
        <div
            id="webform_<?= $_uid ?>_success_text"
            class="
                message
                message--success
                display-none
            "
        >
        </div>
    <?php endif; ?>

    <?php if ($this->getSuccess()): ?>
        <div class="webforms-success-text">
            <?= $this->getSuccessText() ?>
        </div>
    <?php endif; ?>
    <?php if (!$this->getSuccess() || $this->getData('after_submission_form')): ?>
        <?php if ($messages = $this->getErrorMessages()): ?>
            <div class="message error">
                <div>
                    <?php foreach ($messages as $message): ?>
                        <?= $message ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>

        <?php
            $aria_describedby = "";
            if ($this->getDescription()) {
                $aria_describedby = "aria-describedby=\"{$_uid}form_description\"";
            }
        ?>
        <div
            id="webform_<?= $_uid ?>_form"
            class="webforms" <?= $aria_describedby ?>
        >
            <?php if ($this->getDescription()): ?>
                <div id="<?= $_uid ?>form_description">
                    <?= $this->getDescription(); ?>
                </div>
            <?php endif; ?>

            <?php if ($this->isAjax()): ?>
                <iframe
                    title="<?= $this->getForm()->getName() ?>"
                    id="webform_<?= $_uid ?>_iframe"
                    name="webform_<?= $_uid ?>_iframe"
                    role="none"
                    style="width:0;height:0;border:0;position:absolute">
                </iframe>
            <?php endif; ?>

            <div
                class="
                    row
                    center-xs
                "
            >
                <div
                    class="
                        col-xs-12
                        col-md-8
                        col-lg-6
                        start-xs
                    "
                >
                    <form
                        class="form"
                        action="<?= $this->getFormAction() ?>"
                        method="post"
                        name="webform_<?= $_uid ?>"
                        id="webform_<?= $_uid ?>"
                        enctype="<?= $this->getEnctype() ?>"
                        class="webforms-<?= $this->getForm()->getCode() ?>"
                        <?php if ($this->getDescription()): ?>
                            aria-describedby="<?= $_uid ?>form_description"
                        <?php endif ?>
                        aria-label="<?= $this->getForm()->getName() ?>"
                        <?php if ($this->isAjax()): ?>
                            target="webform_<?= $_uid ?>_iframe"
                        <?php endif ?>
                        role="none">

                        <input
                            name="form_key"
                            type="hidden"
                            value="<?= $block->escapeHtmlAttr($this->getFormKey()) ?>"
                        />
                        <input
                            type="hidden"
                            name="submitForm_<?= $block->escapeHtmlAttr($this->getForm()->getId()) ?>"
                            value="1"
                        />
                        <input
                            type="hidden"
                            name="webform_id"
                            value="<?= $block->escapeHtmlAttr($this->getForm()->getId()) ?>"
                        />

                        <?php if (is_array($this->getData('hidden'))): ?>
                            <?php foreach ($this->getData('hidden') as $key => $value): ?>
                                <input
                                    type="hidden"
                                    name="<?= $block->escapeHtmlAttr($key) ?>"
                                    value="<?= $block->escapeHtmlAttr($value) ?>"
                                />
                            <?php endforeach; ?>
                        <?php endif; ?>

                        <?php if (count($this->getForm()->_getHidden())): ?>
                            <?php foreach ($this->getForm()->_getHidden() as $field): ?>
                                <?= $field->toHtml(); ?>
                            <?php endforeach; ?>
                        <?php endif; ?>

                        <?php foreach ($this->getForm()->_getFieldsToFieldsets() as $fieldset_id => $fieldset): ?>
                            <fieldset
                                id="fieldset_<?= $_uid . $fieldset_id ?>"
                                class="fieldset fieldset-<?= $fieldset_id ?>
                                <?= (!empty($fieldset['css_class'])) ? $fieldset['css_class'] : ''; ?>"
                                style="<?= (!empty($fieldset['css_style'])) ? $fieldset['css_style'] . ';' : ''; ?>
                                <?= ($fieldset['logic_visibility'] == \VladimirPopov\WebForms\Model\Logic::VISIBILITY_HIDDEN) ? 'display:none' : ''; ?>"
                                role="group"
                                <?php if ($fieldset_id): ?>
                                    aria-labelledby="legend_<?= $_uid . $fieldset_id ?>"
                                <?php endif; ?>
                            >
                                <?php if (!empty($fieldset['name'])): ?>
                                    <legend
                                        class="fieldset__legend fieldset__legend--hidden"
                                        id="legend_<?= $_uid . $fieldset_id ?>"
                                    >
                                        <?= $block->escapeHtml($fieldset['name']) ?>
                                    </legend>
                                <?php endif ?>

                                <?php foreach ($fieldset['fields'] as $field) {
                                    // set temporary value
                                    $field->setData('result', $tmpResult);
                                    $field->setData('uid', $_uid);
                                    $fieldId = $block->escapeHtmlAttr($field->getId());
                                    $fieldUid = $this->getFieldUid($fieldId);
                                    $field_css_type = 'type-' . str_replace('/', '-', $field->getType());
                                    if ($field->getType() == 'subscribe') $field_css_type .= ' choice';
                                    $aria_labelledby = "aria-labelledby=\"label_field" . $fieldUid . "\"";
                                    if (in_array($field->getType(), ["html", "subscribe"]) || $field->getHideLabel())
                                        $aria_labelledby = "";
                                    $label_for = "for=\"field" . $fieldUid . "\"";
                                    if (in_array($field->getType(), ["select/radio", "select/checkbox"])) {
                                        $label_for = "";
                                    }

                                    $aria_describedby = "";
                                    if ($field->getComment()) $aria_describedby = "aria-describedby=\"comment_field" . $fieldUid . "\"";
                                    ?>
                                    <div
                                        id="field_<?= $fieldUid ?>"
                                        role="group"
                                        class="
                                            webforms-field
                                            <?= $field->getCssClassContainer() ?>
                                            <?= $field_css_type ?>
                                            webforms-fields-<?= $field->getId() ?>
                                            <?= ($field->getCode()) ? 'webforms-fields-' . $field->getCode() : ''; ?>
                                            <?= ($field->getRequired()) ? 'required' : ''; ?>
                                        "
                                        <?= $aria_labelledby ?>
                                        <?= $aria_describedby ?>
                                        <?php if ($field->getData('logic_visibility') == \VladimirPopov\WebForms\Model\Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>
                                    >
                                        <div
                                            class="control"
                                            role="group"
                                            <?= $aria_labelledby ?>
                                        >
                                            <?php if ($field->getType() != 'html' && $field->getType() != 'subscribe' && !$field->getHideLabel()): ?>
                                                <label
                                                    class="label"
                                                    id="label_field<?= $fieldUid ?>"
                                                    <?= $label_for ?>
                                                >
                                                    <?= $block->escapeHtml($field->getName()) ?>
                                                    <?php $tooltip = $field->getTooltip(); ?>
                                                    <?= ($tooltip) ? $this->getLayout()->createBlock(
                                                        'VladimirPopov\WebForms\Block\Script\Tooltip',
                                                        null
                                                    )->setField($field)->setTooltip($tooltip)->toHtml() : ''; ?>
                                                </label>
                                            <?php endif; ?>

                                            <?= $field->toHtml(); ?>

                                            <?php if ($field->getValidationAdvice()): ?>
                                                <div
                                                    class="validation-advice display-none"
                                                    id="advice-required-entry-field<?= $fieldUid ?>"
                                                >
                                                    <?= $block->escapeHtml($field->getValidationAdvice()) ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($field->getComment()): ?>
                                                <p
                                                    class="webforms-fields-comment"
                                                    id="comment_field<?= $fieldUid ?>"
                                                    tabindex="0"
                                                >
                                                    <?= $block->escapeHtml(nl2br($field->getComment())) ?>
                                                </p>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php } ?>
                            </fieldset>
                        <?php endforeach; ?>

                        <?= $this->getLayout()->createBlock(
                            'VladimirPopov\WebForms\Block\Script\Gdpr',
                            null,
                            ['data' => [
                                'uid' => $_uid
                            ]]
                        )->setForm($this->getForm())->toHtml();
                        ?>
                        <div
                            id="submit<?= $_uid ?>"
                            class="
                                <?php if ($this->getSubmitVisibility() == 'hidden'): ?>
                                    display-none
                                <?php endif; ?>
                            "
                        >
                            <?php if ($this->getForm()->useCaptcha()): ?>
                                <div class="recaptcha">
                                    <?= $this->getCaptcha()->getHTML() ?>
                                </div>
                            <?php endif; ?>

                            <?php if ($this->honeypot()): ?>
                                <?= $this->getLayout()->createBlock(
                                    'Magento\Framework\View\Element\Template',
                                    null,
                                    [
                                        'data' => [
                                            'webform_id' => $this->getForm()->getId(),
                                            'template' => 'VladimirPopov_WebForms::webforms/scripts/honeypot.phtml'
                                        ]
                                    ]
                                )->toHtml(); ?>
                            <?php endif; ?>
                            <div class="actions-group">
                                <div class="actions-group__handler primary">
                                    <button
                                        type="submit"
                                        class="
                                            button
                                            actions-group__button
                                            contact-us__button
                                        "
                                        id="webform_<?= $_uid ?>_submit_button"
                                        title="<?= $block->escapeHtmlAttr(__($this->getForm()->getSubmitButtonText())) ?>"
                                        name="field[submit]"
                                        onclick="return false;"
                                    >
                                        <?= $block->escapeHtml(__($this->getForm()->getSubmitButtonText())) ?>
                                    </button>
                                </div>
                            </div>
                            <div class="secondary">
                                <div
                                    class="please-wait display-none"
                                    id="webform_<?= $_uid ?>_sending_data"
                                >
                                    <div class="loading-indicator"></div>
                                    <span id="webform_<?= $_uid ?>_progress_text">
                                        <?= $block->escapeHtml(__('Sending...')) ?>
                                    </span>
                                </div>
                            </div>
                            <p class="contact-us__tips">
                                <?= $block->escapeHtml(__('Fields marked * are mandatory')) ?>
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?= $this->getLayout()->createBlock(
                                'VladimirPopov\WebForms\Block\Script\Submit',
                                null,
                                ['data' => [
                                    'uid' => $_uid,
                                    'ajax' => $this->isAjax(),
                                    'scroll_to' => $this->getData('scroll_to'),
                                    'after_submission_form' => $this->getData('after_submission_form')
                                ]]
                            )->setForm($this->getForm())->toHtml();
        ?>

        <?= $this->getLayout()->createBlock(
            'VladimirPopov\WebForms\Block\Script\Logic',
            null,
            ['data' => [
                'uid' => $_uid
            ]]
        )->setForm($this->getForm())->toHtml();
        ?>
    <?php endif; ?>
<?php endif; ?>
