<?php
// TODO: Add proper escaping methods e.g $block->escapeHtmlAttr(), format code, remove echo
/** @var VladimirPopov\WebForms\Block\Form $this */ ?>
<?php $_uid = $this->getUid(); ?>
<div
    class="
        block
        widget
        block-webforms-form
    "
>
    <div class="margin-bottom-xs">
        <strong>
            <?= $this->getForm()->getName() ?>
        </strong>
    </div>
    <div class="block-content">

        <?php
        /** @var VladimirPopov\WebForms\Block\Form $this */

        // in case redirect fails

        if ($this->getRegistry()->registry('redirect_url')) {
        ?>
            <meta http-equiv="refresh" content="0;url=<?= $this->getRegistry()->registry('redirect_url') ?>">
            <script type="text/javascript">
                window.location = '<?= $this->getRegistry()->registry('redirect_url') ?>';
            </script>
        <?php
        }

        // get temporary data
        $tmpData = $this->getSession()->getData('webform_result_tmp_' . $this->getForm()->getId());
        $tmpResult = new \Magento\Framework\DataObject;
        if (!empty($tmpData['field']) && is_array($tmpData['field'])) {
            foreach ($tmpData['field'] as $field_id => $value) {
                $tmpResult->setData('field_' . $field_id, $value);
            }
        }
        if ($this->getForm()->getIsActive() == \VladimirPopov\WebForms\Model\Form::STATUS_DISABLED || !$this->isDirectAvailable()) {
            echo $this->getNotAvailableMessage();
        } else { ?>

            <?php if ($this->isAjax()) { ?>
                <div
                    id="webform_<?= $_uid ?>_success_text"
                    class="std webforms-success-text"
                    style="display:none"
                ></div>
            <?php } ?>

            <?php
            if ($this->getSuccess()) {
            ?>
                <div class="webforms-success-text">
                    <?= $this->getSuccessText() ?>
                </div>
            <?php
            }
            if (!$this->getSuccess() || $this->getData('after_submission_form')) {
            ?>
                <div
                    id="webform_<?= $_uid ?>_form"
                    class="webforms"
                >
                    <?php if ($this->getDescription()) { ?>
                        <div class="webforms-description-text">
                            <?= $this->getDescription(); ?>
                        </div>
                    <?php } ?>

                    <?php if ($this->isAjax()) { ?>
                        <iframe
                            id="webform_<?= $_uid ?>_iframe"
                            name="webform_<?= $_uid ?>_iframe"
                            style="width:0;height:0;border:0;position:absolute"
                        ></iframe>
                    <?php } ?>

                    <form
                        class="form"
                        action="<?= $this->getFormAction() ?>"
                        method="post"
                        name="webform_<?= $_uid ?>"
                        id="webform_<?= $_uid ?>"
                        enctype="<?= $this->getEnctype() ?>"
                        class="webforms-<?= $this->getForm()->getCode() ?>"
                        <?php if ($this->isAjax()) { ?>
                            target="webform_<?= $_uid ?>_iframe"
                        <?php } ?>>

                        <input
                            name="form_key"
                            type="hidden"
                            value="<?php /* @escapeNotVerified */ echo $this->getFormKey() ?>"
                        />
                        <input
                            type="hidden"
                            name="submitForm_<?= $this->getForm()->getId() ?>"
                            value="1"
                        />
                        <input
                            type="hidden"
                            name="webform_id"
                            value="<?= $this->getForm()->getId() ?>"
                        />

                        <?php if (is_array($this->getData('hidden'))) {
                            foreach ($this->getData('hidden') as $key => $value) {
                        ?>
                                <input
                                    ype="hidden"
                                    name="<?= $key ?>"
                                    value="<?= $value ?>"
                                />
                        <?php
                            }
                        } ?>

                        <?php if (count($this->getForm()->_getHidden())) {
                            foreach ($this->getForm()->_getHidden() as $field) {
                                echo $field->toHtml();
                            }
                        } ?>

                        <?php foreach ($this->getForm()->_getFieldsToFieldsets() as $fieldset_id => $fieldset) { ?>

                            <fieldset
                                id="fieldset_<?= $_uid . $fieldset_id ?>"
                                class="
                                    fieldset
                                    fieldset-<?= $fieldset_id ?>
                                    <?php if (!empty($fieldset['css_class'])) echo $fieldset['css_class']; ?>
                                "
                                style="
                                    <?php if (!empty($fieldset['css_style'])) echo $fieldset['css_style'] . ";"; ?>
                                    <?php if ($fieldset['logic_visibility'] == \VladimirPopov\WebForms\Model\Logic::VISIBILITY_HIDDEN) echo 'display:none'; ?>
                                "
                                role="group"
                                aria-labelledby="legend_<?= $_uid . $fieldset_id ?>"
                            >

                                <?php if (!empty($fieldset['name'])) { ?>
                                    <legend
                                        class="legend"
                                        id="legend_<?= $_uid . $fieldset_id ?>"
                                    >
                                        <?= $fieldset['name'] ?>
                                    </legend>
                                <?php } ?>

                                <?php
                                foreach ($fieldset['fields'] as $field) {
                                    // set temporary value
                                    $field->setData('result', $tmpResult);
                                    $field->setData('uid', $_uid);
                                    $field_css_type = 'type-' . str_replace('/', '-', $field->getType());
                                    if ($field->getType() == 'subscribe') $field_css_type .= ' choice';
                                ?>
                                    <div
                                        id="field_<?= $this->getFieldUid($field->getId()) ?>"
                                        class="
                                            field
                                            <?= $field->getCssClassContainer() ?>
                                            <?= $field_css_type ?> webforms-fields-<?= $field->getId() ?>
                                            <?php if ($field->getCode()) { ?> webforms-fields-<?= $field->getCode();} ?>
                                            <?php if ($field->getRequired()) { ?>required<?php } ?>"
                                            <?php if ($field->getData('logic_visibility') == \VladimirPopov\WebForms\Model\Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>
                                        >

                                        <?php if ($field->getType() != 'html' && $field->getType() != 'subscribe' && !$field->getHideLabel()) { ?>
                                            <label
                                                class="label"
                                                id="label_field<?= $this->getFieldUid($field->getId()) ?>"
                                                for="field<?= $this->getFieldUid($field->getId()) ?>"
                                            >
                                                <?= $field->getName() ?>
                                                <?php
                                                $tooltip = $field->getTooltip();
                                                if ($tooltip) {
                                                    echo $this->getLayout()->createBlock(
                                                        'VladimirPopov\WebForms\Block\Script\Tooltip',
                                                        null
                                                    )->setField($field)->setTooltip($tooltip)->toHtml();
                                                }
                                                ?>
                                            </label>
                                        <?php } ?>

                                        <div class="control">
                                            <?= $field->toHtml(); ?>

                                            <?php if ($field->getValidationAdvice()) { ?>
                                                <div
                                                    style="display:none"
                                                    class="validation-advice"
                                                    id="advice-required-entry-field<?= $this->getFieldUid($field->getId()) ?>"
                                                >
                                                    <?= $field->getValidationAdvice() ?>
                                                </div>
                                            <?php } ?>

                                            <?php if ($field->getComment()) { ?>
                                                <p class="webforms-fields-comment">
                                                    <?= nl2br($field->getComment()) ?>
                                                </p>
                                            <?php } ?>
                                        </div>
                                    </div>
                                <?php } ?>
                            </fieldset>

                        <?php } // foreach 'fields_to_fieldsets'
                        ?>

                        <?= $this->getLayout()->createBlock(
                            'VladimirPopov\WebForms\Block\Script\Gdpr',
                            null,
                            ['data' => [
                                'uid' => $_uid
                            ]]
                        )->setForm($this->getForm())->toHtml();
                        ?>

                        <div
                            id="submit<?= $_uid ?>"
                            class="actions-toolbar" <?php if ($this->getSubmitVisibility() == 'hidden') { ?>
                            style="display: none" <?php } ?>
                        >
                            <?php if ($this->getForm()->useCaptcha()) { ?>
                                <div class="recaptcha">
                                    <?= $this->getCaptcha()->getHTML() ?>
                                </div>
                            <?php } ?>

                            <?php if ($this->honeypot()) {
                                echo $this->getLayout()->createBlock(
                                    'Magento\Framework\View\Element\Template',
                                    null,
                                    [
                                        'data' => [
                                            'webform_id' => $this->getForm()->getId(),
                                            'template' => 'VladimirPopov_WebForms::webforms/scripts/honeypot.phtml'
                                        ]
                                    ]
                                )->toHtml();
                            } ?>

                            <div class="primary">
                                <button
                                    type="submit"
                                    class="button action submit primary"
                                    id="webform_<?= $_uid ?>_submit_button"
                                    title="<?= $block->escapeHtmlAttr(__($this->getForm()->getSubmitButtonText())) ?>"
                                    onclick="return false;"
                                >
                                    <?= $block->escapeHtml(__($this->getForm()->getSubmitButtonText())) ?>
                                </button>
                            </div>
                            <div class="secondary">
                                <div
                                    class="please-wait"
                                    id="webform_<?= $_uid ?>_sending_data"
                                    style="display:none;"
                                >
                                    <div class="loading-indicator"></div>
                                    <span id="webform_<?= $_uid ?>_progress_text">
                                        <?= $block->escapeHtml(__('Sending...')) ?>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

                                    <?= $this->getLayout()->createBlock(
                                        'VladimirPopov\WebForms\Block\Script\Submit',
                                        null,
                                        ['data' => [
                                            'uid' => $_uid,
                                            'ajax' => $this->isAjax(),
                                            'scroll_to' => $this->getData('scroll_to'),
                                            'after_submission_form' => $this->getData('after_submission_form')
                                        ]]
                                    )->setForm($this->getForm())->toHtml();
                                    ?>

                <?= $this->getLayout()->createBlock(
                    'VladimirPopov\WebForms\Block\Script\Logic',
                    null,
                    ['data' => [
                        'uid' => $_uid
                    ]]
                )->setForm($this->getForm())->toHtml();
                ?>

        <?php
            } // if(show_success)
        } // is active
        ?>
    </div>
</div>
