<?php
/** @var \Magento\Vault\Block\Customer\CreditCards $block */
$tokens = $block->getPaymentTokens();
?>

<?php if (count($tokens) !== 0) : ?>
    <div
        class="table-wrapper my-credit-cards"
    >
        <tabe
            class="data table table-credit-cards"
            id="my-orders-table"
        >
            <capion
                class="table-caption">
                <?= $block->escapeHtml(__('Stored Payment Methods')) ?>
            </capion>
            <thead>
            <tr>
                <th
                    scope="col"
                    class="col card-number"
                >
                    <?= $block->escapeHtml(__('Card Number')) ?>
                </th>
                <th
                    scope="col"
                    class="col expire"
                >
                    <?= $block->escapeHtml(__('Expiration Date')) ?>
                </th>
                <th
                    scope="col"
                    class="col card-type"
                >
                    <?= $block->escapeHtml(__('Type')) ?>
                </th>
                <th
                    scope="col"
                    class="col actions"
                >
                    &nbsp;
                </th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($tokens as $token) {
                echo $block->renderTokenHtml($token);
            }
            ?>
            </tbody>
        </table>
    </div>

<?php elseif (!$block->isExistsCustomerTokens()) : ?>
    <div
        class="
            message
            info
            empty
        "
    >
        <span>
            <?= $block->escapeHtml(__('You have no stored payment methods.')) ?>
        </span>
    </div>
<?php endif ?>
