<?php
    $_item = $block->getItem();
    $product = $_item->getProduct();
    $isVisibleProduct = $product->isVisibleInSiteVisibility();
    /** @var \Magento\Msrp\Helper\Data $helper */
    $helper = $this->helper('Magento\Msrp\Helper\Data');
    $canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>

<div class="cart-list-item">
    <a
        class="cart-list-item__image"
        href="<?= $block->getProductUrl() ?>"
    >
        <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
    </a>
    <div class="cart-list-item__info">
        <div class="cart-list-item__data">
            <?php if ($block->hasProductUrl()): ?>
                <a
                    href="<?= $block->getProductUrl() ?>"
                    class="link link--invert cart-list-item__name"
                >
                    <?= $block->escapeHtml($block->getProductName()) ?>
                </a>
            <?php else: ?>
                <div class="link link--invert cart-list-item__name">
                    <?= $block->escapeHtml($block->getProductName()) ?>
                </div>
            <?php endif; ?>
            <div class="cart-list-item__details">
                <div class="cart-list-item__qty">
                    <div class="input cart-list-item__qty-wrapper">
                        <label
                            class="label label--hidden"
                            for="cart-<?= $_item->getId() ?>-qty"
                        >
                            <?= __('Qty') ?>
                        </label>
                        <input
                            id="cart-<?= $_item->getId() ?>-qty"
                            name="cart[<?= $_item->getId() ?>][qty]"
                            data-cart-item-id="<?= $_item->getSku() ?>"
                            value="<?= $block->getQty() ?>"
                            type="text"
                            title="<?= $block->escapeHtml(__('Qty')) ?>"
                            class="input__field cart-list-item__qty-input"
                            maxlength="12"
                            data-validate="{
                                required: true,
                                'validate-greater-than-zero': true
                            }"
                            data-role="cart-item-qty"
                        >
                    </div>
                </div>
                <div class="cart-list-item__price">
                    <?php if ($canApplyMsrp): ?>
                        --
                    <?php else: ?>
                        <?= $block->getRowTotalHtml($_item) ?>
                    <?php endif; ?>
                </div>
            </div>
            <div class="products-list-item__messages">
                <div class="product-item-details">
                    <?php if ($messages = $block->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class="item message <?= $message['type'] ?>">
                                <div>
                                    <?= $block->escapeHtml($message['text']) ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock() ?>
                    <?php if ($addInfoBlock): ?>
                        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif; ?>
                </div>
            </div>
            <?php if ($_options = $block->getOptionList()): ?>
                <dl
                    class="
                        list
                        list--description
                        cart-list-item__attributes
                    "
                >
                    <?php foreach ($_options as $_option): ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt class="list__label"><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd class="list__value">
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?= $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?= $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
        </div>
        <div class="cart-list-item__actions">
            <?= $block->getActions($_item) ?>
        </div>
    </div>
</div>
