<?php
/**
 * @see \Magento\GiftCardAccount\Block\Checkout\Cart\Giftcardaccount
 * @var \Magento\GiftCardAccount\Block\Checkout\Cart\Giftcardaccount $block
 */
?>
<div class="col-sm-6 block giftcard gift-card"
     id="block-giftcard"
     data-mage-init='{
         "collapsible":{
             "openedState": "active",
             "saveState": false
         }
     }'
>
    <div data-role="title" class="gift-card__title">
        <span class="gift-card__title-text">
            <?= $block->escapeHtml(__('Gift Cards')); ?>
        </span>
        <svg class="gift-card__title-icon">
            <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#arrow-down'); ?>"></use>
        </svg>
    </div>
    <div data-role="content" class="content gift-card__content" aria-labelledby="block-giftcard-heading">
        <div id="giftcard-balance-lookup"></div>
        <span id="gc-please-wait"
              class="please-wait load indicator"
              style="display: none;"
              data-text="<?= $block->escapeHtml(__('This won\'t take long . . .')); ?>"
        >
              <?= $block->escapeHtml(__('This won\'t take long . . .')); ?>
        </span>

        <?php
            $getGiftCardStatusUrl = $block->escapeHtml($block->getUrl('magento_giftcardaccount/cart/quickCheck',  ['_secure' => true]));
        ?>

        <form class="form form--compact giftcard add gift-card__form"
              id="giftcard-form"
              action="<?= $block->escapeUrl($block->getUrl('magento_giftcardaccount/cart/add')); ?>"
              method="post"
              data-mage-init='{
                  "validation": {"errorClass": "form__error"},
                  "giftCard": {
                      "giftCardCodeSelector": "#giftcard-code",
                      "checkStatus": ".action.check",
                      "giftCardStatusUrl": "<?= $getGiftCardStatusUrl ?>",
                      "giftCardStatusId": "#giftcard-balance-lookup",
                      "giftCardSpinnerId": "#gc-please-wait",
                      "messages": ".page.messages .messages"
                  }
              }'
        >
            <div class="fieldse form__content gift-card__fields">
                <div class="input">
                    <label for="giftcard-code" class="label label--hidden">
                        <?= $block->escapeHtml(__('Enter the gift card code')); ?>
                    </label>
                    <input class="input-text input__field"
                           type="text"
                           id="giftcard-code"
                           name="giftcard_code"
                           data-validate="{'required-entry':true}" value=""
                           placeholder="<?= $block->escapeHtml(__('Enter the gift card code')); ?>"
                    >
                </div>
                <button class="action add button gift-card__button"
                        type="submit"
                        value="<?= $block->escapeHtml(__('Add Gift Card')); ?>"
                >
                    <?= $block->escapeHtml(__('Add Gift Card')); ?>
                </button>
            </div>
            <button class="action check button button--native-link"
                    type="button"
                    value="<?= $block->escapeHtml(__('Check Gift Card status and balance')) ?>"
            >
                <?= $block->escapeHtml(__('Check Gift Card status and balance')) ?>
            </button>
        </form>
    </div>
</div>
