<?php if ($block->isPossibleOnepageCheckout()): ?>
    <button
        type="button"
        data-role="proceed-to-checkout"
        title="<?= __('Proceed to Checkout') ?>"
        data-mage-init='{
            "Magento_Checkout/js/proceed-to-checkout": {
                "checkoutUrl":"<?= $block->getCheckoutUrl(); ?>"
            }
        }'
        class="
            action
            primary
            button
            button--fluid
            cart-summary__checkout-button
            checkout<?= ($block->isDisabled()) ? ' disabled' : ''; ?>
        "
        data-testid="proceed-to-checkout-button"
        <?= ($block->isDisabled()) ? 'disabled="disabled"' : ''; ?>
    >
        <?= __('Proceed to Checkout'); ?>
    </button>
<?php endif; ?>
