<?php if ($block->isPossibleOnepageCheckout()): ?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>"
            data-mage-init='{
                "Magento_Checkout/js/proceed-to-checkout": {
                    "checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl(); ?>"
                }
            }'
            class="
                action
                primary
                button
                button--fluid
                cart-summary__checkout-button
                checkout<?php echo($block->isDisabled()) ? ' disabled' : ''; ?>
            "
            <?= ($block->isDisabled()) ? 'disabled="disabled"' : ''; ?>
    >
        <?= /* @escapeNotVerified */ __('Proceed to Checkout'); ?>
    </button>
<?php endif; ?>
