<?php
/**
 * @var $block \Yotpo\Yotpo\Block\Yotpo
 */
?>
<?php if (!($block->isEnabled() && ($block->isRenderBottomline() || $block->isRenderBottomlineQna()))) {
    return;
} ?>
<!-- Yotpo - BottomLine -->
<div class="yotpoBottomLine">
    <?php if ($block->isRenderBottomline()) : ?>
        <div class="yotpo bottomLine bottomline-position"
            data-product-id="<?= $block->getProductId() ?>"
            data-url="<?= $block->getProductUrl() ?>">
        </div>
    <?php endif; ?>
    <?php if ($block->isRenderBottomlineQna()) : ?>
        <div class="yotpo QABottomLine"
            data-appkey="<?= $block->getAppKey() ?>"
            data-product-id="<?= $block->getProductId() ?>">
        </div>
    <?php endif; ?>
</div>
<!--/ Yotpo - BottomLine -->
