<?php
/**
 * @var $block \Yotpo\Yotpo\Block\Yotpo
 */
?>
<?php if (!($block->isEnabled() && ($block->isRenderBottomline() || $block->isRenderBottomlineQna()))) {
    return;
} ?>
<!-- Yotpo - BottomLine -->
<div
    class="
        yotpoBottomLine
        product-view__yotpo-summary
    "
    data-mage-init='{"reviewsNav": {}}'
>
    <?php if ($block->isRenderBottomline()): ?>
        <div
            class="
                yotpo
                bottomLine
                bottomline-position
            "
            data-product-id="<?= $block->escapeHtmlAttr($block->getProductId()) ?>"
            data-url="<?= $block->escapeUrl($block->getProductUrl()) ?>"
        >
        </div>
    <?php endif; ?>
    <?php if ($block->isRenderBottomlineQna()): ?>
        <div
            class="yotpo QABottomLine"
            data-appkey="<?= $block->escapeHtmlAttr($block->getAppKey()) ?>"
            data-product-id="<?= $block->escapeHtmlAttr($block->getProductId()) ?>"
        >
        </div>
    <?php endif; ?>
</div>
<!--/ Yotpo - BottomLine -->
