<?php $_product = $block->getProduct() ?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="product-view__stock-status">
            <?= $block->escapeHtml(__('In stock')) ?>
        </div>
    <?php else: ?>
        <div
            class="
                product-view__stock-status
                product-view__stock-status--out-of-stock
            "
        >
            <?= $block->escapeHtml(__('Out of stock')) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?= $block->getChildHtml('bundle_prices') ?>
