<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Review\Block\Customer\ListCustomer $block */
?>
<div class="users-account">
    <?php if ($block->getReviews() && count($block->getReviews())): ?>
        <h2>
            <?php /* @escapeNotVerified */ echo __('Product Reviews'); ?>
        </h2>
        <div class="table-wrapper reviews">
            <table class="data table table-reviews"
                   id="my-reviews-table"
                   aria-label="<?php /* @escapeNotVerified */ echo __('Product Reviews'); ?>"
            >
                <thead>
                    <tr>
                        <th scope="col" class="date">
                            <?php /* @escapeNotVerified */ echo __('Created'); ?>
                        </th>
                        <th scope="col" class="item">
                            <?php /* @escapeNotVerified */ echo __('Product Name'); ?>
                        </th>
                        <th scope="col" class="summary">
                            <?php /* @escapeNotVerified */ echo __('Rating'); ?>
                        </th>
                        <th scope="col" class="description">
                            <?php /* @escapeNotVerified */ echo __('Review') ?>
                        </th>
                        <th scope="col" class="actions">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($block->getReviews() as $_review): ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Created')); ?>"
                            class="date"
                        >
                            <?php /* @escapeNotVerified */ echo $block->dateFormat($_review->getReviewCreatedAt()); ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>"
                            class="item"
                        >
                            <strong>
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductLink(); ?>id/<?php /* @escapeNotVerified */ echo $_review->getEntityPkValue(); ?>">
                                    <?php echo $block->escapeHtml($_review->getName()); ?>
                                </a>
                            </strong>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Rating')); ?>"
                            class="summary"
                        >
                        <?php if ($_review->getSum()): ?>
                            <div class="rating">
                                <div class="rating__summary">
                                    <svg title="icon rating summary"
                                         class="rating__icon"
                                    >
                                        <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#stars'); ?>"></use>
                                    </svg>
                                    <div class="rating__results"
                                         title="rating <?php /* @escapeNotVerified */ echo($_review->getSum() / $_review->getCount()); ?>%"
                                         style="width:<?php /* @escapeNotVerified */ echo($_review->getSum() / $_review->getCount()); ?>%;"
                                    >
                                        <svg title="icon rating results"
                                             class="rating__icon rating__icon--results"
                                        >
                                            <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#stars'); ?>"></use>
                                        </svg>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Review')); ?>"
                            class="description"
                        >
                            <?php echo $this->helper('Magento\Review\Helper\Data')->getDetailHtml($_review->getDetail()); ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')); ?>"
                            class="actions"
                        >
                            <a href="<?php /* @escapeNotVerified */ echo $block->getReviewLink() ?>id/<?php /* @escapeNotVerified */ echo $_review->getReviewId() ?>"
                               class="action more"
                            >
                                <?php /* @escapeNotVerified */ echo __('See Details'); ?>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php if ($block->getToolbarHtml()): ?>
            <div class="toolbar products-reviews-toolbar bottom">
                <?php echo $block->getToolbarHtml() ?>
            </div>
        <?php endif; ?>
    <?php else: ?>
        <div class="message info empty">
            <div class="message__container">
                <p class="message__text">
                    <?php /* @escapeNotVerified */ echo __('You have submitted no reviews.'); ?>
                </p>
            </div>
        </div>
    <?php endif; ?>
    <div class="actions-toolbar">
        <a class="action back actions-toolbar__button"
           href="<?php echo $block->escapeUrl($block->getBackUrl()); ?>"
        >
            <?php /* @escapeNotVerified */ echo __('Back'); ?>
        </a>
    </div>
</div>
