<?php if ($block->getReviews() && count($block->getReviews())): ?>
    <div class="dashboard-table">
        <div class="dashboard-table__header">
            <h3 class="dashboard-table__title">
                <?= /* @escapeNotVerified */ __('Product Reviews') ?>
            </h3>
        </div>

        <div class="dashboard-table__content">
            <table class="table" id="my-reviews-table">
                <thead>
                    <tr>
                        <th scope="col" class="col date">
                            <?= /* @escapeNotVerified */ __('Created') ?>
                        </th>

                        <th scope="col" class="col item">
                            <?= /* @escapeNotVerified */ __('Product Name') ?>
                        </th>

                        <th scope="col" class="col summary">
                            <?= /* @escapeNotVerified */ __('Rating') ?>
                        </th>

                        <th scope="col" class="col description">
                            <?= /* @escapeNotVerified */ __('Review') ?>
                        </th>

                        <th scope="col" class="col actions">
                            &nbsp;
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($block->getReviews() as $_review): ?>
                        <?php
                            $getDetails     = $this->helper('Magento\Review\Helper\Data')
                                                   ->getDetailHtml($_review->getDetail());
                            $getProductLink = $block->getProductLink().'id'.$_review->getEntityPkValue();
                            $getDetailsLink = $block->getReviewLink().'id/'.$_review->getReviewId();
                        ?>

                        <tr>
                            <td data-th="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Created')) ?>"
                                class="col date"
                            >
                                <?= /* @escapeNotVerified */ $block->dateFormat($_review->getReviewCreatedAt()); ?>
                            </td>

                            <td data-th="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Product Name')) ?>"
                                class="col item"
                            >
                                <strong class="product-name">
                                    <a href="<?= /* @escapeNotVerified */ $getProductLink ?>" class="link">
                                        <?= /* @escapeNotVerified */ $block->escapeHtml($_review->getName()) ?>
                                    </a>
                                </strong>
                            </td>

                            <td data-th="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Rating')) ?>"
                                class="col summary"
                            >
                                <?php if ($_review->getSum()): ?>
                                    <?php $getPercentRating = ($_review->getSum() / $_review->getCount()).'%'; ?>

                                    <div class="rating__summary">
                                        <span class="rating__fill"
                                              style="width:<?php /* @escapeNotVerified */ $getPercentRating; ?>;"
                                        >
                                            <span>
                                                <?= /* @escapeNotVerified */ $getPercentRating; ?>
                                            </span>
                                        </span>
                                    </div>
                                <?php endif; ?>
                            </td>

                            <td data-th="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Review')) ?>"
                                class="col description"
                            >
                                <?= /* @escapeNotVerified */ $getDetails; ?>
                            </td>

                            <td data-th="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Actions')) ?>"
                                class="col actions"
                            >
                                <a href="<?= /* @escapeNotVerified */ $getDetailsLink ?>" class="link more">
                                    <?= /* @escapeNotVerified */ __('See Details') ?>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <?php if ($block->getToolbarHtml()): ?>
        <div class="toolbar products-reviews-toolbar bottom">
            <?= /* @escapeNotVerified */$block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty">
        <?= /* @escapeNotVerified */ __('You have submitted no reviews.') ?>
    </div>
<?php endif; ?>

<div class="action">
    <div class="action__handler">
        <a class="link action__link back"
           href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getBackUrl()) ?>"
        >
            <?= /* @escapeNotVerified */ __('Back') ?>
        </a>
    </div>
</div>
