<?php
/** @var $block \Magento\Review\Block\Customer\Recent */
?>

<?php if ($block->getReviews() && count($block->getReviews())): ?>
    <div class="dashboard-items">
        <div class="dashboard-table__header">
            <h3 class="dashboard-table__title">
                <?= /* @escapeNotVerified */  __('My Recent Reviews') ?>
            </h3>

            <a class="link dashboard-table__link"
               href="<?= /* @escapeNotVerified */  $block->getAllReviewsUrl() ?>"
            >
               <?= /* @escapeNotVerified */  __('View All') ?>
            </a>
        </div>

        <div class="grid dashboard-items__content">
            <?php foreach ($block->getReviews() as $_review): ?>
                <div class="dashboard-items__item grid__column grid__column--1-4">
                    <h4>
                        <a href="<?= /* @escapeNotVerified */  $block->getReviewUrl($_review->getReviewId()) ?>">
                            <?= /* @escapeNotVerified */ $block->escapeHtml($_review->getName()) ?>
                        </a>
                    </h4>

                    <?php if ($_review->getSum()): ?>
                        <?php $rating = $_review->getSum() / $_review->getCount() ?>

                        <span class="review__description">
                            <?= /* @escapeNotVerified */  __('Rating') ?>:
                        </span>

                        <div class="rating__summary" title="<?= /* @escapeNotVerified */  $rating; ?>%">
                            <span class="rating__fill" style="width:<?= /* @escapeNotVerified */  $rating; ?>%">
                                <span>
                                    <?= /* @escapeNotVerified */ $rating; ?>%
                                </span>
                            </span>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
