<?php
    $product = $block->getProductData();
?>
<?php if ($product->getId()): ?>
    <h3 class="dashboard__title">
        <?= /* @escapeNotVerified */  __('Review Details') ?>
    </h3>

    <div class="product dashboard__product">
        <a class="product__link" href="<?= /* @escapeNotVerified */ $product->getProductUrl() ?>">
            <div class="product__img-box">
                <?php /* customer_account_product_review_page */ ?>
                <?= /* @escapeNotVerified */
                    $block->getImage($block->getProductData(), 'customer_account_product_review_page')
                          ->toHtml()
                ?>
            </div>
        </a>

        <h2 class="product__name dashboard__item">
            <?= /* @escapeNotVerified */ $block->escapeHtml($product->getName()) ?>
        </h2>

        <?php if ($block->getRating() && $block->getRating()->getSize()): ?>
            <?= /* @escapeNotVerified */ $block->getReviewsSummaryHtml($product) ?>
        <?php endif; ?>

        <h4 class="dashboard__title">
            <?= /* @escapeNotVerified */ __('Your Review'); ?>
        </h4>

        <div class="review dashboard__item">
            <?php if ($block->getRating() && $block->getRating()->getSize()): ?>
                <?php foreach ($block->getRating() as $_rating): ?>
                    <?php if ($_rating->getPercent()): ?>
                        <?php $rating = ceil($_rating->getPercent()) ?>

                        <div class="review__divider">
                            <span class="review__description">
                                <?= /* @escapeNotVerified */ $block->escapeHtml($_rating->getRatingCode()).':' ?>
                            </span>

                            <div class="rating__summary " title="<?= /* @escapeNotVerified */  $rating; ?>%">
                                <span class="rating__fill" style="width:<?= /* @escapeNotVerified */  $rating; ?>%">
                                    <span>
                                        <?= /* @escapeNotVerified */ $rating; ?>%
                                    </span>
                                </span>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>

            <h5 class="review__title">
                <?= /* @escapeNotVerified */ $block->escapeHtml($block->getReviewData()->getTitle()) ?>
            </h5>

            <div class="review__divider">
                <?= /* @escapeNotVerified */ nl2br($block->escapeHtml($block->getReviewData()->getDetail())) ?>
            </div>

            <div class="review__divider review__date">
                <?= /* @escapeNotVerified */
                    __('Submitted on %1', '<time class="date">' . $block->dateFormat($block->getReviewData()->getCreatedAt()) . '</time>')
                ?>
            </div>
        </div>
    </div>

    <div class="action">
        <div class="action__handler">
            <a class="link action__link back"
               href="<?= /* @escapeNotVerified */ $block->getBackUrl() ?>"
            >
                <?= /* @escapeNotVerified */  __('Back to My Reviews') ?>
            </a>
        </div>
    </div>
<?php endif; ?>
