<?php /** @var \Amasty\Gdpr\Block\CheckboxNewsletter $block */ ?>
<div
    class="
        newsletter__agreements
        input
        gdpr
        required
    "
    id="amprivacy-checkbox"
    data-role="amasty-gdpr-consent"
>
    <div class="checkbox newsletter__checkbox">
        <input
            type="checkbox"
            name="amgdpr_agree_newsletter"
            value="1"
            id="amgdpr_agree_newsletter"
            class="checkbox__field"
            data-validate="{required:true}"
        />

        <svg
            class="
                checkbox__icon
                checkbox__icon--checked
            "
            role="presentation"
            focusable="false"
        >
            <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
        </svg>

        <svg
            class="
                checkbox__icon
                checkbox__icon--unchecked
            "
            role="presentation"
            focusable="false"
        >
            <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
        </svg>

        <label
            for="amgdpr_agree_newsletter"
            class="checkbox__label"
        >
            <?= $block->escapeHtml($block->getConsentText($consent), ['a']) ?>
        </label>
    </div>
</div>
