<?php /** @var \Amasty\Gdpr\Block\Checkbox $block */ ?>
<div
    class="
        input
        gdpr
        required
    "
    id="amprivacy-checkbox"
    data-role="amasty-gdpr-consent"
>
    <div class="checkbox">
        <input
            type="checkbox"
            name="amgdpr_agree"
            value="1"
            id="amgdpr_agree"
            class="checkbox__field"
            data-validate="{required:true}"
        >

        <svg
            class="
                checkbox__icon
                checkbox__icon--checked
            "
            role="presentation"
            focusable="false"
        >
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
        </svg>

        <svg
            class="
                checkbox__icon
                checkbox__icon--unchecked
            "
            role="presentation"
            focusable="false"
        >
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
        </svg>

        <label
            for="amgdpr_agree"
            class="checkbox__label"
        >
            <?= $block->getConsentText() ?>
        </label>
    </div>
</div>
