<?php
/** @var $block \Magento\Catalog\Block\Product\View\Addto\Compare */
?>
<?php $viewModel = $block->getData('addToCompareViewModel'); ?>
<?php if ($viewModel->isAvailableForCompare($block->getProduct())) :?>
    <button
        class="
            product-view__action
            product-view__action--button
            product-view__action--compare
        "
        data-post='<?= $block->getPostDataParams() ?>'
        data-role="add-to-links"
        type="button"
        data-testid="product-compare-button"
    >
        <svg class="icon">
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#compare')); ?>"></use>
        </svg>
    </button>
<?php endif; ?>