<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Catalog\Product\View\Addto\Compare */
?>

<button
    class="
        product-view__action
        product-view__action--button
        product-view__action--compare
    "
    data-post='<?= $block->getPostDataParams() ?>'
    data-role="add-to-links"
    type="button"
    data-testid="product-compare-button"
>
    <svg class="icon">
        <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#compare'); ?>"></use>
    </svg>
</button>
