<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Catalog\Product\View\Addto\Compare */
$additionalClass = $block->getAdditionalClass();
?>

<button
    class="
        button
        button--icon
        product-view__button
        <?= $block->escapeHtmlAttr($additionalClass) ?>
    "
    data-post='<?= $block->escapeHtmlAttr($block->getPostDataParams()) ?>'
    data-role="add-to-links"
    type="button"
    data-testid="product-compare-button"
    aria-label="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>"
    title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>"
>
    <svg
        class="icon button__icon"
        role="presentation"
        focusable="false"
    >
        <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#compare')); ?>"></use>
    </svg>

    <span class="button__text">
        <?= $block->escapeHtml(__('Compare')) ?>
    </span>
</button>
