<?php
// @codingStandardsIgnoreFile
/** @var $block Magento\Company\Block\Company\Management\Info */
?>
<?php if ($block->hasCustomerCompany() && $block->isRoleEditAllowed()): ?>
    <div class="dashboard-actions-toolbar roles-and-permissions__actions">
        <button
            type="button"
            title="<?= $block->escapeHtml(__('Add New Role')) ?>"
            class="button dashboard-actions-toolbar__item"
            onclick="location = ('<?= $block->getUrl('*/*/edit') ?>')"
            data-mobile-label="<?= $block->escapeHtml(__('Add New Role')) ?>"
        >
            <?= $block->escapeHtml(__('Add New Role')) ?>
        </button>
    </div>
<?php endif; ?>
