<?php
/** @var $block Magento\Company\Block\Company\Management\Info */
?>
<?php if ($block->hasCustomerCompany() && $block->isRoleEditAllowed()): ?>
    <div class="actions-group margin-vc-sm">
        <div class="actions-group__handler">
            <button
                type="button"
                title="<?= $block->escapeHtmlAttr(__('Add New Role')) ?>"
                class="
                    button
                    button--secondary
                    action
                    primary
                "
                onclick="location = ('<?= $block->escapeJs($block->escapeUrl($block->getUrl('*/*/edit'))) ?>')"
                data-mobile-label="<?= $block->escapeHtmlAttr(__('Add New Role')) ?>"
            >
                <?= $block->escapeHtml(__('Add New Role')) ?>
            </button>
        </div>
    </div>
<?php endif; ?>
