<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Company\Block\Company\Management\Info */
?>
<?php if ($block->hasCustomerCompany() && $block->isRoleEditAllowed()) : ?>
    <div class="actions">
        <button type="button"
                title="<?= $block->escapeHtmlAttr(__('Add New Role')) ?>"
                class="action primary"
                onclick="location = ('<?= $block->escapeJs($block->escapeUrl($block->getUrl('*/*/edit'))) ?>')"
                data-mobile-label="<?= $block->escapeHtmlAttr(__('Add New Role')) ?>">
            <span><?= $block->escapeHtml(__('Add New Role')) ?></span>
        </button>
    </div>
<?php endif; ?>
