<div class="dashboard-table">
<?php $_order = $block->getOrder(); ?>
    <div class="dashboard-table__header">
        <h5 class="heading heading--fifth-level dashboard-table__title">
            <?php /* @escapeNotVerified */ echo __('Shipments') ?>
        </h5>

        <?php if ($_order->getTracksCollection()->count()) : ?>
            <?php echo $block->getChildHtml('track-all-link') ?>
        <?php endif; ?>

        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <a class="link dashboard-table__link" 
               href="<?php /* @escapeNotVerified */ echo $block->getPrintAllShipmentsUrl($_order) ?>"
            >
                <?php /* @escapeNotVerified */ echo __('Print All Shipments') ?>
            </a>
        <?php endif; ?>
    </div>

    <?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>
        <div class="dashboard-table__content">
            <div class="dashboard-table__header">
                <strong>
                    <?php /* @escapeNotVerified */ echo __('Shipment #') ?><?php /* @escapeNotVerified */ echo $_shipment->getIncrementId(); ?>
                </strong>

                <a href="<?php /* @escapeNotVerified */ echo $block->getPrintShipmentUrl($_shipment) ?>"
                   onclick="this.target='_blank'"
                   class="link"
                >
                    <?php /* @escapeNotVerified */ echo __('Print Shipment') ?>
                </a>

                <a href="#"
                   data-mage-init='{"popupWindow": {"windowURL":"<?php /* @escapeNotVerified */ echo $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($_shipment) ?>","windowName":"trackshipment","width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
                   title="<?php /* @escapeNotVerified */ echo __('Track this shipment') ?>"
                   class="link"
                >
                    <?php /* @escapeNotVerified */ echo __('Track this shipment') ?>
                </a>
            </div>

            <?php $tracks = $_shipment->getTracksCollection(); ?>

            <?php if ($tracks->count()): ?>
                <strong>
                    <?php /* @escapeNotVerified */ echo __('Tracking Number(s):') ?>
                </strong>
                
                <ul class="list" id="my-tracking-table-<?php /* @escapeNotVerified */ echo $_shipment->getId(); ?>">
                    <?php
                        $i = 1;
                        $_size = $tracks->count();
                    ?>
                    <?php foreach ($tracks as $track): ?>
                        <li class="list__item">
                            <?php if ($track->isCustom()): ?>
                                <?php echo $block->escapeHtml($track->getNumber()) ?>
                            <?php else: ?>
                                <a href="#"
                                   data-mage-init='{"popupWindow": {"windowURL":"<?php /* @escapeNotVerified */ echo $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($track) ?>","windowName":"trackorder","width":800,"height":600,"left":0,"top":0,"resizable":1,"scrollbars":1}}'
                                   class="action track"
                                >
                                    <?php echo $block->escapeHtml($track->getNumber()) ?>
                                </a>
                                <?php endif; ?>
                                
                                <?php if ($i != $_size): ?>
                                , 
                                <?php endif; ?>
                            <?php $i++; ?>
                        </li>
                    <?php endforeach; ?>                    
                </ul>
            <?php  endif; ?>

            <table class="table" id="my-shipment-table-<?php /* @escapeNotVerified */ echo $_shipment->getId(); ?>">
                <thead>
                    <tr>
                        <th class="name">
                            <?php /* @escapeNotVerified */ echo __('Product Name') ?>
                        </th>

                        <th class="sku">
                            <?php /* @escapeNotVerified */ echo __('SKU') ?>
                        </th>

                        <th class="qty">
                            <?php /* @escapeNotVerified */ echo __('Qty Shipped') ?>
                        </th>
                    </tr>
                </thead>

                <?php $_items = $_shipment->getAllItems(); ?>
                <?php $_count = count($_items) ?>

                <?php foreach ($_items as $_item): ?>
                    <?php if ($_item->getOrderItem()->getParentItem()): continue; endif; ?>

                    <tbody>
                        <?php echo $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endforeach; ?>
            </table>
            <?php echo $block->getCommentsHtml($_shipment)?>
        </div>
    <?php endforeach; ?>
</div>
