<div class="dashboard-table dashboard-table--tab">
    <?php $_order = $block->getOrder(); ?>
    <?php if ($_order->getTracksCollection()->count()): ?>
        <?= $block->getChildHtml('track-all-link') ?>
    <?php endif; ?>

    <?php if (sizeof($_order->getItems()) > 0): ?>
        <a class="link dashboard-table__link"
            href="<?=  $block->getPrintAllShipmentsUrl($_order) ?>"
        >
            <?=  __('Print All Shipments') ?>
        </a>
    <?php endif; ?>

    <?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>
        <div class="dashboard-table__content">
            <div class="dashboard-table__header">
                <?php
                    $getTrackingUrl = $this->helper('Magento\Shipping\Helper\Data')
                                           ->getTrackingPopupUrlBySalesModel($_shipment);
                ?>

                <h3 class="dashboard-table__title">
                    <?=  __('Shipment #') ?>
                    <?=  $_shipment->getIncrementId(); ?>
                </h3>

                <a href="<?=  $block->getPrintShipmentUrl($_shipment) ?>"
                   onclick="this.target='_blank'"
                   class="link dashboard-table__spacer"
                >
                    <?=  __('Print Shipment') ?>
                </a>

                <a href="#"
                   data-mage-init='{
                       "popupWindow": {
                           "windowURL": "<?= $getTrackingUrl ?>",
                           "windowName": "trackshipment",
                           "width":800,
                           "height":600,
                           "top":0,
                           "left":0,
                           "resizable":1,
                           "scrollbars":1
                        }
                   }'
                   title="<?=  __('Track this shipment') ?>"
                   class="link"
                >
                    <?=  __('Track this shipment') ?>
                </a>
            </div>

            <?php $tracks = $_shipment->getTracksCollection(); ?>

            <?php if ($tracks->count()): ?>
                <strong>
                    <?=  __('Tracking Number(s):') ?>
                </strong>

                <ul class="list" id="my-tracking-table-<?=  $_shipment->getId(); ?>">
                    <?php
                        $i = 1;
                        $_size = $tracks->count();
                    ?>
                    <?php foreach ($tracks as $track): ?>
                        <?php
                            $getPopupUrl = $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($track);
                        ?>

                        <li class="list__item">
                            <?php if ($track->isCustom()): ?>
                                <?= $block->escapeHtml($track->getNumber()) ?>
                            <?php else: ?>
                                <a href="#"
                                   data-mage-init='{
                                        "popupWindow": {
                                            "windowURL": "<?= $getPopupUrl ?>",
                                            "windowName":"trackorder",
                                            "width":800,
                                            "height":600,
                                            "left":0,
                                            "top":0,
                                            "resizable":1,
                                            "scrollbars":1
                                        }
                                    }'
                                   class="action track"
                                >
                                    <?= $block->escapeHtml($track->getNumber()) ?>
                                </a>
                            <?php endif; ?>

                            <?php if ($i != $_size): ?>
                            ,
                            <?php endif; ?>
                            <?php $i++; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php  endif; ?>

            <table class="table" id="my-shipment-table-<?=  $_shipment->getId(); ?>">
                <thead>
                    <tr>
                        <th class="name">
                            <?=  __('Product Name') ?>
                        </th>

                        <th class="sku">
                            <?=  __('SKU') ?>
                        </th>

                        <th class="qty">
                            <?=  __('Qty Shipped') ?>
                        </th>
                    </tr>
                </thead>

                <?php $_items = $_shipment->getAllItems(); ?>
                <?php $_count = count($_items); ?>

                <?php foreach ($_items as $_item): ?>
                    <?php if ($_item->getOrderItem()->getParentItem()): continue; endif; ?>

                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endforeach; ?>
            </table>
            <?= $block->getCommentsHtml($_shipment) ?>
        </div>
    <?php endforeach; ?>
</div>
