<div
    class="actions-toolbar requisition-view-buttons"
    data-mage-init='{"requisitionActions":{ }}'
>
    <div class="primary actions-group">
        <div class="actions-group__handler">
            <?php if ($block->getItemCount()): ?>
                <!-- ko scope: 'requisition.list.items.massaction.addtocart' -->
                    <button
                        type="button"
                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                        class="
                            button
                            button--add-to
                            actions-group__button
                            action
                            primary
                            disabled
                        "
                        data-bind="
                            css: {
                                disabled: !isEnable()
                            },
                            click: applyAction.bind($data, {
                                requisition_id: '<?= (int) $block->getRequest()->getParam('requisition_id') ?>'
                            })
                        "
                        data-mobile-label="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                    >
                        <?= $block->escapeHtml(__('Add to Cart')) ?>
                    </button>
                <!-- /ko -->
            <script type="text/x-magento-init">
                {
                    "*": {
                        "Magento_Ui/js/core/app": {
                            "components": {
                                "requisition.list.items.massaction.addtocart": {
                                    "component": "Magento_RequisitionList/js/requisition/items/grid/massaction/add-to-cart",
                                    "selectProvider": "requisition.item.grid.selection.provider",
                                    "hasConfirm": true,
                                    "action": "<?= $block->escapeUrl($block->getUrl('requisition_list/item/addToCart')) ?>"
                                }
                            }
                        }
                    }
                }
            </script>
            <button
                type="button"
                title="<?= $block->escapeHtmlAttr(__('Update List')) ?>"
                class="
                    button
                    button--secondary
                    actions-group__button
                    action
                    secondary
                "
                data-action="update-list"
                data-mobile-label="<?= $block->escapeHtmlAttr(__('Update List')) ?>"
                data-update-list='{
                    "updateUrl":"<?= $block->escapeUrl($block->getUrl('*/item/update', [
                        'requisition_id' => (int) $block->getRequest()->getParam('requisition_id')
                    ])) ?>"
                }'
            >
                <?= $block->escapeHtml(__('Update List')) ?>
            </button>
            <?php endif ?>
            <button
                type="button"
                title="<?= $block->escapeHtmlAttr(__('Delete Requisition List')) ?>"
                class="
                    button
                    button--secondary
                    actions-group__button
                    action
                    secondary delete
                "
                data-action="remove-list"
                data-mobile-label="<?= $block->escapeHtmlAttr(__('Delete Requisition List')) ?>"
                data-delete-list='{
                    "deleteUrl":"<?= $block->escapeUrl($block->getUrl('*/requisition/delete', [
                        'requisition_id' => (int) $block->getRequest()->getParam('requisition_id')
                    ])) ?>",
                    "listName": "<?= $block->escapeHtmlAttr($block->getRequisitionList()->getName()) ?>"
                }'
            >
                <?= $block->escapeHtml(__('Delete Requisition List')) ?>
            </button>
        </div>
        <div class="actions-group__handler">
            <a
                href="<?= $block->escapeUrl($block->getUrl('customer/account')); ?>"
                class="
                    link
                    actions-group__link
                    action
                    back
                "
            >
                <?= $block->escapeHtml(__('Back')) ?>
            </a>
        </div>
    </div>
</div>
