<?php
/**
 * @var $block \Magento\RequisitionList\Block\Requisition\View\Items\Grid
 */

$itemsList =  $block->getRequisitionListItems();
?>
<div
    class="requisition-content"
    data-mage-init='{"requisitionActions":{ }}'
>
    <?= $block->getChildHtml('requisition.management') ?>
    <?php if (empty($itemsList)): ?>
        <div
            class="
                message
                info
                empty
            "
        >
            <?= $block->escapeHtml(__('You have no items in this requisition list.'))  ?>
        </div>
    <?php else: ?>
        <div
            class="
                requisition-grid
                table-wrapper
                margin-bottom-m
            "
        >
            <form
                action="<?= $block->escapeUrl($block->getUrl('*/item/update', [
                    'requisition_id' => (int) $block->getRequest()->getParam('requisition_id')
                ])) ?>"
                method="post"
                data-mage-init='{"validation":{}}'
                id="form-requisition-list"
            >
                <table class="data-table table">
                    <thead>
                        <tr class="headings">
                            <th class="col number">
                                <span>
                                    #
                                </span>
                            </th>
                            <th
                                class="col product"
                                colspan="2"
                            >
                                <span data-print-label="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
                                    <?= $block->escapeHtml(__('Item')) ?>
                                </span>
                            </th>
                            <th class="col price">
                                <span>
                                    <?= $block->escapeHtml(__('Price')) ?>
                                </span>
                            </th>
                            <th class="col qty">
                                <span>
                                    <?= $block->escapeHtml(__('Qty')) ?>
                                </span>
                            </th>
                            <th class="col subtotal">
                                <span>
                                    <?= $block->escapeHtml(__('Subtotal')) ?>
                                </span>
                            </th>
                            <th class="col action">
                                <span>
                                    <?= $block->escapeHtml(__('Action')) ?>
                                </span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i = 0 ?>
                        <?php foreach ($itemsList as $item): $i++ ?>
                            <tr
                                class="_<?= ($i % 2) ? 'even' : 'odd' ?> item"
                                data-product-id="<?= (int) $item->getId() ?>"
                            >
                                <td
                                    class="col number"
                                    data-th="<?= $block->escapeHtmlAttr(__('Number')) ?>"
                                >
                                    <?= (int) $i ?>
                                </td>
                                <?php
                                    $block->getChildBlock('requisition.list.item.view')
                                        ->setItem($item)
                                        ->setItemErrors($block->getItemErrors($item));
                                ?>
                                <?= $block->getChildHtml('requisition.list.item.view', false) ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </form>
        </div>
    <?php endif; ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "requisition.item.grid.selection.provider": {
                        "component": "Magento_RequisitionList/js/requisition/items/grid/selection-provider",
                        "selectionSelector": "[data-action='requisition-item-check']"
                    }
                }
            }
        }
    }
</script>
