<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Magento\RequisitionList\Block\Requisition\View\Items\Grid
 */

$itemsList =  $block->getRequisitionListItems();

?>
<div
    class="requisition-list-view"
    data-mage-init='{ "requisitionActions": {} }'
>
    <?= $block->getChildHtml('requisition.management') ?>
    <?php if (empty($itemsList)): ?>
        <div class="message info empty">
            <?= $escaper->escapeHtml(__('You have no items in this requisition list.')) ?>
        </div>
    <?php else: ?>
        <div class="requisition-grid table-wrapper">
            <form
                action="<?= $escaper->escapeUrl($block->getUrl('*/item/update', [
                    'requisition_id' => $block->getRequest()->getParam('requisition_id')
                ])) ?>"
                method="post"
                data-mage-init='{"validation":{}}'
                id="form-requisition-list"
            >
                <table class="data-table table">
                    <thead>
                        <tr class="headings">
                            <th class="col number">
                                <span>#</span>
                            </th>
                            <th class="col product" colspan="2">
                                <span
                                    data-print-label="<?= $escaper->escapeHtml(__('Product Name')) ?>"
                                >
                                    <?= $escaper->escapeHtml(__('Item')) ?>
                                </span>
                            </th>
                            <th class="col price">
                                <?= $escaper->escapeHtml(__('Price')) ?>
                            </th>
                            <th class="col qty">
                                <?= $escaper->escapeHtml(__('Qty')) ?>
                            </th>
                            <th class="col subtotal action">
                                <?= $escaper->escapeHtml(__('Subtotal')) ?>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i = 0 ?>
                        <?php foreach ($itemsList as $item):$i++ ?>
                            <tr
                                class="_<?= ($i % 2) ? 'even' : 'odd' ?> item"
                                data-product-id="<?= $escaper->escapeHtml($item->getId()) ?>"
                            >
                                <td class="col number">
                                    <?= $i ?>
                                </td>
                                <?php
                                    $block->getChildBlock('requisition.list.item.view')
                                        ->setItem($item)
                                        ->setItemErrors($block->getItemErrors($item));
                                ?>
                                <?= $block->getChildHtml('requisition.list.item.view', false) ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </form>
        </div>
    <?php endif; ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "requisition.item.grid.selection.provider": {
                        "component": "Magento_RequisitionList/js/requisition/items/grid/selection-provider",
                        "selectionSelector": "[data-action='requisition-item-check']"
                    }
                }
            }
        }
    }
</script>
