<?php
/* @var $block \Magento\RequisitionList\Block\Requisition\Item\Options */
?>
<?php $options = $block->getOptionList(); ?>

<?php if ($options): ?>
    <div class="product-item-details">
        <?php foreach ($options as $option): ?>
            <dt class="list__label">
                <?= $block->escapeHtml($option['label']) ?>
            </dt>
            <dd class="list__value">
                <?php if (is_array($option['value'])): ?>
                    <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $option['value']), ['span'])) ?>
                <?php elseif (isset($option['option_type']) && $option['option_type'] == 'file'): ?>
                    <?php $viewModel = $block->getData('downloadableViewModel'); ?>
                    <?php $viewModel->setItem($block->getItem()) ?>
                    <?= /* @noEscape */ $viewModel->getOptionValueForFile($option) ?>
                <?php else: ?>
                    <?= $block->escapeHtml($option['value']) ?>
                <?php endif; ?>
            </dd>
        <?php endforeach; ?>
    </div>
<?php endif ?>
