<?php
/**
 * @var $block \Magento\RequisitionList\Block\Requisition\View\Details
 */
?>
<div class="requisition-toolbar">
    <div class="requisition-toolbar-select">
        <div class="checkbox">
            <input
                type="checkbox"
                name=""
                id="requisition-select-all"
                class="checkbox__field"
                data-role="select-all"
            />

            <svg
                class="
                    checkbox__icon
                    checkbox__icon--checked
                "
                role="presentation"
                focusable="false"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
            </svg>
            <svg
                class="
                    checkbox__icon
                    checkbox__icon--unchecked
                "
                role="presentation"
                focusable="false"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
            </svg>
            <label
                class="checkbox__label"
                for="requisition-select-all"
            >
                <?= $block->escapeHtml(__('Select all')) ?>
            </label>
        </div>
    </div>
    <div
        class="
            dashboard-actions-toolbar
            margin-bottom-m
            requisition-toolbar-actions
        "
    >
        <?= $block->getChildHtml('massactions') ?>
    </div>
</div>
