<?php
/**
 * @var $block \Magento\RequisitionList\Block\Requisition\View\Details
 */
?>
<div class="requisition-toolbar">
    <div class="requisition-toolbar-select">
        <input
            type="checkbox"
            name=""
            id="requisition-select-all"
            data-role="select-all"
        >
        <label class="label" for="requisition-select-all">
            <?= $block->escapeHtml(__('Select all')) ?>
        </label>
    </div>
    <div class="requisition-toolbar-actions">
        <span class="mobile-label">
            <?= $block->escapeHtml(__('With Selected')) ?>
        </span>
        <?= $block->getChildHtml('massactions') ?>
    </div>
</div>
