<div>
    <?php $_order = $block->getOrder() ?>

    <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())): ?>
        <a
            class="
                actions-group__link
                dashboard-table__link
                padding-0
                action
                reorder
            "
            href="#"
            data-post='<?= /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order)) ?>'
        >
            <?= $block->escapeHtml(__('Reorder')) ?>
        </a>
    <?php endif; ?>

    <a
        href="<?= $block->escapeUrl($block->getPrintUrl($_order)) ?>"
        class="
            actions-group__link
            dashboard-table__link
            padding-0
            action
            print
        "
        target="_blank"
        rel="noopener"
    >
        <?= $block->escapeHtml(__('Print Order')) ?>
    </a>

    <?= $block->getChildHtml() ?>
</div>
