<?php
/* @var $block \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart */
/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<?php foreach ($block->getChildNames() as $childName): ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false); ?>
<?php endforeach; ?>

<?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()): ?>
    <div
        class="
            input
            input--inline
            wishlist__qty
        "
    >
        <label
            for="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
            class="
                label
                wishlist__label
            "
        >
            <?= $block->escapeHtml(__('Quantity')); ?>:
        </label>
        <div
            class="quantity-update"
            data-mage-init='{ "qtyUpdater": {
                "increaseText": "<?= $block->escapeHtml(__('The quantity was increased to')) ?>",
                "decreseText": "<?= $block->escapeHtml(__('The quantity was decreased to')) ?>"
            } }'
        >
            <button
                class="
                    button
                    button--icon
                    quantity-update__button
                    quantity-update__button--minus
                "
                type="button"
                aria-label="<?= $block->escapeHtmlAttr(__('Decrease the quantity')) ?>"
                data-testid="quantity-minus-button"
            >
                <svg
                    class="
                        icon
                        button__icon
                        quantity-update__icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#minus')); ?>"></use>
                </svg>
            </button>
            <input
                type="number"
                data-role="qty"
                id="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
                class="
                    quantity-update__input
                    wishlist__field-qty
                    qty
                    margin-0
                "
                data-validate="{'required-number':true,'validate-greater-than-zero':true}"
                name="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
                value="<?= $block->escapeHtmlAttr($block->getAddToCartQty($item) * 1) ?>"
                required
            />
            <button
                class="
                    button
                    button--icon
                    quantity-update__button
                    quantity-update__button--plus
                "
                type="button"
                aria-label="<?= $block->escapeHtmlAttr(__('Increase the quantity')) ?>"
                data-testid="quantity-plus-button"
            >
                <svg
                    class="
                        icon
                        button__icon
                        quantity-update__icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#plus')); ?>"></use>
                </svg>
            </button>
            <p
                role="alert"
                class="quantity-update__alert display-none"
            ></p>
        </div>
    </div>
<?php endif; ?>

<?php if ($product->isSaleable()): ?>
    <div
        class="
            wishlist__item-actions
            wishlist__item-actions--to-cart
        "
    >
        <button
            type="button"
            data-role="tocart"
            data-post='<?= $block->escapeHtmlAttr($block->getItemAddToCartParams($item)) ?>'
            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
            data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>"
            class="
                button
                wishlist__button
            "
        >
            <?= $block->escapeHtml(__('Add to Cart')); ?>
        </button>
    </div>
<?php else: ?>
    <?php if ($product->getIsSalable()): ?>
        <p
            class="wishlist__item-stock-info text-right"
            title="<?= $block->escapeHtmlAttr(__('Availability')) ?>"
        >
            <?= $block->escapeHtml(__('In stock')); ?>
        </p>
    <?php else: ?>
        <p
            class="wishlist__item-stock-info text-right"
            title="<?= $block->escapeHtmlAttr(__('Availability')) ?>"
        >
            <?= $block->escapeHtml(__('Out of stock')); ?>
        </p>
    <?php endif; ?>
<?php endif; ?>
