<?php
/* @var \Magento\Wishlist\Model\Item $item */

$item = $block->getItem();
$placeholder = $this->helper('Magento\Wishlist\Helper\Data')->defaultCommentString();
?>

<div class="input wishlist__comment">
    <textarea
        id="product-item-comment-<?= $item->getWishlistItemId() ?>"
        placeholder="<?= $placeholder; ?>"
        name="description[<?= $item->getWishlistItemId() ?>]"
        title="<?= $escaper->escapeHtmlAttr(__('Comment')) ?>"
        class="input__field input__field--textarea"
        <?= $item->getProduct()->isSaleable() ? '' : 'disabled="disabled"' ?>
    ><?= ($escaper->escapeHtml($item->getDescription())) ?></textarea>
</div>
