<?php

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
    <a class="action edit wishlist-button"
       href="<?php /* @escapeNotVerified */ echo $block->getItemConfigureUrl($item); ?>"
    >
        <?php /* @escapeNotVerified */ echo __('Edit'); ?>
    </a>
<?php endif ?>
