<?php
/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
    <a
        class="button button--icon"
        href="<?= $block->escapeUrl($block->getItemConfigureUrl($item)) ?>"
        title="<?= $block->escapeHtmlAttr(__('Edit product parameters')) ?>"
        aria-label="<?= $block->escapeHtmlAttr(__('Edit product parameters')) ?>"
    >
        <svg
            class="button__icon"
            role="img"
        >
            <title><?= __('Edit') ?></title>
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#edit')); ?>"></use>
        </svg>
   </a>
<?php endif ?>
