<?php
    /* @var \Magento\Wishlist\Model\Item $item */
    $item = $block->getItem();
    $product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
    <div class="action__handler">
        <a class="link action__link" href="<?= /* @escapeNotVerified */ $block->getItemConfigureUrl($item) ?>">
            <?= /* @escapeNotVerified */ __('Edit') ?>
        </a>
    </div>
<?php endif ?>
