<?php
    /* @var \Magento\Wishlist\Model\Item $item */
    $item = $block->getItem();
    $product = $item->getProduct();
?>
<a class="catalog-grid-item__link"
   href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>"
   title="<?= /* @escapeNotVerified */ $block->escapeHtml($product->getName()) ?>"
>
    <div class="catalog-grid-item__image-wrapper">
        <?= /* @escapeNotVerified */ $block->getImage($product, 'wishlist_thumbnail')->toHtml(); ?>
    </div>
</a>
