<?php
    /* @var \Magento\Wishlist\Model\Item $item */
    $item = $block->getItem();
    $product = $item->getProduct();
?>
<a class="product__link" 
   href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>" 
   title="<?php echo $block->escapeHtml($product->getName()) ?>"
>
    <div class="product__img-box">
        <?php echo $block->getImage($product, 'wishlist_thumbnail')->toHtml(); ?>
    </div>
</a>
