<?php
/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<a
    href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
    title="<?= $block->escapeHtmlAttr($product->getName()) ?>"
    class="wishlist__link"
    aria-label="<?= $block->escapeHtmlAttr($product->getName()) ?>"
>
    <?= $block->getImage($product, 'wishlist_thumbnail')->toHtml(); ?>
</a>
