<?php
    /* @var \Magento\Wishlist\Model\Item $item */
    $item = $block->getItem();
    $product = $item->getProduct();
?>

<h2 class="product__name">
    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>" 
       title="<?php echo $block->escapeHtml($product->getName()) ?>" 
       class="link"
    >
        <?php echo $block->escapeHtml($product->getName()) ?>
    </a>
</h2>
