<?php
/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<h2 class="wishlist__item-name padding-0">
    <a
        href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
        title="<?= $block->escapeHtmlAttr($product->getName()) ?>"
        class="link wishlist__item-name-link"
    >
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</h2>
