<?php
    /* @var \Magento\Wishlist\Model\Item $item */
    $item = $block->getItem();
    $product = $item->getProduct();
?>

<h2 class="product__name">
    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>" 
       title="<?= /* @escapeNotVerified */ $block->escapeHtml($product->getName()) ?>" 
       class="link"
    >
        <?= /* @escapeNotVerified */ $block->escapeHtml($product->getName()) ?>
    </a>
</h2>
