<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
?>
<div class="product__price">
    <?php foreach ($block->getChildNames() as $childName): ?>
        <?php /* @escapeNotVerified */ echo $block->getLayout()->renderElement($childName, false); ?>
    <?php endforeach;?>
</div>
