<a
    href="#"
    data-role="remove"
    data-post-remove='<?= /* @escapeNotVerified */ $block->getItemRemoveParams($block->getItem()); ?>'
    title="<?= /* @escapeNotVerified */ __('Remove Item') ?>"
    class="button button--icon wishlist__remove"
>
    <svg class="button__icon">
        <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#remove'); ?>"></use>
    </svg>
</a>
