<button
    type="button"
    class="button button--icon wishlist__remove"
    data-role="remove"
    data-post-remove='<?= /* @escapeNotVerified */ $block->getItemRemoveParams($block->getItem()); ?>'
    title="<?= /* @escapeNotVerified */ __('Remove Item') ?>"
    aria-label="<?= /* @escapeNotVerified */ __('Remove Item') ?>"
>
    <svg class="button__icon">
        <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#remove'); ?>"></use>
    </svg>
</button>
