<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\GiftCardAccount\Block\Account\Redeem $block
 * @see \Magento\GiftCardAccount\Block\Account\Redeem
 */
?>
<?php if ($block->canRedeem()) : ?>
    <div class="block block-balance-giftcard">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Redeem Gift Card')) ?></strong>
        </div>
        <div class="block-content">
          <p>
              <?= $block->escapeHtml(__('Have a gift card? ')); ?>
              <a href="<?= $block->escapeUrl($block->getUrl('magento_giftcardaccount/customer')) ?>">
                  <?= $block->escapeHtml(__('Click here')) ?>
              </a>
              <?= $block->escapeHtml(__(' to redeem it.')) ?>
        </div>
    </div>
<?php endif; ?>
