<?php if ($block->canRedeem()): ?>
    <div class="information ">
        <h3 class="information__title">
            <?= $block->escapeHtml(__('Redeem Gift Card')); ?>
        </h3>

        <p class="information__text">
            <?= $block->escapeHtml(__('Have a gift card? ')); ?>

            <a href="<?= $block->escapeUrl($block->getUrl('magento_giftcardaccount/customer'));?>"
               class="dashboard__link"
            >
                <?= $block->escapeHtml(__('Click here')); ?>
            </a>

            <?= $block->escapeHtml(__(' to redeem it.')); ?>
        </p>
    </div>
<?php endif; ?>
