<div id="gc-please-wait"
      class="dashboard__item please-wait load indicator"
      data-text="<?= $escaper->escapeHtmlAttr(__('This won\'t take long . . .')); ?>"
      style="display: none;"
>
    <?= $escaper->escapeHtml(__('This won\'t take long . . .')); ?>
</div>

<?php
    $getGiftCardStatusUrl = $escaper->escapeUrl($block->getUrl('magento_giftcardaccount/cart/quickCheck',  ['_secure' => true]));
?>

<form class="form form-giftcard-redeem"
      id="giftcard-form"
      action="<?= $escaper->escapeUrl($block->getUrl('*/*/*')); ?>"
      method="post"
      data-mage-init='{
        "giftCard": {
            "giftCardCodeSelector": "#giftcard-code",
            "checkStatus": ".action__button.check",
            "giftCardStatusUrl": "<?= $getGiftCardStatusUrl ?>",
            "giftCardStatusId": "#giftcard-balance-lookup",
            "giftCardSpinnerId": "#gc-please-wait",
            "messages": ".page.messages .messages"
        }
      }'
>
    <h3 class="dashboard-form__title">
        <?= __('Gift Card') ?>
    </h3>

    <div id="giftcard-balance-lookup" class="giftcard ballance"></div>

    <div class="input giftcard required">
        <label class="label" for="giftcard-code">
            <?= $escaper->escapeHtml(__('Enter gift card code')); ?>
        </label>

        <input
            class="input__field"
            id="giftcard-code"
            type="text"
            name="giftcard_code"
            data-validate="{required:true}"
            value="<?= /* @noEscape */ $block->getCurrentGiftcard(); ?>"
        />
    </div>

    <div class="action">
        <?php if ($block->canRedeem()): ?>
            <div class="action__handler">
                <button class="button action__button redeem primary"
                        type="submit"
                        value="<?= $escaper->escapeHtmlAttr(__('Redeem Gift Card')); ?>"
                >
                    <?= $escaper->escapeHtml(__('Redeem Gift Card')); ?>
                </button>
            </div>
        <?php endif; ?>

        <div class="action__handler">
            <button class="button action__button check"
                    id="gca_balance_button"
                    type="button"
                    value="<?= $escaper->escapeHtmlAttr(__('Check status and balance')); ?>"
            >
                <?= $escaper->escapeHtml(__('Check status and balance')); ?>
            </button>
        </div>
    </div>
</form>
