<?php
/**
 * @var \Magento\GiftCardAccount\Block\Account\Redeem $block
 * @see \Magento\GiftCardAccount\Block\Account\Redeem
 */
?>
<?php if ($block->canRedeem()) : ?>
    <div
        class="
            dashboard-items
            col-xs-12
            col-md-6
            block
            block-balance-giftcard
        "
    >
        <div class="dashboard-items__title block-title">
            <?= $block->escapeHtml(__('Redeem Gift Card')) ?>
        </div>
        <div
            class="
                dashboard-items__item
                margin-bottom-m
                block-content
            "
        >
            <?= $block->escapeHtml(__('Have a gift card? ')); ?>
            <a
                class="actions-group__link"
                href="<?= $block->escapeUrl($block->getUrl('magento_giftcardaccount/customer')) ?>"
            >
                <?= $block->escapeHtml(__('Click here')) ?>
            </a>
            <?= $block->escapeHtml(__(' to redeem it.')) ?>
        </div>
    </div>
<?php endif; ?>
