<form action="<?= $block->getAddActionUrl(); ?>"
      method="post"
      id="form-validate"
      class="form dashboard-form validation"
      data-hasrequired="<?= __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'
>
    <?= $block->getBlockHtml('formkey') ?>

    <h3 class="dashboard-form__title">
        <?= __('General Information') ?>
    </h3h5>

    <div class="select dashboard-form__select required">
        <label for="type_id" class="label">
            <?= __('Gift Registry Type') ?>
        </label>

        <select data-validate="{required:true}"
                name="type_id"
                id="type_id"
                class="select__field select__field--native validate-select"
                data-mage-init='{"select": {}}'
        >
            <option value="" selected disabled>
                <?= __('Please select a gift registry type.') ?>
            </option>

            <?php foreach ($block->getTypeList() as $type): ?>
                <option value="<?= $type['value'] ?>">
                    <?= $type['label'] ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="action">
        <div class="action__handler">
            <button type="submit"
                    id="submit.next"
                    title="<?= __('Next') ?>"
                    class="button action__button primary next"
            >
                <?= __('Next') ?>
            </button>
        </div>

        <div class="action__handler">
            <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
               class="link action__link back"
            >
                <?= __('Back') ?>
            </a>
        </div>
    </div>
</form>
