<?php
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
<h2 class="subtitle">
    <?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
</h2>

<form action="<?= $block->escapeUrl($block->getAddActionUrl()) ?>"
      method="post"
      id="form-validate"
      class="form validation form-giftregistry-create"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="fieldset__legend fieldset__legend--hidden"><span><?= $block->escapeHtml(__('General Information')) ?></span></legend>

        <div class="select select--native type required">
            <label for="type_id" class="label"><span><?= $block->escapeHtml(__('Gift Registry Type')) ?></span></label>
            <div class="control">
                <select class="select__field" data-validate="{required:true}" name="type_id" id="type_id" data-mage-init='{ "select": {}}'>
                    <option value=""><?= $block->escapeHtml(__('Please select a gift registry type.')) ?></option>
                    <?php foreach ($block->getTypeList() as $type) :?>
                        <option value="<?= $block->escapeHtmlAttr($type['value']) ?>"><?= $block->escapeHtml($type['label']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </fieldset>

    <div class="actions-group">
        <div class="actions-group__handler">
            <button type="submit" id="submit.next" title="<?= $block->escapeHtmlAttr(__('Next')) ?>" class="button link--button action primary next">
                <span><?= $block->escapeHtml(__('Next')) ?></span>
            </button>
        </div>
        <div class="actions-group__handler">
            <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="actions-group__link action back">
                <span><?= $block->escapeHtml(__('Back')) ?></span>
            </a>
        </div>
    </div>
</form>
