<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/editPost'); ?>"
      method="post"
      id="form-validate"
      class="form form-giftregistry-edit validation"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'
>
    <?php echo $block->getBlockHtml('formkey')?>
    <?php echo $block->getChildHtml(); ?>

    <div class="action">
        <div class="action__handler">
            <button type="submit" 
                    id="submit.save" 
                    title="<?php /* @escapeNotVerified */ echo __('Save') ?>" 
                    class="button action__button primary save"
            >
                <?php /* @escapeNotVerified */ echo __('Save') ?>
            </button>
        </div>

        <div class="action__handler">
            <a href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>" 
               class="link action__link back"
            >
                <?php /* @escapeNotVerified */ echo __('Back') ?>
            </a>
        </div>
    </div>
</form>
