<form
    action="<?= $block->escapeUrl($block->getUrl('*/*/editPost')) ?>"
    method="post"
    id="form-validate"
    class="form form-giftregistry-edit validation"
    data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
    data-mage-init='{"validation":{}}'
>
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getChildHtml() ?>

    <div class="actions-group">
        <div class="actions-group__handler">
            <button
                type="submit"
                id="submit.save"
                title="<?= $block->escapeHtmlAttr(__('Save')) ?>"
                class="
                    button
                    link--button
                    action
                    primary
                    save
                "
            >
                <?= $block->escapeHtml(__('Save')) ?>
            </button>
        </div>
        <div class="actions-group__handler">
            <a
                href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
                class="
                    actions-group__link
                    action
                    back
                "
            >
                <?= $block->escapeHtml(__('Back')) ?>
            </a>
        </div>
    </div>
</form>
