<form
    action="<?= $escaper->escapeUrl($block->getUrl('*/*/editPost')); ?>"
    method="post"
    id="form-validate"
    class="
        form
        form-giftregistry-edit
        validation
    "
    data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
    data-mage-init='{"validation":{}}'
>
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getChildHtml(); ?>

    <div class="action">
        <div class="action__handler">
            <button
                type="submit"
                id="submit.save"
                title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>"
                class="
                    button
                    action__button
                    primary
                    save
                "
            >
                <?= $escaper->escapeHtml(__('Save')) ?>
            </button>
        </div>

        <div class="action__handler">
            <a href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"
               class="link action__link back"
            >
                <?= $escaper->escapeHtml(__('Back')) ?>
            </a>
        </div>
    </div>
</form>
