<input type="hidden" name="entity_id" id="entity_id" value="<?= $block->getEntity()->getEntityId(); ?>" />
<input type="hidden" name="type_id" id="type_id" value="<?= $block->getTypeId(); ?>" />

<h3 class="dashboard-form__title">
    <?= __('General Information') ?>
</h3>

<div class="information">
    <p class="information__text">
        <span>
            <?= __('Type:') ?>
        </span>

        <strong>
            <?= $block->getTypeLabel(); ?>
        </strong>
    </p>
</div>

<div class="dashboard-form__divider " >
    <div class="input required">
        <label for="title" class="label">
            <?= __('Event') ?>
        </label>

        <input type="text"
               name="title"
               id="title"
               value="<?= $block->escapeHtml($block->getEntity()->getTitle());?>"
               title="<?= __('Event') ?>"
               class="input__field"
               data-validate="{required:true}"
        />
    </div>

    <div class="input required">
        <label for="message" class="label">
            <?= __('Message') ?>
        </label>

        <textarea name="message"
                  id="message"
                  cols="5"
                  rows="3"
                  class="input__field input__field--textarea"
                  title="<?= __('Message') ?>"
                  data-validate="{required:true}"
        ><?= $block->escapeHtml($block->getEntity()->getMessage());?></textarea>
    </div>

    <div class="select dashboard-form__select required" data-mage-init='{"loadSelect": {}}'>
        <label for="is_public" class="label">
            <?= __('Privacy Settings') ?>
        </label>

        <?= $block->getIsPublicHtml() ?>
    </div>

    <div class="select dashboard-form__select required">
        <label for="status" class="label">
            <?= __('Status') ?>
        </label>

        <select data-validate="{required:true}"
                name="status"
                id="status"
                class="select__field select__field--native validate-select"
                data-mage-init='{"select": {}}'
        >
            <?php foreach ($block->getEntity()->getOptionsStatus() as $num=>$type):?>
                <option value="<?= $num; ?>">
                    <?= $type->getText() ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>

<?php
$fieldsets = $block->getGroupedRegistryAttributes();

foreach ($fieldsets as $fieldset => $fields) : ?>
    <h3 class="dashboard-form__title">
        <?= $block->getGroupLabel($fieldset); ?>
    </h3>

    <?php foreach ($fields as $field => $data) : ?>
        <?php $isRequired = $block->isAttributeRequired($data); ?>

        <?php
            $name  = $data['name'];
            $id    = $data['id'];
            $value = $this->getEntity()->getFieldValue($id);

            switch ($data['type']) :
                case 'country':
                    $options = $block->getCountry();
        ?>
                    <div class="select dashboard-form__select required">
                        <label for="<?= $id; ?>" class="label">
                            <?= __($data['label']) ?>
                        </label>

                        <select data-validate="{required:true}"
                                name="<?= $id; ?>"
                                id="<?= $id; ?>"
                                class="select__field select__field--native validate-select"
                                data-mage-init='{"select": {}}'
                        >
                            <option value="" disabled selected>
                                <?php  echo __('Please Select a country'); ?>
                            </option>

                            <?php foreach ($options as $option):?>
                                <option value="<?= $option['value'] ?>">
                                    <?= __($option['label']) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
        <?php
                    break;

                case 'region':
                    $value = $this->getEntity()->getFieldValue($id);
        ?>
                    <div class="input required">
                        <label for="<?= $id.'_text'; ?>" class="label">
                            <?= __($data['label']) ?>
                        </label>

                        <input type="text"
                               id="<?= $id.'_text'; ?>"
                               name="<?= $id.'_text'; ?>"
                               value="<?= $value; ?>"
                               title="<?= __('State/Province') ?>"
                               class="input__field <?= $block->getRegionValidationClass(); ?>"
                               <?= $block->displayAll(); ?>
                        />
                    </div>
        <?php
                    break;

                case 'date':
                    $formatType      = \IntlDateFormatter::SHORT;
                    $isRequiredField = ($isRequired ? ' required' : '');
        ?>
                    <div class="
                            input
                            dashboard-form__divider
                            <?= $isRequiredField; ?>
                            <?= $field == 'event_date' ? ' date' : ''; ?>
                         "
                    >
                        <?= /* @escapeNotVerified */
                            $block->getCalendarDateHtml($name, $id, $value, $formatType, 'input__field');
                        ?>
                    </div>
        <?php
                    break;

                case 'select':
                    $options = $block->getOptionsToArray($data['options']);
        ?>
                    <div class="select dashboard-form__select required">
                        <label for="<?= $id; ?>" class="label">
                            <?= __($data['label']) ?>
                        </label>

                        <div class="select--native">
                            <?= /* @escapeNotVerified */
                                $this->getSelectHtml($options, $name, $id, $value, 'select__field select__field--native');
                            ?>
                        </div>
                    </div>
        <?php
                    break;

                case 'number':
        ?>
                    <div class="
                            input
                            dashboard-form__divider
                            validate-digits
                            <?= ($isRequired ? ' required' : ''); ?>
                         "
                    >
                        <label for="<?= $field ?>" class="label">
                            <?= __($data['label']); ?>
                        </label>

                        <input type="number"
                               class="input__field required-entry"
                               name="<?= $id; ?>"
                               id="<?= $id; ?>"
                        />
                    </div>
        <?php
                    break;

                default:
                    $class = 'input__field';
                    $requiredField = ($isRequired ? ' required' : '');

                    $template = $this->getLayout()->getBlock('giftregistry_edit')->getInputTypeTemplate('text');

                    $this->setInputName(
                        $name
                    )->setInputId(
                        $id
                    )->setInputValue(
                        $value
                    )->setInputClass(
                        $class
                    );
        ?>
                    <div class="input <?= $requiredField; ?>">
                        <label for="<?= $field ?>" class="label">
                            <?= __($data['label']); ?>
                        </label>

                        <?=  $this->fetchView($template); ?>
                    </div>
        <?php
            endswitch;
        ?>
    <?php endforeach; ?>
<?php endforeach; ?>
