<?php

// @codingStandardsIgnoreFile

/** @var $block \Magento\Wishlist\Block\Customer\Wishlist\Button */
?>
<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->getShared() < $block->getConfig()->getSharingEmailLimit()): ?>
    <button type="submit"
            name="save_and_share"
            title="<?php /* @escapeNotVerified */ echo __('Share Wish List'); ?>"
            class="action share actions-toolbar__button"
    >
        <?php /* @escapeNotVerified */ echo __('Share Wish List'); ?>
    </button>
<?php endif;?>
