<?php
/** @var $block \Magento\Wishlist\Block\Customer\Wishlist\Button */

$getWishlistItems      = $block->getWishlist()->getItemsCount();
$getWishlistShared     = $block->getWishlist()->getShared();
$getWishlistEmailLimit = $block->getConfig()->getSharingEmailLimit();
?>
<?php if ($getWishlistItems && $getWishlistShared < $getWishlistEmailLimit): ?>
    <button
        type="submit"
        name="save_and_share"
        title="<?= __('Share Wish List') ?>"
        class="button button--secondary action__button share"
    >
        <?= __('Share Wish List') ?>
    </button>
<?php endif;?>
