<?php

// @codingStandardsIgnoreFile

?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
    <button type="button"
            data-role="all-tocart"
            title="<?php /* @escapeNotVerified */ echo __('Add All to Cart'); ?>"
            class="action tocart actions-toolbar__button"
    >
        <?php /* @escapeNotVerified */ echo __('Add All to Cart'); ?>
    </button>
<?php endif;?>
