<?php
use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {
    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You may also like');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You may also like');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
$_item = null;
?>

<?php if ($exist): ?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div
                class="product-view__slider <?= $block->escapeHtmlAttr($class) ?>"
                data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
                data-shuffle="<?= $block->escapeHtmlAttr($shuffle) ?>"
            >
        <?php else: ?>
            <div
                class="product-view__slider <?= $block->escapeHtmlAttr($class) ?>"
                data-mage-init='{ "upsellProducts": {} }'
                data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
                data-shuffle="<?= /* @noEscape */ $shuffle ?>"
            >
        <?php endif; ?>
    <?php else: ?>
        <div class="product-view__slider <?= $block->escapeHtmlAttr($class) ?>">
    <?php endif; ?>

        <h4 id="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
            <?= $block->escapeHtml($title) ?>
        </h4>

        <div
            class="slider product-view__slider-container"
            data-rewind="true"
            data-enable-mouse-events="true"
            data-mage-init='{ "slider": {} }'
            aria-labelledby="block-<?= $class ?>-heading"
        >
            <div class="slider__handler">
                <div class="slider__slides">
                    <?php $iterator = 1; ?>

                    <?php foreach ($items as $_item): ?>

                        <?= ($iterator++ == 1) ? '<div class="slider__item product-view__slide-item active">' : '</div><div class="slider__item product-view__slide-item">' ?>

                        <div class="catalog-grid-item product-view__grid-item">
                            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>

                            <a
                                href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                class="catalog-grid-item__link"
                            >
                                <div class="catalog-grid-item__image-wrapper">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </div>
                            </a>

                            <section class="catalog-grid-item__details">
                                <h2 class="catalog-grid-item__name">
                                    <a
                                        href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                        class="catalog-grid-item__name-link"
                                        title="<?= $block->escapeHtml($_item->getName()) ?>"
                                    >
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </h2>
                                <div class="catalog-grid-item__price">
                                    <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                                </div>
                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>
                                <?php if ($showAddTo || $showCart): ?>
                                    <div class="catalog-grid-item__actions">
                                        <?php if ($showCart): ?>
                                            <?php if ($_item->isSaleable()): ?>
                                                <div class="catalog-grid-item__primary-form">
                                                    <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                                        <button
                                                            class="
                                                                button
                                                                button--secondary
                                                                catalog-grid-item__primary-action
                                                                tocart
                                                            "
                                                            data-mage-init='{
                                                                "redirectUrl": {
                                                                    "url": "<?= $block->getAddToCartUrl($_item) ?>"
                                                                }
                                                            }'
                                                            type="button"
                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            data-testid="add-to-cart-button"
                                                        >
                                                            <span class="catalog-grid-item__cart-text">
                                                                <?= $block->escapeHtml(__('Add to Cart')) ?>
                                                            </span>
                                                            <svg class="icon catalog-grid-item__cart-icon">
                                                                <title><?= $block->escapeHtml(__('Add to Cart')) ?></title>
                                                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#shopping-cart')) ?>"></use>
                                                            </svg>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            /** @var $viewModel PreparePostData */
                                                            $viewModel = $block->getViewModel();
                                                            $postArray = $viewModel->getPostData(
                                                                $block->escapeUrl($block->getAddToCartUrl($_item)),
                                                                ['product' => $_item->getEntityId()]
                                                            );
                                                            $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                        ?>
                                                        <form 
                                                            data-role="tocart-form"
                                                            data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                            action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                            method="post"
                                                        >
                                                            <input 
                                                                type="hidden" 
                                                                name="product"
                                                                value="<?= /* @noEscape */ (int)$_item->getEntityId() ?>"
                                                            >
                                                            <input 
                                                                type="hidden"
                                                                name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED?>"
                                                                value="<?= /* @noEscape */ $value ?>"
                                                            >
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <button 
                                                                type="submit"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                class="action tocart primary"
                                                            >
                                                            <button
                                                                class="
                                                                    button
                                                                    button--secondary
                                                                    catalog-grid-item__primary-action
                                                                    tocart
                                                                "
                                                                data-post='<?= $postData ?>'
                                                                type="button"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                data-testid="add-to-cart-button"
                                                            >
                                                                <span class="catalog-grid-item__cart-text">
                                                                    <?= $block->escapeHtml(__('Add to Cart')) ?>
                                                                </span>
                                                                <svg class="icon catalog-grid-item__cart-icon">
                                                                    <title><?= $block->escapeHtml(__('Add to Cart')) ?></title>
                                                                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#shopping-cart')) ?>"></use>
                                                                </svg>
                                                            </button>
                                                        </form>
                                                    <?php endif; ?>
                                                </div>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available">
                                                        <?= $block->escapeHtml(__('In stock')) ?>
                                                    </div>
                                                <?php else: ?>
                                                    <div class="stock unavailable">
                                                        <?= $block->escapeHtml(__('Out of stock')) ?>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                        <?php if ($showAddTo): ?>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <div class="catalog-grid-item__secondary-action">
                                                    <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </section>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</div>' : '' ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
