<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

?>
<?php if ($block->getCollection()->getSize()): ?>
    <?php
        $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
        $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
    <div
        class="
            toolbar
            toolbar-products
        "
        data-mage-init='{
            "productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>
        }'
    >
        <?php
            if ($block->isExpanded()) {
                $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml'));
                $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml'));
            }
            $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml'));
            $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml'));
        ?>

        <?= $block->getPagerHtml() ?>
    </div>
<?php endif ?>
