<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<div
    class="
        lazyload-wrapper
        ratio-container
    "
    style="padding-bottom: <?= ($block->getRatio() * 100) ?>%;"
>
    <img
        class="
            image
            product-image-photo
            ratio-image
            lazyload
        "
        src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAABCAQAAABN/Pf1AAAAC0lEQVR42mNkwAIAACoAAgu1Hc4AAAAASUVORK5CYII="
        data-src="<?= $block->escapeUrl($block->getImageUrl()) ?>"
        alt="<?= $block->escapeHtmlAttr($block->stripTags($block->getLabel(), null, true)) ?>"
    />
</div>
