<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<div class="lazyload-wrapper">
    <img
        class="image product-image-photo catalog-grid-item__image lazyload"
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-src="<?= $block->getImageUrl() ?>"
        alt="<?= $block->stripTags($block->getLabel(), null, true) ?>"
    />
</div>
