<div
    id="reorder-quote-popup"
    data-mage-init='
        {
            "Magento_NegotiableQuote/js/model/create-quote-popup": {}
        }
    '
    data-role="reorder-quote-popup"
    class="
        modal-container
        reorder-quote-popup
    "
>
        <fieldset
            class="
                fieldset
                info
                margin-bottom-l
            "
        >
            <div class="field quote-reorder-message">
                <p
                    class="
                        text-main
                        margin-bottom-xs
                    "
                ></p>
                <p class="text-secondary"></p>
            </div>
        </fieldset>
        <div class="actions-group">
            <div class="actions-group__handler">
                <button
                    class="
                        action
                        merge
                        primary
                        button
                        actions-group__button
                    "
                    data-action="merge-quote"
                    title="<?= $block->escapeHtmlAttr(__('Merge')) ?>"
                    >
                        <?= $block->escapeHtml(__('Merge')) ?>
                    </button>
                <button
                    class="
                        action
                        replace
                        button
                        actions-group__button
                    "
                    data-action="replace-quote"
                    title="<?= $block->escapeHtmlAttr(__('Replace')) ?>"
                >
                    <?= $block->escapeHtml(__('Replace')) ?>
                </button>
            </div>
            <div class="actions-group__handler">
                <button
                    class="
                        action
                        cancel
                        button
                        button--secondary
                        actions-group__button
                    "
                    data-action="close-modal"
                    title="<?= $block->escapeHtmlAttr(__('Cancel')) ?>"
                >
                    <?= $block->escapeHtml(__('Cancel')) ?>
                </button>
            </div>
        </div>
</div>
