<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div id="reorder-quote-popup" data-mage-init='{"Magento_NegotiableQuote/js/model/create-quote-popup": {}}'
     data-role="reorder-quote-popup" class="modal-container reorder-quote-popup">
        <fieldset class="fieldset info">
            <div class="field quote-reorder-message">
                <p class="text-main"></p>
                <p class="text-secondary"></p>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button class="action merge primary" data-action="merge-quote"
                        title="<?= $block->escapeHtmlAttr(__('Merge')) ?>"><span><?= $block->escapeHtml(__('Merge')) ?></span></button>
                <button class="action replace" data-action="replace-quote"
                        title="<?= $block->escapeHtmlAttr(__('Replace')) ?>"><span><?= $block->escapeHtml(__('Replace')) ?></span></button>
            </div>
            <div class="secondary">
                <button class="action cancel secondary" data-action="close-modal"
                        title="<?= $block->escapeHtmlAttr(__('Cancel')) ?>"><span><?= $block->escapeHtml(__('Cancel')) ?></span></button>
            </div>
        </div>
</div>
