<?php // @codingStandardsIgnoreFile ?>
<?php /** @var $block \Magento\Company\Block\Company\Login\Info */ ?>
<div class="col-xs-12">
    <div class="login__company-wrapper">
        <h3>
            <?= __('New Company Account') ?>
        </h3>
        <div class="divider"></div>
        <div class="block-content" aria-labelledby="block-new-company-heading">
            <p class="login__info">
                <?= __(
                    'If you represent a company, you will want to use our company account area. ' .
                    'Creating a company account provides all company members with access to B2B features like quoting, ' .
                    'company users management, quick order, and more.'
                ) ?>
            </p>
            <a
                href="<?= $block->escapeUrl($block->getCreateCompanyAccountUrl()) ?>"
                class="button button--link login__button"
                data-testid="create-company-account-link"
            >
                <?= __('Create a Company Account') ?>
            </a>
        </div>
    </div>
</div>
