<?php /** @var $block \Magento\Company\Block\Company\Login\Info */ ?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
<div class="dashboard-items">
    <h2 class="dashboard-items__title">
        <?= $block->escapeHtml(__('New Company Account')) ?>
    </h2>
    <div class="row">
        <div class="dashboard-items__item">
            <p>
            <?= $block->escapeHtml(__(
                'If you represent a company, you will want to use our company account area. ' .
                'Creating a company account provides all company members with access to B2B features like quoting, ' .
                'company users management, quick order, and more.'
            )) ?>
            </p>
            <div class="actions-group">
                <div class="actions-group__handler">
                    <a
                        href="<?= $block->escapeUrl($block->getCreateCompanyAccountUrl()) ?>"
                        class="
                            action
                            create
                            primary
                            button
                            actions-group__button
                        "
                    >
                        <?= $block->escapeHtml(__('Create a Company Account')) ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
