<?php /** @var $block \Magento\Company\Block\Company\Login\Info */ ?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="auth__container">
        <div class="margin-top-xl">
            <h2 class="text-center">
                <?= $block->escapeHtml(__('New Company Account')) ?>
            </h2>
            <div class="row">
                <div class="padding-vc-m padding-hz-m">
                    <p class="text-center">
                        <?= $block->escapeHtml(__(
                            'If you represent a company, you will want to use our company account area. ' .
                            'Creating a company account provides all company members with access to B2B features like quoting, ' .
                            'company users management, quick order, and more.'
                        )) ?>
                    </p>
                    <div class="account-form__actions">
                        <a
                            href="<?= $block->escapeUrl($block->getCreateCompanyAccountUrl()) ?>"
                            class="button link--button"
                        >
                            <?= $block->escapeHtml(__('Create a Company Account')) ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
