<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Company\Block\Company\Account\Create
 */
?>
<div class="registration">
    <form
        class="form create account form-create-account registration__content"
        action="<?= $block->getPostActionUrl() ?>"
        method="post"
        id="form-validate"
        enctype="multipart/form-data"
        autocomplete="off"
    >
        <?= $block->getBlockHtml('formkey') ?>
        <fieldset class="fieldset registration__fieldset">
            <h3 class="legend">
                <?= $block->escapeHtml(__('Company Information')) ?>
            </h3>
            <div class="divider registration__divider"></div>
            <div class="input company-name _required">
                <label class="label" for="company_name">
                    <?= $block->escapeHtml(__('Company Name')) ?>
                </label>
                <input
                    type="text"
                    name="company[company_name]"
                    id="company_name"
                    value=""
                    title="<?= $block->escapeHtml(__('Company Name')) ?>"
                    class="input__field"
                    data-validate="{ required: true }"
                >
            </div>
            <div class="input legal-name">
                <label class="label" for="legal_name">
                    <?= $block->escapeHtml(__('Company Legal Name')) ?>
                </label>
                <input
                    type="text"
                    name="company[legal_name]"
                    id="legal_name"
                    value=""
                    title="<?= $block->escapeHtml(__('Company Legal Name')) ?>"
                    class="input__field"
                >
            </div>
            <div class="input company-email _required">
                <label class="label" for="company_email">
                    <?= $block->escapeHtml(__('Company Email')) ?>
                </label>
                <input
                    type="email"
                    name="company[company_email]"
                    id="company_email"
                    value=""
                    title="<?= $block->escapeHtml(__('Company Email')) ?>"
                    class="input__field"
                    data-role="email"
                    data-async-is-valid="true"
                    data-mage-init='{
                        "Magento_Company/js/form/element/async-validation": {
                            "name": "company_email",
                            "validateUrl": "<?= $block->getUrl('company/account/validate') ?>"
                        }
                    }'
                    data-validate="{
                        required:true,
                        'validate-email': true,
                        'validate-async-company-email': true
                    }"
                >
            </div>
            <div class="input vat-tax-id">
                <label class="label" for="vat_tax_id">
                    <?= $block->escapeHtml(__('VAT/TAX ID')) ?>
                </label>
                <input
                    type="text"
                    name="company[vat_tax_id]"
                    id="vat_tax_id"
                    value=""
                    title="<?= $block->escapeHtml(__('VAT/TAX ID')) ?>"
                    class="input__field"
                >
            </div>
            <div class="input reseller-id">
                <label class="label" for="reseller_id">
                    <?= $block->escapeHtml(__('Re-seller ID')) ?>
                </label>
                <input
                    type="text"
                    name="company[reseller_id]"
                    id="reseller_id"
                    value=""
                    title="<?= $block->escapeHtml(__('Re-seller ID')) ?>"
                    class="input__field"
                >
            </div>
        </fieldset>
        <fieldset class="fieldset registration__fieldset">
            <h3>
                <?= $block->escapeHtml(__('Legal Address')) ?>
            </h3>
            <div class="divider registration__divider"></div>
            <div class="input street _required">
                <label class="label" for="street0">
                    <?= $block->escapeHtml(__('Street Address')) ?>
                </label>
                <input
                    type="text"
                    name="company[street][0]"
                    id="street0"
                    value=""
                    title="<?= $block->escapeHtml(__('Street Address')) ?>"
                    class="input__field"
                    data-validate="{ required:true }"
                >
            </div>
            <div class="input street">
                <input
                    type="text"
                    name="company[street][1]"
                    id="street1"
                    value=""
                    title="<?= $block->escapeHtml(__('Street Address')) ?>"
                    class="input__field"
                >
            </div>
            <div class="input city _required">
                <label class="label" for="city">
                    <?= $block->escapeHtml(__('City')) ?>
                </label>
                <input
                    type="text"
                    name="company[city]"
                    id="city"
                    value=""
                    title="<?= $block->escapeHtml(__('City')) ?>"
                    class="input__field"
                    data-validate="{ required: true }"
                >
            </div>
            <div class="select country_id _required">
                <label class="label" for="country_id">
                    <?= $block->escapeHtml(__('Country')) ?>
                </label>
                <div class="control _required">
                    <?php $countryValue = $block->getDefaultCountryId(); ?>
                    <select
                        name="company[country_id]"
                        id="country_id"
                        class="select__field select__field--native"
                        title="<?= $block->escapeHtml(__('Country')) ?>"
                        data-validate="{ required: true }"
                    >
                        <option value=""></option>
                        <?php $countries = $block->getCountriesList(); ?>
                        <?php foreach($countries as $countryCode => $country): ?>
                            <option
                                value="<?= $block->escapeHtml($countryCode) ?>"
                                <?= ($countryCode == $countryValue) ? ' selected' : '' ?>
                            >
                                <?= $block->escapeHtml($country) ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
            <div class="select region-id required">
                <label class="label" for="region_id">
                    <?= $block->escapeHtml(__('State/Province')) ?>
                </label>
                <div class="control _required">
                    <select
                        name="company[region_id]"
                        id="region_id"
                        data-validate="{ required: true }"
                        class="select__field select__field--native"
                    >
                        <option value="">
                            <?= $block->escapeHtml(__('Please select a region, state or province.')) ?>
                        </option>
                    </select>
                    <input
                        type="text"
                        id="region"
                        name="company[region]"
                        value=""
                        title="<?= $block->escapeHtml(__('State/Province')) ?>"
                        class="input__field"
                        style="display: none;"
                    >
                </div>
            </div>
            <div class="input postcode required">
                <label class="label" for="postcode">
                    <?= $block->escapeHtml(__('ZIP/Postal Code')) ?>
                </label>
                <input
                    type="text"
                    name="company[postcode]"
                    id="postcode"
                    value=""
                    title="<?= $block->escapeHtml(__('ZIP/Postal Code')) ?>"
                    class="
                        input__field
                        validate-zip-international
                        <?= /* @escapeNotVerified */ $block->getAttributeValidationClass('postcode') ?>
                    "
                    data-validate="{
                        'required': true,
                        'validate-zip-international': true
                    }"
                >
            </div>
            <div class="input telephone _required">
                <label class="label" for="telephone">
                    <?= $block->escapeHtml(__('Phone Number')) ?>
                </label>
                <input
                    type="text"
                    name="company[telephone]"
                    id="telephone"
                    value=""
                    title="<?= $block->escapeHtml(__('Phone Number')) ?>"
                    class="input__field"
                    data-validate="{ required: true }"
                >
            </div>
        </fieldset>
        <fieldset class="fieldset registration__fieldset">
            <h3>
                <?= __('Company Administrator') ?>
            </h3>
            <div class="divider registration__divider"></div>
            <div class="input legal-name">
                <label class="label" for="job_title">
                    <?= $block->escapeHtml(__('Job Title')) ?>
                </label>
                <input
                    type="text"
                    name="job_title"
                    id="job_title"
                    value=""
                    title="<?= $block->escapeHtml(__('Job Title')) ?>"
                    class="input__field"
                >
            </div>
            <div class="input required">
                <label for="email_address" class="label">
                    <?= __('Email') ?>
                </label>
                <input
                    type="email"
                    name="email"
                    autocomplete="email"
                    id="email_address"
                    value=""
                    title="<?= __('Email') ?>"
                    class="input__field"
                    data-async-is-valid="true"
                    data-mage-init='{
                        "Magento_Company/js/form/element/async-validation": {
                            "name": "customer_email",
                            "validateUrl": "<?= /* @escapeNotVerified */ $block->getUrl('company/account/validate') ?>"
                        }
                    }'
                    data-validate="{
                        required: true,
                        'validate-email': true,
                        'validate-async-customer-email': true
                    }"
                >
            </div>
            <?=
                $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
                    ->setObject($block->getFormData())
                    ->setNoWrap(true)
                    ->setForceUseCustomerAttributes(true)
                    ->toHtml()
            ?>
            <?php $gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
            <?= $gender->setGender($block->getFormData()->getGender())->toHtml() ?>
            <?= $block->getChildHtml('form.additional.info') ?>
        </fieldset>
        <button
            type="submit"
            class="button save"
            title="<?= $block->escapeHtml(__('Submit')) ?>"
        >
            <?= $block->escapeHtml(__('Submit')) ?>
        </button>
    </form>
</div>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($) {
        var dataForm = $('#form-validate');
        var ignore = null;
        dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');
    });
</script>
<script type="text/x-magento-init">
    {
        "#country_id": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "",
                "countriesWithOptionalZip": <?= $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
