<?php
/**
 * @var \Magento\Company\Block\Company\Register\Profile $block
 */
?>
<div class="dashboard-items">
    <div class="block-title">
        <h2 class="dashboard-items__title margin-bottom-sm">
            <?= $block->escapeHtml(__('Company Information')) ?>
        </h2>
    </div>
    <div class="row">
        <div class="dashboard-items__item col-xs-12">
            <div class="box-content">
                <?php $companyInformation = $block->filterEmptyFields($block->getCompanyInformation()); ?>
                <?php foreach ($companyInformation as $field): ?>
                <p>
                    <strong>
                            <?= $block->escapeHtml($field->getLabel()) ?>
                    </strong>
                    <span>
                        <?= $block->escapeHtml($field->getValue()) ?>
                    </span>
                </p>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="dashboard-items__item col-xs-12">
            <h3 class="dashboard-items__subtitle margin-bottom-l">
                <?= $block->escapeHtml(__('Legal Address')) ?>
            </h3>
            <div class="box-content">
                <address>
                    <?php $addressInformation = $block->filterEmptyFields($block->getAddressInformation()); ?>
                    <?php foreach ($addressInformation as $field): ?>
                    <p>
                        <strong>
                            <?= $block->escapeHtml($field->getLabel()) ?>
                        </strong>
                        <span>
                            <?= $block->escapeHtml($field->getValue()) ?>
                        </span>
                    </p>
                    <?php endforeach; ?>
                </address>
            </div>
        </div>
        <div class="dashboard-items__item col-xs-6">
            <h3 class="dashboard-items__subtitle margin-bottom-l">
                <?= $block->escapeHtml(__('Company Administrator')) ?>
            </h3>
            <div class="box-content">
                <?php $adminInformation = $block->filterEmptyFields($block->getAdminInformation()); ?>
                <?php foreach ($adminInformation as $field): ?>
                    <p>
                        <strong>
                            <?= $block->escapeHtml($field->getLabel()) ?>
                        </strong>
                        <span>
                            <?= $block->escapeHtml($field->getValue()) ?>
                        </span>
                    </p>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
