<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Company\Block\Company\Register\Profile $block
 */
?>
<div class="block block-company-profile-account">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Company Information')) ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-account-information">
            <div class="box-content">
                <?php $companyInformation = $block->filterEmptyFields($block->getCompanyInformation()); ?>
                <?php foreach ($companyInformation as $field) : ?>
                <p>
                    <strong><?= $block->escapeHtml($field->getLabel()) ?></strong>
                    <span><?= $block->escapeHtml($field->getValue()) ?></span>
                </p>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<div class="block block-company-profile-address">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Legal Address')) ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-address-information">
            <div class="box-content">
                <address>
                    <?php $addressInformation = $block->filterEmptyFields($block->getAddressInformation()); ?>
                    <?php foreach ($addressInformation as $field) : ?>
                    <p>
                        <strong><?= $block->escapeHtml($field->getLabel()) ?></strong>
                        <span><?= $block->escapeHtml($field->getValue()) ?></span>
                    </p>
                    <?php endforeach; ?>
                </address>
            </div>
        </div>
    </div>
</div>

<div class="block block-company-profile-contacts">
    <div class="block-title">
        <strong>
            <?= $block->escapeHtml(__('Company Administrator')) ?>
        </strong>
    </div>
    <div class="block-content">
        <div class="box box-contact-information">
            <div class="box-content">
                <?php $adminInformation = $block->filterEmptyFields($block->getAdminInformation()); ?>
                <?php foreach ($adminInformation as $field) : ?>
                    <p>
                        <strong><?= $block->escapeHtml($field->getLabel()) ?></strong>
                        <span><?= $block->escapeHtml($field->getValue()) ?></span>
                    </p>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
