<?php
/**
 * Downloadable product links
 *
 * @var $block \Magento\Downloadable\Block\Catalog\Product\Samples
 */
?>

<?php if ($block->hasSamples()) : ?>
    <dl
        class="
            margin-bottom-m
            items
            samples
        "
    >
        <dt
            class="
                heading
                heading--fourth-level
                heading--font-secondary
                item-title
                samples-item-title
            "
        >
            <strong>
                <?= $block->escapeHtml($block->getSamplesTitle()) ?>
            </strong>
        </dt>
        <?php $_samples = $block->getSamples() ?>
        <?php foreach ($_samples as $_sample) : ?>
            <dd class="item samples-item">
                <a
                    href="<?= $block->escapeUrl($block->getSampleUrl($_sample)) ?>"
                    <?= $block->getIsOpenInNewWindow() ? 'onclick="this.target=\'_blank\'"' : '' ?>
                    class="
                        link
                        link--invert
                        item-link
                        samples-item-link
                    "
                >
                    <?= $block->escapeHtml($_sample->getTitle()) ?>
                </a>
            </dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>
