<?php
// @codingStandardsIgnoreFile
?>

<?php /* @var $block \Magento\Downloadable\Block\Catalog\Product\View\Type */ ?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->getIsSalable()): ?>
        <div
            class="product-view__stock-status"
            title="<?= __('Availability') ?>"
        >
            <?= __('In stock') ?>
        </div>
    <?php else: ?>
        <div
            class="product-view__stock-status product-view__stock-status--alert"
            title="<?= __('Availability') ?>"
        >
            <?= __('Out of stock') ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?= $block->getChildHtml() ?>

