<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward
 */
?>
<?= /* @escapeNotVerified */ $block->getChildHtml('', true); ?>

<div class="action">
    <div class="action__handler">
        <a class="link action__link back" 
           href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getBackUrl()) ?>"
        >
            <?= /* @escapeNotVerified */ __('Back') ?>
        </a>
    </div>
</div>
