<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward
 * @var \Magento\Reward\Block\Customer\Reward $block
 */
?>
<?= $block->getChildHtml('', true) ?>
<div class="actions-group ">
    <div class="actions-group__handler">
        <a
            class="
                link
                actions-group__link
            "
            href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
            title="<?= $block->escapeHtmlAttr(__('Back')) ?>"
        >
            <?= $block->escapeHtml(__('Back')) ?>
        </a>
    </div>
</div>
