<?php
/** @var  $block \Magento\NegotiableQuote\Block\Quote\Comments*/
?>
<div class="quote-comments">
    <div class="quote-comments__list">
        <?php foreach ($block->getQuoteComments() as $comment): ?>
            <?php /** @var $comment \Magento\NegotiableQuote\Model\Comment */?>
            <div class="quote-comments__item">
                <date class="quote-comments__date">
                    <?= /* @noEscape */ $block->formatDate($comment->getCreatedAt(), \IntlDateFormatter::MEDIUM, true) ?>
                </date>
                <span class="quote-comments__author">
                    <?= $block->escapeHtml($block->getCommentCreator($comment)) ?>
                </span>
                <div class="quote-comments__content">
                    <?php if ($comment->getIsDecline()): ?>
                        <b class="comments-request-declined">
                            <?= $block->escapeHtml(__('Request Declined. Reason: ')) ?>
                        </b>
                    <?php endif ?>
                    <?= /* @noEscape */ nl2br($block->escapeHtml($comment->getComment())) ?>
                </div>

                <?php $attachments = $block->getCommentAttachments($comment->getEntityId()) ?>
                <?php if ($attachments->count() > 0): ?>
                    <div class="quote-comments__attachments">
                        <ul
                            class="
                                list
                                list--horizontal
                                quote-comments__attachments-list
                            "
                        >
                            <?php foreach ($attachments as $file): ?>
                                <?php /** @var $file \Magento\NegotiableQuote\Model\CommentAttachment */ ?>
                                <li class="list__item">
                                    <a
                                        href="<?= $block->escapeUrl($block->getAttachmentUrl($file->getAttachmentId())) ?>"
                                        aria-label="<?= $block->escapeHtmlAttr($file->getFileName()) ?>"
                                        class="link"
                                    >
                                        <?= $block->escapeHtml($file->getFileName()) ?>
                                    </a>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    </div>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    </div>
</div>
