<?php
/**
 * @var \Magento\NegotiableQuote\Block\Quote\Info $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<ul class="list list--table">
    <li class="list__item">
        <span class="list__label">
            <?= $escaper->escapeHtml(__('Created:')) ?>
        </span>
        <span class="list__value">
            <date>
                <?= /* @noEscape */ $block->formatDate($block->getQuote()->getCreatedAt(), \IntlDateFormatter::LONG) ?>
            </date>
            (<?= $escaper->escapeHtml($block->getQuoteOwnerFullName()) ?>)
        </span>
    </li>
    <li class="list__item">
        <span class="list__label">
            <?= $escaper->escapeHtml(__('Expires:')) ?>
        </span>
        <span class="list__value">
            <?php if ($block->isQuoteExpirationDateDisplayed()): ?>
                <date>
                    <?= /* @noEscape */ $block->formatDate($block->getExpirationPeriodTime(), \IntlDateFormatter::LONG) ?>
                </date>
            <?php else: ?>
                <?= $escaper->escapeHtml(__('Never')) ?>
            <?php endif; ?>
        </span>
    </li>
    <li class="list__item">
        <span class="list__label">
            <?= $escaper->escapeHtml(__('Sales Rep.:')) ?>
        </span>
        <span class="list__value">
            <?= $escaper->escapeHtml($block->getSalesRep()) ?>
        </span>
    </li>
</ul>
