<?php
/**
 * @var \Magento\NegotiableQuote\Block\Quote\Info $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="dashboard__handler">
    <?php if ($block->getQuoteName()): ?>
        <h2
            class="
                heading
                heading--third-level
                margin-right-l
                margin-bottom-0
            "
        >
            <?= $escaper->escapeHtml($block->getQuoteName()) ?>
        </h2>
    <?php endif; ?>
    <span
        id="quote-status-field"
        class="dashboard__status"
    >
        <?= $escaper->escapeHtml($block->getQuoteStatusLabel()) ?>
    </span>
</div>
