<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Swatches\Block\LayeredNavigation\RenderLayered */
?>
<?php $swatchData = $block->getSwatchData(); ?>

<div
    class="<?= /* @escapeNotVerified */ $swatchData['attribute_code'] ?>"
    attribute-code="<?= /* @escapeNotVerified */ $swatchData['attribute_code'] ?>"
    attribute-id="<?= /* @escapeNotVerified */ $swatchData['attribute_id'] ?>"
>
    <div class="swatch clearfix">
        <?php foreach ($swatchData['options'] as $option => $label): ?>
            <a
                href="<?= /* @escapeNotVerified */ $label['link'] ?>"
                aria-label="<?= /* @escapeNotVerified */ $label['label'] ?>"
                class="link"
            >
                <?php if (isset($swatchData['swatches'][$option]['type'])) { ?>
                    <?php switch ($swatchData['swatches'][$option]['type']) {
                        case '3':
                    ?>
                        <div
                            class="swatch__option <?= /* @escapeNotVerified */ $label['custom_style'] ?>"
                            tabindex="-1"
                            option-type="3"
                            option-id="<?= /* @escapeNotVerified */ $option ?>"
                            option-label="<?= /* @escapeNotVerified */ $label['label'] ?>"
                            option-tooltip-thumb=""
                            option-tooltip-value=""
                        ></div>
                    <?php
                        break;
                        case '2':
                    ?>
                        <?php
                            $swatchThumbPath = $block->getSwatchPath('swatch_thumb',
                            $swatchData['swatches'][$option]['value']);
                        ?>

                        <?php
                            $swatchImagePath = $block->getSwatchPath('swatch_image',
                            $swatchData['swatches'][$option]['value']);
                        ?>

                        <div
                            class="swatch__option swatch__option--attribute <?= /* @escapeNotVerified */ $label['custom_style'] ?>"
                            tabindex="-1"
                            option-type="2"
                            option-id="<?= /* @escapeNotVerified */ $option ?>"
                            option-label="<?= /* @escapeNotVerified */ $label['label'] ?>"
                            option-tooltip-thumb="<?= /* @escapeNotVerified */ $swatchThumbPath ?>"
                            option-tooltip-value=""
                            style="
                                background-image: url(<?= /* @escapeNotVerified */ $swatchImagePath ?>);
                                background-repeat: no-repeat;
                                background-position: center;
                                background-size: initial;
                            "
                        ></div>
                    <?php
                        break;
                        case '1':
                    ?>
                        <div
                            class="swatch__option swatch__option--attribute <?= /* @escapeNotVerified */ $label['custom_style'] ?>"
                            tabindex="-1"
                            option-type="1"
                            option-id="<?= /* @escapeNotVerified */ $option ?>"
                            option-label="<?= /* @escapeNotVerified */ $label['label'] ?>"
                            option-tooltip-thumb=""
                            option-tooltip-value="<?= /* @escapeNotVerified */ $swatchData['swatches'][$option]['value'] ?>"
                            style="
                                background-image: <?= /* @escapeNotVerified */ $swatchData['swatches'][$option]['value'] ?>;
                                background-repeat: no-repeat;
                                background-position: center;
                                background-size: initial;"
                        ></div>
                    <?php
                        break;
                        case '0':
                        default:
                    ?>
                        <div
                            class="swatch__option <?= /* @escapeNotVerified */ $label['custom_style'] ?>"
                            tabindex="-1"
                            option-type="0"
                            option-id="<?= /* @escapeNotVerified */ $option ?>"
                            option-label="<?= /* @escapeNotVerified */ $label['label'] ?>"
                            option-tooltip-thumb=""
                            option-tooltip-value=""
                        >
                            <?= /* @escapeNotVerified */ $swatchData['swatches'][$option]['value'] ?>
                        </div>
                    <?php
                        break;
                    } ?>
                <?php } ?>
            </a>
        <?php endforeach; ?>
    </div>
</div>

<script>
    require(["jquery", "jquery/ui", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.<?= /* @escapeNotVerified */ $swatchData['attribute_code'] ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
