<?php
// phpcs:disable PSR2.ControlStructures.SwitchDeclaration
// phpcs:disable Generic.WhiteSpace.ScopeIndent

/** @var $block \Magento\Swatches\Block\LayeredNavigation\RenderLayered */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php $swatchData = $block->getSwatchData(); ?>
<ul
    data-attribute-code="<?= $block->escapeHtmlAttr($swatchData['attribute_code']) ?>"
    data-attribute-id="<?= $block->escapeHtmlAttr($swatchData['attribute_id']) ?>"
    class="
        list
        filter__list
        swatch-attribute
        swatch-layered
        <?= $block->escapeHtmlAttr($swatchData['attribute_code']) ?>
    "
>
    <?php foreach ($swatchData['options'] as $option => $label): ?>
        <?php if (isset($swatchData['swatches'][$option]['type'])): ?>
            <?php switch ($swatchData['swatches'][$option]['type']) {
                case '3':
                ?>
                    <li>
                        <a
                            href="<?= $block->escapeUrl($label['link']) ?>"
                            aria-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                        >
                            <div
                                class="
                                    swatch-option
                                    <?= $block->escapeHtmlAttr($label['custom_style']) ?>
                                "
                                data-option-type="3"
                                data-option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                data-option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                data-option-tooltip-thumb=""
                                data-option-tooltip-value=""
                                tabindex="-1"
                            ></div>
                        </a>
                    </li>
                <?php
                break;
                case '2':
                ?>
                    <?php $swatchThumbPath = $block->getSwatchPath('swatch_thumb',
                    $swatchData['swatches'][$option]['value']); ?>
                    <?php $swatchImagePath = $block->getSwatchPath('swatch_image',
                    $swatchData['swatches'][$option]['value']); ?>
                    <li>
                        <a
                            href="<?= $block->escapeHtmlAttr($label['link']) ?>"
                            aria-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                        >
                            <div
                                class="
                                    swatch-option
                                    <?= $block->escapeHtmlAttr($label['custom_style']) ?>
                                "
                                tabindex="-1"
                                data-option-type="2"
                                data-option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                data-option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                data-option-tooltip-thumb="<?= $block->escapeUrl($swatchThumbPath) ?>"
                                data-option-tooltip-value=""
                                title="<?= $block->escapeHtmlAttr($label['label']) ?>"
                            ></div>
                        </a>
                        <?php
                        $escapedUrl = $block->escapeUrl($swatchImagePath);
                        $element = 'swatchImageOption' . $escaper->escapeJs($option);
                        $script = 'var ' . $element
                            . ' = document.querySelector(\'div[data-option-id="' . $escaper->escapeJs($option)
                            . '"]\');' . PHP_EOL;
                        $script .= $element . '.style.background = "url(\''
                            . $escapedUrl . '\') no-repeat center";' . PHP_EOL;
                        $script .= $element . '.style.backgroundSize = "cover";';
                        ?>
                        <?= /* @noEscape*/ $secureRenderer->renderTag('script', [], $script, false); ?>
                    </li>
                <?php
                break;
                case '1':
                ?>
                    <li class="filter__color-item">
                        <a
                            href="<?= $block->escapeHtmlAttr($label['link']) ?>"
                            class="filter__color-option"
                        >
                            <div
                                class="
                                    filter__color-sample
                                    swatch-option
                                    <?= $block->escapeHtmlAttr($label['custom_style']) ?>
                                "
                                tabindex="-1"
                                data-option-type="1"
                                data-option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                data-option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                data-option-tooltip-thumb=""
                                data-option-tooltip-value="<?= $block->escapeHtmlAttr($swatchData['swatches'][$option]['value']) ?>"
                            ></div>
                            <span class="filter__color-label">
                                <?= $block->escapeHtml($label['label']) ?>
                            </span>
                        </a>
                        <?php
                        $element = 'swatchImageOption' . $escaper->escapeJs($option);
                        $backgroundValue = $escaper->escapeJs(
                            str_replace('\'', '\\\'', $swatchData['swatches'][$option]['value'])
                        );
                        $script = 'var ' . $element
                            . ' = document.querySelector(\'div[data-option-id="' . $escaper->escapeJs($option)
                            . '"]\');' . PHP_EOL;
                        $script .= $element . '.style.background = "' . $backgroundValue
                            .' no-repeat center";' . PHP_EOL;
                        $script .= $element . '.style.backgroundSize = "initial";';
                        ?>
                        <?= /* @noEscape*/ $secureRenderer->renderTag('script', [], $script, false); ?>
                    </li>
                <?php
                break;
                case '0':
                default:
                ?>
                    <li class="filter__swatch-item">
                        <a
                            href="<?= $block->escapeHtmlAttr($label['link']) ?>"
                            class="
                                filter__swatch-option
                                swatch-option
                                <?= $block->escapeHtmlAttr($label['custom_style']) ?>
                            "
                            tabindex="-1"
                            data-option-type="0"
                            data-option-id="<?= $block->escapeHtmlAttr($option) ?>"
                            data-option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                            data-option-tooltip-thumb=""
                            data-option-tooltip-value=""
                        >
                            <?= $block->escapeHtml($swatchData['swatches'][$option]['value']) ?>
                        </a>
                    </li>
                <?php break ?>
            <?php } ?>
        <?php endif ?>
    <?php endforeach ?>
</ul>
<?php $scriptString = <<<script
    require(["jquery", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.{$block->escapeJs($swatchData['attribute_code'])}')
            .find('[data-option-type="1"], [data-option-type="2"], [data-option-type="0"], [data-option-type="3"]')
            .SwatchRendererTooltip();
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
