<?php $swatchData = $block->getSwatchData(); ?>
<ul
    attribute-code="<?= $swatchData['attribute_code'] ?>"
    attribute-id="<?= $swatchData['attribute_id'] ?>"
    class="list filter__list"
>
    <?php foreach ($swatchData['options'] as $option => $label): ?>
        <?php if (isset($swatchData['swatches'][$option]['type'])): ?>
            <?php switch ($swatchData['swatches'][$option]['type']) {
                case '3':
                ?>
                    <li>
                        <a
                            href="<?= $label['link'] ?>"
                            aria-label="<?= $label['label'] ?>"
                        >
                            <div
                                option-type="3"
                                option-id="<?= $option ?>"
                                option-label="<?= $label['label'] ?>"
                            ></div>
                        </a>
                    </li>
                <?php
                break;
                case '2':
                ?>
                    <?php $swatchThumbPath = $block->getSwatchPath('swatch_thumb',
                    $swatchData['swatches'][$option]['value']); ?>
                    <?php $swatchImagePath = $block->getSwatchPath('swatch_image',
                    $swatchData['swatches'][$option]['value']); ?>
                    <li>
                        <a
                            href="<?= $label['link'] ?>"
                            aria-label="<?= $label['label'] ?>"
                        >
                            <div
                                option-type="2"
                                option-id="<?= $option ?>"
                                option-label="<?= $label['label'] ?>"
                                option-tooltip-thumb="<?= $swatchThumbPath ?>"
                                style="background: url(<?= $swatchImagePath ?>) no-repeat center; background-size: cover;"
                                title="<?= $label['label'] ?>"
                            ></div>
                        </a>
                    </li>
                <?php
                break;
                case '1':
                ?>
                    <li class="filter__color-item">
                        <a
                            href="<?= $label['link'] ?>"
                            class="filter__color-option"
                        >
                            <div
                                class="filter__color-sample"
                                option-type="1"
                                option-id="<?= $option ?>"
                                option-label="<?= $label['label'] ?>"
                                option-tooltip-value="<?= $swatchData['swatches'][$option]['value'] ?>"
                                style="background: <?= $swatchData['swatches'][$option]['value'] ?>"
                            ></div>
                            <span class="filter__color-label">
                                <?= $label['label'] ?>
                            </span>
                        </a>
                    </li>
                <?php
                break;
                case '0':
                default:
                ?>
                    <li class="filter__swatch-item">
                        <a
                            href="<?= $label['link'] ?>"
                            class="filter__swatch-option"
                            option-type="0"
                            option-id="<?= $option ?>"
                            option-label="<?= $label['label'] ?>"
                        >
                            <?= $swatchData['swatches'][$option]['value'] ?>
                        </a>
                    </li>
                <?php break ?>
            <?php } ?>
        <?php endif ?>
    <?php endforeach ?>
</ul>

<script>
    require(["jquery", "jquery/ui", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.<?= $swatchData['attribute_code'] ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
