<?php
/**
 * Customer "Remember Me" template
 */

/** @var \Magento\Persistent\Block\Form\Remember $block */
?>
<div
    id="remember-me-box"
    class="field choice persistent"
>
    <?php $rememberMeId = 'remember_me' . $block->getRandomString(10); ?>
    <div class="checkbox">
        <input
            type="checkbox"
            name="persistent_remember_me"
            class="checkbox__field"
            id="<?= $block->escapeHtmlAttr($rememberMeId) ?>"
            <?php if ($block->isRememberMeChecked()): ?>
            checked="checked"
            <?php endif; ?>
            title="<?= $block->escapeHtmlAttr(__('Remember Me')) ?>"
        />
        <svg class="
                checkbox__icon
                checkbox__icon--checked
            "
            role="presentation"
            focusable="false"
        >
            <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
        </svg>
        <svg class="
                checkbox__icon
                checkbox__icon--unchecked
            "
            role="presentation"
            focusable="false"
        >
            <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
        </svg>
        <label
            for="<?= $block->escapeHtmlAttr($rememberMeId) ?>"
            class="checkbox__label"
        >
            <span>
                <?= $block->escapeHtml(__('Remember Me')) ?>
            </span>
        </label>
    </div>
    <span class="tooltip wrapper">
        <span class="tooltip content">
            <?= $block->escapeHtml(__('Check "Remember Me" to access your shopping cart on this computer even if you are not signed in.')) ?>
        </span>
    </span>
</div>
