<?php
/** @var $block \Magento\Sales\Block\Order\Recent */
?>
<div class="dashboard-table">
    <?php $_orders = $block->getOrders(); ?>
    <div class="dashboard-table__header">
        <h2 class="dashboard-table__title">
            <?= $escaper->escapeHtml(__('Recent Orders')) ?>
        </h2>

        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <a
                class="link dashboard-table__link"
                href="<?= $escaper->escapeUrl($block->getUrl('sales/order/history')) ?>"
            >
                <?= $escaper->escapeHtml(__('View All')) ?>
            </a>
        <?php endif; ?>
    </div>
    <div class="dashboard-table__content">
        <?= $block->getChildHtml() ?>
        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <table
                class="table margin-0"
                tabindex="0"
                role="table"
            >
                <caption class="table__caption">
                    <?= $escaper->escapeHtml(__('Recent Orders')) ?>
                </caption>

                <thead>
                    <tr role="row">
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $escaper->escapeHtml(__('Order #')) ?>
                        </th>

                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $escaper->escapeHtml(__('Date')) ?>
                        </th>

                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $escaper->escapeHtml(__('Ship To')) ?>
                        </th>

                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $escaper->escapeHtml(__('Order Total')) ?>
                        </th>

                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $escaper->escapeHtml(__('Status')) ?>
                        </th>

                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <span class="table__visually-hidden">
                                <?= $escaper->escapeHtml(__('Action')) ?>
                            </span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($_orders as $_order): ?>
                        <tr role="row">
                            <td
                                data-th="<?= $escaper->escapeHtmlAttr(__('Order #')) ?>"
                                role="gridcell"
                            >
                                <?= $escaper->escapeHtml($_order->getRealOrderId()) ?>
                            </td>

                            <td
                                data-th="<?= $escaper->escapeHtmlAttr(__('Date')) ?>"
                                role="gridcell"
                            >
                                <?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?>
                            </td>

                            <td
                                data-th="<?= $escaper->escapeHtmlAttr(__('Ship To')) ?>"
                                role="gridcell"
                            >
                                <?=
                                    $_order->getShippingAddress()
                                        ? $escaper->escapeHtml($_order->getShippingAddress()->getName())
                                        : '&nbsp;'
                                ?>
                            </td>

                            <td
                                data-th="<?= $escaper->escapeHtmlAttr(__('Order Total')) ?>"
                                role="gridcell"
                            >
                                <?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?>
                            </td>

                            <td
                                data-th="<?= $escaper->escapeHtmlAttr(__('Status')) ?>"
                                role="gridcell"
                            >
                                <?= $escaper->escapeHtml($_order->getStatusLabel()) ?>
                            </td>

                            <td
                                data-th="<?= $escaper->escapeHtmlAttr(__('Actions')) ?>"
                                role="gridcell"
                            >
                                <a
                                    href="<?= $escaper->escapeUrl($block->getViewUrl($_order)) ?>"
                                    class="dashboard-table__link"
                                >
                                    <?= $escaper->escapeHtml(__('View Order')) ?>
                                </a>

                                <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())): ?>
                                    |
                                    <a
                                        href="#"
                                        data-post='<?= /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order)) ?>'
                                        class="
                                            action
                                            reorder
                                            link
                                            dashboard-table__link
                                        "
                                    >
                                        <?= $escaper->escapeHtml(__('Reorder')) ?>
                                    </a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <div class="message">
                <?= $escaper->escapeHtml(__('You have placed no orders.')); ?>
            </div>
        <?php endif; ?>
    </div>
</div>
