<?php
use Magento\Framework\View\Element\Template;
use Magento\Vault\Api\Data\PaymentTokenInterface;
use Magento\Vault\Block\CardRendererInterface;

/** @var CardRendererInterface|Template $block */

$ccNumberView = $escaper->escapeHtml($block->getNumberLast4Digits());
?>
<tr>
    <td
        data-th="<?= $escaper->escapeHtmlAttr(__('Card Number')) ?>"
        class="col card-number"
    >
        <?= $escaper->escapeHtml(__('ending ')); ?>
        <?= $ccNumberView ?>
    </td>

    <td
        data-th="<?= $escaper->escapeHtmlAttr(__('Expiration Date')) ?>"
        class="col card-expire"
    >
        <?= $escaper->escapeHtml($block->getExpDate()); ?>
    </td>

    <td data-th="<?= $escaper->escapeHtmlAttr(__('Type')) ?>" class="col card-type">
        <img
            src="<?= $block->getIconUrl(); ?>"
            width="<?= $block->getIconWidth(); ?>"
            height="<?= $block->getIconHeight(); ?>"
        >
    </td>

    <td data-th="<?= $escaper->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
        <form
            class="form"
            action="<?= $escaper->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
            method="post"
        >
            <?= $block->getBlockHtml('formkey') ?>

            <input
                name="<?= PaymentTokenInterface::PUBLIC_HASH ?>"
                value="<?= $block->getToken()->getPublicHash() ?>"
                type="hidden"
            >

            <button
                type="submit"
                class="button delete"
                data-mage-init='{
                    "Magento_Vault/js/customer_account/deleteWidget":{
                        "type": "popup",
                        "modalClass": "my-credit-cards-popup",
                        "toggleEvent": "click",
                        "title": "<?= $escaper->escapeHtml(__('Delete')) ?>",
                        "content": "
                            Are you sure you want to delete this card: <?= $ccNumberView ?>?
                        "
                    }
                }'
            >
                <?= $escaper->escapeHtml(__('Delete')) ?>
            </button>
        </form>
    </td>
</tr>
