<?php
use Magento\Framework\View\Element\Template;
use Magento\Vault\Api\Data\PaymentTokenInterface;
use Magento\Vault\Block\CardRendererInterface;

/** @var CardRendererInterface|Template $block */

$ccNumberView = $block->escapeHtml($block->getNumberLast4Digits());
?>

<tr role="row">
    <td
        data-th="<?= $block->escapeHtmlAttr(__('Card Number')) ?>"
        class="col card-number"
        role="gridcell"
    >
        <?= $block->escapeHtml(__('ending')) ?>
        <?= /* @noEscape */ $ccNumberView ?>
    </td>
    <td
        data-th="<?= $block->escapeHtmlAttr(__('Expiration Date')) ?>"
        class="col card-expire"
        role="gridcell"
    >
        <?= $block->escapeHtml($block->getExpDate()) ?>
    </td>
    <td
        data-th="<?= $block->escapeHtmlAttr(__('Type')) ?>"
        class="col card-type"
        role="gridcell"
    >
        <img
            class="width-initial"
            src="<?= /* @noEscape */ $block->getIconUrl() ?>"
            width="<?= /* @noEscape */ $block->getIconWidth() ?>"
            height="<?= /* @noEscape */ $block->getIconHeight() ?>"
        >
    </td>
    <td
        data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>"
        class="col actions"
        role="gridcell"
    >
        <form
            class="form"
            action="<?= $block->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
            method="post"
        >
            <?= $block->getBlockHtml('formkey') ?>
            <input
                name="<?= /* @noEscape */ PaymentTokenInterface::PUBLIC_HASH ?>"
                value="<?= /* @noEscape */ $block->getToken()->getPublicHash() ?>"
                type="hidden"
            />
            <button
                type="submit"
                class="
                    button
                    button--link
                    padding-hz-0
                    dashboard-table__link
                    action
                    delete
                "
                data-mage-init='{
                    "Magento_Vault/js/customer_account/deleteWidget":{
                        "type": "popup",
                        "modalClass": "my-credit-cards-popup",
                        "toggleEvent": "click",
                        "title": "<?= $block->escapeHtml(__('Delete')) ?>",
                        "content": "<?= $escaper->escapeHtml(__('Are you sure you want to delete this card: %1?', $ccNumberView)) ?>"
                    }
                }'
            >
                <?= $block->escapeHtml(__('Delete')) ?>
            </button>
        </form>
    </td>
</tr>
