<?php foreach ($filterItems as $filterItem): ?>
    <?php if ($filterItem->getCount() > 0): ?>
        <a
            href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
            class="checkbox checkbox--link"
        >
            <svg class="checkbox__icon">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#checked') ?>"></use>
            </svg>
            <span class="checkbox__label">
                <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
            </span>
        </a>
    <?php endif ?>
<?php endforeach ?>
