<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
/** @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer */
?>
<?php foreach ($filterItems as $filterItem): ?>
    <?php if ($filterItem->getCount() > 0): ?>
        <li>
            <a
                href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                class="checkbox checkbox--link"
            >
                <svg class="checkbox__icon" role="presentation">
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                </svg>
                <span class="checkbox__label">
                    <?= /* @noEscape */ $filterItem->getLabel() ?>
                </span>
            </a>
        </li>
    <?php endif ?>
<?php endforeach ?>
