<?php if ($block->canShowBlock()): ?>
    <?= $block->getChildHtml('state') ?>
    <?php $isAnyFilterActive = false ?>
    <?php foreach ($block->getFilters() as $filter) {
        if ($filter->getItemsCount()) {
            $isAnyFilterActive = true;
            break;
        }
    } ?>
    <?php if ($isAnyFilterActive): ?>
        <button
            type="button"
            class="filters__switcher"
            data-state-current="hidden"
        >
            <?= __('Shopping Options') ?>
            <svg class="icon filters__switcher-icon" role="presentation">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
            </svg>
        </button>
        <div
            class="
                filters__list
                filters__list--mobile-hidden
                dropdown-list
                dropdown-list--secondary
            "
            data-mage-init='{
                "filters": { },
                "dropdownList": { }
            }'
        >
            <h2 class="filters__heading filters__heading--mobile-hidden">
                <?= __('Shopping Options') ?>
            </h2>
            <div class="divider filters__divider"></div>
            <ul class="dropdown-list__list">
                <?php foreach ($block->getFilters() as $filter): ?>
                    <?php if ($filter->getItemsCount()): ?>
                        <li
                            class="
                                dropdown-list__item
                                dropdown-list__item--collapse
                                filter
                            "
                        >
                            <button
                                type="button"
                                class="dropdown-list__label filter__label"
                                aria-controls="filter-<?= __($filter->getName()) ?>"
                                aria-expanded="false"
                            >
                                <h3 class="filter__label-title">
                                    <?= $block->escapeHtml(__($filter->getName())) ?>
                                </h3>
                                <svg class="icon dropdown-list__icon" role="presentation">
                                    <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#angle-down') ?>"></use>
                                </svg>
                            </button>
                            <div
                                id="filter-<?= __($filter->getName()) ?>"
                                class="dropdown-list__content filter__content"
                                aria-hidden="true"
                            >
                                <ul class="list">
                                    <?= $block->getChildBlock('renderer')->render($filter) ?>
                                </ul>
                            </div>
                        </li>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>
        </div>
    <?php endif ?>
<?php endif ?>
