<?php
// @codingStandardsIgnoreFile

/**
 * @var \Magento\Company\Block\Company\CompanyProfile $block
 */
?>
<?php if ($block->isEditLinkDisplayed()): ?>
    <div class="title-wrapper__actions">
        <a
            class="button button--link button--secondary"
            href="<?= $escaper->escapeUrl($block->getUrl('*/profile/edit')) ?>"
        >
            <?= $escaper->escapeHtml(__('Edit')) ?>
        </a>
    </div>
<?php endif ?>
