<?php
/**
 * @var \Magento\Company\Block\Company\CompanyProfile $block
 */
?>
<?php if ($block->isEditLinkDisplayed()): ?>
    <a
        href="<?= $block->escapeUrl($block->getUrl('*/profile/edit')) ?>"
        class="
            company-profile__edit-button
            button
            button--secondary
            edit-company-profile
        "
    >
        <?= $block->escapeHtml(__('Edit')) ?>
    </a>
<?php endif; ?>
