<?php
/**
 * @var \Magento\Company\Block\Company\CompanyProfile $block
 */
$company = $block->getCustomerCompany();
?>
<?php if ($block->isViewAccountAllowed()): ?>
<div class="dashboard-items">
    <h2 class="dashboard-items__title margin-bottom-sm">
        <?= $block->escapeHtml(__('Account Information')) ?>
    </h2>
    <div class="row">
        <div class="dashboard-items__item col-sm-6">
            <div class="box-content">
                <?php
                $companyName = $block->escapeHtml($company->getCompanyName());
                $companyName .= (!empty($company->getLegalName()))
                    ? ' (' . $block->escapeHtml($company->getLegalName()) . ')' : '';
                ?>
                <p>
                    <?= /* @noEscape */ $companyName ?>
                    <?php
                    if (!empty($company->getCompanyEmail())): ?>
                        <br/><?= $block->escapeHtml($company->getCompanyEmail()) ?>
                        <?php
                    endif; ?>
                    <?php
                    if (!empty($company->getVatTaxId())): ?>
                        <br/><?= $block->escapeHtml(__('VAT/TAX ID: '))
                            . $block->escapeHtml($company->getVatTaxId()); ?>
                        <?php
                    endif; ?>
                    <?php
                    if (!empty($company->getResellerId())): ?>
                    <br/><?= $block->escapeHtml(__('Re-seller ID: '))
                        . $block->escapeHtml($company->getResellerId()); ?>
                    </p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isViewAddressAllowed()): ?>
<div class="dashboard-items">
    <h2 class="dashboard-items__title margin-bottom-sm">
        <?= $block->escapeHtml(__('Legal Address')) ?>
    </h2>
    <div class="row">
        <div class="dashboard-items__item col-sm-6">
            <div class="box-content">
                <address>
                    <?php if (!$block->isCompanyAddressDisplayed($company)): ?>
                        <?= $block->escapeHtml(
                            __('You have no other address entries in your address book.')
                        ); ?>
                    <?php else: ?>
                        <?php if (!empty($company->getStreet())): ?>
                            <?= $block->escapeHtml($block->getCompanyStreetLabel($company)) ?><br />
                        <?php endif; ?>
                        <?= $block->escapeHtml($block->getCompanyAddressString($company)) ?><br />
                        <?= $block->escapeHtml($block->getCompanyCountryLabel($company)) ?><br />
                        <?= $block->escapeHtml(__('T: %1', $company->getTelephone())) ?>
                    <?php endif; ?>
                    <br />
                </address>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isViewContactsAllowed()): ?>
<div class="dashboard-items">
    <h2 class="dashboard-items__title margin-bottom-sm">
        <?= $block->escapeHtml(__('Contacts')) ?>
    </h2>
    <div class="row">
        <div class="dashboard-items__item col-sm-6">
            <h3 class="dashboard-items__subtitle margin-bottom-l">
                <?= $block->escapeHtml(__('Company Administrator')) ?>
            </h3>
            <div class="box-content">
                <?= $block->escapeHtml($block->getCompanyAdminName($company)) ?><br />
                <?php $companyAdminJobTitle = $block->getCompanyAdminJobTitle($company); ?>
                <?php if (!empty($companyAdminJobTitle)): ?>
                    <?= $block->escapeHtml($companyAdminJobTitle) ?><br />
                <?php endif; ?>
                <?= $block->escapeHtml($block->getCompanyAdminEmail($company)) ?>
            </div>
        </div>

        <div class="dashboard-items__item col-sm-6">
           <h3 class="dashboard-items__subtitle margin-bottom-l">
                <?= $block->escapeHtml(__('Sales Representative')) ?>
           </h3>
            <div class="row">
                <div class="dashboard-items__item col-sm-6">
                    <?= $block->escapeHtml($block->getSalesRepresentativeName($company)) ?>
                    <?= $block->escapeHtml($block->getSalesRepresentativeEmail($company)) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
