<?php
// @codingStandardsIgnoreFile

/**
 * @var \Magento\Company\Block\Company\CompanyProfile $block
 */
$company = $block->getCustomerCompany();
?>

<?php if ($block->isViewAccountAllowed()): ?>
    <div class="block-company-profile-account dashboard-items">
        <h3 class="dashboard-items__title">
            <?= $escaper->escapeHtml(__('Account Information')) ?>
        </h3>
        <div class="block-content grid dashboard-items__content">
            <div class="box box-account-information dashboard-items__item">
                <div class="box-content">
                    <?php
                        $companyName = $escaper->escapeHtml($company->getCompanyName());
                        $companyName .= (!empty($company->getLegalName()))
                            ? ' (' . $escaper->escapeHtml($company->getLegalName()) . ')' : '';
                    ?>
                    <p>
                        <?= $companyName ?>§§
                    </p>
                    <?php if (!empty($company->getCompanyEmail())): ?>
                        <p>
                            <?= $escaper->escapeHtml($company->getCompanyEmail()) ?>
                        </p>
                    <?php endif ?>
                    <?php if (!empty($company->getVatTaxId())): ?>
                        <p>
                            <?= $escaper->escapeHtml(__('VAT/TAX ID: ')). $escaper->escapeHtml($company->getVatTaxId()) ?>
                        </p>
                    <?php endif ?>
                    <?php if (!empty($company->getResellerId())): ?>
                        <p>
                            <?= $escaper->escapeHtml(__('Re-seller ID: ')) . $escaper->escapeHtml($company->getResellerId()) ?>
                        </p>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>
<?php if ($block->isViewAddressAllowed()): ?>
    <div class="block-company-profile-address dashboard-items">
        <h3 class="dashboard-items__title">
            <?= $escaper->escapeHtml(__('Legal Address')) ?>
        </h3>
        <div class="block-content grid dashboard-items__content">
            <div class="box box-address-information dashboard-items__item">
                <div class="box-content">
                    <address>
                        <?php if (!$block->isCompanyAddressDisplayed($company)): ?>
                            <?= $escaper->escapeHtml(__('You have no other address entries in your address book.')) ?><br>
                        <?php else: ?>
                            <?php if (!empty($company->getStreet())): ?>
                                <?= $block->getCompanyStreetLabel($company) ?><br>
                            <?php endif ?>
                            <?= $escaper->escapeHtml($block->getCompanyAddressString($company)) ?><br>
                            <?= $escaper->escapeHtml($block->getCompanyCountryLabel($company)) ?><br>
                            <?= $escaper->escapeHtml(__('T: %1', $company->getTelephone())) ?>
                        <?php endif ?>
                        <br>
                    </address>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>
<?php if ($block->isViewContactsAllowed()): ?>
    <div class="block-company-profile-contacts dashboard-items">
        <h3 class="dashboard-items__title">
            <?= $escaper->escapeHtml(__('Contacts')) ?>
        </h3>
        <div class="block-content row dashboard-items__content">
            <div
                class="
                    box
                    box-contact-information
                    dashboard-items__item
                    col-sm-6
                "
            >
                <h4>
                    <?= $escaper->escapeHtml(__('Company Administrator')) ?>
                </h4>
                <div class="box-content">
                    <?= $escaper->escapeHtml($block->getCompanyAdminName($company)) ?><br>
                    <?php $companyAdminJobTitle = $block->getCompanyAdminJobTitle($company); ?>
                    <?php if (!empty($companyAdminJobTitle)): ?>
                        <?= $escaper->escapeHtml($companyAdminJobTitle) ?><br>
                    <?php endif ?>
                    <?= $escaper->escapeHtml($block->getCompanyAdminEmail($company)) ?>
                </div>
            </div>
            <div class="dashboard-items__item col-sm-6">
                <h4>
                    <?= $escaper->escapeHtml(__('Sales Representative')) ?>
                </h4>
                <div class="box-content">
                    <?= $escaper->escapeHtml($block->getSalesRepresentativeName($company)) ?><br>
                    <?= $escaper->escapeHtml($block->getSalesRepresentativeEmail($company)) ?>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>
