<?php
/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox $block */

/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel      = $block->getPriceType('regular_price');

/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix        = $block->getIdSuffix() ?: '';
$schema          = $block->getZone() == 'item_view';
?>

<?php if ($block->hasSpecialPrice()): ?>
    <div class="price__wrapper display-none">
        <span
            class="
                price__value
                price__value--old
                sly-old-price
            "
        >
            <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => false,
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]) ?>
        </span>
        <span
            class="
                price__value
                price__value--special
                sly-final-price
            "
        >
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => false,
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]) ?>
        </span>
    </div>
<?php else: ?>
    <span
        class="
            price__value
            price__value--normal
        "
    >
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]) ?>
    </span>
<?php endif ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()): ?>
        <a
            href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>"
            class="minimal-price-link"
        >
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else: ?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif ?>
<?php endif ?>
