<?php
/**
 * @see \Magento\Paypal\Block\Express\Review\Details
 * @var \Magento\Paypal\Block\Express\Review\Details $block
 */
?>
<div
    id="details-reload"
    class="table-wrapper order-items"
>
    <table
        id="details-table"
        class="
            table
            table-paypal-review-items
            table--tfoot-scope-row
        "
    >
        <thead>
            <tr role="row">
                <th
                    scope="col"
                    role="columnheader"
                >
                    <?= $block->escapeHtml(__('Item')) ?>
                </th>
                <th
                    scope="col"
                    role="columnheader"
                >
                    <?= $block->escapeHtml(__('Price')) ?>
                </th>
                <th
                    scope="col"
                    role="columnheader"
                >
                    <?= $block->escapeHtml(__('Qty')) ?>
                </th>
                <th
                    scope="col"
                    role="columnheader"
                >
                    <?= $block->escapeHtml(__('Subtotal')) ?>
                </th>
            </tr>
        </thead>
            <?php foreach ($block->getItems() as $item) : ?>
                <?= $block->getItemHtml($item) ?>
            <?php endforeach ?>
        <tfoot class="opc-block-summary">
            <?= $block->getChildHtml('totals') ?>
        </tfoot>
    </table>
</div>
