<?php $_countries = $this->getCountries() ?>
<?php if (count($_countries) > 0): ?>
    <div class="select select--native">
        <select
            name="<?= $this->getFieldName()?>"
            id='<?= $this->getFieldId()?>'
            class='select__field <?= $this->getFieldClass()?>'
            style='<?= $this->getFieldStyle()?>'
            <?php if ($this->getField()->getHideLabel()): ?>
                aria-label="<?= $this->getField()->getName() ?>"
            <?php else: ?>
                aria-labelledby="label_<?= $this->getFieldId() ?>"
            <?php endif; ?>
            <?php if($this->getField()->getBrowserAutocomplete()): ?>
                autocomplete="<?= $this->getField()->getBrowserAutocomplete()?>"
            <?php endif; ?>
            <?php if($this->getField()->getRequired()): ?>
                aria-required="true"
            <?php endif; ?>
            <?php if($this->getField()->getDisabled()): ?>
                disabled
            <?php endif; ?>
            <?= htmlspecialchars($this->getField()->getCustomAttributes()) ?>
        >
            <?php foreach($_countries as $_country): ?>
                <?php $selected = ($this->getFieldValue() == $_country['value']) ? 'selected="selected"' : ''; ?>
                <option
                    value="<?= $_country['value'] ?>"
                    <?= $selected ?>
                >
                    <?= $_country['label'] ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
<?php endif; ?>
