<?php $_countries = $this->getCountries() ?>
<?php if (count($_countries) > 0): ?>
    <div class="select select--native">
        <select
            name="<?= $block->escapeHtmlAttr($this->getFieldName()) ?>"
            id='<?= $block->escapeHtmlAttr($this->getFieldId()) ?>'
            class='
                select__field
                <?= $block->escapeHtmlAttr($this->getFieldClass()) ?>
            '
            style='<?= $block->escapeHtmlAttr($this->getFieldStyle()) ?>'
            <?php if ($this->getField()->getHideLabel()): ?>
                aria-label="<?= $block->escapeHtmlAttr($this->getField()->getName()) ?>"
            <?php else: ?>
                aria-labelledby="label_<?= $block->escapeHtmlAttr($this->getFieldId()) ?>"
            <?php endif; ?>
            <?php if($this->getField()->getBrowserAutocomplete()): ?>
                autocomplete="<?= $block->escapeHtmlAttr($this->getField()->getBrowserAutocomplete()) ?>"
            <?php endif; ?>
            <?php if($this->getField()->getRequired()): ?>
                aria-required="true"
            <?php endif; ?>
            <?php if($this->getField()->getDisabled()): ?>
                disabled
            <?php endif; ?>
            <?= /* @noEscape */ htmlspecialchars($this->getField()->getCustomAttributes()) ?>
        >
            <?php foreach($_countries as $_country): ?>
                <?php $selected = ($this->getFieldValue() == $_country['value']) ? 'selected="selected"' : ''; ?>
                <option
                    value="<?= $block->escapeHtmlAttr($_country['value']) ?>"
                    <?= /* @noEscape */ $selected ?>
                >
                    <?= $block->escapeHtml($_country['label']) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
<?php endif; ?>
