<?php $hint = htmlspecialchars(trim($this->getField()->getHint())); ?>
<div class="input">
    <input
        type='number'
        name='<?= $this->getFieldName() ?>'
        id='<?= $this->getFieldId() ?>'
        class='input__field <?= $this->getFieldClass() ?>'
        style='<?= $this->getFieldStyle() ?>'
        value="<?= htmlspecialchars($this->getFieldValue()); ?>"
        placeholder="<?= $hint ?>"
        <?php if ($this->getField()->getHideLabel()): ?>
            aria-label="<?= $this->getField()->getName() ?>"
        <?php else: ?>
            aria-labelledby="label_<?= $this->getFieldId() ?>"
        <?php endif; ?>
        <?php if ($this->getField()->getRequired()): ?>
            aria-required="true"
        <?php endif; ?>
        <?php if ($this->getField()->getBrowserAutocomplete()): ?>
            autocomplete="<?= $this->getField()->getBrowserAutocomplete() ?>"
        <?php endif; ?>
        <?php if (strlen($this->getMin())): ?>
            min="<?= $this->getMin() ?>"
        <?php endif; ?>
        <?php if (strlen($this->getMax())): ?>
            max="<?= $this->getMax() ?>"
        <?php endif; ?>
        <?php if ($this->getField()->getDisabled()): ?>
            disabled
        <?php endif; ?>
        <?= htmlspecialchars($this->getField()->getCustomAttributes()) ?>
    />
</div>
