<?php $hint = htmlspecialchars(trim($this->getField()->getHint())); ?>
<input type='number' name='<?php echo $this->getFieldName() ?>' id='<?php echo $this->getFieldId() ?>'
       class='input__field <?php echo $this->getFieldClass() ?>' style='<?php echo $this->getFieldStyle() ?>'
       value="<?php echo htmlspecialchars($this->getFieldValue()); ?>"
       <?php if ($this->getField()->getHideLabel()) { ?>aria-label="<?php echo $this->getField()->getName() ?>"
    <?php } else { ?> aria-labelledby="label_<?php echo $this->getFieldId() ?>" <?php } ?>
       <?php if ($this->getField()->getRequired()) { ?>aria-required="true"<?php } ?>
       <?php if($this->getField()->getBrowserAutocomplete()) { ?>autocomplete="<?php echo $this->getField()->getBrowserAutocomplete()?>" <?php }?>
        <?php if (strlen($this->getMin())) echo "min=" . $this->getMin(); ?>
    <?php if (strlen($this->getMax())) echo "max=" . $this->getMax(); ?>
    <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?>
       placeholder="<?php echo $hint?>" <?php echo htmlspecialchars($this->getField()->getCustomAttributes())?>/>
