<?php $hint = htmlspecialchars(trim($this->getField()->getHint())); ?>
<div class="input">
    <input
        type='number'
        name='<?= $block->escapeHtmlAttr($this->getFieldName()) ?>'
        id='<?= $block->escapeHtmlAttr($this->getFieldId()) ?>'
        class='input__field <?= $block->escapeHtmlAttr($this->getFieldClass()) ?>'
        style='<?= $block->escapeHtmlAttr($this->getFieldStyle()) ?>'
        value="<?= /* @noEscape */ htmlspecialchars($this->getFieldValue()); ?>"
        placeholder="<?= $block->escapeHtmlAttr($hint) ?>"
        <?php if ($this->getField()->getHideLabel()): ?>
            aria-label="<?= $block->escapeHtmlAttr($this->getField()->getName()) ?>"
        <?php else: ?>
            aria-labelledby="label_<?= $block->escapeHtmlAttr($this->getFieldId()) ?>"
        <?php endif; ?>
        <?php if ($this->getField()->getRequired()): ?>
            aria-required="true"
        <?php endif; ?>
        <?php if ($this->getField()->getBrowserAutocomplete()): ?>
            autocomplete="<?= $block->escapeHtmlAttr($this->getField()->getBrowserAutocomplete()) ?>"
        <?php endif; ?>
        <?php if (strlen($this->getMin())): ?>
            min="<?= $block->escapeHtmlAttr($this->getMin()) ?>"
        <?php endif; ?>
        <?php if (strlen($this->getMax())): ?>
            max="<?= $block->escapeHtmlAttr($this->getMax()) ?>"
        <?php endif; ?>
        <?php if ($this->getField()->getDisabled()): ?>
            disabled
        <?php endif; ?>
        <?= /* @noEscape */ htmlspecialchars($this->getField()->getCustomAttributes()) ?>
    />
</div>
