<div class="select select--native">
    <select
        name='<?= $this->getFieldName()?>'
        id='<?= $this->getFieldId()?>'
        class='
            select__field
            <?= $this->getFieldClass()?>
        '
        data-mage-init='{"select": {"options": {"shouldSort": false}}}'
        style='<?= $this->getFieldStyle()?>' <?php if ($this->getField()->getDisabled()) { ?>
        disabled <?php } ?> <?= htmlspecialchars($this->getField()->getCustomAttributes())?>
        <?php if ($this->getField()->getHideLabel()) { ?>
            aria-label="<?= $this->getField()->getName() ?>"
        <?php } else { ?>
            aria-labelledby="label_<?= $this->getFieldId() ?>" <?php } ?>
        <?php if ($this->getField()->getRequired()) { ?>
            aria-required="true"<?php } ?>
        <?php if($this->getField()->getBrowserAutocomplete()) { ?>
            autocomplete="<?= $this->getField()->getBrowserAutocomplete()?>" <?php }?>
    >
        <?php foreach ($this->getFieldOptions() as $i => $option) {
            $checked = false;
            if ($option["checked"]) {
                $checked = 'selected';
            }
            if (isset($option["value"])) {
                $contact = $this->getField()->getContactArray($option["value"]);
                $value = $option["value"];
                if ($option['null']) {
                    $value = '';
                }
                if (!empty($option['optgroup']) && !empty($option['label'])) {
                    ?>
                    <optgroup label="<?= $option['label'] ?>">
                    <?php
                } elseif (!empty($option['optgroup_close'])) {
                    ?>
                    </optgroup>
                    <?php
                } else
                    if ($contact) {
                    ?>
                    <option value="<?= $contact["email"] ? $i : $value;?>" <?= $checked?>><?= $contact['name']?></option>
                    <?php
                }
            }
        }
        ?>
    </select>
</div>
