<div>
    <?php
    $validate = '';
    $validate_min = '';
    $validate_max = '';
    $options = $this->getFieldOptions();
    foreach ($this->getFieldOptions() as $i => $option) {
        $checked = false;
        $validate_min = '';
        $validate_max = '';
        if ($option["checked"]) {
            $checked = 'checked';
        }
        if ($this->getField()->getRequired() && $i == (count($options) - 1)) {
            $validate = "validate-one-required-by-name";
            if ($this->getField()->getData('validate_regex')) {
                $validate .= ' validate-field-' . $this->getField()->getId();
            }
            $validate .= ' ' . $this->getFieldClass();
        }
        if ($this->getMin() && $i == (count($options) - 1)) {
            $validate_min = "validate-field-options-min-{$this->getField()->getId()}";
        }
        if ($this->getMax() && $i == (count($options) - 1)) {
            $validate_max = "validate-field-options-max-{$this->getField()->getId()}";
        }
        if(!$this->getField()->getValidationAdvice()){
            $this->getField()->setValidationAdvice(__('Please select one of the options.'));
        }
        if (isset($option["value"]) && empty($option['optgroup']) && empty($option['optgroup_close'])) {
            $label = $option["label"];
            if ($option["image_src"]) {
                $label = "<figure><img src='{$option['image_src']}'/><figcaption>{$label}</figcaption></figure>";
            }
            ?>

            <div class='field choice option-<?php echo $i?>' style='<?php echo $this->getFieldStyle() ?>'>
                <input type='checkbox'
                       name='<?php echo $this->getFieldName() ?>[]'
                       id='<?php echo $this->getFieldId() . $i ?>'
                       value="<?php echo htmlspecialchars($option["value"]) ?>"
                       class='checkbox <?php echo $validate ?> <?php echo $validate_min?> <?php echo $validate_max?>' <?php echo $checked ?>
                       aria-labelledby="<?php echo $this->getFieldId() . $i ?>_label<?php if(!$this->getField()->getHideLabel()){?> label_<?php echo $this->getFieldId() ?><?php } ?>"
                    <?php echo htmlspecialchars($this->getField()->getCustomAttributes())?>
                />
                <label id="<?php echo $this->getFieldId() . $i ?>_label"
                       for='<?php echo $this->getFieldId() . $i ?>' class=''><?php echo $label ?></label>
                <?php
                $tooltip = $this->getField()->getTooltip($option["value"]);
                if ($tooltip) {
                    echo $this->getLayout()->createBlock(
                        'VladimirPopov\WebForms\Block\Script\Tooltip',
                        null
                    )->setField($this->getField())->setTooltip($tooltip)->toHtml();
                }
                ?>

            </div>

            <?php
        }
    }
    ?>
</div>
<?php if($validate_min) {
    $validate_message = __('Please check at least %1 options', $this->getField()->getValue('options_checkbox_min'));
    if (!empty($this->getField()->getValue('options_checkbox_min_error_text')))
        $validate_message = $this->getField()->getValue('options_checkbox_min_error_text');
    ?>
    <div class="validation-advice"
         id="advice-validate-field-options-min-<?php echo $this->getField()->getId()?>-<?php echo $this->getFieldId(). $i?>"
         style="display:none"><?php echo $validate_message ?></div>
<?php }?>
<?php if($validate_max) {
    $validate_message = __('Please check not more than %1', $this->getField()->getValue('options_checkbox_max'));
    if (!empty($this->getField()->getValue('options_checkbox_max_error_text')))
        $validate_message = $this->getField()->getValue('options_checkbox_max_error_text');
    ?>
    <div class="validation-advice"
         id="advice-validate-field-options-max-<?php echo $this->getField()->getId()?>-<?php echo $this->getFieldId(). $i?>"
         style="display:none"><?php echo $validate_message ?></div>
<?php }?>
<?php if ($validate && $this->getField()->getValidationAdvice()) { ?>
    <div class="validation-advice"
         id="advice-validate-one-required-by-name-<?php echo $this->getFieldId() . $i ?>"
         style="display:none"><?php echo $this->getField()->getValidationAdvice() ?></div>
<?php } ?>