<div class="select select--native">
    <select
        name='<?= $block->escapeHtmlAttr($this->getFieldName()) ?><?php if ($this->getMultiselect()) echo '[]' ?>'
        id='<?= $block->escapeHtmlAttr($this->getFieldId()) ?>'
        class='
            select__field
            <?= $block->escapeHtmlAttr($this->getFieldClass()) ?>
        '
        style='<?= $block->escapeHtmlAttr($this->getFieldStyle()) ?>'
        data-mage-init='{"select": {"options": {"shouldSort": false}}}'
        <?php if ($this->getField()->getHideLabel()): ?>
            aria-label="<?= $block->escapeHtmlAttr($this->getField()->getName()) ?>"
        <?php else: ?>
            aria-labelledby="label_<?= $block->escapeHtmlAttr($this->getFieldId()) ?>"
        <?php endif; ?>
        <?php if ($this->getField()->getRequired()): ?>
            aria-required="true"
        <?php endif; ?>
        <?php if ($this->getField()->getBrowserAutocomplete()): ?>
            autocomplete="<?= $block->escapeHtmlAttr($this->getField()->getBrowserAutocomplete()) ?>"
        <?php endif; ?>
        <?php if ($this->getField()->getDisabled()): ?>
            disabled
        <?php endif; ?>
        <?php if ($this->getMultiselect()): ?>
            multiple
        <?php endif; ?>
        <?= /* @noEscape */ htmlspecialchars($this->getField()->getCustomAttributes()) ?>
    >

        <?php foreach ($this->getFieldOptions() as $option): ?>
            <?php
                $checked = false;
                $disabled = false;
                if ($option["checked"]) {
                    $checked = 'selected';
                }
                if ($option["disabled"]) {
                    $disabled = 'disabled';
                }
            ?>
            <?php if (isset($option["value"])): ?>
                <?php
                    $value = htmlspecialchars($option["value"]);
                    if ($option['null']) {
                        $value = '';
                    }
                ?>
                <option
                    value="<?= $block->escapeHtmlAttr($value) ?>"
                    <?= /* @noEscape */ $checked ?>
                    <?= /* @noEscape */ $disabled ?>
                >
                    <?= $block->escapeHtml($option['label']) ?>
                </option>
            <?php endif; ?>
        <?php endforeach; ?>
    </select>
</div>
