<div class="select select--native">
    <select
        name='<?php echo $this->getFieldName()?>'
        id='<?php echo $this->getFieldId()?>'
        class='
            select__field
            <?php echo $this->getFieldClass()?>
        '
        data-mage-init='{"select": {"options": {"shouldSort": false}}}'
        style='<?php echo $this->getFieldStyle()?>' <?php if ($this->getField()->getDisabled()) { ?>
        disabled <?php } ?> <?php echo htmlspecialchars($this->getField()->getCustomAttributes())?>
        <?php if ($this->getField()->getHideLabel()) { ?>
            aria-label="<?php echo $this->getField()->getName() ?>"
        <?php } else { ?>
            aria-labelledby="label_<?php echo $this->getFieldId() ?>" <?php } ?>
        <?php if ($this->getField()->getRequired()) { ?>
            aria-required="true"<?php } ?>
        <?php if($this->getField()->getBrowserAutocomplete()) { ?>
            autocomplete="<?php echo $this->getField()->getBrowserAutocomplete()?>" <?php }?>
    >
        <?php
        foreach ($this->getFieldOptions() as $i => $option) {
            $checked = false;
            if ($option["checked"]) {
                $checked = 'selected';
            }
            if (isset($option["value"])) {
                $contact = $this->getField()->getContactArray($option["value"]);
                $value = $option["value"];
                if ($option['null']) {
                    $value = '';
                }
                if (!empty($option['optgroup']) && !empty($option['label'])) {
                    ?>
                    <optgroup label="<?php echo $option['label'] ?>">
                    <?php
                } elseif (!empty($option['optgroup_close'])) {
                    ?>
                    </optgroup>
                    <?php
                } else
                    if ($contact) {
                    ?>
                    <option value="<?php echo $contact["email"] ? $i : $value;?>" <?php echo $checked?>><?php echo $contact['name']?></option>
                    <?php
                }
            }
        }
        ?>
    </select>
</div>
