<?php
$validate = '';
$options = $this->getFieldOptions();
$fieldId = $block->escapeHtmlAttr($this->getFieldId());
?>
<div
    <?php if ($this->getField()->getHideLabel()): ?>
        aria-label="<?= $block->escapeHtmlAttr($this->getField()->getName()) ?>"
    <?php else: ?>
        aria-labelledby="label_<?= $block->escapeHtmlAttr($fieldId) ?>"
    <?php endif; ?>
>
    <?php foreach ($this->getFieldOptions() as $i => $option): ?>
        <?php
            $checked = false;
            if ($option["checked"]) {
                $checked = 'checked';
            }
            if ($this->getField()->getRequired() && $i == (count($options) - 1)) {
                $validate = "validate-one-required-by-name";
                if ($this->getField()->getData('validate_regex')) {
                    $validate .= ' validate-field-' . $this->getField()->getId();
                }
            }
            if (!$this->getField()->getValidationAdvice()) {
                $this->getField()->setValidationAdvice(__('Please select one of the options.'));
            }
        ?>
        <?php if (isset($option["value"]) && empty($option['optgroup']) && empty($option['optgroup_close'])): ?>
            <?php
                $label = $option["label"];
                if ($option["image_src"]) {
                    $label = "<figure><img src='{$option['image_src']}'/><figcaption>{$label}</figcaption></figure>";
                }
            ?>
            <div
                class="
                    field
                    choice
                    option-<?= $block->escapeHtmlAttr($i) ?>
                    radio__handler
                "
                style="<?= $block->escapeHtmlAttr($this->getFieldStyle()) ?>">
                <input
                    type="radio"
                    id="<?= $block->escapeHtmlAttr($fieldId . $i) ?>"
                    name="<?= $block->escapeHtmlAttr($this->getFieldName()) ?>"
                    value="<?= $block->escapeHtmlAttr(htmlspecialchars($option['value'])) ?>"
                    class="radio__field <?= $block->escapeHtmlAttr($validate) ?>"
                    aria-labelledby="
                        <?= $block->escapeHtmlAttr($fieldId . $i) ?>_label
                        <?php if(!$this->getField()->getHideLabel()): ?>
                             label_<?= $block->escapeHtmlAttr($fieldId) ?>
                        <?php endif; ?>
                    "
                    <?= /* @noEscape */ $checked ?>
                    <?php if ($this->getField()->getDisabled()): ?>
                        disabled
                    <?php endif; ?>
                    <?= /* @noEscape */ htmlspecialchars($this->getField()->getCustomAttributes()) ?>
                />
                <label
                    id="<?= $block->escapeHtmlAttr($fieldId . $i) ?>_label"
                    for="<?= $block->escapeHtmlAttr($fieldId . $i) ?>"
                    class="radio__label <?= $block->escapeHtmlAttr($this->getFieldClass()) ?>"
                >
                    <?= $block->escapeHtml($label) ?>
                </label>
                <?php
                    $tooltip = $this->getField()->getTooltip($option["value"]);
                ?>
                <?= ($tooltip) ? $this->getLayout()->createBlock(
                    'VladimirPopov\WebForms\Block\Script\Tooltip',
                    null
                )->setField($this->getField())->setTooltip($tooltip)->toHtml() : ''; ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<?php if ($validate && $this->getField()->getValidationAdvice()) { ?>
    <!-- style="display:none" should be inline for validation message -->
    <div
        class="
            validation-advice
        "
        id="advice-validate-one-required-by-name-<?= $block->escapeHtmlAttr($fieldId . $i) ?>"
        style="display:none"
    >
        <?= $block->escapeHtml($this->getField()->getValidationAdvice()) ?>
    </div>
<?php } ?>
