<div>
    <?php
    $validate = '';
    $validate_min = '';
    $validate_max = '';
    $options = $this->getFieldOptions();
    foreach ($this->getFieldOptions() as $i => $option):
        $checked = false;
        $validate_min = '';
        $validate_max = '';
        if ($option["checked"]) {
            $checked = 'checked';
        }
        if ($this->getField()->getRequired() && $i == (count($options) - 1)) {
            $validate = "validate-one-required-by-name";
            if ($this->getField()->getData('validate_regex')) {
                $validate .= ' validate-field-' . $this->getField()->getId();
            }
            $validate .= ' ' . $this->getFieldClass();
        }
        if ($this->getMin() && $i == (count($options) - 1)) {
            $validate_min = "validate-field-options-min-{$this->getField()->getId()}";
        }
        if ($this->getMax() && $i == (count($options) - 1)) {
            $validate_max = "validate-field-options-max-{$this->getField()->getId()}";
        }
        if (!$this->getField()->getValidationAdvice()){
            $this->getField()->setValidationAdvice(__('Please select one of the options.'));
        }
    ?>
        <?php if (isset($option["value"]) && empty($option['optgroup']) && empty($option['optgroup_close'])):
            $label = $option["label"];
            if ($option["image_src"]) {
                $label = "<figure><img src='{$option['image_src']}'/><figcaption>{$label}</figcaption></figure>";
            }
        ?>
            <div
                class='
                    field
                    choice
                    option-<?= $block->escapeHtmlAttr($i) ?>
                    checkbox
                '
                style='<?= $block->escapeHtmlAttr($this->getFieldStyle()) ?>'
            >
                <input type='checkbox'
                    name='<?= $block->escapeHtmlAttr($this->getFieldName()) ?>[]'
                    id='<?= $block->escapeHtmlAttr($this->getFieldId() . $i) ?>'
                    value="<?= $block->escapeHtmlAttr(htmlspecialchars($option['value'])) ?>"
                    class='
                        checkbox__field
                        <?= $block->escapeHtmlAttr($validate) ?>"
                        <?= $block->escapeHtmlAttr($validate_min ) ?>"
                        <?= $block->escapeHtmlAttr($validate_max ) ?>"
                    '
                    <?= /* @noEscape */ $checked ?>
                    aria-labelledby="
                        <?= $block->escapeHtmlAttr($this->getFieldId() . $i) ?>
                        <?php if(!$this->getField()->getHideLabel()): ?>
                                label_<?= $block->escapeHtmlAttr($this->getFieldId()) ?>
                        <?php endif; ?>
                    "
                    <?= /* @noEscape */ htmlspecialchars($this->getField()->getCustomAttributes())?>
                />
                <svg
                    class="checkbox__icon checkbox__icon--checked"
                    role="presentation"
                    focusable="false"
                >
                    <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked')) ?>"/>
                </svg>
                    <svg
                    class="checkbox__icon checkbox__icon--unchecked"
                    role="presentation"
                    focusable="false"
                >
                    <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#unchecked')) ?>"/>
                </svg>
                <label
                    id="<?= $block->escapeHtmlAttr($this->getFieldId() . $i) ?>_label"
                    for="<?= $block->escapeHtmlAttr($this->getFieldId() . $i) ?>"
                    class="checkbox__label"
                >
                    <?= $block->escapeHtml($label) ?>
                </label>
                <?php
                    $tooltip = $this->getField()->getTooltip($option["value"]);
                    if ($tooltip) {
                        echo $this->getLayout()->createBlock(
                            'VladimirPopov\WebForms\Block\Script\Tooltip',
                            null
                        )->setField($this->getField())->setTooltip($tooltip)->toHtml();
                    }
                ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>

<?php if ($validate_min):
    $validate_message = __('Please check at least %1 options', $this->getField()->getValue('options_checkbox_min'));
    if (!empty($this->getField()->getValue('options_checkbox_min_error_text')))
        $validate_message = $this->getField()->getValue('options_checkbox_min_error_text');
?>
    <div
        id="advice-validate-field-options-max-<?= $block->escapeHtmlAttr($this->getField()->getId())?>-<?= $block->escapeHtmlAttr($this->getFieldId(). $i)?>"
        class="validation-advice display-none"
    >
        <?= $block->escapeHtml($validate_message) ?>
    </div>
<?php endif;?>

<?php if ($validate_max):
    $validate_message = __('Please check not more than %1', $this->getField()->getValue('options_checkbox_max'));
    if (!empty($this->getField()->getValue('options_checkbox_max_error_text')))
        $validate_message = $this->getField()->getValue('options_checkbox_max_error_text');
?>
    <div
        id="advice-validate-field-options-max-<?= $block->escapeHtmlAttr($this->getField()->getId())?>-<?= $block->escapeHtmlAttr($this->getFieldId(). $i)?>"
        class="validation-advice display-none"
    >
        <?= $block->escapeHtml($validate_message) ?>
    </div>
<?php endif;?>

<?php if ($validate && $this->getField()->getValidationAdvice()): ?>
    <div
        id="advice-validate-one-required-by-name-<?= $block->escapeHtmlAttr($this->getFieldId() . $i) ?>"
        class="validation-advice display-none"
    >
        <?= $block->escapeHtml($this->getField()->getValidationAdvice()) ?>
    </div>
<?php endif;?>
