<?php $placeholder = htmlspecialchars(trim($this->getPlaceholder())); ?>
<div class="input">
    <textarea
        name='<?= $block->escapeHtmlAttr($this->getFieldName()) ?>'
        id='<?= $block->escapeHtmlAttr($this->getFieldId()) ?>'
        class='
            input__field
            input__field--textarea
            <?= $block->escapeHtmlAttr($this->getFieldClass()) ?>
        '
        placeholder="<?= $block->escapeHtmlAttr($placeholder) ?>"
        style='<?= $block->escapeHtmlAttr($this->getFieldStyle()) ?>'
        <?php if ($this->getField()->getHideLabel()): ?>
            aria-label="<?= $block->escapeHtmlAttr($this->getField()->getName()) ?>"
        <?php else: ?>
            aria-labelledby="label_<?= $block->escapeHtmlAttr($this->getFieldId()) ?>"
        <?php endif; ?>
        <?php if ($this->getField()->getRequired()): ?>
            aria-required="true"
        <?php endif; ?>
        <?php if ($this->getField()->getBrowserAutocomplete()): ?>
            autocomplete="<?= $block->escapeHtmlAttr($this->getField()->getBrowserAutocomplete()) ?>"
        <?php endif ?>
        <?php if ($this->getField()->getDisabled()): ?>
            disabled
        <?php endif ?>
        <?= /* @noEscape */ htmlspecialchars($this->getField()->getCustomAttributes()) ?>
    ><?= $block->escapeHtml($this->getFieldValue()); ?></textarea>
</div>
