<?php $placeholder = htmlspecialchars(trim($this->getPlaceholder())); ?>
<div class="input">
    <textarea
        name='<?= $this->getFieldName() ?>'
        id='<?= $this->getFieldId() ?>'
        class='
            input__field
            input__field--textarea
            <?= $this->getFieldClass() ?>
        '
        placeholder="<?= $placeholder ?>"
        style='<?= $this->getFieldStyle() ?>'
        <?php if ($this->getField()->getHideLabel()): ?>
            aria-label="<?= $this->getField()->getName() ?>"
        <?php else: ?>
            aria-labelledby="label_<?= $this->getFieldId() ?>"
        <?php endif; ?>
        <?php if ($this->getField()->getRequired()): ?>
            aria-required="true"
        <?php endif; ?>
        <?php if ($this->getField()->getBrowserAutocomplete()): ?>
            autocomplete="<?= $this->getField()->getBrowserAutocomplete() ?>"
        <?php endif ?>
        <?php if ($this->getField()->getDisabled()): ?>
            disabled
        <?php endif ?>
        <?= htmlspecialchars($this->getField()->getCustomAttributes()) ?>
    ><?= $this->getFieldValue(); ?></textarea>
</div>
