<?php $placeholder = htmlspecialchars(trim($this->getPlaceholder())); ?>

<div class="input">
    <input
        type='text'
        name='<?= $block->escapeHtmlAttr($this->getFieldName()) ?>'
        id='<?= $block->escapeHtmlAttr($this->getFieldId()) ?>'
        class='input__field <?= $block->escapeHtmlAttr($this->getFieldClass()) ?>'
        style='<?= $block->escapeHtmlAttr($this->getFieldStyle()) ?>'
        value="<?= /* @noEscape */ htmlspecialchars($this->getFieldValue()); ?>"
        placeholder="<?= $block->escapeHtmlAttr($placeholder) ?>"
        <?php if ($this->getField()->getHideLabel()): ?>
            aria-label="<?= $block->escapeHtmlAttr($this->getField()->getName()) ?>"
        <?php else: ?>
            aria-labelledby="label_<?= $block->escapeHtmlAttr($this->getFieldId()) ?>"
        <?php endif; ?>
        <?php if ($this->getField()->getRequired()): ?>
            aria-required="true"
        <?php endif; ?>
        <?php if ($this->getField()->getBrowserAutocomplete()): ?>
            autocomplete="<?= $block->escapeHtmlAttr($this->getField()->getBrowserAutocomplete()) ?>"
        <?php endif; ?>
        <?php if ($this->getField()->getType() == 'email'): ?>
            onkeyup="if(this.value.search(' ')>=0){this.value = this.value.replace(' ','');}"
        <?php endif; ?>
        <?php if ($this->getField()->getDisabled()): ?>
            disabled
        <?php endif; ?>
        <?= /* @noEscape */ htmlspecialchars($this->getField()->getCustomAttributes()) ?>
    />
</div>
