<?php $placeholder = htmlspecialchars(trim($this->getPlaceholder())); ?>
<input
    type='text'
    name='<?= $this->getFieldName() ?>'
    id='<?= $this->getFieldId() ?>'
    class='input__field <?= $this->getFieldClass() ?>'
    style='<?= $this->getFieldStyle() ?>'
    value="<?= htmlspecialchars($this->getFieldValue()); ?>"
    placeholder="<?= $placeholder ?>"
    <?php if ($this->getField()->getHideLabel()): ?>
        aria-label="<?= $this->getField()->getName() ?>"
    <?php else: ?>
        aria-labelledby="label_<?= $this->getFieldId() ?>"
    <?php endif; ?>
    <?php if ($this->getField()->getRequired()): ?>
        aria-required="true"
    <?php endif; ?>
    <?php if ($this->getField()->getBrowserAutocomplete()): ?>
        autocomplete="<?= $this->getField()->getBrowserAutocomplete() ?>"
    <?php endif; ?>
    <?php if ($this->getField()->getType() == 'email'): ?>
        onkeyup="if(this.value.search(' ')>=0){this.value = this.value.replace(' ','');}"
    <?php endif; ?>
    <?php if ($this->getField()->getDisabled()): ?>
        disabled
    <?php endif; ?>
    <?= htmlspecialchars($this->getField()->getCustomAttributes()) ?>
/>
