<?php
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>

    <?php if ($heading = $block->getTitle()): ?>
        <h2 class="catalog-grid__title">
            <?= $escaper->escapeHtml(__($heading)) ?>
        </h2>
    <?php endif ?>

    <?php if (count($items) == 0): ?>
        <div class="message info empty">
            <div>
                <?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?>
            </div>
        </div>
    <?php else: ?>
        <ul class="catalog-grid">
            <?php foreach ($items as $_item): ?>
                <li class="catalog-grid-item">
                    <a
                        href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                        class="catalog-grid-item__link"
                        title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                    >
                        <?= /* @noEscape */ $block->getImage($_item, $image)->toHtml() ?>
                    </a>
                    <section class="catalog-grid-item__details">
                        <h2 class="catalog-grid-item__name">
                            <a
                                title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                                class="catalog-grid-item__name-link"
                            >
                                <?= $escaper->escapeHtml($_item->getName()) ?>
                            </a>
                        </h2>

                        <div class="catalog-grid-item__price">
                            <?= $block->getProductPriceHtml($_item, $type) ?>
                            <?= $block->getProductDetailsHtml($_item) ?>
                        </div>

                        <?php if ($templateType): ?>
                            <div class="rating catalog-grid-item__rating" tabindex="0">
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            </div>
                        <?php endif; ?>

                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                            <div class="catalog-grid-item__actions">
                                <?php if ($showCart): ?>
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>

                                        <form
                                            class="catalog-grid-item__primary-form"
                                            data-role="tocart-form"
                                            data-product-sku="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>"
                                            action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                            method="post"
                                        >
                                            <input
                                                type="hidden"
                                                name="product"
                                                value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>"
                                            >
                                            <input
                                                type="hidden"
                                                name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>"
                                            >

                                            <?= $block->getBlockHtml('formkey') ?>

                                            <button
                                                class="
                                                    button
                                                    button--secondary
                                                    catalog-grid-item__primary-action
                                                    action
                                                    tocart
                                                "
                                                type="submit"
                                            >
                                                <span class="catalog-grid-item__cart-text">
                                                    <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                </span>
                                                <svg class="icon catalog-grid-item__cart-icon">
                                                    <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#shopping-cart')) ?>"></use>
                                                </svg>
                                            </button>
                                        </form>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare): ?>
                                    <div class="catalog-grid-item__secondary-action">
                                        <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                            <a
                                                href="#"
                                                data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                class="
                                                    button
                                                    button--icon
                                                    action
                                                    towishlist
                                                "
                                                data-action="add-to-wishlist"
                                                title="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                            >
                                                <svg class="button__icon">
                                                    <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#heart')) ?>"></use>
                                                </svg>
                                            </a>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                            <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                            <a
                                                href="#"
                                                class="
                                                    button
                                                    button--icon
                                                    action
                                                    tocompare
                                                "
                                                data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                            >
                                                <svg class="button__icon">
                                                    <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#compare')) ?>"></use>
                                                </svg>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </section>
                </li>
            <?php endforeach ?>
        </ul>

        <?= $block->getPagerHtml() ?>
    <?php endif ?>
    <?php if ($block->getBlockHtml('formkey')): ?>
        <script type="text/x-magento-init">
        {
            ".block.widget [data-role=tocart-form]": {
                "Magento_Catalog/js/validate-product": {}
            }
        }
        </script>
    <?php endif;?>
<?php endif;?>
