<?php
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;

    //slider config
    $sliderArrows           = true;
    $sliderItemClass        = 'slider__item';
    $sliderClass            = 'slider--products';
    $sliderInfinite         = 'no';
    $sliderSlidesToShow     = '2';
    $sliderSlidesToScroll   = '1';
    $sliderResponsiveConfig = '[
        {
            "breakpoint": 767,
            "settings": {
                "slidesToShow": 3,
                "slidesToScroll": 1,
                "dots": false
            }
        },
        {
            "breakpoint": 1023,
            "settings": {
                "slidesToShow": 4,
                "slidesToScroll": 1,
                "dots": false
            }
        }
    ]';
    ?>

    <?php if ($block->getTitle()): ?>
        <div class="section__heading">
            <h2
                class="
                    heading--first-level
                    margin-0
                "
                id="widget-product-grid-title"
            >
                <?= $block->escapeHtml(__($block->getTitle())) ?>
            </h2>
        </div>
    <?php endif ?>

    <div class="section__content section__content--products">
        <?= '<!-- ' . $image . '-->' ?>
        <?php
        $sliderBlockBefore = $this->getLayout()
            ->createBlock("Magento\Framework\View\Element\Template")
            ->setTemplate("Magento_Theme::html/slider.phtml");

        $sliderBlockBefore->setData([
            'slider_html'       => 'before-slides',
            'arrows'            => $sliderArrows,
            'slider_class'      => $sliderClass,
            'infinite'          => $sliderInfinite,
            'slides_to_show'    => $sliderSlidesToShow,
            'slides_to_scroll'  => $sliderSlidesToScroll,
            'responsive_config' => $sliderResponsiveConfig
        ]);
        ?>

        <?= $sliderBlockBefore->toHtml(); ?>

        <?php foreach ($items as $key => $_item) : ?>
            <div
                class="
                    <?= $block->escapeHtmlAttr($sliderItemClass) ?>
                    <?= $key + 1 === 1 ? 'active' : '' ?>
                "
            >
                <div
                    class="
                        product-grid-item
                        product-grid-item--slider-item
                        product-item-info
                    "
                    tabindex="0"
                >
                    <a
                        href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                        class="product-grid-item__link"
                        tabindex="-1"
                    >
                        <?php if ($_item->getBadge()): ?>
                            <?php $productBadges = $_item->getAttributeText('badge'); ?>
                            <div
                                class="
                                    badges
                                    product-grid-item__badges
                                "
                            >
                                <?php if (is_array($productBadges)): ?>
                                    <?php foreach ($productBadges as $productBadge): ?>
                                        <div
                                            class="
                                                badge
                                                badge--<?= $block->escapeHtmlAttr(mb_strtolower($productBadge, 'UTF-8')) ?>
                                            "
                                        >
                                            <?= $block->escapeHtml($productBadge) ?>
                                        </div>
                                    <?php endforeach ?>
                                <?php else: ?>
                                    <div
                                        class="
                                            badge
                                            badge--<?= $block->escapeHtmlAttr(mb_strtolower($productBadges, 'UTF-8')) ?>
                                        "
                                    >
                                        <?= $block->escapeHtml($productBadges) ?>
                                    </div>
                                <?php endif ?>
                            </div>
                        <?php endif ?>
                        <div class="product-grid-item__image-wrapper">
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </div>
                    </a>
                    <section class="product-grid-item__details">
                        <div class="product-grid-item__rating">
                            <?php if ($templateType) : ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>
                        </div>
                        <h3 class="product-grid-item__name">
                            <a
                                href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                class="product-grid-item__name-link"
                                title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                            >
                                <?php
                                    $productName = $block->escapeHtml($_item->getName());

                                    if (strlen($productName) > 50) {
                                        $productName = substr($productName, 0, 50) . '...';
                                    }
                                ?>
                                <?= $productName ?>
                            </a>
                        </h3>
                        <div class="product-grid-item__details-bottom">
                            <div class="product-grid-item__price">
                                <?= $block->getProductPriceHtml($_item, $type) ?>
                            </div>
                            <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                <div class="product-grid-item__actions">
                                    <?php if ($showWishlist || $showCompare) : ?>
                                        <div
                                            class="product-grid-item__secondary-action"
                                            data-role="add-to-links"
                                        >
                                            <?php //phpcs:disable ?>
                                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                            <?php //phpcs:enable ?>
                                                <button
                                                    class="
                                                        button
                                                        button--icon
                                                        add-to-wishlist
                                                    "
                                                    type="submit"
                                                    aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                    data-post='<?= $block->getAddToWishlistParams($_item) ?>'
                                                    data-action="add-to-wishlist"
                                                >
                                                    <svg
                                                        class="
                                                            icon
                                                            button__icon
                                                        "
                                                        role="presentation"
                                                        focusable="false"
                                                    >
                                                        <title><?= __('Wishlist heart') ?></title>
                                                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#heart')) ?>"></use>
                                                    </svg>
                                                </button>
                                            <?php endif; ?>

                                            <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                <?php //phpcs:disable ?>
                                                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                <?php //phpcs:enable ?>
                                                <button
                                                    class="
                                                        button
                                                        button--icon
                                                    "
                                                    type="submit"
                                                    aria-label="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                    data-post='<?= $compareHelper->getPostDataParams($_item) ?>'
                                                    data-testid="add-to-compare-button"
                                                >
                                                    <svg
                                                        class="icon button__icon"
                                                        role="presentation"
                                                        focusable="false"
                                                    >
                                                        <title><?= __('Add to Compare') ?></title>
                                                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#compare')) ?>"></use>
                                                    </svg>
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showCart) : ?>
                                        <div class="product-grid-item__primary-action">
                                            <?php if ($_item->isSaleable()) : ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <form
                                                    data-role="tocart-form"
                                                    data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                    action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                    method="post"
                                                >
                                                    <input
                                                        type="hidden"
                                                        name="product"
                                                        value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>"
                                                    />
                                                    <input
                                                        type="hidden"
                                                        name="<?= Action::PARAM_NAME_URL_ENCODED ?>"
                                                        value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>"
                                                    />
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button
                                                        class="
                                                            button
                                                            button--add-to
                                                        "
                                                        type="submit"
                                                        aria-label="<?= $block->escapeHtmlAttr(__('Add to cart')) ?>"
                                                    >
                                                        <svg
                                                            class="icon button__icon"
                                                            role="presentation"
                                                            focusable="false"
                                                        >
                                                            <title><?= __('Add to cart') ?></title>
                                                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#shopping-cart')) ?>"></use>
                                                        </svg>
                                                    </button>
                                                </form>
                                            <?php else : ?>
                                                <?php if ($_item->getIsSalable()) : ?>
                                                    <div class="stock available">
                                                        <?= $block->escapeHtml(__('In stock')) ?>
                                                    </div>
                                                <?php else : ?>
                                                    <div class="stock unavailable">
                                                        <?= $block->escapeHtml(__('Out of stock')) ?>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </section>
                </div>
            </div>
        <?php endforeach ?>

        <?php
        $sliderBlockAfter = $this->getLayout()
            ->createBlock("Magento\Framework\View\Element\Template")
            ->setTemplate("Magento_Theme::html/slider.phtml");

        $sliderBlockAfter->setData([
            'slider_html'   => 'after-slides'
        ]);
        ?>
        <?= $sliderBlockAfter->toHtml(); ?>

        <?= $block->getPagerHtml() ?>
    </div>
<?php endif;?>
