<?php
/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="list__item"
    data-label="<?= $escaper->escapeHtmlAttr(__('or')); ?>"
>
    <a <?= $block->getLinkAttributes(); ?><?= $dataPostParam; ?>>
        <?= $escaper->escapeHtml($block->getLabel()); ?>
    </a>
</li>
