<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="list__item"
    data-label="<?= /* @escapeNotVerified */ $block->escapeHtml(__('or')); ?>"
>
    <a <?= /* @escapeNotVerified */ $block->getLinkAttributes(); ?><?= /* @escapeNotVerified */ $dataPostParam; ?>>
        <?= /* @escapeNotVerified */ $block->escapeHtml($block->getLabel()); ?>
    </a>
</li>
