<?php
// phpcs:disable Squiz.ControlStructures.SwitchDeclaration
// phpcs:disable PSR2.ControlStructures.SwitchDeclaration

/**
 * Catalog Event product page
 *
 * @var $block \Magento\CatalogEvent\Block\Catalog\Product\Event
 */
?>
<?php $_event = $block->getEvent(); ?>
<?php if ($block->canDisplay()) : ?>
    <section
        class="
            catalog-event
            section
            block
            block-category-event
            <?= $block->escapeHtmlAttr($_event->getStatus()) ?>
        "
    >
        <h2
            class="
                heading
                heading--second-level
                text-center
                margin-bottom-0
                block-title
            "
        >
            <?= $block->escapeHtml($block->getStatusText($_event)) ?>
        </h2>
        <div class="block-content">
            <?php switch ($_event->getStatus()) :
                case \Magento\CatalogEvent\Model\Event::STATUS_UPCOMING: ?>
                <div
                    class="catalog-event__ticker dates"
                >
                    <div class="catalog-event__ticker-item start">
                        <p class="catalog-event__ticker-value date">
                            <?= $block->escapeHtml($block->getEventDate('start', $_event)) ?>
                        </p>
                        <span class="catalog-event__ticker-label time">
                            <?= $block->escapeHtml($block->getEventTime('start', $_event, 'hh a zzz')) ?>
                        </span>
                    </div>
                    <p class="catalog-event__ticker-value margin-hz-m">
                        -
                    </p>
                    <div class="catalog-event__ticker-item end">
                        <p class="catalog-event__ticker-value date">
                            <?= $block->escapeHtml($block->getEventDate('end', $_event)) ?>
                        </p>
                        <span class="catalog-event__ticker-label time">
                            <?= $block->escapeHtml($block->getEventTime('end', $_event, 'hh a zzz')) ?>
                        </span>
                    </div>
                </div>
            <?php break;
                case \Magento\CatalogEvent\Model\Event::STATUS_OPEN: ?>
                <ul
                    class="catalog-event__ticker list ticker"
                    id="event-ticker-<?= $block->escapeHtmlAttr($_event->getId()) ?>"
                    data-mage-init='
                        {
                            "ticker": {
                                "eventEndTimeUTC": <?= $block->escapeHtmlAttr($block->getEndTimeUTC($_event)) ?>
                            }
                        }
                    '
                >
                    <li
                        class="
                            catalog-event__ticker-item
                            list__item
                            days
                        "
                    >
                        <span
                            data-container="days"
                            class="catalog-event__ticker-value value"
                        >
                            &nbsp;
                        </span>
                        <span class="catalog-event__ticker-label label">
                            <?= $block->escapeHtml(__('Dayclears')) ?>
                        </span>
                    </li>
                    <li
                        class="
                            catalog-event__ticker-item
                            list__item
                            hour
                        "
                    >
                        <span
                            data-container="hour"
                            class="catalog-event__ticker-value value"
                        >
                            &nbsp;
                        </span>
                        <span class="catalog-event__ticker-label label">
                            <?= $block->escapeHtml(__('Hrs')) ?>
                        </span>
                    </li>
                    <li
                        class="
                            catalog-event__ticker-item
                            list__item
                            minute
                        "
                    >
                        <span
                            data-container="minute"
                            class="catalog-event__ticker-value value"
                        >
                            &nbsp;
                        </span>
                        <span class="catalog-event__ticker-label label">
                            <?= $block->escapeHtml(__('Mins')) ?>
                        </span>
                    </li>
                    <li
                        class="
                            catalog-event__ticker-item
                            list__item
                            second
                        "
                    >
                        <span
                            data-container="second"
                            class="catalog-event__ticker-value value"
                        >
                            &nbsp;
                        </span>
                        <span class="catalog-event__ticker-label label">
                            <?= $block->escapeHtml(__('Sec')) ?>
                        </span>
                    </li>
                </ul>
            <?php break;
                case \Magento\CatalogEvent\Model\Event::STATUS_CLOSED: ?>
                <div class="catalog-event__ticker dates">
                    <div class="catalog-event__ticker-item start">
                        <span class="catalog-event__ticker-value date">
                            <?= $block->escapeHtml($block->getEventDate('start', $_event)) ?>
                        </span>
                        <span class="catalog-event__ticker-label time">
                            <?= $block->escapeHtml($block->getEventTime('start', $_event, 'hh a zzz')) ?>
                        </span>
                    </div>
                    <div class="catalog-event__ticker-item end">
                        <span class="catalog-event__ticker-value date">
                            <?= $block->escapeHtml($block->getEventDate('end', $_event)) ?>
                        </span>
                        <span class="catalog-event__ticker-label time">
                            <?= $block->escapeHtml($block->getEventTime('end', $_event, 'hh a zzz')) ?>
                        </span>
                    </div>
                </div>
            <?php break; ?>
            <?php endswitch; ?>
        </div>
    </section>
<?php endif; ?>
