<h5 class="heading heading--fifth-level dashboard-form__title">
    <?php /* @escapeNotVerified */ echo __('Shipping Address'); ?>
</h5>

<?php if ($block->customerHasAddresses()) : ?>
    <div class="input dashboard-form__divider address">
        <label for="address_type_or_id" class="label">
            <?php /* @escapeNotVerified */ echo __('Select a shipping address from your address book or enter a new address.') ?>
        </label>
        
        <?php 
            /**
             * Get all addresses from customer and list in select
             *
             */
        ?>
        <?php foreach ($this->getCustomer()->getAddresses() as $address): ?>
            <?php $options[] = ['value' => $address->getId(), 'label' => $address->format('oneline')]; ?>
        <?php endforeach; ?>

        <div class="select dashboard-form__select" data-shipping-address="<?php /* @escapeNotVerified */ echo $block->getEntity()->getShippingAddress() ? 'true' : 'false'; ?>">
            <select data-validate="{required:true}" 
                    name="address_type_or_id" 
                    id="address_type_or_id"
                    class="select__field validate-select"
                    data-mage-init='{"select": {}}'
            >
                <option value="none" selected>
                    <?php /* @escapeNotVerified */ echo __('None'); ?>
                </option>

                <?php foreach ($options as $num => $option): ?>
                    <option value="<?php echo $num ?>">
                        <?php /* @escapeNotVerified */ echo $option['label'] ?>
                    </option>
                <?php endforeach; ?>

                <option value="new">
                    <?php /* @escapeNotVerified */ echo __('New Address'); ?>
                </option>
            </select>
        </div>
    </div>
<?php endif ?>

<div class="dashboard-form__divider" id="shipping-new-address-form"<?php if ($block->customerHasAddresses()): ?> style="display: none;"<?php endif ?>>
    <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getAddress())->setFieldNameFormat('address[%s]')->toHtml(); ?>

    <div class="input dashboard-form__divider company">
        <label for="address:company" class="label">
            <?php /* @escapeNotVerified */ echo __('Company'); ?>
        </label>
        
        <input type="text" 
               id="address:company" 
               name="address[company]" 
               value="<?php echo $block->escapeHtml($block->getAddress()->getCompany()); ?>" 
               title="<?php /* @escapeNotVerified */ echo __('Company'); ?>" 
               class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company'); ?>"
        />
    </div>

    <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

    <div class="input dashboard-form__divider address street required">
        <label for="address:street1" class="label">
            <?php /* @escapeNotVerified */ echo __('Address'); ?>
        </label>
        
        <input type="text" 
               title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" 
               name="address[street][]" 
               id="address:street1" 
               value="<?php echo $block->escapeHtml($block->getAddress()->getStreetLine(1)) ?>" 
               class="input__field <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>" 
        />
    </div>

        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>

        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <div class="input dashboard-form__divider additional no-label">
                <label for="address:street<?php /* @escapeNotVerified */ echo $_i ?>" class="label">
                    <?php /* @escapeNotVerified */ echo __('Address %1', $_i); ?>
                </label>
                
                <input type="text"
                       title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" 
                       name="address[street][]" 
                       id="address:street<?php /* @escapeNotVerified */ echo $_i ?>" 
                       value="<?php echo $block->escapeHtml($block->getAddress()->getStreetLine($_i)) ?>" 
                       class="input__field <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>"
                />
            </div>
        <?php endfor; ?>

    <div class="input dashboard-form__divider address city required" 
         data-mage-init='
            {
                "countryList": { 
                    "countrySelect"  : "address:country_id", 
                    "regionSelect"   : "address:region_id",
                    "regionText"     : "address:region",
                    "regionContainer": "region_container",
                    "placeholder"    : "<?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?>"
                }
            }
          '>
        <label for="address:city" class="label">
            <?php /* @escapeNotVerified */ echo __('City') ?>
        </label>
        
        <input type="text" 
               title="<?php /* @escapeNotVerified */ echo __('City') ?>" 
               name="address[city]" 
               value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>" 
               class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" 
               id="address:city"
        />
    </div>

    <div id="region_container" class="select dashboard-form__select address region required">
        <label for="address:region_id" class="label">
            <?php /* @escapeNotVerified */ echo __('State/Province') ?>
        </label>

        <select id="address:region_id" 
                name="address[region_id]" 
                title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" 
                class="select__field validate-select"
                data-mage-init='{"select": {}}'
        >
            <option value="" disabled>
                <?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?>
            </option>
        </select>

        <input type="text" 
               id="address:region" 
               name="address[region]" 
               value="<?php echo $block->escapeHtml($block->getAddress()->getRegion()) ?>" 
               title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" 
               class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" 
        />
    </div>

    <div class="input dashboard-form__divider address postcode required">
        <label for="address:postcode" class="label">
            <?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>
        </label>

        <input type="text" 
               title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" 
               name="address[postcode]" 
               id="address:postcode" 
               value="<?php echo $block->escapeHtml($block->getAddress()->getPostcode()) ?>" 
               class="input__field validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>" 
               data-validate="{'required':true, 'validate-zip-international':true}"
        />
    </div>

    <div class="select dashboard-form__select required">
        <label for="address:country_id" class="label">
            <?php /* @escapeNotVerified */ echo __('Country') ?>
        </label>

        <?php $countryList = $block->getCountryCollection()->toOptionArray() ?>

        <select data-validate="{required:true}" 
                name="address[country_id]" 
                id="address:country_id"
                class="select__field validate-select"
                data-mage-init='{"select": {}}'
        >
            <option value="" disabled>
                <?php /* @escapeNotVerified */ echo __('Please select a country.') ?>
            </option>

            <?php for ($i = 1, $n = count($countryList); $i < $n; $i++): ?>
                <?php if ($block->getCountryId() === $countryList[$i]['value']): ?>
                    <option value="<?php /* @escapeNotVerified */ echo $countryList[$i]['value'] ?>" selected>
                        <?= $countryList[$i]['label']; ?>
                    </option>
                <?php else: ?>
                    <option value="<?php /* @escapeNotVerified */ echo $countryList[$i]['value'] ?>">
                        <?= $countryList[$i]['label']; ?>
                    </option>
                <?php endif ?>
            <?php endfor ?>
        </select>
    </div>

    <div class="input dashboard-form__divider address telephone required">
        <label for="address:telephone" class="label">
            <?php /* @escapeNotVerified */ echo __('Phone Number') ?>
        </label>
        
        <input type="text" 
               name="address[telephone]" 
               value="<?php echo $block->escapeHtml($block->getAddress()->getTelephone()) ?>" 
               title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" 
               class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>" 
               id="address:telephone"
        />
    </div>

    <div class="input dashboard-form__divider address fax">
        <label for="address:fax" class="label">
            <?php /* @escapeNotVerified */ echo __('Fax') ?>
        </label>
        
        <input type="text" 
               name="address[fax]" 
               value="<?php echo $block->escapeHtml($block->getAddress()->getFax()) ?>" 
               title="<?php /* @escapeNotVerified */ echo __('Fax') ?>" 
               class="input__field <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('fax') ?>" 
               id="address:fax"
        >
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#address\\:country_id": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#address\\:region_id",
                "regionInputId": "#address\\:region",
                "postcodeId": "#address\\:postcode",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson(); ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getAddress()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>   
            }
        }
    }
</script>
