<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>
<form
    class="form"
    action="<?= $block->escapeUrl($block->getFormAction()); ?>"
    id="contact-form"
    method="post"
    data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
    data-mage-init='{"validation":{}}'
>
    <div class="input required">
        <label
            for="name"
            class="input__label"
        >
            <?= $block->escapeHtml(__('Name')) ?>
        </label>

        <input
            type="text"
            name="name"
            id="name"
            class="input__field"
            title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
            value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>"
            data-validate="{required: true}"
        />
    </div>

    <div class="input required">
        <label
            for="email"
            class="input__label"
        >
            <?= $block->escapeHtml(__('Email')) ?>
        </label>

        <input
            type="email"
            name="email"
            id="email"
            class="input__field"
            title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
            value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
            data-validate="{
                required: true,
                'validate-email': true
            }"
        />
    </div>

    <div class="input">
        <label
            for="telephone"
            class="input__label"
        >
            <?= $block->escapeHtml(__('Phone Number')) ?>
        </label>

        <input
            type="tel"
            name="telephone"
            id="telephone"
            class="input__field"
            title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
            value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
        />
    </div>

    <div class="input required">
        <label
            for="comment"
            class="input__label"
        >
            <?= $block->escapeHtml(__('What’s on your mind?')) ?>
        </label>

        <textarea
            class="input__field input__field--textarea"
            name="comment"
            id="comment"
            title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
            cols="5"
            rows="3"
            data-validate="{required: true}"
        ><?= $block->escapeHtml($viewModel->getUserComment()) ?></textarea>
    </div>

    <?= $block->getChildHtml('form.additional.info'); ?>

    <button
        class="button primary"
        title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"
        type="submit"
    >
        <?= $block->escapeHtml(__('Submit')) ?>
    </button>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>
