<?php
// @codingStandardsIgnoreFile

?>
<form class="form"
      action="<?= $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'
>
    <div class="input required">
        <label for="name" class="input__label">
            <?= __('Name') ?>
        </label>

        <input type="text"
               name="name"
               id="name"
               class="input__field"
               title="<?= __('Name') ?>"
               value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>"
               data-validate="{required:true}"
        />
    </div>

    <div class="input required">
        <label for="email" class="input__label">
            <?= __('Email') ?>
        </label>

        <input type="email"
               name="email"
               id="email"
               class="input__field"
               title="<?= __('Email') ?>"
               value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>"
               data-validate="{required:true, 'validate-email':true}"
        />
    </div>

    <div class="input">
        <label for="telephone" class="input__label">
            <?= __('Phone Number') ?>
        </label>

        <input type="text"
               name="telephone"
               id="telephone"
               class="input__field"
               title="<?= __('Phone Number') ?>"
               value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>"
        />
    </div>

    <div class="input required">
        <label for="comment" class="input__label">
            <?= __('What’s on your mind?') ?>
        </label>

        <textarea class="input__field input__field--textarea"
                  name="comment"
                  id="comment"
                  title="<?= __('What’s on your mind?') ?>"
                  cols="5"
                  rows="3"
                  data-validate="{required:true}"
        ><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
    </div>

    <?= $block->getChildHtml('form.additional.info'); ?>

    <button class="button primary"
            title="<?= __('Submit') ?>"
            type="submit"
    >
        <?= __('Submit') ?>
    </button>
</form>
