<button
    type="button"
    title="<?= $block->escapeHtmlAttr(__('Delete Wish List')) ?>"
    data-wishlist-delete='{
        "wishlistId":"<?= $block->escapeHtmlAttr($block->getWishlistInstance()->getId()) ?>",
        "redirectUrl":"<?= $block->escapeUrl($block->getRedirectUrl()) ?>",
        "deleteUrl":"<?= $block->escapeUrl($block->getDeleteUrl()) ?>"
    }'
    class="
        button
        button--secondary
        actions-group__button
        margin-bottom-m
    "
>
    <?= $block->escapeHtml(__('Delete Wish List')) ?>
</button>
