<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<button type="button" title="<?= $block->escapeHtmlAttr(__('Delete Wish List')) ?>" data-wishlist-delete='{"wishlistId":"<?= $block->escapeHtmlAttr($block->getWishlistInstance()->getId()) ?>", "redirectUrl":"<?= $block->escapeUrl($block->getRedirectUrl()) ?>", "deleteUrl":"<?= $block->escapeUrl($block->getDeleteUrl()) ?>"}' class="action remove"><span><?= $block->escapeHtml(__('Delete Wish List')) ?></span></button>
