<?php
$customClass = $block->getData('custom-class');
?>
<?php if ($contactBar = $this->getChildHtml('contact-bar-block')): ?>
    <div
        class="contact-bar"
        aria-label="<?= __('Contact information') ?>"
    >
        <div
            class="
                <?= $customClass ? $block->escapeHtmlAttr($customClass) : 'container contact-bar__container' ?>
            "
        >
            <?= $contactBar ?>
        </div>
    </aside>
<?php endif; ?>
