<div class="header__featured-info">
    <a href="#" class="featured-info">
        <div class="featured-info__icon">
            <svg title="curved-arrows" class="featured-info__icon-svg">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#curved-arrows'); ?>"></use>
            </svg>
        </div>
        <div class="featured-info__data">
            <div class="featured-info__data-title">
                30 days for return
            </div>
            <div class="featured-info__data-subtitle">
                <?= __('see details') ?>
            </div>
        </div>
    </a>
    <a href="#" class="featured-info">
        <div class="featured-info__icon">
            <svg title="delivery-truck" class="featured-info__icon-svg featured-info__icon-svg--delivery-truck">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#delivery-truck'); ?>"></use>
            </svg>
        </div>
        <div class="featured-info__data">
            <div class="featured-info__data-title">
                <?= __('Shipping in 24h') ?>
            </div>
            <div class="featured-info__data-subtitle">
                <?= __('see details') ?>
            </div>
        </div>
    </a>
</div>
