<header class="header">
    <div class="marketing-bar ">
        Subscribe and get 10$ for Shopping!
        <button class="button button--icon marketing-bar__close" type="button">
            <svg title="close" class="marketing-bar__close-icon">
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#close'); ?>"></use>
            </svg>
        </button>
    </div>
    <div class="top-bar">
        <div class="container top-bar__wrapper">
            <div class="top-bar__contact-info">
                + 48 68 433 00 00
                <a class="top-bar__contact-info-link" href="#">Contact</a>
            </div>
            <div class="top-bar__links">
                <a class="top-bar__links-item" href="#">
                    <svg title="heart" class="top-bar__links-icon">
                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#heart'); ?>"></use>
                    </svg>
                    Wish List
                </a>
                <a class="top-bar__links-item" href="#">
                    <svg title="signin" class="top-bar__links-icon">
                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#signin'); ?>"></use>
                    </svg>
                    Sign In
                </a>
                <a class="top-bar__links-item" href="#">
                    <svg title="account-mini" class="top-bar__links-icon">
                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#account'); ?>"></use>
                    </svg>
                    Create account
                </a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="header__wrapper">
            <a class="logo header__logo" href="#">
                <img class="logo__image lazyload" data-src="<?= $block->getViewFileUrl('images/icons/logo.svg') ?>">
            </a>
            <div class="header__icons">
                <a class="header__icons-item" href="#">
                    <svg title="phone" class="header__icon">
                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#phone'); ?>"></use>
                    </svg>
                </a>
                <a class="header__icons-item" href="#">
                    <svg title="account" class="header__icon">
                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#account'); ?>"></use>
                    </svg>
                </a>
            </div>
            <div class="header__minicart">
                <button class="minicart-trigger button popup__button" type="button">
                    <svg title="shopping-cart" class="minicart-trigger__icon">
                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#shopping-cart'); ?>"></use>
                    </svg>
                    <span class="minicart-trigger__counter">
                        82
                    </span>
                </button>
            </div>
            <div class="header__menu-trigger">
                <button class="side-menu-trigger" type="button">
                    <div class="side-menu-trigger__handler">
                        <span class="side-menu-trigger__line"></span>
                        <span class="side-menu-trigger__line"></span>
                        <span class="side-menu-trigger__line"></span>
                        <span class="side-menu-trigger__line"></span>
                        <span class="side-menu-trigger__text">
                            menu
                        </span>
                    </div>
                </button>
            </div>
            <div class="header__featured-info">
                <a href="#" class="featured-info">
                    <div class="featured-info__icon">
                        <svg title="curved-arrows" class="featured-info__icon-svg">
                            <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#curved-arrows'); ?>"></use>
                        </svg>
                    </div>
                    <div class="featured-info__data">
                        <div class="featured-info__data-title">
                            30 days for return
                        </div>
                        <div class="featured-info__data-subtitle">
                            see details
                        </div>
                    </div>
                </a>
                <a href="#" class="featured-info">
                    <div class="featured-info__icon">
                        <svg title="delivery-truck" class="featured-info__icon-svg featured-info__icon-svg--delivery-truck">
                            <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#delivery-truck'); ?>"></use>
                        </svg>
                    </div>
                    <div class="featured-info__data">
                        <div class="featured-info__data-title">
                            Shipping in 24h
                        </div>
                        <div class="featured-info__data-subtitle">
                            see details
                        </div>
                    </div>
                </a>
            </div>
            <div class="header__search-wrapper">
                <form class="search-form">
                    <div class="input search-form__input-wrapper">
                        <label class="label search-form__label" for="input"></label>
                        <input class="input__field search-form__input" id="input" type="text" placeholder="Search entire store here...">
                    </div>
                    <button class="button button--icon search-form__button" type="button">
                        <svg title="search" class="button__icon">
                            <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#search'); ?>"></use>
                        </svg>
                    </button>
                </form>
            </div>
        </div>
    </div>
</header>
