<header class="header">
    <div class="container">
        <div class="header__wrapper">
            <?= $block->getChildHtml('menu-main-mobile') ?>
            <div class="header__buttons">
                <?= $this->getChildHtml('wish-list-link') ?>
                <?= $this->getChildHtml('contact-link') ?>
                <?= $this->getChildHtml('account-link') ?>
                <?= $this->getChildHtml('minicart') ?>
            </div>

            <?= $this->getChildHtml('logo') ?>

            <div class="header__search-wrapper">
                <?= $this->getChildHtml('search') ?>
            </div>
        </div>
    </div>
</header>
<?= $block->getChildHtml('menu-main-desktop') ?>
