<div class="marketing-bar" data-testid="marketing-bar-message">
    <div class="container marketing-bar__container">
        <div class="marketing-bar__text">
            <!-- TODO: Move to CMS block -->
            <?= $block->escapeHtml(__('Subscribe and get 10$ for Shopping!')) ?>
        </div>

        <button
            class="
                button
                button--icon
                marketing-bar__close
            "
            type="button"
            aria-label="<?= $block->escapeHtmlAttr(__('Close marketing bar')) ?>"
        >
            <svg
                class="marketing-bar__close-icon"
                role="presentation"
                focusable="false"
            >
                <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#close')) ?>"></use>
            </svg>
        </button>
    </div>
</div>
