<div class="marketing-bar">
    Subscribe and get 10$ for Shopping!
    <button class="button button--icon marketing-bar__close"
            type="button"
            aria-label="<?= /* @escapeNotVerified */ __('Close marketing bar') ?>"
    >
        <svg title="close" class="marketing-bar__close-icon">
            <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#close'); ?>"></use>
        </svg>
    </button>
</div>
