<?php if ($marketingBar = $this->getChildHtml('marketing-bar-block')): ?>
    <aside
        class="marketing-bar marketing-bar--closed"
        aria-label="<?= __('Special Offer') ?>"
        data-testid="marketing-bar-message"
        data-type="marketing-bar"
        data-mage-init='{ "marketingBar": {} }'
    >
        <div class="container marketing-bar__container">
            <div class="marketing-bar__text">
                <?= $marketingBar ?>
            </div>
            <button
                class="
                    button
                    button--icon
                    button--rotate-icon
                    marketing-bar__close
                "
                type="button"
                aria-label="<?= $block->escapeHtmlAttr(__('Close marketing bar')) ?>"
            >
                <svg
                    class="
                        icon
                        button__icon
                        marketing-bar__close-icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <title><?= __('Close') ?></title>
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#close')) ?>"></use>
                </svg>
            </button>
        </div>
    </aside>
<?php endif; ?>
