<?php
/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div class="header__minicart" data-block="minicart">
    <a class="header-button popup-trigger showcart"
       href="<?= /* @escapeNotVerified */ $block->getShoppingCartUrl() ?>"
       data-bind="scope: 'minicart_content'"
    >
        <svg title="<?= /* @escapeNotVerified */ __('Shopping cart') ?>" class="icon header-button__icon">
            <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#shopping-cart'); ?>"></use>
        </svg>
        <span class="header-button__text">
            <?= __('Cart') ?>
        </span>
        <!-- ko if: getCartParam('summary_count') -->
            <span class="header-button__counter">
                <span class="header-button__counter-dot"></span>
            </span>
        <!-- /ko -->
    </a>

    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart minicart empty"
             data-role="dropdownDialog"
             data-mage-init='
                 {
                     "dropdownDialog":{
                         "appendTo":"[data-block=minicart]",
                         "triggerTarget":".showcart",
                         "timeout": "2000",
                         "closeOnMouseLeave": false,
                         "closeOnEscape": true,
                         "triggerClass":"active",
                         "parentClass":"active",
                         "buttons":[]
                     }
                 }
             '
        >
            <div id="minicart-content-wrapper"
                 class="minicart__wrapper"
                 data-bind="scope: 'minicart_content'"
            >
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>

    <script>
        window.checkout = <?= /* @escapeNotVerified */ \Zend_Json::encode($block->getConfig()) ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
        }
    }
    </script>
</div>
