<?php
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
/** @var $block \Magento\Rma\Block\Returns\History */
?>
<?php $_returns = $block->getReturns(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_returns->getSize()): ?>
    <div class="dashboard-table__content">
        <table
            class="table"
            id="my-returns-table"
            role="table"
        >
            <caption class="table__caption">
                <?= $block->escapeHtml(__('My Returns')) ?>
            </caption>
            <thead>
                <tr role="row">
                    <th
                        role="columnheader"
                        scope="col"
                        class="col id"
                    >
                        <?= $block->escapeHtml(__('Return #')) ?>
                    </th>
                    <th
                        role="columnheader"
                        scope="col"
                        class="col date"
                    >
                        <?= $block->escapeHtml(__('Date')) ?>
                    </th>
                    <th
                        role="columnheader"
                        scope="col"
                        class="col shipping"
                    >
                        <?= $block->escapeHtml(__('Ship From')) ?>
                    </th>
                    <th
                        role="columnheader"
                        scope="col"
                        class="col status"
                    >
                        <?= $block->escapeHtml(__('Return Status')) ?>
                    </th>
                    <th
                        role="columnheader"
                        scope="col"
                        class="col actions"
                    >
                        <?= $block->escapeHtml(__('Action')) ?>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php $_odd = ''; ?>
                <?php foreach ($_returns as $_return): ?>
                    <tr role="row">
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Return #:')) ?>"
                            role="gridcell"
                            class="col id"
                        >
                            <?= $block->escapeHtml($_return->getIncrementId()) ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Date:')) ?>"
                            role="gridcell"
                            class="col date"
                        >
                            <?= $block->escapeHtml($this->helper(Magento\Rma\Helper\Data::class)->getFormatedDate($_return->getDateRequested())) ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Ship From:')) ?>"
                            role="gridcell"
                            class="col shipping"
                        >
                            <?= $block->escapeHtml($_return->getCustomerName()) ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Return Status:')) ?>"
                            role="gridcell"
                            class="col status"
                        >
                            <?= $block->escapeHtml($_return->getStatusLabel()) ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Action:')) ?>"
                            role="gridcell"
                            class="col actions"
                        >
                            <a
                                href="<?= $block->escapeUrl($block->getViewUrl($_return)) ?>"
                                class="link dashboard-table__link"
                            >
                                <?= $block->escapeHtml(__('View Return')) ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="margin-top-sm">
            <?= $block->getPagerHtml() ?>
        </div>
    <?php endif ?>
<?php else: ?>
    <div
        class="
            message
            info
            empty
        "
    >
        <?= $block->escapeHtml(__('You have placed no returns.')) ?>
    </div>
<?php endif ?>
