<?php
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
/** @var $block \Magento\Rma\Block\Returns\Returns */
?>
<?php $_returns = $block->getReturns(); ?>

<?php if ($_returns->getSize()): ?>
    <div class="dashboard-table">
        <?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
        <?= $block->getChildHtml('info') ?>
        <div class="dashboard-table__header">
            <h2 class="heading dashboard-table__title">
                <?= $block->escapeHtml(__('My Returns')) ?>
            </h2>
            <?= $block->getChildHtml('order_actions') ?>
        </div>
        <div class="dashboard-table__content">
            <table
                class="table"
                id="my-returns-table"
                role="table"
            >
                <caption class="table__caption">
                    <?= $block->escapeHtml(__('My Returns')) ?>
                </caption>
                <thead>
                    <tr role="row">
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Return #')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Date')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Ship From')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Return Status')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $_odd = ''; ?>
                    <?php foreach ($_returns as $_return): ?>
                        <tr role="row">
                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Return #')) ?>"
                                role="gridcell"
                            >
                                <?= $block->escapeHtml($_return->getIncrementId()) ?>
                            </td>
                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>"
                                role="gridcell"
                            >
                                <?=
                                    $block->escapeHtml($this->helper(Magento\Rma\Helper\Data::class)
                                        ->getFormatedDate($_return->getDateRequested()))
                                ?>
                            </td>
                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Ship From')) ?>"
                                role="gridcell"
                            >
                                <?= $block->escapeHtml($_return->getCustomerName()) ?>
                            </td>
                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Return Status')) ?>"
                                role="gridcell"
                            >
                                <?= $block->escapeHtml($_return->getStatusLabel()) ?>
                            </td>
                            <td
                                data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>"
                                role="gridcell"
                            >
                                <a
                                    href="<?= $block->escapeUrl($block->getViewUrl($_return)) ?>"
                                    class="
                                        link
                                        dashboard-table__link
                                    "
                                    title="<?= $block->escapeHtmlAttr(__('View Return')) ?>"
                                >
                                    <?= $block->escapeHtml(__('View Return')) ?>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?= $block->getPagerHtml() ?>
    </div>
<?php else: ?>
    <div class="message">
        <?= $block->escapeHtml(__('You have placed no returns.')) ?>
    </div>
<?php endif ?>
