<?php
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
/** @var $block \Magento\Rma\Block\Returns\Tracking */
?>

<?php if ($block->getErrorMessage()): ?>
    <tr role="row">
        <td
            colspan="3"
            role="gridcell"
        >
            <div class="message error">
                <?= $block->escapeHtml($block->getErrorMessage()) ?>
            </div>
        </td>
    </tr>
<?php endif ?>
<?php foreach ($block->getTrackingNumbers() as $number): ?>
    <tr role="row">
        <td
            data-th="<?= $block->escapeHtmlAttr(__('Carrier')) ?>"
            class="col carrier"
            role="gridcell"
        >
            <?= $block->escapeHtml($number->getCarrierTitle()) ?>
        </td>
        <td
            data-th="<?= $block->escapeHtmlAttr(__('Number')) ?>"
            class="col id"
            role="gridcell"
        >
            <a
                href="#"
                data-mage-init='
                    {
                        "popupWindow": {
                            "windowURL":"<?= $block->escapeUrl($this->helper(Magento\Rma\Helper\Data::class)->getTrackingPopupUrlBySalesModel($number)) ?>",
                            "windowName":"trackshipment",
                            "width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1
                        }
                    }
                '
                title="<?= $block->escapeHtml($number->getTrackNumber()) ?>"
                class="link"
            >
                <?= $block->escapeHtml($number->getTrackNumber()) ?>
            </a>
        </td>
        <td
            data-th="<?= $block->escapeHtmlAttr(__('Action')) ?>"
            class="col actions"
            role="gridcell"
        >
            <?php if (!$number->getIsAdmin() && $block->isPrintShippingLabelAllowed()): ?>
                <a
                    href="#"
                    data-entity-id="<?= (int) $number->getEntityId() ?>"
                    class="action delete" title="<?= $block->escapeHtmlAttr(__('Delete')) ?>"
                >
                    <?= $block->escapeHtml(__('Delete')) ?>
                </a>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if ($block->isPrintShippingLabelAllowed()): ?>
    <script type="text/x-magento-init">
        {
            "#rma_track_info": {
                "Magento_Rma/set-options": {
                    "deleteLabelUrl": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteLabelUrl())) ?>",
                    "deleteMsg": "<?= $block->escapeJs($block->escapeHtml(__('Are you sure you want to delete this tracking information?'))) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
