<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
//phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
/** @var $block \Magento\Rma\Block\Returns\View */
?>

<?php
    $_rma = $block->getRma();
    $_order = $block->getOrder();
    $additionalData = $block->getAdditionalData();
    $rmaHelper = $block->getRmaHelper();
?>

<div class="block block-return-details">
    <div class="block-content">
        <div class="box box-returns-requested">
            <strong class="box-title"><span><?= $block->escapeHtml(__('Request Information')); ?></span></strong>
            <div class="box-content">
                <?= $block->escapeHtml(__('ID')); ?>: <?= $block->escapeHtml($_rma->getIncrementId()) ?><br>
                <?= $block->escapeHtml(__('Order ID')); ?>: <a href="<?= $block->escapeUrl($block->getOrderUrl($_rma)); ?>"><?= $block->escapeHtml($_rma->getOrderIncrementId()) ?></a><br>
                <?= $block->escapeHtml(__('Date Requested')); ?>: <?= $block->escapeHtml($rmaHelper->getFormatedDate($_rma->getDateRequested())); ?><br>
                <?= $block->escapeHtml(__('Email')); ?>: <?= $block->escapeHtml($_order->getCustomerEmail()) ?>
                <?php if ($_rma->getCustomerCustomEmail()) : ?>
                    <br>
                    <?= $block->escapeHtml(__('Contact Email Address')); ?>: <?= $block->escapeHtml($_rma->getCustomerCustomEmail()) ?>
                <?php endif ?>
            </div>
        </div>
        <div class="box box-treturns-shipping">
            <strong class="box-title"><span><?= $block->escapeHtml(__('Shipping Address')); ?></span></strong>
            <div class="box-content">
                <address>
                    <?= /* @noEscape */ $block->getAddress() ?>
                </address>
            </div>
        </div>
    </div>
</div>

<div class="returns-details-items">
    <span id="rma-please-wait" class="please-wait load indicator" style="display: none;" data-text="<?= $block->escapeHtml(__('This won\'t take long . . .')); ?>">
        <span><?= $block->escapeHtml(__('This won\'t take long . . .')); ?></span>
    </span>

    <?php $trackingNumbers = $block->getTrackingNumbers() ?>
    <?php if ($block->isPrintShippingLabelAllowed() || $trackingNumbers->count()) : ?>
        <div class="block block-returns-tracking">
            <div class="block-title">
                <strong><?= $block->escapeHtml(__('Shipping and Tracking Information')); ?></strong>
                <?php if ($trackingNumbers->count() || $block->canShowButtons()) : ?>
                    <div class="actions-track">
                        <?php if ($trackingNumbers->count()) : ?>
                            <a class="action track" href="#" data-mage-init='{"popupWindow": {
                            "windowURL":"<?= $block->escapeUrl($rmaHelper->getTrackingPopupUrlBySalesModel($block->getRma())) ?>",
                            "windowName":"trackshipment",
                            "width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1
                        }}' title="<?= $block->escapeHtml(__('Track this shipment')) ?>">
                                <span><?= $block->escapeHtml(__('Track this shipment')) ?></span>
                            </a>
                        <?php endif ?>
                        <?php if ($block->canShowButtons()) : ?>
                            <a href="<?= $block->escapeUrl($rmaHelper->getPackagePopupUrlByRmaModel($block->getRma(), 'printlabel')) ?>"
                               title="<?= $block->escapeHtml(__('Print Shipping Label')) ?>"
                               class="action track">
                                <span><?= $block->escapeHtml(__('Print Shipping Label')) ?></span>
                            </a>
                            <a class="action track" href="#" data-mage-init='{"popupWindow": {
                            "windowURL":"<?= $block->escapeUrl($rmaHelper->getPackagePopupUrlByRmaModel($block->getRma())) ?>",
                            "windowName":"package",
                            "width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1
                        }}' title="<?= $block->escapeHtml(__('Show Packages')) ?>">
                                <span><?= $block->escapeHtml(__('Show Packages')) ?></span>
                            </a>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="block-content">
                <form method="post"
                      id="rma_track_info"
                      class="form form-tracking"
                      data-mage-init='{"rmaTrackInfo":{"addLabelUrl": "<?= $block->escapeUrl($block->getAddLabelUrl()); ?>"}, "validation":{}}'>
                    <div class="table-wrapper">
                        <table class="data table" id="track-info-table">
                            <caption class="table-caption"><?= $block->escapeHtml(__('Shipping and Tracking Information')); ?></caption>
                            <thead>
                            <tr>
                                <th scope="col" class="col carrier"><?= $block->escapeHtml(__('Carrier')); ?></th>
                                <th scope="col" class="col id"><?= $block->escapeHtml(__('Number')); ?></th>
                                <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')); ?></th>
                            </tr>
                            </thead>
                            <tbody id="track-info-tbody">
                            <?= /* @noEscape */ $block->getTrackingInfo('tracking') ?>
                            </tbody>
                            <?php if ($block->isPrintShippingLabelAllowed()) : ?>
                                <tfoot>
                                <tr>
                                    <td class="col carrier">
                                        <select name="tracking_carrier_select" id="tracking_carrier_select" class="select" data-validate="{required:true}">
                                            <option value=""></option>
                                            <?php foreach ($block->getCarriers() as $key => $value) : ?>
                                                <option value="<?= $block->escapeHtml($key); ?>"><?= $block->escapeHtml($value) ?></option>
                                            <?php endforeach ?>
                                        </select>
                                    </td>
                                    <td class="col id">
                                        <input type="text" class="input-text" value="" name="tracking_number_input" id="tracking_number_input" data-validate="{required:true}">
                                    </td>
                                    <td class="col actions">
                                        <button type="button" class="action add" id="btn-add-track-number" title="<?= $block->escapeHtml(__('Add')); ?>"><span><?= $block->escapeHtml(__('Add')); ?></span></button>
                                    </td>
                                </tr>
                                </tfoot>
                            <?php endif ?>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    <?php endif ?>

    <div class="block block-returns-items">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Items Return Requested For')); ?></strong>
        </div>
        <div class="block-content">
            <div class="table-wrapper table-returns">
                <table class="data table table-returns" id="my-returns-items-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Items Return Requested For')); ?></caption>
                    <thead>
                    <tr>
                        <?php $availableAttributes = $block->getVisibleAttributes(); ?>
                        <th scope="col" class="col id"><?= $block->escapeHtml(__('Product Name')); ?></th>
                        <th scope="col" class="col sku"><?= $block->escapeHtml(__('SKU')); ?></th>
                        <?php if (isset($availableAttributes['condition'])) : ?>
                            <th scope="col" class="col condition"><?= $block->escapeHtml(__('Condition')); ?></th>
                        <?php endif; ?>
                        <?php if (isset($availableAttributes['condition'])) : ?>
                            <th scope="col" class="col resolution"><?= $block->escapeHtml(__('Resolution')); ?></th>
                        <?php endif; ?>
                        <th scope="col" class="col request qty"><?= $block->escapeHtml(__('Request Qty')) ?></th>
                        <th scope="col" class="col qty"><?= $block->escapeHtml(__('Qty')); ?></th>
                        <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $_qna = null; ?>
                    <?php foreach ($block->getItems() as $key => $item) : ?>
                        <?php foreach ($block->getRealValueAttributes($item->getId()) as $code => $attribute) {
                            if (!in_array($code, $block->getAttributeFilter()) && !empty($attribute['value']) && $block->getAttributeLabel($item->getId(), $code)
                                && false !== $block->getAttributeValue($item->getId(), $code)) {
                                $_qna .= '
                                        <tr><td class="col questions">' . $block->getAttributeLabel($item->getId(), $code) . '</td>
                                        <td class="col answers">' . $block->getAttributeValue($item->getId(), $code) . '</td></tr>
                                    ';
                            }
                        } ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col id">
                                <?= $block->escapeHtml($item->getProductName()) ?>
                                <?php if ($_options = $block->getItemOptions($item)) : ?>
                                    <dl class="item options">
                                        <?php foreach ($_options as $_option) : ?>
                                            <dt><?= $block->escapeHtml($_option['label']); ?></dt>
                                            <dd><?= $block->escapeHtml($_option['value']); ?></dd>
                                        <?php endforeach; ?>
                                    </dl>
                                <?php endif; ?>
                                <?php if ($_qna) : ?>
                                    <button class="action details" type="button" data-mage-init='{"toggleAdvanced": {"newLabel": "<?= $block->escapeHtml(__('Hide Details')); ?>", "toggleContainers": "#shf_<?= $block->escapeHtml($key); ?>"}}'>
                                        <span><?= $block->escapeHtml(__('Show Details')); ?></span>
                                    </button>
                                <?php endif; ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col sku"><?= $block->escapeHtml($item->getProductSku()) ?></span></td>
                            <?php if (false !== $block->getAttributeValue($item->getId(), 'condition')) : ?>
                                <td data-th="<?= $block->escapeHtml(__('Condition')) ?>" class="col condition"><?= $block->escapeHtml($block->getAttributeValue($item->getId(), 'condition')) ?></td>
                            <?php endif; ?>
                            <?php if (false !== $block->getAttributeValue($item->getId(), 'condition')) : ?>
                                <td data-th="<?= $block->escapeHtml(__('Resolution')) ?>" class="col resolution"><?= $block->escapeHtml($block->getAttributeValue($item->getId(), 'resolution')) ?></td>
                            <?php endif; ?>
                            <td data-th="<?= $block->escapeHtml(__('Request Qty')) ?>" class="col request qty"><?= $block->escapeHtml($rmaHelper->parseQuantity($item->getQtyRequested(), $item)) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty"><?= $block->escapeHtml($rmaHelper->getQty($item)) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($item->getStatusLabel()) ?></td>
                        </tr>
                        <?php if ($_qna) : ?>
                            <tr id="shf_<?= $block->escapeHtml($key); ?>" class="hidden returns-details">
                                <td colspan="7">
                                    <table class="data table">
                                        <caption class="table-caption"><?= $block->escapeHtml(__('Questions and Answers')); ?></caption>
                                        <thead>
                                        <tr>
                                            <th class="col questions"><?= $block->escapeHtml(__('Questions')); ?></th>
                                            <th class="col answers"><?= $block->escapeHtml(__('Answers')); ?></th>
                                        </tr>
                                        </thead>
                                        <?= /* @noEscape */ $_qna ?>
                                    </table>
                                </td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="block block-returns-comments">
        <div class="block-title"><strong><?= $block->escapeHtml(__('Comments')); ?></strong></div>
        <div class="block-content">
            <dl class="returns-comments">
                <?php $_comments = $block->getComments(); ?>
                <?php if (!empty($_comments)) : ?>
                    <?php foreach ($_comments as $_comment) : ?>
                        <?php if ($_comment->getIsVisibleOnFront()) : ?>
                            <dt class="returns-comment-date">
                                <strong class="returns-comment-autor">
                                    <?php if ($_comment->getIsAdmin()) : ?>
                                        <?= $block->escapeHtml(__('Customer Service')); ?>
                                    <?php else : ?>
                                        <?= $block->escapeHtml($block->getCustomerName()) ?>
                                    <?php endif; ?>
                                </strong>
                                <?= $block->escapeHtml($block->formatDate($_comment->getCreatedAt())); ?> <?= $block->escapeHtml($block->formatTime($_comment->getCreatedAt())); ?>
                            </dt>
                            <dd class="returns-comment-text">
                                <?= /* @noEscape */ nl2br($block->escapeHtml($_comment->getComment())) ?>
                            </dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </dl>
            <form method="post"
                  id="rma_comment"
                  action="<?= $block->escapeUrl($block->getSubmitUrl()); ?>"
                  class="form form-returns-comments"
                  data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset">
                    <div class="field comment">
                        <label class="label"><span><?= $block->escapeHtml(__('Leave Comment')); ?></span></label>
                        <div class="control">
                            <textarea id="rma_comment_text" cols="5" rows="3" name="comment" data-validate="{required:true}"></textarea>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action submit primary" id="submit.save"><span><?= $block->escapeHtml(__('Submit Comment')); ?></span></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
