<?php
/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */
?>
<button
    class="button button--icon"
    title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>"
    aria-label="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>"
    data-post='<?= /* @noEscape */ $block->getCompareHelper()->getPostDataParams($block->getProduct()) ?>'
    role="button"
    data-testid="add-to-compare-button"
>
    <svg class="button__icon">
        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#compare')) ?>"></use>
    </svg>
</button>
