<button
    class="button button--icon"
    title="<?= /* @escapeNotVerified */ __('Add to Compare') ?>"
    aria-label="<?= /* @escapeNotVerified */ __('Add to Compare') ?>"
    data-post='<?= /* @escapeNotVerified */ $block->getCompareHelper()->getPostDataParams($block->getProduct()) ?>'
    role="button"
>
    <svg class="button__icon">
        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#compare') ?>"></use>
    </svg>
</button>
