<?php
// @codingStandardsIgnoreFile
/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */
?>
<button
    class="catalog-grid-item__secondary-action"
    title="<?= $block->escapeHtml(__('Add to Compare')); ?>"
    aria-label="<?= $block->escapeHtml(__('Add to Compare')); ?>"
    data-post='<?= /* @escapeNotVerified */ $block->getCompareHelper()->getPostDataParams($block->getProduct()); ?>'
    role="button"
>
    <svg class="icon">
        <use xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#compare'); ?>"></use>
    </svg>
</button>
