<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<form
    method="post"
    class="confirmation-link"
    id="form-validate"
    data-mage-init='{"validation": {}}'
>
    <p>
        <?= $escaper->escapeHtml(__('Please enter your email below and we will send you the confirmation link.')) ?>
    </p>
    <div class="input required">
        <label for="email_address">
            <?= $escaper->escapeHtml(__('Email')) ?>
        </label>
        <input
            type="email"
            name="email"
            id="email_address"
            class="input__field"
            value="<?= $escaper->escapeHtmlAttr($block->getEmail()) ?>"
            data-validate="{required: true, 'validate-email': true}"
            data-mage-init='{"mage/trim-input":{}}'
        >
    </div>
    <button type="submit" class="button">
        <?= $escaper->escapeHtml(__('Send confirmation link')) ?>
    </button>
    <a
        href="<?= $escaper->escapeUrl($block->getLoginUrl()) ?>"
        class="confirmation-link__link"
    >
        <?= $escaper->escapeHtml(__('Back to Sign In')) ?>
    </a>
</form>
