<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<form
    method="post"
    id="form-validate"
    data-mage-init='{"validation": {}}'
>
    <fieldset
        class="fieldset"
        data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
    >
        <p class="field note">
            <?= __('Please enter your email below and we will send you the confirmation link.') ?>
        </p>
        <div class="field email required">
            <label for="email_address">
                <?= __('Email') ?>
            </label>
            <div class="input">
                <input
                    type="email"
                    name="email"
                    id="email_address"
                    class="input__field"
                    value="<?= $block->escapeHtmlAttr($block->getEmail()) ?>"
                    data-validate="{required: true, 'validate-email': true}"
                >
            </div>
        </div>
    </fieldset>
    <button type="submit" class="button">
        <?= __('Send confirmation link') ?>
    </button>
    <div>
        <a href="<?= $block->escapeUrl($block->getLoginUrl()) ?>">
            <?= $block->escapeHtml(__('Back to Sign In')) ?>
        </a>
    </div>
</form>
