<form class="dashboard-form" 
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account/editPost') ?>" 
      method="post" 
      id="form-validate" 
      enctype="multipart/form-data" 
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" 
      autocomplete="off"
>
    <?php echo $block->getBlockHtml('formkey')?>

    <h5 class="heading heading--fifth-level dashboard-form__title">
        <?php /* @escapeNotVerified */ echo __('Account Information') ?>
    </h5>

    <div class="dashboard-form__divider">
        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>

        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>

        <div class="checkbox dashboard-form__divider">
            <input type="checkbox" 
                   name="change_email" 
                   id="change-email" 
                   data-role="change-email" 
                   value="1" 
                   title="<?php /* @escapeNotVerified */ echo __('Change Email') ?>" 
                   class="checkbox__field" 
            />

            <svg class="checkbox__icon">
                <use xlink:href="<?= $block->getViewFileUrl('images/icon-sprite.svg#checked'); ?>"></use>
            </svg>

            <label class="checkbox__label" for="change-email">
                <?php /* @escapeNotVerified */ echo __('Change Email') ?>
            </label>
        </div>

        <div class="checkbox dashboard-form__divider">
            <input type="checkbox" 
                   name="change_password" 
                   id="change-password" 
                   data-role="change-password" 
                   value="1" 
                   title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>"
                   <?php if ($block->getChangePassword()): ?> 
                        checked="checked"
                   <?php endif; ?> 
                   class="checkbox__field" 
            />

            <svg class="checkbox__icon">
                <use xlink:href="<?= $block->getViewFileUrl('images/icon-sprite.svg#checked'); ?>"></use>
            </svg>

            <label class="checkbox__label" for="change-password">
                <?php /* @escapeNotVerified */ echo __('Change Password') ?>
            </label>
        </div>

        <div class="dashboard-form__divider dashboard-form__fields" data-container="change-email-password">
            <h5 class="
                    heading
                    heading--sixth-level
                    dashboard-form__title-form
                    dashboard-form__divider
                "
            >
                <span data-title="change-email-password">
                    <?php /* @escapeNotVerified */ echo __('Change Email and Password') ?>
                </span>
            </h5>

            <div class="input dashboard-form__divider email required" data-container="change-email">
                <label class="label" for="email">
                    <?php /* @escapeNotVerified */ echo __('Email') ?>
                </label>

                <input type="email" 
                       name="email" 
                       id="email" 
                       autocomplete="email"
                       data-input="change-email" 
                       value="<?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?>" 
                       title="<?php /* @escapeNotVerified */ echo __('Email') ?>" 
                       class="input__field" 
                       data-validate="{required:true, 'validate-email':true}" 
                />
            </div>

            <div class="input dashboard-form__divider password required">
                <label class="label" for="current-password">
                    <?php /* @escapeNotVerified */ echo __('Current Password') ?>
                </label>

                <input type="password" 
                       class="input__field" 
                       name="current_password" 
                       id="current-password" 
                       data-input="current-password" 
                       autocomplete="off" 
                />
            </div>

            <div class="input dashboard-form__divider dashboard-form--hidden newPassword required" 
                 data-container="new-password" 
                 data-mage-init='{
                    "passwordStrengthIndicator": {
                        "defaultClassName": "password-strength--"
                    }
                 }'
            >
                <label class="label" for="password">
                    <?php /* @escapeNotVerified */ echo __('New Password') ?>
                </label>
                
                <input type="password" 
                       class="input__field" 
                       name="password" 
                       id="password"
                       data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                       data-input="new-password"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off" 
                />
                <div data-role="password-strength-meter"
                     class="password-strength"
                >
                    <div class="password-strength__progress">
                        <?= /* @escapeNotVerified */ __('Password Strength'); ?>:
                        <span data-role="password-strength-meter-label">
                            <?= /* @escapeNotVerified */ __('No Password'); ?>
                        </span>
                    </div>
                </div>
            </div>

            <div class="input dashboard-form__divider confirmPassword required" 
                 data-container="confirm-password"
            >
                <label class="label" for="password-confirmation">
                    <?php /* @escapeNotVerified */ echo __('Confirm New Password') ?>
                </label>

                <input type="password" 
                       class="input__field" 
                       name="password_confirmation" 
                       id="password-confirmation"
                       data-input="confirm-password"
                       autocomplete="off" 
                />
            </div>

            <?php echo $block->getChildHtml('form_additional_info'); ?>
        </div>
    </div>

    <div class="action">
        <div class="action__handler">
            <button type="submit" 
                    class="button action__button" 
                    title="<?php /* @escapeNotVerified */ echo __('Save') ?>"
            >
                <?php /* @escapeNotVerified */ echo __('Save') ?>
            </button>
        </div>

        <div class="action__handler">
            <a class="action__link" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>">
                <?php /* @escapeNotVerified */ echo __('Go back') ?>
            </a>
        </div>
    </div>
</form>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
        
        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?php /* @escapeNotVerified */ echo __('Change Email') ?>",
                "titleChangePassword": "<?php /* @escapeNotVerified */ echo __('Change Password') ?>",
                "titleChangeEmailAndPassword": "<?php /* @escapeNotVerified */ echo __('Change Email and Password') ?>"
            }
        }
    }
</script>
