<?php
use Magento\Customer\Block\Widget\Name;

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<form
    class="
        dashboard-form
        form
    "
    action="<?= $escaper->escapeUrl($block->getUrl('customer/account/editPost')) ?>"
    method="post"
    id="form-validate"
    enctype="multipart/form-data"
    data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
    autocomplete="off"
>
    <?= $block->getBlockHtml('formkey') ?>

    <h3 class="dashboard-form__title">
        <?= $escaper->escapeHtml(__('Account Information')) ?>
    </h3>

    <div class="dashboard-form__divider">
        <?=
            $block->getLayout()
                ->createBlock(Name::class)
                ->setObject($block->getCustomer())
                ->toHtml()
        ?>

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>

        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>

        <div class="checkbox dashboard-form__divider">
            <input
                id="change-email"
                type="checkbox"
                name="change_email"
                data-role="change-email"
                value="1"
                title="<?= $escaper->escapeHtmlAttr(__('Change Email')) ?>"
                class="checkbox__field"
            />

            <svg
                class="checkbox__icon"
                role="presentation"
                focusable="false"
            >
                <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked')) ?>"></use>
            </svg>

            <label
                class="checkbox__label"
                for="change-email"
            >
                <?= $escaper->escapeHtml(__('Change Email')) ?>
            </label>
        </div>

        <div
            class="
                checkbox
                dashboard-form__divider
            "
        >
            <input
                id="change-password"
                class="checkbox__field"
                type="checkbox"
                name="change_password"
                data-role="change-password"
                value="1"
                title="<?= $escaper->escapeHtmlAttr(__('Change Password')) ?>"
                <?php if ($block->getChangePassword()): ?>
                    checked="checked"
                <?php endif; ?>
            />

            <svg
                class="checkbox__icon"
                role="presentation"
                focusable="false"
            >
                <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked')) ?>"></use>
            </svg>

            <label
                class="checkbox__label"
                for="change-password"
            >
                <?= $escaper->escapeHtml(__('Change Password')) ?>
            </label>

            <?= $block->getChildHtml('fieldset_edit_info_additional') ?>
        </div>

        <div
            class="
                dashboard-form__divider
                dashboard-form__fields
            "
            data-container="change-email-password"
        >
            <h4 class="dashboard-form__title-form dashboard-form__divider">
                <span data-title="change-email-password">
                    <?= $escaper->escapeHtml(__('Change Email and Password')) ?>
                </span>
            </h4>

            <div
                class="
                    input
                    email
                    required
                "
                data-container="change-email"
            >
                <label
                    class="label"
                    for="email"
                >
                    <?= $escaper->escapeHtml(__('Email')) ?>
                </label>

                <input
                    id="email"
                    class="input__field"
                    type="email"
                    name="email"
                    autocomplete="email"
                    data-input="change-email"
                    value="<?= $escaper->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"
                    title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                    class="input__field"
                    data-validate="{required: true, 'validate-email': true}"
                />
            </div>

            <div class="input password required">
                <label class="label" for="current-password">
                    <?= $escaper->escapeHtml(__('Current Password')) ?>
                </label>

                <input
                    id="current-password"
                    class="input__field"
                    type="password"
                    name="current_password"
                    data-input="current-password"
                    autocomplete="off"
                />
            </div>

            <div
                class="
                    input
                    dashboard-form--hidden
                    newPassword
                    required
                "
                data-container="new-password"
            >
                <?php
                    $minPasswordLength = $escaper->escapeHtml($block->getMinimumPasswordLength());
                    $maxPasswordLength = $escaper->escapeHtml($block->getRequiredCharacterClassesNumber());
                ?>

                <label class="label" for="password">
                    <?= $escaper->escapeHtml(__('New Password')) ?>
                </label>

                <input
                    id="password"
                    class="input__field"
                    type="password"
                    name="password"
                    data-password-min-length="<?= $escaper->escapeHtmlAttr($minPasswordLength) ?>"
                    data-password-min-character-sets="<?= $escaper->escapeHtmlAttr($maxPasswordLength) ?>"
                    data-input="new-password"
                    data-validate="{
                        required: true,
                        'validate-customer-password': true
                    }"
                    autocomplete="off"
                />

                <div
                    id="password-strength-meter-container"
                    data-role="password-strength-meter"
                    aria-live="polite"
                    class="password-strength"
                >
                    <div
                        id="password-strength-meter"
                        data-role="password-strength-meter"
                        class="password-none"
                    >
                        <div class="password-strength__handle">
                            <?= $escaper->escapeHtml(__('Password Strength')) ?>:
                            <span
                                id="password-strength-meter-label"
                                data-role="password-strength-meter-label"
                                class="password-strength__indicator"
                            >
                                <?= $escaper->escapeHtml(__('No Password')) ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div
                class="
                    input
                    confirmation
                    password
                    required
                "
                data-container="confirm-password"
            >
                <label class="label" for="password-confirmation">
                    <?= $escaper->escapeHtml(__('Confirm New Password')) ?>
                </label>

                <input
                    id="password-confirmation"
                    class="input__field"
                    type="password"
                    name="password_confirmation"
                    data-input="confirm-password"
                    autocomplete="off"
                >
            </div>

            <div
                class="input choice"
                data-bind="scope: 'showPassword'"
            >
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>


            <?= $block->getChildHtml('form_additional_info'); ?>
        </div>
    </div>

    <div class="action">
        <div class="action__handler">
            <button
                type="submit"
                class="button action__button"
                title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>"
            >
                <?= $escaper->escapeHtml(__('Save')) ?>
            </button>
        </div>

        <div class="action__handler">
            <a
                class="action__link"
                href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"
            >
                <?= $escaper->escapeHtml(__('Go back')) ?>
            </a>
        </div>
    </div>
</form>
<?php $ignore = /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null';
$scriptString = <<<script
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = {$ignore};

        dataForm.mage('validation', {
script;
if ($_dob->isEnabled()):
    $scriptString .= <<<script
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
script;
else:
    $scriptString .= <<<script
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
script;
endif;
$scriptString .= <<<script
        });
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php $changeEmailAndPasswordTitle = $escaper->escapeHtml(__('Change Email and Password')) ?>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $escaper->escapeJs($escaper->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $escaper->escapeJs($escaper->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $escaper->escapeJs($changeEmailAndPasswordTitle) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        },
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "showPassword": {
                        "component": "Magento_Customer/js/show-password",
                        "passwordSelector": "#current-password,#password,#password-confirmation"
                    }
                }
            }
        }
    }
</script>
