<?php
/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<div class="dashboard-form">
    <form
        class="form form-edit-account"
        action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>"
        method="post"
        id="form-validate"
        enctype="multipart/form-data"
        data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
        autocomplete="off"
    >
        <div class="fieldset info">
            <?= $block->getBlockHtml('formkey') ?>
            <h2 class="dashboard-items__title margin-bottom-sm">
                <?= $block->escapeHtml(__('Account Information')) ?>
            </h2>
            <?= $block->getLayout()
                ->createBlock(\Magento\Customer\Block\Widget\Name::class)
                ->setObject($block->getCustomer())
                ->toHtml()
            ?>
            <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
            <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
            <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
            <?php if ($_dob->isEnabled()) : ?>
                <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
            <?php endif ?>
            <?php if ($_taxvat->isEnabled()) : ?>
                <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
            <?php endif ?>
            <?php if ($_gender->isEnabled()) : ?>
                <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
            <?php endif ?>
            <div class="checkbox">
                <input
                    type="checkbox"
                    name="change_email"
                    id="change-email"
                    data-role="change-email"
                    value="1"
                    title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>"
                    class="checkbox__field"
                />
                <svg
                    class="
                        checkbox__icon
                        checkbox__icon--checked
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                </svg>
                <svg
                    class="
                        checkbox__icon
                        checkbox__icon--unchecked
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
                </svg>
                <label
                    class="checkbox__label"
                    for="change-email"
                >
                    <?= $block->escapeHtml(__('Change Email')) ?>
                </label>
            </div>
            <div class="checkbox">
                <input
                    type="checkbox"
                    name="change_password"
                    id="change-password"
                    data-role="change-password"
                    value="1"
                    title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"
                    <?php if ($block->getChangePassword()): ?>
                        checked="checked"
                    <?php endif; ?>
                    class="checkbox__field"
                />
                <svg
                    class="
                        checkbox__icon
                        checkbox__icon--checked
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                </svg>
                <svg
                    class="
                        checkbox__icon
                        checkbox__icon--unchecked
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
                </svg>
                <label
                    class="checkbox__label"
                    for="change-password"
                >
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </label>
            </div>
        </div>

        <div
            class="fieldset display-none"
            data-container="change-email-password"
            aria-labelledby="change-email-password"
        >
            <h2
                class="dashboard-items__title margin-bottom-sm"
                data-title="change-email-password"
                id="change-email-password"
            >
                <?= $block->escapeHtml(__('Change Email and Password')) ?>
            </h2>
            <div
                class="input required"
                data-container="change-email"
            >
                <label
                    class="input__label"
                    for="email"
                >
                    <?= $block->escapeHtml(__('Email')) ?>
                </label>
                <input
                    type="email"
                    name="email"
                    id="email"
                    autocomplete="email"
                    data-input="change-email"
                    value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"
                    title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                    class="input__field"
                    data-validate="{required:true, 'validate-email':true}"
                />
            </div>
            <div class="input password current required">
                <label
                    class="input__label"
                    for="current-password"
                >
                    <?= $block->escapeHtml(__('Current Password')) ?>
                </label>
                <input
                    type="password"
                    class="input__field"
                    name="current_password"
                    id="current-password"
                    data-input="current-password"
                    autocomplete="off"
                />
            </div>
            <div
                class="input new password required"
                data-container="new-password"
            >
                <label
                    class="input__label"
                    for="password"
                >
                    <?= $block->escapeHtml(__('New Password')) ?>
                </label>
                <input
                    type="password"
                    class="input__field"
                    name="password"
                    id="password"
                    data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off"
                />
                <div class="password-strength margin-top-xs">
                    <div
                        id="password-strength-meter-container"
                        class="password-none"
                        data-role="password-strength-meter"
                        aria-live="polite"
                    >
                        <div
                            id="password-strength-meter"
                            class="password-strength__handle password-strength-meter"
                        >
                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                            <span
                                id="password-strength-meter-label"
                                class="password-strength__indicator"
                                data-role="password-strength-meter-label"
                            >
                                <?= $block->escapeHtml(__('No Password')) ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div
                class="input confirmation password required"
                data-container="confirm-password"
            >
                <label
                    class="input__label"
                    for="password-confirmation"
                >
                    <?= $block->escapeHtml(__('Confirm New Password')) ?>
                </label>
                <input
                    type="password"
                    class="input__field"
                    name="password_confirmation"
                    id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off"
                />
            </div>
        </fieldset>
        <?= $block->getChildHtml('form_additional_info') ?>
        <div class="actions-group margin-top-l">
            <div class="actions-group__handler">
                <button
                    type="submit"
                    class="button actions-group__button"
                    title="<?= $block->escapeHtmlAttr(__('Save')) ?>"
                >
                    <?= $block->escapeHtml(__('Save')) ?>
                </button>
            </div>
            <div class="actions-group__handler">
                <a
                    class="actions-group__link"
                    href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
                >
                    <?= $block->escapeHtml(__('Go back')) ?>
                </a>
            </div>
        </div>
    </form>
</div>

<script>
    require([
        "jquery",
        "mage/mage"
    ], function($) {
        var dataForm = $('#form-validate');
        var ignore = <?= $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()): ?>
                errorPlacement: function(error, element) {
                    if (element.prop('id').search('full') !== -1) {
                        var dobElement = $(element).parents('.customer-dob'),
                            errorClass = error.prop('class');
                        error.insertAfter(element.parent());
                        dobElement.find('.validate-custom').addClass(errorClass)
                            .after('<div class="' + errorClass + '"></div>');
                    } else {
                        error.insertAfter(element);
                    }
                },
                ignore: ':hidden:not(' + ignore + ')'
            <?php else: ?>
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            <?php endif ?>
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
