<?php
/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="forgot-password">
    <p id="formLabel">
        <?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')); ?>
    </p>
    <form
        action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
        method="post"
        id="form-validate"
        data-mage-init='{ "validation": { } }'
        aria-labelledby="formLabel"
    >
        <div class="input required">
            <label for="email-address" class="label">
                <?= $block->escapeHtml(__('Email')) ?>
            </label>
            <input
                type="email"
                name="email"
                alt="email"
                id="email-address"
                class="input__field"
                value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>"
                data-validate="{ required: true, 'validate-email': true }"
            >
        </div>
        <?=  $block->getChildHtml('form_additional_info'); ?>
        <button type="submit" class="button">
            <?= $block->escapeHtml(__('Reset My Password')) ?>
        </button>
    </form>
</div>
