<?php
/** @var $block \Magento\Customer\Block\Account\Forgotpassword */
?>
<div class="forgot-password">
    <p id="formLabel">
        <?= __('Please enter your email address below to receive a password reset link.'); ?>
    </p>
    <form
        action="<?= $block->getUrl('*/*/forgotpasswordpost') ?>"
        method="post"
        id="form-validate"
        data-mage-init='{ "validation": { } }'
        aria-labelledby="formLabel"
    >
        <div class="input required">
            <label for="email-address" class="label">
                <?= __('Email') ?>
            </label>
            <input
                type="email"
                name="email"
                alt="email"
                id="email-address"
                class="input__field"
                value="<?= $block->escapeHtml($block->getEmailValue()) ?>"
                data-validate="{ required: true, 'validate-email': true }"
            >
        </div>
        <?=  $block->getChildHtml('form_additional_info'); ?>
        <button type="submit" class="button">
            <?= __('Reset My Password') ?>
        </button>
    </form>
</div>
