<?php
/** @var $block \Magento\Customer\Block\Account\Forgotpassword */
?>
<form class="form forgot-password"
      action="<?= /* @escapeNotVerified */ $block->getUrl('*/*/forgotpasswordpost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'
>
    <p class="paragraph">
        <?= /* @escapeNotVerified */ __('Please enter your email address below to receive a password reset link.'); ?>
    </p>

    <div class="input required">
        <label for="email_address" class="input__label">
            <?= /* @escapeNotVerified */ __('Email') ?>
        </label>
        <input type="email"
               name="email"
               alt="email"
               id="email_address"
               class="input__field"
               value="<?= $block->escapeHtml($block->getEmailValue()) ?>"
               data-validate="{required:true, 'validate-email':true}"
        >
    </div>

    <?=  $block->getChildHtml('form_additional_info'); ?>
    
    <button type="submit" class="button">
        <?= /* @escapeNotVerified */ __('Reset My Password') ?>
    </button>
</form>
