<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var \Magento\Customer\Block\Form\Login $block
 */
?>
<div class="col-xs-12 col-md-6 login__form-column">
    <h3>
        <?= $block->escapeHtml(__('Registered Customers')) ?>
    </h3>
    <div class="divider"></div>
    <p class="login__info">
        <?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?>
    </p>
    <form
        class="login__form"
        action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
        method="post"
        id="login-form"
        data-mage-init='{"validation":{}}'
    >
        <fieldset class="fieldset login__fieldset">
            <legend class="fieldset__legends login__legend"></legend>
            <?= $block->getBlockHtml('formkey'); ?>
            <div class="input login__input required">
                <label for="email">
                    <?= $block->escapeHtml(__('Email')) ?>
                </label>
                <input
                    name="login[username]"
                    value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                    <?= ($block->isAutocompleteDisabled()) ? 'autocomplete="off"' : '' ?>
                    id="email"
                    type="email"
                    class="input__field"
                    title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                    data-mage-init='{"mage/trim-input":{}}'
                    data-validate="{required:true, 'validate-email':true}"
                >
            </div>
            <div class="input login__input required">
                <label>
                   <?= $block->escapeHtml(__('Password')) ?>
                </label>
                <input
                    name="login[password]"
                    type="password"
                    <?= ($block->isAutocompleteDisabled()) ?  'autocomplete="off"': '' ?>
                    class="input__field"
                    id="pass"
                    title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                    data-validate="{required:true}"
                >
            </div>
            <?= $block->getChildHtml('form_additional_info'); ?>
        </fieldset>
        <div class="login__actions">
            <button
                type="submit"
                class="button login__button"
                name="send"
                id="send2"
                data-testid="submit-login-button"
            >
                <?= $block->escapeHtml(__('Sign In')) ?>
            </button>
            <a
                href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"
                class="login__forgot-password"
                data-testid="forgot-password-link"
            >
                <?= $block->escapeHtml(__('Forgot your password?')) ?>
            </a>
        </div>
    </form>
</div>
