<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var \Magento\Customer\Block\Form\Login $block
 */
?>
<div class="col-xs-12 col-md-6 login__form-column">
    <h3>
        <?= __('Registered Customers') ?>
    </h3>
    <div class="divider"></div>
    <p class="login__info">
        <?= __('If you have an account, sign in with your email address.') ?>
    </p>
    <form
        class="login__form"
        action="<?= $block->getPostActionUrl() ?>"
        method="post"
        id="login-form"
        data-mage-init='{"validation":{}}'
    >
        <fieldset class="fieldset login__fieldset">
            <legend class="fieldset__legends login__legend"></legend>
            <?= $block->getBlockHtml('formkey'); ?>
            <div class="input login__input required">
                <label for="email">
                    <?= __('Email') ?>
                </label>
                <input
                    name="login[username]"
                    value="<?= $block->escapeHtml($block->getUsername()) ?>"
                    <?= ($block->isAutocompleteDisabled()) ? 'autocomplete="off"' : '' ?>
                    id="email"
                    type="email"
                    class="input__field"
                    title="<?= __('Email') ?>"
                    data-validate="{required:true, 'validate-email':true}"
                >
            </div>
            <div class="input login__input required">
                <label>
                   <?= __('Password') ?>
                </label>
                <input
                    name="login[password]"
                    type="password"
                    <?= ($block->isAutocompleteDisabled()) ?  'autocomplete="off"': '' ?>
                    class="input__field"
                    id="pass"
                    title="<?= __('Password') ?>"
                    data-validate="{required:true}"
                >
            </div>
            <?= $block->getChildHtml('form_additional_info'); ?>
        </fieldset>
        <div class="login__actions">
            <button
                type="submit"
                class="button login__button"
                name="send"
                id="send2"
                data-testid="submit-login-button"
            >
                <?= __('Sign In') ?>
            </button>
            <a
                href="<?= $block->getForgotPasswordUrl() ?>"
                class="login__forgot-password"
                data-testid="forgot-password-link"
            >
                <?= __('Forgot your password?') ?>
            </a>
        </div>
    </form>
</div>
