<?php echo $block->getChildHtml('form_before')?>

<form class="form dashboard-form" action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>" method="post" id="form-validate">
    <?php echo $block->getBlockHtml('formkey')?>

    <h5 class="heading heading--fifth-level dashboard-form__title">
        <?php /* @escapeNotVerified */ echo __('Subscription option') ?>
    </h5>

    <div class="checkbox dashboard-form__divider">
        <input type="checkbox" 
               name="is_subscribed" 
               id="subscription" 
               value="1" 
               title="<?php /* @escapeNotVerified */ echo __('General Subscription') ?>"
               <?php if ($block->getIsSubscribed()): ?> 
                    checked="checked"
               <?php endif; ?> 
               class="checkbox__field"
        />

        <svg class="checkbox__icon">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
        </svg>

        <label for="subscription" class="checkbox__label">
            <?php /* @escapeNotVerified */ echo __('General Subscription') ?>
        </label>
    </div>

    <?php /* Extensions placeholder */ ?>
    <?php echo $block->getChildHtml('customer.form.newsletter.extra')?>

    <div class="action">
        <div class="action__handler">
            <button type="submit" 
                    title="<?php /* @escapeNotVerified */ echo __('Save') ?>" 
                    class="button action__button save primary"
            >
                <?php /* @escapeNotVerified */ echo __('Save') ?>
            </button>
        </div>
        
        <div class="action__handler">
            <a class="link action__link back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>">
                <?php /* @escapeNotVerified */ echo __('Back') ?>
            </a>
        </div>
    </div>
</form>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.newsletter.extra2')?>
