<?= $block->getChildHtml('form_before') ?>

<form
    class="form dashboard-form"
    action="<?= $escaper->escapeUrl($block->getAction()) ?>"
    method="post"
    id="form-validate"
>
    <?= $block->getBlockHtml('formkey') ?>

    <h3 class="dashboard-form__title">
        <?= $escaper->escapeHtml(__('Subscription option')) ?>
    </h3>

    <div class="checkbox dashboard-form__divider">
        <input type="checkbox"
               name="is_subscribed"
               id="subscription"
               value="1"
               title="<?= $escaper->escapeHtmlAttr(__('General Subscription')) ?>"
               <?php if ($block->getIsSubscribed()): ?>
                    checked="checked"
               <?php endif; ?>
               class="checkbox__field"
        />

        <svg class="checkbox__icon">
            <use
                xmlns:xlink="http://www.w3.org/1999/xlink"
                href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked')); ?>"
            ></use>
        </svg>

        <label
            for="subscription"
            class="checkbox__label"
        >
            <?= $escaper->escapeHtml(__('Subscribe to our newsletter')) ?>
        </label>
    </div>

    <?php /* Extensions placeholder */ ?>
    <?= $block->getChildHtml('customer.form.newsletter.extra') ?>

    <div class="action">
        <div class="action__handler">
            <button
                type="submit"
                title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>"
                class="
                    button
                    action__button
                    save
                    primary
                "
            >
                <?= $escaper->escapeHtml(__('Save')) ?>
            </button>
        </div>

        <div class="action__handler">
            <a
                class="link action__link back"
               href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"
            >
                <?= $escaper->escapeHtml(__('Back')) ?>
            </a>
        </div>
    </div>
</form>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.newsletter.extra2') ?>
