<?php
/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<form
    class="forgot-password"
    action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['id' => $block->getCustomerId(), 'token' => $block->getResetPasswordLinkToken()]])) ?>"
    method="post"
    <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
    id="form-validate"
    data-mage-init='{ "validation": { } }'
    data-hasrequired="<?= __('* Required Fields') ?>"
>
    <div
        data-mage-init='{
            "passwordStrengthIndicator": {
                "defaultClassName": "password-strength--"
            }
        }'
    >
        <div class="input required">
            <label class="label" for="password">
                <?= __('New Password') ?>
            </label>
            <input
                type="password"
                class="input__field"
                name="password"
                id="password"
                data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                data-validate="{
                    required: true,
                    'validate-customer-password': true
                }"
                autocomplete="off"
            >
        </div>
        <div class="password-strength forgot-password__strength-meter">
            <div
                id="password-strength-meter-container"
                data-role="password-strength-meter"
                aria-live="polite"
            >
                <div
                    id="password-strength-meter"
                    class="password-strength-meter"
                >
                    <?= __('Password Strength') ?>:
                    <span
                        class="password-strength__indicator"
                        id="password-strength-meter-label"
                        data-role="password-strength-meter-label"
                    >
                        <?= __('No Password') ?>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div class="input required">
        <label class="label" for="password-confirmation">
            <?= __('Confirm New Password') ?>
        </label>
        <input
            type="password"
            class="input__field"
            name="password_confirmation"
            id="password-confirmation"
            data-validate="{ required: true, equalTo: '#password' }"
            autocomplete="off"
        >
    </div>

    <button
        type="submit"
        class="button"
    >
        <?= __('Set a New Password') ?>
    </button>
</form>
