<?php
/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<div class="forgot-password">
    <form
        action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['token' => $block->getResetPasswordLinkToken()]])) ?>"
        method="post"
        id="form-validate"
        class="account-form"
        data-mage-init='{"validation":{}}'
    >
        <fieldset
            class="
                fieldset
                margin-bottom-sm
            "
            data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
        >
            <div
                data-mage-init='{
                    "passwordStrengthIndicator": {
                        "defaultClassName": "password-strength--"
                    }
                }'
            >
                <div
                    class="
                        input
                        input--password
                        required
                    "
                >
                    <label
                        class="label input__label"
                        for="password"
                    >
                        <?= $block->escapeHtml(__('New Password')) ?>
                    </label>
                    <input
                        type="password"
                        class="input__field"
                        name="password"
                        id="password"
                        data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                        data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                        data-validate="{required:true, 'validate-customer-password':true}"
                        autocomplete="off"
                    />
                    <button
                        type="button"
                        class="
                            button
                            button--icon
                            input__button-pass
                        "
                        aria-label="<?= $block->escapeHtmlAttr(__('Show/hide password')) ?>"
                        data-mage-init='{"passwordTrigger": {}}'
                    >
                        <svg
                            class="
                                icon
                                icon--secondary
                                input__button-pass-icon-view
                            "
                            role="presentation"
                            focusable="false"
                        >
                            <title><?= $block->escapeHtml(__('View password icon')) ?></title>
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#visibility-off')); ?>"></use>
                        </svg>

                        <svg
                            class="
                                icon
                                icon--secondary
                                input__button-pass-icon-hide
                            "
                            role="presentation"
                            focusable="false"
                        >
                            <title><?= $block->escapeHtml(__('Hide password icon')) ?></title>
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#visibility')); ?>"></use>
                        </svg>
                    </button>
                    <div
                        class="
                            password-strength
                            margin-bottom-m
                            margin-top-xs
                        "
                    >
                        <div
                            class="password-none"
                            data-role="password-strength-meter"
                        >
                            <div class="password-strength__handle">
                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                <span
                                    class="password-strength__indicator"
                                    data-role="password-strength-meter-label"
                                    aria-live="polite"
                                >
                                    <?= $block->escapeHtml(__('No Password')) ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div
                class="
                    input
                    input--password
                    required
                "
            >
                <label
                    class="label input__label"
                    for="password-confirmation"
                >
                    <?= $block->escapeHtml(__('Confirm New Password')) ?>
                </label>
                <input
                    type="password"
                    class="input__field"
                    name="password_confirmation"
                    id="password-confirmation"
                    data-validate="{required:true,equalTo:'#password'}"
                    autocomplete="off"
                >
                <button
                    type="button"
                    class="
                        button
                        button--icon
                        input__button-pass
                    "
                    aria-label="<?= $block->escapeHtmlAttr(__('Show/hide password')) ?>"
                    data-mage-init='{"passwordTrigger": {}}'
                >
                    <svg
                        class="
                            icon
                            icon--secondary
                            input__button-pass-icon-view
                        "
                        role="presentation"
                        focusable="false"
                    >
                        <title><?= $block->escapeHtml(__('View password icon')) ?></title>
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#visibility-off')); ?>"></use>
                    </svg>

                    <svg
                        class="
                            icon
                            icon--secondary
                            input__button-pass-icon-hide
                        "
                        role="presentation"
                        focusable="false"
                    >
                        <title><?= $block->escapeHtml(__('Hide password icon')) ?></title>
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#visibility')); ?>"></use>
                    </svg>
                </button>
            </div>
        </fieldset>
        <div class="account-form__actions">
            <button
                type="submit"
                class="button account-form__button"
            >
                <?= $block->escapeHtml(__('Set a New Password')) ?>
            </button>
        </div>
    </form>
</div>
