<?php
/** @var \Magento\Captcha\Block\Captcha\DefaultCaptcha $block */
/** @var \Magento\Captcha\Model\DefaultModel $captcha */
$captcha = $block->getCaptchaModel();
/** @var bool $validationEnabled */
$validationEnabled = $block->hasData('frontend_validation') ? $block->getData('frontend_validation') : true;
$inputName = $block->escapeHtmlAttr(\Magento\Captcha\Helper\Data::INPUT_NAME_FIELD_VALUE);
$loaderUrl = $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif'));
?>
<div
    class="
        input
        forgot-password__captcha-field
        <?php if ($validationEnabled): ?>
            required
        <?php endif; ?>"
    "
>
    <label
        class="input__label"
        for="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
    >
        <?= $block->escapeHtml(__('Please type the letters below')) ?>
    </label>
    <input
        name="<?= /* @noEscape */ $inputName ?>[<?= $block->escapeHtmlAttr($block->getFormId()) ?>]"
        type="text"
        class="input__field"
        <?php if ($validationEnabled): ?>
            data-validate="{ required: true }"
        <?php endif; ?>"
        id="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
    />
</div>

<div
    class="forgot-password__captcha-wrapper"
    data-captcha="<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
    id="captcha-container-<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
    data-mage-init='{
        "captcha": {
            "url": "<?= $block->escapeUrl($block->getRefreshUrl()) ?>",
            "imageLoader": "<?= /* @noEscape */ $loaderUrl ?>",
            "type": "<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
        }
    }'
>
    <img
        alt="<?= $block->escapeHtmlAttr(__('Please type the letters below')) ?>"
        class="
            captcha-img
            image
            forgot-password__image
        "
        height="<?= (float) $block->getImgHeight() ?>"
        src="<?= $block->escapeUrl($captcha->getImgSrc()) ?>"
    />
    <button
        type="button"
        class="
            button
            button--secondary
            forgot-password__captcha
            captcha-reload
        "
        title="<?= $block->escapeHtmlAttr(__('Reload captcha')); ?>"
    >
        <?= $block->escapeHtml(__('Reload captcha')) ?>
    </button>
</div>
