<?php
/** @var \Magento\Captcha\Block\Captcha\DefaultCaptcha $block */

/** @var \Magento\Captcha\Model\DefaultModel $captcha */
$captcha = $block->getCaptchaModel();
/** @var bool $validationEnabled */
$validationEnabled = $block->hasData('frontend_validation') ? $block->getData('frontend_validation') : true;
$inputName = $escaper->escapeHtmlAttr(\Magento\Captcha\Helper\Data::INPUT_NAME_FIELD_VALUE);
$loaderUrl = $escaper->escapeUrl($block->getViewFileUrl('images/loader-2.gif'));
$note = $escaper->escapeHtml(__('<strong>Attention</strong>: Captcha is case sensitive.'), ['strong']);
?>
<div
    class="
        input
        forgot-password__captcha-field
        <?php if ($validationEnabled): ?> required<?php endif; ?>
    "
>
    <label
        class="label"
        for="captcha_<?= $escaper->escapeHtmlAttr($block->getFormId()) ?>"
    >
        <?= $escaper->escapeHtml(__('Please type the letters below')) ?>
    </label>
    <input
        name="<?= /* @noEscape */ $inputName ?>[<?= $escaper->escapeHtmlAttr($block->getFormId()) ?>]"
        type="text"
        class="
            input__field
            <?php if ($validationEnabled): ?> required-entry<?php endif; ?>
        "
        <?php if ($validationEnabled): ?>data-validate="{ required: true }"<?php endif; ?>
        id="captcha_<?= $escaper->escapeHtmlAttr($block->getFormId()) ?>"
        autocomplete="off"
    />
</div>

<div
    class="
        captcha
        forgot-password__captcha-wrapper
    "
    data-captcha="<?= $escaper->escapeHtmlAttr($block->getFormId()) ?>"
    id="captcha-container-<?= $escaper->escapeHtmlAttr($block->getFormId()) ?>"
    data-mage-init='{
        "captcha":{
            "url": "<?= $escaper->escapeUrl($block->getRefreshUrl()) ?>",
            "imageLoader": "<?= /* @noEscape */ $loaderUrl ?>",
            "type": "<?= $escaper->escapeHtmlAttr($block->getFormId()) ?>"
        }
    }'
>
    <img
        alt="<?= $escaper->escapeHtmlAttr(__('Please type the letters and numbers below')) ?>"
        class="
            captcha-img
            image
            forgot-password__image
        "
        height="<?= /* @noEscape */ (float) $block->getImgHeight() ?>"
        src="<?= $escaper->escapeUrl($captcha->getImgSrc()) ?>"
    />
    <button
        type="button"
        class="
            button
            button--secondary
            reload
            captcha-reload
        "
        title="<?= $escaper->escapeHtmlAttr(__('Reload captcha')); ?>"
    >
        <?= $escaper->escapeHtml(__('Reload captcha')) ?>
    </button>
    <?php if ($captcha->isCaseSensitive()):?>
        <div class="captcha-note input__note">
            <?= /* @noEscape */ $note ?>
        </div>
    <?php endif; ?>
</div>
