<?php
/** @var \Magento\Captcha\Block\Captcha\DefaultCaptcha $block */
/** @var \Magento\Captcha\Model\DefaultModel $captcha */
$captcha = $block->getCaptchaModel();
?>
<div class="input forgot-password__captcha-field required">
    <label
        class="label"
        for="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
    >
        <?= __('Please type the letters below') ?>
    </label>
    <input
        name="<?= $block->escapeHtmlAttr(\Magento\Captcha\Helper\Data::INPUT_NAME_FIELD_VALUE) ?>[<?= $block->escapeHtmlAttr($block->getFormId()) ?>]"
        type="text"
        class="input__field"
        data-validate="{ required: true }"
        id="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
    />
</div>

<div
    class="forgot-password__captcha-wrapper"
    data-captcha="<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
    id="captcha-container-<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
    data-mage-init='{
        "captcha": {
            "url": "<?= $block->escapeUrl($block->getRefreshUrl()) ?>",
            "imageLoader": "<?= $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif')) ?>",
            "type": "<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
        }
    }'
>
    <img
        alt="<?= __('Please type the letters below') ?>"
        class="
            captcha-img
            image
            forgot-password__image
        "
        height="<?= (float) $block->getImgHeight() ?>"
        src="<?= $block->escapeUrl($captcha->getImgSrc()) ?>"
    />
    <button
        type="button"
        class="
            button
            button--secondary
            reload
            captcha-reload
        "
        title="<?= __('Reload captcha') ?>"
    >
        <?= __('Reload captcha') ?>
    </button>
</div>
