<!-- <link
    href="<?= $this->getViewFileUrl('Amasty_Storelocator::css/source/mkcss/amlocator.css') ?>"
    rel="stylesheet"
    media="print"
    onload="this.media='all';
    this.onload=null;"
/>
 -->

<link
    rel="preload"
    href="<?= $this->getViewFileUrl('Amasty_Storelocator::css/source/mkcss/amlocator.css') ?>"
    as="style"
    onload="this.onload=null;this.rel='stylesheet'">

<noscript>
    <link rel="stylesheet" href="<?= $this->getViewFileUrl('Amasty_Storelocator::css/source/mkcss/amlocator.css') ?>">
</noscript>
