<?php /** @var \Amasty\Storelocator\Block\Location $block */ ?>
<?php
$productId = (int) $block->getRequest()->getParam('product');

if ($productId):
    $product = $block->getProductById($productId);
    ?>
    <h1>
        <?= $block->escapeHtml($product->getName()); ?><?= $block->escapeHtml(__(' can be found at the following stores:&nbsp;')); ?>
    </h1>
    <hr>
<?php endif; ?>
<div
    class="
        amlocator-main-container
        store-locator
    "
    style="<?= $block->escapeHtmlAttr($block->getMainBlockStyles()); ?>"
>
    <?php if ($block->getWidgetDescription()): ?>
        <div>
            <?= $block->escapeHtml($block->getWidgetDescription()); ?>
        </div>
    <?php endif; ?>
    <div
        id="<?= $block->escapeHtmlAttr($block->getMapContainerId()); ?>"
        class="amlocator-map-container"
    >
        <?php if ($block->getShowSearch()): ?>
            <div class="amlocator-search-container">
                <div
                    class="
                        amlocator-block
                        -current
                        amlocator-current-location
                    "
                >
                    <div
                        class="
                            amlocator-wrapper
                            input
                            input--password
                        "
                    >
                        <label
                            for="store-locator-search"
                            class="label label--hidden"
                        >
                            <?= $block->escapeHtml(__('Search location')) ?>
                        </label>
                        <input
                            type="text"
                            value=""
                            class="
                                input__field
                                amlocator-text
                            "
                            id="store-locator-search"
                            name="address"
                            placeholder="<?= $block->escapeHtmlAttr(__('Current location')); ?>"
                            data-amlocator-js="address"
                            autocomplete="off"
                        >
                        <button
                            type="button"
                            class="
                                button
                                button--icon
                                input__button-pass
                                store-locator__button-search
                            "
                            data-amlocator-js="search"
                        >
                            <svg
                                class="
                                    icon
                                    icon--secondary
                                    input__button-pass-icon-view
                                "
                                role="presentation"
                                focusable="false"
                            >
                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#search')); ?>"></use>
                            </svg>
                        </button>
                        <button
                            type="button"
                            class="
                                amlocator-reset
                                -hidden
                                button
                                button--icon
                                input__button-pass
                                store-locator__button-search
                            "
                            data-amlocator-js="reset"
                        >
                            <svg
                                class="
                                    icon
                                    icon--secondary
                                    input__button-pass-icon-view
                                "
                                role="presentation"
                                focusable="false"
                            >
                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#close')); ?>"></use>
                            </svg>
                        </button>
                    </div>
                </div>
                <div
                    class="
                        amlocator-block
                        -search
                        amlocator-search-radius
                        margin-bottom-s
                    "
                >
                    <label
                        class="amlocator-title"
                        id="range_radius"
                        for="radius"
                    >
                        <?= $block->escapeHtml(__('Search Radius')); ?>
                    </label>
                    <?php if ($block->getDistanceConfig() == 'choose'): ?>
                        <div
                            class="
                                amlocator-select
                                select
                                select--native
                            "
                        >
                            <select
                                class="
                                    -measurement
                                    select__field
                                "
                                id="amlocator-measurement"
                                name="measurement"
                                data-amlocator-js="measurment-select"
                            >
                                <option value="km">
                                    <?= $block->escapeHtml(__('km')); ?>
                                </option>
                                <option selected="selected" value="mi">
                                    <?= $block->escapeHtml(__('mi')); ?>
                                </option>
                            </select>
                        </div>
                    <?php else: ?>
                        <label class="amlocator-title">
                            , <?= $block->escapeHtml($block->getDistanceConfig()) ?>
                        </label>
                    <?php endif; ?>
                    <div class="amlocator-wrapper">
                        <?php if ($block->getRadiusType() == 'select' || empty($block->getRadiusType())): ?>
                            <div
                                class="
                                    select
                                    select--native
                                    amlocator-select
                                "
                            >
                                <select
                                    class="select__field"
                                    data-amlocator-js="radius-select"
                                    name="radius"
                                >
                                    <?php foreach ($block->getSearchRadius() as $range): ?>
                                        <option value="<?= is_numeric($range) ? (int) $range : ''; ?>">
                                            <?= $block->escapeHtml($range) ?>
                                        </option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        <?php else:?>
                            <div
                                class="amlocator-range-slider"
                                data-amlocator-js="range-slider"
                            >
                                <div
                                    class="
                                        amlocator-handle
                                        ui-slider-handle
                                    "
                                >
                                    <div class="amlocator-tooltip display-none">
                                        <span data-amlocator-js="radius-measurment">
                                            <?= ($block->getDistanceConfig() != 'choose')
                                                ? $block->escapeHtml($block->getDistanceConfig())
                                                : '' ?>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <input
                                type="hidden"
                                name="radius"
                                data-amlocator-js="radius-select"
                                value="<?= (int) $block->getMaxRadiusValue(); ?>"
                                min="<?= (int) $block->getMinRadiusValue(); ?>"
                                max="<?= (int) $block->getMaxRadiusValue(); ?>"
                            />
                        <?php endif ?>
                    </div>
                </div>
                <div class="amlocator-block -separator">
                    <hr class="hr"/>
                </div>
                <button
                    class="
                        button
                        button--fluid
                        amlocator-button
                        -nearby
                    "
                    title="<?= $block->escapeHtmlAttr(__('Locate Nearby')); ?>"
                >
                    <?= $block->escapeHtml(__('Locate Nearby')); ?>
                </button>
                <div class="amlocator-block -separator">
                    <hr class="hr"/>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($block->getShowLocations()): ?>
            <?php if ($attributes = $block->getAttributes()): ?>
                <div
                    class="
                        amlocator-block
                        -filter
                    "
                >
                    <div class="amlocator-filters-container">
                        <div
                            class="
                                amlocator-title
                                amlocator-attribute-filter
                            "
                            data-amlocator-js="filters-title"
                        >
                            <span>
                                <?= $block->escapeHtml(__('Filter')); ?>
                            </span>
                            <span
                                class="
                                    amlocator-arrow
                                    <?= $block->escapeHtml($block->getFilterClass()) ? ' -down' : ''; ?>
                                "
                            ></span>
                        </div>
                        <div
                            class="amlocator-content<?= $block->escapeHtml($block->getFilterClass()); ?>"
                            data-amlocator-js="filters-container"
                        >
                            <?php $attributes = $block->getAttributes(); ?>
                            <form
                                class="attributes"
                                action="#"
                                data-amlocator-js="attributes-form"
                            >
                                <?php foreach ($attributes as $attribute): ?>
                                    <div class="amlocator-attribute-wrapper">
                                        <div class="amlocator-label">
                                            <?= $block->escapeHtml($attribute['label']); ?>
                                        </div>
                                        <div
                                            class="
                                                amlocator-input
                                                select
                                                select--native
                                            "
                                        >
                                            <select
                                                name="<?= (int) $attribute['attribute_id']; ?>"
                                                class="amlocator-select"
                                                <?php if ($attribute['frontend_input'] == 'multiselect'): ?>
                                                    multiple="multiple"
                                                    data-amlocator-js="multiple-select"
                                                <?php endif; ?>
                                            >
                                                <?php if ($attribute['frontend_input'] != 'multiselect'):?>
                                                    <option value="" selected>
                                                        <?= $block->escapeHtml(__('Please Select')); ?>
                                                    </option>
                                                <?php endif?>
                                                <?php foreach ($attribute['options'] as $valueId => $option): ?>
                                                    <option
                                                        <?php if ($block->isOptionSelected(
                                                            $attribute,
                                                            $option
                                                        )): ?>
                                                            selected
                                                        <?php endif; ?>
                                                        value="<?= (int)$option['value'] ?>">
                                                        <?= $block->escapeHtml(
                                                            $option['label']
                                                        ); ?>
                                                    </option>
                                                <?php endforeach;?>
                                            </select>
                                        </div>
                                    </div>
                                <?php endforeach;?>
                            </form>
                            <div
                                class="
                                    amlocator-actions
                                    store-locator__filter-actions
                                "
                            >
                                <span
                                    class="
                                        amlocator-clear
                                        button
                                        button--secondary
                                        margin-right-s
                                    "
                                   title="<?= $block->escapeHtml(__('Reset')); ?>"
                                   data-amlocator-js="clear-filters"
                                >
                                    <?= $block->escapeHtml(__('Reset')); ?>
                                </span>
                                <button
                                    class="
                                        button
                                        amlocator-button
                                        amlocator-filter-attribute
                                    "
                                    type="button"
                                    title="<?= $block->escapeHtml(__('Filter')) ?>"
                                >
                                    <?= $block->escapeHtml(__('Filter')); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div
                class="
                    amlocator-block
                    -storelist
                    amlocator-store-list
                "
            >
                <?= $block->getLeftBlockHtml(); ?>
            </div>
        <?php endif; ?>
        <div class="amlocator-block -map">
            <div
                class="amlocator-map"
                id="<?= $block->escapeHtml($block->getMapId()); ?>"
            ></div>
        </div>
    </div>
</div>

<script>
require([
    'jquery',
    'Amasty_Storelocator/js/main',
    'Amasty_Storelocator/js/cluster',
    'domReady!',
    'mage/loader',
    'https://maps.googleapis.com/maps/api/js?libraries=places&key=<?= $block->escapeHtml(
        $block->configProvider->getApiKey()
    ); ?>'
], function ($) {
    var mapId =  "<?= '#' . $block->escapeHtml($block->getMapId()); ?>",
        $body = $('body'),
        isLoaderAjaxInitiated = !!$.data($body.get(0), 'mage-loader'),
        isLoaderInitiated = isLoaderAjaxInitiated,
        initFunction,
        tryToInit = function () {
            if (isLoaderInitiated && isLoaderAjaxInitiated) {
                initFunction();

                return true;
            }

            return false;
        };

    initFunction = function () {
        $(mapId).amLocator({
            amMediaUrl :"<?= $block->escapeHtml($block->getAmStoreMediaUrl()); ?>",
            mapZoom: <?= $block->escapeHtml($block->getMapZoom()); ?>,
            productId: "<?= (int) $block->getProductId() ?>",
            categoryId: "<?= (int) $block->getCategoryId() ?>",
            automaticLocate: "<?= (bool) $block->getAutomaticLocate(); ?>",
            enableClustering: "<?= (bool) $block->getClustering(); ?>",
            enableSuggestionClickSearch: "<?= (bool) $block->getSuggestionClickSearch(); ?>",
            enableCountingDistance: "<?= (bool) $block->getCountingDistance(); ?>",
            distanceConfig: "<?= $block->escapeHtml($block->getDistanceConfig()); ?>",
            useGeoConfig: "<?= (bool) $block->getGeoUse()?>",
            allowedCountries: <?= /* @noEscape */ $block->getAllowedCountries(); ?>,
            ajaxCallUrl: "<?= $block->escapeHtml(
                $block->getUrl('amlocator/index/ajax') . $block->getQueryString()
            ); ?>",
            useBrowserLocation: "<?= (bool) $block->getUseBrowserLocation()?>",
            jsonLocations: <?= /* @noEscape */ $block->getJsonLocations() ?>,
            imageLocations: "<?= $block->escapeHtml($block->getViewFileUrl('Amasty_Storelocator::images/')); ?>",
            mapId : "<?= $block->escapeHtml($block->getMapId()); ?>",
            mapContainerId: "<?= $block->escapeHtml($block->getMapContainerId()); ?>",
            showSearch: <?= (int) $block->getShowSearch(); ?>,
            <?php if ($block->getRadiusType() == 'range'):?>
                isRadiusSlider: <?= $block->escapeHtml($block->getRadiusType()) == 'range'?>,
                maxRadiusValue: <?= (int) $block->getMaxRadiusValue(); ?>,
                minRadiusValue: <?= (int) $block->getMinRadiusValue(); ?>,
                measurementRadius: "<?= ($block->getDistanceConfig() != 'choose') ?
                    $block->escapeHtml($block->getDistanceLabel()) : ''?>"
            <?php endif;?>
        });
    };

    tryToInit();
    $body.on('loadercreate', function () {
        isLoaderInitiated = true;
        tryToInit();
    }).on('loaderajaxcreate', function () {
        isLoaderAjaxInitiated = true;
        tryToInit();
    });
})
</script>
