<?php
/**
 * @var \Amasty\Storelocator\Block\Location $block
 * @var \Amasty\Storelocator\Model\Location $location
 */
$locations = $block->getLocationCollection();
?>
<div class="amlocator-wrapper">
    <div class="amlocator-stores-wrapper">
        <?php foreach ($locations as $location): ?>
            <div
                class="amlocator-store-desc"
                name="leftLocation"
                data-mapid="<?= $block->escapeHtmlAttr($block->getMapId()); ?>"
                data-amid="<?= (int) $location['id']; ?>"
            >
                <div
                    class="
                        amlocator-block
                        store-locator__stores
                    "
                >
                    <?php if ($baseImage = $block->getLocationImage($location)): ?>
                        <div
                            class="amlocator-image"
                            style="background-image: url('<?= $block->escapeUrl($baseImage) ?>')"
                        ></div>
                    <?php endif;?>
                    <div class="amlocator-store-information">
                        <?= $location->getStoreListHtml() ?>
                        <div
                            style="display: none;"
                            class="amasty_distance"
                            id="amasty_distance_<?= (int) $location['id'] ?>"
                        >
                            <?= $block->escapeHtml(__('Distance:')) ?>
                            <span class="amasty_distance_number"></span>
                        </div>
                    </div>
                </div>
                <?=
                $block->getLayout()
                    ->createBlock(\Amasty\Storelocator\Block\View\Schedule::class)
                    ->setData('location', $location)
                    ->toHtml();
                ?>
            </div>
        <?php endforeach; ?>
    </div>

    <?php if ($pager = $block->getPagerHtml()) : ?>
        <div class="amlocator-pager-container">
            <?= /** @escapeNotVerified */ $pager; ?>
        </div>
    <?php endif; ?>
</div>
