<?php /* @var $block \Amasty\GiftCard\Block\Customer\CardForm */ ?>
<div class="amgiftcard">
    <form
        class="form amgiftcard-form"
        id="amgiftcard-form"
        action="<?= $block->escapeUrl($block->getUrl('amgiftcard/account/addCard')) ?>"
        method="post"
        enctype="multipart/form-data"
    >
        <?= $block->getBlockHtml('formkey') ?>
        <h2 class="dashboard-items__title margin-bottom-sm">
            <?= __('Specify Gift Code') ?>
        </h2>
        <div class="fieldset margin-top-m">
            <div
                class="input required"
                data-container="change-email"
            >
                <label
                    for="am_giftcard_code"
                    class="
                        label
                        label--hidden
                        input__label
                    "
                >
                    <?= __('Enter gift card code') ?>
                </label>
                <input
                    type="text"
                    class="input__field"
                    id="am_giftcard_code"
                    name="am_giftcard_code"
                    value=""
                    required
                />
            </div>
        </div>

        <button
            type="submit"
            class="button"
            title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"
        >
            <?= __('Submit') ?>
        </button>
    </form>
</div>
