<?php /* @var $block \Amasty\GiftCard\Block\Customer\CardForm */ ?>
<div class="amgiftcard">
    <form
        class="form amgiftcard-form"
        id="amgiftcard-form"
        action="<?= $block->escapeUrl($block->getUrl('amgiftcard/account/addCard')) ?>"
        method="post"
        enctype="multipart/form-data"
    >
        <?= $block->getBlockHtml('formkey') ?>
        <h2 class="dashboard-items__title margin-bottom-sm">
            <?= $block->escapeHtml(__('Specify Gift Code')) ?>
        </h2>
        <div class="fieldset margin-top-m">
            <div
                class="input required"
                data-container="change-email"
            >
                <input
                    type="text"
                    class="input__field"
                    id="am_giftcard_code"
                    name="am_giftcard_code"
                    value=""
                />
            </div>
        </div>
        <?php
            $submitLabel = __('Submit');
        ?>
        <button
            type="submit"
            class="button"
            title="<?= $block->escapeHtmlAttr($submitLabel) ?>"
        >
            <?= $block->escapeHtml($submitLabel) ?>
        </button>
    </form>
</div>
