<?php
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar__amount" id="toolbar-amount">
    <span class="toolbar__amount-content">
        <?php if ($block->getLastPageNum() > 1): ?>
            <?= __(
                'Items %1 - %2 of %3',
                $block->getFirstNum(),
                $block->getLastNum(),
                $block->getTotalNum()
            ) ?>
        <?php elseif ($block->getTotalNum() == 1): ?>
            <?= __('%1 Item', $block->getTotalNum()) ?>
        <?php else: ?>
            <?= __('%1 Items', $block->getTotalNum()) ?>
        <?php endif ?>
    </span>
</div>
