<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

?>
<div class="toolbar__amount input__label">
    <?php if ($block->getLastPageNum() > 1): ?>
        <?php /* @escapeNotVerified */ echo __(
                'Items %1-%2 of %3',
                $block->getFirstNum(),
                $block->getLastNum(),
                $block->getTotalNum()
            )
        ?>
    <?php elseif ($block->getTotalNum() == 1): ?>
        <?php /* @escapeNotVerified */
        echo __('%1 Item', $block->getTotalNum()) ?>
    <?php else: ?>
        <?php /* @escapeNotVerified */
        echo __('%1 Items', $block->getTotalNum()) ?>
    <?php endif; ?>
</div>
