<?php
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div
    class="
        toolbar__limiter
        select
        margin-0
    "
>
    <label
        class="
            label
            select__label
            toolbar__limiter-label
            margin-right-s
            margin-bottom-0
        "
        for="limiter"
        aria-label="<?= $block->escapeHtmlAttr(__('Show number of products on the page')) ?>"
    >
        <?= $block->escapeHtml(__('Show')) ?>
    </label>
    <select
        id="limiter"
        data-role="limiter"
        class="
            select__field
            toolbar__limiter-select
        "
        name="limiter"
        data-mage-init='{
            "select": {
                "type": "number"
            }
        }'
        aria-label="<?= $block->escapeHtmlAttr(__('Show')); ?>"
    >
        <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
            <option
                value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?= ($block->isLimitCurrent($_key)) ? 'selected="selected"' : '' ?>
            >
                <?= $block->escapeHtml($_limit) ?>
            </option>
        <?php endforeach ?>
    </select>
</div>
