<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

?>
<div class="toolbar__limiter">
    <div class="input input--inline">
        <label class="input__label" for="limiter">
            <?= /* @escapeNotVerified */ __('Show') ?>
        </label>
        <select id="limiter" class="select">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                <option value="<?php /* @escapeNotVerified */ echo $_key ?>"
                    <?= $block->isLimitCurrent($_key) ? 'selected="selected"' : ''?>
                >
                    <?= /* @escapeNotVerified */ $_limit ?>
                </option>
            <?php endforeach; ?>
        </select>
        <span class="input__suffix">
            <?= /* @escapeNotVerified */ __('per page') ?>
        </span>
    </div>
</div>
