<?php
/** @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar */
?>

<div class="toolbar__limiter">
    <div class="select toolbar__limiter-wrapper">
        <label class="label toolbar__limiter-label" for="limiter">
            <?= $block->escapeHtml(__('Show')) ?>
        </label>
        <select
            id="limiter"
            data-role="limiter"
            class="select__field select__field--native toolbar__limiter-select"
            name="limiter"
            onchange="document.location.href=this.value"
            data-mage-init='{ "select": { "type": "number" } }'
        >
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                <option
                    value="<?= $block->escapeHtmlAttr($_key) ?>"
                    <?= ($block->isLimitCurrent($_key)) ? 'selected="selected"' : '' ?>
                >
                    <?= $block->escapeHtml($_limit) ?>
                </option>
            <?php endforeach ?>
        </select>
    </div>
</div>
