<?php
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($block->isEnabledViewSwitcher()): ?>
    <div class="toolbar__mode">
        <?php $_modes = $block->getModes() ?>
        <?php if ($_modes && count($_modes) > 1): ?>
            <?php foreach ($block->getModes() as $_code => $_label):
                $_modeName    = strtolower($_code);
                $_modeIconUrl = 'images/icons-sprite.svg#' . $_modeName;
            ?>
                <button
                    type="button"
                    class="
                        button
                        button--icon
                        toolbar__mode-button
                        button--icon-light
                        <?= ($block->isModeActive($_code)) ? 'toolbar__mode-button--active' : '' ?>
                    "
                    data-value="<?= $block->escapeHtmlAttr($_modeName) ?>"
                    title="<?= $block->escapeHtmlAttr($_label) ?>"
                    aria-label="<?= $block->escapeHtmlAttr($_label) ?>"
                    <?php if (!$block->isModeActive($_code)): ?>
                        id="mode-<?= $block->escapeHtmlAttr($_modeName) ?>"
                        data-role="mode-switcher"
                    <?php endif ?>
                >
                    <svg
                        class="
                            icon
                            toolbar__mode-icon
                        "
                        role="presentation"
                        focusable="false"
                    >
                        <title><?= $block->escapeHtml($_modeName) ?></title>
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl($_modeIconUrl)) ?>"></use>
                    </svg>
                </button>
            <?php endforeach ?>
        <?php endif ?>
    </div>
<?php endif ?>
