<?php
/**
 * @var \Magento\CompanyShipping\Block\Company\Profile\ShippingMethod $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="dashboard-items">
    <h2
        class="
            dashboard-items__title
            margin-bottom-sm
        "
    >
        <?= $escaper->escapeHtml(__('Shipping Information')) ?>
    </h2>
    <div class="row">
        <div
            class="
                dashboard-items__item
                col-sm-6
            "
        >
            <?php if ($block->hasShippingMethods()): ?>
                <div class="company-profile-shipping-methods">
                    <h3
                        id="shipping-method-label"
                        class="
                            dashboard-items__subtitle
                            margin-bottom-l
                        "
                    >
                        <?= $escaper->escapeHtml(__('Available Shipping Methods')) ?>
                    </h3>
                    <ul
                        class="
                            shipping-methods-list
                            list
                            list--native
                        "
                        aria-labelledby="shipping-method-label"
                    >
                        <?php foreach ($block->getShippingMethods() as $shippingMethod): ?>
                            <li class="list__item">
                                <?= $escaper->escapeHtml($shippingMethod) ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php else: ?>
                <div class="message message-notice notice">
                    <div data-ui-id="messages-message-notice">
                        <?= $escaper->escapeHtml(
                            __('This company has no shipping methods. Please contact store administrator.')
                        ) ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
