<?php
/** @var \Magento\Wishlist\Block\Item\Configure $block */
?>
<?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()): ?>
    <button
        class="
            button
            button--secondary
            product-view__update-wishlist
            action
            towishlist
            updated
        "
        data-post='<?= /* @noEscape */ $block->getUpdateParams() ?>'
        data-action="add-to-wishlist"
    >
        <?= $block->escapeHtml(__('Update Wish List')) ?>
    </button>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getWishlistOptions()) ?>
        }
    }
</script>
