<?php
/** @var \Magento\Wishlist\Block\Item\Configure $block */
?>
<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
    <button
        class="
            button
            button--secondary
            product-view__update-wishlist
            action
            towishlist
            updated
        "
        data-post='<?= $block->getUpdateParams() ?>'
        data-action="add-to-wishlist"
    >
        <?= __('Update Wish List') ?>
    </button>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions()) ?>
        }
    }
</script>
