<?php if ($block->getShowBanner()): ?>
    <?php
    $collection = $block->getCollection();
    ?>
    <?php if ($collection->getSize()): ?>
        <div class="container">
            <?php foreach ($collection as $content) : ?>
                <?php
                $bannerUrl = $content->getData('hps_ban_url');
                $bannerAlt = $content->getData('hps_ban_alt');

                $bannerDefault = $content->getFile('hps_ban_image_default');
                $banner480 =
                    $content->getData('hps_ban_image_max_480') ? $content->getFile('hps_ban_image_max_480') : false;
                $banner768 =
                    $content->getData('hps_ban_image_max_768') ? $content->getFile('hps_ban_image_max_768') : false;
                $banner1024 =
                    $content->getData('hps_ban_image_max_1024') ? $content->getFile('hps_ban_image_max_1024') : false;
                $banner1328 =
                    $content->getData('hps_ban_image_max_1328') ? $content->getFile('hps_ban_image_max_1328') : false;
                $bannerFull =
                    $content->getData('hps_ban_image_full') ? $content->getFile('hps_ban_image_full') : false;
                ?>

                <?php $block->getChildBlock('banner-picture')->setData([
                    'picture_class' => 'banner__image',
                    'picture_full_url' => true,
                    'img_default' => $bannerDefault,
                    'img_480' => $banner480,
                    'img_768' => $banner768,
                    'img_1024' => $banner1024,
                    'img_1328' => $banner1328,
                    'img_full' => $bannerFull,
                    'banner_alt' => $bannerAlt
                ]);
                ?>
                <<?= $bannerUrl ? 'a href="' . $block->escapeUrl($bannerUrl) . '"' : 'div' ?>
                    class="banner <?= $block->escapeHtmlAttr($block->getBannerClass()) ?>"
                >
                    <?= $block->getChildHtml('banner-picture', false); ?>
                </<?= $block->escapeUrl($bannerUrl) ? 'a' : 'div' ?>>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
