<form
    id="form-validate"
    class="dashboard-form form"
    action="<?= $block->getUrl('customer/account/editPost') ?>"
    method="post"
    enctype="multipart/form-data"
    data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
    autocomplete="off"
>
    <?= $block->getBlockHtml('formkey') ?>

    <h3 class="dashboard-form__title">
        <?= $escaper->escapeHtml(__('Account Information')) ?>
    </h3>

    <div class="dashboard-form__divider">
        <?=
            $block->getLayout()
                ->createBlock('Magento\Customer\Block\Widget\Name')
                ->setObject($block->getCustomer())
                ->toHtml()
        ?>

        <?php
            $_dob    = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class);
            $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class);
            $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class);
        ?>

        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>

        <div class="checkbox dashboard-form__divider">
            <input
                id="change-email"
                class="checkbox__field"
                type="checkbox"
                name="change_email"
                data-role="change-email"
                value="1"
                title="<?= $escaper->escapeHtmlAttr(__('Change Email')) ?>"
            >

            <svg class="checkbox__icon">
                <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked')); ?>"></use>
            </svg>

            <label class="checkbox__label" for="change-email">
                <?= $escaper->escapeHtmlAttr(__('Change Email')) ?>
            </label>
        </div>

        <div class="checkbox dashboard-form__divider">
            <input
                id="change-password"
                class="checkbox__field"
                type="checkbox"
                name="change_password"
                data-role="change-password"
                value="1"
                title="<?= $escaper->escapeHtmlAttr(__('Change Password')) ?>"
                <?php if ($block->getChangePassword()): ?>
                    checked="checked"
                <?php endif; ?>
            >

            <svg class="checkbox__icon">
                <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked')); ?>"></use>
            </svg>

            <label class="checkbox__label" for="change-password">
                <?= $escaper->escapeHtmlAttr(__('Change Password')) ?>
            </label>
        </div>

        <div
            class="dashboard-form__divider dashboard-form__fields"
            data-container="change-email-password"
        >
            <h4 class="dashboard-form__title-form dashboard-form__divider">
                <span data-title="change-email-password">
                    <?= $escaper->escapeHtmlAttr(__('Change Email and Password')) ?>
                </span>
            </h4>

            <div
                class="input email required"
                data-container="change-email"
            >
                <label class="label" for="email">
                    <?= $escaper->escapeHtml(__('Email')) ?>
                </label>

                <input
                    id="email"
                    class="input__field"
                    name="email"
                    type="email"
                    autocomplete="email"
                    data-input="change-email"
                    value="<?= $escaper->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"
                    title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                    data-validate="{required:true, 'validate-email':true}"
                >
            </div>

            <div class="input password required">
                <label class="label" for="current-password">
                    <?= $escaper->escapeHtml(__('Current Password')) ?>
                </label>

                <input
                    id="current-password"
                    class="input__field"
                    type="password"
                    name="current_password"
                    data-input="current-password"
                    autocomplete="off"
                >
            </div>

            <div
                class="input dashboard-form--hidden newPassword required"
                data-container="new-password"
                data-mage-init='{
                    "passwordStrengthIndicator": {
                        "defaultClassName": "password-strength--"
                    }
                }'
            >
                 <?php
                    $getMinPasswordLength = $escaper->escapeHtml($block->getMinimumPasswordLength());
                    $getMaxPasswordLength = $escaper->escapeHtml($block->getRequiredCharacterClassesNumber());
                 ?>

                <label class="label" for="password">
                    <?= $escaper->escapeHtml(__('New Password')) ?>
                </label>

                <input
                    id="password"
                    class="input__field"
                    type="password"
                    name="password"
                    data-password-min-length="<?= $escaper->escapeHtmlAttr($getMinPasswordLength); ?>"
                    data-password-min-character-sets="<?= $escaper->escapeHtmlAttr($getMaxPasswordLength); ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off"
                >
                <div class="password-strength">
                    <div
                        class="password-none"
                        data-role="password-strength-meter"
                    >
                        <div class="password-strength__handle">
                            <?= $escaper->escapeHtml(__('Password Strength')); ?>:
                            <span
                                class="password-strength__indicator"
                                data-role="password-strength-meter-label"
                                aria-live="polite"
                            >
                                <?= $escaper->escapeHtml(__('No Password')); ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div
                class="input confirmPassword required"
                data-container="confirm-password"
            >
                <label class="label" for="password-confirmation">
                    <?= $escaper->escapeHtml(__('Confirm New Password')) ?>
                </label>

                <input
                    id="password-confirmation"
                    class="input__field"
                    type="password"
                    name="password_confirmation"
                    data-input="confirm-password"
                    autocomplete="off"
                >
            </div>

            <?= $block->getChildHtml('form_additional_info'); ?>
        </div>
    </div>

    <div class="action">
        <div class="action__handler">
            <button
                type="submit"
                class="button action__button"
                title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>"
            >
                <?= $escaper->escapeHtml(__('Save')) ?>
            </button>
        </div>

        <div class="action__handler">
            <a
                class="action__link"
                href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"
            >
                <?= $escaper->escapeHtml(__('Go back')) ?>
            </a>
        </div>
    </div>
</form>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?= $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= __('Change Email') ?>",
                "titleChangePassword": "<?= __('Change Password') ?>",
                "titleChangeEmailAndPassword": "<?= __('Change Email and Password') ?>"
            }
        }
    }
</script>
