<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong
?>
<div class="container auth">
    <div class="auth__links auth__links--registration">
        <a
            href="<?= $block->escapeUrl($block->getUrl('customer/account/login')); ?>"
            class="
                button
                button--link
                auth__link
            "
        >
            <?= $block->escapeHtml(__('Login')) ?>
            <svg
                class="icon auth__icon"
                aria-hidden="true"
            >
                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#expand-down')); ?>"></use>
            </svg>
        </a>
        <button
            class="
                button
                button--link
                auth__link
                auth__link--active
            "
        >
            <?= $block->escapeHtml(__('Create account')) ?>
            <svg
                class="icon auth__icon"
                aria-hidden="true"
            >
                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#expand-down')); ?>"></use>
            </svg>
        </button>
    </div>
    <div class="account-form">
        <p class="account-form__info">
            <?= $block->escapeHtml(__('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.')) ?>
        </p>
        <?= $block->getChildHtml('form_fields_before') ?>
        <?php /* Extensions placeholder */ ?>
        <?= $block->getChildHtml('customer.form.register.extra') ?>
        <form
            class="account-form__form"
            action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
            method="post"
            id="form-validate"
            enctype="multipart/form-data"
        >
            <?= /* @noEscape */ $block->getChildHtml('form_fields_before_in_form') ?>
            <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
            <fieldset
                class="
                    fieldset
                    account-form__fieldset
                "
            >
                <legend
                    class="
                        fieldset__legend
                        account-form__legend
                    "
                >
                    <?= $block->escapeHtml(__('Personal Information')) ?>
                </legend>
                <input
                    type="hidden"
                    name="success_url"
                    value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>"
                />
                <input
                    type="hidden"
                    name="error_url"
                    value="<?= $block->escapeUrl($block->getErrorUrl()) ?>"
                />
                <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

                <?php if ($block->isNewsletterEnabled()): ?>
                <div
                    class="
                        checkbox
                        account-form__newsletter-checkbox
                    "
                >
                    <input
                        type="checkbox"
                        name="is_subscribed"
                        title="<?= $block->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>"
                        value="1"
                        id="is_subscribed"
                        <?= ($block->getFormData()->getIsSubscribed()) ? 'checked="checked"' : '' ?>
                        class="
                            checkbox__field
                            account-form__newsletter-checkbox-field
                        "
                    />
                    <svg
                        class="
                            checkbox__icon
                            checkbox__icon--checked
                        "
                        role="presentation"
                        focusable="false"
                    >
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
                    </svg>
                    <svg
                        class="
                            checkbox__icon
                            checkbox__icon--unchecked
                        "
                        role="presentation"
                        focusable="false"
                    >
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
                    </svg>
                    <label
                        for="is_subscribed"
                        class="
                            checkbox__label
                            account-form__newsletter-checkbox-label
                        "
                    >
                        <?= $block->escapeHtml(__('Sign Up for Newsletter')) ?>
                    </label>
                </div>
                    <?php /* Extensions placeholder */ ?>
                    <?= $block->getChildHtml('customer.form.register.newsletter') ?>
                <?php endif ?>

                <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
                <?php if ($_dob->isEnabled()): ?>
                    <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                <?php endif ?>

                <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
                <?php endif ?>

                <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
                <?php if ($_gender->isEnabled()): ?>
                    <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                <?php endif ?>

                <?php $customerAttributes = $block->getChildBlock('customer_form_user_attributes');?>
                <?php if ($customerAttributes): ?>
                    <?php $customerAttributes->setObject($block->getFormData())->setEntityType('customer')->setShowContainer(false);?>
                    <?php $block->restoreSessionData($customerAttributes->getMetadataForm());?>
                    <?= $customerAttributes->toHtml() ?>
                <?php endif;?>
            </fieldset>
        <?php if ($block->getShowAddressFields()): ?>
            <fieldset
                class="
                    fieldset
                    account-form__fieldset
                "
            >
                <legend
                    class="
                        fieldset__legend
                        account-form__legend
                    "
                >
                    <?= $block->escapeHtml(__('Address Information')) ?>
                </legend>
                <input
                    type="hidden"
                    name="create_address"
                    value="1"
                />
                <div class="input account-form__input">
                    <label
                        for="company"
                        class="label"
                    >
                        <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('company') ?>
                    </label>
                    <input
                        type="text"
                        name="company"
                        id="company"
                        value="<?= $block->escapeHtmlAttr($block->getFormData()->getCompany()) ?>"
                        title="<?= $block->escapeHtmlAttr(__('Company')) ?>"
                        class="
                            input__field
                            <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('company') ?>
                        "
                    />
                </div>
                <div
                    class="
                        input
                        account-form__input
                        required
                    "
                >
                    <label
                        for="telephone"
                        class="label"
                    >
                        <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('telephone') ?>
                    </label>
                    <input
                        type="text"
                        name="telephone"
                        id="telephone"
                        value="<?= $block->escapeHtmlAttr($block->getFormData()->getTelephone()) ?>"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('telephone') ?>"
                        class="
                            input__field
                            <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('telephone') ?>"
                        />
                </div>

                <?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>

                <div
                    class="
                        input
                        account-form__input
                        required
                    "
                >
                    <label
                        for="street_1"
                        class="label"
                    >
                        <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>
                    </label>
                    <input
                        type="text"
                        name="street[]"
                        value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreetLine(1)) ?>"
                        title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                        id="street_1"
                        class="
                            input__field
                            <?= /* @noEscape */ $_streetValidationClass ?>
                        "
                    />
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <div
                            class="
                                input
                                account-form__input
                            "
                        >
                            <label
                                class="label"
                                for="street_<?= /* @noEscape */ $_i ?>"
                            >
                                <?= $block->escapeHtml(__('Street Address %1', $_i)) ?>
                            </label>
                            <input
                                type="text"
                                name="street[]"
                                value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreetLine($_i - 1)) ?>"
                                title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>"
                                id="street_<?= /* @noEscape */ $_i ?>"
                                class="
                                    input__field
                                    <?= /* @noEscape */ $_streetValidationClass ?>"
                                />
                        </div>
                    <?php endfor; ?>
                <div
                    class="
                        input
                        account-form__input
                        required
                    "
                >
                    <label
                        for="city"
                        class="label"
                    >
                        <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>
                    </label>
                        <input
                            type="text"
                            name="city"
                            value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>"
                            title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                            class="input__field <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city') ?>"
                            id="city"
                        />
                </div>

                <div
                    class="
                        select
                        select--native
                        account-form__input
                        required
                    "
                >
                    <label
                        for="region_id"
                        class="label"
                    >
                        <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>
                    </label>
                    <select
                        id="region_id"
                        name="region_id"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                        class="
                            select__field
                            validate-select
                            region_id
                            display-none
                        "
                    >
                        <option value="">
                            <?= $block->escapeHtml(__('Please select a region, state or province.')) ?>
                        </option>
                    </select>
                    <input
                        type="text"
                        id="region"
                        name="region"
                        value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                        class="
                            input__field
                            display-none
                            <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region') ?>"
                        />
                </div>

                <div class="input required">
                    <label
                        for="zip"
                        class="label"
                    >
                        <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>
                    </label>
                    <input
                        type="text"
                        name="postcode"
                        value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                        id="zip"
                        class="
                            input__field
                            validate-zip-international
                            <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode') ?>
                        "
                        data-validate="{'required':true, 'validate-zip-international':true}"
                    />
                </div>

                <div class="select required">
                    <label
                        for="country"
                        class="label"
                    >
                        <?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?>
                    </label>
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
                    <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                    <?php if ($addressAttributes): ?>
                        <?php $addressAttributes->setEntityType('customer_address'); ?>
                        <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                        <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                        <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
                    <?php endif;?>
                <input
                    type="hidden"
                    name="default_billing"
                    value="1"
                />
                <input
                    type="hidden"
                    name="default_shipping"
                    value="1"
                />
            </fieldset>

        <?php endif; ?>
            <fieldset
                class="
                    fieldset
                    account-form__fieldset
                "
                data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
            >
                <legend class="account-form__legend">
                    <?= $block->escapeHtml(__('Sign-in Information')) ?>
                </legend>
                <div class="input required">
                    <label
                        for="email_address"
                        class="label"
                    >
                        <?= $block->escapeHtml(__('Email')) ?>
                    </label>
                    <input
                        type="email"
                        name="email"
                        id="email_address"
                        autocomplete="email"
                        value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>"
                        title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                        class="input__field"
                        data-validate="{required:true, 'validate-email':true}"
                    />
                </div>
                <div
                    data-mage-init='{
                        "passwordStrengthIndicator": {
                            "defaultClassName": "password-strength--"
                        }
                    }'
                >
                    <div
                        class="
                            input
                            input--password
                            required
                        "
                    >
                        <label
                            for="password"
                            class="label input__label"
                        >
                            <?= $block->escapeHtml(__('Password')) ?>
                        </label>
                        <input
                            type="password"
                            name="password"
                            id="password"
                            title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                            class="input__field"
                            data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                            data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                            data-validate="{required:true, 'validate-customer-password':true}"
                            autocomplete="off"
                        />
                        <button
                            type="button"
                            class="
                                button
                                button--icon
                                input__button-pass
                            "
                            aria-label="<?= $block->escapeHtmlAttr(__('Show/hide password')) ?>"
                            data-mage-init='{"passwordTrigger": {}}'
                        >
                            <svg
                                class="
                                    icon
                                    icon--secondary
                                    input__button-pass-icon-view
                                "
                                role="presentation"
                                focusable="false"
                            >
                                <title><?= $block->escapeHtml(__('View password icon')) ?></title>
                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#visibility-off')); ?>"></use>
                            </svg>

                            <svg
                                class="
                                    icon
                                    icon--secondary
                                    input__button-pass-icon-hide
                                "
                                role="presentation"
                                focusable="false"
                            >
                                <title><?= $block->escapeHtml(__('Hide password icon')) ?></title>
                                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#visibility')); ?>"></use>
                            </svg>
                        </button>
                    </div>
                    <div class="password-strength margin-bottom-m">
                        <div
                            class="password-none"
                            data-role="password-strength-meter"
                        >
                            <div class="password-strength__handle">
                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                <span
                                    class="password-strength__indicator"
                                    data-role="password-strength-meter-label"
                                    aria-live="polite"
                                >
                                    <?= $block->escapeHtml(__('No Password')) ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    class="
                        input
                        input--password
                        required
                    "
                >
                    <label
                        for="password-confirmation"
                        class="label input__label"
                    >
                        <?= $block->escapeHtml(__('Confirm Password')) ?>
                    </label>
                    <input
                        type="password"
                        name="password_confirmation"
                        title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>"
                        id="password-confirmation"
                        class="input__field"
                        data-validate="{required:true, equalTo:'#password'}"
                    />
                    <button
                        type="button"
                        class="
                            button
                            button--icon
                            input__button-pass
                        "
                        aria-label="<?= $block->escapeHtmlAttr(__('Show/hide password')) ?>"
                    >
                        <svg
                            class="
                                icon
                                icon--secondary
                                input__button-pass-icon-view
                            "
                            role="presentation"
                            focusable="false"
                        >
                            <title><?= $block->escapeHtml(__('View password icon')) ?></title>
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#visibility-off')); ?>"></use>
                        </svg>

                        <svg
                            class="
                                icon
                                icon--secondary
                                input__button-pass-icon-hide
                            "
                            role="presentation"
                            focusable="false"
                        >
                            <title><?= $block->escapeHtml(__('Hide password icon')) ?></title>
                            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#visibility')); ?>"></use>
                        </svg>
                    </button>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
            </fieldset>
            <div class="account-form__actions">
                <button
                    type="submit"
                    class="button account-form__button"
                    title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>"
                >
                    <?= $block->escapeHtml(__('Create an Account')) ?>
                </button>
                <a
                    class="link margin-top-m"
                    href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
                >
                    <?= $block->escapeHtml(__('Back')) ?>
                </a>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        <?php if ($block->getShowAddressFields()): ?>
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ ($block->getConfig("general/region/display_all") ? "true" : "false") ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        },
        <?php endif; ?>
        "*": {
            "Magento_CustomerCustomAttributes/validation": {
                "ignore": <?= (int) ($_dob->isEnabled() || $customerAttributes->hasUserDefinedAttributes()) ?>,
                "hasUserDefinedAttributes": <?= (int) $customerAttributes->hasUserDefinedAttributes() ?>,
                "isDobEnabled": <?= (int) $_dob->isEnabled() ?>,
                "disableAutoComplete": true,
                "mixins": [
                    "Magento_CustomerCustomAttributes/error-placement",
                    "Magento_CustomerCustomAttributes/validation-ignore"
                ]
            }
        },
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>

<script>
    require([
        'jquery',
        'mage/mage'
    ], function($) {
        var dataForm = $('#form-validate'),
            ignore = <?= $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()): ?>
                errorPlacement: function(error, element) {
                    if (element.prop('id').search('full') !== -1) {
                        var dobElement = $(element).parents('.customer-dob'),
                            errorClass = error.prop('class');
                        error.insertAfter(element.parent());
                        dobElement.find('.validate-custom').addClass(errorClass)
                            .after('<div class="' + errorClass + '"></div>');
                    } else {
                        error.insertAfter(element);
                    }
                },
                ignore: ':hidden:not(' + ignore + ')'
            <?php else: ?>
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            <?php endif ?>
        });
    });
</script>
