<?php
    $addressHelper = $this->helper('Magento\Customer\Helper\Address');
?>

<div class="row registration">
    <?= $block->getChildHtml('form_fields_before') ?>
    <?php /* Extensions placeholder */ ?>
    <?= $block->getChildHtml('customer.form.register.extra') ?>
    <form
        class="
            col-xs-12
            col-md-6
            registration__content
        "
        action="<?= $block->getPostActionUrl() ?>"
        method="post"
        id="form-validate"
        enctype="multipart/form-data"
        autocomplete="off"
    >
        <?= $block->getBlockHtml('formkey'); ?>
        <fieldset class="fieldset registration__fieldset">
            <legend class="fieldset__legend registration__legend">
                <?= $block->escapeHtml(__('Personal Information')) ?>
            </legend>
            <div class="divider registration__divider"></div>
            <input type="hidden"
                   name="success_url"
                   value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>"
            >
            <input type="hidden"
                   name="error_url"
                   value="<?= $block->escapeUrl($block->getErrorUrl()) ?>"
            >
            <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
            <?php if ($block->isNewsletterEnabled()): ?>
                <div class="checkbox">
                    <input type="checkbox"
                           name="is_subscribed"
                           title="<?= $block->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>"
                           value="1"
                           id="is_subscribed"
                           class="checkbox__field"
                        <?= ($block->getFormData()->getIsSubscribed()) ? 'checked="checked"' : '' ?>
                    >
                    <svg class="checkbox__icon">
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
                    </svg>
                    <label for="is_subscribed" class="checkbox__label">
                        <?= $block->escapeHtml(__('Sign Up for Newsletter')) ?>
                    </label>
                </div>
                <?php /* Extensions placeholder */ ?>
                <?= $block->getChildHtml('customer.form.register.newsletter') ?>
            <?php endif ?>

            <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
            <?php if ($_dob->isEnabled()): ?>
                <?= $_dob->setDate($block->getFormData()->getDob())
                    ->setHtmlClass('input__field')
                    ->toHtml();
                ?>
            <?php endif ?>

            <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
            <?php endif ?>

            <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
            <?php if ($_gender->isEnabled()): ?>
                <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
            <?php endif ?>
        </fieldset>
        <?php if ($block->getShowAddressFields()): ?>
            <fieldset class="form__fieldset">
                <legend class="form__legend">
                    <?= $block->escapeHtml(__('Address Information')) ?>
                </legend>
                <input type="hidden" name="create_address" value="1"/>
                <div class="input">
                    <label for="company" class="input__label">
                        <?= $block->escapeHtml(__('Company')) ?>
                    </label>
                    <input type="text"
                           name="company"
                           id="company"
                           value="<?= $block->escapeHtmlAttr($block->getFormData()->getCompany()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Company')) ?>"
                           class="input__field <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('company')) ?>"
                    >
                </div>
                <div class="input">
                    <label for="telephone" class="input__label">
                        <?= $block->escapeHtml(__('Phone Number')) ?>
                    </label>
                    <input type="text"
                           name="telephone"
                           id="telephone"
                           value="<?= $block->escapeHtmlAttr($block->getFormData()->getTelephone()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                           class="input__field <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('telephone')) ?>"
                    >
                </div>

                <?php $_streetValidationClass = $addressHelper->getAttributeValidationClass('street'); ?>

                <div class="input required">
                    <label for="street_1" class="input__label">
                        <?= $block->escapeHtml(__('Street Address')) ?>
                    </label>
                    <input type="text"
                           name="street[]"
                           value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                           id="street_1"
                           class="input__field <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"
                    >
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $addressHelper->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="input">
                                <label class="input__label"
                                       for="street_<?= /* @noEscape */ $_i ?>"
                                >
                                    <?= $block->escapeHtml(__('Address')) ?>
                                </label>
                                <input type="text"
                                       name="street[]"
                                       value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreetLine($_i - 1)) ?>"
                                       title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>"
                                       id="street_<?= /* @noEscape */ $_i ?>"
                                       class="input__field <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"
                                >
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>

                <div class="input required">
                    <label for="city" class="input__label">
                        <?= $block->escapeHtml(__('City')) ?>
                    </label>
                    <input type="text" name="city"
                           value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                           class="input__field <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('city')) ?>"
                           id="city"
                    >
                </div>

                <div class="input required">
                    <label for="region_id" class="input__label">
                        <?= $block->escapeHtml(__('State/Province')) ?>
                    </label>
                    <select id="region_id"
                            name="region_id"
                            title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                            class="select validate-select"
                            style="display:none;"
                    >
                        <option value="">
                            <?= $block->escapeHtml(__('Please select a region, state or province.')) ?>
                        </option>
                    </select>
                    <input type="text"
                           id="region"
                           name="region"
                           value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                           class="input__field <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('region')) ?>"
                           style="display:none;"
                    >
                </div>

                <div class="input required">
                    <label for="zip" class="input__label">
                        <?= $block->escapeHtml(__('Zip/Postal Code')) ?>
                    </label>
                    <input type="text"
                           name="postcode"
                           value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>"
                           id="zip"
                           class="input__field validate-zip-international <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('postcode')) ?>"
                    >
                </div>

                <div class="input required">
                    <label for="country" class="input__label">
                        <?= $block->escapeHtml(__('Country')) ?>
                    </label>
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
                <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes'); ?>
                <?php if ($addressAttributes): ?>
                    <?php $addressAttributes->setEntityType('customer_address'); ?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
                    <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address'); ?>
                    <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
                <?php endif; ?>
                <input type="hidden" name="default_billing" value="1">
                <input type="hidden" name="default_shipping" value="1">
            </fieldset>

        <?php endif; ?>

        <fieldset class="fieldset registration__fieldset"
                  data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
        >
            <legend class="fieldset__legend registration__legend">
                <?= $block->escapeHtml(__('Sign-in Information')) ?>
            </legend>
            <div class="divider registration__divider"></div>
            <div class="input required">
                <label for="email_address"
                       class="input__label"
                >
                    <?= $block->escapeHtml(__('Email')) ?>
                </label>
                <input type="email"
                       name="email"
                       autocomplete="email"
                       id="email_address"
                       value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>"
                       title="<?= $block->escapeHtml(__('Email')) ?>"
                       class="input__field"
                       data-validate="{required:true, 'validate-email':true}"
                >
            </div>
            <div
                class="registration__password-wrapper"
                data-mage-init='{
                    "passwordStrengthIndicator": {
                        "defaultClassName": "password-strength--"
                    }
                }'
            >
                <div
                    class="
                        input
                        password
                        register__password
                        required
                    "
                >
                    <label
                        for="password"
                        class="input__label"
                    >
                        <?= $block->escapeHtml(__('Password')) ?>
                    </label>
                    <input
                        type="password"
                        name="password"
                        id="password"
                        title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                        class="input__field"
                        data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                        data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                        data-validate="{required:true, 'validate-customer-password':true}"
                        autocomplete="off"
                    >
                </div>
                <div class="password-strength">
                    <div
                        class="password-none"
                        data-role="password-strength-meter"
                    >
                        <div class="password-strength__handle">
                            <?= $block->escapeHtml(__('Password Strength')); ?>:
                            <span
                                class="password-strength__indicator"
                                data-role="password-strength-meter-label"
                                aria-live="polite"
                            >
                                <?= $block->escapeHtml(__('No Password')); ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="input required">
                <label for="password-confirmation" class="input__label">
                    <?= $block->escapeHtml(__('Confirm Password')) ?>
                </label>
                <input type="password"
                       name="password_confirmation"
                       title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>"
                       id="password-confirmation"
                       class="input__field"
                       data-validate="{required:true, equalTo:'#password'}"
                       autocomplete="off"
                >
            </div>
            <?= $block->getChildHtml('form_additional_info'); ?>
        </fieldset>
        <button type="submit"
                class="button"
                title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>"
        >
            <?= $block->escapeHtml(__('Create an Account')) ?>
        </button>
    </form>
</div>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($) {

        var dataForm = $('#form-validate');
        var ignore = <?= $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore        : ':hidden:not(' + ignore + ')'
            <?php else: ?>
            ignore        : ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            <?php endif ?>
        }).find('input:text').attr('autocomplete', 'off');

    });
</script>
<?php if ($block->getShowAddressFields()): ?>
    <script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= ($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?= $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }

    </script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".input.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form"
            }
        }
    }
</script>
