<?php
/**
 * @var \Magento\Paypal\Block\Express\Review $block
 */
?>
<div class="paypal-review">
    <div
        class="
            payapal-review__details
            row
            margin-bottom-m
        "
    >
        <div class="block-content">
            <?php if ($block->getShippingAddress()) : ?>
                <div
                    class="
                        payapal-review__details-item
                        col-lg-4
                        margin-right-auto
                        margin-bottom-m
                    "
                >
                    <form
                        method="post"
                        id="shipping-method-form"
                        action="<?= $block->escapeUrl($block->getShippingMethodSubmitUrl()) ?>"
                        class="form"
                    >
                        <fieldset class="fieldset">
                            <legend class="fieldset__legend fieldset__legend--hidden">
                                <?= $block->escapeHtml(__('Shipping Method')) ?>
                            </legend>
                            <?php if ($block->canEditShippingMethod()) : ?>
                                <?php if ($groups = $block->getShippingRateGroups()) : ?>
                                    <?php $currentRate = $block->getCurrentShippingRate(); ?>
                                    <label
                                        class="label"
                                        for="shipping-method"
                                    >
                                        <?= $block->escapeHtml(__('Shipping Method')) ?>
                                    </label>
                                    <div class="control">
                                        <div
                                            class="
                                                select
                                                select--native
                                                field
                                                shipping
                                                required
                                            "
                                            required
                                        >
                                            <select
                                                name="shipping_method"
                                                id="shipping-method"
                                                class="select__field"
                                            >
                                                <?php if (!$currentRate) : ?>
                                                    <option value="">
                                                        <?= $block->escapeHtml(__('Please select a shipping method...')); ?>
                                                    </option>
                                                <?php endif; ?>
                                                <?php foreach ($groups as $code => $rates) : ?>
                                                    <optgroup
                                                        label="<?= $block->escapeHtmlAttr($block->getCarrierName($code)); ?>"
                                                    >
                                                        <?php foreach ($rates as $rate) : ?>
                                                            <option
                                                                value="
                                                                    <?=
                                                                        $block->escapeHtml(
                                                                            $block->renderShippingRateValue($rate)
                                                                        );
                                                                    ?>
                                                                "
                                                                <?= ($currentRate === $rate) ? ' selected="selected"' : ''; ?>
                                                            >
                                                                <?= /* @noEscape */ $block->renderShippingRateOption($rate); ?>
                                                            </option>
                                                        <?php endforeach; ?>
                                                    </optgroup>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="actions-group">
                                        <div class="actions-group__handler">
                                            <button
                                                id="update-shipping-method-submit"
                                                type="submit"
                                                class="
                                                    button
                                                    actions-group__button
                                                    action
                                                    update
                                                    primary
                                                "
                                            >
                                                <?= $block->escapeHtml(__('Update Shipping Method')) ?>
                                            </button>
                                        </div>
                                    </div>
                                <?php else : ?>
                                    <p>
                                        <?= $block->escapeHtml(__('Sorry, no quotes are available for this order right now.')); ?>
                                    </p>
                                <?php endif; ?>
                            <?php else : ?>
                                <p>
                                    <?= /* @noEscape */ $block->renderShippingRateOption(
                                        $block->getCurrentShippingRate()
                                    ); ?>
                                </p>
                            <?php endif; ?>
                        </fieldset>
                    </form>
                </div>
                <div
                    class="
                        payapal-review__details-item
                        col-lg-3
                        margin-bottom-m
                    "
                >
                    <h2 class="heading--third-level">
                        <?= $block->escapeHtml(__('Shipping Address')) ?>
                    </h2>
                    <div class="shipping-address-details box-content">
                        <address>
                            <?= $block->escapeHtml($block->renderAddress($block->getShippingAddress()), ['br']);?>
                        </address>
                    </div>
                    <?php if ($block->getCanEditShippingAddress()) : ?>
                        <div class="actions-group">
                            <div class="actions-group__handler">
                                <a
                                    href="<?= $block->escapeUrl($block->getEditUrl()) ?>"
                                    class="
                                        actions-group__link
                                        padding-top-xs
                                        action
                                        edit
                                    "
                                >
                                    <?= $block->escapeHtml(__('Edit')) ?>
                                </a>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <div
                class="
                    payapal-review__details-item
                    col-lg-3
                    margin-bottom-m
                "
            >
                <h2 class="heading--third-level">
                    <?= $block->escapeHtml(__('Payment Method')) ?>
                </h2>
                <div class="box-content">
                    <?= $block->escapeHtml($block->getPaymentMethodTitle()) ?>
                    <br>
                    <?= $block->escapeHtml($block->getEmail()) ?>
                </div>
                <?php if ($block->getEditUrl()) : ?>
                    <div class="actions-group">
                        <div class="actions-group__handler">
                            <a
                                href="<?= $block->escapeUrl($block->getEditUrl()) ?>"
                                class="
                                    actions-group__link
                                    padding-top-xs
                                    action
                                    edit
                                "
                            >
                                <?= $block->escapeHtml(__('Edit Payment Information')) ?>
                            </a>
                        </div>
                    </div>
                <?php endif ?>
            </div>
        </div>
    </div>

    <div
        class="
            paypal-review__discount
            row
            margin-bottom-xl
        "
    >
        <div class="col-lg-5">
            <?= $block->getChildHtml('paypal.additional.actions') ?>
        </div>
    </div>

    <div class="payapal-review__shopping-cart">
        <h2 class="heading--third-level">
            <?= $block->escapeHtml(__('Items in your shopping cart')) ?>
        </h2>
        <div class="actions-group">
            <div class="actions-group__handler">
                <a
                    href="<?= $block->escapeUrl($block->getEditUrl()) ?>"
                    class="actions-group__link padding-top-0 action edit"
                >
                    <?= $block->escapeHtml(__('Edit Shopping Cart')) ?>
                </a>
            </div>
        </div>
        <?= $block->getChildHtml('details') ?>

        <form
            method="post"
            id="order-review-form"
            action="<?= $block->escapeUrl($block->getPlaceOrderUrl()) ?>"
            class="form order-review-form"
        >
            <?= $block->getChildHtml('agreements') ?>
            <button
                type="button"
                id="review-button"
                class="
                    button
                    button button--fluid
                    margin-top-m
                    action
                    checkout
                    primary
                "
                value="<?= $block->escapeHtmlAttr(__('Place Order')) ?>"
            >
                <?= $block->escapeHtml(__('Place Order')) ?>
            </button>
            <span
                class="please-wait load indicator"
                id="review-please-wait"
                style="display: none;"
                data-text="<?= $block->escapeHtmlAttr(__('Submitting order information...')) ?>"
            >
                <?= $block->escapeHtml(__('Submitting order information...')) ?>
            </span>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#order-review-form": {
            "validation": {},
            "orderReview": {
                "shippingSubmitFormSelector": "#shipping-method-form",
                "shippingSelector": "#shipping-method",
                "shippingMethodUpdateUrl": "<?= $block->escapeUrl($block->getUpdateShippingMethodsUrl()) ?>",
                "isAjax": <?= /* @noEscape */ $block->getUseAjax() ? 'true' : 'false' ?>,
                "canEditShippingMethod": <?= /* @noEscape */ $block->canEditShippingMethod() ? 'true' : 'false' ?>
            }
        }
    }
</script>
