<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php if ($block->getMenu()): ?>
    <?php $menuClass = $block->getMenu()->getCssClass() ?>
    <div
        class="side-menu"
    >
        <button
            class="
                button
                button--icon
                button--icon-light
                modal-trigger
                side-menu__trigger
            "
            type="button"
            data-modal-trigger="side-menu"
            aria-label="<?= $block->escapeHtmlAttr(__('Open menu')) ?>"
            data-mage-init='{ "modal": {} }'
        >
            <svg
                class="
                    icon
                    side-menu__trigger-icon
                "
                role="presentation"
                focusable="false"
            >
                <title><?= $block->escapeHtml(__('Mobile-menu')) ?></title>
                <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#mobile-menu')) ?>"></use>
            </svg>
        </button>

        <div
            role="dialog"
            aria-hidden="true"
            id="side-menu"
            data-modal="side-menu"
            class="
                modal
                modal--tertiary
                side-menu__modal
            "
        >
            <div
                role="document"
                class="
                    modal__container
                    side-menu__container
                "
                tabindex="0"
            >
                <div
                    class="
                        modal__content
                        side-menu__content
                    "
                >
                    <div
                        class="
                            modal__middle
                            side-menu__content-middle
                        "
                    >
                        <nav
                            id="dropdown-default"
                            class="
                                dropdown-list
                                dropdown-list--with-nested
                                <?= $block->escapeHtmlAttr($menuClass) ?>
                            "
                            data-mage-init='{ "dropdownList": {} }'
                        >
                            <ul
                                class="
                                    dropdown-list__list
                                    <?= $block->escapeHtmlAttr($menuClass) ?>__list
                                "
                            >
                                <?php foreach ($block->getNodes() as $node): ?>
                                    <?php
                                        $childrenLevel = $node->getLevel() + 1;
                                        $children = $this->getNodes($childrenLevel, $node);
                                        $node->setIsParent((bool) $children);
                                        $parentClass = $children ? ' ' . $menuClass . '__item--collapse' : '';
                                        $additionalClasses = $node->getClasses() ? ' ' . $node->getClasses() : '';
                                        $itemClasses = $parentClass . $additionalClasses;
                                    ?>
                                    <li class="<?= $block->escapeHtmlAttr($menuClass) ?>__item<?= $block->escapeHtmlAttr($itemClasses) ?>">
                                        <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                                        <?= /* @noEscape */ $block->renderSubmenu($children, $node, $childrenLevel) ?>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        </nav>
                    </div>

                    <?php if ($contactBar = $this->getChildHtml('mobile-contact-bar-block')): ?>
                        <div
                            class="
                                modal__bottom
                                side-menu__content-bottom
                            "
                        >
                            <div
                                class="
                                    modal__bottom-actions
                                    side-menu__bottom-actions
                                "
                            >
                                <div
                                    class="
                                        modal__bottom-action
                                        side-menu__bottom-action
                                    "
                                >
                                    <div
                                        class="
                                            contact-bar
                                            contact-bar--vertical
                                        "
                                    >
                                        <div class="contact-bar__container">
                                            <?= /* @noEscape */ $contactBar ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <button
                    class="
                        button
                        button--icon
                        button--rotate-icon
                        modal__close-button
                        side-menu__close-button
                    "
                    type="button"
                    aria-label="<?= $block->escapeHtmlAttr(__('Click to close the modal')) ?>"
                >
                    <svg
                        class="
                            icon
                            button__icon
                            modal__close-button-icon
                        "
                        role="img"
                    >
                        <title><?= $block->escapeHtml(__('Close')) ?></title>
                        <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#close')) ?>"></use>
                    </svg>
                    <span class="side-menu__close-button-text">
                        <?= $block->escapeHtml(__('Menu')) ?>
                    </span>
                </button>
            </div>
        </div>
    </div>
<?php endif; ?>
