<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php if ($block->getMenu()): ?>
    <?php $menuClass = $block->getMenu()->getCssClass() ?>
    <div
        class="side-menu"
    >
        <button
            class="
                button
                button--icon
                button--icon-light
                modal-trigger
                side-menu__trigger
            "
            type="button"
            data-modal-trigger="side-menu"
            aria-label="<?= $block->escapeHtmlAttr(__('Open menu')) ?>"
            data-mage-init='{ "modal": {} }'
        >
            <svg
                class="
                    icon
                    side-menu__trigger-icon
                "
                role="presentation"
                focusable="false"
            >
                <title><?= __('Mobile-menu') ?></title>
                <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#mobile-menu') ?>"></use>
            </svg>
        </button>

        <div
            role="dialog"
            aria-hidden="true"
            id="side-menu"
            data-modal="side-menu"
            class="
                modal
                modal--tertiary
                side-menu__modal
            "
        >
            <div
                role="document"
                class="
                    modal__container
                    side-menu__container
                "
                tabindex="0"
            >
                <div
                    class="
                        modal__content
                        side-menu__content
                    "
                >
                    <div
                        class="
                            modal__middle
                            side-menu__content-middle
                        "
                    >
                        <nav
                            id="dropdown-default"
                            class="
                                dropdown-list
                                dropdown-list--with-nested
                                <?= $menuClass ?>
                            "
                            data-mage-init='{ "dropdownList": {} }'
                        >
                            <ul
                                class="
                                    dropdown-list__list
                                    <?= $menuClass ?>__list
                                "
                            >
                                <?php foreach ($block->getNodes() as $node): ?>
                                    <?php
                                        $childrenLevel = $node->getLevel() + 1;
                                        $children = $this->getNodes($childrenLevel, $node);
                                        $node->setIsParent((bool) $children);
                                        $parentClass = $children ? ' ' . $menuClass . '__item--collapse' : '';
                                        $additionalClasses = $node->getClasses() ? ' ' . $node->getClasses() : '';
                                        $itemClasses = $parentClass . $additionalClasses;
                                    ?>
                                    <li class="<?= $menuClass ?>__item<?= $itemClasses ?>">
                                        <?= $block->renderMenuNode($node) ?>
                                        <?= $block->renderSubmenu($children, $node, $childrenLevel) ?>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        </nav>
                    </div>
                </div>
                <button
                    class="
                        button
                        button--icon
                        button--rotate-icon
                        modal__close-button
                        side-menu__close-button
                    "
                    type="button"
                    aria-label="<?= $block->escapeHtmlAttr(__('Click to close the modal')) ?>"
                >
                    <svg
                        class="
                            icon
                            button__icon
                            modal__close-button-icon
                        "
                        role="img"
                    >
                        <title><?= __('Close') ?></title>
                        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#close') ?>"></use>
                    </svg>
                </button>
            </div>
        </div>
    </div>
<?php endif; ?>
