<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="col-xs-12 col-md-6 login__link-column">
        <h3>
            <?= __('New Customers') ?>
        </h3>
        <div class="divider"></div>
        <p class="login__info">
            <?= __('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.') ?>
        </p>
        <a
            href="<?= $block->getCreateAccountUrl() ?>"
            class="button button--link login__button login__button--create-accunt"
            data-testid="create-customer-account-link"
        >
            <?= __('Create an Account') ?>
        </a>
    </div>
<?php endif; ?>
