<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="grid__column grid__column--1-2">
    <h3 class="heading heading--third-level">
        <?= /* @escapeNotVerified */ __('New Customers') ?>
    </h3>
    <p class="paragraph">
        <?= /* @escapeNotVerified */ __('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.') ?>
    </p>
    <a href="<?= /* @escapeNotVerified */ $block->getCreateAccountUrl() ?>"
       class="button button--link"
    >
        <?= /* @escapeNotVerified */ __('Create an Account') ?>
    </a>
</div>
<?php endif; ?>
