<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="grid__column grid__column--1-2 login__link-column">
        <h3>
            <?= /* @escapeNotVerified */ __('New Customers') ?>
        </h3>
        <div class="divider">
            <span class="divider__left"></span>
            <span class="divider__right"></span>
        </div>
        <p class="login__info">
            <?= /* @escapeNotVerified */ __('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.') ?>
        </p>
        <a
            href="<?= /* @escapeNotVerified */ $block->getCreateAccountUrl() ?>"
            class="button button--link login__button login__button--create-accunt"
        >
            <?= /* @escapeNotVerified */ __('Create an Account') ?>
        </a>
    </div>
<?php endif; ?>
