<?php /** @var \Snowdog\SolrNavigation\Block\Filters\ItemList $block */ ?>
<?php foreach ($block->getValues() as $valueId => $valueLabel): ?>
    <li class="active-filters__item list__item">
        <a
            href="<?= $escaper->escapeUrl($block->getCleanUrl($valueId)) ?>"
            class="active-filters__remove"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Disable filter')
                . ': '
                . $block->getLabel()
                . ' - '
                . $valueLabel)
            ?>"
            title="<?= $escaper->escapeHtmlAttr(__('Disable filter')
                . ': '
                . $block->getLabel()
                . ' - '
                . $valueLabel)
            ?>"
        >
            <svg
                class="icon active-filters__remove-icon"
                role="presentation"
                focusable="false"
            >
                <use href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#close')) ?>"></use>
            </svg>
        </a>
        <span class="active-filters__label">
            <?= $block->getLabel() . '&nbsp;:&nbsp;' ?>
        </span>
        <span class="active-filters__value">
            <?= $valueLabel ?>
        </span>
    </li>
<?php endforeach; ?>
