<?php /** @var \Snowdog\SolrNavigation\Block\Filters\VisualSwatch $block */ ?>
<?php foreach ($block->getValues() as $valueId => $valueData): ?>
    <li class="active-filters__item list__item">
        <a
            href="<?= $escaper->escapeUrl($block->getCleanUrl($valueId)) ?>"
            class="active-filters__remove"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Disable filter')
                . ': '
                . $block->getLabel()
                . ' - '
                . $valueData['label'])
            ?>"
            title="<?= $escaper->escapeHtmlAttr(__('Disable filter')
                . ': '
                . $block->getLabel()
                . ' - '
                . $valueData['label'])
            ?>"
        >
            <svg class="icon active-filters__remove-icon" role="img">
                <title><?= __('Close') ?></title>
                <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#close')) ?>"></use>
            </svg>
        </a>
        <span class="active-filters__label">
            <?= $block->getLabel() . '&nbsp;:&nbsp;' ?>
        </span>
        <span class="active-filters__value">
            <?= $valueData['label'] ?>
        </span>
    </li>
<?php endforeach; ?>
