<?php
$collection = $block->getCollection();
$sliderClassName = $block->getSliderClass();
$sliderTitleClassName = $block->getSliderTitleClass();
$bannersArray = [];
$sliderBlockName = $block->getSliderPictureBlock();

$sliderPrefix = 'cb_slider_';
$picturePrefix = 'cb_pic_';
// banners attrubutes to show
$bannersAttributes = ['*'];
?>

<?php foreach ($collection as $content) : ?>
    <?php
    //slider data
    $sliderTitle = $block->escapeHtml($content->getData($sliderPrefix . 'title'));
    $sliderDisplayTitle = $block->escapeHtml($content->getData($sliderPrefix . 'display_title'));
    $sliderDisplayTitle = ($sliderDisplayTitle === 'no') ? false : true;
    $sliderContentBefore =
        $content->getData($sliderPrefix . 'ct_before') ?
        $content->render($sliderPrefix . 'ct_before') :
        false;
    $sliderContentAfter =
        $content->getData($sliderPrefix . 'ct_after') ?
        $content->render($sliderPrefix . 'ct_after') :
        false;

    $sliderBanners = $content->getContentCollection($sliderPrefix . 'banners', $bannersAttributes);

    foreach ($sliderBanners as $index => $banner) {
        $bannersArray[$index]['title'] = $banner->getData($picturePrefix . 'title');
        $bannersArray[$index]['alt'] = $banner->getData($picturePrefix . 'alt');
        $bannersArray[$index]['url'] = $banner->getData($picturePrefix . 'url');
        $bannersArray[$index]['url_target'] = $banner->getData($picturePrefix . 'url_target');
        $bannersArray[$index]['is_main'] = $banner->getData($picturePrefix . 'main_image');
        $bannersArray[$index]['order'] = $banner->getData($picturePrefix . 'order');
        $bannersArray[$index]['default'] = $banner->getFile($picturePrefix . 'default');
        $bannersArray[$index]['max_480'] =
            $banner->getData($picturePrefix . 'max_480') ? $banner->getFile($picturePrefix . 'max_480') : false;
        $bannersArray[$index]['max_768'] =
            $banner->getData($picturePrefix . 'max_768') ? $banner->getFile($picturePrefix . 'max_768') : false;
        $bannersArray[$index]['max_1024'] =
            $banner->getData($picturePrefix . 'max_1024') ? $banner->getFile($picturePrefix . 'max_1024') : false;
        $bannersArray[$index]['max_1328'] =
            $banner->getData($picturePrefix . 'max_1328') ? $banner->getFile($picturePrefix . 'max_1328') : false;
        $bannersArray[$index]['full'] =
            $banner->getData($picturePrefix . 'full') ? $banner->getFile($picturePrefix . 'full') : false;
        //2x
        $bannersArray[$index]['max_480_2x'] =
            $banner->getData($picturePrefix . 'max_480_2x') ? $banner->getFile($picturePrefix . 'max_480_2x') : false;
        $bannersArray[$index]['max_768_2x'] =
            $banner->getData($picturePrefix . 'max_768_2x') ? $banner->getFile($picturePrefix . 'max_768_2x') : false;
        $bannersArray[$index]['max_1024_2x'] =
            $banner->getData($picturePrefix . 'max_1024_2x') ? $banner->getFile($picturePrefix . 'max_1024_2x') : false;
        $bannersArray[$index]['max_1328_2x'] =
            $banner->getData($picturePrefix . 'max_1328_2x') ? $banner->getFile($picturePrefix . 'max_1328_2x') : false;
        $bannersArray[$index]['full_2x'] =
            $banner->getData($picturePrefix . 'full_2x') ? $banner->getFile($picturePrefix . 'full_2x') : false;
    }

    // sorting banners collection by order
    usort($bannersArray, function ($a, $b) {
        return $a['order'] - $b['order'];
    });

    ?>

    <?php if ($sliderDisplayTitle): ?>
        <span
            class="
                slider__heading
                <?= $block->escapeHtmlAttr($sliderTitleClassName) ?>
            "
        >
            <?= $sliderTitle ?>
        </span>
    <?php endif ?>

    <?php if ($sliderContentBefore): ?>
        <div class="slider__before">
            <?= $sliderContentBefore ?>
        </div>
    <?php endif ?>

    <div
        class="<?= $block->escapeHtmlAttr($sliderClassName) ?>"
        data-rewind="true"
        data-enable-mouse-events="true"
        data-mage-init='{ "slider": {} }'
    >
        <div class="slider__navigation">
            <button
                class="
                    button
                    button--icon
                    button--icon-light
                    slider__navigation-icon
                    slider__prev
                "
                type="button"
                aria-label="<?= $block->escapeHtmlAttr(__('Previous slide')) ?>"
            >
                <svg
                    class="
                        icon
                        button__icon
                        slider__icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <title><?= __('Previous slide') ?></title>
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#arrow-left')) ?>"></use>
                </svg>
            </button>

            <button
                class="
                    button
                    button--icon
                    button--icon-light
                    slider__navigation-icon
                    slider__next
                "
                type="button"
                aria-label="<?= $block->escapeHtmlAttr(__('Next slide')) ?>"
            >
                <svg
                    class="
                        icon
                        button__icon
                        slider__icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <title><?= __('Next slide') ?></title>
                    <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#arrow-right')) ?>"></use>
                </svg>
            </button>
        </div>
        <div class="slider__handler">
            <div class="slider__slides">
                <?php if ($bannersArray): ?>
                    <?php foreach ($bannersArray as $banner): ?>
                        <?php
                            $bannerUrl = $block->escapeUrl($banner['url']);
                            $bannerUrlTarget = $block->escapeUrl(($banner['url_target'] == 'blank') ? '_blank' : '_self');
                        ?>
                        <div class="slider__item">
                            <<?= $bannerUrl ? 'a href="' . $bannerUrl . '" target="' . $bannerUrlTarget . '"' : 'div' ?>
                                class="banner"
                            >
                                <?php $block->getChildBlock($sliderBlockName)->setData([
                                    'picture_class' => 'banner__image',
                                    'picture_full_url' => true,
                                    'img_default' => $banner['default'],
                                    'img_480' => $banner['max_480'],
                                    'img_768' => $banner['max_768'],
                                    'img_1024' => $banner['max_1024'],
                                    'img_1328' => $banner['max_1328'],
                                    'img_full' => $banner['full'],
                                    'img_4802x' => $banner['max_480_2x'],
                                    'img_7682x' => $banner['max_768_2x'],
                                    'img_10242x' => $banner['max_1024_2x'],
                                    'img_13282x' => $banner['max_1328_2x'],
                                    'img_full_2x' => $banner['full_2x'],
                                    'picture_alt' => $banner['alt']
                                ]);
                                ?>
                                <?= $block->getChildHtml($sliderBlockName, false); ?>
                            </<?= $bannerUrl ? 'a' : 'div' ?>>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
        <div class="slider__dots"></div>
    </div>

    <?php if ($sliderContentAfter): ?>
        <div class="slider__after">
            <?= $sliderContentAfter ?>
        </div>
    <?php endif ?>
<?php endforeach; ?>
