<?php
/** @var \Magento\Wishlist\Pricing\Render\ConfiguredPriceBox $block */
$schema = ($block->getZone() == 'item_view');
$idSuffix = $block->getIdSuffix() ?: '';
/** @var \Magento\Wishlist\Pricing\ConfiguredPrice\ConfigurableProduct $configuredPrice */
$configuredPrice = $block->getPrice();
$configuredRegularAmountValue = $configuredPrice->getConfiguredRegularAmount()->getValue();
?>
<?php if ($block->hasSpecialPrice()
    && $configuredRegularAmountValue
    && $configuredPrice->getConfiguredAmount()->getValue() !== $configuredRegularAmountValue): ?>
    <span class="price__value price__value--special">
        <?= /* @noEscape */ $block->renderAmount(
            $configuredPrice->getConfiguredAmount(),
            [
                'display_label'     => $block->escapeHtml(__('Special Price')),
                'price_id'          => $block->escapeHtml($block->getPriceId('product-price-' . $idSuffix)),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema,
            ]
        ); ?>
    </span>
    <span class="price__value price__value--old">
        <?= /* @noEscape */ $block->renderAmount(
            $configuredPrice->getConfiguredRegularAmount(),
            [
                'display_label'     => $block->escapeHtml(__('Regular Price')),
                'price_id'          => $block->escapeHtml($block->getPriceId('old-price-' . $idSuffix)),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true,
            ]
        ); ?>
    </span>
<?php else : ?>
    <?php
        $priceLabel = ($block->getPriceLabel() !== null) ? $block->getPriceLabel() : '';
    ?>
    <span class="price__value">
        <?= /* @noEscape */ $block->renderAmount(
            $configuredPrice->getAmount(),
            [
                'display_label'     => $block->escapeHtml($priceLabel),
                'price_id'          => $block->escapeHtml($block->getPriceId('product-price-' . $idSuffix)),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema,
            ]
        ); ?>
    </span>
<?php endif; ?>
