<?php // @codingStandardsIgnoreFile ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
$isTextarea = \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_AREA;
$isTextField = \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_FIELD;

$_textValidate = null;

if ($_option->getIsRequire()) {
    $_textValidate['required'] = true;
}

if ($_option->getMaxCharacters()) {
    $_textValidate['maxlength'] = $_option->getMaxCharacters();
}
?>

<div
    class="
        input
        <?php if ($_option->getType() == $isTextarea): ?>
            textarea
        <?php endif; ?>
        <?= /* @escapeNotVerified */ $class ?>
    "
>
    <label class="label" for="options_<?= /* @escapeNotVerified */ $_option->getId() ?>_text">
        <?= $block->escapeHtml($_option->getTitle()) ?>

        <?= /* @escapeNotVerified */ $block->getFormatedPrice() ?>
    </label>

    <?php if ($_option->getType() == $$isTextField): ?>
        <input
            type="text"
            id="options_<?= /* @escapeNotVerified */ $_option->getId() ?>_text"
            class="input__field"
            <?php if (!empty($_textValidate)) {?>
                data-validate="<?= $block->escapeHtml(json_encode($_textValidate)) ?>"
            <?php } ?>
            name="options[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
            data-selector="options[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
            value="<?= $block->escapeHtml($block->getDefaultValue()) ?>"
        />
    <?php elseif ($_option->getType() == $isTextarea): ?>
        <textarea
            id="options_<?= /* @escapeNotVerified */ $_option->getId() ?>_text"
            class="input__field input__field--textarea"
            <?php if (!empty($_textValidate)) {?>
                data-validate="<?= $block->escapeHtml(json_encode($_textValidate)) ?>"
            <?php } ?>
            name="options[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
            data-selector="options[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
            rows="5"
            cols="25"
        ><?= $block->escapeHtml($block->getDefaultValue()) ?></textarea>
    <?php endif; ?>

    <?php if ($_option->getMaxCharacters()): ?>
        <p>
            <?= /* @escapeNotVerified */ __('Maximum number of characters:') ?>

            <strong>
                <?= /* @escapeNotVerified */ $_option->getMaxCharacters() ?>
            </strong>
        </p>
    <?php endif; ?>
</div>
