<?php // @codingStandardsIgnoreFile ?>
<?php
$_option = $block->getOption();
$_optionId = $_option->getId();
$class = ($_option->getIsRequire()) ? ' required' : '';
$isTextarea = \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_AREA;
$isTextField = \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_FIELD;
$maxCharacters = $_option->getMaxCharacters();

$_textValidate = null;

if ($_option->getIsRequire()) {
    $_textValidate['required'] = true;
}

if ($maxCharacters) {
    $_textValidate['maxlength'] = $maxCharacters;
}
?>

<div
    class="
        input
        field
        <?php if ($_option->getType() == $isTextarea): ?>
            textarea
        <?php endif; ?>
        <?= $class ?>
    "
>
    <label
        class="label"
        for="options_<?= $block->escapeHtmlAttr($_optionId) ?>_text"
    >
        <?= $block->escapeHtml($_option->getTitle()) ?>

        <?= $block->getFormatedPrice() ?>
    </label>

    <div class="control">
        <?php if ($_option->getType() == $isTextField): ?>
            <input
                type="text"
                id="options_<?= $block->escapeHtmlAttr($_optionId) ?>_text"
                class="product-custom-option input__field"
                <?php if (!empty($_textValidate)) {?>
                    data-validate="<?= $block->escapeHtmlAttr(json_encode($_textValidate)) ?>"
                <?php } ?>
                name="options[<?= $block->escapeHtmlAttr($_optionId) ?>]"
                data-selector="options[<?= $block->escapeHtmlAttr($_optionId) ?>]"
                value="<?= $block->escapeHtmlAttr($block->getDefaultValue()) ?>"
            />
        <?php elseif ($_option->getType() == $isTextarea): ?>
            <textarea
                id="options_<?=  $block->escapeHtmlAttr($_optionId) ?>_text"
                class="
                    product-custom-option
                    input__field
                    input__field--textarea
                "
                <?php if (!empty($_textValidate)) {?>
                    data-validate="<?= $block->escapeHtmlAttr(json_encode($_textValidate)) ?>"
                <?php } ?>
                name="options[<?= $block->escapeHtmlAttr($_optionId) ?>]"
                data-selector="options[<?= $block->escapeHtmlAttr($_optionId) ?>]"
                rows="5"
                cols="25"
            ><?= $block->escapeHtml($block->getDefaultValue()) ?></textarea>
        <?php endif; ?>

        <?php if ($maxCharacters): ?>
            <p class="note note_<?= $block->escapeHtmlAttr($_option->getId()) ?>">
                <?= $block->escapeHtml(__('Maximum %1 characters', $maxCharacters)) ?>

                <strong class="character-counter no-display">
                    <?= $maxCharacters ?>
                </strong>
            </p>
        <?php endif; ?>
    </div>

    <?php if ($_option->getMaxCharacters()) :?>
        <script type="text/x-magento-init">
            {
                "[data-selector='options[<?= $block->escapeJs($_option->getId()) ?>]']": {
                    "Magento_Catalog/js/product/remaining-characters": {
                        "maxLength":  "<?= (int)$_option->getMaxCharacters() ?>",
                        "noteSelector": ".note_<?= $block->escapeJs($_option->getId()) ?>",
                        "counterSelector": ".note_<?= $block->escapeJs($_option->getId()) ?> .character-counter"
                    }
                }
            }
        </script>
    <?php endif; ?>
</div>
