<?php
// @codingStandardsIgnoreFile
?>
<?php /** @var $block Magento\Company\Block\Company\Management\Add */ ?>
<form
    class="form form-add-user"
    method="post"
    id="add-user-form"
    action="<?= $block->escapeUrl($block->getUrl('*/customer/manage')) ?>"
    data-mage-init='{ "validation":{} }'
>
    <input type="hidden" name="target_id">
    <input type="hidden" name="customer_id">
    <fieldset class="fieldset info">
        <div class="field input jobtitle required">
            <label class="label" for="jobtitle">
                <?= $block->escapeHtml(__('Job Title')) ?>
            </label>
            <input
                type="text"
                name="extension_attributes[company_attributes][job_title]"
                id="jobtitle"
                value=""
                title="<?= $block->escapeHtml(__('Job Title')) ?>"
                class="input-text input__field"
                data-validate="{ required: true }"
            >
        </div>
        <div class="field select role required">
            <label class="label" for="jobtitle">
                <?= $block->escapeHtml(__('User Role')) ?>
            </label>
            <select
                data-role="role-select"
                name="role"
                id="role"
                class="select__field select__field--native"
            >
                <?php foreach ($block->getRoles() as $role): ?>
                    <option value="<?= $block->escapeHtml($role->getId()) ?>">
                        <?= $block->escapeHtml($role->getRoleName()) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
        <div class="field input firstname required">
            <label class="label" for="firstname">
                <?= $block->escapeHtml(__('First Name')) ?>
            </label>
            <input
                type="text"
                name="firstname"
                id="firstname"
                value=""
                title="<?= $block->escapeHtml(__('First Name')) ?>"
                class="input-text input__field"
                data-validate="{ required: true }"
            >
        </div>
        <div class="field input lastname required">
            <label class="label" for="lastname">
                <?= $block->escapeHtml(__('Last Name')) ?>
            </label>
            <input
                type="text"
                name="lastname"
                id="lastname"
                value=""
                title="<?= $block->escapeHtml(__('Last Name')) ?>"
                class="input-text input__field"
                data-validate="{ required: true }"
            >
        </div>
        <div class="field input email required">
            <label class="label" for="add-user-email">
                <?= $block->escapeHtml(__('Email')) ?>
            </label>
            <input
                type="email"
                name="email"
                id="add-user-email"
                value=""
                title="<?= $block->escapeHtml(__('Email')) ?>"
                data-role="email"
                data-url-validate="<?= $block->escapeUrl($block->getUrl('*/customer/check')) ?>"
                class="input-text input__field"
                data-validate="{ required: true, 'validate-email': true }"
            >
        </div>
        <div class="field input telephone required">
            <label class="label" for="telephone">
                <?= $block->escapeHtml(__('Phone Number')) ?>
            </label>
            <input
                type="text"
                name="extension_attributes[company_attributes][telephone]"
                id="telephone"
                value=""
                title="<?= $block->escapeHtml(__('Phone Number')) ?>"
                class="input-text input__field"
                data-validate="{ required:true }"
            >
        </div>
        <div class="field status select">
            <label class="label" for="status">
                <?= $block->escapeHtml(__('Status')) ?>
            </label>
            <select
                data-role="status-select"
                name="extension_attributes[company_attributes][status]"
                id="status"
                class="select__field select__field--native"
            >
                <option value="1">
                    <?= $block->escapeHtml(__('Active')) ?>
                </option>
                <option value="0">
                    <?= $block->escapeHtml(__('Inactive')) ?>
                </option>
            </select>
        </div>
    </fieldset>
    <div
        id="additional_fields_create"
        data-role="create-additional-fields"
        class="_hidden additional-fields"
    >
        <?= $block->getChildHtml('customer_form_user_attributes_create') ?>
    </div>
    <div
        id="additional_fields_edit"
        data-role="edit-additional-fields"
        class="_hidden additional-fields"
    >
        <?= $block->getChildHtml('customer_form_user_attributes_edit') ?>
    </div>
</form>
