<?php /** @var $block Magento\Company\Block\Company\Management\Add */ ?>
<form
    class="
        dashboard-form
        form
        form-add-user
    "
    method="post"
    id="add-user-form"
    action="<?= $block->escapeUrl($block->getUrl('*/customer/manage')) ?>"
    data-mage-init='{"validation":{}}'
>
    <input
        type="hidden"
        name="target_id"
    />
    <input
        type="hidden"
        name="customer_id"
    />
    <fieldset class="fieldset info">
        <legend
            class="
                fieldset__legend
                fieldset__legend--hidden
            "
        >
            <?= $block->escapeHtml(__('User Information')) ?>
        </legend>
        <div
            class="
                input
                jobtitle
                required
            "
        >
            <label
                class="label"
                for="jobtitle"
            >
                <?= $block->escapeHtml(__('Job Title')) ?>
            </label>
            <input
                type="text"
                name="extension_attributes[company_attributes][job_title]"
                id="jobtitle"
                value=""
                title="<?= $block->escapeHtmlAttr(__('Job Title')) ?>"
                class="input__field"
            />
        </div>
        <div
            class="
                input
                role
                required
            "
        >
            <label
                class="label"
                for="jobtitle"
            >
                <?= $block->escapeHtml(__('User Role')) ?>
            </label>
            <div
                class="
                    control
                    select
                    select--native
                "
            >
                <select
                    data-role="role-select"
                    name="role"
                    id="role"
                    class="select__field"
                >
                    <?php foreach ($block->getRoles() as $role): ?>
                        <option value="<?= (int) $role->getId() ?>">
                            <?= $block->escapeHtml($role->getRoleName()) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div
            class="
                input
                firstname
                required
            "
        >
            <label
                class="label"
                for="firstname"
            >
                <?= $block->escapeHtml(__('First Name')) ?>
            </label>
            <input
                type="text"
                name="firstname"
                id="firstname"
                value=""
                title="<?= $block->escapeHtmlAttr(__('First Name')) ?>"
                class="input__field"
                data-validate="{required:true}"
            />
        </div>
        <div
            class="
                input
                lastname
                required
            "
        >
            <label
                class="label"
                for="lastname"
            >
                <?= $block->escapeHtml(__('Last Name')) ?>
            </label>
            <input
                type="text"
                name="lastname"
                id="lastname"
                value=""
                title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>"
                class="input__field"
                data-validate="{required:true}"
            />
        </div>
        <div
            class="
                input
                email
                required
            "
        >
            <label
                class="label"
                for="email"
            >
                <?= $block->escapeHtml(__('Email')) ?>
            </label>
            <input
                type="email"
                name="email"
                id="email"
                value=""
                title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                data-role="email"
                data-url-validate="<?= $block->escapeUrl($block->getUrl('*/customer/check')) ?>"
                class="input__field"
                data-validate="{required:true, 'validate-email':true}"
            />
        </div>
        <div
            class="
                input
                telephone
                required
            "
        >
            <label
                class="label"
                for="telephone"
            >
                <?= $block->escapeHtml(__('Phone Number')) ?>
            </label>
            <input
                type="text"
                name="extension_attributes[company_attributes][telephone]"
                id="telephone"
                value=""
                title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                class="input__field"
                data-validate="{required:true}"
            />
        </div>
        <div class="input status">
            <label
                class="label"
                for="status"
            >
                <?= $block->escapeHtml(__('Status')) ?>
            </label>
            <div
                class="
                    control
                    select
                    select--native
                "
            >
                <select
                    data-role="status-select"
                    name="extension_attributes[company_attributes][status]"
                    id="status"
                    class="select__field"
                >
                    <option value="1"><?= $block->escapeHtml(__('Active')) ?></option>
                    <option value="0"><?= $block->escapeHtml(__('Inactive')) ?></option>
                </select>
            </div>
        </div>
    </fieldset>
    <div
        id="additional_fields_create"
        data-role="create-additional-fields"
        class="_hidden additional-fields"
    >
        <?= $block->getChildHtml('customer_form_user_attributes_create') ?>
    </div>
    <div
        id="additional_fields_edit"
        data-role="edit-additional-fields"
        class="_hidden additional-fields"
    >
        <?= $block->getChildHtml('customer_form_user_attributes_edit') ?>
    </div>
</form>
