<div class="row">
    <div class="col-xs-12 col-md-6">
        <form
            class="form form-orders-search"
            id="oar-widget-orders-and-returns-form"
            data-mage-init='{
                "ordersReturns":{},
                "validation":{}
            }'
            action="<?= $block->escapeUrl($block->getActionUrl()) ?>"
            method="post"
            name="guest_post"
        >
            <fieldset class="fieldset">
                <legend class="fieldset__legend fieldset__legend--hidden">
                    <?= $block->escapeHtml(__('Order Information')) ?>
                </legend>
                <div class="input required">
                    <label
                        class="label"
                        for="oar-order-id"
                    >
                        <?= $block->escapeHtml(__('Order ID')) ?>
                    </label>

                    <input
                        type="text"
                        class="input__field"
                        id="oar-order-id"
                        name="oar_order_id"
                        data-validate="{required:true}"
                    />
                </div>
                <div class="input required">
                    <label
                        class="label"
                        for="oar-billing-lastname"
                    >
                        <?= $block->escapeHtml(__('Billing Last Name')) ?>
                    </label>

                    <input
                        type="text"
                        class="input__field"
                        id="oar-billing-lastname"
                        name="oar_billing_lastname"
                        data-validate="{required:true}"
                    />
                </div>
                <div
                    class="
                        select
                        select--native
                        required
                    "
                >
                    <label
                        class="label"
                        for="quick-search-type-id"
                    >
                        <?= $block->escapeHtml(__('Find Order By')) ?>
                    </label>

                    <select
                        name="oar_type"
                        id="quick-search-type-id"
                        class="select__field"
                        data-mage-init='{ "select": {}}'
                    >
                        <option value="email">
                            <?= $block->escapeHtml(__('Email')) ?>
                        </option>
                        <option value="zip">
                            <?= $block->escapeHtml(__('ZIP Code')) ?>
                        </option>
                    </select>
                </div>
                <div
                    id="oar-email"
                    class="input required"
                >
                    <label
                        class="label"
                        for="oar_email"
                    >
                        <?= $block->escapeHtml(__('Email')) ?>
                    </label>

                    <input
                        type="email"
                        class="input__field"
                        id="oar_email"
                        name="oar_email"
                        data-validate="{
                            required:true,
                            'validate-email':true
                        }"
                    />
                </div>
                <div
                    id="oar-zip"
                    class="
                        input
                        required
                        display-none
                    "
                >
                    <label
                        class="label"
                        for="oar_zip"
                    >
                        <?= $block->escapeHtml(__('Billing ZIP Code')) ?>
                    </label>

                    <input
                        type="text"
                        class="input__field"
                        id="oar_zip"
                        name="oar_zip"
                        data-validate="{required:true}"
                    />
                </div>
            </fieldset>
            <div class="actions-group">
                <div class="actions-group__handler">
                    <button
                        type="submit"
                        title="<?= $block->escapeHtml(__('Continue')) ?>"
                        class="
                            actions-group__button
                            button
                            action
                            submit
                            primary
                        "
                    >
                        <?= $block->escapeHtml(__('Continue')) ?>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
