<?php
/* @var $block \Magento\Catalog\Block\Product\View\AbstractView */
$_product = $block->getProduct();
$_associatedProducts = $block->getAssociatedProducts();
$_hasAssociatedProducts = count($_associatedProducts) > 0;
?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable() && $_hasAssociatedProducts): ?>
        <div
            class="product-view__stock-status"
            title="<?= $block->escapeHtmlAttr(__('Availability')) ?>"
        >
            <?= $block->escapeHtml(__('In stock')) ?>
        </div>
    <?php else: ?>
        <div
            class="
                product-view__stock-status
                product-view__stock-status--alert
            "
            title="<?= $block->escapeHtmlAttr(__('Availability')) ?>"
        >
            <?= $block->escapeHtml(__('Out of stock')) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
