<?php $block->setPreconfiguredValue(); ?>
<?php $_product               = $block->getProduct(); ?>
<?php $_associatedProducts    = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>

<div id="validation-message-box"></div>
<table
    class="table product-view__grouped-table"
    tabindex="0"
    role="table"
    id="super-product-table"
    data-mage-init='{ "Magento_GroupedProduct/js/product-ids-resolver": {} }'
>
    <caption class="table__caption">
        <?= $block->escapeHtml(__('Grouped product items')) ?>
    </caption>
    <thead>
        <tr role="row">
            <th scope="col" role="columnheader">
                <?= $block->escapeHtml(__('Product Name')) ?>
            </th>
            <?php if ($_product->isSaleable()): ?>
                <th
                    class="product-view__grouped-col-qty"
                    scope="col"
                    role="columnheader"
                >
                    <?= $block->escapeHtml(__('Qty')) ?>
                </th>
            <?php endif; ?>
        </tr>
    </thead>
    <?php if ($_hasAssociatedProducts): ?>
        <tbody>
            <?php foreach ($_associatedProducts as $_item): ?>
                <tr role="row">
                    <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>:" role="gridcell">
                        <span class="product-view__grouped-product-name">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </span>
                        <span>
                            <?php if ($block->getCanShowProductPrice($_product)): ?>
                                <?php if ($block->getCanShowProductPrice($_item)): ?>
                                    <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </span>
                    </td>
                    <?php if ($_product->isSaleable()): ?>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>:" role="gridcell">
                            <?php if ($_item->isSaleable()) : ?>
                                <div class="input product-view__grouped-qty">
                                    <label class="label label--hidden" for="field-id-1">
                                        <? $block->escapeHtml(__('Qty')) ?>
                                    </label>
                                    <input
                                        class="input__field input-text qty"
                                        id="field-id-1"
                                        name="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                                        type="number"
                                        min="0"
                                        value="<?= $block->escapeHtmlAttr($_item->getQty()) * 1 ?>"
                                        data-selector="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                                        data-validate="{'validate-grouped-qty':'#super-product-table'}"
                                        data-errors-message-box="#validation-message-box"
                                    >
                                </div>
                            <?php else: ?>
                                <div
                                    class="
                                        product-view__stock-status
                                        product-view__stock-status--alert
                                    "
                                >
                                    <?= $block->escapeHtml(__('Out of stock')) ?>
                                </div>
                            <?php endif; ?>
                        </td>
                    <?php endif; ?>
                </tr>
                <?php if ($block->getCanShowProductPrice($_product)
                    && $block->getCanShowProductPrice($_item)
                    && trim($block->getProductPriceHtml(
                        $_item,
                        \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                    ))
                ): ?>
                    <tr role="row">
                        <td colspan="2">
                            <?= $block->getProductPriceHtml(
                                $_item,
                                \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                            ) ?>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </tbody>
    <?php else: ?>
        <tbody>
            <tr>
                <td colspan="2">
                    <?= $block->escapeHtml(__('No options of this product are available.')) ?>
                </td>
            </tr>
        </tbody>
    <?php endif; ?>
</table>
