<script type="text/javascript">
function addMarginForFooter() {
  let addToCartSticky = document.querySelector('[data-aos-id="addtocart-sticky"]');

  if (addToCartSticky) {
    let footer = document.querySelector('footer');
    footer.style.marginBottom = addToCartSticky.offsetHeight + 'px';
  }
}

require([
  'aos'
], function(aos) {
  aos.init();
  addMarginForFooter();

  window.addEventListener('resize', function () {
    addMarginForFooter();
  });

  window.addEventListener('onload', function () {
    addMarginForFooter();
  });
});
</script>
