<script type="text/javascript">
    require(['lazysizes', 'picturefill', 'closestPolyfill']);
    require([
        'svg4everybody'
    ],
    function() {
        svg4everybody();

        // polyfill for nodeList.forEach method
        NodeList.prototype.forEach = function(callback) {
            for (var i = 0; i < this.length; i++) {
                callback.apply(this, this[i], i, this);
            }
        }
    });
</script>
