<div>
    <div
        class="
            product
            name
            product-item-name
        "
    >
        <a
            href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
            class="actions-group__link"
        >
            <?= $block->escapeHtml($block->getProductName()) ?>
        </a>
    </div>
    <?php if ($_options = $block->getOptionList()): ?>
        <dl
            class="
                list
                list--description
                item-options
            "
        >
            <?php foreach ($_options as $_option): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dt class="list__label">
                    <?= $block->escapeHtml($_option['label']) ?>
                </dt>
                <dd
                    class="
                        list__value
                        <?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper': '') ?>
                    "
                >
                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span']) ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <dl
                            class="
                                item
                                options
                                tooltip
                                content
                            "
                        >
                            <dt class="list__label">
                                <?= $block->escapeHtml($_option['label']) ?>
                            </dt>
                            <dd class="list__value">
                                <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['span']) ?>
                            </dd>
                        </dl>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php if ($addtInfoBlock = $block->getProductAdditionalInformationBlock()): ?>
        <?= $addtInfoBlock->setItem($block->getItem())->toHtml() ?>
    <?php endif; ?>
</div>
