<?php
/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>

<a class="top-bar__links-item"
   <?= /* @escapeNotVerified */ $block->getLinkAttributes(); ?>
   <?= /* @escapeNotVerified */ $dataPostParam; ?>
>
    <svg title="signin" class="top-bar__links-icon">
        <use xlink:href="<?= $block->getViewFileUrl('/images/icons-sprite.svg#signin'); ?>"></use>
    </svg>
    <?= $block->escapeHtml($block->getLabel()) ?>
</a>
