<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward\History
 */
?>
<div class="dashboard-table dashboard__item">
    <div class="dashboard-table__header">
        <h5 class="heading heading--fifth-level dashboard-table__title">
            <?= /* @escapeNotVerified */ __('Balance History'); ?>
        </h5>
    </div>

    <?php if ($history = $block->getHistory()):?>
        <div class="dashboard-table__content">
            <?= /* @escapeNotVerified */ $block->getChildHtml('pager') ?>

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" class="col balance">
                            <?= /* @escapeNotVerified */ __('Balance'); ?>
                        </th>

                        <th scope="col" class="col amount">
                            <?= /* @escapeNotVerified */ __('Amount'); ?>
                        </th>

                        <th scope="col" class="col points">
                            <?= /* @escapeNotVerified */ __('Points'); ?>
                        </th>

                        <th scope="col" class="col reason">
                            <?= /* @escapeNotVerified */ __('Reason'); ?>
                        </th>

                        <th scope="col" class="col date">
                            <?= /* @escapeNotVerified */ __('Date'); ?>
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($history as $item): ?>
                        <tr>
                            <td data-th="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Balance')); ?>" classs="col balance">
                                <?= /* @escapeNotVerified */ $block->getPointsBalance($item) ?>
                            </td>

                            <td data-th="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Amount')); ?>" classs="col amount">
                                <?= /* @escapeNotVerified */ $block->getCurrencyBalance($item) ?>
                            </td>

                            <td data-th="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Points')); ?>" classs="col points">
                                <?= /* @escapeNotVerified */ $block->getPointsDelta($item) ?>
                            </td>

                            <td data-th="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Reason')); ?>" classs="col reason">
                                <?= /* @escapeNotVerified */ $block->escapeHtml($block->getMessage($item)) ?>
                                
                                <?php if ($explanation = $block->getExplanation($item)): ?>
                                    <small>
                                        <?= /* @escapeNotVerified */ $block->escapeHtml($explanation); ?>
                                    </small>
                                <?php endif;?>
                            </td>

                            <td data-th="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Date')); ?>" classs="col date">
                                <span class="datetime">
                                    <?= /* @escapeNotVerified */ $block->getDate($item) ?>
                                </span>

                                <?php if ($expirationDate = $block->getExpirationDate($item)): ?>
                                    <small>
                                        <?= /* @escapeNotVerified */ __('Expires on %1', $expirationDate); ?>
                                    </small>
                                <?php endif;?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            <?= /* @escapeNotVerified */ $block->getChildHtml('pager') ?>
        </div>
    <?php else:?>
        <div class="message info empty">
            <?= /* @escapeNotVerified */ __('There is no balance history.') ?>
        </div>
    <?php endif;?>
</div>
