<?php
// phpcs:disable Magento2.Files.LineLength
?>
<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward\History
 * @var \Magento\Reward\Block\Customer\Reward\History $block
 */
?>
<div class="block block-reward-history">
    <div class="block-content">
        <?php if ($history = $block->getHistory()) : ?>
            <?= $block->getChildHtml('pager') ?>
            <div class="table-wrapper reward-history">
            <table
                class="data table table-reward-history"
                tabindex="0"
                role="table"
            >
                <caption class="table__caption">
                    <?= $block->escapeHtml(__('Balance History')); ?>
                </caption>
                <thead>
                    <tr role="row">
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Balance')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Amount')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Points')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Reason')) ?>
                        </th>
                        <th
                            scope="col"
                            role="columnheader"
                        >
                            <?= $block->escapeHtml(__('Date')) ?>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($history as $item) : ?>
                    <tr role="row">
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Balance')) ?>"
                            role="gridcell"
                        >
                            <?= $block->escapeHtml($block->getPointsBalance($item)) ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Amount')) ?>"
                            role="gridcell"
                        >
                            <?= $block->escapeHtml($block->getCurrencyBalance($item), ['span']) ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Points')) ?>"
                            role="gridcell"
                        >
                            <?= $block->escapeHtml($block->getPointsDelta($item)) ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Reason')) ?>"
                            role="gridcell"
                        >
                            <?= $block->escapeHtml($block->getMessage($item)) ?>
                            <?php if ($explanation = $block->getExplanation($item)) : ?>
                                <small>
                                    <?= $block->escapeHtml($explanation) ?>
                                </small>
                            <?php endif; ?>
                        </td>
                        <td
                            data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>"
                            role="gridcell"
                        >
                            <span class="datetime">
                                <?= $block->escapeHtml($block->getDate($item)) ?>
                            </span>
                            <?php if ($expirationDate = $block->getExpirationDate($item)) : ?>
                                <span class="datetime">
                                    <?= $block->escapeHtml(__('Expires on %1', $expirationDate)) ?>
                                </span>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
            <?= $block->getChildHtml('pager') ?>
        <?php else : ?>
            <div class="message">
                <?= $block->escapeHtml(__('There is no balance history.')) ?>
            </div>
        <?php endif;?>
    </div>
</div>
