<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward\Settings
 */
?>
<form class="form reward-settings" 
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('reward/customer/saveSettings') ?>" 
      method="post" 
      id="form-validate"
>
    <?php echo $block->getBlockHtml('formkey')?>

    <h5 class="heading heading--fifth-level dashboard-form__title">
        <?php /* @escapeNotVerified */ echo __('Email Notification Settings'); ?>
    </h5>

    <div class="dashboard-form__divider">
        <div class="checkbox dashboard-form__divider choice">
            <input type="checkbox" 
                   name="subscribe_updates" 
                   id="subscribe_updates" 
                   value="1" 
                   class="checkbox__field"
                   title="<?php /* @escapeNotVerified */ echo __('Subscribe for Balance Updates') ?>"
                   <?php if ($block->isSubscribedForUpdates()): ?> 
                        checked="checked"
                   <?php endif; ?> 
            />
            
            <svg class="checkbox__icon">
                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
            </svg>

            <label class="checkbox__label" for="subscribe_updates">
                <?php /* @escapeNotVerified */ echo __('Subscribe for Balance Updates') ?>
            </label>
        </div>

        <div class="checkbox dashboard-form__divider choice">
            <input type="checkbox" 
                   name="subscribe_warnings" 
                   id="subscribe_warnings" 
                   class="checkbox__field"
                   value="1"<?php if ($block->isSubscribedForWarnings()): ?> 
                   checked="checked"<?php endif; ?>
            />

            <svg class="checkbox__icon">
                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="<?= $block->getViewFileUrl('images/icons-sprite.svg#checked'); ?>"></use>
            </svg>

            <label class="checkbox__label" for="subscribe_warnings">
                <?php /* @escapeNotVerified */ echo __('Subscribe for Points Expiration Notifications') ?>
            </label>
        </div>
    </div>

    <div class="action dashboard__item">
        <div class="action__handler">
            <button type="submit" 
                    class="button action__button save primary" 
                    title="<?php /* @escapeNotVerified */ echo __('Save Subscription Settings') ?>"
            >
                <?php /* @escapeNotVerified */ echo __('Save Subscription Settings') ?>
            </button>
        </div>
    </div>
</form>
