<?php
// phpcs:disable Magento2.Files.LineLength
?>

<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward\Subscription
 * @var \Magento\Reward\Block\Customer\Reward\Subscription $block
 */
?>
<form
    class="
        dashboard-form
        form
        reward-settings
    "
    action="<?= $block->escapeUrl($block->getUrl('magento_reward/customer/saveSettings')) ?>"
    method="post"
    id="form-validate"
>
    <?= $block->getBlockHtml('formkey') ?>
    <h2 class="dashboard-form__title margin-bottom-sm">
        <?= $block->escapeHtml(__('Email Notification Settings')) ?>
    </h2>
    <fieldset class="fieldset">
        <div class="checkbox">
            <input
                class="checkbox__field"
                type="checkbox"
                name="subscribe_updates"
                id="subscribe_updates"
                value="1"
                title="<?= $block->escapeHtmlAttr(__('Subscribe for Balance Updates')) ?>"
                <?php if ($block->isSubscribedForUpdates()) : ?>
                    checked="checked"
                <?php endif; ?>
            />
            <svg class="
                checkbox__icon
                checkbox__icon--checked
            "
                 role="presentation"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
            </svg>
            <svg
                class="
                    checkbox__icon
                    checkbox__icon--unchecked
                "
                role="presentation"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
            </svg>
            <label
                class="
                    checkbox__label
                    label
                "
                for="subscribe_updates"
            >
                <span class="checkbox__text">
                    <?= $block->escapeHtml(__('Subscribe for Balance Updates')) ?>
                </span>
            </label>
        </div>
        <div class="checkbox margin-bottom-s">
            <input
                class="checkbox__field"
                type="checkbox"
                name="subscribe_warnings"
                id="subscribe_warnings"
                value="1"
                <?php if ($block->isSubscribedForWarnings()) : ?>
                    checked="checked"
                <?php endif; ?>
            />
            <svg
                class="
                    checkbox__icon
                    checkbox__icon--checked
                "
                role="presentation"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#checked')) ?>"></use>
            </svg>
            <svg
                class="
                    checkbox__icon
                    checkbox__icon--unchecked
                "
                role="presentation"
            >
                <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#unchecked')) ?>"></use>
            </svg>
            <label
                class="
                    checkbox__label
                    label
                "
                for="subscribe_warnings"
            >
                <span class="checkbox__text">
                    <?= $block->escapeHtml(__('Subscribe for Points Expiration Notifications')) ?>
                </span>
            </label>
        </div>
    </fieldset>
    <div class="actions-group margin-bottom-sm">
        <div class="actions-group__handler">
            <button
                type="submit"
                class="button"
                title="<?= $block->escapeHtmlAttr(__('Save Subscription Settings')) ?>"
                aria-label="button"
            >
                <?= $block->escapeHtml(__('Save Subscription Settings')) ?>
            </button>
        </div>
    </div>
</form>
