<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

 /** @var \Magento\CatalogSearch\Helper\Data $helper */
$helper = $this->helper(Magento\CatalogSearch\Helper\Data::class);
?>
<div class="search__advanced">
    <a class="action advanced"
       href="<?= $helper->getAdvancedSearchUrl(); ?>"
       data-action="advanced-search"
    >
        <?= $block->escapeHtml(__('Advanced Search')); ?>
    </a>
</div>
