<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>

<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong>
            <?php echo $block->escapeHtml($_item->getName()) ?>
        </strong>

        <?php if ($_options = $block->getItemOptions()): ?>
            <ul class="list">
                <?php foreach ($_options as $_option) : ?>
                    <li>
                        <?php echo $block->escapeHtml($_option['label']).': ' ?>

                        <?php if (!$block->getPrintStatus()): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>

                            <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'].': ' ?>

                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <strong>
                                    <?php echo $block->escapeHtml($_option['label']).' ' ?>

                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                </strong>
                            <?php endif; ?>
                        <?php else: ?>
                            <strong>
                                <?php echo $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?>
                            <strong>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>

        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>

        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>

    <td class="sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>">
        <?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?>
    </td>

    <td class="price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>

    <td class="qty" data-th="<?php echo $block->escapeHtml(__('Qty Invoiced')); ?>">
        <?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?>
    </td>

    <td class="subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
