<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>

<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="name" data-th="<?= $escaper->escapeHtmlAttr(__('Product Name')); ?>">
        <strong>
            <?= $escaper->escapeHtml($_item->getName()) ?>
        </strong>

        <?php if ($_options = $block->getItemOptions()): ?>
            <ul class="list">
                <?php foreach ($_options as $_option) : ?>
                    <li>
                        <?= $escaper->escapeHtml($_option['label']).': ' ?>

                        <?php if (!$block->getPrintStatus()): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>

                            <?= $escaper->escapeHtml($_formatedOptionValue['value'], ['a', 'img']) . ': ' ?>

                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <strong>
                                    <?= $escaper->escapeHtml($_option['label']).' ' ?>

                                    <?= $escaper->escapeHtml($_formatedOptionValue['full_view']) ?>
                                </strong>
                            <?php endif; ?>
                        <?php else: ?>
                            <strong>
                                <?= $escaper->escapeHtml($_option['print_value'] ?? $_option['value']) ?>
                            <strong>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>

        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>

        <?= $escaper->escapeHtml($_item->getDescription()) ?>
    </td>

    <td class="sku" data-th="<?= $escaper->escapeHtmlAttr(__('SKU')); ?>">
        <?= /* @noEscape */ $block->prepareSku($block->getSku()) ?>
    </td>

    <td class="price" data-th="<?= $escaper->escapeHtmlAttr(__('Price')); ?>">
        <?= /* @noEscape */ $block->getItemPriceHtml(); ?>
    </td>

    <td class="qty" data-th="<?= $escaper->escapeHtmlAttr(__('Qty Invoiced')); ?>">
        <?= (float) $_item->getQty() ?>
    </td>

    <td class="subtotal" data-th="<?= $escaper->escapeHtmlAttr(__('Subtotal')); ?>">
        <?= /* @noEscape */ $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
