<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<div class="price">
    <?php if ($block->hasSpecialPrice()): ?>
        <span class="price__value price__value--old">
            <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => false,
                'skip_adjustments'  => true
            ]); ?>
        </span>
        <span class="price__value price__value--special">
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => false,
                'schema' => $schema
            ]); ?>
        </span>
    <?php else: ?>
        <span class="price__value">
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => false,
                'schema' => $schema
            ]); ?>
        </span>
    <?php endif; ?>
</div>
<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()): ?>
        <a
            href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>"
            class="minimal-price-link"
        >
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else: ?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif; ?>
<?php endif; ?>
